### ISSUE TITLE
AWS credentials ending in "=" don't work

### ISSUE THREAD

**Issue by vsivsi** [restic/restic#970] opened 2017-05-25 02:16 UTC
## Output of `restic version`

restic 0.5.0

## How did you start restic exactly? (Include the complete command line)

restic init

The problem is when the AWS credentials (in this case from env vars), end in the character "="

Minio will automatically generate such credentials...

## What backend/server/service did you use?

S3 / minio 

## Expected behavior

Restic will work with an S3 backend that requires credentials ending in "="

## Actual behavior
```
restic init

create backend at s3:http://192.168.100.38:9002/backups failed: client.BucketExists: Missing fields in request.
```

## Steps to reproduce the behavior

Use minio to bring up a server setting either the access key or secret key to a string ending in "=".

Attempt to use restic to init a repo using these credentials.  Note, `mc` has no difficulty using such credentials to access the same server, and minio will randomly generate such credentials.

## Do you have any idea what may have caused this?

My guess is the `=` isn't being properly escaped in some URI being used to access the S3 backend.

**Comment by fd0** [comment] 2017-05-25 07:38
Huh, interesting! I'll look into it, thanks for the report!

**Comment by fd0** [comment] 2017-05-25 07:50
I'm unable to reproduce this issue for the `AWS_SECRET_ACCESS_KEY` (works fine with an equals sign at the end), but setting a `AWS_ACCESS_KEY_ID` with an equals sign at the end provokes the error.

**Comment by fd0** [comment] 2017-05-25 07:58
Something is strange here.  I've verified that restic just passes the values in the environment variables to the minio-go s3 library, so it's not a bug in restic. 

Where did you get the credentials? As far as I know, `AWS_ACCESS_KEY_ID` should be an alphanumeric string, so it should not contain equals at all. The `AWS_SECRET_ACCESS_KEY` is base64 encoded, so for certain lengths there will be one or two equals signs at the end of the string. My minio binary here will only generate secrets with a length that does not result in an equals sign when base64 encoded. And I've verified (by manually configuring a minio server with a secret of `DiU8zVwhiXowkApWRvdQhd7bQeUk+CxBgngnATM=`, that works just fine.

So I'm a bit at loss what's happening here, but I suspect that it is not a bug (neither in restic nor in minio-go).

@harshavardhana Could you comment on the format of the `AWS_ACCESS_KEY_ID` maybe? Thanks!

**Comment by vsivsi** [comment] 2017-05-25 08:00
I may have been mistaken about `AWS_SECRET_ACCESS_KEY`, thought I checked that one too.

I lost about 2 hours today to this... Could not figure out what had changed that broke restic. The ransom credentials generated by minio each had an `=` at the end.

**Comment by fd0** [comment] 2017-05-25 08:17
I'm sorry that you lost so much time. I'm not sure how you ended up with credentials containing `=` at all:

For the `AWS_ACCESS_KEY_ID`, minio will generate a string of 20 random characters from the set `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ`, so that should never contain `=`: https://github.com/minio/minio/blob/master/cmd/credential.go#L32 https://github.com/minio/minio/blob/master/cmd/credential.go#L105-L110

For the `AWS_SECRET_ACCESS_KEY`, the minio server generates 40 random bytes, encodes them with base64, and takes the first 40 bytes. Since `=` is only valid at the end of a base64 encoded string, there cannot be a `=` in that string either: https://github.com/minio/minio/blob/master/cmd/credential.go#L117

Since 0.5.0 and master we've upgraded the minio-go library, so it may well be that there was a bug in the library. Using 0.5.0 with a minio server is very slow, so there may be something strange going on.

Could you test the master branch?

**Comment by vsivsi** [comment] 2017-05-25 08:36
I'm no longer sure how I ended up with those credentials either.  I plucked them off the screen that minio dumps to stdout when it starts. But that was during a test that I discarded soon after I figured out what was going on and submitted this issue.  

I'm using the latest minio.  I'm working off a fork of restic, partially because of the slowness issue, partially because my project requires the S3 / filesystem path layout parity that we've discussed (which I have implemented), and partially because I require a build of restic with cgo enabled, since the go runtime without cgo does funny things with DNS resolution that make using local DNS lookups unusable (say by registering redundant minio servers with Consul, and using an address like `minio.service.consul` to load balance). See here if you are curious about that... https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by vsivsi** [comment] 2017-05-25 08:37
Just to add, I did test with official restic 0.5.0 (and not just my fork) before submitting this issue. Unfortunately I'm on deadline and don't have much more time to help with this.

**Comment by fd0** [comment] 2017-05-25 08:52
Ok, thanks for taking the time to report this. We'll wait and see what @harshavardhana thinks.

By the way: I've already implemented the default repository layout for s3 in the master branch, you can use it by setting `-o s3.layout=default` when creating a new repository. Afterwards you don't need that parameter any more, restic will auto detect the layout used for the s3 repository and do the right thing.

For cgo, you just need to change this one line in `build.go`: https://github.com/restic/restic/blob/master/build.go#L198

**Comment by fd0** [comment] 2017-05-25 13:51
There's the new release: https://github.com/restic/restic/releases/tag/v0.6.0-rc.1

**Comment by harshavardhana** [comment] 2017-05-25 14:54
@vsivsi I am pretty you must have interchanged the keys.

AccessKey can never be alphanumeric unless you manually edited it.

Will test by manually setting it and see what happens.

**Comment by vsivsi** [comment] 2017-05-25 17:01
I have no idea how I end up with such keys.  I'm working fast and furious right now, so it's possible there was human error in the loop (as alway).  At a minimum, restic need pa to give a more helpful error message in such cases than: `missing fields in request`

**Comment by vsivsi** [comment] 2017-05-25 17:04
Oops, didn't mean to close the issue.

**Comment by vsivsi** [comment] 2017-05-25 17:05
@fd0  thanks for the link, I'll try to check out the new RC, but my ship literally sails on Saturday, so time is short!

**Comment by fd0** [comment] 2017-05-31 21:33
I'll close this issue for now, we can always reopen it later. Thanks!

**Closed by fd0** 2017-05-31 21:33 UTC
Labels: backend:s3, bug, feedback needed
