### ISSUE TITLE
typo in 'check' output on windows

### ISSUE THREAD

**Issue by AxelPetermann** [restic/restic#3352] opened 2021-04-01 21:23 UTC
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64

How did you run restic exactly?
-------------------------------
restic.exe --repo %repo% --password-file %pwdfile% check

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backend for repository: VeraCrypt-container stored on local HDD

Expected behavior
-----------------
no typo: typo is in the 'Actual behavior' section below in the second to last line, the last word:
'foundapshots' instead of just 'found'

Actual behavior
---------------
using temporary cache in C:\Users\ABCDEFGH\AppData\Local\Temp\restic-check-cache-269911643
repository 73d0ac3a opened successfully, password is correct
created new cache in C:\Users\ABCDEFGH\AppData\Local\Temp\restic-check-cache-309920683
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were foundapshots
[0:00] 100.00%  12 / 12 snapshots

Steps to reproduce the behavior
-------------------------------
just run the above mentioned command

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
great tool and so easy to set-up
way faster than my previous backup-solution (https://schinagl.priv.at/nt/ln/ln.html)

**Comment by dimejo** [comment] 2021-04-02 08:01
I don't see this typo on my systems when using CMD or PowerShell on Windows 10 20H2:
```
using temporary cache in C:\Users\aj\AppData\Local\Temp\restic-check-cache-025776715
repository 3fda17a2 opened successfully, password is correct
created new cache in C:\Users\aj\AppData\Local\Temp\restic-check-cache-025776715
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
[0:00] 100.00%  2 / 2 snapshots
```

Can you provide more information about your environment?

**Comment by greatroar** [comment] 2021-04-02 09:17
Probably a duplicate of #3344.

**Comment by AxelPetermann** [comment] 2021-04-02 12:02
@dimejo: Thanks for your quick reply.
@greatroar: I think you are right.

I made some further tests on Windows10 (same Laptop / environment as above. I did the following:

- created new repository ('init' command)
- backup a tiny folder (restic.exe --repo %repo% --password-file %pwdfile% backup --verbose=1 "D:\testfolder")
- run 'check' command (restic.exe --repo %repo% --password-file %pwdfile% check)
- I did 'backup' -> 'check' -> 'backup' -> 'check' until I had 26 snapshots

The outcome is: sometimes the typo occurred, sometimes not. With snapshot 26 I run the 'check' command several times (one check after the other). Here the same: Sometimes the typo occurred and sometimes not. See below the output:

```
using temporary cache in C:\Users\ABCDEFGH\AppData\Local\Temp\restic-check-cache-325945315
repository 41feec73 opened successfully, password is correct
created new cache in C:\Users\ABCDEFGH\AppData\Local\Temp\restic-check-cache-325945315
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found snapshots
[0:00] 100.00%  4 / 4 snapshots

no errors were found0 snapshots
[0:00] 100.00%  10 / 10 snapshots

no errors were foundapshots
[0:00] 100.00%  11 / 11 snapshots

no errors were found20 snapshots
[0:00] 100.00%  20 / 20 snapshots

no errors were foundapshots
[0:00] 100.00%  23 / 23 snapshots

no errors were found26 snapshots
[0:00] 100.00%  26 / 26 snapshots

no errors were foundapshots
[0:00] 100.00%  26 / 26 snapshots
```

**Comment by fd0** [comment] 2021-04-03 09:08
I'm closing this as a duplicate of #3344, thanks for the report!

**Closed by fd0** 2021-04-03 09:08 UTC
