### ISSUE TITLE
Set minPackSize via commandline

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#2678] opened 2020-04-03 05:56 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I'd like the ability to specify the minPackSize via commandline. Especially with large backups there are a lot of files. This need some time to transfer to a second backup location and sometimes you're limited in the number of maximum files.

It has already been implemented in a very old version, see here https://github.com/kayrus/restic/commit/71c13bab23ecb45f23cafb57609930fb9ffba806
You should be able to just copy the code.

What are you trying to do?
--------------------------
I want to make a backup at home so that in recovery case I have fast access and then transfer it to a cloud storage.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm just experimenting with it. We'll see how suitable it is. Currently I'm using duplicati. Without the index/database it took about 2 weeks on a i5 8th Generation mobile CPU with 4 physical cores to rebuild the database after that you could begin with restoring. Much to long for emergeny situations. So I'm trying with restic now.

**Comment by MichaelEischer** [comment] 2020-04-03 12:15
You might want to take a look at #2671 , which implements the command-line switch you've asked for.

**Comment by JsBergbau** [comment] 2020-04-03 12:38
Thanks. I hope that it is implemented in the next release soon.

**Comment by MichaelEischer** [comment] 2022-05-15 14:15
Duplicate of #2291.

**Closed by MichaelEischer** 2022-05-15 14:15 UTC
Labels: type: feature enhancement, category: backup
