### ISSUE TITLE
Latest restic client (0.8.3) takes very long time on any interaction with s3 minio backend

### ISSUE THREAD

**Issue by aleksystasiak** [restic/restic#1785] opened 2018-05-18 08:19 UTC
## Output of `restic version`
restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?
```
root@backupninja:/home/dsd# date
pią, 18 maj 2018, 09:56:49 CEST
root@backupninja:/home/dsd# ./restic_0.8.3_linux_amd64 -r s3:http://172.16.37.11:8000/data backup /backup/test
enter password for repository:
password is correct
scan [/backup/test]
scanned 1 directories, 1 files in 0:00
[2:30] 100.00%  6.630 MiB / 6.630 MiB  2 / 2 items  0 errors  ETA 0:00
duration: 2:30
snapshot ca5cf51b saved
root@backupninja:/home/dsd# date
pią, 18 maj 2018, 10:06:36 CEST
```

Only variables used are AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY

## What backend/server/service did you use to store the repository?
Minio distributed setup on ubuntu 16.04 - RELEASE.2018-05-16T23-35-33Z

## Expected behavior
Backup of 1 file in freshly initialized repo should complete instantly.

## Actual behavior
Backup of single 6MB file took 10 minutes.
Other commands also take very long time to complete against minio backend.

The problem does not exist when using restic client 0.6.0

## Steps to reproduce the behavior

Setup minio with latest version
Try to interact with fresh bucket with restic client 0.8.3 in any way

## Do you have any idea what may have caused this?

No

## Do you have an idea how to solve the issue?

No

**Comment by fd0** [comment] 2018-05-18 20:33
Oh, that's very odd, thanks for the report!

Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) of a run of `restic init` and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by fd0** [comment] 2018-05-18 20:56
I can't reproduce the issue, neither with 0.8.3, nor with the master branch. Hm.

Is there anything in between you and the server (a proxy or load-balancer or so)? It looks like it's within the same LAN, but I'd like to confirm this.

**Comment by aleksystasiak** [comment] 2018-05-22 06:12
All machines are in the same local network, minio servers (5 servers with 2 mino drives each)  are behind haproxy loadbalancer tcp backend.
Operations initiated using restic client version lower than 0.7 result in normal speed.
I will be back with more information after trying Your suggestions.

**Comment by aleksystasiak** [comment] 2018-05-22 06:40
I can already confirm that latest beta version (restic_v0.9.0-1-g20bfed59_linux_amd64) behaves normally, and commands are processed instantly .

**Comment by fd0** [comment] 2018-05-23 18:28
I've got no idea what's going on here, but if it works with 0.9.0 (which got released a few days ago), can we close this issue until it happens again? :)

**Comment by fd0** [comment] 2019-04-27 19:51
Since we haven't received any feedback in a long time I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!

**Closed by fd0** 2019-04-27 19:51 UTC
Labels: backend:s3, bug, feedback needed
