### ISSUE TITLE
Restic never and and create a lot of cache

### ISSUE THREAD

**Issue by guidtz** [restic/restic#3629] opened 2022-01-12 14:05 UTC
Output of `restic version` : restic 0.12.1 compiled with go1.16.6 on linux/amd64

On Debian 10
--------------------------

How did you run restic exactly?
-------------------------------
/usr/sbin/restic backup --no-cache --files-from /root/admin_scripts/backup_restic_s3/include.txt --exclude-file /root/admin_scripts/backup_restic_s3/exclude.txt >> $LOG

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Expected behavior
-----------------
All works

Actual behavior
---------------

restic backup never and avec 93% and generate a lot of cache.

I don't understand why it never ends 

Steps to reproduce the behavior
-------------------------------

Start the command and wait

Do you have any idea what may have caused this?
-----------------------------------------------

No idea before it's works well

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

In all others servers it's works

**Comment by guidtz** [comment] 2022-01-12 14:07
Same issue with : 
```
/usr/sbin/restic backup --files-from /root/admin_scripts/backup_restic_s3/include.txt --exclude-file /root/admin_scripts/backup_restic_s3/exclude.txt >> $LOG
```

**Comment by guidtz** [comment] 2022-01-12 17:40
Does restic have a limit in file number, in those server we have a lot of sess_ files and a think there is a problem with that 
```
df -i
/dev/sda1        13107200 9449551 3555751   73% /
```

**Comment by JsBergbau** [comment] 2022-01-14 01:28
> restic backup never and avec 93% and generate a lot of cache.

Sorry don't understand what you exactly mean. There seems to be missing a verb what restic never does.

What exactly does restic output when the error occurs?

If you have a lot of small files it can take a while to scan all files.

Don't know if your server is bare metal, if so I would also check with smartctl if HDD is working within normal parameters.

Regarding file count:
Largest Windows repository:
```
Stats in restore-size mode:
Snapshots processed:   34
   Total File Count:   17361060
         Total Size:   53.670 TiB
```

Largest Linux
```
Stats in restore-size mode:
Snapshots processed:   66
   Total File Count:   21780391
         Total Size:   704.316 GiB
```
and most files

```
Stats in restore-size mode:
Snapshots processed:   255
   Total File Count:   28130478
         Total Size:   26.477 GiB
```

**Comment by MichaelEischer** [comment] 2022-01-22 15:20
> Does restic have a limit in file number, in those server we have a lot of sess_ files and a think there is a problem with that

There is no hard limit on the number of files. However, more files lead to more metadata and require more RAM for restic to work. Note that folders with hundreds of thousands of files (or even millions) will cause one problem or another.

**Comment by MichaelEischer** [comment] 2024-07-03 19:12
Closing as the issue is very old and there's not enough information available to further investigate. Feel free to open a new open if there's still a problem.

**Closed by MichaelEischer** 2024-07-03 19:12 UTC
