### ISSUE TITLE
Verify local file before restoring

### ISSUE THREAD

**Issue by stang** [restic/restic#2011] opened 2018-09-27 14:47 UTC
Output of `restic version`
--------------------------

```
restic 0.9.2 compiled with go1.10.3 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently, when using the `restic restore` command, it systematically restore data from a snapshot and eventually check the integrity of the restored data afterward if the `--verify` arg is used.

It would good to check the data before restoring it as well, and skip the restore part if the data present on the disk is already valid (same principle as `rsync`).

What are you trying to do?
--------------------------

It would save time when restoring backups _not from scratch_.

For example, we want to give our users the content of their last backup so they can do incremental backup (with logic on application level).

To do so, we're giving our users a working directory:
* we restore the content of the last backup if they ask for it,
* they do their backup and write in that directory,
* we're backing up this directory using `restic`.

This directory is persisted but to guarantee that its content is not altered between two backups, we systematically restore the content of the previous backup before presenting it back to the users.

Currently, this means that we systematically entirely restore a snapshot, which can take a bit of time.

Executing the same operation as during the `--verify` before restoring objects would save quite a lot of time, and shouldn't add much overhead when restoring in an empty directory.

-------------------------------------------------

**Comment by fd0** [comment] 2018-09-28 11:14
Thanks for reporting this, and for the implementation!

**Comment by MichaelEischer** [comment] 2022-05-15 15:44
Duplicate of #2662.

**Closed by MichaelEischer** 2022-05-15 15:44 UTC
Labels: type: feature enhancement, category: restore
