### ISSUE TITLE
Add support for Amazon S3 virtual-hosted–style URL

### ISSUE THREAD

**Issue by K-2233** [restic/restic#4635] opened 2024-01-15 01:51 UTC
Output of `restic version`
--------------------------

0.16.2

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It seems Restic only support path-style URL when using an Amazon S3 bucket.

From the [Restic doc:](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html)

> restic expects [path-style URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html) like for example s3.us-west-2.amazonaws.com/bucket_name. Virtual-hosted–style URLs like bucket_name.s3.us-west-2.amazonaws.com, where the bucket name is part of the hostname are not supported. These must be converted to path-style URLs instead, for example s3.us-west-2.amazonaws.com/bucket_name.

But those path-style URL will be[ deprecated:
](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access)
> Currently, Amazon S3 supports both virtual-hosted–style and path-style URL access in all AWS Regions. However, path-style URLs will be discontinued in the future. For more information, see the following Important note.

> Important
> 
> Update (September 23, 2020) – To make sure that customers have the time that they need to transition to virtual-hosted–style URLs, we have decided to delay the deprecation of path-style URLs. For more information, see [Amazon S3 Path Deprecation Plan – The Rest of the Story](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)
> in the AWS News Blog.

So doing a backup to an Amazon S3 Bucket is currently **not future-proof** until virtual-hosted–style URL are supported.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic helps me everyday, it's a great project!!

**Comment by MichaelEischer** [comment] 2024-01-15 18:32
Duplicate of #2264. For Amazon S3, the path style requests are internally converted in to virtual hosted requests.

**Closed by MichaelEischer** 2024-01-15 18:32 UTC
