### ISSUE TITLE
number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by NovacomExperts** [restic/restic#1539] opened 2018-01-09 17:15 UTC
## Output of `restic version`

restic 0.8.1
compiled with go1.9.2 on windows/amd64
Downloaded binaries 

## How did you run restic exactly?

On Windows :

init :
set AWS_ACCESS_KEY_ID=<changed>
set AWS_SECRET_ACCESS_KEY=<changed>
set RESTIC_REPOSITORY=s3:nyc3.digitaloceanspaces.com/myspace/mysubfolder
set RESTIC_PASSWORD=<changed>

restic prune
password is correct
counting files in repo
building new index for repo
Stat(<data/34173bc2dd>) returned error, retrying after 690.178772ms: Stat: 504 Gateway Timeout
Stat(<data/3f7af32003>) returned error, retrying after 571.503182ms: Stat: 504 Gateway Timeout
Stat(<data/69f7acd5c7>) returned error, retrying after 541.619181ms: Stat: 504 Gateway Timeout
Stat(<data/7675706f7c>) returned error, retrying after 490.685294ms: Stat: 504 Gateway Timeout
Stat(<data/ac3b90c6b4>) returned error, retrying after 394.979263ms: Stat: 504 Gateway Timeout
Stat(<data/b42467ad25>) returned error, retrying after 607.6434ms: Stat: 504 Gateway Timeout
[7:31] 100.00%  609 / 609 packs
repository contains 609 packs (21217 blobs) with 2.749 GiB
processed 21217 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 6 snapshots
[0:02] 100.00%  6 / 6 snapshots
number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

## What backend/server/service did you use to store the repository?

Digital Ocean

## Expected behavior

I ran a couple of snapshot for a Windows client and a Linux client. Both in the same repo. I did about 6-7 snapshots over the last days at this repo. Initial testing. 

This morning i ran : 
restic forget --keep-last 3 --prune

I expected success but got :

## Actual behavior

Stat(<data/b42467ad25>) returned error, retrying after 608.106213ms: Stat: 504 Gateway Timeout
Stat(<data/cf705aa534>) returned error, retrying after 502.775988ms: Stat: 504 Gateway Timeout
[5:51] 100.00%  609 / 609 packs
finding old index files
Save(<index/11e37f1344>) returned error, retrying after 293.660013ms: client.PutObject: Put https://nyc3.digitaloceanspaces.com/myspace/myfolder/index/11e37f134490b455d50c6c3ceb00f965473bfae80b37b5f8ec1863df339eb897: Connection closed by foreign host https://nyc3.digitaloceanspaces.com/myspace/myfolder/index/11e37f134490b455d50c6c3ceb00f965473bfae80b37b5f8ec1863df339eb897. Retry again.
saved new index as 11e37f13
remove 11 old index files
[0:42] 100.00%  32 / 32 packs deleted
done

so i decided to run a check

restic check

...
error for tree 7f1f8ac3:
  tree 7f1f8ac3, blob ee74ac56: not found in index
  tree 7f1f8ac3, blob 99f140f6: not found in index
  tree 7f1f8ac3, blob a9af8d40: not found in index
  tree 7f1f8ac3, blob ac84f2d5: not found in index
error for tree cbe7656e:
  tree cbe7656e, blob ee74ac56: not found in index
  tree cbe7656e, blob 99f140f6: not found in index
  tree cbe7656e, blob a9af8d40: not found in index
error for tree a22d2eb2:
  tree a22d2eb2, blob 40ebbeb1: not found in index
  tree a22d2eb2, blob 6315dead: not found in index
error for tree 8ad86e78:
  tree 8ad86e78, blob 687fb9be: not found in index
error for tree 538bb7fa:
  tree 538bb7fa, blob b3c26094: not found in index
error for tree f8fd9b57:
  tree f8fd9b57, blob b393955d: not found in index
... 
1000 times +

after : restic prune asked to report issue here

## Steps to reproduce the behavior

multiple restic snapshots to digitalocean spaces
restic forget --prune --keep-last 3
restic check
restic prune

## Do you have any idea what may have caused this?

Not sure if those timeourts are normal
Stat(<data/34173bc2dd>) returned error, retrying after 690.178772ms: Stat: 504 Gateway Timeout
All tests on sftp ran perfectly

## Do you have an idea how to solve the issue?

I could flush the whole repo and restart my backups, but that wont point to the right issue.
I did not try to reindex the whole thing

## Did restic help you or made you happy in any way?

restic for me is VERY attractive. I does deduplication, manage snapshots easily and encrypt the data at a remote storage. My tests on sftp runs great so far. I really hope this can work out.

**Comment by fd0** [comment] 2018-01-09 21:08
Hi, thanks for the report! It looks like restic was unable to find several pack files stored in the repo during the `prune` run (it even tried several times with waiting in between), so it prompted you to file a report. That's a safety feature.

Unfortunately we've received several reports that DO Spaces may not be as reliable as DO would like it to be (see #1457). I've been in contact with several engineers there and sent them instructions on how to reproduce some issues using only their own infrastructure, but I haven't heard back after that.

I'm not sure what we (from restic's side) can improve: We already retry failed requests, wait a bit in between the tries, but if the service is unable/unwilling to send us the requested data there's not much we can do. I hope that over time the service will become usable.

In your case, you can try running `restic rebuild-index`, there's a good chance that this will correct most errors. Please try that and report back!

**Comment by fd0** [comment] 2018-01-09 21:09
I'm going to close this issue as there's not much we can do. Please do add a comment anyway and report back if `rebuild-index` recovered the repo! Thanks!

**Closed by fd0** 2018-01-09 21:09 UTC

**Comment by NovacomExperts** [comment] 2018-01-09 21:39
Hello Alexander.

Stability issue on DO side make sense...
I will continue my testing using an original AWS S3 bucket and see if it's more stable.

FWI : i just ran `restic rebuild-index` and it ran without errors

Just after I ran `restic check` and the output was like before : 

```
...
error for tree de15a0c4:
  tree de15a0c4, blob f5e46b9a: not found in index
error for tree 2b695360:
  tree 2b695360, blob 1128d42a: not found in index
  tree 2b695360, blob 6debc2a7: not found in index
error for tree 57544298:
  tree 57544298, blob 802af6af: not found in index
  tree 57544298, blob aff133db: not found in index
...
```
No data is critical there,  I'll open a ticket on my side with them to see if it can help. I'll post back to the forum afterward.

Thanks

**Comment by NovacomExperts** [comment] 2018-01-09 22:30
Hello Alexander, Digital ocean aknowledges problems on NYC3 spaces. I should have checked there first. Keep on the good work !

>NYC3 Spaces Increased Error Rates
>
> Yesterday
> The error rate for Spaces in NYC3 has improved, and our engineering team will continue to monitor the service. If you are experiencing additional issues with Spaces in NYC3, please open a ticket with our Support team for further assistance.
> 
> Yesterday
> Our engineering team continues to investigate the cause of the increased error rates when making requests to Spaces in NYC3. We will provide updates a they become available.
> 
> Yesterday
> Our engineering team is investigating an increased rate of errors when making requests to Spaces in NYC3. We apologize for the inconvenience and will provide updates as we have more information.

**Comment by fd0** [comment] 2018-01-10 08:20
Don't worry, thanks for the feedback! ;)

**Comment by fd0** [comment] 2018-01-11 20:38
What I really like about restic: It makes it possible to detect these kinds of errors early on, **before** you actually need it. :)

**Comment by NovacomExperts** [comment] 2018-01-11 20:45
Indeed !

Seems all good now ! You really do have an awesome backup program. Started using in small setups here and there.I will keep you informed...
