### ISSUE TITLE
restore no progress information

### ISSUE THREAD

**Issue by gluthgao** [restic/restic#1154] opened 2017-08-11 06:37 UTC
## Output of `restic version`
debug enabled
restic 0.7.1 (v0.7.1-80-g5b25b85)
compiled with go1.8.1 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
./restic -r repo restore 50be5857 --target ~/Desktop/test2/

## What backend/server/service did you use?
object storage

## Expected behavior
should show the progress information

## Actual behavior
don't know the progress, like the backup we do have the progress information

## Steps to reproduce the behavior
enter password for repository:
restoring <Snapshot 50be5857 of [/Users/gluth/Desktop] at 2017-08-10 19:22:29.945157443 +0800 CST by gluth@gluthdeMacBook-Pro.local> to /Users/gluth/Desktop/test2/
no any progress information showed

## Do you have any idea what may have caused this?
we should have some progress information for restore, for each backup we can save the total size,  and during the run restore we got the size from repo, which will give the progress information.

**Comment by fd0** [comment] 2017-08-11 06:49
Hey, thanks for leaving an issue. I'm labeling this as an enhancement for the restore process.

When reporting issues, it is a good idea not to mix the observation/description with a proposed solution. In this case, I think it is not a good idea to just save the size of the backup to use for restore progress: It is not backwards compatible and changes the repository format, that is only permissible in certain situations. It may also be inaccurate: What if the user specifies includes/excludes?

A better idea is to wait for #1040 to land, then we can traverse the restore tree once to get the size, and then display progress information. During traversal, we can take any includes/excludes into account so the progress information is accurate.

**Comment by peperunas** [comment] 2018-02-06 22:31
Hello! I don't want to sound harsh but any news on this?
I am just restoring a backup and having no information whatsoever is a little bit confusing.

Thanks!

**Comment by zout** [comment] 2018-02-14 12:24
Maybe this should get more priority. I've been waiting for hours to restore something, and see some CPU load, but no data being transferred. Because i'm in testing phase, i'm considering other options.

**Comment by rawtaz** [comment] 2018-02-14 12:55
@zout It's always good to consider multiple options to find the one that suits you the most :)

It's pretty odd however that you are not seeing any data being transferred. What backend are you using, how are you restoring (e.g. what's the command you use)? Seems fishy.

Personally I just check the size of the target folder(s) to check on progress, then I let it run as long as it needs to (assuming I'm seeing progress of course).

**Comment by zout** [comment] 2018-02-14 14:47
I've used a S3 backend, and are backing up a minio data folder. Minio stores a lot of small files. For our repo it comes down to about 493000 files. I now keep progress of restoring by counting all the files (also in subfolders). What I suspect is dat restoring is happening file by file, and it only does about 100 files per second. It takes little over 2 hours to complete the restore that tool under 2 minutes to backup to S3.

Thats why I was very worried that it was not doing anything at all, but it was, but just very slowly.

**Comment by MichaelEischer** [comment] 2020-10-10 09:35
As suggested in #2438, the `--verbose` flag could be used to select how much information should be printed, just like with the backup command.

**Comment by fermulator** [comment] 2021-02-22 02:47
I believe this is a duplicate of #426

**Comment by MichaelEischer** [comment] 2021-06-05 11:52
Merged into #426.

**Closed by MichaelEischer** 2021-06-05 11:52 UTC
Labels: category: restore, category: user interface, help: wanted, type: feature enhancement
