### ISSUE TITLE
error loading blob wrong length returned

### ISSUE THREAD

**Issue by rooty123** [restic/restic#743] opened 2017-01-24 06:06 UTC
## Output of `restic version`

restic 0.3.3 (v0.3.3-59-g0d12572)
compiled with go1.6.1 on linux/amd64

## Expected behavior

Restoring from ssh repository

## Actual behavior

For some files I get errors while restoring

`
error for /home/sasha/tmp/oops2/src/prdui/.git/objects/0f/bef8e80bf1a9b108f9c9a3aab0df5aa1cff08a: error loading blob 98180b5a: wrong length returned, want 447701, got 662648
restic/repository.(*Repository).loadBlob
        /tmp/restic-build-826987944/src/restic/repository/repository.go:110
restic/repository.(*Repository).LoadBlob
        /tmp/restic-build-826987944/src/restic/repository/repository.go:534
restic.Node.createFileAt
        /tmp/restic-build-826987944/src/restic/node.go:214
restic.(*Node).CreateAt
        /tmp/restic-build-826987944/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
        /tmp/restic-build-826987944/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
        /tmp/restic-build-826987944/src/restic/restorer.go:122
main.runRestore
        /tmp/restic-build-826987944/src/cmds/restic/cmd_restore.go:135
main.glob.func13
`

**Comment by fawick** [comment] 2017-01-24 07:13
This is exactly the kind of error I got when calliing restore, so I guess it is a duplicate of #742

Switching backwards to released version v0.3.3 is a workaround until this is fixed.

**Comment by fd0** [comment] 2017-01-24 07:44
Thanks for your report, I'll investigate now.

**Comment by fd0** [comment] 2017-01-24 11:12
Resolved via #745

**Closed by fd0** 2017-01-24 11:12 UTC
Labels: bug
