### ISSUE TITLE
prune reports missing data blobs

### ISSUE THREAD

**Issue by tomm87** [restic/restic#3272] opened 2021-02-08 23:25 UTC
Output of `restic version`
--------------------------
> restic 0.10.0 compiled with go1.15.2 on linux/amd64

I'm running this on Debian 10.6 ("Buster"), using an official Restic binary (as opposed to a self-compiled or distro-packaged version).

How did you run restic exactly?
-------------------------------
The following 6-line script:
> #!/bin/bash
> export RESTIC_REPOSITORY=b2:WWULibBackupSpecColl
> export RESTIC_PASSWORD=*[redacted]*
> export B2_ACCOUNT_ID=*[redacted]*
> export B2_ACCOUNT_KEY=*[redacted]*
> /usr/local/bin/restic prune -o b2.connections=50

Output is attached, with link in the **Actual behavior** section below.

I have not changed Restic versions recently, although the repository was created and early backups were done with an earlier version than I'm using now. 

In case it matters: Backups are performed using Rclone's Restic REST server mode as the backend seen by Restic -- only Rclone talks directly to the repository in Backblaze B2 during backups.  In contrast, maintenance operations (`forget`, `prune`, `check`) are performed by the Rclone server (not the machine that's been backed up), directly against the repository on B2 without involving any version of the Restic REST server.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
Prune the repository and report success.
This is both what I expect and want.

Actual behavior
---------------
The `prune` operation appears to finish building a new index (reaches 100%), and finding data used by existing snapshots (reaches 100%). Then it reported missing data blobs, and asked me to report the problem here.  Output is attached:  [out.txt](https://github.com/restic/restic/files/5947202/out.txt)

Steps to reproduce the behavior
-------------------------------
I ran `prune` again and got the same result, so presumably I can reproduce at will by running `prune` against this repository. (Perhaps `check` would also produce the same error, but I haven't tried that.) 

This repository has been pruned and checked monthly for well over a year; this is the first time I've encountered this problem. The repository is approximately 2 TB.  I'm guessing that you might need access to this repository in order to reproduce this problem. (I can try to arrange that if you like.)

Do you have any idea what may have caused this?
-----------------------------------------------
The most obvious possibility is that the repository is truly damaged, although I don't know how that might have happened.

Do you have an idea how to solve the issue?
-------------------------------------------
No, but if it would help I can try to build a debug-enabled copy of Restic.  Also, I can probably get permission from the data owner to let you examine the repository.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Backing up large amounts of data has been a headache for me for many years. Restic, plus Backblaze's affordable B2 storage, is by far the best solution I've ever found, and that literally makes me happy every day when I get my script-driven backup status report and remember that I'm not replacing failed or filled disks in my own miserable backup server any more.  Today I'm having my first serious problem with Restic, and although the problem per se is not making me happy today, it also highlights how trouble-free Restic has generally been. Restic is a tremendous gift -- thank you so much!

**Comment by MichaelEischer** [comment] 2021-02-10 20:45
This could be same issues as in #3266. Please run `restic cat pack --no-cache --quiet 46609e589ae9d0aa4f42c1175a16f5a8643482b219724492739d811cfb7695c6 > temp-46609e5[...]` to download all pack files reported as `incomplete pack file`. Then use `shasum -a256 temp-46609e5[...]  [...]` to check the hash of these files. For files whose hash does not match the filename, please lookup these in the B2 web ui. The creation/modification time and the expected sha1 checksum would be the most interesting. Then compare these sha1 checksums to the output of `sha1sum temp-[...]`.

**Comment by tomm87** [comment] 2021-02-11 00:33
Thank you very much Michael. It will take me some time to read issue 3266 and follow your advice, but I will report back when I've done that. It might be a few days.

**Comment by tomm87** [comment] 2021-02-17 18:48
Just popping my head in to say I'm still alive and still care about this issue. Today was earmarked to work on this in earnest, but now B2 is down  :-(
I can only work on this a couple days each week, so I apologize for slow progress. I'll be back with an update soon, for large-ish values of "soon".

**Comment by MichaelEischer** [comment] 2021-02-17 19:43
The main investigation of this B2 issue is now in #3268. The current state seems to be that the problem reproduces without restic and B2 is currently investigating: https://github.com/restic/restic/issues/3268#issuecomment-780172480

**Comment by tomm87** [comment] 2021-02-17 21:06
I can now get to B2 again, so I finished the first test that I had ready to go. I downloaded the 6 packs that `prune` identified as incomplete. 4 of them have correct SHA256 hashes; 2 are incorrect.

If it would be helpful, I'd be happy to continue with the B2 web UI lookup, or other steps. But I wonder if this would really be valuable considering issue #3268 looks like it might be on the verge of a solution. Please let me know if you'd like me to do more.

**Comment by tomm87** [comment] 2021-02-24 00:08
I have some multi-terabyte repositories, so I was very excited to try the performance improvements in newer Restic versions. I upgraded to Restic 0.12.0 and tried both `prune` and `check --no-cache` on my problem repository and neither found any problems. Moreover, both took seconds or minutes instead of many hours  :-D

I realize this is a bad troubleshooting method, but it appears issue #3268 is essentially solved (if not formally solved yet), and I did not have much to contribute to its solution. I hope the fact that my problem now seems to be fixed supports the theory that #3268 is also essentially fixed.

A huge THANK YOU to Michael and the Restic developers. I will close this issue in a few days if there's no new activity.

**Comment by MichaelEischer** [comment] 2021-02-27 17:47
@tomm87 Closing this issue, as I'm pretty sure that your prune issues were caused by the temporarily invalid pack files returned by B2. Feel free to reopen the issue is the issue resurfaces.

Btw, I wouldn't recommend using the `--no-cache` flag with `check`. The `check` command by default already downloads a fresh copy of all files into a new temporary cache. And when using a cache, check is a lot faster than without.

**Closed by MichaelEischer** 2021-02-27 17:47 UTC
Labels: backend: b2, state: need investigating
