### ISSUE TITLE
restic init password interaction fail on MSYS2 Windows bash

### ISSUE THREAD

**Issue by frederich** [restic/restic#330] opened 2015-10-28 10:35 UTC
I'm a MSYS2 respectively Cygwin user. I've tried `restic init` in a MSYS2 bash. It fail with error:

```
v% restic init --repo backup
enter password for new backend: unable to read password: Das Handle ist ungültig.
v% restic init --repo backup
enter password for new backend: unable to read password: Das Handle ist ungültig.

v% echo $0
/usr/bin/bash
```
The same at a dos console works.

```
H:\>restic init --repo backup
enter password for new backend:
enter password again:
created restic backend xxxxx backup
```

**Comment by fd0** [comment] 2015-10-28 20:55
This is an interesting bug, the password is just read from stdin, although restic tries to configure the terminal and disable echo (so that the password isn't shown).

**Comment by frederich** [comment] 2015-10-28 21:04
Hi Alex (also from Schland ;-),

I believe the terminal modification cause the issue. Should I try something?

```
v% echo $TERM
xterm-256color
```

**Comment by frederich** [comment] 2015-10-28 21:10
The MSYS2 terminal is a mintty 2.0.3.

**Comment by fd0** [comment] 2015-10-28 21:12
Hm, interesting. It really seems to be caused by the `terminal/ssh` library, there is different code executed for windows and linux here: https://github.com/restic/restic/tree/master/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal

I don't  think the library detects xterm running on windows and uses the linux code.

**Comment by frederich** [comment] 2015-10-28 21:26
Okay, I can modify the code and use the linux code of terminal/ssh and run some tests.

**Comment by frederich** [comment] 2015-10-28 22:08
It's a general Go issue. You can copy util_linux.go to util_windows.go and add 'windows' to build. After a `go run build.go` run the output is:

```
v% go run ./build.go
# golang.org/x/crypto/ssh/terminal
E:\tmp\restic-build-031239579\src\golang.org\x\crypto\ssh\terminal\util.go:27: undefined: syscall.Termios
build failed: exit status 2
exit status 1
```

The Termios syscall is missing. I think it's a general go problem. We've to file a new Golang issue and describe the scenario. I hope Cygwin will be a new Golang target.

**Comment by fd0** [comment] 2015-10-29 15:46
It's not a "general Go problem" in my opinion. I think the use case "unix terminal on windows" just isn't supported yet. Thanks for raising the issue, though!

**Comment by frederich** [comment] 2015-10-29 17:06
You are right, "general" is the wrong word. Yes, the case isn't supported yet. But what's the best solution? Adding syscall.Termios for target Windows? Adding a complete new target Cygwin?

**Comment by fd0** [comment] 2015-10-29 20:36
I'm not sure how to approach this. Could you maybe use strace/ltrace to have a look what e.g. `ssh` does in the DOS box versus in the terminal?

**Comment by frederich** [comment] 2015-10-29 21:55
No that's not possible. Strace is MSYS2/Cygwin based on Windows. You can trace cmd's which are compiled with this virtual Posix enviroment. The Windows Go tools chain use the native Windows interface, no Posix wrapper.

```
v% strace restic -r /h/backup snapshots
enter password for repository: unable to read password: Das Handle ist ungültig.
--- Process 8672 created
--- Process 8672 loaded C:\Windows\System32\ntdll.dll at 0000000077100000
--- Process 8672 loaded C:\Windows\System32\msctf.dll at 000007FEFE440000
--- Process 8672 thread 3620 created
--- Process 8672 loaded C:\Windows\System32\cryptsp.dll at 000007FEFC970000
--- Process 8672 loaded C:\Windows\System32\rsaenh.dll at 000007FEFC450000
--- Process 8672 loaded C:\Windows\System32\cryptbase.dll at 000007FEFCD80000
--- Process 8672 thread 6288 created
--- Process 8672 thread 5516 created
--- Process 8672 thread 3960 created
--- Process 8672 exited with status 0x2
```

Mintty termina xterm is termios based. It use the same interface like Linux. The Dos box on the other hand use the native Windows [console interface](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682010%28v=vs.85%29.aspx).

The type [`syscall.Termios`](https://golang.org/src/syscall/ztypes_linux_amd64.go?s=10251:10439#L590) is not defined for Windows.

To support termios based

**Comment by frederich** [comment] 2015-10-30 20:42
I've found a work around. For me it's acceptable. In general MSYS2 starts a shell via `msys2_shell.bat`. The Bat script starts a Mintty (xterm based) terminal and execute bash. Replacing the Mintty terminal with a Dos Box solves the password issue.

replace: 
       
        start %WD%mintty -i /msys2.ico /usr/bin/bash --login %*

with: 
   
        %WD%bash --login -i %*

I think you'd place a note for all MSYS2 and Cygwin Mintty users.

**Comment by fd0** [comment] 2015-10-30 20:54
Hm, I don't have a good idea where to place the note, do you have a proposal? Otherwise we can leave this issue open until the problem is fixed in the library, so users can find it (and the workaround).

**Comment by frederich** [comment] 2015-11-02 09:15
My proposal is the leave a note at the "Initialize a repository" section. For instance

At the moment Restic supports only Dos Box based terminals session like `cmd.exe` or Standard `cygwin.bat`. Terminals like Mintty.exe (xterm based), which is the default MSYS2 terminal, cannot by handled at the moment.

**Comment by frederich** [comment] 2015-11-02 13:13
I've found a fine solution which works on Mintty (xterm) based terminal sessions. That's the default on MSYS2. There is a tool called [winpty](https://github.com/rprichard/winpty). Winpty providing an interface similar to a Unix pty-master for communicating with Windows console programs. 

```
# install winpty on MSYS2
v% pacman -S winpty
```

```
v% restic -r backup snapshots
enter password for repository: unable to read password: Das Handle ist ungültig.

v% winpty restic -r backup snapshots
enter password for repository:
ID        Date                 Source      Directory
----------------------------------------------------------------------
088cc522  2015-11-02 10:32:41  XXXXXXXX  e:\home\user
```

**Comment by fd0** [comment] 2015-11-02 16:58
Ok, so we could add that to the manual section about initialization, right? May I ask that you open a PR at https://github.com/restic/restic.github.io? That'd be awesome!

**Comment by fd0** [comment] 2016-08-21 17:19
Since you didn't answer I assume that you didn't have the time to do this. I'm closing this issue for now, if you still want to add a section to the manual, please create a PR or add a comment here. Thanks!

**Closed by fd0** 2016-08-21 17:19 UTC
Labels: bug, user interface
