### ISSUE TITLE
Handle interrupted backups

### ISSUE THREAD

**Issue by yatesco** [restic/restic#385] opened 2016-01-08 12:16 UTC
Hi,

I have about 500GB being backed up, hardly any of which changes, however, backing up takes a while and if anything goes wrong and the `backup` operation needs to be started again it doesn't resume.

Not critical, but nice to have.

Thanks!

**Comment by fd0** [comment] 2016-01-08 13:06
It already does resume, but only in regards to transferred data. I consider this a duplicate of #386, since it's the same underlying issue.

**Closed by fd0** 2016-01-08 13:06 UTC
