### ISSUE TITLE
restic check dumps a stack trace

### ISSUE THREAD

**Issue by flo82** [restic/restic#2093] opened 2018-11-16 23:07 UTC
Output of `restic version`
--------------------------

restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------

restic -p /opt/scripts/restic.pass check

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

azure account

Expected behavior
-----------------

check output, that i understand ;-)

Actual behavior
---------------

> github.com/restic/restic/internal/repository.FilesInParallel.func2(0x8, 0xc32ab0)
>         /restic/internal/repository/parallel.go:40 +0xaa
> golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001e7650, 0xc0001e7dd0)
>         /restic/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
> created by golang.org/x/sync/errgroup.(*Group).Go
>         /restic/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
> 
> goroutine 754 [select]:
> net/http.(*persistConn).writeLoop(0xc00034d320)
>         /usr/local/go/src/net/http/transport.go:1885 +0x113
> created by net/http.(*Transport).dialConn
>         /usr/local/go/src/net/http/transport.go:1339 +0x966
> 
> goroutine 810 [IO wait]:
> internal/poll.runtime_pollWait(0x7f031b134c90, 0x72, 0xc063dc7858)
>         /usr/local/go/src/runtime/netpoll.go:173 +0x66
> internal/poll.(*pollDesc).wait(0xc03e716a18, 0x72, 0xffffffffffffff00, 0xccf960, 0x116c4e0)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
> internal/poll.(*pollDesc).waitRead(0xc03e716a18, 0xc00b254000, 0x400, 0x400)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> internal/poll.(*FD).Read(0xc03e716a00, 0xc00b254000, 0x400, 0x400, 0x0, 0x0, 0x0)
>         /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
> net.(*netFD).Read(0xc03e716a00, 0xc00b254000, 0x400, 0x400, 0x40862b, 0xc0001be000, 0xb2e140)
>         /usr/local/go/src/net/fd_unix.go:202 +0x4f
> net.(*conn).Read(0xc000208070, 0xc00b254000, 0x400, 0x400, 0x0, 0x0, 0x0)
>         /usr/local/go/src/net/net.go:177 +0x68
> crypto/tls.(*block).readFromUntil(0xc03e1dad50, 0xcce2a0, 0xc000208070, 0x5, 0xc000208070, 0x342b4ba25f09a275)
>         /usr/local/go/src/crypto/tls/conn.go:492 +0x89
> crypto/tls.(*Conn).readRecord(0xc00006a380, 0xc32a17, 0xc00006a4a0, 0x601c7248b4ceb22b)
>         /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
> crypto/tls.(*Conn).Read(0xc00006a380, 0xc069886000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>         /usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
> net/http.(*persistConn).Read(0xc00034c360, 0xc069886000, 0x1000, 0x1000, 0x404a93, 0xc0008acc70, 0x429762)
>         /usr/local/go/src/net/http/transport.go:1497 +0x75
> bufio.(*Reader).fill(0xc01a284cc0)
>         /usr/local/go/src/bufio/bufio.go:100 +0x106
> bufio.(*Reader).Peek(0xc01a284cc0, 0x1, 0xc0002f41e0, 0xc0008acd58, 0x756ad655639d95fc, 0x2ab050be5edb048d, 0xe0d396990451c04e)
>         /usr/local/go/src/bufio/bufio.go:132 +0x3f
> net/http.(*persistConn).readLoop(0xc00034c360)
>         /usr/local/go/src/net/http/transport.go:1645 +0x1a2
> created by net/http.(*Transport).dialConn
>         /usr/local/go/src/net/http/transport.go:1338 +0x941
> 
> goroutine 809 [select]:
> github.com/restic/restic/internal/repository.(*Index).Each.func1(0xc06481ea00, 0xc0002c8ea0, 0xcd6340, 0xc000122ac0)
>         /restic/internal/repository/index.go:223 +0x2d7
> created by github.com/restic/restic/internal/repository.(*Index).Each
>         /restic/internal/repository/index.go:215 +0x8f
> 
> goroutine 811 [select]:
> net/http.(*persistConn).writeLoop(0xc00034c360)
>         /usr/local/go/src/net/http/transport.go:1885 +0x113
> created by net/http.(*Transport).dialConn
>         /usr/local/go/src/net/http/transport.go:1339 +0x966
> 
> goroutine 753 [IO wait]:
> internal/poll.runtime_pollWait(0x7f031b134a20, 0x72, 0xc00b03d858)
>         /usr/local/go/src/runtime/netpoll.go:173 +0x66
> internal/poll.(*pollDesc).wait(0xc06812ce98, 0x72, 0xffffffffffffff00, 0xccf960, 0x116c4e0)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
> internal/poll.(*pollDesc).waitRead(0xc06812ce98, 0xc0682c2000, 0x8000, 0x8000)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> internal/poll.(*FD).Read(0xc06812ce80, 0xc0682c2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
>         /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
> net.(*netFD).Read(0xc06812ce80, 0xc0682c2000, 0x8000, 0x8000, 0x40862b, 0xc0001be000, 0xb2e140)
>         /usr/local/go/src/net/fd_unix.go:202 +0x4f
> net.(*conn).Read(0xc000208378, 0xc0682c2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
>         /usr/local/go/src/net/net.go:177 +0x68
> crypto/tls.(*block).readFromUntil(0xc046186c30, 0xcce2a0, 0xc000208378, 0x5, 0xc000208378, 0x448b0a)
>         /usr/local/go/src/crypto/tls/conn.go:492 +0x89
> crypto/tls.(*Conn).readRecord(0xc000156000, 0xc32a17, 0xc000156120, 0x454870)
>         /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
> crypto/tls.(*Conn).Read(0xc000156000, 0xc068002000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>         /usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
> net/http.(*persistConn).Read(0xc00034d320, 0xc068002000, 0x1000, 0x1000, 0xc00b03dc70, 0x404c85, 0xc0001215c0)
>         /usr/local/go/src/net/http/transport.go:1497 +0x75
> bufio.(*Reader).fill(0xc063933500)
>         /usr/local/go/src/bufio/bufio.go:100 +0x106
> bufio.(*Reader).Peek(0xc063933500, 0x1, 0x0, 0x0, 0x1, 0xc00002cc60, 0x0)
>         /usr/local/go/src/bufio/bufio.go:132 +0x3f
> net/http.(*persistConn).readLoop(0xc00034d320)
>         /usr/local/go/src/net/http/transport.go:1645 +0x1a2
> created by net/http.(*Transport).dialConn
>         /usr/local/go/src/net/http/transport.go:1338 +0x941
> 

Steps to reproduce the behavior
-------------------------------

don't know

Do you have any idea what may have caused this?
-----------------------------------------------

perhaps low ram. but dmesg doesnt' show anything.

Do you have an idea how to solve the issue?
-------------------------------------------

sorry - no.

Did restic help you or made you happy in any way?
-------------------------------------------------

perfect backup - but i am not sure right now, if the backup is error free.

**Comment by cdhowie** [comment] 2018-11-16 23:50
This indicates a crash.  However, it looks like the panic log is missing some lines at the beginning, which should indicate what caused the panic.  Can you capture the complete output?

```
restic -p /opt/scripts/restic.pass check 2>&1 >restic.log
```

**Comment by flo82** [comment] 2018-11-17 08:50
Thanks @cdhowie 👍  
as expected the pc runs out of memory:

> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0xc0d786, 0x16)
>         /usr/local/go/src/runtime/panic.go:608 +0x72
> runtime.sysMap(0xc088000000, 0x14000000, 0x11e41d8)
>         /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
> runtime.(*mheap).sysAlloc(0x11ca7a0, 0x14000000, 0x7faa42770c10, 0xc0007c1e30)
>         /usr/local/go/src/runtime/malloc.go:619 +0x1c7
> runtime.(*mheap).grow(0x11ca7a0, 0x9080, 0x0)
>         /usr/local/go/src/runtime/mheap.go:920 +0x42
> runtime.(*mheap).allocSpanLocked(0x11ca7a0, 0x9080, 0x11e41e8, 0x20300500000000)
>         /usr/local/go/src/runtime/mheap.go:848 +0x337
> runtime.(*mheap).alloc_m(0x11ca7a0, 0x9080, 0xc000270101, 0x7faa00000001)
>         /usr/local/go/src/runtime/mheap.go:692 +0x119
> runtime.(*mheap).alloc.func1()
>         /usr/local/go/src/runtime/mheap.go:759 +0x4c
> runtime.(*mheap).alloc(0x11ca7a0, 0x9080, 0xc000010101, 0x43afc5)
>         /usr/local/go/src/runtime/mheap.go:758 +0x8a
> runtime.largeAlloc(0x12100000, 0x101, 0x1)
>         /usr/local/go/src/runtime/malloc.go:1019 +0x97
> runtime.mallocgc.func1()
>         /usr/local/go/src/runtime/malloc.go:914 +0x46
> runtime.systemstack(0xc000231110)
>         /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
> runtime.mstart()
>         /usr/local/go/src/runtime/proc.go:1229

are there any rules of thumb how much RAM is needed for checking a repo?

**Comment by cdhowie** [comment] 2018-11-17 17:00
I'm not sure how much RAM is needed to be honest, but you could try increasing the amount of swap on the system.  The check will probably cause the machine to thrash, however.  If you don't mind waiting some hours for the check to complete, it might be okay.

**Comment by flo82** [comment] 2018-11-18 18:59
increased the swap to 8 GB. still the same error (but different call stack).
Now trying again with 64 GB.

**Comment by cdhowie** [comment] 2018-11-18 20:05
Note that I would expect the call stack to be different every time, regardless of changes to swap.  Any small amount of activity on the machine is likely to cause a slightly different amount of memory to be available to restic on every invocation, causing it to run out of memory at different points in the check procedure.

For reference, I ran a check against a 68GB repository, and `/usr/bin/time -v` claims:

```
Maximum resident set size (kbytes): 826636
```

826MB isn't really that much.  If we assume that memory usage scales linearly with repository size, then it appears that the memory usage required to check a repository is a little over 1% of the total size of the repository.

How large is the repository you are trying to check?

**Comment by flo82** [comment] 2018-11-18 20:15
hmm... the backup is running for a couple of months now ;-) I'm keeping last 30 days, last 10 weeks, last 12 months and last 75 years - and delete the others.

so we have ~ 2400 GB of data. so 1% of 2400 GB = 24 GB.
let's see how long it takes and how much ram/swap it consumes.

any idea how to monitor the progress?

**Comment by cdhowie** [comment] 2018-11-18 20:46
I don't believe there is a way to monitor the progress of a check operation.

I just confirmed that memory consumption is NOT linear to the size of the repository in bytes.  I ran a check on another repository.

* Repo A: 68GB repository, check resident set peaked at 807MB.  (~86:1 ratio of size:RAM)
* Repo B: 159GB repository, check resident set peaked at 172MB.  (~946:1 ratio of size:RAM)

Note that repo A stores system backups, so the tree structures are fairly deep, and there are many small files.  Repo B stores file server backups.  Most of the files are photos, so the tree structure is fairly flat, and most of the files are big.

It seems that the number of objects in the repository has more of an impact on the amount of memory required than the overall repository size.

Interestingly, this should correlate to the size of the indexes, so let's look at the size of the indexes instead:

* Repo A: 109MB indexes, check resident set peaked at 807MB.  (~1:7.4 ratio of indexes:RAM)
* Repo B: 20MB indexes, check resident set peaked at 172MB.  (~1:8.6 ratio of indexes:RAM)

These ratios are much closer.  Let's approximate that to a 1:8 ratio.  How much data is in the index directory in this repository?  Multiply that by 8, and that's an approximation of the maximum resident set that restic will need to check it.

**Comment by flo82** [comment] 2018-11-18 21:11
here are the statistics of my archive. due to the fact that it is located on an azure-container and the check process is running, i can only provide bucket-statistics (the rough-statistics provided in my previous post were wrong - perhaps old cache values).

here are the absolute statistics of files and usage (count took over 3 minutes - so i hope they are correct now):
* data dir: 998.944 blobs; 5.177.332.257.266 bytes 
* index dir: 1.034 blobs; 804.419.013 bytes
* snapshots dir: 266 blobs; 73.727 bytes

804 MB index size * 8 = 6432 MB peak. During the last check 2 GB of ram and 8 GB of swap were not sufficient. I will monitor that and give feedback.

**Comment by mholt** [comment] 2018-11-18 21:14
> I don't believe there is a way to monitor the progress of a check operation.

That might be changing if #2003 successfully implements a command-agnostic progress reporter system :) /cc @ifedorenko  -- I for one would be happy to help integrate progress reporting for other commands like check, once that is ready.

**Comment by ifedorenko** [comment] 2018-11-19 12:44
#2003 already implements progress for `check`, `backup` and `restore` commands. give it a try and let me know if "ui" provides sufficient details. (hint: if you run headlessly or on non-ansi "dump" terminals, use `-v` flag to get less fancy but imho still very useful progress feedback).

**Comment by flo82** [comment] 2018-11-20 17:50
still running (started: So 18. Nov 19:57:46 CET 2018). so around 47 hours now.
Max. swap was 14.5% of 68GB = 9.86 GB

i received a couple of errors (ms change and filename in "locks" folder change):

`Save(<lock/7224ac0b9a>) returned error, retrying after 353.238012ms: CreateBlockBlobFromReader: Put https://xxx.blob.core.windows.net/resticazure/locks/7224ac0b9a3c80867d800be0e27d10cd87de445b7301d7d2da0e3337fa469844: net/http: TLS handshake timeout
`

Do I need to worry about them?

**Comment by cdhowie** [comment] 2018-11-20 22:18
> Do I need to worry about them?

Restic should continue to run, but it's not able to update the lock file.  As long as you don't have any concurrent Restic processes against this repo, you should be fine.

However, I might worry a bit about what is causing these timeouts in the first place.

**Comment by fd0** [comment] 2018-11-21 07:40
This sometimes happens with some services, notably B2. All operations are retried, so unless restic aborts there's no need for worry.

**Comment by flo82** [comment] 2018-11-21 16:02
so my check is finished:

```
Start: So 18. Nov 19:57:46 CET 2018
successfully removed locks
using temporary cache in /tmp/restic-check-cache-202571517
created new cache in /tmp/restic-check-cache-202571517
create exclusive lock for repository
load indexes
pack 9fd8fc40 contained in several indexes: {70be9a65 c93fcaae}
This is non-critical, you can run `restic rebuild-index' to correct this
check all packs
check snapshots, trees and blobs
no errors were found
End:   Mi 21. Nov 00:34:55 CET 2018
Duration: 52h:37m:9s
```
looks good to me. Max. swap was 14.5% of 68GB = 9.86 GB.

i'm afraid running rebuild-index because check took ~53h ;-)
how long would you expect running the rebuild-index command?
how much network traffic will be created?
what is the difference between prune und rebuild-index?
and would you recommend running check, rebuild-index and prune regulary? if yes when and any specific order?

**Comment by cdhowie** [comment] 2018-11-21 17:05
I can't answer all of those questions but I will answer some.

> what is the difference between prune und rebuild-index?

Prune does three things: (1) remove blobs not referenced by any snapshot, (2) remove duplicate blobs, and (3) rebuild the index.  Rebuild-index only rebuilds the index; it does not delete anything.

> and would you recommend running check, rebuild-index and prune regulary? if yes when and any specific order?

I would not manually run rebuild-index because that's one of the things prune does.  You don't need to run both commands.  (The only time you should need to run rebuild-index is if your indexes are damaged, and in that case, I would honestly just run prune... if you're going to fetch all the pack headers, you might as well potentially throw out some data at the same time.)

Prune will necessarily do some amount of checking, because it traverses every pack and every snapshot looking for blobs to delete.  (Note that it does not download the entirety of each pack, just the header from each pack to see what it contains, just like check (without `--read-data`) and rebuild-index.)

Prune is only useful if you have:

* Deleted some snapshots; there may be unused blobs that can be deleted, or
* Interrupted a backup; the uploaded blobs may be unused, or
* Run two or more backups concurrently; they may have each uploaded the same blob, and a prune would deduplicate them.

A specific case in which you might opt to run check instead of prune is if you want to test the consistency of the repository, but there are ongoing backups.  Prune cannot run at the same time as any other repository activity, but I believe check only uses a read lock and can therefore run concurrently with backups.

As far as how often to prune, that depends on how often you delete snapshots and how much data you can delete, on average.  Running prune against a repository in cloud storage will probably incur some transfer and request costs, similar to a check.  The question is whether you will make up for those costs with the amount of data that is removed.  This isn't really something I can answer for you.

**Comment by fd0** [comment] 2019-04-26 07:37
I just read through all the comments, this started out as a report that restic printed an error message which is very hard to understand, then we figured out that probably restic used too much memory. In the end, the `restic check` went through fine.

I think there's nothing we can do for this issue (apart from reducing restic's memory usage, see #1453 for that), so I'm closing this issue for now. Please feel free to add further comments. Thanks!

**Closed by fd0** 2019-04-26 07:37 UTC
