### ISSUE TITLE
Rendered system mostly unresponsive.

### ISSUE THREAD

**Issue by bfitzsimmons** [restic/restic#522] opened 2016-05-17 20:17 UTC
## Output of `restic version`

``` bash
$ restic version
restic 0.1.0 (v0.1.0-548-g795e3d5)
compiled at 2016-05-17 02:08:13 with go1.6.2
```
## Expected behavior

I expected my files to be backed up to S3.
## Actual behavior

My laptop became mostly unresponsive each time I tried this. I could still move the pointer, and switch between applications, but the applications wouldn't work (spinning beach ball).

I took a pic (using my phone) of the htop output (couldn't take a screenshot due to how things stopped working). Please note the memory usage on the top line.

![img_3581](https://cloud.githubusercontent.com/assets/538579/15337356/47dd9156-1c49-11e6-8713-c33d784c5435.JPG)
## Steps to reproduce the behavior

I ran the following command:

``` bash
restic -r s3://s3.amazonaws.com/bfitzsimmons-backups backup ~/code
```

**Comment by fd0** [comment] 2016-05-18 07:16
Hey, thanks a lot for your report!

Can you give me a bit more details about your setup?
 * What operating system do you use? It looks like darwin/OS X, but I'm not entirely sure.
 * How much data did you try to backup?
 * Do you remember how much data restic processed before the system became unresponsive?

Please note that the memory reported in the VIRT column of htop is not a good representation of how much memory the process really uses, that is listed in the RES column (and looks rather good, with only 303MiB).

I have a hunch why this behavior occurs: restic reads a lot of files, and all data read this way is added to the OS' file system cache. Over time, data that belongs to other running processes is moved from RAM to the swap. When you now switch to a different application, the system needs to move the data of that application back to the ram, which takes some time since restic is still busy reading files.

On Linux, we've implemented a fix by telling the operating system to discard data read by restic, since it's unlikely that we're going to read that data again in the near future. This was https://github.com/restic/restic/pull/487.

Could you confirm your OS and setup?

**Comment by bfitzsimmons** [comment] 2016-05-18 15:26
> On May 18, 2016, at 3:16 AM, Alexander Neumann <notifications@github.com> wrote:
> 
> Hey, thanks a lot for your report!
> 
> Can you give me a bit more details about your setup?
> 
> What operating system do you use? It looks like darwin/OS X, but I'm not entirely sure.
It is, indeed, OS X.
> How much data did you try to backup?
Approximately 16GB.
> Do you remember how much data restic processed before the system became unresponsive?
This was on a run after the initial backup had completed (not without multiple tracebacks). So, I guess this is the “grab anything that has changed” phase.
> Please note that the memory reported in the VIRT column of htop is not a good representation of how much memory the process really uses, that is listed in the RES column (and looks rather good, with only 303MiB).
> 
> I have a hunch why this behavior occurs: restic reads a lot of files, and all data read this way is added to the OS' file system cache. Over time, data that belongs to other running processes is moved from RAM to the swap. When you now switch to a different application, the system needs to move the data of that application back to the ram, which takes some time since restic is still busy reading files.
> 
That does match the behavior. It felt like an under-provisioned Linux server that was swapping itself to death. Only, in this case, I couldn’t see the disk activity as the activity monitor was one of the first apps to become unresponsive.
> On Linux, we've implemented a fix by telling the operating system to discard data read by restic, since it's unlikely that we're going to read that data again in the near future. This was #487 <https://github.com/restic/restic/pull/487>.
> 
> Could you confirm your OS and setup?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/restic/restic/issues/522#issuecomment-219945438>

Thanks for looking into this.


--
Brant Fitzsimmons
https://about.me/bfitzsimmons

**Comment by fd0** [comment] 2016-05-18 15:32
Thanks for confirming your setup. Unfortunately, my hypothesis does not line up with your observations: restic does not read data on a subsequent backup, it just checks timestamps.

Are you able to reproduce this bad behavior? Could you give it a try? If that works, can you create a debug log? Here are instructions: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs

Please have a look at the debug log before uploading it anywhere (you can also send it to me via email), as the file names are included in verbatim.

**Comment by bfitzsimmons** [comment] 2016-05-18 21:38
I'm able to reproduce the bad behavior each and every time I attempt to back up the ~/code dir. And each time I try it I have to power cycle the laptop to get it to become responsive again. I can't kill the process, or anything.  I can still type commands in the terminal, but them actually doing anything is inconsistent.

So, I have a very large debug log, and it does have private info. that I can't share. Is there anything in particular that you're looking for in the log that I could extract?

BTW, things don't appear to go south until *after* it counts the files. The next phase is where things start to fall apart.

**Comment by fd0** [comment] 2016-05-19 06:40
Sorry to phrase it that way but: It's a good thing you can reproduce it. This means we can try to find the cause.

I already suspected that the first scanning phase (when the files are counted) is not the cause.

You said that the first backup ran fine, so I have two ideas on how to proceed further:
 * Try running `restic backup --force`. This does not use the timestamp information from a former backup, but reads all files again, which means a slightly different code path.
 * Can you try backing up a small part of the large directory to a new repository and test whether this stops your system again?
 * If you can bear more tests, repeat the steps above with a local repository instead of s3.

For the reference, here is a bit background on the apparently high memory usage you saw in htop: https://deferpanic.com/blog/understanding-golang-memory-usage/

**Comment by bfitzsimmons** [comment] 2016-05-26 14:56
`restic backup --force` ran without issue.

I'll try backing up a smaller part of the directory.

**Comment by bfitzsimmons** [comment] 2016-05-26 15:41
Running the backup on a smaller subdir. did not go over nearly as well. I'm still recovering from it.

The initial backup went fine, but the update resulted in the same bad behavior.

I'll try the backup to a local repo. now.

**Comment by bfitzsimmons** [comment] 2016-05-26 16:48
The local backup (and update) worked just fine.

**Comment by fd0** [comment] 2016-06-08 18:58
This is strange, thanks for investigating!

**Comment by fd0** [comment] 2017-04-16 18:11
Could you please check whether this still occurs with the current master branch (or the 0.5.0 release)?

**Comment by fd0** [comment] 2017-09-15 17:15
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-09-15 17:15 UTC
Labels: bug, platform:Darwin
