### ISSUE TITLE
Initializing a new repository with v0.14.0 in B2 emits errors

### ISSUE THREAD

**Issue by jcasale** [restic/restic#3896] opened 2022-08-27 14:43 UTC
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

How did you run restic exactly?
-------------------------------
I am invoking through ssh in a bash shell. All the common parameters are supplied through environment variables.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
No errors are emitted when initializing a new repository.

Actual behavior
---------------
Two 404 errors are emitted to the console.

Steps to reproduce the behavior
-------------------------------
The following environment variables and command invocation reproduce the error:
```bash
# export TMPDIR=/tmp
# export RESTIC_CACHE_DIR=/tmp
# export RESTIC_REPOSITORY='b2:xyz:/'
# export RESTIC_PASSWORD='...'
# export B2_ACCOUNT_ID='...'
# export B2_ACCOUNT_KEY='...'
# export RESTIC_COMPRESSION=max
# export DEBUG_LOG=~/b2_bucket_init.log
# restic init --verbose=3
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
created restic repository c410391d33 at b2:xyz:/

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```

Do you have any idea what may have caused this?
-----------------------------------------------
No.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It helps me every day, I back up several hosts of various platforms daily. Great tool.

[b2_bucket_init.log](https://github.com/restic/restic/files/9438155/b2_bucket_init.log)

**Comment by MichaelEischer** [comment] 2022-08-27 20:06
This is a duplicate of #3750

**Closed by MichaelEischer** 2022-08-27 20:06 UTC
