### ISSUE TITLE
`--only-log-changed`

### ISSUE THREAD

**Issue by ShadowJonathan** [restic/restic#3540] opened 2021-10-06 10:23 UTC
Related to #1805

Output of `restic version`
--------------------------

`restic 0.12.1 compiled with go1.16.6 on linux/arm`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Only log changed files. When doing `restic backup --verbose=2`, i'd like to be able to add `--only-log-changed` to it so it does not log `unchanged`.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Currently my logs are filled with a slurry of `unchanged`, this is not very helpful when disseminating what files were actually stored, at a later date.

Note: i know that #1805 is supposed to fix this, but i have not seen much change in it, and i think that this opt-in logging exclusion would help my use-case quicker.

**Comment by MichaelEischer** [comment] 2021-10-09 18:26
You could probably use `restic [...] | grep -v "^unchanged "` to filter out these log lines. Or use the json output and filter it using `jq`.

Isn't the `--only-log-changed` option exactly what has been suggested as log level 2 in #1805?

**Comment by MichaelEischer** [comment] 2021-10-30 21:33
> That's harder to do when using restic in a systemd service file, i'm trying to clean up some of my logs with this.

The cleanest solution there would be to use a wrapper script for restic to filter the log output.

I'm closing this as duplicate of #1805 as it is necessary to do some planning on how to control the log output to avoid creating a mess of command-line options.

**Closed by MichaelEischer** 2021-10-30 21:33 UTC
Labels: state: need feedback
