### ISSUE TITLE
would it be possible to resore deleted (forget without prune) snapshots?

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4133] opened 2023-01-06 15:40 UTC
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
As I understand forget deletes a snapshot and prune deletes blobs and packs that are not referenced by a snapshot.
Between forget and prune it is possible to recover a (single?) snapshot with alle packs/blobs that are currently not referenced by a snapshot.

Maybe it would be better to only mark a snapshot as deleted or move them to some kind of recyclebin so they could be restored without a dummy-snapshot.

**Comment by mattxtaz** [comment] 2023-01-06 20:32
`restic help recover` is probably what you want

**Comment by AlBundy33** [comment] 2023-01-06 20:56
Forget to mention that I'm talking about `recover` (updated the text).

As far as I underetand recover searches for all packs that are not referenced by a snapshot and creates a single-recover-snapshot with those.

So the idea was to not delete the snapshots and just to mark them as deleted - with this we could restore the original snapshots.

Haven't tested it yet but what happens now if I backup a linux- and a windows-system tomthe same repository, forget one snapshot from each and use recover - wouldn't this end in a snapshot with directories from both? :thinking:

**Comment by MichaelEischer** [comment] 2023-01-07 23:21
Duplicate of #3415.

**Closed by MichaelEischer** 2023-01-07 23:21 UTC
