### ISSUE TITLE
enhancement: sftp support when reading from a file

### ISSUE THREAD

**Issue by danielb2** [restic/restic#1808] opened 2018-05-24 04:46 UTC
restic supports writing to a remote path via sftp, but is there any reason it doesn't allow me to read from sftp?

IOW:  `restic -r <repo> backup sftp:user@host:/path` much like rsync does.

**Comment by fd0** [comment] 2018-06-08 17:31
Yep, the reason is that it's not implemented (yet). With #1494, I've laid the groundwork for a file system abstraction, which allows us to (eventually) implement this. Stay tuned.

**Comment by danielb2** [comment] 2018-06-08 18:05
I had assumed that since it could write, the reading was very closely related insofar as being able to support it. Glad to hear this is coming :)

**Comment by MichaelEischer** [comment] 2020-10-05 19:26
Closing this as it's a duplicate of #299

**Closed by MichaelEischer** 2020-10-05 19:26 UTC
Labels: type: feature suggestion
