### ISSUE TITLE
a problem about pr check jobs

### ISSUE THREAD

**Issue by haoshuwei** [restic/restic#2522] opened 2019-12-17 11:07 UTC
I created a [PR](https://github.com/restic/restic/pull/2521) which need add new vendor files,  should I execute the command `go mod vendor` to add them or not?

If I execute the command above, the `1.13.x` job check failed with output:
```
error running tests: vendor/ directory was modified:
diff --git a/go.mod b/go.mod
index a166061..1dd4dd2 100644
--- a/go.mod
+++ b/go.mod
@@ -6,6 +6,7 @@ require (
 	github.com/Azure/azure-sdk-for-go v27.3.0+incompatible
 	github.com/Azure/go-autorest/autorest v0.9.2 // indirect
 	github.com/aliyun/aliyun-oss-go-sdk v2.0.4+incompatible
+	github.com/baiyubin/aliyun-sts-go-sdk v0.0.0-20180326062324-cfa1a18b161f // indirect
 	github.com/cenkalti/backoff v2.1.1+incompatible
 	github.com/cpuguy83/go-md2man v1.0.10 // indirect
 	github.com/dnaeon/go-vcr v1.0.1 // indirect
diff --git a/go.sum b/go.sum
index 4688c31..f828b5b 100644
--- a/go.sum
+++ b/go.sum
@@ -27,6 +27,8 @@ github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf/go.mod h1:ybxpYRF
 github.com/aliyun/aliyun-oss-go-sdk v2.0.4+incompatible h1:EaK5256H3ELiyaq5O/Zwd6fnghD6DqmZDQmmzzJklUU=
 github.com/aliyun/aliyun-oss-go-sdk v2.0.4+incompatible/go.mod h1:T/Aws4fEfogEE9v+HPhhw+CntffsBHJ8nXQCwKr0/g8=
 github.com/apache/thrift v0.12.0/go.mod h1:cp2SuWMxlEZw2r+iP2GNCdIi4C1qmUzdZFSVb+bacwQ=
+github.com/baiyubin/aliyun-sts-go-sdk v0.0.0-20180326062324-cfa1a18b161f h1:ZNv7On9kyUzm7fvRZumSyy/IUiSC7AzL0I1jKKtwooA=
+github.com/baiyubin/aliyun-sts-go-sdk v0.0.0-20180326062324-cfa1a18b161f/go.mod h1:AuiFmCCPBSrqvVMvuqFuk0qogytodnVFVSN5CeJB8Gc=
 github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973/go.mod h1:Dwedo/Wpr24TaqPxmxbtue+5NUziq4I4S80YR8gNf3Q=
 github.com/cenkalti/backoff v2.1.1+incompatible h1:tKJnvO2kl0zmb/jA5UKAt4VoEVw1qxKWjE/Bpp46npY=
 github.com/cenkalti/backoff v2.1.1+incompatible/go.mod h1:90ReRw6GdpyfrHakVjL/QHaoyV4aDUVVkXQJJJ3NXXM=
exit status 2
The command "go run run_integration_tests.go" exited with 1.
```

If I don't execute the command above, the `1.10.x` job check failed with output:
```
Stderr: internal/backend/oss/oss.go:5:2: cannot find package "github.com/aliyun/aliyun-oss-go-sdk/oss" in any of:
	/home/travis/gopath/src/github.com/restic/restic/vendor/github.com/aliyun/aliyun-oss-go-sdk/oss (vendor tree)
	/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/github.com/aliyun/aliyun-oss-go-sdk/oss (from $GOROOT)
	/home/travis/gopath/src/github.com/aliyun/aliyun-oss-go-sdk/oss (from $GOPATH)
```

**Comment by fd0** [comment] 2020-01-01 15:10
that's odd, I need to look into it. I'm not sure what's going on...

**Comment by fd0** [comment] 2020-02-26 20:37
I cannot reproduce this, so I'm closing this issue for now. Thanks!

**Closed by fd0** 2020-02-26 20:37 UTC
