### ISSUE TITLE
How to recover part of the data with abnormal upload

### ISSUE THREAD

**Issue by mumu-lab** [restic/restic#5181] opened 2024-12-16 03:45 UTC
When I use the REST Server backup mode, the backup is interrupted due to the abnormal shutdown of the server, and the client data has been lost and cannot be backed up after the recovery of the server. In this case, how should I restore the data that has been uploaded before the exception? Unfortunately, this part of the data does not generate a snapshot, how should I restore this part of the data.

**Comment by rawtaz** [comment] 2024-12-18 17:06
This issue is a duplicate of the solved forum thread [here](https://forum.restic.net/t/how-to-recover-part-of-the-data-with-abnormal-upload/8860), so I'm closing it.

**Closed by rawtaz** 2024-12-18 17:06 UTC
