### ISSUE TITLE
"pack not referenced in any index" after rebuild-index

### ISSUE THREAD

**Issue by viric** [restic/restic#435] opened 2016-02-12 08:41 UTC
I cannot get rid of "pack not referenced in any index" messages in "check", even after running rebuild-index.

Running rebuild-index (no matter how many times I run it) gives something like this:
```
rebuilding index from 2 indexes
  loading index 0
  loading index 1
  saving new index
removing 2 old indexes
checking for additional packs
  saving new index
added 34 packs to the index
```
There are always some "additional packs" at every run.

**Comment by fd0** [comment] 2016-02-12 08:45
Thanks for reporting this, I'll have look. It probably is a bug.

**Comment by viric** [comment] 2016-02-12 15:13
Is this bug dangerous? (possible loss of data)

**Comment by fd0** [comment] 2016-03-06 12:17
Please retry with latest master, I've rewritten the `rebuild-index` command.

**Comment by fd0** [comment] 2016-03-07 20:12
We've debugged this on IRC, the issue was caused by duplicate data blobs in pack files. It'll be possible to solve it using the upcoming `prune` command, see #479.

**Comment by fd0** [comment] 2016-08-23 19:39
This is fixed by now.

**Closed by fd0** 2016-08-23 19:39 UTC
Labels: bug, feedback needed
