### ISSUE TITLE
Error during first backup

### ISSUE THREAD

**Issue by nunofgs** [restic/restic#538] opened 2016-06-26 20:07 UTC
I'm trying out _restic_ for the first time. I have an unusual setup though. I'm running Docker on a raspberrypi2.

I essentially wrote a Dockerfile that contains `acdcli` and clones the restic repo runs `go run build.go`.

## Output of `restic version`
```
restic 0.1.0 (v0.1.0-553-g814424f)
compiled at 2016-06-25 15:01:45 with go1.6.2
```

## Steps to reproduce the behavior

```sh
$ export RESTIC_REPOSITORY=/mnt/backups
$ export RESTIC_PASSWORD=foobar
$ acdcli mount $RESTIC_REPOSITORY
$ restic init
$ restic backup /mnt/data
```

Crashes with:

```sh
panic: rename  /mnt/backups/data/ce/cee8d24ca19821196d761863fbae3336643054c690a30f5df35ea7d0bc6d2e59: no such file or directory

goroutine 137 [running]:
panic(0x492bd8, 0x10bf0380)
	/usr/lib/go/src/runtime/panic.go:481 +0x330
restic.(*Archiver).saveChunk(0x10a0ca50, 0x0, 0x9f7f4, 0x28700000, 0x13fca, 0x13dda000, 0x9f7f4, 0xc8000, 0x0, 0x76e3e0c8, ...)
	/tmp/restic-build-115497967/src/restic/archiver.go:165 +0x130
created by restic.(*Archiver).SaveFile
	/tmp/restic-build-115497967/src/restic/archiver.go:237 +0x410
```

Any ideas?

_EDIT_: possibly related to #504.

**Comment by fd0** [comment] 2016-06-27 10:00
Hey, thanks for raising this issue. I'm not sure it is a duplicate of #504, but I'd really like to find the cause of this issue.

Can you reproduce it? Did maybe the filesystem mounted at `/mnt/backups` vanish during the process?

**Comment by nunofgs** [comment] 2016-06-29 18:38
Yup, I can reproduce it reliably on my RaspberryPi.

It seems your hunch was correct. The underlying acdcli fuse mount throws an error after about an hour or two.

**Comment by fd0** [comment] 2016-06-29 19:41
So, apart from a better error message (i.e. not calling `panic()`), I don't think there is anything that restic can do here, so I'm closing the issue.

**Closed by fd0** 2016-06-29 19:41 UTC
Labels: bug, feedback needed
