### ISSUE TITLE
Restore only changed files

### ISSUE THREAD

**Issue by dmotte** [restic/restic#2662] opened 2020-03-22 21:00 UTC
Output of `restic version`
--------------------------

`restic 0.9.5 compiled with go1.12.4 on windows/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I know that this isn't a synchronization software, but it would be veeeery nice to implement a `restore` function which restores only changed files in a directory and deletes files which are present in that directory but not in the snapshot i am restoring. To better clarify this, think of it like a sort of `git checkout`

What are you trying to do?
--------------------------

Suppose that I have a 500GB folder `localdata` on my pc and a dir named `myrepo` on an SFTP server, in which i backup `localdata`. I would like to work on `localdata` in an agile mode, making frequent changes to the directory internal structure, moving files, renaming, deleting some useless content, ... and so on. Every time i feel it is necessary, i execute `restic backup -v localdata -r sftp:user@host:myrepo`

Suddenly, a week later i wake up and i find out that some of my important files in `localdata` are gone, because i deleted them accidentally or maybe my sister deleted them because she doesn't know how to properly use a computer... I'd like to fully restore a previous version of the folder from `myrepo` without the need of redownloading the entire 500GB data from the server. That's what i usually do with `git checkout <old_commit_id>` except that i don't have 500GB git repos :sweat_smile:

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yeah, this software solved me a lot of problems. I use it **daily** for my **main** backups. I also appreciate this wonderful idea of asking users some positive feedback here in issues.

Restic is awesome! Keep up the good work :wink:

**Comment by rawtaz** [comment] 2020-03-22 21:48
> I'd like to fully restore a previous version of the folder from `myrepo` without the need of redownloading the entire 500GB data from the server

This is what the `--include`, `--exclude` and `--iinclude`, `--iexclude` flags to `restic restore` are for, as well as the `restic mount` command which will allow you to just browse the files in your snapshot(s) and copy back the ones you want.

I'm not seeing your suggested feature being implemented anytime soon, so I'm curious if those two alternatives above doesn't work for you?

**Comment by dmotte** [comment] 2020-03-22 22:03
Yes i know about these flags, but this involve indeed browsing and manually
find differences between the local copy and the latest snapshot.
Furthermore, restic mount does not work on Windows. So unfortunately these
alternatives do not work for me :/

If you think that this feature is not relevant, feel free to close this
issue. Maybe in the future i will learn some Go and then make a pull
request, but for now i can't do it.

**Comment by brad2014** [comment] 2020-05-17 19:26
I was also wanting this, but I found `restic mount /backup` plus `rsync -a --delete /backup/<backupdir> <mydir>` to be a useful and performant substitute, also very flexible.

**Comment by dimejo** [comment] 2022-01-09 20:36
Sound like a duplicate of #2348.

**Comment by redstreet** [comment] 2022-01-21 00:35
A slightly more generic way to think about this functionality is like a `restic rsync` of sorts, which downloads the absolute minimum required to transform any arbitrary locally supplied state to the requested restic snapshot.

An intermediate step is to have functionality that expresses the diff of two arbitrary snapshots as:
1. data that is needed to transform one snapshot to another, plus
2. operations (eg: delete, change timestamps, etc.) to transform one snapshot to another

With the above, one can do things like:
- allow user to download a diff between two snapshots
- [make restores resumable](https://github.com/restic/restic/issues/407)
-  supply a local snapshot state, and have restic transform that into a requested snapshot state, while downloading the minimum of data required to do so (which is the main benefit)
- `restic rsync` functionality: supply an arbitrary local state (any set of files) and have restic transform that into a requested snapshot state, while downloading the minimum of data required to do so (which is the main benefit)

Restic has all the fundamental building blocks necessary to build a `restic rsync` functionality.

**Comment by nickchomey** [comment] 2022-04-29 18:46
I'd love this funcitonality as well. I'm very surprised it isn't already the default! I hope #3425 can get merged soon!

**Comment by mamoit** [comment] 2023-07-25 11:52
I'll explain my use case because it seems to be a little bit different from the original intention of this issue but I really don't want to spam a new issue.

I'm trying to use restic to restore a snapshot while minimizing data transfer from the repository.
The backup size can easily reach the TBs so doing a full restore is a very long task that can easily become very expensive.

The obvious option is to do what was proposed by @brad2014, `restic mount` and `rsync`.
The problem is that I'm running from within a container and `restic mount` requires elevating the container permissions more than I would like :disappointed:

If there was a way for the restore to skip whatever is already on disk using the same `mtime` and size comparison to decide what to restore like the `backup` command does it would save a lot of bandwidth and time.
Deletion of extraneous files that appeared in the meantime would also be a plus, but I feel that should be a separate flag.

**Comment by MichaelEischer** [comment] 2023-07-29 18:05
@mamoit Would https://github.com/restic/restic/pull/3425 solve your problem? Or would first reading every file from disk be too slow for you?

**Comment by mamoit** [comment] 2023-08-01 11:50
@MichaelEischer It's better than nothing, but it would be great if checking the file content would be an optional argument with default off.
What the PR you linked to is doing seems to be to implement #1620 but for restores, which is more than what the backup does right now.
In my usecase it would take forever (large dataset over NFS), but it would still be better than restoring everything again.

**Comment by luckydonald** [comment] 2023-12-01 03:48
Note, this would be also desperately needed for #4575 where I'm thinking about a `--inplace` option to the restore.

**Comment by luckydonald** [comment] 2023-12-01 03:55
Thinking of this I think the logic could be like this:

- if you restore to an empty folder, let's go (after all, nothing will be overwritten)
- if filesystem is equal to some snapshot: just add/delete files to get to the version as requested. (after all we have a backup)
- if you have modified files, keep those unless `--delete-modified-files` is set.

**Closed** 2024-06-13 19:26 UTC
Labels: type: feature enhancement, category: restore, state: need direction

**Comment by luckydonald** [comment] 2024-06-26 20:31
Fantastic!
