### ISSUE TITLE
include file

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#1472] opened 2017-12-06 08:07 UTC
Hey,

great restic but an feature i missing.
```--include-from file```

example structure:
/folder1
/folder2/dir1
/folder2/dir2
/folder2/dir3/dir1

example for exclude file:
/folder1
/folder2/*

example for include file:
/folder2/*/dir1

greetings sam

**Comment by moritzdietz** [comment] 2017-12-06 20:53
Hi @unclesamwk please make sure to read the [Guide](https://github.com/restic/restic/blob/master/CONTRIBUTING.md) for creating an issue here.

Be sure to check which version of restic you are running. 
In current version there is support for this kind of feature. Please see the documentation here: http://restic.readthedocs.io/en/latest/040_backup.html

**Comment by fd0** [comment] 2017-12-06 20:59
Mixing include and exclude patterns requires complex code, and we haven't implemented that yet. Its eventual implementation is tracked in #233. I'm closing this as a duplicate of #233.

As @moritzdietz already pointed out it'd be nice if you could fill out the issue template, that helps us a lot. Thanks!

**Closed by fd0** 2017-12-06 20:59 UTC
