### ISSUE TITLE
self-update doesn't work on Windows

### ISSUE THREAD

**Issue by cfbao** [restic/restic#2248] opened 2019-04-23 15:44 UTC
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on windows/amd64

How did you run restic exactly?
-------------------------------
```
>>> restic self-update
writing restic to C:\<...>\restic\restic.exe
find latest release of restic at GitHub
latest version is 0.9.5
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.9.5_windows_amd64.zip
downloaded restic_0.9.5_windows_amd64.zip
Fatal: unable to update restic: unable to remove target file: remove C:\<...>\restic\restic.exe: Access is denied.
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A

Expected behavior
-----------------
Update the binary.

Actual behavior
---------------
restic unable to update itself.

Steps to reproduce the behavior
-------------------------------
Run `restic self-update` on Windows.

Do you have any idea what may have caused this?
-----------------------------------------------
Windows doesn't allow write access to a running executable.

Do you have an idea how to solve the issue?
-------------------------------------------
Just an idea:
* Download the new binary
* Rename its old self to `<original-path/name>-old` (or move to `$TMP/<original-name>`)
* Move and rename the new binary to `<original-path/name>`
* Automatically launch the new binary then exit
* The new binary automatically cleans up the old version then exits

Did restic help you or made you happy in any way?
-------------------------------------------------
Absolutely. Having efficient, regular, and secure backups is awesome.

**Comment by NovacomExperts** [comment] 2019-04-24 14:45
Issue confirmed.

Reproductible on all my Windows installs. I guess restic.exe being "in use" is preventing overwriting itself.

I would suggest this, based on @cfbao 

- Download the new binary in current path - randomizing the name partly.
- Validate file, extract and run the new version with "interim self-update" mode, freeing lock from restic.exe 
- New binary "interim self-update" mode copies itself as restic.exe (original exe)
- New binary "interim self-update" mode automatically runs restic.exe
- Restic.exe cleanup the updates files, prints confirms update version and exit

**Comment by fd0** [comment] 2019-04-24 14:59
Sigh, this complicates everything. Thanks for the report though!

**Comment by NovacomExperts** [comment] 2019-04-24 15:58
Agreed. At some point, there will be a need for special windows "handling". I can think of file metadata ACLs / users / groups and... updates. 

For now, at least we are are of the issue. I will just use a curl.exe command before restic to get the latest restic.exe from my internal network.

**Comment by fd0** [comment] 2019-04-24 17:41
> I will just use a curl.exe command before restic to get the latest restic.exe from my internal network.

Ah, then rather use `restic self-update --output temp-restic.exe`, that'll at least very the authenticity of the binary. You can then move it to the right location manually.

**Comment by NovacomExperts** [comment] 2019-04-24 18:18
Great tip ! Thanks @fd0

**Comment by Confuset** [comment] 2019-04-29 08:24
On windows you can at least rename the file on reboot.
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-movefileexa
with the flag MOVEFILE_DELAY_UNTIL_REBOOT
a reboot might be overkill, but at least its an automated step and less fragile then using restic in interim mode.

**OR**

 check out the 4th solution here https://www.codeproject.com/Questions/621666/Download-and-replace-running-EXE 
1) File.Delete any previous myprogram.bak file
2) File.Move the myprogram.exe to myprogram.bak.
3) File.Copy the /updates/myprogram.exe to /myprogram.exe location.
4) ask the user if they want to restart, calling Application.Restart()

it looks like you can not delete, but move an executing executable.

**Comment by saviodsouza** [comment] 2019-05-21 14:13
Minio.exe update

Updates successfully on windows. Written in Go
Can the update code be copied.

**Comment by gab** [comment] 2019-05-27 01:42
The readme.md says "It supports the three major operating systems (Linux, macOS, Windows)".

Could the claim that restic supports Windows please be removed until this and any other major issues with Windows support are fixed (or at least, put a big fat mention that it's in Beta)?

**Comment by cfbao** [comment] 2019-05-27 01:52
> Could the claim that restic supports Windows please be removed until this and any other major issues with Windows support are fixed (or at least, put a big fat mention that it's in Beta)?

Let's not be overdramatic. restic backs up data on Windows well. There may be a few more bugs and a few missing features, but nothing major that prevents you from using it effectively on Windows.

Also, please don't sidetrack this issue's discussion.

**Comment by chrestomanci** [comment] 2019-06-08 17:48
> Ah, then rather use `restic self-update --output temp-restic.exe`, that'll at least verify the authenticity of the binary. You can then move it to the right location manually.

I think that something like that should be the default on all operating systems.

Currently, if you run restic self-update on linux, and it gets interrupted while it is running, you end up with a truncated and useless restic binary. It would be much better if the replacement of the old binary with the new is done via some sort of atomic operation.

**Comment by lucarota** [comment] 2020-07-06 09:05
Hi,

Can I suggest this library https://github.com/inconshreveable/go-update ? 
With go-update you can build self-updating Go programs and Windows is supported.

**Comment by cdhowie** [comment] 2020-12-31 11:08
> Ah, then rather use `restic self-update --output temp-restic.exe`, that'll at least verify the authenticity of the binary. You can then move it to the right location manually.

Unfortunately, that does not work on Windows either:

```
>restic self-update --output resticnew.exe
CreateFile resticnew.exe: The system cannot find the file specified.
```

**Comment by mvermaes** [comment] 2021-01-04 01:48
> Unfortunately, that does not work on Windows either:
> 
> ```
> >restic self-update --output resticnew.exe
> CreateFile resticnew.exe: The system cannot find the file specified.
> ```

It looks like [a fix for this](https://github.com/restic/restic/pull/2937) was added in 0.11.

I haven't tried it myself - I had been using the workaround of [pre-creating the new binary location in advance](https://github.com/restic/restic/issues/2491#issuecomment-695350041), not realizing it was no longer necessary to do this.

**Comment by ItsMattL** [comment] 2021-08-23 15:24
Moving the running binary before writing the updated version in place version will indeed fix the issue. The running binary remains locked while running, but it can rename itself to something else. Since we have so many options, I'd like to get some input from the restic maintainers (@fd0 ?) before I submit a patch.

1. Do we want to change the behavior for all operating systems, or only for Windows? Renaming the binary may not be necessary on some non-Windows platforms, but it theoretically shouldn't hurt either, and treating Windows separately will add code complexity.
2. Where do we want the old binary to go? Stay in program directory (renamed to .bak or something), moved to system temp directory, etc?
3. Do we want/need to handle clean up? Cleanup has to happen after the original version has exited, so there will need to be an out of band cleanup that can run on subsequent executions. Restic could always check for .bak files on startup, but this adds overhead and complexity. Moving to a temp directory arguably just puts the system in charge of cleaning everything up for us, although Windows isn't always great at this.
4. Other thoughts?

**Comment by ygoe** [comment] 2022-03-19 12:00
What about this:

1. Update to a separate file in any case (all platforms), also for safety.
2. Once the new files exists and is correct, move it to the original file. This process is platform-specific. On Linux, you can use the `mv` command (or its equivalent function call), on Windows you need to do this from a separate process (every Windows devloper knows that running executable files are locked, it has always been like that and will always be because of the way the Windows kernel works). Just run a command like `cmd /c timeout /t 1 && move restic.tmp restic.exe` and exit the restic process immediately.

**Closed** 2022-04-09 19:55 UTC
Labels: type: bug, help: wanted, platform: windows

**Comment by ygoe** [comment] 2022-04-09 21:06
Thank you! I didn't know you can rename the own executable on Windows. That makes my suggestion above unnecessary complicated.
