### ISSUE TITLE
Can't access lock file when performing forget/check

### ISSUE THREAD

**Issue by jarmo** [restic/restic#2067] opened 2018-10-28 10:44 UTC
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on windows/amd64

How did you run restic exactly?
-------------------------------
I'm running three restic commands sequentially - backup, forget (with prune) and check.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local disk. Windows 10 Pro.

Expected behavior
-----------------
I expect all these commands to work without any errors every time.

Actual behavior
---------------
I'm running `backup` with `--quiet` flag and I don't see any error messages spit out, which makes me believe that backup itself is done successfully. However, running `forget` after backup shows the following output:

```
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 588.946255ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 546.672148ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 896.500398ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 1.171012508s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 3.351752264s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 5.172108509s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 5.102365118s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 11.36725609s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 8.257503061s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 15.848447829s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 320.7184ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 640.466149ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 898.972917ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 1.300936819s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 1.80019984s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 3.91249865s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 8.306766816s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 9.899700585s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 10.140919524s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 20.143098869s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Applying Policy: keep the last 60 snapshots, 30 daily, 4 weekly, 3 monthly snapshots
snapshots for (host [emperor], paths [j:\documents]):
...
# list of snapshots follow here
```

And after that I see output from `check` (which implies that `forget` exited with exit code 0 since I'm running commands with `&&`):

```
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 621.861845ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 845.062006ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 843.481213ms: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 1.261209931s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 3.236096517s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 2.22105914s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 8.320329679s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 12.01927326s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: Access is denied.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 12.207128758s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: The system cannot find the file specified.
Load(<lock/c36d0cf6d4>, 0, 0) returned error, retrying after 21.332079465s: open \\?\j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec: The system cannot find the file specified.
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

Again, it seems that this command exits successfully. However, notice that the lock file name is exactly the same between `forget` and `check` commands!

Steps to reproduce the behavior
-------------------------------

Hard to say since it doesn't happen every time and not with every repo (I'm backing up different disks to different repos).

Do you have any idea what may have caused this?
-----------------------------------------------
I'm having one backup process running at the same time (backing up once every day) so there's no way that some other restic process accesses the same repo at the exact same time. There seems to be some problem regarding cleaning up the lock file or some other problem (although "Access denied" error seems weird).

Do you have an idea how to solve the issue?
-------------------------------------------
I don't know how these lock files are exactly created by restic, but it seems to me that there are no actual file locks used - if it were then lock files would not have locks on them anymore after process exit. However, maybe that is not the reason at all since there is this weird "Access denied" error. Is restic doing anything weird with the NTFS file system ACL and lock files?

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, of course!

**Comment by fd0** [comment] 2018-10-28 13:16
Hm, it looks like there's a leftover lock file in the repo that restic is unable to read. Did you run a backup with the privileges of a different account, and maybe that one was aborted? Can you try running `restic unlock`, and if that does not help, manually remove the file? That should get you out of this situation.

**Comment by jarmo** [comment] 2018-11-09 09:54
Sorry for long delay for reply. To answer your questions - no, I'm running backup once per day using Windows Task Scheduler having only one active restic process per repo (I will explain below) and I will receive an e-mail when backup has completed. I'm receiving that e-mail and it has lock warnings in it. I can see that this lock error does not happen every time and happens with different disks.

Just for clarification - I'm backing up different physical disks to different restic repositories on a backup disk. I'm doing it sequentially and not in parallel.

**Comment by mholt** [comment] 2018-11-09 16:41
Unlock is safe to run, it only removes stale locks. If you use --remove-all (or something like that, can't remember off-hand) it gets a little dicey but only if you have conflicting operations running at the same time.

**Comment by jarmo** [comment] 2018-11-11 12:34
Okay, but isn't original problem the fact that there are any stale locks? Shouldn't they be removed after process exits in any way?

**Comment by fd0** [comment] 2018-11-11 12:47
At some point, one instance of restic left a lock file in the repo. You're right, that should not happen. I don't have any idea why it happened. The next time restic is run, it tried to access the file and was not granted access by the operating system. Did you maybe at one point in time run restic with a different user account? Or did some (automatic?) process change the ownership or access modes for the files in the repo?

Can you check the access rights for the file `j:\backup\locks\c36d0cf6d432c72d82c90d7adce5c4f3614c7591bc5163d0d0566b1748a3ceec`?

**Comment by jarmo** [comment] 2018-11-11 12:53
No, as already stated then restic is being run only by Windows Task Scheduler once per day. It has also ticked `Run with highest privileges`. It seems that restic exits and lock file is not cleaned up everytime. However, I cannot check access rights since that lock file will be deleted at one point (see error message `The system cannot find the file specified.` above). This makes it seem that after some wait time lock file will be removed after all.

Is there any reason why actual file locking mechanism by OS is not used so that locks would be automatically released no matter what happens with the restic process?

**Comment by mholt** [comment] 2018-11-11 15:01
> Is there any reason why actual file locking mechanism by OS is not used so that locks would be automatically released no matter what happens with the restic process?

Probably because restic is designed to work cross platform instead of locking into s particular file system.

**Comment by jarmo** [comment] 2019-01-02 08:31
I'm having `restic unlock --remove-all` now before *backup*, *forget* and *check*. It still fails occasionally. For example:
```
Remove(<lock/ecf878fc84>) returned error, retrying after 468.745285ms: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 590.792243ms: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 1.624251763s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 1.374102459s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 1.439923449s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 2.083217688s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 7.200532415s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 6.170866771s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 11.871376183s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Remove(<lock/ecf878fc84>) returned error, retrying after 16.589776768s: Chmod: chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
chmod \\?\j:\backup\locks\ecf878fc846ead2d4c0c8c48df05ea945ceca7b57b16530fea0cf4cce6e320e2: Access is denied.
Chmod
github.com/restic/restic/internal/backend/local.(*Local).Remove
	/restic/internal/backend/local/local.go:222
github.com/restic/restic/internal/limiter.(*rateLimitedBackend).Remove
	<autogenerated>:1
github.com/restic/restic/internal/backend.(*RetryBackend).Remove.func1
	/restic/internal/backend/backend_retry.go:98
github.com/cenkalti/backoff.RetryNotify
	/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Remove
	/restic/internal/backend/backend_retry.go:97
github.com/restic/restic/internal/restic.RemoveAllLocks.func1
	/restic/internal/restic/lock.go:296
github.com/restic/restic/internal/repository.(*Repository).List.func1
	/restic/internal/repository/repository.go:585
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
	/restic/internal/backend/backend_retry.go:133
github.com/restic/restic/internal/backend/local.(*Local).List.func1
	/restic/internal/backend/local/local.go:267
path/filepath.walk
	/usr/local/go/src/path/filepath/path.go:358
path/filepath.walk
	/usr/local/go/src/path/filepath/path.go:382
path/filepath.Walk
	/usr/local/go/src/path/filepath/path.go:404
github.com/restic/restic/internal/fs.Walk
	/restic/internal/fs/file.go:99
github.com/restic/restic/internal/backend/local.(*Local).List
	/restic/internal/backend/local/local.go:238
github.com/restic/restic/internal/limiter.(*rateLimitedBackend).List
	<autogenerated>:1
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
	/restic/internal/backend/backend_retry.go:127
github.com/cenkalti/backoff.RetryNotify
	/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).List
	/restic/internal/backend/backend_retry.go:126
github.com/restic/restic/internal/repository.(*Repository).List
	/restic/internal/repository/repository.go:579
github.com/restic/restic/internal/restic.RemoveAllLocks
	/restic/internal/restic/lock.go:295
main.runUnlock
	/restic/cmd/restic/cmd_unlock.go:44
main.glob..func24
	/restic/cmd/restic/cmd_unlock.go:16
github.com/spf13/cobra.(*Command).execute
	/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/go/src/runtime/proc.go:201
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

And let me re-iterate - there is only once process of this whole thing running by Task Scheduler and it is always ran with the same user rights. I don't understand how it is even possible that it will get access denied errors.

Without me doing anything with these locks/problems, the next morning there might be no errors whatsoever so it's not happening 100% of the time.

**Comment by MichaelEischer** [comment] 2020-10-06 10:04
@jarmo Does this issue still exist? Could this be interference by some anti-virus software? As you stated that there is only one restic process running, it must be some external interference.

**Comment by MichaelEischer** [comment] 2020-12-29 21:33
Closing this issue for now as it seems like it is caused by something external and not restic.

**Closed by MichaelEischer** 2020-12-29 21:33 UTC
Labels: platform: windows, state: need feedback, state: need investigating, type: bug

**Comment by jarmo** [comment] 2020-12-29 21:59
I can confirm that I have not experienced this problem anymore. Running restic version 0.11.0.
