### ISSUE TITLE
Small file backup may trigger memory leak

### ISSUE THREAD

**Issue by ruanchen** [restic/restic#3084] opened 2020-11-11 09:02 UTC
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r myrepo backup bigfile.txt

pidstat -r -p resticPid 1

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3 backend

Expected behavior
-----------------
Memory keeps stable

Actual behavior
---------------
When backup, memery keeps add from 136MB to 445MB. My file is 100GB and I split it to every 512k file, and the file counts are 204800.

Steps to reproduce the behavior
-------------------------------
Bigfile more than 100GB, and split it to every one less than 1MB, and start backup

Do you have any idea what may have caused this?
-----------------------------------------------
restic do not free the memory or restic keeps the files and flush them to backend finally 

Do you have an idea how to solve the issue?
-------------------------------------------
I am not sure

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
i am happy everyday

**Comment by fd0** [comment] 2020-11-11 10:03
Thanks for the report. Restic keeps track of what data is stored in the repo, so if you add more data, restic needs more memory for the so-called "index".

Why do you think it is a memory leak?

Why did you split the 100GB file into many smaller files? Restic would be **much** more efficient if it could handle the large file directly.

**Comment by ruanchen** [comment] 2020-11-11 10:11
@fd0 Thanks for your reply.
What make the difference is when I backup a 100GB file, the memory is stable and smaller,but when I backup the small files, the memory is gradually increased,still the end of this backup,which I think may cause the memory leak.
Consider various scenarios,I need test for different files, not just small files or large files.

**Comment by fd0** [comment] 2020-11-11 13:53
> when I backup the small files, the memory is gradually increased,still the end of this backup

Yes: in this case, restic needs to handle much more metadata so it needs more memory.

> which I think may cause the memory leak

That's not a memory leak, that's regular usage.

I'm closing this issue, it is not a bug in restic. Please feel free to add further comments. Thanks!

**Closed by fd0** 2020-11-11 13:53 UTC
Labels: state: need feedback
