### ISSUE TITLE
Restore to another directory, exclude parent structure

### ISSUE THREAD

**Issue by peixotorms** [restic/restic#2803] opened 2020-06-21 17:50 UTC
Hi,

On my production server, I am creating a snapshot on the path `/var/www/public_html`
It works great, however now I would like to restore it to another server, on another path.

I do `restic -r b2:mybucket:database restore latest --target /home/sites/staging --path "/var/www/public_html" --host myhostname` and I would expect to get the data from `public_html` directly inside my target.

Instead, I get `/home/sites/staging/var/www/public_html` so is there any way to achieve this directly with restic?

Also how is this going to work if I want to restore it on windows with the different slash formats?

Thanks

**Comment by rawtaz** [comment] 2020-06-21 18:05
@peixotorms This is a usage question, not a bug report or feature request. Please post it in [the restic forum](https://forum.restic.net/) instead, as instructed in the issue template when opening a new issue :) You could also look into the `restic help restore` information, as I don't think the `--path` argument does what you think it does. That said I'm closing this for now, see you in the forum!

**Closed by rawtaz** 2020-06-21 18:05 UTC
