### ISSUE TITLE
Strange errors/messages on SIGINT

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [restic/restic#1543] opened 2018-01-10 23:53 UTC
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```
On Kubuntu 16.04.

## How did you run restic exactly?
(this is in a bash script)
```
export B2_ACCOUNT_ID="..."
export B2_ACCOUNT_KEY="..."
export RESTIC_REPOSITORY="b2:..."
export RESTIC_PASSWORD="..."

ionice -c2 nice -n19 ./restic backup \
  --files-from $HOME/restic/include.txt \
  --exclude-file=$HOME/restic/exclude.txt \
  -o b2.connections=10
```

## What backend/server/service did you use to store the repository?

Backblaze B2

## Expected behavior

When I sent SIGINT through Konsole with Ctrl-C, I expected a clean abort of the backup process.

## Actual behavior

Instead, I got this:
```

  signal interrupt received, cleaning up

error while saving data to the repo: context canceled
Close
github.com/restic/restic/internal/backend/b2.(*b2Backend).Save
        src/github.com/restic/restic/internal/backend/b2/b2.go:214
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        src/github.com/restic/restic/internal/backend/backend_retry.go:71
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        src/github.com/restic/restic/internal/backend/backend_retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        src/github.com/restic/restic/internal/backend/backend_retry.go:65
github.com/restic/restic/internal/cache.(*Backend).Save
        src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:253
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:618
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:106
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:171
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: Close: context canceled

goroutine 2565 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc420473020, 0xe39760, 0xc420059300, 0x521933, 0x12c85c, 0xc6764b5600000, 0xc42620a000, 0x12c85c, 0x13a000, 0xc420460000, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:176 +0x41b
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:250 +0x3d0
```

## Steps to reproduce the behavior

This happened every time I tried to abort a backup with SIGINT. If it's at all relevant, this was an initial backup to a recently initialized and empty repository.

## Do you have any idea what may have caused this?

Possibly related to changes made around #1434 ? This isn't #1434 though; restic aborts immediately after receiving SIGINT.

I don't really know enough about Go or Restic's internals to have any other credible guess.

## Do you have an idea how to solve the issue?

No.

## Did restic help you or made you happy in any way?

Restic looks great, and I'm hoping it will -- I'll let you know once I've got it set up and running. This is the first decent looking piece of Linux backup software I've seen.

**Comment by fd0** [comment] 2018-01-14 09:57
Hey, thanks for the report. The issue is known and will be solved with the new archiver code in #1494, the old archiver code simply has no good way of returning this error, so it spews out the stacktrace and exits the whole process.

I'm going to close this issue for now, please feel free to add further comments. Thanks!

**Closed by fd0** 2018-01-14 09:57 UTC
