### ISSUE TITLE
Slow restore from Azure blob

### ISSUE THREAD

**Issue by ediazrod** [restic/restic#1740] opened 2018-04-30 08:37 UTC
## Output of `restic version`
ediaz@debianbackup:~$ restic version
restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?
restic -r azure:backup1234:/ restore 506f64d6 --target /datos/datosbackup/backupadycorestore/

I add the commands to avoid password and the command works perfectly

## What backend/server/service did you use to store the repository?

Azure

## Expected behavior

The speed recover is 3Mbytes

## Actual behavior

Better speed recover like 8Mbytes of more (the speed of the line is 30Mbytes

## Steps to reproduce the behavior

I try on two diferent machines.

## Do you have any idea what may have caused this?

I don't know maybe concurrent access to the blob storage?

## Do you have an idea how to solve the issue?

may be add concurrent access to the blob storage

## Did restic help you or made you happy in any way?

Is a great product but I don't know why don't get any stats on restore (speed and files transfer).

**Comment by ifedorenko** [comment] 2018-04-30 12:40
#1719 will almost certainly improve restore performance with azure. not only will restic restore multiple files concurrently, it will also make fewer remote requests to azure.

**Comment by ediazrod** [comment] 2018-05-02 20:57
It is already  committed? I see in the log some conflict files, regards!

**Comment by ifedorenko** [comment] 2018-05-03 02:54
no, the restore optimizations haven't been merged yet, but I rebased the branch on master and I encourage you to try it.

**Comment by fd0** [comment] 2018-05-05 10:51
Thanks for the report. This is also a duplicate of #1605 (it's independent of the backend used), please subscribe over there to be notified of the progress resolving it.

I'm closing this issue here, please see #1605.

**Closed by fd0** 2018-05-05 10:51 UTC

**Comment by fpytloun** [comment] 2020-04-02 23:22
Did the fix really help to make restore faster? It seems to be still too slow - I restored 1,3GB in 2 hours on Azure VM (so network is not a bottleneck) and still not finished. Running with `-o azure.connections=30`.

**Comment by ifedorenko** [comment] 2020-04-02 23:42
#2195 is reported to have solved restore of large files by many users. You do need to use latest master as it hasn't been included in an official release yet (afaik). If you still see slow restore performance, please open new issue and provide steps I can use to reproduce it.

**Comment by fpytloun** [comment] 2020-04-03 08:30
@ifedorenko Thank you for info. I tried latest beta build and it's working. What took 3 hours takes now 5 minutes.. :-)
