### ISSUE TITLE
On snapshot, restic complains about index load errors for non-existing indexes

### ISSUE THREAD

**Issue by youam** [restic/restic#1788] opened 2018-05-19 10:44 UTC
## Output of `restic version`
```
restic 0.8.3
compiled with go1.10 on linux/amd64
```

this is the original binary from https://github.com/restic/restic/releases/download/v0.8.3/restic_0.8.3_linux_amd64.bz2

While debugging, https://beta.restic.net/restic-v0.8.3-269-gecfe5923/restic_v0.8.3-269-gecfe5923_linux_amd64 was also used.

## How did you run restic exactly?

The full command used is:
```
cat /dev/vg/vm-win10 | /usr/local/bin/restic -r rest:http://vmimages:RESTPASS@RASPBERRY:8000/vmimages --password-file /etc/restic/vm-pass backup --hostname vm-win10 --stdin --stdin-filename vm-win10.img
```

## What backend/server/service did you use to store the repository?

The remote repository is running on a rpi3 with ```rest-server 0.9.7 compiled with go1.10 on linux/arm64```, also from github's release page.

The repository was pruned by running restic on the rpi directly (also with the latest 0.8.3 image from github). While pruning, the filesystem (btrfs) ran out of space repeatedly, the prune aborted and was restarted after adding more free space. restic check on the repository reports no error

## Expected behavior

A new backup is created without showing any errors or warnings

## Actual behavior

The command above runs every night with cron.

Invesitgating with restic snapshots on the rpi, shows this output:
```
password is correct
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
[...]
ed119cd9  2018-05-14 02:04:24  vm-win10                vm-win10.img
4f2af5f6  2018-05-15 02:04:10  vm-win10                vm-win10.img
5a8fca41  2018-05-18 11:43:00  vm-win10                /root/vm-win10.img
43d54103  2018-05-18 11:48:46  vm-win10                vm-win10.img
c927581e  2018-05-19 02:04:18  vm-win10                vm-win10.img
0a092ebf  2018-05-19 12:14:33  vm-win10                vm-win10.img
----------------------------------------------------------------------
27 snapshots
```

So, daily snapshots until the prune completed. From then on, the nightly backup failed.

Cron shows the following output for the nightly backup for 2018-05-16, which did not leave a finished snapshot:
```
Load(<index/40668bca1e>, 0, 0) returned error, retrying after 728.090219ms: <index/40668bca1e> does not exist
Load(<index/2e0a6ebfb5>, 0, 0) returned error, retrying after 622.982319ms: <index/2e0a6ebfb5> does not exist
Load(<index/1724d49bc8>, 0, 0) returned error, retrying after 737.493357ms: <index/1724d49bc8> does not exist
Load(<index/2e0a6ebfb5>, 0, 0) returned error, retrying after 939.354339ms: <index/2e0a6ebfb5> does not exist
Load(<index/40668bca1e>, 0, 0) returned error, retrying after 1.020464335s: <index/40668bca1e> does not exist
Load(<index/1724d49bc8>, 0, 0) returned error, retrying after 773.153315ms: <index/1724d49bc8> does not exist
Load(<index/1724d49bc8>, 0, 0) returned error, retrying after 1.347041612s: <index/1724d49bc8> does not exist
Load(<index/2e0a6ebfb5>, 0, 0) returned error, retrying after 1.372138514s: <index/2e0a6ebfb5> does not exist
[... about 50 more ...]
Load(<index/40668bca1e>, 0, 0) returned error, retrying after 19.888040857s: <index/40668bca1e> does not exist
Load(<index/2e0a6ebfb5>, 0, 0) returned error, retrying after 9.840845217s: <index/2e0a6ebfb5> does not exist
<index/1724d49bc8> does not exist, ignoring
<index/2e0a6ebfb5> does not exist, ignoring
<index/40668bca1e> does not exist, ignoring
Save(<data/c185b0ec22>) returned error, retrying after 648.43575ms: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 806.472256ms: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 1.370555821s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 1.34720084s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 3.755806287s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 3.370044044s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 7.866627841s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 4.305309552s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 15.177706681s: server response unexpected: 400 Bad Request (400)
Save(<data/c185b0ec22>) returned error, retrying after 20.290664968s: server response unexpected: 400 Bad Request (400)
[1:07] 20.861 MiB  0B/s

duration: 1:07
server response unexpected: 400 Bad Request (400)
github.com/restic/restic/internal/backend/rest.(*restBackend).Save
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/backend/rest/rest.go:146
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/backend/backend_retry.go:71
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/backend/backend_retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/backend/backend_retry.go:65
github.com/restic/restic/internal/cache.(*Backend).Save
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/repository/repository.go:257
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/repository/repository.go:611
github.com/restic/restic/internal/archiver.(*Reader).Archive
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/archiver/archive_reader.go:58
main.readBackupFromStdin
        src/github.com/restic/restic/cmd/restic/cmd_backup.go:275
main.glob..func2
        src/github.com/restic/restic/cmd/restic/cmd_backup.go:46
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
```

Those cron jobs did not leave snapshots. 

While investigating, I removed the local .cache/restic directory. This did not change restic's behaviour.

On the 18th, I started to investigate and let the command run interactively. This produced the same output as above, until I aborted restic wihle it's still been searching for missing indexes.

I retried with restic_v0.8.3-269-gecfe5923_linux_amd64 to verify if this fixed my problem. output as follows shows, no:

```
# cat /dev/vg/vm-win10 | ~youam/Downloads/restic_v0.8.3-269-gecfe5923_linux_amd64 -r $( cat /etc/restic/vm-repository ) --password-file /etc/restic/vm-pass backup --hostname vm-win10 --stdin --stdin-filename vm-win10.img
repository e7b6b597 opened successfully, password is correct
Load(<index/470784b67e>, 0, 0) returned error, retrying after 279.263866ms: <index/470784b67e> does not exist
Load(<index/9e4924547e>, 0, 0) returned error, retrying after 728.361691ms: <index/9e4924547e> does not exist
Load(<index/d43877fe7d>, 0, 0) returned error, retrying after 264.996131ms: <index/d43877fe7d> does not exist
Load(<index/470784b67e>, 0, 0) returned error, retrying after 424.689391ms: <index/470784b67e> does not exist
Load(<index/d43877fe7d>, 0, 0) returned error, retrying after 974.80569ms: <index/d43877fe7d> does not exist
[... about 50 more of those ...]

oad(<index/d43877fe7d>, 0, 0) returned error, retrying after 25.362168384s: <index/d43877fe7d> does not exist
Load(<index/9e4924547e>, 0, 0) returned error, retrying after 10.401240685s: <index/9e4924547e> does not exist
Load(<index/470784b67e>, 0, 0) returned error, retrying after 13.371355549s: <index/470784b67e> does not exist
<index/9e4924547e> does not exist, ignoring
<index/470784b67e> does not exist, ignoring
<index/d43877fe7d> does not exist, ignoring
error: invalid combination of flags 0x20800

Files:           0 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      13 B 

processed 0 files, 0 B in 2:07
snapshot 5a8fca41 saved
root@aurnia:~# echo $?
0
```

Note:
  - restic DID report an error, but did exit with status 0
  - restic reports having processed 0 files, 0 bytes. investigating the saved snapshot returns an empty tree:
```
$ sudo ~/restic -r /srv/backup/restic/vmimages -p /tmp/ofo cat snapshot 5a8fca41
password is correct
{
  "time": "2018-05-18T11:43:00.206449393+02:00",
  "parent": "4f2af5f64be2cee3d3c59c7421e36c103b90967359ec582db167db288d92e9ab",
  "tree": "ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8",
  "paths": [
    "/root/vm-win10.img"
  ],
  "hostname": "vm-win10",
  "username": "root"
}
$ sudo ~/restic -r /srv/backup/restic/vmimages -p /tmp/resticpass cat blob ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8
password is correct
{"nodes":[]}
```

After that, I retried with the 0.8.3 image:

```
# cat /dev/vg/vm-win10 | restic -r $( cat /etc/restic/vm-repository ) --password-file /etc/restic/vm-pass backup --hostname vm-win10 --stdin --stdin-filename vm-win10.img
password is correct
Load(<index/d43877fe7d>, 0, 0) returned error, retrying after 416.795775ms: <index/d43877fe7d> does not exist
Load(<index/470784b67e>, 0, 0) returned error, retrying after 715.515413ms: <index/470784b67e> does not exist
Load(<index/9e4924547e>, 0, 0) returned error, retrying after 590.559892ms: <index/9e4924547e> does not exist
Load(<index/d43877fe7d>, 0, 0) returned error, retrying after 464.815433ms: <index/d43877fe7d> does not exist
Load(<index/9e4924547e>, 0, 0) returned error, retrying after 589.075976ms: <index/9e4924547e> does not exist
[...]
Load(<index/470784b67e>, 0, 0) returned error, retrying after 23.622823524s: <index/470784b67e> does not exist
Load(<index/d43877fe7d>, 0, 0) returned error, retrying after 15.43000104s: <index/d43877fe7d> does not exist
Load(<index/9e4924547e>, 0, 0) returned error, retrying after 23.460792898s: <index/9e4924547e> does not exist
<index/d43877fe7d> does not exist, ignoring
<index/470784b67e> does not exist, ignoring
<index/9e4924547e> does not exist, ignoring
[6:13:36] 64.000 GiB  2.924 MiB/s
duration: 6:13:36
archived as 43d54103
```

(runtime and amount of data are consistent with what I expect them to be). 

This backup command actually produced a snapshot instead of the stack trace. All following commands also seem to do. The message about missing indexes still occurs.

## Steps to reproduce the behavior

No clue.

## Do you have any idea what may have caused this?

I suspect the aborted prune command, but the repository check (without further arguments) states the repository to be clean.

## Do you have an idea how to solve the issue?

No, but as the warnings still occur, I'm open to try suggestions...

## Did restic help you or made you happy in any way?

Yes. :-)

**Comment by fd0** [comment] 2018-05-19 19:40
Thanks for the report, this is a bug (or even two). I'll try to reproduce it...

**Comment by fd0** [comment] 2018-05-19 19:44
Can you please list the `index` subdir contains? `ls -l index/` should be sufficient...

**Comment by fd0** [comment] 2018-05-19 20:03
I can't reproduce it. Hm.  Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by youam** [comment] 2018-05-20 08:39
Argh. I found the reason, the index subdir listing got the clue. I'm running the rest-server process as user `restic`, but when I ran the `restic prune`, I did so as root. So all data rewritten by the prune belonged to the `root` user (and were chmod 0600), so weren't readable by the rest-server process. The `restic check` I did also was run locally as root on the backend server, and so was abled to read everything.

After running

```
find \! -user restic | xargs chown restic:restic
```

restic no longer complains about nonexisting indices.

So I think there are two bugs in play here:

- rest-server returns unreadable index files (and probably all other files) as non-existing. The rest-server process is running in a shell, neither on stdout/stderr nor in any logfiles are warnings about wrong permissions / unreadable files
- the latest restic version from beta.restic.net failed to create a snapshot, but did state so only in stderr, not on the exit code and actually produced a NULL tree as a snapshot

**Comment by youam** [comment] 2018-05-20 10:42
To be abled to track this correctly, I suppose this bug report focusses on eventually getting better diagnostics / error messages for the first case with the incorrect permissions. For the other case, I've created #1790 just now.

**Comment by dantefff** [comment] 2020-01-14 08:53
Thanks to this bug report. It saved me a lot of research time!

**Comment by MichaelEischer** [comment] 2020-10-06 09:17
See #1871 for further discussions on the required REST server fixes.

**Comment by aventrax** [comment] 2021-07-01 16:02
Just to note that even with the repository run out of space, rest-server returns a 400 Bad Request. Not the best explanation to find the problem....

Anyway, thanks for this software!

**Comment by MichaelEischer** [comment] 2022-08-20 16:53
Closing as duplicate of #1871.

**Closed by MichaelEischer** 2022-08-20 16:53 UTC
Labels: type: bug, backend: rest, category: resilience
