### ISSUE TITLE
lock bug

### ISSUE THREAD

**Issue by corkerss** [restic/restic#1627] opened 2018-02-18 20:18 UTC
## Output of `restic version`
```
user@ubuntu:$ restic version
restic 0.8.2
compiled with go1.10 on linux/amd64'
```

## How did you run restic exactly?

Restic run using script

```
#!/usr/bin/bash

#set backblaze b2 account credentials
export B2_ACCOUNT_ID="XXXXXXXXXXX"
export B2_ACCOUNT_KEY="XXXXXXXXXXXXXXXXXXXXXX"
export RESTIC_PASSWORD="XXXXXXXXXXXX"

#set restic bucket repo
export RESTIC_REPOSITORY="b2:XXXXXXXXXX"

#backup Home directory excluding any unwanted directories
#script will not backup Downloads
#script backs all home directory
restic backup  /home    \
/etc                 \
'/var/lib/plexmediaserver/Library/Application Support/Plex Media Server' \ 

#check data is correctly in repo
restic check >> restic.snapshots.txt
restic snapshots >> restic.snapshots.txt

#Remove old repos based on backup strategy
restic forget           \
--keep-hourly 4         \
--keep-daily 7          \
--keep-weekly 4         \
--keep-monthly 6        \
>> ~/restic.snapshots.txt 

#Delete removed snapshots
restic prune >> ~/restic.snapshots.txt

#Route the normal process logging to journalctl
2>&1

# If there is an error backing up, reset b2 credentials
export B2_ACCOUNT_ID=""
export B2_ACCOUNT_KEY=""
export RESTIC_PASSWORD=""

exit 0
```

Output
```
martin@ubuntu:/scripts$ sudo sh restic.sh 
/home/martin/scripts/  does not exist, skipping
password is correct
using parent snapshot 540e9f5d
scan [/home/martin /etc /var/lib/plexmediaserver/Library/Application Support/Plex Media Server]
scanned 125697 directories, 246971 files in 8:40
[3:35] 100.00%  41.743 GiB / 41.742 GiB  372668 / 372668 items  0 errors  ETA 0:00 
duration: 3:35
snapshot 3efce4b3 saved
^Z
[4]+  Stopped                 sudo sh restic.sh
martin@ubuntu:~/scripts$ sudo sh restic.sh 
[sudo] password for martin: 
/home/martin/scripts/  does not exist, skipping
password is correct
List(lock) returned error, retrying after 364.145008ms: repository is already locked by PID 7770 on ubuntu by root (UID 0, GID 0)
lock was created at 2018-02-18 19:29:09 (17m25.94100157s ago)
storage ID fa5e3b28
List(lock) returned error, retrying after 727.903271ms: repository is already locked by PID 7770 on ubuntu by root (UID 0, GID 0)
lock was created at 2018-02-18 19:29:09 (17m29.361673954s ago)
storage ID fa5e3b28
using parent snapshot 3efce4b3
scan [/home/martin /etc /var/lib/plexmediaserver/Library/Application Support/Plex Media Server]
scanned 125697 directories, 246971 files in 7:53
[1:59] 100.00%  41.744 GiB / 41.743 GiB  372668 / 372668 items  0 errors  ETA 0:00 
duration: 1:59
snapshot 2bc148d9 saved
List(lock) returned error, retrying after 646.588351ms: repository is already locked by PID 7770 on ubuntu by root (UID 0, GID 0)
lock was created at 2018-02-18 19:29:09 (27m35.726502512s ago)
storage ID fa5e3b28
List(lock) returned error, retrying after 557.193005ms: repository is already locked by PID 7770 on ubuntu by root (UID 0, GID 0)
lock was created at 2018-02-18 19:29:09 (27m38.777363008s ago)
storage ID fa5e3b28
^Z
[5]+  Stopped                 sudo sh restic.sh
```

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior

Clean exit, not locking errors

## Actual behavior
Run script
Creates snapshot. Error message on creating locks
use restic unlock to break lock
Successful unlock message
Re run script.
Snapshot saves
Terminal hangs until cancelled by user

Creates snapshot. Error message on creating locks
use restic unlock to break lock
Successful unlock message
Re run script.
Snapshot saves
Terminal hangs until cancelled by user

Script to unlock 

```
#!/usr/bin/env bash

#set backblaze b2 account credentials
export B2_ACCOUNT_ID="xxxxxxxxxx"
export B2_ACCOUNT_KEY="xxxxxxxxxxxxxxxxxxxxxxxxx"
export RESTIC_PASSWORD="xxxxx"

#set restic bucket repo
export RESTIC_REPOSITORY="b2:xxxxxx"

#unlock restic lock
restic unlock


#Route the normal process logging to journalctl
2>&1

#Reset b2 credentials
        export B2_ACCOUNT_ID=""
        export B2_ACCOUNT_KEY=""
        export RESTIC_PASSWORD=""

exit 0
```

## Do you have any idea what may have caused this?
Broken upload to b2?

## Do you have an idea how to solve the issue?
Absolutely not

## Did restic help you or made you happy in any way?

Yes, great little program that backs up into very affordable backend
<img width="994" alt="screen shot 2018-02-18 at 19 45 57" src="https://user-images.githubusercontent.com/36156736/36356356-cebbedaa-14e8-11e8-99a6-ef5159fb323c.png">
<img width="995" alt="screen shot 2018-02-18 at 20 00 50" src="https://user-images.githubusercontent.com/36156736/36356357-cee08b06-14e8-11e8-9efc-e96416a14781.png">

**Comment by fd0** [comment] 2018-02-18 20:40
Hey, thanks for the report and for taking the time to fill out the issue template. I'm pretty sure it's not a bug in restic, but in your script.

What makes me think this is this line, after running the script the first time:
```
^Z
[4]+  Stopped                 sudo sh restic.sh
```

Did you manually stop the script? It looks like you've pressed CTRL+Z, which stops the process (the shell script and restic) temporarily. This probably happens while the script runs `restic prune`, which requires an exclusive lock. This is still present in the repo, that's what the second run of the script complains about. restic refuses to make a new backup when the repo is locked.

**Comment by corkerss** [comment] 2018-02-18 20:45
Yeah, it hangs forever so wasnt sure it was doing, I read the prune can take sometime so I didnt think to remember this

Ill leave it to see if it finishes and report back. Thanks very much for your help

**Comment by fd0** [comment] 2018-02-18 20:52
I'm closing this issue for now, please report back if you find anything else.

I'd recommend not redirecting the output of restic prune to a file, otherwise you won't see any progress...

**Closed by fd0** 2018-02-18 20:52 UTC
Labels: feedback needed

**Comment by corkerss** [comment] 2018-02-18 21:16
hello, removing the comments i get alot of 
pack 0f1cd652616d42c475516c04e2fd3698abe8f131af7843645e1e79763fecb85c: not referenced in any index, is this normal behaviour?

**Comment by rawtaz** [comment] 2018-02-18 21:18
@corkerss Yes, see [this FAQ entry](https://restic.readthedocs.io/en/latest/faq.html#restic-check-reports-packs-that-aren-t-referenced-in-any-index-is-my-repository-broken).

**Comment by fd0** [comment] 2018-02-19 07:35
By the way, @corkerss, running `restic prune` every time in the script will mean the `prune` operation is run every single time. Better remove the explicit call to `restic prune`, and call `forget` with the `--prune` option. This instructs restic to run `prune` after `forget`, but only if snapshots have been removed.

**Comment by corkerss** [comment] 2018-02-19 09:51
Hey,

I left it to do its thing and it finished up error free. thanks for all the help. I will alter the scripts and carry on using this wonderful program

cheers

**Comment by fd0** [comment] 2018-02-19 18:47
Nice, thanks for the feedback!
