### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs

### ISSUE THREAD

**Issue by danielb2** [restic/restic#2663] opened 2020-03-24 15:37 UTC
Also having a lot of errors when doing a `restic check`

Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.7 on freebsd/amd64

How did you run restic exactly?
-------------------------------
restic prune

variables:
```
set -gx AWS_ACCESS_KEY_ID secret
set -gx AWS_SECRET_ACCESS_KEY secret
set -gx RESTIC_HOME $HOME/.config/restic
set -gx RESTIC_PASSWORD_FILE $RESTIC_HOME/etc/pass
set -gx RESTIC_INCLUDE $RESTIC_HOME/include
set -gx RESTIC_REPOSITORY s3:https://secret/bkup
```
I don't remember which variables are used for restic but here are the ones I've set for myself.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS

Expected behavior
-----------------

I expected prune to prune the data

Actual behavior
---------------

```
[~]$ restic prune
repository 3a6e47e7 opened successfully, password is correct
counting files in repo
building new index for repo
[17:12] 100.00%  150137 / 150137 packs
repository contains 150137 packs (676019 blobs) with 718.767 GiB
processed 676019 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 23 snapshots
[0:32] 100.00%  23 / 23 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

I was prompted to file this ticket

Steps to reproduce the behavior
-------------------------------

restic prune

Do you have any idea what may have caused this?
-----------------------------------------------

no idea. the tool told me to file the issue

Do you have an idea how to solve the issue?
-------------------------------------------

none

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

it makes me happy almost every day

**Comment by dimejo** [comment] 2020-03-24 16:11
Quote from the issue template:
> Fill out the issue template below - not doing so needs a good reason.

It probalbly doesn't make a difference in this case (as there are plenty of bug reports) but I'm still wondering why you didn't fill out the issue template. How do you expect developers to help when you don't provide any information besides the error messages?

Related issues:
#2642 
#2400 
#2385
#2334 
#2273
#2045
#2024

**Comment by danielb2** [comment] 2020-03-24 16:19
It wasn't  intentional. I didn't get prompted.

**Comment by jkirk** [comment] 2020-03-25 23:17
JFTR (@dimejo): `restic prune` states:

```
[~]$ restic prune
[...]
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

Following the given [link](https://github.com/restic/restic/issues/new) opens a new issue without a template. `restic` should instead show [this](https://github.com/restic/restic/issues/new/choose) or [Bug report](https://github.com/restic/restic/issues/new?template=Bug.md)?

**Comment by jkirk** [comment] 2020-03-26 00:18
Anyway, I also stumbled over this error.

Thank you @dimejo for the [list of issues](https://github.com/restic/restic/issues/2663#issuecomment-603341808). I went through all of them and tried to sort them out a bit (in case someone else stumbles over your list).

These are quite good issues, with an ongoing discussion: 
#2642
#2045

This issue is currently without comments, but a bit concerning as a data loss followed by `restic rebuild-index` seems to break the repo:
#2334 

These issues are just plain reports without useful information. (Maybe they should be closed and marked as duplicates?):
#2400
#2385 

This issue seems to have a different cause (problem with NetApp S3 Object Storage where local storage works):
#2273 

I am unsure about the following issue. It was created by @fd0 and leads to an another interesting issue (#2547) which is way out of my comprehension scope:
#2024 

My issue is:

My backend is a plain NTFS USB3 hard disk drive. `restic backup` is run once an hour and there are 292 snapshots. As this is a simple desktop setup I have no idea or even control if the disk was always attached and every backup run was successfully. `restic check` reports a large list of errors like:
```
error for tree c333c61c:
  tree c333c61c: file ".ICEauthority" blob 0 size could not be found
  tree c333c61c: file ".Xauthority" blob 0 size could not be found
  tree c333c61c, blob 1cbc6e23: not found in index
  tree c333c61c, blob f6271f6c: not found in index
[...]
error for tree 5bf92b7d:
  tree 5bf92b7d: file "SAL 0118.pdf" blob 0 size could not be found
  tree 5bf92b7d, blob c64d7eae: not found in index
[...]
Fatal: repository contains errors
```

My current only concern is: Can I still trust the backup or is it broken? Will `restic rebuild-index` break everything? What shall I do?

**Comment by danielb2** [comment] 2020-03-26 00:22
I ran `restic rebuild-index` and it didn't improve or make things worse . I think it's safe to try it

**Comment by jkirk** [comment] 2020-03-26 00:33
@danielb2 Did you run `backup -f <path...> `as stated by @MichaelEischer in his [comment](https://github.com/restic/restic/issues/2642#issuecomment-602246129)?
> * Run `backup -f <path...>` to have restic fully rescan all files and upload any missing chunks. The important part here is the `-f (=--force)` flag.

**Comment by dimejo** [comment] 2020-03-26 08:21
> Following the given link opens a new issue without a template. restic should instead show this or Bug report?

Thanks for the information, I wasn't aware of that. But I had assumed people would skim through old issues before opening a new one.

> My current only concern is: Can I still trust the backup or is it broken? Will restic rebuild-index break everything? What shall I do?

Running `restic rebuild-index` and `restic prune` makes sure that restic cleans any incomplete parts which couldn't be restored anyways.

> @danielb2 Did you run backup -f <path...> as stated by @MichaelEischer in his comment?

FYI, it looks like the discussion continued in [this thread in the forum](https://forum.restic.net/t/fail-restic-stats-mode-raw-data/2601).

**Comment by MichaelEischer** [comment] 2020-03-26 22:21
> This issue is currently without comments, but a bit concerning as a data loss followed by `restic rebuild-index` seems to break the repo:

That's actually an instance of "blame the messenger". The repository was already broken after the pack file was deleted. Running restore would have lead to the same results as it did after running `rebuild-index`. The purpose of `rebuild-index` is to rebuild the index (I know that's totally surprising) to make sure that it accurately reflects the state of the repository. Most importantly the index must not contain blobs/packs that are actually missing. In that case restic has no chance to detect the problem unless you try to restore data, and then it's too late, or run `check --read-data`. `rebuild-index` only makes changes to the index but never to the actual backup data, such that it's a rather safe operation (except for some very special cases of damaged files).

The general rule of thumb is to run `rebuild-index` early on together with `backup --force ...` (for every backup set!) when a repository was damaged to prevent the damage from affecting future snapshots. Of course, it advisable to `check` the repository afterwards to detect further problems. In case it's possible to freeze a backup repository for a few days, it would be rather helpful to be able to try to investigate the problem.

@jkrik Your repository is missing some data. So you won't be able to restore everything in that repository. I'm a bit surprise to see a NTFS formatted drive, but filename that point at a Unixoid system. Could you create a forum post to use for further investigations, in order to not hijack this issue?

**Comment by olarriga** [comment] 2020-04-11 16:11
Hello,

I have the same issue:

Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64


How did you run restic exactly?
-------------------------------
export OS_AUTH_URL=https://auth.cloud.ovh.net/v3/
export OS_IDENTITY_API_VERSION=3
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_TENANT_ID=**************
export OS_TENANT_NAME="************"
export OS_USERNAME="**********"
export OS_PASSWORD="************"
export OS_REGION_NAME="GRA"
export RESTIC_PASSWORD="*****************"
restic_0.9.6_linux_amd64 -r swift:myobject:/ --cache-dir /tmp/restic/cache prune


What backend/server/service did you use to store the repository?
----------------------------------------------------------------
OVH Object Storage


Expected behavior
-----------------
I expected that prune remove the unused files


Actual behavior
---------------
The error message : 
Fatal: number of used blobs is larger than number of available blobs! Please report this error (along with the output of the 'prune' run) at https://github.com/restic/restic/issues/new


Steps to reproduce the behavior
-------------------------------
Just run restic prune


Do you have any idea what may have caused this?
-----------------------------------------------
No :(


Do you have an idea how to solve the issue?
-------------------------------------------
No :(


Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, until now it was great.

**Comment by olarriga** [comment] 2020-04-12 14:55
I managed to repair the repository. I followed the instructions found on the forum.
1/ find the id of the tree with errors with the commande "restic check"
2/ find the id of the snapshot containing this tree with "restic find --tree <id of the tree with errors>"
3/ Delete the snapshots with "restic forget"
4/ Prune the repository with "restic prune"
I do not have the error anymore.

PS : Maybe this can be automated with a sort of "repair" commande ?

**Comment by danielb2** [comment] 2020-04-12 17:52
I ended up doing something similar to olarriga but since I didn't know about restic find --tree, I just deleted snapshots until I didn't get the error anymore

**Comment by k3a** [comment] 2020-08-02 13:18
If that helps somehow, it happened to me shortly after upgrading from `restic-v0.9.4-0-gcd9b2295` to `restic-v0.9.6-0-gb723ca3d` while keeping the previously backed-up data.

**Comment by Alwaysin** [comment] 2020-09-07 13:12
These errors also started to appear on my side after upgrading to restic_0.9.6-348-g0fed6a8d (I needed the return codes feature).

**Comment by MichaelEischer** [comment] 2020-09-09 19:48
@Alwaysin Which error do you get exactly? Could you try the last master branch, which will provide a bit more information when prune encounters a damaged repository? Which backend are you using? Which errors does the `check` command return?

**Comment by Alwaysin** [comment] 2020-09-09 20:49
@MichaelEischer the same error that is described in the first post. I had upgraded to v0.9.6-377-gc34c7316 and it looks there is no errors anymore ? At least I can't reproduce. If I recall correctly, a prune and rebuild-index and another prune has been done with latest version, maybe it resolved the problem. For the record, I'm using rest-server on latest version, that is 0.9.7.

**Comment by MichaelEischer** [comment] 2020-09-10 19:53
@Alwaysin There are no changes between v0.9.6-377-gc34c7316 and v0.9.6-348-g0fed6a8d which should cause prune to stop complaining, if anything it should complain more often as I've tightened the sanity checks run at the start of the prune command in #2674 . 

For `prune`, `rebuild-index` and `prune`, I would expect that the first prune run did fail, rebuild-index could then add missing blobs to the index such that the second prune run works? If the first prune run worked, then it should also have worked with the old restic version.

**Comment by MichaelEischer** [comment] 2021-01-11 22:26
Closing this issue as there seems nothing left to be done here. If one of the reported repository issues still exists please open a new issue and use a recent restic version (at least >= 0.10.0). Please do **not** run `rebuild-index` before we had the chance for an initial assessment of the repository damage. Or at least create a backup of the `index/` folder if you can't wait.

**Closed by MichaelEischer** 2021-01-11 22:26 UTC
