### ISSUE TITLE
Feature: control "--dry-run" via environment variable "RESTIC_DRY_RUN"

### ISSUE THREAD

**Issue by mgumz** [restic/restic#4073] opened 2022-12-04 13:43 UTC
Output of `restic version`
--------------------------

restic 0.14.0 compiled with go1.19.2 on darwin/arm64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Various commands support the --dry-run flag. When restic is used as part
of a scripted chain, adding/removing "--dry-run" to check the chain is
tedious.

Setting RESTIC_DRY_RUN=1 allows to check the pipeline without changing any part of it.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

    $> export RESTIC_DRY_RUN=1 
    $> /path/to/my/backup.sh
    <run restic in dry-mode>

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes. Yes.

**Comment by MichaelEischer** [comment] 2022-12-07 20:57
Duplicate of #3703

**Closed by MichaelEischer** 2022-12-07 20:57 UTC
