### ISSUE TITLE
Ability to explicitely lock the repo

### ISSUE THREAD

**Issue by brunoleon** [restic/restic#3233] opened 2021-01-20 09:12 UTC
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be nice to be able to explicit require an exclusive lock of the repository.
The lock code being already there, this just need a new command line option to call it.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I need to sync my local repo (restic-rest) to an external source.
This will be done via rclone to an S3 Glacier (but that could be anything rclone supports), and I need to ensure the repo is not being written into while doing the sync to avoid weird behavior (like inconsistent pack, index, snapshots... see https://forum.restic.net/t/directly-copying-restic-data-between-repositories/2876/6) 

As for a BDD backup, my plan is:
Lock repo => LVM snapshot => release lock => rclone sync the snapshot

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is really great for day to day use, but restore speed is pretty slow.
Big repo with lots of files seems difficult to handle too (mail servers) but still works.

**Comment by MichaelEischer** [comment] 2021-01-21 22:03
Closing this as a duplicate of #2166.

> Restic is really great for day to day use, but restore speed is pretty slow.

To which restic version does that apply and what do you mean by "slow"? Since restic 0.10.0 the restore speed should be reasonable. Last time I've restored a server  with lots of small files from a local SFTP server, restic was restoring at around 100MB/s (at which point the SFTP connection was the bottleneck).

**Closed by MichaelEischer** 2021-01-21 22:03 UTC
