### ISSUE TITLE
[S3] [EMC-ECS] client.BucketExists: Invalid Argument

### ISSUE THREAD

**Issue by karlesnine** [restic/restic#765] opened 2017-01-31 16:26 UTC
## Output of `restic version`
```
debug log file /Users/k/HDVM/go/restic/debug.log
debug enabled
restic 0.3.3 (v0.3.3-88-gc7d6027)
compiled with go1.7.5 on darwin/amd64
```

## Expected behavior

Initialize a repository on a [EMC ECS](https://en.wikipedia.org/wiki/EMC_Elastic_Cloud_Storage) appliance S3 compliante

```
./restic --repo s3:http://emc-ecs-hostname.tld:9020/test init
```
- AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY correctly exported and validate
- Bucket create by the way of EMC ECS management interface
- Bucket Access / write / delete tested with [Cyberduck](https://cyberduck.io/) and a [dedicated profile](https://community.emc.com/docs/DOC-27683) for AWS4 auth

## Actual behavior

Command fail with this message

```
./restic --repo s3:http://emc-ecs-hostname.tld:9020/test init
debug log file /Users/k/HDVM/go/restic/debug.log
debug enabled
create backend at s3:http://emc-ecs-hostname.tld:9020/test failed: client.BucketExists: Invalid Argument
```

The debug log contains

```
2017/01/31 17:13:37 restic/main.go:48	main.main	1	main []string{"./restic", "--repo", "s3:http://emc-ecs-hostname.tld:9020/test", "init"}
2017/01/31 17:13:37 restic/global.go:338	main.create	1	parsing location s3:http://emc-ecs-hostname.tld:9020/test
2017/01/31 17:13:37 restic/global.go:361	main.create	1	create s3 repository at s3.Config{Endpoint:"emc-ecs-hostname.tld:9020", UseHTTP:true, KeyID:"", Secret:"", Bucket:"test", Prefix:"restic"}
2017/01/31 17:13:37 s3/s3.go:31	s3.Open	1	open, config s3.Config{Endpoint:"emc-ecs-hostname.tld:9020", UseHTTP:true, KeyID:"test", Secret:"WXqJIOSTjD8pPsHq7lC3fcUrBU+sb5aLxx1RodPc", Bucket:"test", Prefix:"restic"}
2017/01/31 17:13:37 s3/s3.go:43	s3.Open	1	BucketExists(test) returned err Invalid Argument
2017/01/31 17:13:37 restic/lock.go:112	main.unlockAll	1	unlocking 0 locks
```

## Tcpdump extract

```
..>..a1.GET /test/?location= HTTP/1.1
Host:emc-ecs-hostname.tld:9020
User-Agent: Minio (darwin; amd64) minio-go/2.0.1
Authorization: AWS4-HMAC-SHA256 Credential=test/20170131/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=dbc6f21f31c743a24f65592662ffb11dbe99e4ee8c4ebfedfa55ca4d82a12cf0
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170131T161337Z
Accept-Encoding: gzip

[...]

.a1...>.HTTP/1.1 400 Bad Request
Date: Tue, 31 Jan 2017 16:13:37 GMT
x-amz-id-2:
Server: ViPR/1.0
x-amz-request-id: 0a14b00a:15608de177b:edee5:ba
Content-Type: application/xml
Content-Length: 130

<Error><Code>InvalidArgument</Code><Message>Invalid Argument</Message><RequestId>0a14b00a:15608de177b:edee5:ba</RequestId></Error>
17:13:37.709720 IP (tos 0x0, ttl 64, id 40760, offset 0, flags [DF], proto TCP (6), length 52)
    10.44.0.11.63794 > emc-ecs-hostname.tld.tambora: Flags [.], cksum 0xba57 (correct), seq 475, ack 329, win 4099, options [nop,nop,TS val 377962188 ecr 4234228181], length 0
...!E..4.8@.@..6
```

## Suspect

According to the S3 Api documentation of EMC ECS the [GET Bucket location](https://www.emc.com/techpubs/ecs/ecs_s3_supported_features-1.htm#GUID-0FD70C3E-E13C-45E7-AEB5-C8541FA18615) is not supported because ECS is only aware of a single virtual data center.

## Asked / Expected

Is it possible to disable what is related to the location ? Or  to provide a deactivation switch in this case.

**Comment by fd0** [comment] 2017-02-01 10:13
Thanks for reporting this. We're using the [minio-go](https://github.com/minio/minio-go) library to access s3, and the call to `GET` Bucket Location is contained in the library. I don't see how we can disable that for restic.

You could maybe test if the rest of the backend implementation works, try commenting out the highlighted lines, recompile restic and try again: https://github.com/restic/restic/blob/master/src/restic/backend/s3/s3.go#L41-L53

**Comment by fd0** [comment] 2017-05-14 20:20
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-05-14 20:20 UTC
Labels: backend:s3, bug, feedback needed
