### ISSUE TITLE
locks: invalid argument (docker)

### ISSUE THREAD

**Issue by bbigras** [restic/restic#3751] opened 2022-05-11 16:45 UTC
Output of `restic version`
--------------------------

`restic 0.13.1 compiled with go1.16.15 on linux/amd64`

How did you run restic exactly?
-------------------------------

```sh
docker run --rm \
    --read-only \
    --tmpfs /tmp \
    --name restic-backup \
    -v /net/nouvbackup/ubuntu:/backup \
    -v /srv_no_backup/restic/cache:/restic-cache \
    -v /srv_no_backup/restic/password-file:/password-file:ro \
    -v /srv_no_backup/restic/excludes:/excludes:ro \
    -v /srv:/data/srv:ro \
    -v /etc:/data/etc:ro \
    -v /home:/data/home:ro \
    restic/restic:0.13.1 \
    -r /backup/restic \
    --cache-dir /restic-cache \
    -p /password-file \
    --exclude-file /excludes \
    backup \
    /data/srv \
    /data/etc \
    /data/home
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

`/net/nouvbackup/ubuntu` is a windows share

Expected behavior
-----------------

With [0.12.1](https://hub.docker.com/layers/restic/restic/restic/0.12.1/images/sha256-3d8655b111a584fb649eabe4c69c61abbef93505348acdcd557d974c54a07249?context=explore) it's fine.

Actual behavior
---------------

```
Status: Downloaded newer image for restic/restic:0.13.1
Save(<lock/bf789d7343>) returned error, retrying after 552.330144ms: sync /backup/restic/locks: invalid argument
Save(<lock/bf789d7343>) returned error, retrying after 1.080381816s: sync /backup/restic/locks: invalid argument
Save(<lock/bf789d7343>) returned error, retrying after 1.31013006s: sync /backup/restic/locks: invalid argument
```

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment] 2022-05-11 18:23
This is a duplicate of #3720. Is the repository location a CIFS mount? Or a different filesystem?

**Comment by bbigras** [comment] 2022-05-11 18:39
Oh, sorry.

Yes, a CIFS mount.

**Comment by MichaelEischer** [comment] 2022-05-11 18:41
Could you test whether #3752 fixes the problem for you?

**Closed** 2022-05-29 10:54 UTC
