### ISSUE TITLE
[Windows] Backup a network share fails

### ISSUE THREAD

**Issue by underdpt** [restic/restic#3630] opened 2022-01-12 15:49 UTC
Output of `restic version`
--------------------------
`restic 0.12.1 compiled with go1.16.6 on windows/amd64`

How did you run restic exactly?
-------------------------------
Environment:

```
RESTIC_REPOSITORY='d:/testrepo'
RESTIC_PASSWORD='00000000000000000000000000' // For testing pursposes
```

Command to create the repo:

```
❯ D:/desarrollos/mainsip/easy-restic/restic.exe init

created restic repository 9f589b8b55 at d:/testrepo

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```` 

Command to perform the backup of a network share:

```
❯ D:/desarrollos/mainsip/easy-restic/restic.exe backup //pc-hogar/downloads --json

<-- files being copied -->

Fatal: unable to save snapshot: Lstat: CreateFile \\?\D:\desarrollos\mainsip\easy-restic\pc-hogar: The system cannot find the file specified.
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local backend for testing purposes. I found the bug first doing backups to a Wasabi bucket (S3 compatible) so I think the backend is not relevant to this bug.

Expected behavior
-----------------

The snapshot should be saved correctly, without an error being arisen.

Actual behavior
---------------

The backup fails with an error:

```
Fatal: unable to save snapshot: Lstat: CreateFile \\?\D:\desarrollos\mainsip\easy-restic\pc-hogar: The system cannot find the file specified.
```

The data is saved on the repository but no snapshot is created, so no way to recover that data.

As you can see, it's trying to create a directory on the current folder (`D:\desarrollos\mainsip\easy-restic\`), with the root file name. If i manually create this file:

```
❯ mkdir pc-hogar
❯ D:/desarrollos/mainsip/easy-restic/restic.exe backup //pc-hogar/downloads --json

<-- files being copied -->
Files:          46 new,     0 changed,     0 unmodified
Dirs:           11 new,     0 changed,     0 unmodified
Added to the repo: 1.779 GiB
processed 46 files, 1.803 GiB in 0:19
snapshot ba0ce885 saved
```

But it's impossible to recover the files:

```
❯ D:/desarrollos/mainsip/easy-restic/restic.exe restore ba0ce88509b425227f889a7258b8a7eec169dea5004686d74a971614e60cb7d4 --include / --target ./restore --json

restoring <Snapshot ba0ce885 of [\\pc-hogar\downloads] at 2022-01-12 16:41:05.4004513 +0100 CET by UNDERDPT-PC02\underdpt@underdpt-pc02> to ./restore
ignoring error for \: invalid child node name \\pc-hogar\downloads
ignoring error for \: invalid child node name \\pc-hogar\downloads
Fatal: There were 2 errors
```

Steps to reproduce the behavior
-------------------------------

The steps are outlined above.

Do you have any idea what may have caused this?
-----------------------------------------------

I think this might be an issue with share naming convention on Windows.

Do you have an idea how to solve the issue?
-------------------------------------------

No. I've a workaround by mapping the share to a drive letter and then backup that drive directly.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yeah. I'm moving all my customer's backups to restic, on a Wasabi backend, and I'm very happy with it. I come from duplicati and the backup and restore times are awesome.

I'm developing a tool to workaround some restic limitations (easy setup, pre-backup scripts, mysql backup, email post-backup reports, etc.) which I'll open source once it's stable enough.

**Comment by MichaelEischer** [comment] 2022-01-12 19:20
This is a duplicate of #3339. Please note that currently #2807 would also prevent restoring the files.

**Closed by MichaelEischer** 2022-01-12 19:20 UTC
