### ISSUE TITLE
Metadat Access Denied when using VSS

### ISSUE THREAD

**Issue by ccmgr** [restic/restic#5106] opened 2024-10-28 19:27 UTC
Output of `restic version`
--------------------------
0.17.2

What backend/service did you use to store the repository?
---------------------------------------------------------
Back Blaze

Problem description / Steps to reproduce
----------------------------------------

Ouput of Restic Backup

open repository
using parent snapshot 3eac77d0
load index files
start scan on [E:\hMailServer\hMailserver]
start backup on [E:\hMailServer\hMailserver]
creating VSS snapshot for [e:\]
successfully created snapshot for [e:\]
error: incomplete metadata for E:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1973\, with: The process cannot access the file because it is being used by another process.]
scan finished in 144.040s: 64785 files, 16.102 GiB

Files:          19 new,     1 changed, 64765 unmodified
Dirs:            0 new,    27 changed,  1563 unmodified
Data Blobs:     31 new
Tree Blobs:     28 new
Added to the repository: 16.425 MiB (14.255 MiB stored)
processed 64785 files, 16.102 GiB in 2:30
snapshot 80756a1c saved
Warning: at least one source file could not be read

Expected behavior
-----------------

Actual behavior
---------------

Do you have any idea what may have caused this?
-----------------------------------------------
Update to 0.17.2. Rolled back to 0.17.1 and backup runs without throwing an error

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment] 2024-10-28 19:36
Duplicate of https://github.com/restic/restic/issues/5107

**Closed by MichaelEischer** 2024-10-28 19:36 UTC
