### ISSUE TITLE
cached file is truncated

### ISSUE THREAD

**Issue by mrzv** [restic/restic#1328] opened 2017-10-05 02:18 UTC
## Output of `restic version`
```
restic 0.7.3 (v0.7.3-87-g3afd974d)
compiled with go1.9 on darwin/amd64
```

## How did you run restic exactly?
`restic -r sftp:... backup ...`

## What backend/server/service did you use?
SFTP

## Actual behavior
```
cached file is truncated, removing
github.com/restic/restic/internal/cache.(*Cache).Load
	src/github.com/restic/restic/internal/cache/file.go:63
github.com/restic/restic/internal/cache.(*Backend).Load
	src/github.com/restic/restic/internal/cache/backend.go:203
github.com/restic/restic/internal/backend.LoadAll
	src/github.com/restic/restic/internal/backend/utils.go:13
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
	src/github.com/restic/restic/internal/repository/repository.go:72
github.com/restic/restic/internal/repository.LoadIndexWithDecoder
	src/github.com/restic/restic/internal/repository/index.go:558
github.com/restic/restic/internal/repository.LoadIndex
	src/github.com/restic/restic/internal/repository/repository.go:459
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func1
	src/github.com/restic/restic/internal/repository/repository.go:379
github.com/restic/restic/internal/repository.ParallelWorkFuncParseID.func1
	src/github.com/restic/restic/internal/repository/parallel.go:74
github.com/restic/restic/internal/repository.FilesInParallel.func1
	src/github.com/restic/restic/internal/repository/parallel.go:39
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337
```

## Steps to reproduce the behavior
I don't entirely believe it, when it says it's removing the file because I get the same error over and over when I rerun the command. At the very least, it would be helpful if the error message reported which cache file it thinks is truncated.

## Do you have any idea what may have caused this?
I'm guessing an interrupted backup, but I'm not quite sure.

**Comment by mrzv** [comment] 2017-10-05 03:33
A related follow-up. I have two repositories. Is it possible to tell which cache directory corresponds to which repository? (So I can wipe out just the one that has the truncated file.)

**Comment by fd0** [comment] 2017-10-05 17:08
Hm, interesting. There's code to remove the file after that error is printed:
https://github.com/restic/restic/blob/1dcfd640281acf324991a80c9df6f7bba2d92f01/internal/cache/file.go#L60-L64

Currently, the repo ID is only printed right after `init`, but you're right and we should print it somewhere.

**Comment by mrzv** [comment] 2017-10-05 17:10
Meaning there are multiple truncated files, and it's reporting them to me one-by-one, on each subsequent execution?

**Comment by fd0** [comment] 2017-10-05 17:11
No, I suspect there's a bug and the file isn't removed. I'm having a look now.

**Comment by fd0** [comment] 2017-10-05 17:31
I'm unable to reproduce it. I've added the name of the file to the error message in the branch `fix-1328`, can you please try that and write a debug log?

**Comment by mrzv** [comment] 2017-10-05 17:34
"debug log" meaning you want me to build with `-tags debug`?

**Comment by mrzv** [comment] 2017-10-05 17:40
Without `-tags debug`:
```
password is correct
cached file <index/7b203dc438> is truncated, removing
github.com/restic/restic/internal/cache.(*Cache).Load
	src/github.com/restic/restic/internal/cache/file.go:63
github.com/restic/restic/internal/cache.(*Backend).Load
	src/github.com/restic/restic/internal/cache/backend.go:203
github.com/restic/restic/internal/backend.LoadAll
	src/github.com/restic/restic/internal/backend/utils.go:13
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
	src/github.com/restic/restic/internal/repository/repository.go:72
github.com/restic/restic/internal/repository.LoadIndexWithDecoder
	src/github.com/restic/restic/internal/repository/index.go:558
github.com/restic/restic/internal/repository.LoadIndex
	src/github.com/restic/restic/internal/repository/repository.go:459
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func1
	src/github.com/restic/restic/internal/repository/repository.go:379
github.com/restic/restic/internal/repository.ParallelWorkFuncParseID.func1
	src/github.com/restic/restic/internal/repository/parallel.go:74
github.com/restic/restic/internal/repository.FilesInParallel.func1
	src/github.com/restic/restic/internal/repository/parallel.go:39
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337
```

**Comment by mrzv** [comment] 2017-10-05 17:42
Oh, it gives the same thing with `-tags debug` (with the extra line `debug enabled`), so I guess that doesn't matter.

**Comment by fd0** [comment] 2017-10-05 18:28
This error is caused by the index file in the repo being incomplete, the cache error is misleading. The real error (with `--no-cache`) reveals that it's a duplicate of #1229:
```
$ ./restic backup --no-cache .
load <index/40179ac6b9>: invalid data returned
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
        src/github.com/restic/restic/internal/repository/repository.go:79
github.com/restic/restic/internal/repository.LoadIndexWithDecoder
        src/github.com/restic/restic/internal/repository/index.go:558
github.com/restic/restic/internal/repository.LoadIndex
        src/github.com/restic/restic/internal/repository/repository.go:459
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func1
        src/github.com/restic/restic/internal/repository/repository.go:379
github.com/restic/restic/internal/repository.ParallelWorkFuncParseID.func1
        src/github.com/restic/restic/internal/repository/parallel.go:74
github.com/restic/restic/internal/repository.FilesInParallel.func1
        src/github.com/restic/restic/internal/repository/parallel.go:39
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:2337
```

**Comment by mrzv** [comment] 2018-07-09 09:20
I'm not filing this as a separate bug, because I think it's related.
```
$ restic version
restic 0.9.1 compiled with go1.10.3 on darwin/amd64
```

Using SFTP backend:
```
$ restic backup ...
repository 2f0992a2 opened successfully, password is correct
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 493.131141ms: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 470.25637ms: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 623.93107ms: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 1.321777958s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 2.174017432s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 4.55691167s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 8.292878832s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 10.192375844s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 7.549709993s: trying to cache truncated file <snapshot/d7efe02e72>
Load(<snapshot/d7efe02e72>, 0, 0) returned error, retrying after 16.192814128s: trying to cache truncated file <snapshot/d7efe02e72>
Error loading snapshot d7efe02e: load <snapshot/d7efe02e72>: invalid data returned
github.com/restic/restic/internal/restic.FindLatestSnapshot.func1
	src/github.com/restic/restic/internal/restic/snapshot_find.go:39
github.com/restic/restic/internal/repository.(*Repository).List.func1
	src/github.com/restic/restic/internal/repository/repository.go:585
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
	src/github.com/restic/restic/internal/backend/backend_retry.go:133
github.com/restic/restic/internal/backend/sftp.(*SFTP).List
	src/github.com/restic/restic/internal/backend/sftp/sftp.go:462
github.com/restic/restic/internal/limiter.(*rateLimitedBackend).List
	<autogenerated>:1
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
	src/github.com/restic/restic/internal/backend/backend_retry.go:127
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
	src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	src/github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).List
	src/github.com/restic/restic/internal/backend/backend_retry.go:126
github.com/restic/restic/internal/cache.(*Backend).List
	<autogenerated>:1
github.com/restic/restic/internal/repository.(*Repository).List
	src/github.com/restic/restic/internal/repository/repository.go:579
github.com/restic/restic/internal/restic.FindLatestSnapshot
	src/github.com/restic/restic/internal/restic/snapshot_find.go:36
main.findParentSnapshot
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:317
main.runBackup
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:395
main.glob..func2
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:54
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:756
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:846
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:794
main.main
	src/github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
```

```
$ restic backup ... --no-cache
repository 2f0992a2 opened successfully, password is correct
Error loading snapshot d7efe02e: load <snapshot/d7efe02e72>: invalid data returned
github.com/restic/restic/internal/restic.FindLatestSnapshot.func1
	src/github.com/restic/restic/internal/restic/snapshot_find.go:39
github.com/restic/restic/internal/repository.(*Repository).List.func1
	src/github.com/restic/restic/internal/repository/repository.go:585
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
	src/github.com/restic/restic/internal/backend/backend_retry.go:133
github.com/restic/restic/internal/backend/sftp.(*SFTP).List
	src/github.com/restic/restic/internal/backend/sftp/sftp.go:462
github.com/restic/restic/internal/limiter.(*rateLimitedBackend).List
	<autogenerated>:1
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
	src/github.com/restic/restic/internal/backend/backend_retry.go:127
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
	src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	src/github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).List
	src/github.com/restic/restic/internal/backend/backend_retry.go:126
github.com/restic/restic/internal/repository.(*Repository).List
	src/github.com/restic/restic/internal/repository/repository.go:579
github.com/restic/restic/internal/restic.FindLatestSnapshot
	src/github.com/restic/restic/internal/restic/snapshot_find.go:36
main.findParentSnapshot
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:317
main.runBackup
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:395
main.glob..func2
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:54
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:756
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:846
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:794
main.main
	src/github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
```

**Comment by fd0** [comment] 2018-11-25 13:02
Thanks for leaving additional information here. I'm closing this as a duplicate of #1229

**Closed by fd0** 2018-11-25 13:02 UTC
Labels: bug, needs triage
