### ISSUE TITLE
Feature Request: Allow user to identify snapshot with tilde symbol

### ISSUE THREAD

**Issue by yookoala** [restic/restic#2352] opened 2019-07-25 10:13 UTC
Output of `restic version`
--------------------------

`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

`restic` should accept tilde symbol like git to specify previous snapshots of a specific snapshot according to path(s).

For example, if `ab12345` is a snapshot of `/home/user/some_folder1` and `/home/user/some_folder2`, then `ab12345~1` should be 1 snapshot before `ab12345` for the `/home/user/some_folder1` and `/home/user/some_folder2`. But not for snapshot with other path combinations, even if they also include `/home/user/some_folder1` or / and `/home/user/some_folder2`.

Then `ab12345~2` should be the snapshot before `ab12345~1`. So on and so forth.

What are you trying to do?
--------------------------

It is not very convenient for restic to only reference snapshot by the exact ID. In git, you may refer a commit with either the commit hash or the branch, optionally with tilde specifier. For example, if you want to specify snapshot.

Did restic help you or made you happy in any way?
-------------------------------------------------

`restic` is an excellent backup solution, Thanks for all the great work.

**Comment by MichaelEischer** [comment] 2023-01-02 20:55
Duplicate of #4122

**Closed by MichaelEischer** 2023-01-02 20:55 UTC
Labels: category: user interface, type: feature suggestion
