### ISSUE TITLE
dmesg entry "task restic:XXX blocked for more than 120 seconds."

### ISSUE THREAD

**Issue by flo82** [restic/restic#1739] opened 2018-04-30 07:38 UTC
## Output of `restic version`

```
restic 0.8.3
compiled with go1.10 on linux/amd64
```
## How did you run restic exactly?

```
export AZURE_ACCOUNT_NAME=XXX
export AZURE_ACCOUNT_KEY=XXX
export RESTIC_REPOSITORY=azure:resticazure:/

restic -p /opt/scripts/restic.pass backup /backup/archiv >> /var/log/restic.log
restic -p /opt/scripts/restic.pass backup /backup/data>> /var/log/restic.log

``` 

I'm using Ubuntu 18.04. with 4.15.0-20-generic kernel and ZFS 0.7.5

## What backend/server/service did you use to store the repository?

azure account (see above)

## Expected behavior

no errors in dmesg.

## Actual behavior

each restic command produces an entry in dmesg:

```
[Apr30 06:31] INFO: task restic:24399 blocked for more than 120 seconds.
[  +0,000064]       Tainted: P           OE    4.15.0-20-generic #21-Ubuntu
[  +0,000053] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  +0,000062] restic          D    0 24399   7157 0x00000000
[  +0,000004] Call Trace:
[  +0,000009]  __schedule+0x297/0x8b0
[  +0,000004]  schedule+0x2c/0x80
[  +0,000003]  io_schedule+0x16/0x40
[  +0,000010]  cv_wait_common+0xb2/0x140 [spl]
[  +0,000003]  ? wait_woken+0x80/0x80
[  +0,000007]  __cv_wait_io+0x18/0x20 [spl]
[  +0,000057]  zio_wait+0xf8/0x1b0 [zfs]
[  +0,000035]  dmu_buf_hold_array_by_dnode+0x15c/0x450 [zfs]
[  +0,000033]  dmu_read_uio_dnode+0x49/0x100 [zfs]
[  +0,000033]  dmu_read_uio_dbuf+0x49/0x70 [zfs]
[  +0,000048]  zfs_read+0x136/0x3f0 [zfs]
[  +0,000047]  zpl_read_common_iovec+0x80/0xd0 [zfs]
[  +0,000044]  zpl_iter_read+0x9c/0xe0 [zfs]
[  +0,000005]  new_sync_read+0xe4/0x130
[  +0,000004]  __vfs_read+0x29/0x40
[  +0,000003]  vfs_read+0x8e/0x130
[  +0,000004]  SyS_read+0x55/0xc0
[  +0,000004]  do_syscall_64+0x73/0x130
[  +0,000003]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[  +0,000003] RIP: 0033:0x46c800
[  +0,000002] RSP: 002b:000000c44d575f50 EFLAGS: 00000206 ORIG_RAX: 0000000000000000
[  +0,000003] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 000000000046c800
[  +0,000001] RDX: 0000000000080000 RSI: 000000c45f082000 RDI: 000000000000000b
[  +0,000001] RBP: 000000c44d575fa8 R08: 0000000000000000 R09: 0000000000000000
[  +0,000002] R10: 0000000000000000 R11: 0000000000000206 R12: 000000c498d08000

```

## Steps to reproduce the behavior

currently this happens each time I run restic command. Don't know how to reproduce this.

## Do you have any idea what may have caused this?

Updated to Ubuntu 18.04 and ZFS 0.7.5.
In Ubuntu 16.04. and ZFS 0.6.x this error was not present.

## Do you have an idea how to solve the issue?

I'm sorry no.

## Did restic help you or made you happy in any way?

Best backup program ever - love it - keep going :-)

**Comment by fd0** [comment] 2018-05-05 10:49
Thanks for the report!

This is not an error in restic, the message means that restic was blocked for more than 120 seconds while waiting on IO. It may very well be the case that restic is the cause for the IO blockage, as it is using a lot of resources in the 0.8.3 release. We've since reworked the archiver code (see #1494), and the next release will be much less resource-hungry.

Would you mind testing this again on the master branch? 
You can find compiled binaries of the restic master branch here: https://beta.restic.net/?sort=time&order=desc

I'm closing this issue for now, please report back (and feel free to add further comments). Thanks!

**Closed by fd0** 2018-05-05 10:49 UTC
