### ISSUE TITLE
[0.9.4] Restic restore displays timezone offset twice

### ISSUE THREAD

**Issue by whereisaaron** [restic/restic#2259] opened 2019-04-30 06:04 UTC
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

How did you run restic exactly?
-------------------------------

`restic restore --repo b2:foo --target /bar/ a1234567`

```
...
restoring <Snapshot a1234567 of [/foo/bar] at 2019-04-18 03:06:12.28791144 +1200 +1200 by @someone> to /baz/
...
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

B2

Expected behavior
-----------------

Display timezone offset just once

Actual behavior
---------------

Displays time offset twice, e.g. `+1200 +1200`

Steps to reproduce the behavior
-------------------------------

`restic restore --repo b2:foo --target /bar/ a1234567`

Did restic help you or made you happy in any way?
-------------------------------------------------

Restored 2.5GB files in a nice fast time by using a restore server not too far from B2 (low latency).

**Comment by fd0** [comment] 2019-05-08 14:29
Hm, I'm not sure what's going on here. I cannot reproduce the issue in the master branch:
```
restoring <Snapshot c08648ca of [/baz] at 2019-05-08 16:05:03.736337421 +0200 CEST by fd0@mopped> to test-restore
```

Using the release binary for 0.9.4 also does not show the extra timezone:
```
restoring <Snapshot c08648ca of [/baz] at 2019-05-08 16:05:03.736337421 +0200 CEST by fd0@mopped> to foobar
```

Any idea what's going on? What's your timezone?

Can you please paste the output of `restic cat snapshot a1234567` (where `a1234567` is the ID for a snapshot for which two timezone offsets are displayed)?

**Comment by fd0** [comment] 2019-05-08 14:31
Ah, I have an idea what's going on:

Let's compare the output:
```
restoring <Snapshot c08648ca of [/baz] at 2019-05-08 16:05:03.736337421 +0200 CEST by fd0@mopped> to foobar
restoring <Snapshot a1234567 of [/foo/bar] at 2019-04-18 03:06:12.28791144 +1200 +1200 by @someone> to /baz/
```
You can see that restic (or, rather, the Go standard library function) by default displays the offset as well as the name for the timezone. Do you maybe use an odd timezone? Or one that isn't known to either the Go standard library or your operating system?

**Comment by MichaelEischer** [comment] 2020-10-01 08:16
As the double timezone offset is a result of the Go standard library being unable to decide one a name for the timezone, I don't think there's much we can do here. @whereisaaron Would you object to closing this issue?

**Comment by MichaelEischer** [comment] 2020-11-15 13:14
Closing this issue as no objects were raised.

**Closed by MichaelEischer** 2020-11-15 13:14 UTC
Labels: state: need feedback, state: need triaging, type: bug

**Comment by whereisaaron** [comment] 2021-04-02 09:12
Late back to the party here sorry. Agree it is not a 'restic' bug and there is no reason for us to work around 'go' display format bugs. Closed.
