### ISSUE TITLE
is restic prune slow issue is fixed and merged? Please guide me to the solution. 

### ISSUE THREAD

**Issue by mkanna** [restic/restic#2892] opened 2020-08-18 16:05 UTC
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.11.5 on linux/amd64

How did you run restic exactly?
-------------------------------
restic backed s3 bucket.  daily & hourly snapshots, restic prune takes a lot of time 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
s3 bucket

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by aawsome** [comment] 2020-08-18 18:31
see #2718 
This issue is actually a duplicate of #1599 and #2162. :wink:

**Closed** 2020-08-18 19:24 UTC
