### ISSUE TITLE
Restic 0.16.3 stop working on Windows 2008 R2

### ISSUE THREAD

**Issue by Mitchou** [restic/restic#4652] opened 2024-01-22 10:03 UTC
Output of `restic version`
--------------------------
Not working (but is 0.16.3)

```
C:\Users\myuser>L:\restic_0.16.3_windows_amd64.exe version
Exception 0xc0000005 0x8 0x0 0x0 PC=0x0

runtime.asmstdcall()
        /usr/local/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46d335
rax     0x0
rbx     0x1b5e300
rcx     0x1bb4100
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1b855b8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1b5da60
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

What backend/service did you use to store the repository?
---------------------------------------------------------
Not Applicable

Problem description / Steps to reproduce
----------------------------------------
When I type only restic in the commande line on my Windows 2008 R2 Server:
```
C:\Users\myuser>L:\restic_0.16.3_windows_amd64.exe
Exception 0xc0000005 0x8 0x0 0x0 PC=0x0

runtime.asmstdcall()
        /usr/local/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46d335
rax     0x0
rbx     0x1b5e300
rcx     0x1bb4100
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1b855b8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1b5da60
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```
I've try on my Windows 11 with no problem

Expected behavior
-----------------
Restic help text

Actual behavior
---------------
See problem descriptions

Do you have any idea what may have caused this?
-----------------------------------------------
Latest version on Restic 0.16.3, no problem with 0.16.2

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is the best backup app !!! I use it every day on all my devices

**Comment by ProactiveServices** [comment] 2024-01-22 14:18
Duplicate of https://github.com/restic/restic/issues/4636 , which might be worth pinning to the issue tracker.

**Comment by rawtaz** [comment] 2024-01-22 14:22
Yes, this is because the Go compiler has removed support for old and unsupported Windows versions. This has been on the wall for a long time, so there's really no other recommendation that can be given other than to move on from such old Windows versions.

**Closed by rawtaz** 2024-01-22 14:22 UTC
