### ISSUE TITLE
wording: output of 'restic forget'

### ISSUE THREAD

**Issue by tribor** [restic/restic#3056] opened 2020-11-04 17:54 UTC
minor bug! the output of restic forget contains the word 'snapshots' two times

Output of `restic version`
--------------------------
```
/ # restic version
restic 0.9.6 compiled with go1.13.10 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
/ # restic forget -l2
repository 1d504fe1 opened successfully, password is correct
Applying Policy: keep the last 2 snapshots snapshots
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local path

Expected behavior
-----------------
`Applying Policy: keep the last 2 snapshots`

Actual behavior
---------------
`Applying Policy: keep the last 2 snapshots snapshots`

**Comment by rawtaz** [comment] 2020-11-04 18:11
Thanks for taking the time to report this. I believe this was fixed in https://github.com/restic/restic/pull/2959 (which is in master as it was done after v0.10.0 was released). If you want to/can verify this you can use the latest master build from https://beta.restic.net/?sort=time&order=desc . I'm closing this for now, if you suspect the issue isn't fixes, please comment here and we'll re-open :)

**Closed by rawtaz** 2020-11-04 18:11 UTC
