### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by dominikschulz** [restic/restic#544] opened 2016-07-17 09:27 UTC
## Output of `restic version`
restic 0.1.0 (v0.1.0-556-gc9ab75a)
compiled at 2016-07-06 20:50:51 with go1.6

## Expected behavior
`restic rebuild-index` completes without error.

## Actual behavior
`restic rebuild-index` failes with multiple "too many open files" errors.

```error for pack cfeb7ef9847d399ad2438a32cf0c06273fe2f7bf7a226d695c22086fdaf33b87: seeking to read header length failed: Get https://mybucket.s3-eu-west-1.amazonaws.com/restic/data/cfeb7ef9747da99ad2438a82cf3c06273fe2f7bf7a226d695c22086fdaf33b87: dial tcp: lookup mybucket.s3-eu-west-1.amazonaws.com on 192.168.1.1:53: dial udp 192.168.1.1:53: socket: too many open files
error for pack 9646553db8f36d1e913cc551bd43dd3560bc6d69b1e238f76519473f5204ed69: reading header length failed: Get https://mybucket.s3-eu-west-1.amazonaws.com/restic/data/9646553db8f36d1e913cc551bd43dd3560bcfd89b1e238f7651997345204ed69: dial tcp: lookup mybucket.s3-eu-west-1.amazonaws.com on 192.168.1.1:53: dial udp 192.168.1.1:53: socket: too many open files
loaded blobs from 244 packs
  saving new index
Put https://mybucket.s3-eu-west-1.amazonaws.com/restic/index/4a10c82380d32eba0373d1da058b7a8e77d8b7144262046f7b2af2d9bb5c8154: dial tcp: lookup mybucket.s3-eu-west-1.amazonaws.com on 192.168.1.1:53: dial udp 192.168.1.1:53: socket: too many open files
error in cleanup handler: dial tcp: lookup mybucket.s3-eu-west-1.amazonaws.com on 192.168.1.1:53: dial udp 192.168.1.1:53: socket: too many open files```

`ulimit -n` is at the default of 1024.

## Steps to reproduce the behavior

Run the following on a sufficently large directory (e.g. > 20k files):
```
restic init
restic backup /home
restic rebuild-index
```

**Comment by fd0** [comment] 2016-07-20 19:07
This is a bug, thanks for reporting!

**Comment by benagricola** [comment] 2016-07-29 10:35
Maybe related, I bumped ulimit -n to 65535 for testing and started running into socket errors:

```
root@****:~/restic# netstat -nap | grep restic | wc -l
28230
```

It appears that restic is holding open a single TCP connection to the S3 backend (in this case MinIO) for every data file or something like that.

**Comment by fd0** [comment] 2016-07-29 11:03
Huh, this is really strange, I'll contact the minio people about this.

Do you regularly run into this issue? Can you reproduce it? In this case I can come up with a few things we could try.

**Comment by benagricola** [comment] 2016-07-29 12:50
#552 might help with this if the open file issue *is* down to lots of open HTTP connections

**Comment by fd0** [comment] 2016-07-29 18:31
Can you try again with the current master (including the patch by @benagricola, #552)?

**Comment by pdf** [comment] 2016-08-21 12:41
@fd0 can reproduce with current master, `restic prune` on a relatively small repo with a minio backend quickly produces load avg ~900, uses all available memory (I only had 6GB free) and `too many open files`.

**Comment by fd0** [comment] 2016-08-21 13:03
@pdf thanks for reporting. The memory issue is probably caused by #565, which also applies to HTTP1 (only less severe). I don't have any idea why so many connections are collected, but I'll look into it.

**Comment by fd0** [comment] 2016-08-21 13:05
How large (in terms of #files and space) is the repo you tested this with?

**Comment by pdf** [comment] 2016-08-21 13:10
~1.8m files and ~100GB.  Attached is the golang stack (`kill -QUIT`) while it's tripping over the open files limit.

[restic-dump.txt](https://github.com/restic/restic/files/428847/restic-dump.txt)

**Comment by fd0** [comment] 2016-08-21 13:23
Observation: This does only occur when running `rebuild-index` or `prune`. Hm.

**Comment by fd0** [comment] 2016-08-21 13:26
Oh, I can reproduce it locally, looking into this now.

**Comment by fd0** [comment] 2016-08-21 14:11
Found the bug, very embarrassing.

**Comment by fd0** [comment] 2016-08-21 14:23
This is the fix: https://github.com/restic/restic/pull/579/files#diff-6bb6c9bcf3c5b6d5bf1f8d475ac98eb5R197

Could you please test the code in the branch `debug-544`?

**Comment by pdf** [comment] 2016-08-21 14:38
Yeah, that'll do it.

**Comment by fd0** [comment] 2016-08-21 14:53
What does that mean? It works (and the connection numbers are down)?

**Comment by pdf** [comment] 2016-08-21 14:58
Correct - not closing the obj in `Stat()` would certainly leak connections and goroutines, and I'm no longer seeing out of control memory growth or connections as a result of the change there.  AFAICT with a quick desk-check, you've covered all the leaky method calls now.

**Comment by fd0** [comment] 2016-08-21 15:09
Awesome, thanks for the confirmation. I'm going to merge the PR now.

**Closed** 2016-08-21 15:10 UTC
Labels: backend:s3, bug
