### ISSUE TITLE
Manually lock the database

### ISSUE THREAD

**Issue by akrabu** [restic/restic#3333] opened 2021-03-11 19:07 UTC
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.7 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Here's an idea.  How about "restic lock" - all it would do is lock the database from any operation.  Say you're about to sync to another cloudspace, and you don't want any clients automatically backing up to it in the meantime.  Run restic lock, transfer, then unlock on the target endpoint.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Could come in handy to be able to stop incoming backups (etc) purposefully before maintenance, syncing operations, etc.  Especially if you have a large number of clients and a wide, randomized backup window.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always! :)

**Comment by MichaelEischer** [comment] 2021-03-11 19:23
Closing this as duplicate of #2166. In case you have no scripts that automatically run `unlock`, you could create a copy of the lock file create by `check` or `prune` and place that in the lock folder when you want to block operations on the repository.

**Closed by MichaelEischer** 2021-03-11 19:23 UTC
