### ISSUE TITLE
--files-from: "pattern ... does not match any files, skipping" / "syntax error in pattern"

### ISSUE THREAD

**Issue by kiuuik** [restic/restic#2276] opened 2019-05-19 01:25 UTC
Output of `restic version`
--------------------------

I tried with a binary you provide 

     restic 0.9.5 compiled with go1.12.4 on linux/amd64

and a version I built today ("go get" and then "go build.go")

     restic 0.9.5 (v0.9.5-30-g5bd5db42) compiled with go1.12.5 on linux/amd64

summary
--------------------------

`--files-from` doesn't work for me as expected. If I have a file `0 [1].docx` and its absolute paths `/some/path/0 [1].docx` in a line in a textfile and when I run `restic backup --files-from textfile` I get this error: `pattern "/some/path/0 [1].docx" does not match any files, skipping`.

After reading the example with `find ... | grep ...` in the manual under [including-and-excluding-files](https://restic.readthedocs.io/en/stable/040_backup.html#including-and-excluding-files) my impression is that I can use one file per line with any name?

How did you run restic exactly?
-------------------------------

    $ flist="/tmp/flist.txt"
    $ find "$HOME/Desktop/testsource/" -type f > "${flist}"
    $ restic --repo "$HOME/repo" -p "$HOME/password.txt" backup --files-from "${flist}"

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

local folder

Expected behavior
-----------------

backup those files when they are in a text file that I use as an argument for `--files-from`. The textfile has these lines:

    /home/user/Desktop/testsource/1 [1] text
    /home/user/Desktop/testsource/0 [1].docx
    /home/user/Desktop/testsource/01 [02] text.docx
    /home/user/Desktop/testsource/0 [1]
    /home/user/Desktop/testsource/2 [3]

Actual behavior
---------------

    $ restic --repo "$HOME/repo" -p "$HOME/password.txt" backup --files-from "${flist}"
    pattern "/home/user/Desktop/testsource/1 [1] text" does not match any files, skipping
    pattern "/home/user/Desktop/testsource/0 [1].docx" does not match any files, skipping
    pattern "/home/user/Desktop/testsource/01 [02] text.docx" does not match any files, skipping
    pattern "/home/user/Desktop/testsource/0 [1]" does not match any files, skipping
    pattern "/home/user/Desktop/testsource/2 [3]" does not match any files, skipping
    Fatal: nothing to backup, please specify target files/dirs

If I have a file with a name like `2 [3` and I run the commands from above again I get

    syntax error in pattern
    pattern: /home/user/Desktop/testsource/2 [3

The files exist.:

    $ find /home/user/Desktop/testsource
    /home/user/Desktop/testsource
    /home/user/Desktop/testsource/1 [1] text
    /home/user/Desktop/testsource/0 [1].docx
    /home/user/Desktop/testsource/01 [02] text.docx
    /home/user/Desktop/testsource/0 [1]
    /home/user/Desktop/testsource/2 [3

the output of the find command shows the directory contents after I renamed one file to get the "syntax error in pattern" message. So the output of find here for this file doesn't match the file name from above where the error message was " does not match any files, skipping".

Did restic help you or made you happy in any way?
-------------------------------------------------

I've been a regular user for over a year with a different config. No problems yet and it allowed to recover some files that were overwritten by accident (which saved me some hours of work). I love that I can use one FOSS software on all my computers (win,linux) which saved me some hours of research, config, and testing. I love that it's really fast - I can run hourly cronjobs without the job running for a sustantial part of this hour ... Many Thanks for this amazing sofware.

**Comment by ProactiveServices** [comment] 2019-07-11 00:45
[Further reading](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) on rules for naming files, paths and namespaces in Windows.

**Comment by fzcar** [comment] 2019-07-30 21:11
I guess I have the same problem in Windows 10 1903 64bit (build 18362). I noticed with a file with a structure like `my file [ name.pdf`. 

For my os version and restic version check my powershell output: 

    PS C:\Users\Stephan> [System.Environment]::OSVersion.Version

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    10     0      18362  0


    PS C:\Users\Stephan> restic version
    restic 0.9.5 compiled with go1.12.4 on windows/amd64
    PS C:\Users\Stephan> restic -r C:\testdest\ init
    enter password for new repository:
    enter password again:
    created restic repository 830832d916 at C:\testdest\

    Please note that knowledge of your password is required to access
    the repository. Losing your password means that your data is
    irrecoverably lost.
    PS C:\Users\Stephan> $TempFile = New-TemporaryFile
    PS C:\Users\Held> Get-ChildItem -Path C:\testsource -Recurse | % { $_.FullName } > $TempFile   # an alternative would be:     fd . 'C:\testsource\' >$TempFile
    PS C:\Users\Held> Get-Content $TempFile
    C:\testsource\my file name.pdf
    C:\testsource\my file [ name.pdf
    C:\testsource\my file ] name.pdf
    PS C:\Users\Held> restic -r  C:\testdest\ backup --files-from $TempFile
    syntax error in pattern
    pattern: C:\testsource\my file [ name.pdf


I also tried with a file like the OP has (`C:\testsource\1 [01] AT.pdf`). Such files are not saved. I used a new repo:
    
    PS C:\Users\Stephan> $TempFile = New-TemporaryFile
    PS C:\Users\Stephan> Get-ChildItem -Path C:\testsource -Recurse | % { $_.FullName } > $TempFile
    PS C:\Users\Stephan> Get-Content $TempFile
    C:\testsource\1 [01] AT.pdf
    C:\testsource\1 [02] AT.pdf
    C:\testsource\1_2.pdf
    PS C:\Users\Stephan> restic -r  C:\testdest\ backup --files-from $TempFile
    pattern "C:\\testsource\\1 [01] AT.pdf" does not match any files, skipping
    pattern "C:\\testsource\\1 [02] AT.pdf" does not match any files, skipping
    enter password for repository:
    repository 830832d9 opened successfully, password is correct
    created new cache in C:\Users\Stephan\AppData\Local\restic

    Files:           1 new,     0 changed,     0 unmodified
    Dirs:            2 new,     0 changed,     0 unmodified
    Added to the repo: 907 B

    processed 1 files, 14 B in 0:00
    snapshot c6c9ab32 saved
    PS C:\Users\Stephan>   # notice that the list included three files but only one file was added

**Comment by kiuuik** [comment] 2019-10-30 23:51
issue #2448 ("Paths in --files-from files that include brackets aren't backed up") which mentions pull request #1892 ("Expand Glob wildcards character in paths in file in --files-from") seems relevant.

I built restic from the commit prior to #1892 and then with the commit from #1892.  In the former case it works but not in the latter.

Details:   cloned the restic repo and then did 

    git checkout 0c0a8e3d
    go run build.go
    ./restic --repo "$HOME/repo" -p "$HOME/password.txt" backup --files-from "${flist}"

This works as expected and I can't reproduce the problem mentioned above.

Then I did 

    git checkout e2da0a41
    go run build.go
    ./restic --repo "$HOME/repo" -p "$HOME/password.txt" backup --files-from "${flist}"

Now the files are not in the snapshot and I have the problem mentioned above.

So maybe it's about commit e2da0a41. Keep in mind I'm not a programmer ...

**Comment by rawtaz** [comment] 2019-11-18 01:46
@kiuuik @fzcar Sorry to hear you are having this issue. As you have already identified, the commit in #1892 introduced the cause of the issue, which is the globbing of the pattern.

Restic globs the patterns listed in the `--files-from` file using https://golang.org/pkg/path/filepath/#Glob. In https://golang.org/pkg/path/filepath/#Match you can read that `[` and `]` are special chars in this context (e.g. `[a-z]` means "one of any of the characters from a to z").

This means that when you list e.g. `0 [1].docx` in your `--files-from` file, the filename that would match the globbing that takes places is `0 1.docx`, which naturally is not what you expect in your case.

@kiuuik I think you should be able to solve this by escaping the `[` and `]` in your patterns. Instead of `[1]`, write `\[1]` or `\[1\]` or `\\[1]` or `\\[1\\]` (I believe the first one should work, but aren't sure as I haven't tried it).

@fzcar Unfortunately, on Windows the escaping is disabled. In https://golang.org/pkg/path/filepath/#Match you can read "On Windows, escaping is disabled. Instead, '\\' is treated as path separator." which means that doing what I suggested above as a workaround won't work. Instead, you can try to replace the `[` and `]` with a `?`, that might work (please note that it will match *any* character where the `[` or `]` would be, so it might match more than you want).

**Comment by kiuuik** [comment] 2019-11-30 17:01
Thanks for the solution and sorry for answering so late. I should have read the documentation more carefully - when it comes to globbing I didn't think that other characters than `*` and `?` might get a special treatment .

So on non-Windows systems I just need to postprocess the output of find with a regular expression search&replace like `find .... | perl -pe 's/(\\|\-|\[|\?|\*)/\\\1/g' > my-file-list.txt` ? On Windows you could probably run this command from the "Windows Subsystem for Linux"?

**Comment by Kris013f** [comment] 2020-01-01 13:13
Creating backups taking into account conditions on large databases is very difficult, e.g. for f = `find" $ {dir} "-size + $ {s0} c -size - $ {s1} k -type f -not -name '* .pdf '-not -name' * .jpeg ''
tar czvf bakup_365d (0c-2015M) _10: 30.tgz --force-local --no-recursion --files-from <(echo "$ f") # works perfectly
but
restic backup -vr "${resticSftp}" --files-from <(echo "$f")  # don't work for filenames with some chars e.g. "["
The solution could be variable support (in linux): 'set -o noglob'

**Comment by MichaelEischer** [comment] 2021-08-18 22:24
Closing this issue as there's the `--files-from-verbatim` option since restic 0.12.0 which interprets paths without globbing.

**Closed by MichaelEischer** 2021-08-18 22:24 UTC
