### ISSUE TITLE
Restic unnecessarily requires lock for "forget" command with "--dry-run" and "--no-lock" specified

### ISSUE THREAD

**Issue by ATLief** [restic/restic#2550] opened 2020-01-16 05:55 UTC
I'm currently running a long backup operation and would like to improve my cron scripts at the same time. I'd like to see how the `forget` command would affect my backups. Since this is a read-only operation, acquiring a lock on the repository shouldn't be necessary.

**Output of `restic version`**
> restic 0.9.5 compiled with go1.12.9 on linux/amd64

**How did you run restic exactly?**
Command:
`restic forget -H 16 -d 7 -w 4 -m 18 -y 4 --no-lock -n --password-file=/path/to/password-file -r /path/to/repo`

Output:
> repository c63c41de opened successfully, password is correct
> Fatal: unable to create lock in backend: repository is already locked by PID 23156 on hostname by root (UID 0, GID 0)
> lock was created at 2020-01-15 23:55:25 (49m50.228631411s ago)
> storage ID 8179edd2

**What backend/server/service did you use to store the repository?**
A locally mounted disk formatted with ext4.

**Expected behavior**
Show how the `forget` command with the given parameters would affect the specified backup repository, without requiring its own lock. Stated differently, `restic forget --no-lock -n [...]` or `restic forget --no-lock --dry-run [...]` should work regardless of whether another process has locked the repository.

**Actual behavior**
Restic refuses to perform the command if another process has locked the repository.

**Steps to reproduce the behavior**
1. Start a backup, or any other operation requiring a lock on the repository.
2. In another session, attempt to run the `forget` command mentioned above

**Do you have any idea what may have caused this?**
A missing or incorrectly written check.

**Do you have an idea how to solve the issue?**
Add a special case within the `forget` command that bypasses the attempt to lock the repository if `--dry-run` (or `-n`) and `--no-lock` are specified, or remove the check preventing this behaviour in this situation.

**Did restic help you today? Did it make you happy in any way?**
Yes, it just saved my system/data from a RAID corruption. Restic didn't really make me "happy" so much as "less sad".

**Comment by MichaelEischer** [comment] 2021-08-19 13:12
Closing as duplicate of #3464

**Closed by MichaelEischer** 2021-08-19 13:12 UTC
