### ISSUE TITLE
Extend --ignore-inode to support directories

### ISSUE THREAD

**Issue by weisdd** [restic/restic#3357] opened 2021-04-07 21:57 UTC
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

If I haven't misread the source code, currently, the `--ignore-inode` option covers only files, not directories. As a consequence, we're getting the following stats after a backup is completed for a FUSE-based file system (s3fs-fuse):

```json
{
    "message_type": "summary",
    "files_new": 297,
    "files_changed": 0,
    "files_unmodified": 23692,
    "dirs_new": 467,
    "dirs_changed": 39514,
    "dirs_unmodified": 3045,
    "data_blobs": 510,
    "tree_blobs": 39980,
    "data_added": 360926862,
    "total_files_processed": 23989,
    "total_bytes_processed": 30678305296,
    "total_duration": 3998.24064557,
    "snapshot_id": "0281d215"
}
```

So, it looks as if ~39.5k of directories have changed since the last backup, ~3k stayed unmodified (happened to have the same inode), whereas in reality, the only change was: `"dirs_new": 467, "files_new": 297`.

It would be great if `--ignore-inode` option could cover not only files, but directories as well.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

We're trying to backup minio buckets, which are mounted with the help of s3fs-fuse.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Absolutely :) One of the best pieces of software I've ever come across :)

**Comment by greatroar** [comment] 2021-04-08 06:37
`--ignore-inode` only changes the behavior of the `fileChanged` heuristic, which determines whether file contents should be read to find changes. What you're suggesting is that it should also cause metadata changes to no longer be tracked.

I think that can lead to inconsistencies when restoring. E.g., the restorer may try to create one file as a hard link of another, because the inode for one was reused for the other across backups.

**Comment by weisdd** [comment] 2021-04-08 08:53
@greatroar Thanks for the detailed reply!
I'm not well versed at restic's or S3 internals, so can't be sure if my thinking is correct here. S3 mounts come at the expense of sending lots of HTTP requests. When you've got tens of thousands of directories, each extra request per object leads to longer backup time as the operation is way more expensive than with local files. If the number of requests restic sends doesn't change with different inodes, then I guess it's fine.

**Comment by greatroar** [comment] 2021-04-08 18:29
Scanning the directories is unavoidable: restic has to find every file and stat it because it works at the POSIX fs level.

I'm not familiar enough with S3 to answer precisely how many requests that costs. I do see that [s3fs-fuse has a cache of stat results](https://github.com/s3fs-fuse/s3fs-fuse/blob/3663082a01319006aa04cfce869433ee00944016/doc/man/s3fs.1#L157), which you can tune if your buckets are very large.

**Comment by weisdd** [comment] 2021-04-10 12:37
Well, I played with the cache options before, though failed to see significant reduction in backup time.
In the end, I decided to replace s3fs with `mc mirror` (command from minio that just copies all files from s3 bucket to a local folder) for buckets containing tens of thousands of small files spread across thousands of paths. It reduced the total time to backup by 20 times at a cost of extra storage and having false statistics for files (restic does not currently allow to ignore mtime, and changes in mtime are inevitable with mc mirror).
---
If extending `--ignore-inode` to directories does not currently make any sense, we can close the issue. I just thought it might be an important change.

**Comment by MichaelEischer** [comment] 2021-04-10 21:13
Just ignoring the inode for some kind of change detection (which doesn't exist for directories, restic always traverses all directories) wouldn't be enough. We'd have to remove the inode from the directory metadata as otherwise the directories will keep changing. And I'm not sure that's a good idea.

**Comment by greatroar** [comment] 2021-04-12 21:22
Hard-linking directories normally isn't allowed (only macOS allows it to support Time Machine, IIRC) and the restorer doesn't try. So an option to not store directories' inode numbers should be safe, right?

**Comment by MichaelEischer** [comment] 2021-05-14 17:56
We'd have to not store any inodes at all. Otherwise the directory content would still change every time the inode of any file changes. The restorer should be able to handle that case when the number of links for all files is 1. But the only problem we can solve by that is to reduce the directory metadata duplication; it won't speed up the backup times. I'm not sure whether it's worth to complicate the backup code for a bit less metadata.

**Comment by weisdd** [comment] 2021-05-24 08:48
Well, my concern was mostly about statistics. If the suggested change is potentially harmful, let's close the issue with a closing note that the current behavior is intentional.

**Comment by MichaelEischer** [comment] 2021-06-05 11:38
Let's close this issue for now. We can revisit it at a later time, when this causes a problem due to a too large directory metadata size.

**Closed by MichaelEischer** 2021-06-05 11:38 UTC
Labels: category: backup, type: feature suggestion

**Comment by wendell77** [comment] 2024-12-13 13:24
I use restic to back up a Google Drive structure. It has thousands of folders. The --ignore-inodes parameter is not applied to folders, so the backup takes more than 10 hours to scan the entire structure even though there are no new or modified files. Is there a solution to mitigate the impact of modifying the folders' inodes? @MichaelEischer

**Comment by MichaelEischer** [comment] 2025-02-01 22:44
restic always walks the full directory structure. Directory inodes aren't relevant in any way for the backup performance. If you have a list of changed files, then maybe https://github.com/restic/restic/issues/4804 could help otherwise you'll need to find some way to speed up the tools that provides the Google Drive structure.

**Comment by wendell77** [comment] 2025-02-05 15:09
> restic always walks the full directory structure. Directory inodes aren't relevant in any way for the backup performance. If you have a list of changed files, then maybe [#4804](https://github.com/restic/restic/issues/4804) could help otherwise you'll need to find some way to speed up the tools that provides the Google Drive structure.

When the repository is Google Drive, for example, restic updates all folders even if no files are updated. See:
2025-02-05 00:43:47 modified  /drive/dir1/a/1
2025-02-05 00:43:47 modified  /drive/dir1/a
2025-02-05 00:43:47 modified  /drive/dir1
2025-02-05 00:43:47 modified  /drive/

This folder update does not occur when the repository is local.

**Comment by MichaelEischer** [comment] 2025-02-07 20:37
> When the repository is Google Drive, for example, restic updates all folders even if no files are updated

This can occur when the metadata of those folders differs across restic executions. You can compare the directory metadata stored by restic to see what changes:
```
restic cat tree <firstSnapshotID>: /drive/dir1/a/1 | jq
restic cat tree <secondSnapshotID>: /drive/dir1/a/1 | jq
```

However, unless there are millions of folders, updating the directory metadata shouldn't have much impact on restic's performance.

**Comment by wendell77** [comment] 2026-05-22 14:18
> > When the repository is Google Drive, for example, restic updates all folders even if no files are updated
> 
> This can occur when the metadata of those folders differs across restic executions. You can compare the directory metadata stored by restic to see what changes:
> 
> ```
> restic cat tree <firstSnapshotID>: /drive/dir1/a/1 | jq
> restic cat tree <secondSnapshotID>: /drive/dir1/a/1 | jq
> ```
> 
> However, unless there are millions of folders, updating the directory metadata shouldn't have much impact on restic's performance.

Files:         143 new,     8 changed, 104229 unmodified
Dirs:          339 new, 85661 changed,     0 unmodified
Data Blobs:    133 new
Tree Blobs:    335 new
Added to the repository: 101.635 MiB (91.004 MiB stored)

processed 104380 files, 222.686 GiB in 8:20:58

**Is 8:20 a satisfactory time?**

**Comment by MichaelEischer** [comment] 2026-05-30 20:41
> Tree Blobs: 335 new
> Added to the repository: 101.635 MiB (91.004 MiB stored)

This basically proofs that the slow backup is NOT caused by restic having to upload large amounts of new tree metadata.

As mentioned before: if it takes 8 hours for the filesystem to check the metadata of 100k files, then this is a problem of the filesystem not of restic.
