### ISSUE TITLE
Inconsistent find command

### ISSUE THREAD

**Issue by mnesrine** [restic/restic#892] opened 2017-03-20 14:25 UTC
## Output of `restic version`
restic 0.5.0
Behavior in Linux and Windows

## Expected behavior
In the restic manual it is noted that the 'find' command display the complete path.
Unless when we use the find, the results contains only the name of matching file.
Maybe I do something wrong, Otherwise he is being a bit inconsistent when we backup different path with the same filename.

## Steps to reproduce the behavior

`restic.exe backup C:\Users\nes\Desktop\10.pdf
 restic.exe backup C:\dev\bak\10.pdf
 restic.exe find *0.pdf

Found matching entries in snapshot 15974c44d41bec349be476ab340c760be3c328022dde02e3679b72576aeebe5f
/10.pdf

Found matching entries in snapshot 8a1a763de0f515151084c6b1f9aba6f395a07be17ed4e67c6a44b26c32d216d1
/10.pdf`

**Comment by yhafri** [comment] 2017-03-20 15:33
I was about to open the same issue.
@fd0 is that something hard to fix? Hope not !!!

**Comment by fd0** [comment] 2017-03-20 19:52
This is actually cause by #549: When called as `restic backup C:\Users\nes\Desktop\10.pdf`, it will save only the file, as `/10.pdf`. So the find command only displays what (little) structure there is in the repo. I'm going to close this as a duplicate of #549, which unfortunately is hard to fix. But I'm already working on it.

**Closed** 2017-03-21 20:06 UTC
Labels: bug, duplicate
