### ISSUE TITLE
`restic snapshots | head` does not unlock repository

### ISSUE THREAD

**Issue by lbausch** [restic/restic#3868] opened 2022-08-13 16:44 UTC
Output of `restic version`
--------------------------
Latest beta `restic_v0.13.0-359-gf0bb4f87_linux_amd64` (`restic 0.13.1-dev (compiled manually) compiled with go1.18 on linux/amd64`), but I was able to also reproduce it with the latest stable version 0.13.1 (`restic 0.13.1 compiled with go1.18 on linux/amd64`).

How did you run restic exactly?
-------------------------------

```
$ restic snapshots | head -n 1
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local repository.

Expected behavior
-----------------

Repository is not locked.

```
$ restic list locks
repository 98ead6a4 opened (repository version 1) successfully, password is correct
```

Actual behavior
---------------

Repository is locked.

```
$ restic list locks           
repository 98ead6a4 opened (repository version 1) successfully, password is correct
3d6554009e3c0b0959f97ad87811bcc3e3b795af07141647213e9606e8378615
```

Steps to reproduce the behavior
-------------------------------

```
$ export RESTIC_REPOSITOR=/path/to/repository
$ export RESTIC_PASSWORD=<redacted>
$ restic init

# Create some snapshots
$ for i in $(seq 0 10) ; do restic backup /some/data ; done

# List snapshots
$ restic snapshots | head -n 1

# If the repository is not locked, list snapshots a second time
$ restic snapshots | head -n 1
```

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe piping the output of restic to `head` blocks the output and restic never reaches the point where it would we able to unlock the repository. I varied the amount of lines (`-n`) displayed by head and it seems like using a higher number of lines than the output of `restic snapshots` has, does not result in a locked repository.

Do you have an idea how to solve the issue?
-------------------------------------------

Unfortunately not.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic saved me several times already, it's just great 😄

**Comment by rawtaz** [comment] 2022-08-13 21:27
This is a duplicate of #1466.

You can work around it easily by piping through `tail` with a high-enough number, e.g. `restic snapshots | tail -9999 | head -1` (9999 need to be as high as the most amount of lines you expect to be output).

I'm closing this for now, but feel free to add more comments here or in #1466.

**Closed by rawtaz** 2022-08-13 21:27 UTC

**Comment by lbausch** [comment] 2022-08-13 22:18
Ah, didn't make the connection. Thanks!
