### ISSUE TITLE
Key based restoration restrictions when using a single repo for multiple hosts

### ISSUE THREAD

**Issue by mintyhippoxyz** [restic/restic#4767] opened 2024-04-16 20:33 UTC
Output of `restic version`
--------------------------

0.16.4

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

In a single repo multi host environment where each host has it's own key. I feel that the key should have the ability to optionally restrict restoring backups from other hosts.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I'm trying to take advantage of using a single repo but I have security concerns that 1 compromised host would allow an attacker to read the backups from all the other hosts, potentially turning a small data leak into a very large one.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Bacula user looking for something easier to deal with so yes, very much so :)

**Comment by MichaelEischer** [comment] 2024-04-17 16:38
> In a single repo multi host environment where each host has it's own key

All keys share the same underlying masterkey. Thus, it is impossible to restrict access based on keys.

Duplicate of https://github.com/restic/restic/issues/187 . This cannot be implemented without a massive rework of the repository format, which won't happen in the near term. 

For now, the _only_ possibility to address your use case is to use separate repositories for each host.

**Closed by MichaelEischer** 2024-04-17 16:38 UTC
