### ISSUE TITLE
regression: Fatal: Fatal: config cannot be loaded: ciphertext verification failed

### ISSUE THREAD

**Issue by kisst** [restic/restic#3430] opened 2021-06-13 15:15 UTC
Output of `restic version`
--------------------------

```
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```
vs.
```
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
restic -r /backup_target backup $HOME
open repository
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local mount-point of an NFS share

Expected behavior
-----------------

It should work in the latest version as well.

Actual behavior
---------------

in latest version I got the error:
```
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
```
In 0.11 and before the backup is started just fine, in 0.12 it doesn't, to ensure that I don't just make a typo I tried with the `export RESTIC_PASSWORD="mypassword"` as well.
Confirmed that the error is only related to the version.

Steps to reproduce the behavior
-------------------------------

Try to run backup, on latest version ? 

Do you have any idea what may have caused this?
-----------------------------------------------

Not really.

Do you have an idea how to solve the issue?
-------------------------------------------

Not really.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I managed to backup my data still ( after downgrade  ) so even if I'm not happy at least I'm not super sad, that's something, so I'm happy that the archive build assets are available for download.
And the self update feature is neat ( when it does not break the function :) )

**Comment by rawtaz** [comment] 2021-06-13 17:06
This was an interesting one. Can you please see if you can reproduce it with a repo that is stored on your local disk (not mounted from NFS or similar), created by restic 0.11.0 and then after some dummy backup with that version see if you can reproduce the problem with the same backup command but with restic 0.12.0?

**Comment by kisst** [comment] 2021-06-13 20:20
OK fair shout I can narrow down the error a bit more, I will test with both local copy of the existing repo and with fresh repo as well.

**Comment by MichaelEischer** [comment] 2021-08-17 19:55
Closing this issue as there's been no feedback in two months. Please try whether restic 0.12.1 works, if not feel free to reopen this issue.

**Comment by kisst** [comment] 2021-09-04 13:02
Tested with 0.12.1 and the same issue is still there, so rolled back again till 0.11, unfortunately I don't have enough storage to test the repo on local filesystem instead of NFS mount, but I will try to install restic on the NFS server and try it that way when I will have a time, if any other debugging options are available happy to try it in the meantime.

**Comment by MichaelEischer** [comment] 2021-09-04 14:08
@kisst My suspicion would be that this is caused by some issues with nfs. Which linux kernel is used on the nfs client and server? You could run restic using `strace` to see what goes wrong when trying to load the config file.

You could also try to build restic yourself. The first thing to try would be whether restic 0.11 works when built with a recent go version. If that is not the problem cause, then use `git bisect` to find whatever change in restic caused the problem.

**Comment by kisst** [comment] 2022-02-03 16:39
Xmas come late, but now I got hold of enough local storage so that I manager to copy the NFS repo to a local drive, and re-run the same tests, NFS was not the source of the error, so somehow my repo is broken but check come backs with no error, and old versions still works.

```
#:~ ./restic_0.10.0_linux_amd64 -r backup-local list locks
repository ******** opened successfully, password is correct
28e73ac621d68728ca55aeac998c88dd855520f6cacd4524f81b45e006982e62
#:~ ./restic_0.11.0_linux_amd64 -r backup-local list locks
repository ******** opened successfully, password is correct
11eb1ab963ede8f8481cb5a6aae74795c59d4e2f9c32fc36e35081c01e12f896
#:~ ./restic_0.12.0_linux_amd64 -r backup-local list locks
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
#:~ ./restic_0.12.1_linux_amd64 -r backup-local list locks
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
```
All binary's are directly from GitHub assets
```
#:~$ ./restic_0.10.0_linux_amd64 version
restic 0.10.0 compiled with go1.15.2 on linux/amd64
#:~$ ./restic_0.11.0_linux_amd64 version
restic 0.11.0 compiled with go1.15.3 on linux/amd64
#:~$ ./restic_0.12.0_linux_amd64 version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
#:~$ ./restic_0.12.1_linux_amd64 version
restic 0.12.1 compiled with go1.16.6 on linux/amd64
```

```
#:~$ md5sum ./restic_0.10.0_linux_amd64
f884ccdb2bebb6a7696f8b72c4080556  ./restic_0.10.0_linux_amd64
#:~$ md5sum ./restic_0.11.0_linux_amd64 
d6baada2b8c6c105e8c1a6f2a1da7ac8  ./restic_0.11.0_linux_amd64
#:~$ md5sum ./restic_0.12.0_linux_amd64 
3ffe5e74c4155b1671f5a9f61cde9640  ./restic_0.12.0_linux_amd64
#:~$ md5sum ./restic_0.12.1_linux_amd64 
1b783f0fa8412c61e56ec8f4515415a3  ./restic_0.12.1_linux_amd64
```

So what's my next debugging move ?

**Comment by MichaelEischer** [comment] 2022-02-05 22:37
I guess the only reasonable option left is to use `git bisect` to find out where the problem was introduced. But first build restic 0.11 and 0.12 using the same golang version and check whether both versions behave like before. Then use `git bisect` between these two restic releases.

Feel free to ask if you need more / much more detailed instructions on how to do that.

Btw: if you want to run these tests on a dev machine, you just need the `config` file and the `keys` folder. Did you test whether a different machine is able to decrypt the config file using a new restic version?

**Comment by kisst** [comment] 2022-02-07 13:34
I did test with 3 different machine, so we can rule that out, but I guess I need to get into building. 
This is the right place to start https://restic.readthedocs.io/en/stable/020_installation.html#from-source ?

**Comment by MichaelEischer** [comment] 2022-02-07 20:43
Yep, these steps will work. Or just run a plain `go build ./cmd/restic`. Just make sure that you use a recent go version (>= 1.14).

**Comment by kisst** [comment] 2022-03-10 08:33
I hope I did it right, let me know how can I help next
```
#:~/git/restic$ git bisect start
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.12.0 (v0.12.0-0-g27f24133) compiled with go1.17 on linux/amd64
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
#:~/git/restic$ git bisect bad
#:~/git/restic$ git bisect good v0.11.0
Bisecting: 191 revisions left to test after this (roughly 8 steps)
[1cdd38d9e0c772fadf18aa40684f49cad9c602bb] Merge pull request #3165 from restic/2747-doc-forget
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-191-g1cdd38d9) compiled with go1.17 on linux/amd64
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
#:~/git/restic$ git bisect bad
Bisecting: 95 revisions left to test after this (roughly 7 steps)
[fdec8051abff5445c1748a69c92eeea1139b1179] tags: Tweak description of --add/set/remove options
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-95-gfdec8051) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
4d9956bd48414ca5b190832ae22a5d1311a3c5272df711ea1a5dfddb0ddfa751
#:~/git/restic$ git bisect good
Bisecting: 47 revisions left to test after this (roughly 6 steps)
[a851c53cbe7053cf052079b6806fe22135248cbb] Use PackSize in checker
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-143-ga851c53c) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
e1dfce627ca097e4aed815909606e8b04c6fbb2a8850b9f15599744f2185bc77
#:~/git/restic$ git bisect good
Bisecting: 24 revisions left to test after this (roughly 5 steps)
[f2959127b6f4f0eff2568f10ae6f391fab0f612a] Merge pull request #3065 from greatroar/local-subdirs
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-166-gf2959127) compiled with go1.17 on linux/amd64
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
#:~/git/restic$ git bisect bad
Bisecting: 11 revisions left to test after this (roughly 4 steps)
[a568211b98fd8c9ab3c6126402d69fd6df38ab7f] Merge pull request #3128 from vrenaville/tzdata
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-154-ga568211b) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
4e13b32bd55112cc8afc941d24c4433a37708118c1fb01a2505955fd44b86d9b
#:~/git/restic$ git bisect good
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[a7b49c4889a0e12e298e568c3ccfe1e081615d99] Merge pull request #3119 from restic/keep-mountpoints
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-159-ga7b49c48) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
23647c3164c2a0ac9edd1db69dc30d0eb1b833dd4b95eb1ca7f53f0ff939d325
#:~/git/restic$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[52b98f7f95f38581283af9fc7de8db9c4883087a] Merge pull request #3017 from greatroar/files-from0
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-163-g52b98f7f) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
242ab823f59aa2af7b9c0835692917c1fb771a92548f22a4e4426fe5a6714124
#:~/git/restic$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 1 step)
[8e213e82fc86a50faf360f74789fa6f6e79c8a17] backend/local: replace fs.Walk with custom walker
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-26-g8e213e82) compiled with go1.17 on linux/amd64
Fatal: Fatal: config cannot be loaded: ciphertext verification failed
#:~/git/restic$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[a2d42093220b6f7e3c33af40138c001dd4e7b398] Don't recurse in local backend's List if not required
#:~/git/restic$ go run build.go && ./restic version && ./restic -r /backup_target list locks
restic 0.11.0 (v0.11.0-25-ga2d42093) compiled with go1.17 on linux/amd64
repository ******** opened successfully, password is correct
3ea0313b786e0fb74a413b1e22e6a4f4c89a054accbd3a1d4cf169b2c21fe39e
#:~/git/restic$ git bisect good
8e213e82fc86a50faf360f74789fa6f6e79c8a17 is the first bad commit
commit 8e213e82fc86a50faf360f74789fa6f6e79c8a17
Author: greatroar <@>
Date:   Thu Nov 19 16:46:42 2020 +0100

    backend/local: replace fs.Walk with custom walker

    This code is more strict in what it expects to find in the backend:
    depending on the layout, either a directory full of files or a directory
    full of such directories.

 internal/backend/local/local.go | 85 ++++++++++++++++++++++++++---------------
 1 file changed, 55 insertions(+), 30 deletions(-)
```

**Comment by MichaelEischer** [comment] 2022-03-10 20:56
The bisect run looks fine. So it seems to have something to do with listing the files in the `keys/` folder of the repository. Does `ls -la path/to/repo and path/to/repo/keys` show anything unusual? Maybe some hidden files or symlinks?

**Comment by MichaelEischer** [comment] 2022-03-22 21:43
Could you try whether `restic list locks --key-hint 'id-of-the-broken-key'` works with an _old_ restic version? Or does that result in the same error? It could be the case recent restic versions just try the keys in a different order...

**Comment by kisst** [comment] 2022-03-23 12:43
Specifying the ( broken ) key does break old versions too, tested with `0.9.6` , `0.10` and latest `0.12.1` they all work with any other key and neither works with the broken key.

**Comment by MichaelEischer** [comment] 2022-04-03 17:33
So it looks like the key is just broken. The strange thing here is that the key apparently matches the password you're using for the repository, but then includes the wrong key. I've no idea how that can happen, the only thing I could think of would be to manually copy keys between repositories.

So the only thing we could do here is to improve the error message and maybe return something like "config or key %s is damaged".

**Comment by kisst** [comment] 2022-04-05 04:27
I think that's plenty, a good error-message, and maybe, a try the next key ?

**Comment by MichaelEischer** [comment] 2022-04-09 20:21
Hmm, just printing a slightly more detailed error message would be much simpler to implement. And after all a damaged key is a serious problem that must be fixed as one otherwise risks loosing access to the repository. It also seems to occur rarely enough that I'd prefer a simple solution for now.

**Closed** 2022-04-10 18:25 UTC
Labels: state: need feedback, state: need investigating
