### ISSUE TITLE
Panic removing rest-tmp-pack file during backup on Win 10

### ISSUE THREAD

**Issue by patternseek** [restic/restic#1419] opened 2017-11-10 16:16 UTC
## Output of `restic version`

restic 0.7.3
compiled with go1.9.2 on windows/amd64

(Built from master downloaded 2017-11-08)

## How did you run restic exactly?

In cmd.exe I ran: 
cmd /c "C:\restic.exe backup --password-file c:\resticfl.txt -r b2:****-restic Users"
(cmd /c because it's a copy and paste from a scheduled task)

B2 keys set in environment variables

## What backend/server/service did you use?

B2

## Expected behavior

Complete the backup

## Actual behavior

Restic panics when trying to remove a temp file.

```
error while saving data to the repo: remove C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887: The process cannot access the file because it is being used by another process.
Remove
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:136
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:253
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:618
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2337
panic: Remove: remove C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887: The process cannot access the file because it is being used by another process.

goroutine 1606 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc0422b9220, 0xdf5940, 0xc042008180, 0x0, 0x40000, 0x1, 0xc04854c000, 0x40000, 0x80000, 0xc04232aa50, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x422
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d7
```

Procmon shows that no non-restic processes accessed that file and that only one restic process accessed it.

Final lines for the file in question from procmon:

```
3:29:31.6289340 PM	restic.exe	5704	ReadFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	Offset: 4,427,243, Length: 4,096
3:29:31.6682149 PM	restic.exe	5704	ReadFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	Offset: 4,431,339, Length: 23
3:29:36.2378350 PM	restic.exe	5704	CloseFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	
3:29:36.2387746 PM	restic.exe	5704	CreateFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SHARING VIOLATION	Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
3:29:36.2392334 PM	restic.exe	5704	CreateFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	NOT A DIRECTORY	Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
3:29:36.2399047 PM	restic.exe	5704	CreateFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
3:29:36.2400935 PM	restic.exe	5704	QueryBasicInformationFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	CreationTime: 10-Nov-17 3:04:55 PM, LastAccessTime: 10-Nov-17 3:04:55 PM, LastWriteTime: 10-Nov-17 3:29:36 PM, ChangeTime: 10-Nov-17 3:29:36 PM, FileAttributes: A
3:29:36.2401550 PM	restic.exe	5704	CloseFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS	
3:29:36.2736842 PM	restic.exe	5704	CloseFile	C:\Users\Tolan\AppData\Local\Temp\restic-temp-pack-412362887	SUCCESS

```
## Steps to reproduce the behavior

The initial snapshot saved fine. I ran restic again to see how long an incremental with minimal changes would take and got this error. The error happens each time I run the same restic command. I've also tried removing all the tmp-pack files between runs. I've also disabled AV.

## Do you have any idea what may have caused this?

Nope sorry.

## Do you have an idea how to solve the issue?

No.

**Comment by patternseek** [comment] 2017-11-10 17:45
Of course c:\Users which I'm backing up also contains the temp dir. I'll try changing the tmpdir and running again.

**Comment by fd0** [comment] 2017-11-10 20:08
Please report back, I think the problem is that restic is reading files from its own temp dir, so when the pack file is to be removed, it cannot be removed because restic is still reading it. The workaround is using the `TMPDIR` environment variable and set the tempdir for restic to something specific, and then exclude that via `--exclude`.

**Comment by fd0** [comment] 2017-11-10 20:09
I'm closing this bug as a duplicate of #1380, please do add further comments, thanks!

**Closed** 2017-11-10 20:09 UTC
Labels: bug, duplicate

**Comment by patternseek** [comment] 2017-11-11 17:30
Yes I moved the tmp dir for the user out of the folder being backed up and the snapshot completed successfully.
