### ISSUE TITLE
Document handling empty forget policy

### ISSUE THREAD

**Issue by alphapapa** [restic/restic#1519] opened 2018-01-02 08:55 UTC
After noticing that some files have been backed up that I don't want to be, I decided to forget all snapshots for a certain tag, but Restic won't let me:
```
$ restic -r /mnt/restic -p /mnt/restic/password forget --dry-run --tag main --keep-last 0 --group-by tags
password is correct
no policy was specified, no snapshots will be removed
```
If I use `--keep-last 1`, it offers to remove all but the latest snapshot.

This might actually be a good safety measure to prevent removing all snapshots in case of a typo, so maybe instead of changing this behavior, there should be an option like `--keep-none` that prompts the user to type `YES` as confirmation.

Thanks for your work on restic!

**Comment by fd0** [comment] 2018-01-02 20:41
Thanks for the report! You're right: for safety reasons, restic refuses to act on an "empty" policy. In this case, users can use `--keep-last 1` and remove the last snapshot ID manually (by passing the ID to `forget`).

This is not a bug, so I'm going to close this issue for now. Please feel free to add further comments, people with the same problem will find this issue.

**Comment by alphapapa** [comment] 2018-01-03 00:30
Ok.  Should we mention this in the docs?

**Comment by fd0** [comment] 2018-01-03 11:41
Good idea, are you up for a PR?

**Comment by alphapapa** [comment] 2018-01-03 16:37
Haha, sure.  Assign it to me if you would, in case I forget.  :)

**Comment by fd0** [comment] 2018-01-03 18:18
Done :)

**Comment by alphapapa** [comment] 2018-01-03 23:23
Thanks, a bit busy right now, but I'll get to it...

**Comment by rawtaz** [comment] 2018-02-13 23:54
Sorry about those two specific commit references popping up here. I was messing around with rebasing and splitting commits and those two were just WIP. They're not part of the PR at all, so I'm not sure why they're still listed, and would like to get them cleaned out.

**Closed** 2018-02-14 21:11 UTC
Labels: documentation, help wanted

**Comment by alphapapa** [comment] 2018-02-15 01:45
Forgot about this.  Thanks, good job.
