### ISSUE TITLE
`restic backup` hangs indefinitely over sftp

### ISSUE THREAD

**Issue by ghost** [restic/restic#2263] opened 2019-05-03 09:37 UTC
hello,

This issue is very similar to #2242.  

Output of `restic version`
--------------------------

on Debian stable (Debian 9)

$ restic version
restic 0.9.5 compiled with go1.12.4 on linux/amd64

this version was installed with `restic self-update`.

How did you run restic exactly?
-------------------------------

manually, for the purpose of this bug report:

```
restic backup --repo sftp:srv:/repo --password-file xxx --host yyy --exclude-caches --exclude 'build/*' --exclude '.stack-work/*' --exclude '*.o' --cleanup-cache --verbose=4 /home/damien
```

I don't setup environment variables for the purpose of restic configuration.

Backing-up on another machine, over LAN, via ssh.

`strace`ing the restic process, once the backup hangs, gives me the following:
```
# ...
[pid 26753] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 26740] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26740] <... ioctl resumed> , [26737]) = 0
[pid 26753] <... nanosleep resumed> NULL) = 0
[pid 26740] getpgid(0 <unfinished ...>
[pid 26753] futex(0xc0003a6848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26740] <... getpgid resumed> )     = 26737
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26740] write(1, "\r\33[2K[2:13] 6.03%  5104 files 5."..., 91) = 91
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26740] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 122 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26740] <... write resumed> )       = 122
[pid 26740] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 90) = 90
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26740] write(1, "\r\33[1A\33[1A", 9 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26740] <... write resumed> )       = 9
[pid 26740] futex(0xc00007a148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26738] futex(0x160bbb0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 26743] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 26743] futex(0x160bbb0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 26738] <... futex resumed> )       = 0
[pid 26743] futex(0xc00007a148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26743] <... futex resumed> )       = 1
[pid 26740] <... futex resumed> )       = 0
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26740] futex(0xc0003a6848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 26743] ioctl(1, TIOCGWINSZ <unfinished ...>
[pid 26753] <... futex resumed> )       = 0
[pid 26743] <... ioctl resumed> , {ws_row=62, ws_col=238, ws_xpixel=0, ws_ypixel=0}) = 0
[pid 26753] futex(0xc0003a6848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26743] futex(0xc0003a6848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 26753] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 26743] <... futex resumed> )       = 0
[pid 26753] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 26743] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 26740] <... futex resumed> )       = 1
[pid 26753] <... nanosleep resumed> NULL) = 0
[pid 26743] <... ioctl resumed> , [26737]) = 0
[pid 26753] futex(0xc0003a6848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26743] getpgid(0 <unfinished ...>
[pid 26740] futex(0x160fa80, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=999043474} <unfinished ...>
[pid 26743] <... getpgid resumed> )     = 26737
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26743] write(1, "\r\33[2K[2:14] 6.03%  5104 files 5."..., 91) = 91
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26743] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 122 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26743] <... write resumed> )       = 122
[pid 26743] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 90 <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26743] <... write resumed> )       = 90
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26743] write(1, "\r\33[1A\33[1A", 9) = 9
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26743] futex(0xc00007b2c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26738] futex(0x160bbb0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 26740] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 26740] futex(0x160bbb0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 26738] <... futex resumed> )       = 0
[pid 26740] futex(0xc00007b2c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26743] <... futex resumed> )       = 0
[pid 26740] <... futex resumed> )       = 1
[pid 26743] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid 26740] futex(0xc0003a6848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26753] <... futex resumed> )       = 0
[pid 26743] <... nanosleep resumed> NULL) = 0
[pid 26740] <... futex resumed> )       = 1
[pid 26743] futex(0xc00007b2c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26753] ioctl(1, TIOCGWINSZ <unfinished ...>
[pid 26740] futex(0x160fa80, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=998351940} <unfinished ...>
[pid 26753] <... ioctl resumed> , {ws_row=62, ws_col=238, ws_xpixel=0, ws_ypixel=0}) = 0
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26753] futex(0xc00007b2c8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 26743] <... futex resumed> )       = 0
[pid 26753] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 26743] futex(0xc00007b2c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26753] <... ioctl resumed> , [26737]) = 0
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26753] getpgid(0 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26753] <... getpgid resumed> )     = 26737
[pid 26753] write(1, "\r\33[2K[2:15] 6.03%  5104 files 5."..., 91 <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26753] <... write resumed> )       = 91
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26753] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 122) = 122
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26753] write(1, "\r\33[2K/home/damien/0 - archive/th"..., 90 <unfinished ...>
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26753] <... write resumed> )       = 90
[pid 26753] write(1, "\r\33[1A\33[1A", 9 <unfinished ...>
[pid 26738] <... nanosleep resumed> NULL) = 0
[pid 26753] <... write resumed> )       = 9
[pid 26738] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 26753] futex(0xc0003a6848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>

```

Actual behavior
---------------

At some point, the backup command "hangs" over a file.  I.e., the backup no longer seems to progress, and the displayed ETA continually grows.
Killing the backup command and running it again makes the backup progressing a little further, before hanging again.

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you or made you happy in any way?
-------------------------------------------------

Absolutely!! Restic is a fantastic tool! Albeit the current issue ;).

**Comment by polypolen** [comment] 2019-05-03 09:37
Don't know what other information I could give for further help, so feel free to ask ;).  thanks!

**Comment by fd0** [comment] 2019-05-08 14:23
Hi, thanks for the report. How much data are you saving?

Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by polypolen** [comment] 2019-05-13 09:13
hi Alexander, @fd0 

Thanks for your quick reply,

I should also mention that I target two backup servers.  
- Backups to the first one (say, serverA) work fine since 10 months.  The server is an older machine, on the intranet in my company.
- Backups to the second one (say, serverB) are exhibiting the issue reported here.  This server is a faster machine, which is in the same LAN than the client machine.  The network access are probably faster than on the first machine.


The size of the backup repository 252GB, but many directories or files are not backed up.  The size to backup is probably about 150GB.

Stats on serverA:
```
$ restic  --repo serverA stats
Stats for all snapshots in restore-size mode:
  Total File Count:   14416413
        Total Size:   1.536 TiB
$ restic  --repo serverA snapshots -c  | wc -l
49
```

Also, I forgot to mention that the client ssh configuration file (`~/.ssh/config`) contains these two settings, as reported in #2242.
```
Host backup-server   # aka serverB
    ...
    ServerAliveInterval 60
    ServerAliveCountMax 240
```

I did two successive backups on serverB, which froze at some point, but each time on a different backup point.

The (redacted) log session for the first backup is uploaded here: 
https://gist.github.com/polypolen/c330b268e68997f5ebf02ef8367e7b37

The first backup froze after showing this in the console:
```
new       /home/damien/.icedove/xxx.default/.../filterlog.html, saved in 0.001s (0 B added)
new       /home/damien/.icedove/xxx.default/.../llvm-dev, saved in 0.288s (0 B added)
scan finished in 17.797s: 854019 files, 93.996 GiB
  signal interrupt received, cleaning up
```


I started a second backup a few minutes after the first.  An extract of the second log is here:
https://gist.github.com/polypolen/907f6cb0e1d9b14af89b948fbffe81a0
This backup froze after showing this in the console:
```
new       /home/damien/.../Makefile, saved in 0.009s (0 B added)
new       /home/damien/.../fibonacci.odo, saved in 0.017s (0 B added)
new       /home/damien/.../test.cdg, saved in 0.017s (0 B added)
uploading intermediate index
  signal interrupt received, cleaning up
```

**Comment by aeltawela** [comment] 2020-09-12 20:29
I am also facing this exact issue

**Comment by MichaelEischer** [comment] 2020-09-30 23:01
@ghost, @aeltaweia: Please kill restic by sending it a SIGABRT signal when it hangs again. This will exit restic and print a stracktrace which should shed some light onto where restic currently hangs.

**Comment by MichaelEischer** [comment] 2020-11-15 13:21
Closing this issue for now as there are not enough information to reproduce / analyze it in any way. Feel free to reopen it when you can provide the requested information.  Please also try whether restic 0.11.0, which has fixed a backup hang, fixes the problem.

**Closed by MichaelEischer** 2020-11-15 13:21 UTC
Labels: state: need feedback, state: need triaging, type: bug
