### ISSUE TITLE
--exclude-if-present considered harmful, breaks deduplication instead of excluding files

### ISSUE THREAD

**Issue by whereisaaron** [restic/restic#1793] opened 2018-05-21 02:35 UTC
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

```
  command:
  - "/usr/local/bin/restic"
  args:
  - "backup"
  - "--quiet"
  - "--hostname=foo"
  - "--exclude-caches"
  #- "--exclude-if-present=auto.cnf"
  - "--tag=job"
  - "/vol/foo"
```

At first I ran backups with just `--exclude-caches` and all worked fine. However it was backing up MySQL data folders which I didn't want. It was backing up diffs for any files that had changed, e.g. MySQL log files:

```
# restic diff 35ee264c 59c42659 | grep logfile
M    /foo-blue-mysql-pvc-cbba2324-4649-11e8-b14a-0ac242bd291a/ib_logfile0
M    /foo-green-mysql-pvc-a6afe5fa-4649-11e8-b14a-0ac242bd291a/ib_logfile0
M    /foo-test-mysql-pvc-076fc58d-41f8-11e8-b14a-0ac242bd291a/ib_logfile0
M    /foo-blue-mysql-pvc-d5c8770c-5992-11e8-b14a-0ac242bd291a/ib_logfile0
M    /foo-green-mysql-pvc-8b60287e-5990-11e8-b14a-0ac242bd291a/ib_logfile0
M    /foo-green-mysql-pvc-fdf49adf-5995-11e8-b14a-0ac242bd291a/ib_logfile0
```

So to fix this I added to the backup `--exclude-if-present=auto.cnf` where `auto.cnf` is the MySQL server UUID file that MySQL servers make, so  a good flag to identify these directories.

However, it had the opposite of the intending impact. Instead of excluding the files in the directories, it now backs up every file in these directories, in full, every backup.

```
# restic diff 6fdd78d8 b5d4a072 | grep logfile
+    /foo-blue-mysql-pvc-cbba2324-4649-11e8-b14a-0ac242bd291a/ib_logfile0
+    /foo-blue-mysql-pvc-cbba2324-4649-11e8-b14a-0ac242bd291a/ib_logfile1
+    /foo-dev-mysql-pvc-e4a0fb9f-41fb-11e8-b14a-0ac242bd291a/ib_logfile0
+    /foo-dev-mysql-pvc-e4a0fb9f-41fb-11e8-b14a-0ac242bd291a/ib_logfile1
+    /foo-green-mysql-pvc-a6afe5fa-4649-11e8-b14a-0ac242bd291a/ib_logfile0
+    /foo-green-mysql-pvc-a6afe5fa-4649-11e8-b14a-0ac242bd291a/ib_logfile1
+    /foo-test-mysql-pvc-076fc58d-41f8-11e8-b14a-0ac242bd291a/ib_logfile0
... 
... many, many more MySQL logs files ...
...
+    /foo-test-mysql-pvc-7cc153e3-571c-11e8-b14a-0ac242bd291a/ib_logfile0
+    /foo-test-mysql-pvc-7cc153e3-571c-11e8-b14a-0ac242bd291a/ib_logfile1
```

The 'exclude' option, intended to make the snapshots smaller by excluding these unnecessary directories, instead makes every snapshot huge, with a complete fresh backup of these directories.

## Expected behavior

Directories containing the file `auto.cnf`, their contents and sub-directories would be excluded from the back-up snapshots.

## Actual behavior

Directories containing the file `auto.cnf` and their contents started getting backed up in full in every snapshot, like they were brand new files every time. Deduplication was entirely disabled for these directories.

## Steps to reproduce the behavior

See 'How did you run restic exactly?' above.

## Do you have any idea what may have caused this?

I am guessing the files get removes from the 'check for modification' list, but are still in the overall scan, so they appear to be 'new' rather than 'modified' files.

_**Extra note:** about the same time I added `--exclude-if-present` I also added `--quiet` to disable the progress scan. Not knowing the code I don't know if there could be any interaction there?_

## Do you have an idea how to solve the issue?

No, I couldn't find the relevant code in the current version with the Github search.

## Did restic help you or made you happy in any way?

I was pretty happy with everything until I added `--exclude-if-present` - but I could simple remove that option again and so now my inner calm has returned :smile:

**Comment by fd0** [comment] 2018-05-21 10:29
I'm unable to reproduce it, it works as expected. I also had a look at the code and couldn't spot anything odd which would explain the behavior you're describing.

I have a hunch. Would you mind trying the following: make a new backup with `--exclude-if-prensent`, then run `restic ls latest` and check the output for the files you'd like it to exclude, (maybe `restic ls latest | grep logfile`)?

**Comment by whereisaaron** [comment] 2018-05-21 20:05
When you say a 'new' backup, do you mean another snapshot? Or a backup to a new repository?

I tried adding `--verbose` and go the error 'unknown flag: --verbose' which tipped me off that the actual backup is happening with and older version sorry, 0.8.1. I'll repeat all this with 0.8.3 for real and report back.

**Comment by fd0** [comment] 2018-05-21 20:35
Another snapshot is enough. The `--verbose` flag was only added in the most recent version of restic (0.9.0), released today, so you're correct in that.

But for the tests to work you don't need `--verbose`, just make a snapshot with `--exclude-if-present` and run `restic ls latest` and look for the files...

**Comment by fd0** [comment] 2018-05-21 20:36
For the record: My hunch was that maybe the `diff` command was used with snapshot IDs in the wrong order...

**Comment by whereisaaron** [comment] 2018-05-21 20:36
I will keep testing but I think this is a missunderstanding on my part of the `diff` command. It assume it would be aware of the snapshot timeline, but I think not. I this it works blindly just like `diff` of text files would.

When I test this I expect I am fooling myself, that the new backup does not have the files:
```
restic diff <newer> <older>
+ logfiles
```
```
restic diff <older> <new>
- logfiles
```

**Comment by fd0** [comment] 2018-05-21 20:36
Ah, so my hunch was correct. Thanks for the feedback! Can we close this issue now? :)

**Comment by whereisaaron** [comment] 2018-05-21 20:39
Thanks, does the snapshot not have an associated timestamp? Worth printing that out with the diff info?

**Closed** 2018-05-21 20:39 UTC
Labels: bug, feedback needed
