### ISSUE TITLE
S3: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by bluepole** [restic/restic#428] opened 2016-02-10 01:58 UTC
Complete backup n00b here. Previously just used rsync to a local disk.

Installation went very smoothly (Debian linux):

restic 0.1.0 (v0.1.0-348-geccbcb7)
compiled at 2016-02-10 00:48:37 with go1.5.3

As a test I used a 700MB directory, mainly small text files with a lot of duplication and a few big binaries up to 150MB. Backing up to the local disk worked OK, so I tried S3, which was my reason for looking at this.

It died at about 66%. Restarted several times, each time initially showing about 25%. Sorry I didn't capture all the output. But now it fails as soon as I enter the password:

scanned 229 directories, 8768 files in 0:00
panic: runtime error: slice bounds out of range

My connection is around 1Mbit/s up and 30Mbit/s down. Mostly the upload was going about twice this rate, I assume because of many near-identical files.

cheers
Nigel

**Comment by fd0** [comment] 2016-02-10 07:12
Hi, thanks for raising this issue. Could you paste the complete output of restic, especially everything that was printed after `panic()`? That'd help us a lot to figure out what went wrong. Thanks!

**Comment by bluepole** [comment] 2016-02-10 08:17
Here you go...

[resticlog.zip](https://github.com/restic/restic/files/124366/resticlog.zip)

**Comment by fd0** [comment] 2016-02-10 08:54
Thanks for the quick reply. You did find a (rather embarrassing) bug in the code that calculates the maximum line length for the status output. I'll have a detailed look in the evening. In the meantime, if you call `restic --quiet backup foo`, the code is not called and the backup should be created.

**Comment by bluepole** [comment] 2016-02-10 13:55
Thanks for the advice. Yes the --quiet got it restarted. But it died after about 5min with a different problem. Output here...

[resticlog2.zip](https://github.com/restic/restic/files/124827/resticlog2.zip)

I think this was in fact the original problem, and the out-of-range bug only appeared after a couple of restarts.

cheers
Nigel

**Comment by fd0** [comment] 2016-02-10 14:15
Ah, thanks for the clarification. This is a duplicate of #415, the s3 service sometimes disconnects "slow" clients (whatever that means exactly), and the error message is unhelpful. You can subscribe to issue #415, I'll use this issue to track correcting the other panic (with the terminal width).

**Closed** 2016-02-10 17:02 UTC
Labels: bug
