### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by peterbladen** [restic/restic#1659] opened 2018-03-08 09:30 UTC
<!--

## Output of `restic version`
restic 0.8.3
compiled with go1.10 on windows/amd64

## How did you run restic exactly?
restic key passwd

## What backend/server/service did you use to store the repository?
Minio on Centos 7
version 2018-02-09T22:40:05Z

## Expected behavior
Expected password to change on repository 
 
## Actual behavior
Crashed out with an error not given option to change password

C:\>restic key passwd
enter password for repository:
password is correct
read /dev/stdin: The handle is invalid.
ReadFull
main.readPassword
        src/github.com/restic/restic/cmd/restic/global.go:251
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:287
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.changePassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:109
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:180
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
unable to read password
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:291
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.changePassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:109
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:180
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361

## Do you have any idea what may have caused this?
Maybe to do with it been the windows version of the client 

## Do you have an idea how to solve the issue?
Nope

**Comment by peterbladen** [comment] 2018-03-08 09:32
C:\>restic key passwd
enter password for repository:
password is correct
read /dev/stdin: The handle is invalid.
ReadFull
main.readPassword
        src/github.com/restic/restic/cmd/restic/global.go:251
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:287
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.changePassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:109
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:180
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
unable to read password
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:291
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.changePassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:109
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:180
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-895135747/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361

**Comment by dimejo** [comment] 2018-03-08 09:51
Looks like a duplicate of #1618.

**Comment by peterbladen** [comment] 2018-03-08 09:53
You are right it does look that way, sorry quite new to github

**Comment by peterbladen** [comment] 2018-03-08 12:08
A little more information if the windows environment variable is set RESTIC_PASSWORD='old password' and you run 

c:\restic key passwd
password is correct
enter password for new key: 'type in new password'
enter password again:
saved new key as 'etc....'

This does change the repository password so it would seem to be how the stdin works for a key change.

**Comment by fd0** [comment] 2018-03-11 13:38
This looks like a duplicate of #1618, I'm therefore closing this issue. Please subscribe over at #1618 to be notified of any progress.

**Closed by fd0** 2018-03-11 13:38 UTC
