### ISSUE TITLE
Disable encryption

### ISSUE THREAD

**Issue by mikeperalta1** [restic/restic#2687] opened 2020-04-09 00:37 UTC
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.9 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It would be cool to have an option not to use encryption with a repository. I have several backup destinations, but one of them is already inside a LUKS container, so restic's encryption isn't needed.

Perhaps a simple flag when initializing could merely set the encryption password to "nopassword", and subsequent operations could do the same. It could also spit out a warning about being a passwordless repo on each use, just to be sure every user understands the security implications.

What are you trying to do?
--------------------------
I would just like to avoid using encryption for one of my destinations that is already encrypted at the block device level.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I discovered restic several days ago and love it so so much. I'm already using it for a remote backup, and intend to migrate away from my previous home brewed solutions to restic. It's so cool !

**Comment by rawtaz** [comment] 2020-04-09 02:04
Thanks for your input. I'm closing this because it's a duplicate of #1018.

**Closed by rawtaz** 2020-04-09 02:04 UTC
Labels: type: feature request
