### ISSUE TITLE
restic cannot handle Windows paths

### ISSUE THREAD

**Issue by frederich** [restic/restic#339] opened 2015-11-04 08:12 UTC
I've done some tests. It seems restic has problems with Windows path notation. I've done my tests in a native Windows terminal.

I've used restic version:
```
e:\tmp>restic version
restic 0.1.0 (v0.1.0-84-g00e05ae)
compiled at 2015-10-28 22:45:42 with go1.5.1
```

Restic can initialize a backup inside the current folder.
```
e:\home\jf>cd /tmp

e:\tmp>restic -r restic_t1 init
enter password for new backend:
enter password again:
created restic backend e52084cde0 at restic_t1

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

e:\tmp>restic -r restic_t1 snapshots
enter password for repository:
ID        Date                 Source      Directory
----------------------------------------------------------------------

e:\tmp>restic -r restic_t1 check
enter password for repository:
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
```

Restic cannot initialize a backup with a absolute Windows path.
```
e:\tmp>restic -r e:\tmp\restic_t2 init
creating backend at e:\tmp\restic_t2 failed: unable to parse url e:\tmp\restic_t2
```

**Comment by frederich** [comment] 2015-11-04 08:18
I believe restic needs more Windows specific tests.

**Comment by frederich** [comment] 2015-11-04 08:29
debug log:
```
2015/11/04 09:26:43 0.000 [    restic]   1 main.go:24 main []string{"e:\\home\\jf\\bin\\restic.exe", "-r", "e:\\tmp\\restic_t2", "init"}
```

**Comment by frederich** [comment] 2015-11-04 08:37
Note, there is also strange behaviour with the debug log generation. A restic call which use the %PATH% variable doesn't generate a log, but with absolute path it does. I've only one restic binary on my System (%HOME%\bin\restic.exe).

```
e:\tmp>set DEBUG_LOG=restic_t2.log
```
```
e:\tmp>restic -r e:\tmp\restic_t2 init
creating backend at e:\tmp\restic_t2 failed: unable to parse url e:\tmp\restic_t2
```

```
e:\tmp>e:\home\jf\bin\restic.exe -r e:\tmp\restic_t2 init
debug log file restic_t2.log
debug enabled
creating backend at e:\tmp\restic_t2 failed: unable to parse url e:\tmp\restic_t2
```

**Comment by fd0** [comment] 2015-11-04 18:00
This sounds like a bug in the URL parsing code, here: https://github.com/restic/restic/blob/master/cmd/restic/global.go#L136

**Comment by JaCoB1123** [comment] 2015-11-16 15:39
I tested the golang url parsing and reported issue golang/go#13276.
Here are some test-cases: https://play.golang.org/p/QuBFiU_1b1

**Comment by fd0** [comment] 2015-11-16 19:09
I've expected that, since windows paths (and also unix paths) are not URLs at all. It's restic's logic that should decide 1) is this a path (windows or unix), and 2) if not, does it parse as a URL.

**Comment by mappu** [comment] 2016-02-10 20:20
Cannot reproduce. 

```
W:\>mkdir sample
W:\>restic-20160125.exe -r W:\sample init
enter password for new backend:
enter password again:
created restic backend 531c2c4be1 at W:\sample

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

W:\>restic-20160125.exe version
restic 0.1.0
compiled at 2016-01-25 13:57:12 with go1.5.1

W:\>ver
Microsoft Windows [Version 10.0.10240]
```

So i think this is fine (or, maybe i misunderstood, or, maybe it was fixed already). Nested absolute directory works fine too.

**Comment by JaCoB1123** [comment] 2016-02-10 22:00
Yeah, I guess it was fixed in 7d5f8214cf51bac0174b4c421bf7a60852fc4aea.
Minor question though: Why is the scheme for local backups "local" and not "file".
(Sounds stupid, when asking it like this :smile:)

**Comment by fd0** [comment] 2016-02-13 17:39
@frederich would you mind trying again with the latest master? Based on the results we can then fix the bug, or close this issue.

@JaCoB1123 At the time the code was written, the only other backend was sftp. So it was either `local` (in a directory, so `dir` would've been more accurate than `file`) or `remote` (sftp).

**Comment by shmox** [comment] 2016-04-19 08:21
I have an error restoring angularjs app with long paths here is some of errors:

 Mkdir: mkdir D:\TMP\prototype\ng-app\node_modules\grunt-bower-install-simple\node_modules\bower\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\registry-url\node_modules\npmconf\node_modules\once\node_modules\wrappy: **Filename or path too long error**

error for prototype\ng-app\node_modules\grunt-bower-install-simple\node_modules\bower\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\registry-url\node_modules\npmconf\node_modules\once\node_modules: restore subtree: UtimesNano: **The specified file not found**

**Comment by mappu** [comment] 2016-04-19 08:41
Windows OS doesn't support paths longer than about 256 characters. Not a bug in restic.

It's possible that the go standard library file IO functions might be modified to use the NT `\\?\` workaround, but, you will find this same issue with almost all software you use (including Windows Explorer).

Since that's a `node_modules` path, easy fix for you: upgrade to npm v3 and flatten your dependencies.

**Comment by shmox** [comment] 2016-04-19 09:07
Why i don't have these errors with other backup applications ?

**Comment by fd0** [comment] 2016-04-19 09:54
Hi, thanks for bringing it up again.

> Why i don't have these errors with other backup applications?

Because these programs probably have special handling code for long paths on Windows. I don't have a Windows development environment, and the Go stdlib does not yet support long paths, see https://github.com/golang/go/issues/3358

So, if someone wants to step up implementing this for restic, I'm glad to assist.

**Comment by shmox** [comment] 2016-04-19 10:26
Okay thank you

**Comment by shmox** [comment] 2016-04-19 10:52
Maybe this can help i'm not a go developer 

https://github.com/docker/docker/blob/master/pkg/longpath/longpath.go

**Comment by georghendrik** [comment] 2016-06-15 14:38
To use restic on Windows with folders that contain path names longer than 260 characters, call restic with absolute pathnames that are prefixed with `\\?\`

```
C:\> restic backup \\?\C:\src\awesomeproject
[...]
snapshot 11dcc257 saved
```

```
C:\> restic restore 11dc --target \\?\X:\target\
restoring <Snapshot 11dcc257 of [\\?\C:\src\awesomeproject] at 2016-06-15 13:02:15.4147595 +0200 CEST> to \\?\X:\target\
```
Using the `\\?\` notation, Windows supports file paths of up to 32,767 wide characters when used with wide-character api calls (Golang does this). The `\\?\` notation does not support relative file paths, so `\\?\..\awesome` will not work.

For reference, see MSDN about File Naming https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath, and the file name parameter documentation for file api calls (e.g. `GetFileAttributeEx`, the windows equivalent of `stat`: https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946(v=vs.85).aspx)

**Comment by fd0** [comment] 2016-08-09 20:07
This issue is about restic being unable to parse windows paths correctly. This seems to be not the case, at least we couldn't reproduce it and got no more feedback since February. Therefore I'm closing this issue. Feel free to add comments if necessary.

Handling long paths on Windows is now tracked in #567.

**Closed by fd0** 2016-08-09 20:07 UTC
Labels: bug, feedback needed, help wanted, platform:Windows
