### ISSUE TITLE
out of memory during restic prune

### ISSUE THREAD

**Issue by kocour** [restic/restic#3844] opened 2022-08-01 09:12 UTC
Output of `restic version`
--------------------------
`restic 0.13.1 compiled with go1.18 on windows/amd64`

How did you run restic exactly?
-------------------------------
RESTIC_CACHE_DIR=F:\Restic
RESTIC_PASSWORD=C:\Restic\passwd.txt
RESTIC_REPOSITORY=C:\Restic\restic.txt
`restic prune`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wasabi S3 Storage (https://wasabi.com/)

Expected behavior
-----------------
delete unused object from repository

Actual behavior
---------------

```
PS C:\> restic prune
repository 45f0f1a4 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 57 snapshots
[0:46] 100.00%  57 / 57 snapshots...
searching used packs...
runtime: VirtualAlloc of 623902720 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x16394c0?, 0xc247e60000?})
        /usr/local/go/src/runtime/panic.go:992 +0x76
runtime.sysUsed(0xc225200000, 0x25300000)
        /usr/local/go/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x1d75880, 0x12980, 0x0, 0x1)
        /usr/local/go/src/runtime/mheap.go:1279 +0x428
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:469 +0x4e

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc18a84aa30 sp=0xc18a84aa28 pc=0xc32020
runtime.(*mheap).alloc(0x25300000?, 0x12980?, 0xc5?)
        /usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc18a84aa78 sp=0xc18a84aa30 pc=0xbf7065
runtime.(*mcache).allocLarge(0x27750b4d6a8?, 0x25300000, 0x1)
        /usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc18a84aac8 sp=0xc18a84aa78 pc=0xbe7305
runtime.mallocgc(0x25300000, 0x1584140, 0x1)
        /usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc18a84ab40 sp=0xc18a84aac8 pc=0xbdd6e5
runtime.newarray(0xc18a84aba0?, 0xbd7052?)
        /usr/local/go/src/runtime/malloc.go:1281 +0x52 fp=0xc18a84ab68 sp=0xc18a84ab40 pc=0xbddbf2
runtime.makeBucketArray(0xbd6dc5?, 0xa0?, 0xbd36fa?)
        /usr/local/go/src/runtime/map.go:363 +0x18e fp=0xc18a84aba8 sp=0xc18a84ab68 pc=0xbdea2e
runtime.hashGrow(0x1569b60?, 0xc03885f5f0)
        /usr/local/go/src/runtime/map.go:1049 +0x79 fp=0xc18a84abe8 sp=0xc18a84aba8 pc=0xbe0339
runtime.mapassign(0x15d0c80, 0xc03885f5f0, 0xc000472800?)
        /usr/local/go/src/runtime/map.go:658 +0xd4 fp=0xc18a84ac68 sp=0xc18a84abe8 pc=0xbdf2d4
github.com/restic/restic/internal/restic.BlobSet.Insert(...)
        /restic/internal/restic/blob_set.go:26
main.prune({_, {_, _}, _, {_, _}, _, _}, {{0x0, 0x0}, ...}, ...)
        /restic/cmd/restic/cmd_prune.go:222 +0x329 fp=0xc18a84b7e8 sp=0xc18a84ac68 pc=0x1410d09
main.runPruneWithRepo({_, {_, _}, _, {_, _}, _, _}, {{0x0, 0x0}, ...}, ...)
        /restic/cmd/restic/cmd_prune.go:162 +0x205 fp=0xc18a84b9a0 sp=0xc18a84b7e8 pc=0x1410925
main.runPrune({_, {_, _}, _, {_, _}, _, _}, {{0x0, 0x0}, ...})
        /restic/cmd/restic/cmd_prune.go:140 +0x213 fp=0xc18a84bb78 sp=0xc18a84b9a0 pc=0x1410573
main.glob..func18(0x1d4b920?, {0x162fe94?, 0x0?, 0x0?})
        /restic/cmd/restic/cmd_prune.go:35 +0x8a fp=0xc18a84bd08 sp=0xc18a84bb78 pc=0x140fc2a
github.com/spf13/cobra.(*Command).execute(0x1d4b920, {0x1db3930, 0x0, 0x0})
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c fp=0xc18a84bde0 sp=0xc18a84bd08 pc=0xedb7bc
github.com/spf13/cobra.(*Command).ExecuteC(0x1d4d220)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4 fp=0xc18a84be98 sp=0xc18a84bde0 pc=0xedbe34
github.com/spf13/cobra.(*Command).Execute(...)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /restic/cmd/restic/main.go:98 +0x32 fp=0xc18a84bf80 sp=0xc18a84be98 pc=0x1428c92
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x1fe fp=0xc18a84bfe0 sp=0xc18a84bf80 pc=0xc0925e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc18a84bfe8 sp=0xc18a84bfe0 pc=0xc34381

goroutine 6 [chan receive, 2 minutes]:
github.com/restic/restic/internal/restic.init.0.func1.1()
        /restic/internal/restic/lock.go:250 +0x77
created by github.com/restic/restic/internal/restic.init.0.func1
        /restic/internal/restic/lock.go:247 +0x25

goroutine 18 [syscall, 2 minutes]:
os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000162800)
        /home/build/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        /home/build/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 9 [chan receive, 2 minutes]:
main.CleanupHandler(0x0?)
        /restic/cmd/restic/cleanup.go:59 +0x39
created by main.init.0
        /restic/cmd/restic/cleanup.go:21 +0x8b

goroutine 140 [select]:
github.com/restic/restic/internal/repository.(*Index).Each.func1.2(0xc06b0dff58)
        /restic/internal/repository/index.go:267 +0x196
github.com/restic/restic/internal/repository.(*indexMap).foreach(...)
        /restic/internal/repository/indexmap.go:59
github.com/restic/restic/internal/repository.(*Index).Each.func1()
        /restic/internal/repository/index.go:266 +0x1e2
created by github.com/restic/restic/internal/repository.(*Index).Each
        /restic/internal/repository/index.go:258 +0xe5

goroutine 25 [select, 2 minutes]:
main.refreshLocks(0x0?, 0xc0002ac300)
        /restic/cmd/restic/lock.go:77 +0xd1
created by main.lockRepository
        /restic/cmd/restic/lock.go:54 +0x1b1

goroutine 139 [select]:
github.com/restic/restic/internal/repository.(*MasterIndex).Each.func1()
        /restic/internal/repository/master_index.go:269 +0x279
created by github.com/restic/restic/internal/repository.(*MasterIndex).Each
        /restic/internal/repository/master_index.go:260 +0xe5
```

Steps to reproduce the behavior
-------------------------------
just run restic prune after forgeting few snapshots

Do you have any idea what may have caused this?
-----------------------------------------------
maybe repository size 36TB

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is fantastic and I'm using it for few years on many projects.

**Comment by MichaelEischer** [comment] 2022-08-04 20:08
36 TB is quite large for a repository. As a temporary workaround you could try to set the environment variable `GOGC=20` which will make the garbage collector more aggressive. But you should consider splitting the repository if possible. How large is the `index/` folder of the repository? How much memory does the host running restic have?

**Comment by kocour** [comment] 2022-08-05 07:45
Many thanks for your suggestions... I've tried running prune with GOGC=20 and it seems like it helped a little bit, as it takes significantly longer until I got out of memory, but it still crashed.
My `index/` takes 3.7GB and host has 16GB of RAM which should be good enough imho.
However I've increased memory to 24GB and it passed. I'm quite surprised how resource intensive the prune operation is and have doubts if it's effective.

**Comment by agrisvv** [comment] 2022-09-27 12:43
Same here:
one day prune killed with 4 GB memory. Ater add +1Gb. runs fine. seems like wanted 4,5 GB for system.
restic 14.x with local repo. Repo not upgraded.
Stopped at "finding data that is stil in use for" get about 7xx from 890 snapshoots.
Index was 1.1 GB
Data arount 6TB..

**Comment by MichaelEischer** [comment] 2022-10-02 21:02
Prune currently requires about 3 times the index size plus GC overhead = `3 * (1 + GOGC/100) = 6 (by default)`.

#3899 will reduce the first factor from 3 to 2.

**Comment by MichaelEischer** [comment] 2022-10-14 19:37
@LuckyFrost How large is the index folder of the repository? I have a few ideas which could reduce the memory usage by a factor 4 compared to the current state. But everything beyond that will require a complete rework of the repository index.

How many files does the repository contain? 100 million files?

**Comment by LuckyFrost** [comment] 2022-11-24 13:44
Sorry for such a long lack of response.
Cleared the repository completely and made new backups.
Here's what it looks like now:
36,67TB 
105 snapshots
In storage (s3): 1 223 343 files
Repo v2, compressed

Additional backup options:
--pack-size 32

63GB RAM used at step "loading indexes"
Then, at some point at the same stage, it dropped to 40GB

Then on step 
"loading all snapshots...
finding data that is still in use for 25 snapshots"
It gradually grew up to 85GB

At step "repacking packs" the amount of memory consumed increased to 105GB

**Comment by MichaelEischer** [comment] 2022-11-25 23:10
How large is the `index` folder? And how many files does a snapshot contain? Reducing the memory usage below the 40GB used after loading the index requires a complete rearchitecture of the index (in addition to making prune more memory efficient). And that won't happen anytime soon.

**Comment by LuckyFrost** [comment] 2022-11-29 13:22
After the previous cleaning, the repository has not yet gained the previous size (36TB), but at the moment with 26TB in use:
>How large is the index folder?
Total Objects: 1665
   Total Size: 10.9 GiB

>And how many files does a snapshot contain?
I'm not sure if I understood the question correctly, but probably 1 file because all data is from stdin

**Comment by MichaelEischer** [comment] 2022-12-01 21:19
> I'm not sure if I understood the question correctly, but probably 1 file because all data is from stdin

So you're essentially passing nearly 1TB files to restic via stdin? Otherwise I can't get anywhere near the repository size for that number of snapshots.

The number of files is a snapshot is useful to estimate how many file blobs restic has to manage in the index. When assuming very large files, we can assume all blobs have the minimum chunk size, which would yield 52 million blobs for a 26 TB repository. 
At about 225 bytes per entry (index size / blob count) that number would be a good fit for a v1 repository, but we're missing a factor 3-4 for a v2 repository.

**Comment by LuckyFrost** [comment] 2022-12-02 21:03
For greater accuracy, I will say that xtrabackup (mysql backup tool) is used in this case. How much is added is also attached

```
xtrabackup --backup --socket=/var/lib/mysql
/mysql.sock  --stream=xbstream --target-dir ./ | /usr/bin/restic --password-file /xxxx -r s3:http://yyyy:8081/xxx-db-backup-restic backup --cache-dir=/zzz --stdin --pack-size 16"

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repository: 1.365 TiB (266.317 GiB stored)

processed 1 files, 4.633 TiB in 1:29:04
```

**Comment by MichaelEischer** [comment] 2022-12-02 21:47
> processed 1 files, 4.633 TiB in 1:29:04

Oh, that is larger than I've expected. That basically means that the directory metadata, which contains the single file from stdin, is about 700MB large when serialized on disk. In memory its probably quite a bit larger. That is probably also what causes the higher than expected memory usage. As the server likely also has quite a few CPU cores, it might help to set the environment variable `GOMAXPROCS=4` to limit restic to 4 CPU cores when running prune. That should also reduce the memory usage a bit especially during the repack step of prune.

The next restic version will also reduce the memory usage during prune quite a bit (approx 30% less), but won't magically make that high memory usage disappear. Once #2446 is fixed, the memory usage should peak before the repack step. But the main problem still remains, that restic is not optimized for multi-TB files so far. Changing that is more of a long-term project as it will require changes to the repository format.

**Comment by Inverness** [comment] 2023-02-18 21:56
> 36 TB is quite large for a repository. As a temporary workaround you could try to set the environment variable `GOGC=20` which will make the garbage collector more aggressive. But you should consider splitting the repository if possible. How large is the `index/` folder of the repository? How much memory does the host running restic have?

I didn't see any documentation for Restic about what could be considered large, or potentially too large, for a repository size. Is this something you could elaborate on? I'd like to know if I'm going to have potential problems executing a prune or other commands.

I'm not yet a Restic user. I did a test yesterday to back up a smaller number of files to a Backblaze B2 bucket (using the S3 API) and I was happy with the result. I was planning on going all-in with Restic in the next few days.

I did see the documentation on increasing the pack size. I settled on 128 MB for that. However, I don't know how having larger pack files will affect a command like prune if at all.

For context: I currently have a 500 GB OS drive, and three other 4 TB drives. I want all of these backed up to B2 using Restic. From your comment I gather it's ideal to have a separate repo for each drive. However, the main thing that drove me to look into cloud backups and to find Restic was my desire to replace two of those 4 TB drives with 16 TB drives. If I am using 1 repo per drive I want to know if, in the future, I'll have trouble with at least 16 TB of data in a B2 repo.

**Comment by MichaelEischer** [comment] 2023-02-19 13:09
> I didn't see any documentation for Restic about what could be considered large, or potentially too large, for a repository size. Is this something you could elaborate on? I'd like to know if I'm going to have potential problems executing a prune or other commands.

restic is currently probably most suitable for single digit TB size repositories, double digit TB will probably work too, but a few performance limits may start to show up.

The larger a repository is, the more memory restic will require, a very rough estimate would be 200MB per 1 million files and also per 1 TB of data. There are few exceptions like multi-TB files or folder which directly (i.e., not in a subfolder) contain millions of files, which can lead to higher memory usage.

The larger a repository is, the more time prune/check will take. As these currently prevent concurrent access to the repository, this is also something you might want to take into account.

**Comment by Inverness** [comment] 2023-02-19 19:30
> The larger a repository is, the more memory restic will require, a very rough estimate would be 200MB per 1 million files and also per 1 TB of data. There are few exceptions like multi-TB files or folder which directly (i.e., not in a subfolder) contain millions of files, which can lead to higher memory usage.

I don't think I'll have a problem with memory usage them. One of my drives would reach 1 GB of memory by this metric, which is perfectly fine. I would suggest including this in the documentation though. It's important to know.

> The larger a repository is, the more time prune/check will take. As these currently prevent concurrent access to the repository, this is also something you might want to take into account.

When you say larger do you mean in terms of file count or file size? I was intending to do a 1% check per day, which would keep my data retrieval charges to a reasonable level with B2. When it comes to prune, if it's something that can be done a few hours overnight every week or month then it isn't an issue.

Can you think of a good metric for estimating the amount of work needed for a prune? I realize the total time would be subject to network bandwidth and CPU usage, so that would be more difficult to estimate.

Here is my current drive layout if it is helpful at all:
```
C: 302.0 GB used of 464.3 GB, 2,200,000 files
E:   3.2 TB used of  13.0 TB,   119,000 files
F:   3.6 TB used of  13.0 TB,   707,000 files
G:   2.7 TB used of   3.6 TB, 2,600,000 files
```
As I said, I'll have a separate repo for each drive. Two of them were recently upgraded in capacity, and the vast majority of new data on them will be video files for TV and movies, so hundreds of MB to several GB in size.

**Comment by LuckyFrost** [comment] 2023-02-19 19:45
`Here is my current drive layout if it is helpful at all`
Rather not very helpful. If you don't have a lot of changes in the files, then the size of the repository will grow insignificantly with every backup. And repacking will also not be very long.
On the other hand, if you change all the contents every day, then after a certain number of backups your repository will grow to huge sizes and its repacking will be very long.

**Comment by Inverness** [comment] 2023-02-19 20:16
> Rather not very helpful. If you don't have a lot of changes in the files, then the size of the repository will grow insignificantly with every backup. And repacking will also not be very long.
On the other hand, if you change all the contents every day, then after a certain number of backups your repository will grow to huge sizes and its repacking will be very long.

You're right, I do need to keep the number of changes in mind. Fortunately, I don't make that many changes, and I don't plan on keeping any snapshots beyond a month. I don't anticipate any issues here.

Thanks for the information.

**Comment by MichaelEischer** [comment] 2023-06-05 19:40
> Prune currently requires about 3 times the index size plus GC overhead = `3 * (1 + GOGC/100) = 6 (by default)`.
> 
> #3899 will reduce the first factor from 3 to 2.

With https://github.com/restic/restic/pull/4353 and https://github.com/restic/restic/pull/4354 the overall overhead will decrease to about 1.5 times the index size. This yields the following memory usage graph (generated using gcvis), for a repository with 5 million blobs.

![opt-prune-memory-annotated](https://github.com/restic/restic/assets/9106997/f393b816-2fb7-4f28-8860-976ecc797bea)

The initial memory usage peak occurs while loading the index, which requires some additional scratch space. Finding all used blobs requires no additional memory. Afterwards, during the repack phase, the memory usage slowly increases. This is caused by the new index entries added for the rewritten blobs. This additional memory usage is proportional to the amount of rewritten blobs and thus should be unproblematic in general.

What's much more problematic, is the memory usage spike at the end. Before compression each index blob has about 20-30MB, multiply that with the compression overhead and the parallelism of 16 CPU cores and 5 threads (16+5), and the result is a memory usage spike by 1.3 GB in this case. This overhead is largely independent of the repository size.

To reduce that overhead we have three options:
- reduce concurrency, the current level is probably a bit too much.
- reduce the size of an individual index. A smaller index requires less memory to compress and upload.
- Unload the repository index and process the individual index files one after another.

The first two options are rather simple to implement, whereas the third option requires a rewrite of how the index is rebuilt. This would also be useful for https://github.com/restic/restic/issues/3806 .

**Comment by molecular** [comment] 2023-06-06 07:46
> Prune currently requires about 3 times the index size plus GC overhead = `3 * (1 + GOGC/100) = 6 (by default)`.
> 
> #3899 will reduce the first factor from 3 to 2.

looks like version 0.11.0 doesn't have #3899?

```
#> restic prune ...
load all snapshots
find data that is still in use for 155 snapshots
runtime: out of memory: cannot allocate 310378496-byte block (3610640384 in use)
```

size of index folder is 1.07 GB. I don't see a GOGC env variable on my system (raspbian on arm with 4 GB ram, 16 GB swap)

Running prune from a different machine with more memory for now, but hoping for #3899.

**Comment by MichaelEischer** [comment] 2024-05-25 20:48
Fixed via https://github.com/restic/restic/pull/4812 and #4354. See https://github.com/restic/restic/pull/4354#issuecomment-2120475965 for a memory usage graph. The memory usage should now be rather similar to that of the `backup` command.

**Closed by MichaelEischer** 2024-05-25 20:48 UTC
Labels: type: feature enhancement, category: optimization, category: prune
