### ISSUE TITLE
Suppress transient errors

### ISSUE THREAD

**Issue by fkusche** [restic/restic#3613] opened 2021-12-31 09:43 UTC
Output of `restic version`
--------------------------
`restic 0.12.1 compiled with go1.16.6 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
There should be a switch which disables output of error messages, if a retry is being done. Messages like:
- Load(<data/fb08221413>, 0, 0) returned error, **retrying** after 552.330144ms: unexpected EOF
- Save(<data/e206e5a956>) returned error, **retrying** after 552.330144ms: client.PutObject: Your socket connection to the server was not read from or written to within the timeout period, source: read tcp a.b.c.d:443->e.f.g.h:40394: i/o timeout
- Save(<data/b176715650>) returned error, **retrying** after 767.86523ms: client.PutObject: Put https://s3.eu-central-1.wasabisys.com/xxxxxxxxxxx/data/b1/b17671....: write tcp a.b.c.d:42900->e.f.g.h:443: use of closed network connection

As an alternative, restic could also prefix any transient errors with a defined word like `TRANSIENT:`. Just grepping each line for `retrying after` seems a bit unsafe to me.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
My script collects the output of `stderr` and if there is any, I have to manually review it. I would like to be able to ignore errors, that have been healed in the same backup run.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic really makes me sleep better :) Thank you very very much!

As a side note: For me, this feature request has low priority. However, I thought such behavior might be useful for a few other people, too.

**Comment by fkusche** [comment] 2021-12-31 10:08
Update: Sorry, I might have been to quick with this one. I somehow overlooked the `--quiet` switch. Is this what I am looking for? (I need the statistics output, though.) Cannot test right now, will do it in the next few days.

**Comment by fkusche** [comment] 2022-01-05 12:09
It seems that `--quiet` does exactly what I want. So this issue can be closed. Sorry for the fuss. 🙂

However, I recommend to make this the default behavior. Those messages could make it hard to see the real (fatal) errors. I would show them only when using `-vv`. But this is my personal view. Feel free to ignore.

**Comment by fkusche** [comment] 2022-01-06 11:28
I have to add another comment - please bear with me...

In order to track down, why I sometimes have large amounts of added data, I wanted to use `-vv` (in combination with `--json`) to see which files have been changed. Unfortunately, you can't use `-vv` and `--quiet` together.

It would be very useful, if the transient error messages would also be printed as JSON. At the moment, they are plain text in between the other JSON messages. And it would be really great, if those messages would have a special `message_type` like `transient_error`. That way, they can be easily ignored.

**Comment by MichaelEischer** [comment] 2022-01-06 22:24
`--quiet` shouldn't have an effect on the retry warnings.

> At the moment, they are plain text in between the other JSON messages.

I agree, the current JSON support is bit of a mess and especially for the stderr of the backup command. Introducing a `transient_error` message type sound like a good idea.

**Comment by MichaelEischer** [comment] 2024-07-03 19:15
Duplicate of https://github.com/restic/restic/issues/3613 .

**Comment by MichaelEischer** [comment] 2024-07-03 19:15
And now with the correct issue number: https://github.com/restic/restic/issues/2954

**Closed by MichaelEischer** 2024-07-03 19:15 UTC
