### ISSUE TITLE
cannot locate OSXFUSE on Apple M1 chip

### ISSUE THREAD

**Issue by austinginder** [restic/restic#3372] opened 2021-04-23 22:02 UTC
Just got a new Macbook Air with the M1 chip and I'm unable to mount my backup with Restic. I'm running the following command with version `restic 0.12.0 compiled with go1.15.7 on darwin/amd64`.

`restic -r rclone:B2:Backup/timemachine mount ~/Tmp/timemachine`

That results in the following output.

```
repository xxxxxxxxx opened successfully, password is correct
cannot locate OSXFUSE
unable to umount (maybe already umounted or still in use?): unmount /Users/austin/Tmp/timemachine: operation not permitted
```

OSX Fuse v4.1.0 is installed and working as I can successfully mount that same folder using `rclone mount`.

`rclone mount B2:Backup/timemachine ~/Tmp/timemachine`

Same error even with the latest beta of restic.

`./restic_v0.12.0-48-gf7316cea_darwin_amd64 -r rclone:B2:Backup/timemachine mount ~/Tmp/timemachine`

It looks like this same issue happened with Rclone and was patched. See here: https://forum.rclone.org/t/cannot-locate-osxfuse-but-its-installed/20816. Maybe a bug with Restic and Apple silicon? Oh after digging around I discovered https://github.com/restic/restic/issues/3096. That explains the issue in more in depth.

Alternative idea, would there be a way Restic could piggyback and use Rclone's mount capabilities?

**Comment by MichaelEischer** [comment] 2021-05-14 20:06
Closing this as duplicate of #3096 as OSXFUSE 4 also does not seem to work on amd64 machines.

**Comment by brenoxp** [comment] 2022-11-30 10:00
I'm also getting this error, and [macFUSE](https://osxfuse.github.io/) seems to be compatible with M1 macs now.

**Comment by MichaelEischer** [comment] 2022-12-01 19:39
Since https://github.com/restic/restic/pull/4024 is merged, the latest beta builds from https://beta.restic.net/?sort=time&order=desc should work (hopefully).

**Comment by Hongbo-Miao** [comment] 2022-12-28 02:08
Tested on restic 0.14.0, macFUSE 4.4.1, still got same error. 🥲

```sh
➜ restic version
restic 0.14.0 compiled with go1.19.2 on darwin/arm64

➜ restic mount --repo=./hm-backup hm-mount
repository 1e6f4142 opened (repository version 2) successfully, password is correct
cannot locate OSXFUSE
unable to umount (maybe already umounted or still in use?): unmount hm-mount: invalid argument
```

**Comment by niklasravnsborg** [comment] 2022-12-28 08:55
I also have the same issue.

**Comment by MichaelEischer** [comment] 2022-12-28 14:50
> the latest beta builds from https://beta.restic.net/?sort=time&order=desc should work (hopefully).

#4024 is not included in a released version yet!

**Comment by necrevistonnezr** [comment] 2023-01-19 20:44
Still having this issue with restic 0.15.0 on a M1 chip with macfuse 4.4.1 (kernel extension enabled)

**Comment by MichaelEischer** [comment] 2023-01-20 23:05
Hmm, is the mount tool for macfuse located in `/Library/Filesystems/macfuse.fs/Contents/Resources/mount_macfuse`? Please provide the exact error shown by restic.

**Comment by necrevistonnezr** [comment] 2023-01-21 06:32
Error:
`repository 0b907373 opened (repo version 2) successfully, password is correct
cannot locate OSXFUSE
unable to umount (maybe already umounted or still in use?): unmount /Users/kdj/Cloudron/resticmount/: operation not permitted`

Mount Tool location:
`cd /Library/Filesystems/macfuse.fs/Contents/Resources/
dir
total 4096
drwxr-xr-x  7 root  wheel   224B 18 Aug 23:27 ./
drwxr-xr-x  7 root  wheel   224B 18 Aug 23:27 ../
-rw-r--r--  1 root  wheel    21K 18 Aug 23:27 License.rtf
-rw-r--r--  1 root  wheel   1,6M 18 Aug 23:27 Volume.icns
-rwsr-xr-x  1 root  wheel   166K 18 Aug 23:27 load_macfuse*
-rwsr-xr-x  1 root  wheel   184K 18 Aug 23:27 mount_macfuse*
drwxr-xr-x  3 root  wheel    96B 19 Jan 21:33 uninstall_macfuse.app/`

**Comment by MichaelEischer** [comment] 2023-01-21 17:44
Phew :sweat_smile: , thanks for the feedback.

**Closed by MichaelEischer** 2023-01-21 17:44 UTC
Labels: category: mount, platform: darwin

**Comment by maciekish** [comment] 2023-02-23 08:55
Hi, sorry for the necro but I'm still having this issue on macOS Ventura, M1.

 % restic version
restic 0.15.1 compiled with go1.19.5 on darwin/arm64
 % which fuse
/usr/local/bin/fuse
 % fuse --version
Fuse version 1.9.0
Copyright (C) 2017 Fusetools
