### ISSUE TITLE
[REQUEST] --assume-path flag to overwrite tracked path

### ISSUE THREAD

**Issue by rumpelsepp** [restic/restic#658] opened 2016-11-04 07:59 UTC
Hi, I like to use restic with temporary btrfs snapshots that happen before `restic backup`. That way there are no changin files during the backup. The problem is that restic seems to expects matching backup paths in order to deduplicate them properly. Maybe a flag to overwrite the tracked path could help here. I am thinking of sth. like this:

```sh
#!/bin/sh
export RESTIC_REPOSITORY="/run/media/hans/09831209381029381/restic"
export RESTIC_PASSWORD="$(pass securely_stored_password)"
ACTUALSRC="/home"
SNAPSHOT="/home/.snapshots/home-42342"

btrfs subvolume snapshot -r "$ACTUALSRC" "$SNAPSHOT"
restic backup --assume-path="$ACTUALSRC" "$SNAPSHOT"
btrfs subvolume delete "$SNAPSHOT"
```

Restic should read the files from `$SNAPSHOT`, but track them as they were from `$ACTUALSRC` (proposed `--assume-path=` flag). Does this sound reasonable?

**Comment by pvgoran** [comment] 2016-11-04 08:04
There is already a request for this: #555.

**Comment by rumpelsepp** [comment] 2016-11-04 08:05
Damn, I missed that one... Thanks for the link.

**Comment by fd0** [comment] 2016-11-05 10:40
Thanks for reporting this, I'm going to close this issue as a duplicate of #555.

Please be aware that deduplication still works and restic doesn't save duplicate data. The only difference is that all data is read and split again, because restic doesn't find a previous path to look at.

**Closed by fd0** 2016-11-05 10:40 UTC
