### ISSUE TITLE
Is it possible not to generate a snapshot if the file has not changed?

### ISSUE THREAD

**Issue by yangjinhe** [restic/restic#4370] opened 2023-06-16 07:16 UTC
Output of `restic version`
--------------------------
restic 0.15.2 compiled with go1.20.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Is it possible not to generate a snapshot if the file has not changed?

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I automatically execute scheduled tasks. If the file has not changed, a snapshot will also be generated, which makes it impossible for me to tell which snapshot is useful, and many unnecessary empty snapshots are kept.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic is very nice，thank you all

**Comment by MichaelEischer** [comment] 2023-06-16 19:13
Duplicate of #662. Please upvote that issue if you're interested in the feature.

**Closed by MichaelEischer** 2023-06-16 19:13 UTC
