### ISSUE TITLE
Progress indicator should include network stats

### ISSUE THREAD

**Issue by CGamesPlay** [restic/restic#4172] opened 2023-01-23 13:08 UTC
Output of `restic version`
--------------------------

`restic 0.15.0 compiled with go1.19.5 on darwin/arm64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I am making a backup using an unreliable internet connection. The connection is relatively slow and occasionally goes down and requires restarting the backup. When the backup reaches 100%, restic appears to hang. Looking at the Activity Monitor, I can see that restic has uploaded 400 MiB *since it stopped listing new files*, but it hasn't output anything about what it's doing. The latest output looks like this:

```
$ restic backup --exclude-file restic-ignore --exclude-caches -vvv ~
# thousands of lines omitted
modified  /Users/rpatterson/Public/Drop Box/, saved in 0.000s (0 B added, 0 B stored, 374 B metadata)
modified  /Users/rpatterson/Public/, saved in 0.000s (0 B added, 0 B stored, 1.194 KiB metadata)
modified  /Users/rpatterson/Projects/, saved in 227.650s (0 B added, 0 B stored, 1.704 MiB metadata)
modified  /Users/rpatterson/, saved in 304.609s (0 B added, 0 B stored, 15.681 KiB metadata)
modified  /Users/, saved in 304.609s (0 B added, 0 B stored, 455 B metadata)
[12:50] 414987 files 7.279 GiB, total 414987 files 7.279 GiB, 0 errors
```

I am using the S3 backend. I *assume* restic is uploading modified chunks to S3, but there's no output confirming this. I am using `-vvv` to get the maximum amount of output from restic, however it doesn't show anything.

If this is a reasonable guess, then **the progress indicator in restic should be updated to include network stats** (e.g. upload rate in KiB/sec, packs uploaded/pending, etc). This way I could be sure that restic is making actual forward progress and hasn't hung on a network timeout.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

To restate, this would allow the user to understand that restic is making progress and to know when the backup process will finish.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is great. I've been using it for ~2 years now, including maintaining [git-remote-restic](https://github.com/CGamesPlay/git-remote-restic). I'm pretty sure that this isn't a bug report because I'm confident that restic is actually doing what it needs to be, but I just wish that it reassured me a little more.

**Comment by MichaelEischer** [comment] 2023-01-23 21:30
Duplicate of #1581.

**Closed by MichaelEischer** 2023-01-23 21:30 UTC

**Comment by MichaelEischer** [comment] 2023-01-23 21:32
Right now the progress bar only shows how much data it has processed, but not how much is left too upload. Usually that shouldn't be much more than a few (dozen) MB such that it usually doesn't take long for the backup to complete after reaching 100%.

**Comment by CGamesPlay** [comment] 2023-01-24 07:02
That's a shame. In the run shown in this task, restic uploaded 500 MiB before exiting. I created a second snapshot immediately after, and restic uploaded 400 MiB after the progress bar reached "100%". The hypothesis that "shouldn't be more than a few (dozen) MB" seems incorrect.

**Comment by MichaelEischer** [comment] 2023-01-28 20:48
I guess you're seeing https://github.com/restic/restic/issues/3643 here. (More specifically the metadata for the `$user/Library/Containers` folder, as apple stores the icons for those directories as extended attributes)

**Comment by CGamesPlay** [comment] 2023-01-29 04:11
Noted. I'll follow both of these issues. Thanks for your dedication to restic!
