### ISSUE TITLE
Integrity check failed: Data seems to be missing.

### ISSUE THREAD

**Issue by neclepsio** [restic/restic#4667] opened 2024-01-29 12:10 UTC
Output of `restic version`
--------------------------

```restic 0.16.3 compiled with go1.21.6 on windows/amd64```

What backend/service did you use to store the repository?
---------------------------------------------------------

Local folder.

Problem description / Steps to reproduce
----------------------------------------

```
# restic prune

enter password for repository:
repository 8ac455d3 opened (version 2, compression level auto)
loading indexes...
[0:03] 100.00%  89 / 89 index files loaded
loading all snapshots...
finding data that is still in use for 139 snapshots
[0:30] 100.00%  139 / 139 snapshots
searching used packs...
{<data/4ea0e0f4> <data/05ab9c75> <data/7efc8633> <data/78a978a5> <data/0944cce7> <data/e56e62b6> <data/40dfa726> <data/412d98c2> <data/9c41d0dd> <data/735a35e3> (128 more)} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete
```

Expected behavior
-----------------

Pruning occours.

Actual behavior
---------------

An error is shown, asking to be reported.

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe several BSOD during the last backup, due to an antivirus I cannot disable.

`restick check --read-data`, which is in progress, shows several packs not references in index and several files not found in index.

**Comment by neclepsio** [comment] 2024-01-30 08:06
One single pack was corrupted.

I tried `rebuild-index` and `repair index` but I still get the same error with `prune`.
Is there a way I can repair the backup?

**Comment by MichaelEischer** [comment] 2024-01-31 19:21
> Then, I used `forget` for the snapshots that where repaired.

That is the reason why https://restic.readthedocs.io/en/latest/077_troubleshooting.html uses `restic repair snapshots --forget`.

> Now `prune` works.

Please run `restic check --read-data` to make sure there are no further hidden defects.

> `restick check --read-data`, which is in progress, shows several packs not references in index and several files not found in index.

Do you still have the output from `check`? The error reported by prune looks like a pack file disappeared for some reason. The mentioned BSODs could be the cause of that, in which case there's nothing restic can do to prevent the repository corruption.

**Comment by neclepsio** [comment] 2024-01-31 19:44
There where some trees missing, but no pack was missing. There was a corrupted pack. Maybe I can get the full output tomorrow.

After the pruning, the subsequent check found another corrupted pack. No BSOD happened in this case.

**Comment by MichaelEischer** [comment] 2024-01-31 20:47
> There was a corrupted pack. Maybe I can get the full output tomorrow.
> 
> After the pruning, the subsequent check found another corrupted pack.

Corrupted pack files often hint at hardware problems. It might be a good idea to run a CPU / RAM stress test.

**Comment by neclepsio** [comment] 2024-02-01 08:20
> Do you still have the output from check? The error reported by prune looks like a pack file disappeared for some reason. The mentioned BSODs could be the cause of that, in which case there's nothing restic can do to prevent the repository corruption.

How can I share it privately?

**Comment by MichaelEischer** [comment] 2024-03-09 17:39
Closing as there has been no feedback. Feel free to reopen it though.

**Closed by MichaelEischer** 2024-03-09 17:39 UTC
Labels: state: need feedback
