### ISSUE TITLE
Feature Request: Storage Backend "Amazon Cloud Drive"

### ISSUE THREAD

**Issue by MirkoDziadzka** [restic/restic#508] opened 2016-05-08 16:31 UTC
I would be great of restic would support "[Amazon Cloud Drive](https://www.amazon.com/clouddrive/home)" as a storage backend.

It seems that you can get "unlimited" file storage for around 60 USD/year - which makes it a great target for encrypted backup.

An API is available: https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api

**Comment by fd0** [comment] 2016-05-08 17:59
Thanks for the suggestion.

**Comment by fd0** [comment] 2016-05-09 14:21
Ah, this issue is a duplicate of #212, closing.

**Closed by fd0** 2016-05-09 14:21 UTC
Labels: backend, feature
