### ISSUE TITLE
restic list locks creates a lock and lists it

### ISSUE THREAD

**Issue by lloeki** [restic/restic#1106] opened 2017-07-17 07:44 UTC
## Output of `restic version`

```
restic version
restic 0.7.0
compiled with go1.8.3 on darwin/amd64
```

## How did you start restic exactly? (Include the complete command line)

`restic list locks`

## What backend/server/service did you use?

Doesn't matter.

## Expected behavior

Same as `restic list locks --no-lock` in terms of output.

## Actual behavior

Creates an extra lock. Not sure how it is useful but it gets listed back.

## Steps to reproduce the behavior

`restic list locks` on a repo.

## Do you have any idea what may have caused this?

I guess `restic list` creates the lock irrespective of the requested object type.

**Comment by fd0** [comment] 2017-07-18 19:52
Hm, I think restic creates a lock when it uses the repo, unless the user explicitly requests not to use a lock. This informs other instances of restic that there is someone using the repo, so destructive operations (`prune` and `forget`) are not allowed until the current instance has finished.

So I'm inclined to close this as it works as intended.

What's your use case?

**Comment by lloeki** [comment] 2017-07-19 08:17
None really precise except some light shell scripting. It's just that semantically, creating a read lock to list locks (which by definition are not impacted by destructive operations such as `prune` and `forget`) looks weird from a high-level point of view (but makes sense from a low-level one).

Whatever, the call is yours, just wanted to bring in some feedback.

**Comment by fd0** [comment] 2017-07-19 08:18
Ah, now I understand where you're coming from. Interesting! I'll think about it.

**Comment by mholt** [comment] 2018-08-08 01:35
I just encountered this too, but `--no-lock` is sufficient for me. In fact, I think I prefer the explicitness of how it is now.

**Comment by rawtaz** [comment] 2020-02-16 02:38
I'm closing this for now, because it doesn't seem like a very problematic issue, more like a corner case of how the locking currently works. Also, if we make the `lock` lock not shown, we'll never see it - perhaps better to be explicit like @mholt says. Please use the `--no-lock` argument, i.e. `restic list locks --no-lock`.

**Closed by rawtaz** 2020-02-16 02:38 UTC
Labels: feature request

**Comment by MichaelEischer** [comment] 2022-02-19 10:39
@quinncomendant What is the reason you're even calling `restic list locks`? That command is only intended for low-level troubleshooting.

**Comment by quinncomendant** [comment] 2022-02-19 22:44
Hi @MichaelEischer, 

I created a shell script that supervises backups for several servers. Due to the distributed architecture, any one of the servers can be responsible for repository maintenance such as `prune` or `forget`, and as such the repository may be locked by another restic process. I know that restic naturally checks for locks before attempting to run a restic command that modifies a repo, but then restic fails with a non-zero exit code. When any command fails with a non-zero exit code, my script sends me an alert. Because I don't want to receive alerts, and I don't want my logs to fill up with `repository is already locked exclusively by PID 12345` messages, I'm using `restic list locks` to check if a lock exists *before* proceeding with any restic command that wants a lock. Then I can skip that restic command silently, with no alerts, and no errors in the logs. (If a repo gets stuck with a stale lock, I will get an alert when the prune command fails to complete after a few days.)

Here's a simplified example of how I'm using `restic list locks` in a bash script:

```bash
function _restic_prune() {
    if (($(_last_prune_time) > prune_expiration)); then
        _info "Skipping prune (last ran $(_last_prune_time) hours ago)";
        return 1;
    fi

    if [[ -n "$(restic -q --no-lock list locks | xargs)" ]]; then
        _info "Skipping prune because repository is locked";
        return 1;
    fi

    _info "Starting prune";
    restic prune 2>&1 | tee -a "${logfile}" || _error "Failed to prune ($(_elapsed) elapsed)"

    _update_prune_time;
}
```

**Comment by MichaelEischer** [comment] 2022-03-06 20:45
@quinncomendant Strictly speaking it's a race condition to first check for locks and then run the prune command in a separate step, but it's probably good enough to prevent most script failures. The cleanest solution would probably be #956.

I've noticed another problem with `restic list lock`: when the repository is locked exclusively by e.g. prune or check, then listing the lock files will fail. So it make zero sense to call the command without `--no-lock`. I've opened PR #3665 to make this the default behavior.

**Comment by quinncomendant** [comment] 2022-03-06 23:19
> The cleanest solution would probably be #956.

Thanks for suggesting this. Indeed, it would meet my goal perfectly if restic returned more useful exit codes. I added [a comment to support that idea](https://github.com/restic/restic/issues/956#issuecomment-1060059170). 

> I've noticed another problem with `restic list lock`: when the repository is locked exclusively by e.g. prune or check, then listing the lock files will fail. So it make zero sense to call the command without `--no-lock`. 

Yes, I noticed this too. I assume it is like that because restic shared the lock code with all commands, and since `restic list lock` creates a lock, it fails just like every other command that creates locks. It not only makes zero sense to run without `--no-lock`, it has no reason to create a lock in the first place (which is the topic of this issue ;).
