### ISSUE TITLE
Device of files are not stored anymore; therefore hardlinks are not handled correctly

### ISSUE THREAD

**Issue by jgfrm** [restic/restic#901] opened 2017-04-03 20:11 UTC
`func (node *Node) fillExtra(path string, fi os.FileInfo) error`

should be

`func (node *Node) fillExtra(path string, fi os.FileInfo) error
...
	switch node.Type {
	case "file":
		node.Size = uint64(stat.size())
		node.Links = uint64(stat.nlink())
		node.Device = uint64(stat.dev())
...
`

**Comment by fd0** [comment] 2017-04-04 14:41
Thanks for reporting, this is a duplicate of #893, so I'm going to close this issue.

Would you mind trying to submit a PR? :)

**Closed by fd0** 2017-04-04 14:41 UTC
