### ISSUE TITLE
installation of  Restic server by sitting behind the proxy

### ISSUE THREAD

**Issue by yashaswiniuma** [restic/restic#3307] opened 2021-02-26 11:44 UTC
Output of `restic version`
--------------------------

it is about installation of restic server 

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am trying to install the restic-server . 
my system is behind proxy-server  so installation process is unable to resolve the links to github.com 
Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
![image](https://user-images.githubusercontent.com/33446718/109296147-e2597980-7855-11eb-843d-a2601537cb66.png)

**Comment by rawtaz** [comment] 2021-02-26 12:26
I'm sorry, but this is not caused by restic, rest-server or similar. This seems like a local network problem on your end, and there's not much we can do about that. You simply have to fix your proxy and network so that you can properly resolve and access github.com.

On a related note, you can (once you are able to access github.com) download a rest-server binary directly from https://github.com/restic/rest-server/releases , in case you don't want to build it yourself. But I guess you do, and there's nothing wrong with that :)

I'll be closing this issue for now. For future reference, please use the [restic forum](https://forum.restic.net/) when you want to ask about a usage problem. The issues here on GitHub are intended for bug reports or feature requests.

**Closed by rawtaz** 2021-02-26 12:26 UTC
