### ISSUE TITLE
Restic 16.3 fails on Windows 7

### ISSUE THREAD

**Issue by NovacomExperts** [restic/restic#4637] opened 2024-01-18 03:49 UTC
Output of `restic version`
--------------------------
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
	/usr/local/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46d335
rax     0x0
rbx     0x1b5e300
rcx     0x1bb4100
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1b855b8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1b5da60
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

What backend/service did you use to store the repository?
---------------------------------------------------------
N/A - just running restic.exe alone after restic.exe selft-update gives the above error

Problem description / Steps to reproduce
----------------------------------------

Take a windows 7 (64bits) host.
Run restic 16.2 = fine
restic.exe self-update = fine to 16.3
Run restic.exe version (or restic.exe or any restic commands)
- error above -

Expected behavior
-----------------

Restic 16.3 should work as expected 

Actual behavior
---------------

restic.exe version gives the error above, consistent on my only 2 Windows 7 hosts / more than 50 mulptiple Windows version.

Do you have any idea what may have caused this?
-----------------------------------------------

Might be related to go1.21.6 ? 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is always positive to me, I also can just roll back to 16.2 on Windows 7 hosts for the moment.

**Comment by bjoe2k4** [comment] 2024-01-18 07:29
See https://github.com/restic/restic/issues/4636

**Comment by rawtaz** [comment] 2024-01-18 12:01
Yeah, this is a duplicate of #4636. You can build restic yourself using an older version of Go to make 0.16.3 work on Windows 7.

**Closed by rawtaz** 2024-01-18 12:01 UTC

**Comment by NovacomExperts** [comment] 2024-01-18 17:44
Sorry about the duplicate. All good !
