### ISSUE TITLE
No possibility to delete all snapshots for certain host/tag/path

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2761] opened 2020-05-28 08:22 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64

How did you run restic exactly?
-------------------------------

    restic forget --path /my/path

I also tried with `--keep-last 0` without any effect.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
MinIO (S3)

Expected behavior
-----------------
Remove all snapshots with path `/my/path`.

Actual behavior
---------------

    no policy was specified, no snapshots will be removed

Steps to reproduce the behavior
-------------------------------

1. Create a few snapshots
2. Run command as described above

Do you have any idea what may have caused this?
-----------------------------------------------
Security measure.

Do you have an idea how to solve the issue?
-------------------------------------------
Option 1: Do allow any filter (host/path/tag) _or_ (keep-x).
Option 2: Add `--force` parameter
Option 3: Approve setting of `--keep-x 0` as policy.

**Comment by rawtaz** [comment] 2020-05-28 21:28
Thanks for your input, but as you already hinted (when you wrote "Security measure") this is intentional and described [here in the docs](https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy):

***For safety reasons, restic refuses to act on an “empty” policy. For example, if one were to specify --keep-last 0 to forget all snapshots in the repository, restic will respond that no snapshots will be removed. To delete all snapshots, use --keep-last 1 and then finally remove the last snapshot ID manually (by passing the ID to forget).***

Closing this issue because it works as intended ;)

**Closed by rawtaz** 2020-05-28 21:28 UTC
