### ISSUE TITLE
stdin | restic ... init crash

### ISSUE THREAD

**Issue by denji** [restic/restic#2235] opened 2019-04-08 02:32 UTC
```
$ restic version
restic 0.9.4 compiled with go1.10.4 on linux/amd64

$ echo 123 | restic -r ./test123 init
read password from stdin
read password from stdin
EOF
ReadFull
main.readPassword
	github.com/restic/restic/cmd/restic/global.go:281
...
```

```
$ echo -n 123 | restic -r ./test123 init
read password from stdin
read password from stdin
EOF
ReadFull
main.readPassword
	github.com/restic/restic/cmd/restic/global.go:281
main.ReadPassword
	github.com/restic/restic/cmd/restic/global.go:317
main.ReadPasswordTwice
	github.com/restic/restic/cmd/restic/global.go:339
main.runInit
	github.com/restic/restic/cmd/restic/cmd_init.go:36
main.glob..func11
	github.com/restic/restic/cmd/restic/cmd_init.go:18
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra/command.go:800
main.main
	github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/lib/go-1.10/src/runtime/proc.go:198
runtime.goexit
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361
unable to read password
main.ReadPassword
	github.com/restic/restic/cmd/restic/global.go:322
main.ReadPasswordTwice
	github.com/restic/restic/cmd/restic/global.go:339
main.runInit
	github.com/restic/restic/cmd/restic/cmd_init.go:36
main.glob..func11
	github.com/restic/restic/cmd/restic/cmd_init.go:18
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra/command.go:800
main.main
	github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/lib/go-1.10/src/runtime/proc.go:198
runtime.goexit
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361

```

**Comment by fd0** [comment] 2019-04-13 11:55
Thanks for the report, it is a duplicate of #2203, so please subscribe over there. Thanks!

**Closed by fd0** 2019-04-13 11:55 UTC
Labels: bug, duplicate
