### ISSUE TITLE
passing `~` to `restic --target` is interpreted verbatim

### ISSUE THREAD

**Issue by jesrui** [restic/restic#801] opened 2017-02-11 22:03 UTC
## Output of `restic version`
```
restic 0.4.0 (v0.4.0-21-g073edd9)
compiled with go1.7.5 on linux/amd64
```

## Expected behavior

```
restic restore f8fd3e73 --target=~/foo
```
Should restore in the `foo` directory in `$HOME`.

## Actual behavior

Files are restored in  `$HOME/~/foo`.

**Comment by fd0** [comment] 2017-02-11 22:11
Thanks for raising this issue. Usually, your shell takes care of expanding the `~` character. This works if you call restic like this: `restic restore f8fd3e73 --target ~/foo`.

I'm going to close this issue since it is not a bug in restic. Please feel free to leave a comment if you disagree.

**Closed by fd0** 2017-02-11 22:11 UTC
