### ISSUE TITLE
How to take backup from one object storage to other object storage?

### ISSUE THREAD

**Issue by yadu-boss** [restic/restic#2649] opened 2020-03-16 04:07 UTC
Output of `restic version`
--------------------------

Describe the issue
------------------
Hi Team

Is it possible to take backup form one object storage (ex: ecs) to second object storage (ex: cloudian)? 
If it possible please share me the steps to take backup and restore.

Thanks in advance.
yadu

**Comment by dimejo** [comment] 2020-03-16 08:09
Please use [the forum](https://forum.restic.net/) for questions about restic's usage.

**Comment by greatroar** [comment] 2020-03-16 08:22
Duplicate of #323.

**Comment by yadu-boss** [comment] 2020-03-16 08:51
What is the solution if restic fails

**Comment by yadu-boss** [comment] 2020-03-16 08:55
Hi 

> Duplicate of #323.

HI greatroar

I dint get any related document, could you please help me to get document

**Comment by rawtaz** [comment] 2020-03-31 03:23
@yadu-boss Please understand that this issue tracker is for bug reports and feature requests, *not* usage questions like the one you asked above. For questions on how to use restic and what you can do with restic, please [use the restic forum](https://forum.restic.net/).

That said:
- In [this pull request](https://github.com/restic/restic/pull/2606) you will find a new `copy` command, by which you can copy one or more snapshots from one repository to another, if that's what you want to do.
- If you want to clone the entire repository from one place to another, you can use e.g. [rclone](https://rclone.org/) to sync the files from one place to the other.

I will close this issue now, as it's not a bug report nor a feature request. In the future, please use the forum. Thanks!

**Closed by rawtaz** 2020-03-31 03:23 UTC
