### ISSUE TITLE
Edit on GitHub links are broken in documentation

### ISSUE THREAD

**Issue by pwaring** [restic/restic#1175] opened 2017-08-24 18:57 UTC
I'm not sure if this repository is the best place for this report but the Edit on GitHub links on the documentation pages appear to be broken.

For example, visiting the installation page:

https://restic.readthedocs.io/en/stable/installation.html

The Edit on GitHub link takes you to:

https://github.com/restic/restic/blob/402b6f5f8d0171d7061cbeab67725fce794fc376/doc/installation.rst

Which is a 404. I have checked most of the other pages under `stable/` and they have the same problem. The links on `latest` on the other hand work as I'd expect.

**Comment by fd0** [comment] 2017-08-26 10:21
Hm, it works for the `latest` and `v0.7.1` versions on ReadTheDocs. Strange. I don't have any idea how to resolve this.

**Comment by pwaring** [comment] 2017-08-26 17:09
I've had a look at some other projects on Read the Docs and they don't appear to have this problem. However, RTD does seem to rely on a project having a `master` branch (which `latest/` points to) and a `stable` branch (which `stable/` points to). restic has `master` but not `stable`, so I think RTD is trying to link to a branch which doesn't exist.

If I've understood it correctly, the solution is either to use a `stable` branch or to disable the generation of docs based on that branch (I don't know if that's an option as I've never used RTD for a project).

**Comment by fd0** [comment] 2017-08-26 19:27
Hm, I read that documentation differently: "stable will be automatically kept up to date to point at your highest version."

So the `stable` selection should point to the latest release tag, and that seems to work. Only the "edit on github" links are wrong. Hm.

**Comment by rawtaz** [comment] 2017-09-05 22:18
Many others are having the same problem over at https://github.com/rtfd/readthedocs.org/issues/1820.

I added a proposed solution in that issue, we'll see if it's something that could solve the problem.

**Comment by martinseener** [comment] 2018-03-21 14:23
Btw. go here: `https://restic.readthedocs.io/en/stable/` and then see the link which reads: `https://github.com/restic/restic/blob/93455f0fc0225992c48527d1f252a5e925c49878/doc/index.rst`

**Comment by rawtaz** [comment] 2018-05-30 22:41
According to the RTD people this has now finally been fixed (see: https://github.com/rtfd/readthedocs.org/pull/4052).

We might need to rebuild the RTD project though, can someone trigger that?

**Comment by fd0** [comment] 2018-05-31 19:29
It works for me right now, does anybody still see an issue with it, or can we close this issue? :)

**Comment by rawtaz** [comment] 2018-05-31 19:34
It's still not working properly, in a sense.

Before, when clicking the "Edit on GitHub" link on e.g. https://restic.readthedocs.io/en/stable/040_backup.html you arrived at a 404 over at GitHub. You no longer do that, you arrive at a page showing the file, so that's better.

But on that page you arrive at on GitHub, you cannot click the edit button for the file, because you are not on a brach but on a specific commit, in this example it's currently https://github.com/restic/restic/blob/e40191942da7e83e45f995cf9f2d5ae54f97289f/doc/040_backup.rst you arrive at.

So while we no longer end up on a 404, we still can't easily edit the file as intended.

This only happens on the Stable version over at RTD, not on Latest or any of the tags.

I suggest we keep this issue open, I'm going to reply to the RTD folks with this info.

**Comment by fd0** [comment] 2018-06-07 18:19
Thanks for investigating! I've triggered a rebuild of the `stable` and `latest` versions, let's see how that goes.

**Comment by rawtaz** [comment] 2020-10-06 00:04
Closing this, seems to work right now and regardless there's nothing we can do here from the restic project.

**Closed by rawtaz** 2020-10-06 00:04 UTC
Labels: category: documentation, help: wanted
