### ISSUE TITLE
Add support for CACHEDIR.TAG

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1159] opened 2017-08-14 07:20 UTC
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/amd64

So far I've been using obnam, and despite its slowness, was rather happy with it.
Unfortunately, obnam is being discontinued [1], so I'm looking for alternatives.
restic seems to tick a lot of the boxes I look for in a backup program. Thanks for that excellent tool!

One thing I'm missing in restic is support for the CACHEDIR.TAG [2].
When using obnam, I added a few of those marker files to say ~/.cache/ to exclude those from the backup. For a seamless transition, it would be great if restic would support CACHEDIR.TAG files as well. This way I wouldn't need a plethora of --exclude parameters

[1] https://blog.liw.fi/posts/2017/08/13/retiring_obnam/
[2] https://www.gnu.org/software/tar/manual/html_node/exclude.html

**Comment by mbiebl** [comment] 2017-08-14 07:21
Related obnam documentation:
http://code.liw.fi/obnam/manual/manual.html#choosing-what-to-backup-and-what-not-to-backup

**Comment by fd0** [comment] 2017-08-14 08:52
Thanks for raising this as an issue, we already have an issue for this so I'm going to close it as a duplicate of #317. I think we can add this feature near term to cater for users switching from obnam :)

**Closed by fd0** 2017-08-14 08:52 UTC
Labels: duplicate, feature request
