### ISSUE TITLE
number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by dmaj** [restic/restic#2273] opened 2019-05-12 08:46 UTC
### Output of `restic version`
restic 0.9.5 (v0.9.5-0-g303210aa) compiled with go1.11.2 on linux/amd64

#### Env variables:
RESTIC_PASSWORD, RESTIC_REPOSITORY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
#### Script
#!/bin/bash
set -euxo pipefail
restic backup --verbose -H gitea-prod /git_repos
su postgres -c "pg_dumpall | gzip | restic backup --verbose -H gitea-prod --stdin-filename postgres.gz --stdin"

### What backend/server/service did you use to store the repository?
S3 from Netapp

### Expected behavior
No Error using restic prune

### Actual behavior

/ # restic --verbose  init
created restic repository 24382aa086 at s3:s3u2082.test.net:8082/gitea-prod

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
/ #
/ # ./b.sh
+ restic backup --verbose -H gitea-prod /git_repos
open repository
repository 24382aa0 opened successfully, password is correct
created new cache in /root/.cache/restic
lock repository
load index files
start scan on [/git_repos]
start backup on [/git_repos]
scan finished in 25.612s: 6241 files, 224.864 MiB

Files:        6241 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:   5137 new
Tree Blobs:      1 new
Added to the repo: 223.792 MiB

processed 6241 files, 224.864 MiB in 0:25
snapshot 36c0a099 saved
+ su postgres -c 'pg_dumpall |gzip | restic backup --verbose -H gitea-prod --stdin-filename postgres.gz --stdin'
open repository
repository 24382aa0 opened successfully, password is correct
created new cache in /var/lib/postgresql/.cache/restic
lock repository
load index files
using parent snapshot 36c0a099
read data from stdin
start scan on [postgres.gz]
start backup on [postgres.gz]
scan finished in 0.421s: 1 files, 0 B

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:      1 new
Tree Blobs:      1 new
Added to the repo: 120.462 KiB

processed 1 files, 120.160 KiB in 0:01
snapshot 28d57e52 saved
/ #
/ # ./b.sh
+ restic backup --verbose -H gitea-prod /git_repos
open repository
repository 24382aa0 opened successfully, password is correct
lock repository
load index files
using parent snapshot 36c0a099
start scan on [/git_repos]
start backup on [/git_repos]
scan finished in 3.220s: 6241 files, 224.864 MiB

Files:           0 new,     0 changed,  6241 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:      0 new
Tree Blobs:      0 new
Added to the repo: 0 B
  
processed 6241 files, 224.864 MiB in 0:07
snapshot fca1964a saved
+ su postgres -c 'pg_dumpall |gzip | restic backup --verbose -H gitea-prod --stdin-filename postgres.gz --stdin'
open repository
repository 24382aa0 opened successfully, password is correct
lock repository
load index files
using parent snapshot fca1964a
read data from stdin
start scan on [postgres.gz]
start backup on [postgres.gz]
scan finished in 0.339s: 1 files, 0 B
  
Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:      1 new
Tree Blobs:      1 new

Added to the repo: 120.459 KiB
processed 1 files, 120.160 KiB in 0:01
snapshot b40516b2 saved
/ #
/ # restic snapshots
repository 24382aa0 opened successfully, password is correct
ID        Time                 Host        Tags        Paths
.-------------------------------------------------------------------
36c0a099  2019-05-12 09:32:44  gitea-prod              /git_repos
28d57e52  2019-05-12 09:33:11  gitea-prod              /postgres.gz
fca1964a  2019-05-12 09:33:17  gitea-prod              /git_repos
b40516b2  2019-05-12 09:33:26  gitea-prod              /postgres.gz
.-------------------------------------------------------------------
4 snapshots
/ #
/ # restic forget --verbose 36c0a099 28d57e52
repository 24382aa0 opened successfully, password is correct
removed snapshot 36c0a099
removed snapshot 28d57e52
/ #
/ # restic prune --verbose
repository 24382aa0 opened successfully, password is correct
counting files in repo
building new index for repo
[0:00]   0 / 0 packs
repository contains 0 packs (0 blobs) with 0 B
processed 0 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 2 snapshots
[0:00] 100.00%  2 / 2 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
/ #

### Steps to reproduce the behavior

1. Init repository
2. Create Backup (Directory, Postgress)
3. Immediately afterwards, another backup is created. Nothing has changed in the directory. 
4. The first two backups are deleted (directory, postgres).
5. Afterwards a "prune" is executed, which however runs on an error message.

The error is reproducible and always occurs during this procedure. 

### Update 1:
The problem also occurs when taking the backup of the postgres from the script.

```
#!/bin/bash
set -euxo pipefail
restic backup --verbose -H gitea-prod /git_repos
```
### Update 2:
I have performed the operation on a normal filesystem as a backup destination. This worked without any problems.  Is it possible that "prune" does not work with "s3"? Or is there a problem with s3 from NetApp?

### Update 3:
It ist working with minio. 
It looks to me at the moment as if there is a problem with the S3 implementation of NetApp.

### Did restic help you or made you happy in any way?
The concept of Restic impresses me. It's a really useful tool. If I wasn't convinced, I wouldn't be writing the bug report.

**Comment by dmaj** [comment] 2019-05-12 09:22
The problem also occurs when taking the backup of the postgres from the script.

```
#!/bin/bash
set -euxo pipefail
restic backup --verbose -H gitea-prod /git_repos
```

**Comment by cdhowie** [comment] 2019-05-18 19:48
This could be a transient issue with Netapp. I perform hourly backups of one of my servers to AWS S3 and haven't had any problems.

**Comment by dimejo** [comment] 2019-05-19 11:57
Please see #2045.

**Comment by dmaj** [comment] 2019-06-02 16:48
I am in contact with NetApp and am trying to solve the problem. If I have more information, I will share it here.

**Comment by nlseven** [comment] 2019-07-10 23:39
I am having the same issue as @dmaj using NetApp's S3 StorageGrid, though can recreate the issue simply by doing the following:

```
rm -rf ~/.cache/restic
restic init
created restic repository 1da3567986 at s3:netapp.obs.addr:8082/restic
...
echo 'hello' > ~/file

restic backup ~/file
repository 1da35679 opened successfully, password is correct
created new cache in /root/.cache/restic

Files:           1 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 853 B

processed 1 files, 6 B in 0:00
snapshot 8dfe169c saved

restic backup ~/file
repository 1da35679 opened successfully, password is correct

Files:           0 new,     0 changed,     1 unmodified
Dirs:            0 new,     0 changed,     1 unmodified
Added to the repo: 0 B  

processed 1 files, 6 B in 0:00
snapshot f5a38da6 saved

restic check
using temporary cache in /tmp/restic-check-cache-165603135
repository 1da35679 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-165603135
create exclusive lock for repository
load indexes
check all packs
pack 2250a2b8: does not exist
pack 2623240f: does not exist
check snapshots, trees and blobs
Fatal: repository contains errors
```

However, by *down*grading to 0.9.0 this issue disappears:

```
./restic_0.9.0_linux_amd64 init
created restic repository 0e46ed8671 at s3:netapp.obs.addr:8082/restic
...

./restic_0.9.0_linux_amd64 backup file
repository 0e46ed86 opened successfully, password is correct

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      374 B

processed 1 files, 6 B in 0:01
snapshot 93f0d6e9 saved

./restic_0.9.0_linux_amd64 backup file
repository 0e46ed86 opened successfully, password is correct

Files:           0 new,     0 changed,     1 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      0 B  

processed 1 files, 6 B in 0:00
snapshot 09cd9823 saved

./restic_0.9.0_linux_amd64 check
using temporary cache in /tmp/restic-check-cache-237050882
repository 0e46ed86 opened successfully, password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found

./restic_0.9.0_linux_amd64 forget --prune 93f0d6e9
repository 0e46ed86 opened successfully, password is correct
removed snapshot 93f0d6e9
1 snapshots have been removed, running prune
counting files in repo
building new index for repo
[0:01] 100.00%  2 / 2 packs
repository contains 2 packs (2 blobs) with 584B
processed 2 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 1 snapshots
[0:00] 100.00%  1 / 1 snapshots
found 2 of 2 data blobs still in use, removing 0 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 0 packs, this frees 0B
counting files in repo
[0:01] 100.00%  2 / 2 packs
finding old index files
saved new indexes as [c0c72fdb]
remove 1 old index files
done

./restic_0.9.0_linux_amd64 rebuild-index
repository 0e46ed86 opened successfully, password is correct
counting files in repo
[0:01] 100.00%  2 / 2 packs
finding old index files
saved new indexes as [16dd028b]
remove 1 old index files

./restic_0.9.0_linux_amd64 check
using temporary cache in /tmp/restic-check-cache-790743125
repository 0e46ed86 opened successfully, password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
```

**Comment by tipruzs** [comment] 2019-08-27 07:31
I am having the same issue with NetApp S3 StorageGrid. In addition to @nlseven i tried version 0.9.4 of restic and it works for me.

@nlseven can you confirm that 0.9.4 is working for you too?

**Comment by fd0** [comment] 2019-08-27 11:16
Uh, interesting! Thanks for spending time to investigate this issue!

The reproduction cases are very helpful. Since I don't have a device to test this, can you please:
 * do a `git bisect` between a working version (0.9.0? or 0.9.4?) and the latest master to find the commit that introduced the faulty change
 *

**Comment by tipruzs** [comment] 2019-09-04 10:05
@fd0 following your instructions `git bisect` came to the following result:

```
b9f0f031b6dbfecc6805a6a68fdd08e4834eeabf is the first bad commit
commit b9f0f031b6dbfecc6805a6a68fdd08e4834eeabf
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Sun Jan 27 21:07:57 2019 +0100

    Update dependencies
    
    Closes #2129
```

Attached is a debug log running v0.9.5 and failling `check` command. If you need any further details, please let me know.

[restic-debug.log](https://github.com/restic/restic/files/3573965/restic-debug.log)

**Comment by basilmusa** [comment] 2019-12-18 20:06
I'm experiencing the same issue with NetApp S3 Object Storage. 
@fd0  @tipruzs Any updates on what is causing this error?

**Comment by basilmusa** [comment] 2019-12-18 20:25
I can see the following when doing:

    git show b9f0f031b6dbfecc6805a6a68fdd08e4834eeabf

```
-       github.com/minio/minio-go v6.0.7+incompatible
...
+       github.com/minio/minio-go v6.0.14+incompatible
```

Could this minio-go version change be related?

**Comment by basilmusa** [comment] 2019-12-31 15:16
@fd0 @tipruzs I was able to pinpoint the exact commit and source file that is causing the problem for Restic to no longer work with NetApp's S3 Obect Storage implementation.

The issue took place in the `api-list.go` file of the `minio/minio-go` project in the commit `a42b0e14697ffdcb4ef223384c1cac12738f574f`.
The exact URL is:
https://github.com/minio/minio-go/commit/a42b0e14697ffdcb4ef223384c1cac12738f574f#diff-e038a2d477fad04d158a4afba2faf85e

I tried reverting this change with the latest Restic code and everything was working as expected.
I have posted an Issue in the minio/minio-go project on GitHub here. Hopefully they will provide a fix soon: https://github.com/minio/minio-go/issues/1207

**Comment by harshavardhana** [comment] 2019-12-31 18:15
This is not a bug minio-go but an implementation issue in NetApp object storage, they should fix the server behavior.

**Comment by Gorra007** [comment] 2020-03-17 17:14
> 
> 
> This is not a bug in minio-go but an implementation issue in NetApp object storage, they should fix the server behavior.
> 
> The PR explains it properly on why it's needed.

Any link to the PR ?

**Comment by MichaelEischer** [comment] 2021-01-09 13:59
Is this issue still relevant. If yes, please try the current `master` branch (builds are available at https://beta.restic.net/?sort=time&order=desc) and test whether #3083 works as a workaround. It adds the `-o s3.list-objects-v1=true` option to avoid using the ListObjectsV2 aip

**Comment by MichaelEischer** [comment] 2021-01-30 16:49
Closing this as there's been no feedback.

**Closed by MichaelEischer** 2021-01-30 16:49 UTC
Labels: backend: s3, state: need feedback, type: bug
