### ISSUE TITLE
Absolute path displayed when relative path is given to backup cmd

### ISSUE THREAD

**Issue by rolfw** [restic/restic#2399] opened 2019-09-15 18:05 UTC
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on darwin/amd64`

How did you run restic exactly?
-------------------------------
```
export RESTIC_REPOSITORY=s3:http://localhost:9000/resticbucket
export AWS_ACCESS_KEY_ID=<id>
export AWS_SECRET_ACCESS_KEY=<key>
cd /Volumes/SomeImage
restic backup --time '2018-07-06 11:06:00' --tag="TimeMachine" . 
```

The output shows the relative paths for the current file processed, as expected. E.g. `/Users/...` instead of `/Volumes/SomeImage/Users/...`

```
restic snapshots
```

The output shows absolute paths in the Paths column. E.g. `/Volumes/SomeImage`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio

Expected behavior
-----------------
I'm trying to migrate old TimeMachine backups and images of my startup volume as if they were made with restic in the first place, so directories such as `/Volumes/SomeImage/Users` should become `/Users`.

The release notes of v0.9.0 suggest that relative path is stored when a relative path is given, and that an absolute path is stored when an absolute path is given. So in this case I'd expect to see the path `/` when running `restic snapshots`.

Actual behavior
---------------
I'm seeing the absolute path, e.g. `/Volumes/SomeImage`

Steps to reproduce the behavior
-------------------------------
Make a backup using the commands described above, then list the snapshots and observe the path printed for the latest backup.

Do you have any idea what may have caused this?
-----------------------------------------------
Nothing comes to mind. I'm just starting out with Restic so I'm not that familiar with it yet.

Do you have an idea how to solve the issue?
-------------------------------------------
Not that I can think of.

Did restic help you or made you happy in any way?
-------------------------------------------------
Absolutely, what I've seen so far I like a lot; It's fast, clean and it has a reliable feel to it. I also like the flexibility it gives me in command-line options, backends, etc. And that it deduplicates of course :)

**Comment by jbsilva** [comment] 2020-08-03 01:38
The same happens on Windows.
restic 0.9.5 compiled with go1.12.4 on windows/amd64

**Comment by MichaelEischer** [comment] 2022-05-14 22:13
Closing as duplicate of #2092

**Closed by MichaelEischer** 2022-05-14 22:13 UTC
