### ISSUE TITLE
`--files-from-raw` Adds Every File to Path Output in `restic snapshots`

### ISSUE THREAD

**Issue by ossie-git** [restic/restic#4780] opened 2024-04-27 09:43 UTC
Output of `restic version`
--------------------------

```
restic 0.16.4 compiled with go1.21.6 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When using `--files-from-raw`, the **Path** column is populated with **every single file** matched by the `--files-from-raw`. I don't think that this is intended as it makes using `restic snapshot` very difficult to use (imagine if you match tens of thousands of files).

For example, if I did the following:

```
restic backup --files-from-raw <( fd -0H . '/home/vagrant/tmux-3.4'  )
```

and then ran:

```
$ restic snapshots
```

it shows:

```
ID        Time                 Host                  Tags        Paths
------------------------------------------------------------------------------------------------------------------------
98712268  2024-04-27 08:34:11  fedora39                          /home/vagrant/tmux-3.4/.deps
                                                                 /home/vagrant/tmux-3.4/.deps/alerts.Po
                                                                 /home/vagrant/tmux-3.4/.deps/arguments.Po
                                                                 /home/vagrant/tmux-3.4/.deps/attributes.Po
                                                                 /home/vagrant/tmux-3.4/.deps/cfg.Po
                                                                 /home/vagrant/tmux-3.4/.deps/client.Po
...
```

for hundreds of lines for a single snapshot. The reason I use `--files-from-raw` is due to the limited **patterns** support in restic. The above is just an example

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Because of the above, running `restic snapshots` is a pain and quickly seeing your snapshots, etc isn't practical. Ideally, it would show only the top folders backed up

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Thanks a lot for developing Restic

**Comment by MichaelEischer** [comment] 2024-05-05 17:49
Duplicate of https://github.com/restic/restic/issues/2714

**Closed by MichaelEischer** 2024-05-05 17:49 UTC
