### ISSUE TITLE
support for acl's

### ISSUE THREAD

**Issue by jgfrm** [restic/restic#732] opened 2017-01-20 21:47 UTC
For full linux backups, support of acl (such as set with the setfacl command) would be convenient

**Comment by pvgoran** [comment] 2017-01-21 01:15
Duplicate of #25.

**Comment by fd0** [comment] 2017-01-21 17:40
Thanks for raising this issue, it is indeed a duplicate so I'm closing this issue. You can subscribe to #25 if you'd like to be notified of the process.

**Closed** 2017-01-21 17:40 UTC
