### ISSUE TITLE
Intermittently fails to remove Backblaze locks

### ISSUE THREAD

**Issue by CendioOssman** [restic/restic#2562] opened 2020-01-28 15:18 UTC
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.11.5 on linux/amd64

How did you run restic exactly?
-------------------------------

```
export RESTIC_PASSWORD="xxx"

export B2_ACCOUNT_ID="xxx"
export B2_ACCOUNT_KEY="xxx"

/usr/bin/restic --quiet --repo "b2:<bucket>:/" backup "<path>"
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze

Expected behavior
-----------------

Silence. Complete backup. No locks left around.

Actual behavior
---------------

First time this happen we got:

```
Remove(<lock/e2da98e949>) returned error, retrying after 372.362036ms: Delete: b2_authorize_account: 401: 
Remove(<lock/e2da98e949>) returned error, retrying after 943.465489ms: Delete: b2_download_file_by_name: 404: bucket xxx does not have file: locks/e2da98e9499d5675c4e2dcb02712fea406b19913933fc849c23e6d0f59797b49
Remove(<lock/e2da98e949>) returned error, retrying after 1.47376298s: Delete: b2_download_file_by_name: 404: bucket xxx does not have file: locks/e2da98e9499d5675c4e2dcb02712fea406b19913933fc849c23e6d0f59797b49
Remove(<lock/e2da98e949>) returned error, retrying after 1.711066009s: Delete: b2_download_file_by_name: 404: bucket xxx does not have file: locks/e2da98e9499d5675c4e2dcb02712fea406b19913933fc849c23e6d0f59797b49
Remove(<lock/e2da98e949>) returned error, retrying after 1.735833725s: Delete: b2_download_file_by_name: 404: bucket xxx does not have file: locks/e2da98e9499d5675c4e2dcb02712fea406b19913933fc849c23e6d0f59797b49
...
```

After which the lock was wedged and we had to manually unlock to make things work again.

Second time just happened, with this error:

```
Remove(<lock/3a93d0ba6c>) returned error, retrying after 722.19857ms: Delete: b2_delete_file_version: 401: 
Fatal: unable to save snapshot: Close: b2_finish_large_file: 400: No active upload for: 4_z517d80021a42b51268e10718_f206d9e98194c45df_d20200128_m142022_c000_v0001065_t0056
```

And there is no snapshot present after this run.

Steps to reproduce the behavior
-------------------------------

No idea what causes this. It was ten days between the current incidents.

Do you have any idea what may have caused this?
-----------------------------------------------

Nope.

Do you have an idea how to solve the issue?
-------------------------------------------

Nope.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not today as the backup failed. But otherwise. :)

**Comment by dimejo** [comment] 2020-01-28 17:13
Looks like a duplicate of #2452.

**Comment by CendioOssman** [comment] 2020-01-29 11:39
Sounds very similar, yes. It doesn't have the entry with the 401 return code though, but that could just be a cropped log.

**Comment by adworacz** [comment] 2021-02-04 15:55
I'm having this exact same issue with Backblaze.

Several of my more recent commands have encountered this issue, including a `forget --prune` run, and now a `rebuild-index` run (which I started running because the `forget --prune` failed due to "data blobs seem to be missing" errors).

What's interesting is that my current `rebuild-index` run has run fine for ~23 hours straight, and then I just checked it this morning and it started exhibiting this issue not but 5 minutes ago.

Here's a sample from my `rebuild-index` log, for what it's worth:
```
repository 06abe926 opened successfully, password is correct
counting files in repo
(Note - the below line appeared ~23 hours into the rebuild)
unable to refresh lock: Delete: b2_delete_file_version: 400: File not present: restic_backup/locks/7655086fe5ebac5e976ce2472c0bf94ca4cc9f2418056e9b01c634
e2f30aeef4 4_z0081896d9c2fa50a6ece0011_f104ce895f7239539_d20210204_m141546_c002_v0001156_t0016
Remove(<lock/7655086fe5>) returned error, retrying after 312.530506ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 796.619196ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 856.537092ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 994.420097ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 2.375796743s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 4.770748265s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 8.446477188s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 5.366570765s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 11.500799285s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 20.381602022s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
unable to refresh lock: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 510.028524ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 457.292085ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 844.006665ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 1.283462078s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 2.313277051s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 1.956028013s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 3.037156291s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 12.417264109s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 14.687552345s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 18.800390089s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
unable to refresh lock: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 486.858982ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 497.259626ms: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 1.675941071s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 1.534339377s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 2.925787307s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 3.550985275s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 5.250898259s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 10.212472917s: Delete: b2_download_file_by_name: 404: File with such name does not exist.
Remove(<lock/7655086fe5>) returned error, retrying after 16.425148888s: Delete: b2_download_file_by_name: 404: File with such name does not exist
```

For giggles, I manually logged in to my Backblaze B2 account and confirmed that the lock file doesn't appear to be there.

**What scares me is that there's no reason for this lock file to just disappear. I haven't lost power, nor run multiple conflicting commands, nothing.** 

Is Backblaze just erroring out in their API for no good reason?

**Comment by MichaelEischer** [comment] 2021-02-04 21:12
> For giggles, I manually logged in to my Backblaze B2 account and confirmed that the lock file doesn't appear to be there.
> 
> **What scares me is that there's no reason for this lock file to just disappear. I haven't lost power, nor run multiple conflicting commands, nothing.**
> 
> Is Backblaze just erroring out in their API for no good reason?

There should be lots of other lock files in the lock directory by now? Make sure to run `restic unlock` once the index rebuild has finished (why are you rebuilding the index anyways? It shouldn't be necessary at all with a somewhat recent restic version).

The important part to notice in the error message is that it changes from `b2_delete_file_version: 400: File not present` to `b2_download_file_by_name: 404: File with such name does not exist.`. My guess is that this has to do with request retries where a delete request has failed in restic's view but did in fact succeed at B2, e.g. due to a transient network problem. restic doesn't handle that case particularly well and starts to create lots of lock files and error messages. Besides that it shouldn't cause much of a problem, as restic for refreshing the lock creates a new lock file before it removes the old one (that last step is failing here).

I'm not completely sure yet how to best handle that case, but I intend to fix that as part of #2715.

**Comment by adworacz** [comment] 2021-02-04 22:50
> There should be lots of other lock files in the lock directory by now?
Yup, there were around 5 other lock files when I manually locked at the lock directory in Backblaze after I saw that log.


> Make sure to run `restic unlock` once the index rebuild has finished (why are you rebuilding the index anyways? It shouldn't be necessary at all with a somewhat recent restic version).

Yup, I run restic unlock every time I see these errors now (which is on every run, unfortunately).

And I'm running an index rebuild because when I previously ran a `forget --prune`, I got the above-mentioned "data blobs seem to be missing" error telling me that the prune was completely aborted. After seeing that error (and the ones on this issue), I went ahead and ran a full `check` and `rebuild-index` just to be absolutely sure that my repository in Backblaze didn't get corrupted somehow.
 
> The important part to notice in the error message is that it changes from `b2_delete_file_version: 400: File not present` to `b2_download_file_by_name: 404: File with such name does not exist.`. My guess is that this has to do with request retries where a delete request has failed in restic's view but did in fact succeed at B2, e.g. due to a transient network problem. 

Good that's what I was hoping the issue was, it didn't appear to be a large problem.

> Besides that it shouldn't cause much of a problem, as restic for refreshing the lock creates a new lock file before it removes the old one (that last step is failing here).

Good to know as well.

> I'm not completely sure yet how to best handle that case, but I intend to fix that as part of #2715.

Looking forward to it. I've subscribed to that issue to follow any associated pull requests.

**Comment by adworacz** [comment] 2021-02-06 01:13
Looks like my prune failed again - I'll open an official issue instead of polluting this one.

**Closed** 2022-03-21 10:10 UTC

**Comment by vsuontam** [comment] 2022-06-10 05:35
I also get these errors a lot on my prune when using Backblaze. 

Using restic 0.13.1 compiled with go1.18 on linux/amd64.
