### ISSUE TITLE
index grows too big

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#1572] opened 2018-01-22 09:50 UTC
## Output of `restic version`

    $ restic version
    restic 0.8.1
    compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?

    # restic -r sftp:root@server:/mnt/array/backup/laptop.restic --one-file-system --exclude=/var/cache --exclude=/var/tmp --exclude=/tmp '--exclude=/home/user/tmp --exclude=/home/user/.cache backup /etc /mnt /root /srv /var /usr /home /boot /boot/efi

## What backend/server/service did you use to store the repository?

SFTP

## Expected behavior

There is around 120Go to backup, so I would expect the index cache to stay far less than 1Go.

## Actual behavior

    # du -sh /root/.cache/restic
    12G	/root/.cache/restic

## Steps to reproduce the behavior

Run the previous command once a day.

## Do you have any idea what may have caused this?

Maybe too many things are kept in the cache?

## Did restic help you or made you happy in any way?

Sure! I use it everyday to backup my data, and packaged it for Debian for people to use it :-).

**Comment by legrostdg** [comment] 2018-01-22 09:53
Seems like almost all the space is taken by `/root/.cache/restic/data/`. `/root/.cache/restic/index/ is 566M, so, of an acceptable size.

**Comment by fd0** [comment] 2018-01-25 20:14
Hey, I don't think this is an issue. It looks like in your case, the metadata (which is cached in `~/.cache/restic`) is almost a GiB in size. That's a common order of magnitude, 1-5% metadata size. It'll get better when we add compression.

I'm closing this issue, please feel free to add further comments. Thanks!

**Closed by fd0** 2018-01-25 20:14 UTC

**Comment by legrostdg** [comment] 2018-01-25 20:49
1% would be OK, but 10% is not!

**Comment by fd0** [comment] 2018-01-25 21:45
So, the real issue is the metadata size, not the index size. I'll correct the title. This is a duplicate of #210 then.

Since restic started, we've changed the behavior a bit, so for example the `atime` isn't saved by default to reduce metadata size. This was only active in the last few revisions of restic, so for earlier snapshots the `atime` was still saved.

The real fix is probably #21, or switching to something else than JSON.
