### ISSUE TITLE
Restic 0.15.0 problems with b2 repositories "b2_download_file_by_name: 404: : b2.b2err"

### ISSUE THREAD

**Issue by wrnod** [restic/restic#4144] opened 2023-01-13 07:34 UTC
With any of the restic commands I use, I get "**b2_download_file_by_name: 404: : b2.b2err**" with my b2 repo since Version Upgrade to 0.15.0. Down below is an example of "restic backup", but the same error code occurs in restic snaphots, restic diff or stdout of restic mount.

Output of `restic version`
--------------------------
restic 0.15.0 compiled with go1.19.5 on darwin/amd64

How did you run restic exactly?
-------------------------------

#######IN
export B2_ACCOUNT_ID=*
export B2_ACCOUNT_KEY=*
export RESTIC_PASSWORD_FILE=*

/usr/local/bin/restic -r b2:buucket:repo --verbose backup ...

#######OUT

open repository
repository e1da* opened (version 2, compression level auto)
lock repository
using parent snapshot e141*
load index files
start scan on [*]
start backup on [*]
scan finished in 5.036s: *** files, *** GiB

Files:           0 new,     3 changed, *** unmodified
Dirs:            0 new,     5 changed,  *** unmodified
Data Blobs:      2 new
Tree Blobs:      4 new
Added to the repository: 755.655 KiB (182.574 KiB stored)

processed *** files, *** GiB in 0:15
snapshot 6aa*** saved
**b2_download_file_by_name: 404: : b2.b2err**

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
Same w/o Errors.

Actual behavior
---------------
see above.

Steps to reproduce the behavior
-------------------------------

interact with b2 repo.

Do you have any idea what may have caused this?
-----------------------------------------------

Versions < 0.15.0 never showed this error.

Do you have an idea how to solve the issue?
-------------------------------------------

No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Tonight the daily backup failed for the first time in a very long time with fatal error. I am not sure if there is a correlation to the 404 Error, but I would assume so. On a second try, it ran through (out of above)

...
Fatal: failed to refresh lock in time
b2_download_file_by_name: 404: : b2.b2err
scan finished in 3894.359s: 567 files, 217.591 MiB
Fatal: unable to save snapshot: context canceled

**Comment by tbm** [comment] 2023-01-13 10:04
I just wanted to report the same issue.

0.15.0:

```
rest prune
loading indexes...
loading all snapshots...
finding data that is still in use for 2 snapshots
[0:00] 100.00%  2 / 2 snapshots
searching used packs...
collecting packs for deletion and repacking

to repack:             0 blobs / 0 B
this removes:          0 blobs / 0 B
to delete:             0 blobs / 83.316 MiB
total prune:           0 blobs / 83.316 MiB
remaining:         19436 blobs / 4.591 GiB
unused size after prune: 0 B (0.00% of remaining size)

deleting unreferenced packs
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
[0:02] 100.00%  5 / 5 files deleted
done
b2_download_file_by_name: 404: : b2.b2err
```

0.14.0

```
restic prune
loading indexes...
loading all snapshots...
finding data that is still in use for 2 snapshots
[0:00] 100.00%  2 / 2 snapshots
searching used packs...
collecting packs for deletion and repacking
[0:01] 100.00%  282 / 282 packs processed

to repack:             0 blobs / 0 B
this removes:          0 blobs / 0 B
to delete:             0 blobs / 0 B
total prune:           0 blobs / 0 B
remaining:         19436 blobs / 4.591 GiB
unused size after prune: 0 B (0.00% of remaining size)

done
```

**Comment by greatroar** [comment] 2023-01-13 10:38
I just tested whether this might be a side effect of #3958 and I don't think it is. @MichaelEischer, could this be #3900?

(Also, is it time to fork or vendor kurin/blazer? It's a pretty small library once you remove all the experimental features.)

**Comment by prestonvanloon** [comment] 2023-01-13 17:22
This happening for me too. I can reproduce with something as simple as listing snapshots. 
A local git bisect indicates that fc506f8538ddbd2519b46f65144eba71523a53f5 is the first commit where this issue manifests.

**Comment by prestonvanloon** [comment] 2023-01-13 18:00
I believe this is a cosmetic error only. See this misplaced fmt.Printf https://github.com/kurin/blazer/blob/master/b2/b2.go#L623

**Comment by prestonvanloon** [comment] 2023-01-13 18:01
See https://github.com/kurin/blazer/pull/84 and https://github.com/restic/restic/issues/3750 (duplicate of this issue)

**Comment by MichaelEischer** [comment] 2023-01-13 23:03
> `b2_download_file_by_name: 404: : b2.b2err`

That error is indeed just a cosmetic problem. It should be fixed by https://github.com/restic/restic/pull/4146 .

> Fatal: failed to refresh lock in time
> b2_download_file_by_name: 404: : b2.b2err
> scan finished in 3894.359s: 567 files, 217.591 MiB
> Fatal: unable to save snapshot: context canceled

This one is more interesting. Apparently, for some reason restic failed to refresh its lock in time. For a backup containing a few hundred files and MBs of data, the scan also shouldn't take more than a few seconds to complete. Did the host maybe enter standby during the backup?

**Comment by wrnod** [comment] 2023-01-14 07:19
> > `b2_download_file_by_name: 404: : b2.b2err`
> 
> That error is indeed just a cosmetic problem. It should be fixed by #4146 .
> 
> > Fatal: failed to refresh lock in time
> > b2_download_file_by_name: 404: : b2.b2err
> > scan finished in 3894.359s: 567 files, 217.591 MiB
> > Fatal: unable to save snapshot: context canceled
> 
> This one is more interesting. Apparently, for some reason restic failed to refresh its lock in time. For a backup containing a few hundred files and MBs of data, the scan also shouldn't take more than a few seconds to complete. Did the host maybe enter standby during the backup?

The same fatal error occured today. Backup in these cases is triggered daily via launchd/launchctl on MacOS Ventura 13.1. I suspect the OS blocking the new binary (was self-updated) from file access. Will have to look into it further..

**Comment by MichaelEischer** [comment] 2023-01-14 11:00
> The same fatal error occured today. Backup in these cases is triggered daily via launchd/launchctl on MacOS Ventura 13.1. I suspect the OS blocking the new binary (was self-updated) from file access. Will have to look into it further..

Can you open a new issue for the lock refresh problem, once you have further information? That is a different problem than the b2 related warning message.

**Closed** 2023-01-14 14:23 UTC

**Comment by linucksrox** [comment] 2023-01-16 18:40
Meanwhile until the next update, I added this to my cron jobs to filter out the noise in my logs:
*/30 */6 * * * /bin/bash resticbackupscript.sh | grep -Ev 'b2_download_file_by_name: 404: : b2.b2err' >> /restic_backup_log.txt
