### ISSUE TITLE
Trailing whitespaces in file names cause errors

### ISSUE THREAD

**Issue by mem89de** [restic/restic#5152] opened 2024-11-25 15:38 UTC
Output of `restic version`
--------------------------
restic 0.17.3 compiled with go1.23.3 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local

Problem description / Steps to reproduce
----------------------------------------
When tinkering with some unrelated scripts I produced some files whose file names ended on white space. When backing up my computer I received some errors. See the following bash script to reproduce this behaviour (tested on win11):

```bash
#!/bin/sh

set -x

restic version

mkdir data
echo "Some Data" > "data/someFile "
cat data/someFile
cat "data/someFile "

FLAGS="--verbose --insecure-no-password --repo repository"

restic init $FLAGS
restic $FLAGS backup ./data
restic $FLAGS snapshots
restic $FLAGS ls latest

rm --recursive --force data repository
```
On my system I get the following output:

```
+ restic version
restic 0.17.3 compiled with go1.23.3 on windows/amd64
+ mkdir data
+ echo 'Some Data'
+ cat data/someFile
cat: data/someFile: No such file or directory
+ cat 'data/someFile '
Some Data
+ FLAGS='--verbose --insecure-no-password --repo repository'
+ restic init --verbose --insecure-no-password --repo repository
created restic repository 98ef0df1e1 at repository

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
+ restic --verbose --insecure-no-password --repo repository backup ./data
open repository
no parent snapshot found, will read all files
load index files
start scan on [./data]
start backup on [./data]
scan: CreateFile \\?\C:\Users\Marc\Desktop\restic-bug\data\someFile: The system cannot find the file specified.
scan finished in 0.002s: 0 files, 0 B
error: CreateFile \\?\C:\Users\Marc\Desktop\restic-bug\data\someFile: The system cannot find the file specified.

Files:           0 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Data Blobs:      0 new
Tree Blobs:      2 new
Added to the repository: 692 B (592 B stored)

processed 0 files, 0 B in 0:00
snapshot b947ffe5 saved
Warning: at least one source file could not be read
+ restic --verbose --insecure-no-password --repo repository snapshots
ID        Time                 Host             Tags        Paths                                  Size
-------------------------------------------------------------------------------------------------------
b947ffe5  2024-11-25 16:34:42  DESKTOP-20R8BPL              C:\Users\Marc\Desktop\restic-bug\data  0 B
-------------------------------------------------------------------------------------------------------
1 snapshots
+ restic --verbose --insecure-no-password --repo repository ls latest
snapshot b947ffe5 of [C:\Users\Marc\Desktop\restic-bug\data] at 2024-11-25 16:34:42.5754196 +0100 CET by DESKTOP-20R8BPL\Marc@DESKTOP-20R8BPL filtered by []:
/data
+ rm --recursive --force data repository
```

Expected behavior
-----------------

The file is backed up without an error.

Actual behavior
---------------

```
scan: CreateFile \\?\C:\Users\Marc\Desktop\restic-bug\data\someFile: The system cannot find the file specified.
scan finished in 0.005s: 0 files, 0 B
error: CreateFile \\?\C:\Users\Marc\Desktop\restic-bug\data\someFile: The system cannot find the file specified.
```

Do you have any idea what may have caused this?
-----------------------------------------------

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not today, but the day will come without doubt :D

**Comment by MichaelEischer** [comment] 2024-11-27 22:12
Duplicate of https://github.com/restic/restic/issues/2745 . According to the Windows docs filenames shouldn't end with spaces or dots. Unfortunately, the Windows function used to calculate absolute file paths also tries to fixes these issues and hence ends up corrupting the file name. See the other issue for more details.

**Closed by MichaelEischer** 2024-11-27 22:12 UTC
