### ISSUE TITLE
restic should not abort on unknown directories / files in the repository

### ISSUE THREAD

**Issue by ckeen** [restic/restic#2199] opened 2019-03-08 08:45 UTC
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-31-g0022926e) compiled with go1.11.5 on linux/amd64

How did you run restic exactly?
-------------------------------
 restic -v -r /mnt/backup/backup -p /home/ckeen/.backup_pass check 

Aborted with:

check snapshots, trees and blobs
hex.DecodeString: encoding/hex: invalid byte: U+002E '.'

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

A CIFS mount which is on a NAS

Expected behavior
-----------------

Checking the repo warning me on additional files

Actual behavior
---------------

Restic aborts on the first directory that does not fit the expected name scheme.
In my case the NAS added .DAV directories into every dir of the repo.

Steps to reproduce the behavior
-------------------------------

Add a subdir .DAV anywhere in the dir structure, run restic check on it.

Do you have any idea what may have caused this?
-----------------------------------------------

See above.

Do you have an idea how to solve the issue?
-------------------------------------------

The workaround is to remove all these directories as they are just additional cruft.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, it has been keeping me in a workable state for years. Thanks! I recommend it to all my peers that ask for it (or not)...

**Comment by mholt** [comment] 2019-03-08 17:05
(Just wanted to say that I appreciate your username and profile pic. Haven't thought about that in years!)

**Comment by MichaelEischer** [comment] 2020-10-06 20:01
Closing this as the bug seems to have been fixed in restic 0.9.5. Since then I'm no longer able to reproduce this issue. Feel free to complain if this is still a problem.

**Closed by MichaelEischer** 2020-10-06 20:01 UTC
