### ISSUE TITLE
Backup of two folders with same name in different start location does not work

### ISSUE THREAD

**Issue by Radioactive-Man** [restic/restic#1213] opened 2017-09-05 13:36 UTC
## Output of restic version
```
restic 0.7.1 (v0.7.1-0-g04cfb984)
compiled with go1.7.1 on windows/amd64
```

## How did you run restic exactly?
```
C:\Tools\restic>restic backup b:\workspace\ResticTest\RepoA\.git b:\workspace\ResticTest\RepoB\.git
using parent snapshot 5302886a
scan [b:\workspace\ResticTest\RepoA\.git b:\workspace\ResticTest\RepoB\.git]
scanned 2 directories, 2 files in 0:00
[0:00] 100.00%  0B/s  12B / 12B  4 / 4 items  0 errors  ETA 0:00
duration: 0:00, 0.00MiB/s
snapshot b93511fe saved
```

The folders look like this
```
B:\WORKSPACE\RESTICTEST
+---RepoA
|   +---.git
|   |       RepoAFile.txt
|   |
|   \---a
|           a.txt
|
\---RepoB
    +---.git
    |       RepoBFile.txt
    |
    \---b
            b.txt
```
## What backend/server/service did you use?
File backend

## Expected behavior
That all my files are in the backup but RepoBFile.txt is missing

## Actual behavior
```
C:\Tools\restic>restic snapshots
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
c6b90dbf  2017-09-05 15:15:55  FE-Z1AIW            ┌── b:\workspace\ResticTest\RepoB\.git
                                                   └── b:\workspace\ResticTest\RepoA\.git

C:\Tools\restic>restic ls latest
snapshot 5302886a of [b:\workspace\ResticTest\RepoA\.git b:\workspace\ResticTest\RepoB\.git] at 2017-09-05 15:
18:50.6564351 +0200 CEST):
\.git
\.git\RepoAFile.txt
```
## Steps to reproduce the behavior
See above

## Do you have any idea what may have caused this?
No

## Do you have an idea how to solve the issue?
No

**Comment by fd0** [comment] 2017-09-05 18:47
Thanks for the report, this is actually a duplicate of #549, and I'm currently working on that (first steps see #1209), so I'm going to close this issue as a duplicate. Please feel free to add further comments, thanks!

**Closed by fd0** 2017-09-05 18:47 UTC
