### ISSUE TITLE
Problem with files that may be moved or removed during backups - Windows

### ISSUE THREAD

**Issue by fpopineau** [restic/restic#5063] opened 2024-09-15 21:34 UTC
Output of `restic version`
--------------------------

```
PS C:\local\restic> .\restic version
restic 0.17.1 compiled with go1.23.1 on windows/amd64
```

What backend/service did you use to store the repository?
---------------------------------------------------------

sftp

Problem description / Steps to reproduce
----------------------------------------

Edit Office files (MSWord, Excel, Powerpoint) while running a backup.

Expected behavior
-----------------

Up to now, I did not notice errors related to the files that I was working on during backups. 
I expect that the backup can run in the background without interfering with the work I do.

Actual behavior
---------------

I was working with a Powerpoint file while the backup was running. 
The temporary file that Powerpoint creates caused the following error:

```
restic.exe : error: incomplete metadata for Home\@Work\02-Areas\Teaching\Python-DSBA\slides\~$Python-1.pptx: multiple
errors occurred: [get named security info failed with: The system cannot find the file specified.; get EA failed while
opening file handle for path Home\@Work\02-Areas\Teaching\Python-DSBA\slides\~$Python-1.pptx, with: The system cannot
find the file specified.]
```

Do you have any idea what may have caused this?
-----------------------------------------------

This file has been removed when I closed Powerpoint during the backup.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Definitely yes : I rely on restic for my home computers backups for a few years now.
It is by far the best tool that I could find for this job.

**Comment by KamikazeePL** [comment] 2024-09-19 09:20
Try to backup with VSS

On Windows, the -`-use-fs-snapshot` option will use Windows’ Volume Shadow Copy Service (VSS) when creating backups. Restic will transparently create a VSS snapshot for each volume that contains files to backup. Files are read from the VSS snapshot instead of the regular filesystem. This allows to backup files that are exclusively locked by another process during the backup.

**Comment by LeLocTai** [comment] 2024-09-21 04:37
I'm also facing this issue. It seems to be a regression, as the files that are causing the problem in my case are some temp files that have always been removed often. 
The error only showed up in v0.17, though I didn't remember which version I used previously.
Ideally I should exclude these files, but a lot of programs generate them so it is not practical to do so.

**Comment by MichaelEischer** [comment] 2024-10-17 19:41
This is the windows variant of https://github.com/restic/restic/issues/3098 . I'm currently (slowly) working on fixing that in https://github.com/restic/restic/issues/5021 but that will still take some time.

> Thanks, but all my backups are made using VSS:

That sounds like there's a second bug somewhere. Judging from the file paths in the error message is looks like the metadata isn't read from the VSS snapshot, which is obviously wrong.

**Comment by LeLocTai** [comment] 2024-10-18 06:31
If it help, this is my log which have a different path structure:
```
using parent snapshot f6331baa
creating VSS snapshot for [c:\]
successfully created snapshot for [c:\]
mountpoints in snapshot volume [c:\]:
 - c:\programdata\microsoft\windows\containers\baseimages\6962efff-1dfc-4947-b80d-381d91de438d\baselayer\ (not snapshotted)
 - c:\programdata\microsoft\windows\containers\baseimages\3f66de78-6799-4622-97ac-adbd7f58ca64\baselayer\ (not snapshotted)
error: incomplete metadata for C:\Users\username\AppData\Local\Microsoft\Windows\Clipboard\HistoryData\{631A7724-4BED-4BAB-991B-32ABDB16912A}: multiple errors occurred: [get named security info failed with: The system cannot find the file specified.; get EA failed while opening file handle for path C:\Users\username\AppData\Local\Microsoft\Windows\Clipboard\HistoryData\{631A7724-4BED-4BAB-991B-32ABDB16912A}, with: The system cannot find the file specified.]
error: incomplete metadata for ... a lot more
```

**Comment by tszynalski** [comment] 2024-10-18 18:41
I've been experiencing the exact same issue with VSS backup on Windows ever since I upgraded to the latest version of Restic. About 30% of the time, restic exits with an error code about some temp file (though the backup is performed fine, it seems), which causes my PowerShell script to think that the backup has failed.
I'll be looking forward to a fix.

**Comment by MichaelEischer** [comment] 2024-10-18 20:47
When creating a VSS backup, the extended metadata was not read from the snapshot but instead from the original filepath. That will be fixed by https://github.com/restic/restic/pull/5097 . (The actual fix is the first commit, everything else is just there to make sure that the issue cannot reappear).

The fix will also land in restic 0.17.2 although that requires a different change https://github.com/restic/restic/pull/5099 .

**Closed** 2024-10-22 17:23 UTC
Labels: type: bug, category: backup

**Comment by ilium007** [comment] 2024-10-29 23:56
Backups failing with 0.17.2 

```
restic.exe : error: incomplete metadata for D:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy165\, with: get file EA failed with: The parameter is incorrect.]
At C:\restic\backup_us.ps1:288 char:13
+             & $ResticExe backup $ResticBackupFlags $folder_list $vss_ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error: incomple... is incorrect.]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Reverted to 0.17.0 and backups are working again.

**Comment by ilium007** [comment] 2024-10-30 05:14
> I'm also having similar problem with the update:
> 
> ```
> 
> using parent snapshot 0a44f88f
> 
> creating VSS snapshot for [c:\]
> 
> successfully created snapshot for [c:\]
> 
> mountpoints in snapshot volume [c:\]:
> 
>  - c:\programdata\microsoft\windows\containers\baseimages\6962efff-1dfc-4947-b80d-381d91de438d\baselayer\ (not snapshotted)
> 
>  - c:\programdata\microsoft\windows\containers\baseimages\93d9469d-4548-4476-bbe0-383d4d23c9f5\baselayer\ (not snapshotted)
> 
> error: incomplete metadata for C:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy5\, with: The process cannot access the file because it is being used by another process.]
> 
> ```
> 
> 
> 
> `is being used by another process` error don't make sense to me since the point of VSS is to avoid this very error?

Yes, roll restic executable back to 0.17.1 and disable maintenance because it will self-update again.

**Comment by MichaelEischer** [comment] 2024-10-30 20:17
See https://github.com/restic/restic/issues/5107
