### ISSUE TITLE
--forget monthly policy is inconsistent

### ISSUE THREAD

**Issue by the-emerald** [restic/restic#4415] opened 2023-07-20 16:17 UTC
Output of `restic version`
--------------------------
```
restic 0.15.2 compiled with go1.20.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
RCLONE_FAST_LIST=true restic -r rclone:b2:PATH_TO_REPOSITORY forget --dry-run --keep-hourly 48 --keep-daily 14 --keep-weekly 8 --keep-monthly 24 --keep-yearly 4
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2 via rclone

Expected behavior
-----------------

`--keep-monthly` should keep the most recent snapshot for every month, i.e. the last backup in April, May, June, etc.. March should not be missing.

Actual behavior
---------------

The repository is scripted to have a snapshot added every hour, on the hour. Backups began on 2022-12-15. The following snapshots are being kept:

```
ID        Time                 Host        Tags        Reasons           Paths
------------------------------------------------------------------------------
da19e1b3  2022-12-31 23:00:02  ganymede                monthly snapshot  /
                                                       yearly snapshot
5abbe9f2  2023-01-31 23:00:02  ganymede                monthly snapshot  /
36c2de36  2023-02-28 23:00:01  ganymede                monthly snapshot  /
bf678323  2023-04-01 00:00:02  ganymede                monthly snapshot  /
54ac8b51  2023-05-01 00:00:02  ganymede                monthly snapshot  /
175cff8f  2023-06-01 00:00:05  ganymede                monthly snapshot  /
4f620cc0  2023-06-05 00:00:01  ganymede                weekly snapshot   /
f0b235ba  2023-06-12 00:00:08  ganymede                weekly snapshot   /
ae919953  2023-06-19 00:00:05  ganymede                weekly snapshot   /
0ed94901  2023-06-26 00:00:03  ganymede                weekly snapshot   /
86faf2b0  2023-07-01 00:00:03  ganymede                monthly snapshot  /
...
```

Notice how the backups for Dec 22, Jan 23, Feb 23 are all at the end of the month. No backups are kept for March. From April onwards, the monthly snapshot kept is at the beginning of the month.

Steps to reproduce the behavior
-------------------------------

Make a snapshot every hour for almost a year.

Run `forget` with the policy.

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes! I use restic for scheduled backups and this is a lifesaver. Being able to mount snapshots as a FUSE, over rclone, is amazing.

**Comment by the-emerald** [comment] 2023-07-20 17:05
I think it's timezones! 
> In the UK the clocks go forward 1 hour at 1am on the last Sunday in March, and back 1 hour at 2am on the last Sunday in October

Which would explain everything after `bf678323`. In UTC, these are all the 30/31st of the last month.

**Comment by MichaelEischer** [comment] 2023-07-22 16:31
`forget` uses the local time stored in the snapshot, whereas the output of `snapshots` uses the current timezone. I'll close this issue as a duplicate of https://github.com/restic/restic/issues/2233 .

**Closed by MichaelEischer** 2023-07-22 16:31 UTC
