### ISSUE TITLE
Cannot dump directory to tar; does not detect file redirection.

### ISSUE THREAD

**Issue by spgill** [restic/restic#2580] opened 2020-02-16 05:44 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic --repo ./backup-test dump latest "/" > ./latest.tar` and several other permutations of the same command

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local files

Expected behavior
-----------------
Write a valid tar archive to the filepath I gave it, as described in the comments of cc8b690b5

Actual behavior
---------------
I receive an error in the console with the following text: `cannot dump file: stdout is the terminal, please redirect output`

and the file I redirected to contains `repository 0eba673e opened successfully, password is correct`

However, if I pipe the exact same command to another command it works exactly as expected. E.g., `restic --repo ./backup-test dump latest "/" | tar tv` will print the full contents of the tar file I would expect to receive from redirecting to a file.

Steps to reproduce the behavior
-------------------------------

1. Initialize a new repo
2. Add at least one backup to the repo
3. Try to dump a _directory_ from any snapshot, while redirecting the output to a file (using the `>` character)

Do you have any idea what may have caused this?
-----------------------------------------------
Best guess is that the logic for detected a tty session on stdout may be faulty.

Do you have an idea how to solve the issue?
-------------------------------------------
No clue. I'm not very familiar with the codebase or with Go.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Oh absolutely! It's replaced my method for weekly backups of Docker data. It's so much easier to use and easier to query than my previous solution.

**Comment by rawtaz** [comment] 2020-02-16 13:57
@Kidswiss I don't suppose this has anything to do with #2254/#2255?

**Comment by Kidswiss** [comment] 2020-02-16 20:13
@rawtaz I haven't encountered that during all my testing.

I'm using `stdoutIsTerminal()` to detect that (https://github.com/restic/restic/blob/master/cmd/restic/cmd_dump.go#L204) so maybe it's an issue there?

BTW: #2255 is ready for reviewing again, so we can finally get rid of that stupid bug :)

**Comment by MichaelEischer** [comment] 2020-08-31 21:06
@spgill restic uses `IsTerminal` from the standard `golang.org/x/crypto/ssh/terminal`, which checks whether the file descriptor has terminal configuration options. I don't see how that could erroneously detect a file as a terminal.

Which shell are you using and on which filesystem did you try to store the tar file?

**Comment by MichaelEischer** [comment] 2020-10-10 12:34
Closing this as we can't reproduce it, the cause is likely outside restic and we didn't get the requested informatino. Feel free to add the information and reopen the issue.

**Closed by MichaelEischer** 2020-10-10 12:34 UTC
Labels: help: minor complexity, help: wanted, state: need feedback
