### ISSUE TITLE
Add (Linux) Binaries for Download

### ISSUE THREAD

**Issue by jojomi** [restic/restic#297] opened 2015-09-07 12:28 UTC
Go's static binding allows for very convenient builds for linux without the hassle of all the different packaging standards.
Projects like [hugo](https://github.com/spf13/hugo/releases) provide binaries for all supported platforms for every github release. Perhaps [goxc](https://github.com/laher/goxc) is an interesting project for this issue.

I don't see why restic could not do this :-). It should make the project a lot more accessible because testers would no longer need a configured go environment.

**Comment by fd0** [comment] 2015-09-07 13:05
Thanks for rising this issue. I'm not sure what's the best approach here, since we'd need to guarantee the integrity of the binaries, ideally by providing digital signatures and an exact way to produce byte-identical binaries (so called "reproduceable builds"). At the moment, only the releases (0.1.0) are signed by me personally via GPG...

**Comment by bchapuis** [comment] 2015-09-07 13:49
Apparently, the debian [wiki](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) simply proposes to add the asc file to the downloadable binaries.

**Comment by fd0** [comment] 2015-09-07 14:26
That's not the problem, signed tags are a standard feature of git...

**Comment by xor-gate** [comment] 2015-11-22 21:06
Restic could do the same as syncthing does to provide signed binaries: https://syncthing.net/security.html  they even have their own tool to sign and verify without the use of gpg and openssl. http://docs.syncthing.net/dev/release-signing.html  the tool is available here which is implemented in golang: https://github.com/syncthing/syncthing/blob/master/cmd/stsigtool/main.go

Hope this is some inspiration :-)

**Comment by fd0** [comment] 2017-07-05 08:50
This is already implemented, we're providing signed binaries for releases and even provide instructions how to reproduce the binaries. I'm closing this issue.

**Closed by fd0** 2017-07-05 08:50 UTC
Labels: project, rfc
