### ISSUE TITLE
Single tag in forget --keep-tag enclosed by brackets has odd behaviour

### ISSUE THREAD

**Issue by the-emerald** [restic/restic#3411] opened 2021-05-31 14:31 UTC
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.16rc1 on linux/amd64`

How did you run restic exactly?
-------------------------------
Here is the list of relevant snapshots for this issue:
`restic -r <repo> snapshots --tag wd-element`

```
ID        Time                 Host             Tags                      Paths
-----------------------------------------------------------------------------------------------
86d9177b  2021-05-17 14:21:22  DESKTOP-GR484G2  wd-elements,keep          F:\rescue-temp-backup
63a2a014  2021-05-27 01:06:54  DESKTOP-GR484G2  wd-elements,last-J,keep   E:\rescue
c5ccdea2  2021-05-29 00:39:25  DESKTOP-GR484G2  wd-elements               E:\rescue
c782e851  2021-05-29 20:34:32  DESKTOP-GR484G2  wd-elements               E:\rescue
97b8c0d1  2021-05-30 18:20:35  DESKTOP-GR484G2  wd-elements               E:\rescue
026990b7  2021-05-30 23:58:46  DESKTOP-GR484G2  wd-elements               E:\rescue
b5f71194  2021-05-31 13:22:37  DESKTOP-GR484G2  wd-elements,trimmed,keep  E:\rescue
-----------------------------------------------------------------------------------------------
7 snapshots
```
First, notice how `--keep-tag={keep}` would have removed some snapshots with the tag `keep` in them, but not others.
`restic -r <repo> --tag wd-elements --keep-tag={keep} --dry-run`

```
Applying Policy: all snapshots with tags [[{keep}]]
remove 6 snapshots:
ID        Time                 Host             Tags                      Paths
-----------------------------------------------------------------------------------
63a2a014  2021-05-27 01:06:54  DESKTOP-GR484G2  wd-elements,last-J,keep   E:\rescue
c5ccdea2  2021-05-29 00:39:25  DESKTOP-GR484G2  wd-elements               E:\rescue
c782e851  2021-05-29 20:34:32  DESKTOP-GR484G2  wd-elements               E:\rescue
97b8c0d1  2021-05-30 18:20:35  DESKTOP-GR484G2  wd-elements               E:\rescue
026990b7  2021-05-30 23:58:46  DESKTOP-GR484G2  wd-elements               E:\rescue
b5f71194  2021-05-31 13:22:37  DESKTOP-GR484G2  wd-elements,trimmed,keep  E:\rescue
-----------------------------------------------------------------------------------
6 snapshots

remove 1 snapshots:
ID        Time                 Host             Tags              Paths
---------------------------------------------------------------------------------------
86d9177b  2021-05-17 14:21:22  DESKTOP-GR484G2  wd-elements,keep  F:\rescue-temp-backup
---------------------------------------------------------------------------------------
1 snapshots

Would have removed the following snapshots:
{026990b7 63a2a014 86d9177b 97b8c0d1 b5f71194 c5ccdea2 c782e851}
```
However, using `--keep-tag keep` without the brackets seems to do the trick.
 `restic -r <repo> --tag wd-elements --keep-tag keep --dry-run`

```
Applying Policy: all snapshots with tags [[keep]]
keep 2 snapshots:
ID        Time                 Host             Tags                      Reasons          Paths
----------------------------------------------------------------------------------------------------
63a2a014  2021-05-27 01:06:54  DESKTOP-GR484G2  wd-elements,last-J,keep   has tags [keep]  E:\rescue
b5f71194  2021-05-31 13:22:37  DESKTOP-GR484G2  wd-elements,trimmed,keep  has tags [keep]  E:\rescue
----------------------------------------------------------------------------------------------------
2 snapshots

remove 4 snapshots:
ID        Time                 Host             Tags         Paths
----------------------------------------------------------------------
c5ccdea2  2021-05-29 00:39:25  DESKTOP-GR484G2  wd-elements  E:\rescue
c782e851  2021-05-29 20:34:32  DESKTOP-GR484G2  wd-elements  E:\rescue
97b8c0d1  2021-05-30 18:20:35  DESKTOP-GR484G2  wd-elements  E:\rescue
026990b7  2021-05-30 23:58:46  DESKTOP-GR484G2  wd-elements  E:\rescue
----------------------------------------------------------------------
4 snapshots

keep 1 snapshots:
ID        Time                 Host             Tags              Reasons          Paths
--------------------------------------------------------------------------------------------------------
86d9177b  2021-05-17 14:21:22  DESKTOP-GR484G2  wd-elements,keep  has tags [keep]  F:\rescue-temp-backup
--------------------------------------------------------------------------------------------------------
1 snapshots

Would have removed the following snapshots:
{026990b7 97b8c0d1 c5ccdea2 c782e851}
```

Finally, what if we use `--keep-tag={keep, last-J}` (multiple tags to keep)?
`restic -r <repo> forget --tag wd-elements --keep-tag={keep,last-J} --dry-run`
```
Applying Policy: all snapshots with tags [[keep] [last-J]]
keep 1 snapshots:
ID        Time                 Host             Tags              Reasons          Paths
--------------------------------------------------------------------------------------------------------
86d9177b  2021-05-17 14:21:22  DESKTOP-GR484G2  wd-elements,keep  has tags [keep]  F:\rescue-temp-backup
--------------------------------------------------------------------------------------------------------
1 snapshots

keep 2 snapshots:
ID        Time                 Host             Tags                      Reasons            Paths
------------------------------------------------------------------------------------------------------
63a2a014  2021-05-27 01:06:54  DESKTOP-GR484G2  wd-elements,last-J,keep   has tags [keep]    E:\rescue
                                                                          has tags [last-J]
b5f71194  2021-05-31 13:22:37  DESKTOP-GR484G2  wd-elements,trimmed,keep  has tags [keep]    E:\rescue
------------------------------------------------------------------------------------------------------
2 snapshots

remove 4 snapshots:
ID        Time                 Host             Tags         Paths
----------------------------------------------------------------------
c5ccdea2  2021-05-29 00:39:25  DESKTOP-GR484G2  wd-elements  E:\rescue
c782e851  2021-05-29 20:34:32  DESKTOP-GR484G2  wd-elements  E:\rescue
97b8c0d1  2021-05-30 18:20:35  DESKTOP-GR484G2  wd-elements  E:\rescue
026990b7  2021-05-30 23:58:46  DESKTOP-GR484G2  wd-elements  E:\rescue
----------------------------------------------------------------------
4 snapshots

Would have removed the following snapshots:
{026990b7 97b8c0d1 c5ccdea2 c782e851}
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local drive

Expected behavior
-----------------

The parameters `--keep-tag={foo}` and `--keep-tag foo` act the same way, or at least consistent with `--keep-tag={foo,bar}`.

Actual behavior
---------------

See above - I'm not too sure what's happening here.

Steps to reproduce the behavior
-------------------------------

Set up snapshots with `foo` tag, add `bar` to some of them. Observe `forget --tag foo --keep={bar}` vs `forget --tag foo --keep bar`.

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic has gotten me off my lazy butt and actually doing backups! You're doing the world a service.

**Comment by MichaelEischer** [comment] 2021-06-04 23:07
From what I can tell, the behavior you're seeing is caused by your shell and not restic. This is the output I get using bash 5.0.17:
```
set -x
$ restic -r <repo> forget --tag wd-elements --keep-tag={keep} --dry-run
restic -r <repo> forget --tag wd-elements --keep-tag={keep} --dry-run

$ restic -r <repo> forget --tag wd-elements --keep-tag keep --dry-run
restic -r <repo> forget --tag wd-elements --keep-tag keep --dry-run

$ restic -r <repo> forget --tag wd-elements --keep-tag={keep,last-J} --dry-run
restic -r <repo> forget --tag wd-elements --keep-tag=keep --keep-tag=last-J --dry-run
```

The last line shows that the shell has used brace expansion which results in two separate `--keep-tag` parameters. This also explains why restic reported these tags: `[[keep] [last-J]]`, The inner square brackets delimit tags passed individually via `--keep-tag`. For example `--keep-tags=abc,def` results in `[[abc, def]]`, which keeps snapshots with both the `abc` and `def` tags.

When you correctly escape the curly brackets you'll get the following results: `--keep-tag='{abc,def}'` expands to `[[{abc, def}]]` where `{abc` is the first tag and `def}` the second one. restic just blindly splits tag lists at commas `,` and removes leading and trailing whitespace.

**Comment by MichaelEischer** [comment] 2021-08-11 19:09
Closing as the issue seems to be caused by brace expansion in the shell. Feel free to reopen the issue if this is not the case.

**Closed by MichaelEischer** 2021-08-11 19:09 UTC
Labels: type: question/problem, state: need feedback
