### ISSUE TITLE
Permission denied error on an excluded folder

### ISSUE THREAD

**Issue by sonicdoe** [restic/restic#1706] opened 2018-04-05 19:30 UTC
## Output of `restic version`

```
restic 0.8.3
compiled with go1.10 on darwin/amd64
```

## How did you run restic exactly?

```
$ restic init --repo /tmp/backup
enter password for new repository: 
enter password again: 
created restic repository 085b3c76b9 at /tmp/backup

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
$ restic --repo /tmp/backup backup /Volumes/restic-test --exclude=.Trashes
enter password for repository: 
password is correct
scan [/Volumes/restic-test]
error for /Volumes/restic-test/.Trashes: open /Volumes/restic-test/.Trashes: permission denied
scanned 2 directories, 3 files in 0:00
[0:00] 100.00%  6.039 KiB / 6.039 KiB  5 / 5 items  0 errors  ETA 0:00 
duration: 0:00
snapshot 40dc1520 saved
```

## What backend/server/service did you use to store the repository?

Local repository.

## Expected behavior

restic should not access excluded folders.

## Actual behavior

restic accesses excluded folders and prints a “permission denied” error.

## Steps to reproduce the behavior

Backup a folder containing a folder which restic is not allowed to list and which is excluded using `--exclude`. A good example is `.Trashes` on macOS since users are not allowed to list its contents without `sudo`.

(Sorry for the terse instructions, however, since I have a pretty good idea why this is happening I figured this would be enough.)

## Do you have any idea what may have caused this?

When `Walk`-ing a directory, restic filters paths _after_ checking for any errors. See: https://github.com/restic/restic/blob/4b2d3b15a260cab5398f27bf8a4b546aaaeadea4/internal/archiver/archiver.go#L826-L843

## Do you have an idea how to solve the issue?

One way would be to `SkipDir` _before_ printing an error. Another (and probably nicer) way would be to completely avoid accessing any excluded directories.

## Did restic help you or made you happy in any way?

I’ve only started using restic a few days ago but I’m quite liking it so far 🙂

**Comment by fd0** [comment] 2018-04-05 20:31
Thanks for the report, this will change in #1494 anyway. I'll have a look.

**Comment by fd0** [comment] 2018-04-05 20:33
It's a duplicate of #1670, I'll close this one. Please subscribe over there. Thanks!

**Closed by fd0** 2018-04-05 20:33 UTC
Labels: bug, duplicate
