### ISSUE TITLE
386 version dont running >= 0.9.2

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#2190] opened 2019-02-27 09:39 UTC
Output of `restic version`
--------------------------
```
futexwakeup addr=0x8c008ec returned -38
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x806cb42]

runtime stack:
runtime.throw(0x86ee401, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x6a
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x239
runtime.futexwakeup(0x8c008ec, 0x1)
	/usr/local/go/src/runtime/os_linux.go:81 +0x82
runtime.notewakeup(0x8c008ec)
	/usr/local/go/src/runtime/lock_futex.go:136 +0x4b
runtime.startlockedm(0x90000e0)
	/usr/local/go/src/runtime/proc.go:2194 +0x6f
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2626 +0x64
runtime.park_m(0x9000620)
	/usr/local/go/src/runtime/proc.go:2676 +0x99
runtime.mcall(0x903e000)
	/usr/local/go/src/runtime/asm_386.s:345 +0x47

goroutine 1 [runnable, locked to thread]:
time.init()
	/usr/local/go/src/time/format.go:1263 +0x120
```

How did you run restic exactly?
-------------------------------
```
restic version
```

**Comment by fd0** [comment] 2019-02-27 10:46
Huh, interesting. We need a bit more information from you, which operating system are you using? Which distribution, which Linux kernel version?

**Comment by unclesamwk** [comment] 2019-02-27 12:09
os = gentoo
kernel = 2.6.20 ( sorry very old i know, migration will be done to a newer kernel )
virtualisation = xen
0.9.2 = works
0.9.3 = dont works
0.9.4 = dont works

**Comment by mholt** [comment] 2019-02-27 12:38
It looks like the panic originates in Go's standard library, and I wonder if it's due to such an old kernel version, maybe no longer supported by Go?

**Comment by smlx** [comment] 2019-02-27 12:38
Actually 2.6.20 doesn't meet the minimum requirements for Go:
https://github.com/golang/go/wiki/MinimumRequirements

**Comment by fd0** [comment] 2019-02-27 19:00
@smlx thanks for the hint, that's likely the cause.

@unclesamwk did you build restic yourself? If so, is it maybe possible that the Go version you used for that changed? So maybe using an older version of Go would help you.

I'll close this issue for now, please let us know when you test this on a newer kernel. Thanks!

**Closed by fd0** 2019-02-27 19:00 UTC
Labels: question

**Comment by unclesamwk** [comment] 2019-02-28 07:36
No i dont build the binary self. i download it from github

**Comment by fd0** [comment] 2019-02-28 10:23
Ok, thanks for the feedback. You said that 0.9.2 works, and 0.9.3 does not work, which can be explained by the version of Go we used for building the binaries:
```
restic 0.9.1 compiled with go1.10.3 on linux/amd64
restic 0.9.2 compiled with go1.10.3 on linux/amd64
restic 0.9.3 compiled with go1.11.1 on linux/amd64
restic 0.9.4 compiled with go1.11.4 on linux/amd64
```

So you could also build restic 0.9.4 with Go 1.10, maybe it works :)
