### ISSUE TITLE
Build in retries.

### ISSUE THREAD

**Issue by wdl1908** [restic/restic#677] opened 2016-11-17 18:22 UTC
at this point [archiver.go#L162](https://github.com/restic/restic/blob/master/src/restic/archiver/archiver.go#L162)

would it be possible to build in a retry. I keep getting these errors when I use a mounted acd_cli fuse file system.

```
panic: TempFile: open /home/acdmount/restic/tmp/temp-974714707: connection timed outA 4:32 

goroutine 776160 [running]:
panic(0xa6c4c0, 0xc82905b720)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
restic/archiver.(*Archiver).saveChunk(0xc82bc04320, 0x3225e36, 0xe4522, 0x138d40add895aa, 0xc83ca5e000, 0xe4522, 0x188000, 0xc8223ac2c0, 0x7f7d422d4cd8, 0xc820050638, ...)
        /tmp/restic-build-300512101/src/restic/archiver/archiver.go:164 +0x12b
created by restic/archiver.(*Archiver).SaveFile
        /tmp/restic-build-300512101/src/restic/archiver/archiver.go:236 +0x629
```

And then the backup must be restarted.

If it could retry a few times it would probably continue.

**Comment by fd0** [comment] 2016-11-18 06:58
Thanks for the suggestion, this is a duplicate of #415 (described for the s3 backend). Unfortunately it's not so easy to just retry again: The other backends (especially sftp) need to reestablish a connection. Code needs to be added for this.

**Closed by fd0** 2016-11-18 06:58 UTC
Labels: duplicate, feature
