### ISSUE TITLE
Parent identification bug

### ISSUE THREAD

**Issue by colorimeter** [restic/restic#4924] opened 2024-07-19 15:58 UTC
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local filesystem or any other

Problem description / Steps to reproduce
----------------------------------------
Restic does not identify the content of the previous snapshot as already backed up even they are the same if parent directory backed up.

Test, let have a tree:

```
/tobackup/a/...
/tobackup/b/...
/tobackup/c/...
```

take a backup like this:

```
cd /tobackup
restic backup *
```

fetch the snapshot id and backup the parent directory itself:

```
cd /
restic backup tobackup --parent snapshot_id
```

Expected behavior
-----------------
the files should only only be stat()-ed.

Actual behavior
---------------
the second backup reads all content again and creates checksums to identify the files to be the same.

Do you have any idea what may have caused this?
-----------------------------------------------
file paths stored differently?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
absolutely

**Comment by MichaelEischer** [comment] 2024-07-20 19:52
I've already replied at https://forum.restic.net/t/parent-content-identification-bug/8054 (please give us more than 9 minutes before opening an issue in addition to a forum post).

Duplicate of https://github.com/restic/restic/issues/2641 .

**Closed by MichaelEischer** 2024-07-20 19:52 UTC
