### ISSUE TITLE
restic restore fails to re-restore symlinks

### ISSUE THREAD

**Issue by piotrcki** [restic/restic#3368] opened 2021-04-22 19:57 UTC
Output of `restic version`
--------------------------

`restic 0.12.0 compiled with go1.16rc1 on linux/amd64`

How did you run restic exactly?
-------------------------------

Here is the full scenario.

```
#!/bin/bash
set -e
set -x

TMP=$(mktemp -d restic-link-demo-XXXXXX)
cd "${TMP}"
mkdir dir1
echo A > dir1/file1
echo B > dir1/file2
ln -s file2 dir1/symlink-to-file2
echo 'pa$$' > restic-pass

restic init    -v -p restic-pass -r restic-repo
restic backup  -v -p restic-pass -r restic-repo dir1

rm -r dir1

restic restore -v -p restic-pass -r restic-repo -t . latest # This works
set +e
restic restore -v -p restic-pass -r restic-repo -t . latest # This FAILS
set -e

cd -
rm -rf "${TMP}"
```

Here is the output.

```
++ mktemp -d restic-link-demo-XXXXXX
+ TMP=restic-link-demo-eO1EfY
+ cd restic-link-demo-eO1EfY
+ mkdir dir1
+ echo A
+ echo B
+ ln -s file2 dir1/symlink-to-file2
+ echo 'pa$$'
+ restic init -v -p restic-pass -r restic-repo
created restic repository a6cda6bf8b at restic-repo

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
+ restic backup -v -p restic-pass -r restic-repo dir1
open repository
repository a6cda6bf opened successfully, password is correct
created new cache in /var/home/user/.cache/restic
lock repository
load index files
no parent snapshot found, will read all files
start scan on [dir1]
start backup on [dir1]
scan finished in 0.206s: 2 files, 4 B

Files:           2 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Data Blobs:      2 new
Tree Blobs:      2 new
Added to the repo: 1.754 KiB

processed 2 files, 4 B in 0:00
snapshot 59e54c42 saved
+ rm -r dir1
+ restic restore -v -p restic-pass -r restic-repo -t . latest
repository a6cda6bf opened successfully, password is correct
restoring <Snapshot 59e54c42 of [/var/home/user/lab/restic/restic-link-demo-eO1EfY/dir1] at 2021-04-22 21:47:41.890254775 +0200 CEST by user@fedora> to .
+ set +e
+ restic restore -v -p restic-pass -r restic-repo -t . latest
repository a6cda6bf opened successfully, password is correct
restoring <Snapshot 59e54c42 of [/var/home/user/lab/restic/restic-link-demo-eO1EfY/dir1] at 2021-04-22 21:47:41.890254775 +0200 CEST by user@fedora> to .
ignoring error for /dir1/symlink-to-file2: Symlink: symlink file2 /var/home/user/lab/restic/restic-link-demo-eO1EfY/dir1/symlink-to-file2: file exists
Fatal: There were 1 errors

+ set -e
+ cd -
/var/home/user/lab/restic
+ rm -rf restic-link-demo-eO1EfY
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

All in one ext4 filesystem.

Expected behavior
-----------------

The second restore command should succeed the same way than the first one do. 

It work if you remove the symlink creation from the above script.  

Actual behavior
---------------

The second  `restic restore` fails (see comments).

Steps to reproduce the behavior
-------------------------------

See above.

Do you have any idea what may have caused this?
-----------------------------------------------

Yes. Unlike with regular files, the default behavior of symlink creation fails with `File exists` error if there is already an existing symlink with the same path.

Do you have an idea how to solve the issue?
-------------------------------------------

Implement the same behavior for symlinks than for regular files: override silently if already exists. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

The awesome tool replaced all my backup scripts.

**Comment by dimejo** [comment] 2021-04-23 08:35
Duplicate of #2578?

**Comment by piotrcki** [comment] 2021-04-23 09:46
Indeed.

I let project managers close this issue if it's relevant.

**Comment by MichaelEischer** [comment] 2021-05-14 18:37
Closing as duplicate of #2578

**Closed by MichaelEischer** 2021-05-14 18:37 UTC
