### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by a-germain** [restic/restic#3263] opened 2021-02-03 13:14 UTC
Output of `restic version`
--------------------------

restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------

I run a daily cronjob of the following script:

```
#!/bin/bash
source /root/.restic-keys
export RESTIC_REPOSITORY="s3:s3.wasabisys.com/resticbackups"
restic backup /home/famille --exclude .cache --exclude .config/Duplicati --exclude .wine --exclude Downloads --exclude src --exclude .local/share/Steam
restic forget --prune --keep-daily 45 --keep-weekly 13 --keep-monthly 12
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Wasabi S3

Expected behavior
-----------------

No missing blob, pruning working.

Actual behavior
---------------

The latest backup job reported this:

```
Files:         307 new,   338 changed, 152300 unmodified
Dirs:           18 new,   195 changed, 29459 unmodified
Added to the repo: 331.934 MiB

processed 152945 files, 277.008 GiB in 5:25
snapshot 8749e922 saved

mer 03 fév 2021 02:05:27 EST - Running forget and prune...

Applying Policy: keep 45 daily, 13 weekly, 12 monthly snapshots
keep 59 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
\--------------------------------------------------------------------------------------
b84f80c1  2020-03-31 02:00:01  happy                   monthly snapshot  /home/famille
1d2d34ef  2020-04-30 02:00:01  happy                   monthly snapshot  /home/famille
ceffc724  2020-05-31 02:00:01  happy                   monthly snapshot  /home/famille
a1351bb3  2020-06-30 02:00:01  happy                   monthly snapshot  /home/famille
dbdbd85e  2020-07-31 02:00:02  happy                   monthly snapshot  /home/famille
6614ce8d  2020-08-31 02:00:01  happy                   monthly snapshot  /home/famille
c8406842  2020-09-30 02:00:01  happy                   monthly snapshot  /home/famille
a4f2cc0d  2020-10-31 02:00:01  happy                   monthly snapshot  /home/famille
e2a38737  2020-11-15 02:00:01  happy                   weekly snapshot   /home/famille
d3c9299a  2020-11-22 02:00:01  happy                   weekly snapshot   /home/famille
44afa329  2020-11-29 02:00:01  happy                   weekly snapshot   /home/famille
9be5f047  2020-11-30 02:00:01  happy                   monthly snapshot  /home/famille
eb79b6c4  2020-12-06 02:00:01  happy                   weekly snapshot   /home/famille
feb6bc33  2020-12-13 02:00:01  happy                   weekly snapshot   /home/famille
2827dbd1  2020-12-20 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
a57f08ec  2020-12-21 02:00:01  happy                   daily snapshot    /home/famille
9960e623  2020-12-22 02:00:01  happy                   daily snapshot    /home/famille
dc906534  2020-12-23 02:00:01  happy                   daily snapshot    /home/famille
62fd920f  2020-12-24 02:00:02  happy                   daily snapshot    /home/famille
08eb29bb  2020-12-25 02:00:01  happy                   daily snapshot    /home/famille
cee2fbe2  2020-12-26 02:00:02  happy                   daily snapshot    /home/famille
6a69ecb7  2020-12-27 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
36e4e84d  2020-12-28 02:00:01  happy                   daily snapshot    /home/famille
d0296f85  2020-12-29 02:00:01  happy                   daily snapshot    /home/famille
39cadf25  2020-12-30 02:00:01  happy                   daily snapshot    /home/famille
481c695e  2020-12-31 02:00:01  happy                   daily snapshot    /home/famille
                                                       monthly snapshot
a7509e09  2021-01-01 02:00:01  happy                   daily snapshot    /home/famille
83660e31  2021-01-02 02:00:01  happy                   daily snapshot    /home/famille
2d193191  2021-01-03 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
f0c31db2  2021-01-04 02:00:01  happy                   daily snapshot    /home/famille
630c59c0  2021-01-05 02:00:01  happy                   daily snapshot    /home/famille
e83187a2  2021-01-06 02:00:01  happy                   daily snapshot    /home/famille
27380a9a  2021-01-07 02:00:01  happy                   daily snapshot    /home/famille
208f5edd  2021-01-08 02:00:01  happy                   daily snapshot    /home/famille
998e9d48  2021-01-09 02:00:01  happy                   daily snapshot    /home/famille
4426a917  2021-01-10 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
822f4fcb  2021-01-11 02:00:01  happy                   daily snapshot    /home/famille
e42322d1  2021-01-12 02:00:01  happy                   daily snapshot    /home/famille
40cb499a  2021-01-13 02:00:02  happy                   daily snapshot    /home/famille
0cdb8681  2021-01-14 02:00:01  happy                   daily snapshot    /home/famille
97c0a4da  2021-01-15 02:00:01  happy                   daily snapshot    /home/famille
45614400  2021-01-16 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
8f9d3b47  2021-01-18 02:00:01  happy                   daily snapshot    /home/famille
57826743  2021-01-19 02:00:01  happy                   daily snapshot    /home/famille
2bc2111a  2021-01-20 02:00:01  happy                   daily snapshot    /home/famille
d97e7eef  2021-01-21 02:00:01  happy                   daily snapshot    /home/famille
61aad44f  2021-01-22 02:00:01  happy                   daily snapshot    /home/famille
2e3deb08  2021-01-23 02:00:01  happy                   daily snapshot    /home/famille
2666f357  2021-01-24 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
9be836e0  2021-01-25 02:00:01  happy                   daily snapshot    /home/famille
cfdbf883  2021-01-26 02:00:01  happy                   daily snapshot    /home/famille
11c91623  2021-01-27 02:00:01  happy                   daily snapshot    /home/famille
9d2ea2a3  2021-01-28 02:00:01  happy                   daily snapshot    /home/famille
598900a8  2021-01-29 02:00:01  happy                   daily snapshot    /home/famille
2ec853f3  2021-01-30 02:00:01  happy                   daily snapshot    /home/famille
08ea99f4  2021-01-31 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
                                                       monthly snapshot
0711b2fe  2021-02-01 02:00:01  happy                   daily snapshot    /home/famille
0f720925  2021-02-02 02:00:01  happy                   daily snapshot    /home/famille
8749e922  2021-02-03 02:00:01  happy                   daily snapshot    /home/famille
                                                       weekly snapshot
                                                       monthly snapshot
\--------------------------------------------------------------------------------------
59 snapshots

remove 1 snapshots:
ID        Time                 Host        Tags        Paths
\--------------------------------------------------------------------
7e51f618  2020-12-19 02:00:01  happy                   /home/famille
\--------------------------------------------------------------------
1 snapshots

[0:00] 100.00%  1 / 1 files deleted

counting files in repo
building new index for repo
[20:45] 100.00%  85770 / 85770 packs

repository contains 85770 packs (754810 blobs) with 383.698 GiB
processed 754810 blobs: 74 duplicate blobs, 13.061 MiB duplicate
load all snapshots
find data that is still in use for 59 snapshots
[0:14] 100.00%  59 / 59 snapshots

Fatal: [<data/0ee77fd7> <data/2e7618c4> <data/2668d14a> <data/ba957672> <data/5aa2d88b> <data/535bfc8b> <data/df6aa3b6> <data/f2dcf93f> <data/d5c3ddbb> <data/a48d1ede> <data/a37ada1e> <data/6ca73990> <data/8b8ac92d> <data/4078fc0c> <data/2aa6d763> <data/eca13e41> <data/12abd33b> <data/8a4fe266> <data/76893464> <data/570f1c02> <data/899f37f9> <data/79b92009> <data/4652b7d6> <data/fd400bb3> <data/1a6e5716> <data/c1d883a9> <data/53f96e04> <data/4775d1c3> <data/58f37b37> <data/8b658914> <data/ce8f531b> <data/1768aff2> <data/85c00f89> <data/15753e58> <data/55efd68d> <data/8bf2bb5c> <data/eed300d5> <data/bc2d9ea3> <data/e6a13522> <data/8c14c7b1> <data/f6291780> <data/a8f9e540> <data/ff3fbaf7> <data/4ecc6cbb> <data/cb5b6e62> <data/12ae6378> <data/8d0d69ec> <data/97548670> <data/51c1f10b> <data/b561925e> <data/80386412> <data/1ca1af89> <data/780173e6> <data/30966152> <data/a564569b> <data/d4ef7409> <data/a06fcc8a> <data/fd6a8595> <data/98b0e54c> <data/5a4d78e9> <data/134c78e9> <data/e8f02ea9> <data/73dba1c2> <data/35463844>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

Steps to reproduce the behavior
-------------------------------

At this point, run a manual prune job will cause the error.

Do you have any idea what may have caused this?
-----------------------------------------------

No idea! 

But in the future, it might be a good idea not to overwrite my backup.log file everyday, and do periodic checks, right...

Do you have an idea how to solve the issue?
-------------------------------------------

I checked at issues #3241, #3239, #3213, and #3201... still not sure what to do.

When running ```restic check``` manually, it reported a whole bunch of unused blobs, and then ```Fatal: repository contains errors```

Next I ran ```restic rebuild-index```, which completed successfully.

But when running ``` restic prune``` again, it still rebuilds the index and gives me the mentionned fatal error.

I'd like to avoid using ```restic check --read``` if possible , as my understanding is it would download each and every file, and since I don't have unlimited bandwidth, that would be very costly.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Maybe not today, but restic has been the most reliable and fastest backup solution for me yet. I've had to recover multiple times and always knew I could trust restic. Keep up the good work!

**Comment by a-germain** [comment] 2021-02-03 13:16
If this could be helpful, ```restic check``` now reports:

```
error for tree 60a72a56:
  tree 60a72a56: file "0e412010e602bfc1_0" blob 0 size could not be found
  tree 60a72a56: file "0e412010e602bfc1_1" blob 0 size could not be found
  tree 60a72a56: file "0e67a7483a6eb12e_0" blob 0 size could not be found
  tree 60a72a56: file "0e67a7483a6eb12e_1" blob 0 size could not be found
  tree 60a72a56: file "0ef878de0e1a4435_0" blob 0 size could not be found
  tree 60a72a56: file "0ef878de0e1a4435_1" blob 0 size could not be found
  tree 60a72a56: file "0ef878de0e1a4435_1" blob 1 size could not be found
  tree 60a72a56: file "0f69f9441aa3af49_0" blob 0 size could not be found
  tree 60a72a56: file "0f69f9441aa3af49_1" blob 0 size could not be found
  tree 60a72a56: file "105451472d4894a5_0" blob 0 size could not be found
  tree 60a72a56: file "105451472d4894a5_1" blob 0 size could not be found
  tree 60a72a56: file "10d57ce5527e7cc5_0" blob 0 size could not be found
  tree 60a72a56: file "10d57ce5527e7cc5_1" blob 0 size could not be found
  tree 60a72a56: file "14b3bfe33c079b50_0" blob 0 size could not be found
  tree 60a72a56: file "14b3bfe33c079b50_1" blob 0 size could not be found
  tree 60a72a56: file "170e3d2b5fe4d4e1_0" blob 0 size could not be found
  tree 60a72a56: file "170e3d2b5fe4d4e1_1" blob 0 size could not be found
  tree 60a72a56: file "172cf9c03ce94f2b_0" blob 0 size could not be found
  tree 60a72a56: file "172cf9c03ce94f2b_1" blob 0 size could not be found
  tree 60a72a56: file "17fe6b986345ad2f_0" blob 0 size could not be found
  tree 60a72a56: file "17fe6b986345ad2f_1" blob 0 size could not be found
  tree 60a72a56: file "199ac3382b97a8d2_0" blob 0 size could not be found
  tree 60a72a56: file "199ac3382b97a8d2_1" blob 0 size could not be found
  tree 60a72a56: file "1b518fe402712d01_0" blob 0 size could not be found
  tree 60a72a56: file "1b518fe402712d01_1" blob 0 size could not be found
  tree 60a72a56: file "1c8b79982a47511a_0" blob 0 size could not be found
  tree 60a72a56: file "1c8b79982a47511a_1" blob 0 size could not be found
  tree 60a72a56: file "1e38b00b1d7e93aa_0" blob 0 size could not be found
  tree 60a72a56: file "1e38b00b1d7e93aa_1" blob 0 size could not be found
  tree 60a72a56: file "1fa180ea5f690835_0" blob 0 size could not be found
  tree 60a72a56: file "1fa180ea5f690835_1" blob 0 size could not be found
  tree 60a72a56: file "1fff131164792779_0" blob 0 size could not be found
  tree 60a72a56: file "1fff131164792779_1" blob 0 size could not be found
  tree 60a72a56: file "208212d19a75d7fe_0" blob 0 size could not be found
  tree 60a72a56: file "208212d19a75d7fe_1" blob 0 size could not be found
  tree 60a72a56: file "250e1dea70e46e53_0" blob 0 size could not be found
  tree 60a72a56: file "250e1dea70e46e53_1" blob 0 size could not be found
  tree 60a72a56: file "2533979c06eda510_0" blob 0 size could not be found
  tree 60a72a56: file "2533979c06eda510_1" blob 0 size could not be found
  tree 60a72a56: file "253e18f5263d039d_0" blob 0 size could not be found
  tree 60a72a56: file "253e18f5263d039d_1" blob 0 size could not be found
  tree 60a72a56: file "26ee654bd270f1ca_0" blob 0 size could not be found
  tree 60a72a56: file "26ee654bd270f1ca_1" blob 0 size could not be found
  tree 60a72a56, blob 8a4fe266: not found in index
  tree 60a72a56, blob 5aa2d88b: not found in index
  tree 60a72a56, blob 30966152: not found in index
  tree 60a72a56, blob 4078fc0c: not found in index
  tree 60a72a56, blob a8f9e540: not found in index
  tree 60a72a56, blob 1ca1af89: not found in index
  tree 60a72a56, blob ff3fbaf7: not found in index
  tree 60a72a56, blob d4ef7409: not found in index
  tree 60a72a56, blob 4652b7d6: not found in index
  tree 60a72a56, blob 76893464: not found in index
  tree 60a72a56, blob f6291780: not found in index
  tree 60a72a56, blob a37ada1e: not found in index
  tree 60a72a56, blob a48d1ede: not found in index
  tree 60a72a56, blob 51c1f10b: not found in index
  tree 60a72a56, blob 58f37b37: not found in index
  tree 60a72a56, blob 2668d14a: not found in index
  tree 60a72a56, blob e6a13522: not found in index
  tree 60a72a56, blob a564569b: not found in index
  tree 60a72a56, blob 85c00f89: not found in index
  tree 60a72a56, blob 8d0d69ec: not found in index
  tree 60a72a56, blob f2dcf93f: not found in index
  tree 60a72a56, blob 2e7618c4: not found in index
  tree 60a72a56, blob ce8f531b: not found in index
  tree 60a72a56, blob d5c3ddbb: not found in index
  tree 60a72a56, blob 8b8ac92d: not found in index
  tree 60a72a56, blob 6ca73990: not found in index
  tree 60a72a56, blob 12abd33b: not found in index
  tree 60a72a56, blob 12ae6378: not found in index
  tree 60a72a56, blob 535bfc8b: not found in index
  tree 60a72a56, blob 73dba1c2: not found in index
  tree 60a72a56, blob 53f96e04: not found in index
  tree 60a72a56, blob 79b92009: not found in index
  tree 60a72a56, blob 2aa6d763: not found in index
  tree 60a72a56, blob eca13e41: not found in index
  tree 60a72a56, blob fd6a8595: not found in index
  tree 60a72a56, blob 98b0e54c: not found in index
  tree 60a72a56, blob 780173e6: not found in index
  tree 60a72a56, blob 1768aff2: not found in index
  tree 60a72a56, blob 1a6e5716: not found in index
  tree 60a72a56, blob cb5b6e62: not found in index
  tree 60a72a56, blob 97548670: not found in index
  tree 60a72a56, blob df6aa3b6: not found in index
  tree 60a72a56, blob 0ee77fd7: not found in index
error for tree 0d231f37:
  tree 0d231f37: file "f_000139" blob 0 size could not be found
  tree 0d231f37: file "f_00013b" blob 0 size could not be found
  tree 0d231f37: file "f_00013d" blob 0 size could not be found
  tree 0d231f37: file "f_00013f" blob 0 size could not be found
  tree 0d231f37: file "f_000141" blob 0 size could not be found
  tree 0d231f37: file "f_000143" blob 0 size could not be found
  tree 0d231f37, blob fd400bb3: not found in index
  tree 0d231f37, blob 4ecc6cbb: not found in index
  tree 0d231f37, blob 35463844: not found in index
  tree 0d231f37, blob 4775d1c3: not found in index
  tree 0d231f37, blob c1d883a9: not found in index
  tree 0d231f37, blob b561925e: not found in index
error for tree cfb33602:
  tree cfb33602: file "data.mdb" blob 668 size could not be found
  tree cfb33602: file "data.mdb" blob 669 size could not be found
  tree cfb33602: file "data.mdb" blob 672 size could not be found
  tree cfb33602: file "data.mdb" blob 674 size could not be found
  tree cfb33602: file "data.mdb" blob 675 size could not be found
  tree cfb33602: file "data.mdb" blob 680 size could not be found
  tree cfb33602: file "data.mdb" blob 686 size could not be found
  tree cfb33602: file "data.mdb" blob 1054 size could not be found
  tree cfb33602: file "data.mdb" blob 1055 size could not be found
  tree cfb33602: file "data.mdb" blob 1056 size could not be found
  tree cfb33602: file "data.mdb" blob 1518 size could not be found
  tree cfb33602: file "data.mdb" blob 1519 size could not be found
  tree cfb33602: file "data.mdb" blob 1520 size could not be found
  tree cfb33602: file "data.mdb" blob 1521 size could not be found
  tree cfb33602: file "data.mdb" blob 1522 size could not be found
  tree cfb33602, blob 5a4d78e9: not found in index
  tree cfb33602, blob 55efd68d: not found in index
  tree cfb33602, blob 134c78e9: not found in index
  tree cfb33602, blob 8b658914: not found in index
  tree cfb33602, blob bc2d9ea3: not found in index
  tree cfb33602, blob e8f02ea9: not found in index
  tree cfb33602, blob 8c14c7b1: not found in index
  tree cfb33602, blob 8bf2bb5c: not found in index
  tree cfb33602, blob a06fcc8a: not found in index
  tree cfb33602, blob 899f37f9: not found in index
  tree cfb33602, blob ba957672: not found in index
  tree cfb33602, blob eed300d5: not found in index
  tree cfb33602, blob 80386412: not found in index
  tree cfb33602, blob 570f1c02: not found in index
  tree cfb33602, blob 15753e58: not found in index
Fatal: repository contains errors
```

**Comment by a-germain** [comment] 2021-02-03 13:31
Okay, after reading #3241 more closely.. I ran ```restic find --tree <tree ID>``` and it gave me this:

```
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot 1d2d34ef (2020-04-30 02:00:01)
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot 6614ce8d (2020-08-31 02:00:01)
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot a1351bb3 (2020-06-30 02:00:01)
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot b84f80c1 (2020-03-31 02:00:01)
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot ceffc724 (2020-05-31 02:00:01)
Found tree 60a72a567ea68bfa8dc261a4c088d609921e53e4b3e3bfcec9ba5651ad78b116
 ... path /home/famille/.config/google-chrome/Default/Service Worker/CacheStorage/47634290d7931d7d87fd9387c9575f44728e4f4b/a61a0a8e-ca48-44f7-a4d6-1bf2f1e33def
 ... in snapshot dbdbd85e (2020-07-31 02:00:02)
```

On the other issue, backuping the files again seems to have fixed the problem?

To be honest, I *really* don't care about these specific files.

**Comment by a-germain** [comment] 2021-02-03 13:37
> To be honest, I really don't care about these specific files.
And obviously, they don't exist anymore since they are merely cache files...

**Comment by a-germain** [comment] 2021-02-03 22:33
Okay, I didn't feel like trying the beta builds to try and remove individual files in the snapshots (using the new ```rewrite``` command).

I figured I can always backup important files again after, so I ran ```restic forget``` on the problematic snapshots.

```restic check``` then ran successfully:

```
using temporary cache in /tmp/restic-check-cache-263870202
repository 4231af28 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-263870202
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

Running ```restic prune``` as I speak...

```
repository 4231af28 opened successfully, password is correct
counting files in repo
building new index for repo
[20:29] 100.00%  85770 / 85770 packs
repository contains 85770 packs (754810 blobs) with 383.698 GiB
processed 754810 blobs: 74 duplicate blobs, 13.061 MiB duplicate
load all snapshots
find data that is still in use for 53 snapshots
[0:11] 100.00%  53 / 53 snapshots
found 491622 of 754810 data blobs still in use, removing 263188 blobs
will remove 0 invalid files
will delete 20385 packs and rewrite 8097 packs, this frees 109.505 GiB
[12:37] 2.89%  234 / 8097 packs rewritten
```

**Comment by a-germain** [comment] 2021-02-04 13:44
Prune OK, Backup OK.

Waiting instructions to close or leave open for further investigation... thanks.

**Comment by MichaelEischer** [comment] 2021-02-04 21:25
> On the other issue, backuping the files again seems to have fixed the problem?

restic (since 0.10.0) automatically backs up files again when it notices that some blobs of a file are missing. In that case restic will also print a warning that it just recovered missing blobs.

Do you have a log of the `prune` just before the failing one? As you seem to run `forget --prune` each day that would be the most likely command to somehow have caused the missing blobs.

**Comment by a-germain** [comment] 2021-02-04 21:35
> restic (since 0.10.0) automatically backs up files again when it notices that some blobs of a file are missing

ok, and since for me, these files are long gone, that wouldn't have helped.

> Do you have a log of the prune just before the failing one?

Unfortunately, no. I should really setup something more sound in place.

What do you recommend in terms of pruning? Weekly?

**Comment by borkd** [comment] 2021-02-05 01:36
I am seeing the same error message. A number of backups were taken with s3 backend, then all data from the bucket downloaded for local check and restore tests.

`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

```
restic -r wip/ prune --no-cache -vvv
repository 97133fe8 opened successfully, password is correct
counting files in repo
building new index for repo
[2:00] 100.00%  71805 / 71805 packs
repository contains 71805 packs (1424277 blobs) with 366.839 GiB
processed 1424277 blobs: 33726 duplicate blobs, 1.604 GiB duplicate
load all snapshots
find data that is still in use for 351 snapshots
[1:36] 100.00%  351 / 351 snapshots
Fatal: [<data/b0b3ae53> <data/3aa84a56> <data/f422e382> <data/f2c75a69> <data/1b7dd74e>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

**Comment by 4001982248998** [comment] 2021-02-05 08:56
I too have the same problem, on several machines. Running Backups to an S3 implementation and forgetting old backups afterwards. Pruning backups and/or rebuilding indices does not fix the problems. Example, cropped outputs below:

```
Feb 02 22:46:33 FNF-Host-US-US resticbackup[2848]: open repository
Feb 02 22:46:36 FNF-Host-US-US resticbackup[2848]: lock repository
Feb 02 22:46:36 FNF-Host-US-US resticbackup[2848]: load index files
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: using parent snapshot edf4b49a
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: start scan on [/srv/samba /etc /home]
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: start backup on [/srv/samba /etc /home]
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.etckeeper not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/index not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/logs/HEAD not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/logs/refs/heads/master not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/objects/04/36a06219fd28340f1d5372a25320c32125d21e not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/objects/05/4d6d9921eead3a8a3c922e3262b55b2b38736f not found in the repository index; storing the file again
Feb 02 22:46:37 FNF-Host-US-US resticbackup[2848]: error: parts of /etc/.git/objects/05/d1ac834a0b26975f93fb834a5157f99293665e not found in the repository index; storing the file again
[…]
# many times this:
Feb 03 00:41:55 myhost resticbackup[2848]: error: parts of […] not found in the repository index; storing the file again
# many times this:
Feb 03 00:40:55 myhost resticbackup[2848]: error: tree fc0dc5ec754fe00e5489dd00e701b8eb0425423bb1a334aceb84b61c3c152579 is not known; the repository could be damaged, run `rebuild-index` to try to repair it
```

Trying to rerun the backup:
```
Feb 03 04:47:32 myhost resticbackup[8698]: counting files in repo
Feb 03 05:05:32 myhost resticbackup[8698]: building new index for repo
Feb 03 05:35:47 myhost resticbackup[8698]: [30:15] 43.96%  18000 / 40946 packs
Feb 03 05:35:47 myhost resticbackup[8698]: repository contains 18000 packs (140487 blobs) with 84.963 GiB
Feb 03 05:35:47 myhost resticbackup[8698]: processed 140487 blobs: 0 duplicate blobs, 0 B duplicate
Feb 03 05:35:47 myhost resticbackup[8698]: load all snapshots
Feb 03 05:35:48 myhost resticbackup[8698]: find data that is still in use for 10 snapshots
Feb 03 05:35:54 myhost resticbackup[8698]: [0:05] 100.00%  10 / 10 snapshots
Feb 03 05:35:54 myhost resticbackup[8698]: 579ad4> <data/161479f1> <data/7f49fd7c> 
[…]
630ce> <data/b77e446c> <data/996a2857> <data/c500f5fa> <data/f4957861> <data/e922aeb8> <data/7d592be0> <data/642d000a> <data/f9d07f08> <data/1b2bf475> <data/47580cae> <data/dbbcc3d4> <data/bc848cf4> <data/c966876d> <data/73204b11> <data/3b6832d2> <data/d9a6e916> <data/fe4d93ae> <da
ta/faf242d4> <tree/1f702d2a> <data/f5114db2> <data/bcdb10d3> <data/3de7e361> <data/f5ad8d63> <data/76fb3d21> <data/13c8bc14> <data/064caa7f> <data/e04757cb> <data/824e3c63> <data/11a03c12> <data/4ddf01f7> <data/5ccb5878> <data/d736013f> <data/da57c149> <tree/08710590> <data/2e1813f
6> <data/66b87311> <data/32cdf547> <data/8019f3c5> <data/6a1f3a4e> <tree/66f596b1> <data/f40c3196> <data/68a29e21> <data/ef13fe1c> <data/61524e73> <data/900bad27> <data/b66ccbf1> <data/6550dd6a> <data/27c89698> <data/25a1f624> <data/0e9c8e1a> <data/75fa8850> <data/ec568cdc> <data/7
8443566> <data/0083e102> <data/d95b6e3d> <data/ad5e9521> <data/51ea1cfc> <data/e6f8543d> <data/015c00cd> <data/d5272d11> <data/a402063a> <data/017bd10a> <data/a98f6e6c> <data/197206f2> <data/34522088> <data/ff3d6327> <tree/fe77bfbb> <data/c4243198> <data/43aad3e4> <data/4b72ee6e> <
data/5bd6e7d3> <data/0ab0f655> <data/0a1e8df9> <tree/0ce00904> <data/f1b69152> <data/f2e97e49> <data/8bb167ec> <data/f0a25240> <data/627b4c31> <data/33e4dafb> <data/9b359897> <data/991b2a0c> <data/a07ed579> <data/6e910f25> <data/e4e30308> <data/7a3b80df> <data/56615058> <data/e52a3
65e> <data/cb375405> <data/1ae3036b> <data/c779f2b8> <data/9fc6ec36> <data/2b3a97ea> <data/3d665c8d> <data/2e79af4f> <data/43641392> <data/3925bee5> <data/4dcf9b9f> <data/67d98294> <data/d73c41aa> <data/925c873e> <data/314f259f> <data/bf7f9eb4> <data/5ece4e3e> <tree/5425323e> <data
/9ad313fb> <tree/114efe21> <data/beb3234d> <data/45c6da2f> <data/8f8e60dd> <data/53832a10> <data/e6752f02> <data/6bac0d38> <data/ef113b20> <tree/7857dd3f> <data/9b806b0d> <data/1fcb7f5c> <data/806b9a35> <data/a0caaf50> <data/c4ae4ee8> <data/80866a71> <tree/a6c999ab> <tree/3e7a2b1c@
Feb 03 05:35:54 myhost resticbackup[8698]: Data blobs seem to be missing, aborting prune to prevent further data loss!
```

**Comment by MichaelEischer** [comment] 2021-02-05 18:43
@a-germain

> What do you recommend in terms of pruning? Weekly?

That mostly depends on how much unnecessary storage usage you can afford and on how quickly old data should be removed. But weekly sounds reasonable. 

@4001982248998

> I too have the same problem, on several machines. Running Backups to an S3 implementation and forgetting old backups afterwards. 

Please open a separate issue, I'd like to avoid mixing different prune problem reports unless we know that these are in fact caused by the same underlying issue. The repository must have been damaged _before_ the backup run from your log snippet. Did restic report any warnings during backup / prune before?

@borkd Please open a new issue too.

**Comment by MichaelEischer** [comment] 2021-02-07 13:49
I'm closing this issue as it looks like there's nothing left to do here.

**Closed by MichaelEischer** 2021-02-07 13:49 UTC
