### ISSUE TITLE
restic -r /srv/restic/ cat pack ... | file - keeps lock in repository

### ISSUE THREAD

**Issue by tyll** [restic/restic#1814] opened 2018-05-25 17:07 UTC
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

```
 export RESTIC_PASSWORD_FILE=/root/restic-password RESTIC_REPOSITORY=/srv/restic/
restic -r /srv/restic/ cat pack add624760238c24a7dbb01c4bdabfb7b8ab257df6361840b0b097b52de38d4b8  |file -
restic check
```

## What backend/server/service did you use to store the repository?

fs

## Expected behavior

repository should not be locked

## Actual behavior

```
restic check
password is correct
create exclusive lock for repository
Fatal: unable to create lock in backend: repository is already locked by PID 18982 on caledvwlch by root (UID 0, GID 0)
lock was created at 2018-05-25 19:03:16 (17.483158175s ago)
storage ID 31086398
```

## Steps to reproduce the behavior

Create repository with unreferenced packs and use one of the IDs like this:
```
 export RESTIC_PASSWORD_FILE=/root/restic-password RESTIC_REPOSITORY=/srv/restic/
restic -r /srv/restic/ cat pack add624760238c24a7dbb01c4bdabfb7b8ab257df6361840b0b097b52de38d4b8  |file -
restic check
```

## Do you have any idea what may have caused this?

Maybe `file` does not read all output of restic and therefore it does not properly terminate or there is just code missing to cleanup the lock.

## Do you have an idea how to solve the issue?

Remove the lock when `restic cat` terminates.

**Comment by fd0** [comment] 2018-05-25 17:12
restic is probably terminated by a signal because `file` just reads the first couple of bytes. You should also get a non-zero exit code.

This can be handled better, I think it's a bug.

**Comment by giskou** [comment] 2019-07-24 13:01
I have noticed that cat requires a lock.
The --no-lock flag seems to be ignored.
Isn't cat a read only operation?

**Comment by MichaelEischer** [comment] 2020-05-01 12:39
Closing this as it is a duplicate of #1466.

**Closed by MichaelEischer** 2020-05-01 12:39 UTC
Labels: misc: bug, state: need implementing
