### ISSUE TITLE
Please reduce your request rate from S3 backend causes intermittent failures in some restic commands

### ISSUE THREAD

**Issue by pypb** [restic/restic#1600] opened 2018-02-01 11:36 UTC
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?
```
export RESTIC_REPOSITORY="s3:ams3.digitaloceanspaces.com/mybucket/myhostname"
export AWS_ACCESS_KEY_ID=my_access_key
export AWS_SECRET_ACCESS_KEY=my_secret
```

I don't usually run restic with s3.connections=50, but it's much easier to reproduce when I do:

```
# /usr/local/bin/restic --password-file /root/.restic.pw check -o s3.connections=50
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 560f9822:
  ReadFull(<data/adf4bb71ca>): Please reduce your request rate.
Fatal: repository contains errors
```

Re-running with fewer connections:

```
# /usr/local/bin/restic --password-file /root/.restic.pw check -o s3.connections=5
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

If "Please reduce your request rate" is returned when trying to open the repo, restic will fail:

```
# /usr/local/bin/restic --password-file /root/.restic.pw rebuild-index --cleanup-cache
unable to open config file: Stat: Please reduce your request rate.
Is there a repository at the following location?
s3:ams3.digitaloceanspaces.com/mybucket/myhostname
```

## What backend/server/service did you use to store the repository?
DigitalOcean Spaces

## Expected behavior
restic should retry, perhaps even back off, but not fail when it recieves "Please reduce your request rate".

## Actual behavior
Intermittently restic commands like check, rebuild-index, prune (and perhaps other commands as well) fails. Possibly depending on which action actually triggers "Please reduce your request rate".

## Steps to reproduce the behavior
Running 'restic check' multiple times will usually trigger the problem, especially on larger data sets. Setting s3.connections to something high like 50 will trigger the problem more often.

## Do you have any idea what may have caused this?
Didn't see it when I started using restic with DigitalOcean but it has started occuring more often lately, possibly due to their load has increased as more users have joined.

## Do you have an idea how to solve the issue?
Make restic handle "Please reduce your request rate" in a clean way, perhaps back off. I saw a suggestion on AWS Developer Forum to introduce exponential backoff as a response to this message.

## Did restic help you or made you happy in any way?
ヽ(´▽`)/

**Comment by ifedorenko** [comment] 2018-02-01 12:39
Looks like a dup of #1559. I proposed fix #1560 but it has not been merged yet. I can update the fix to work with the latest master if you'd like to try it.

**Comment by pypb** [comment] 2018-02-01 13:59
Sounds good, I can give it a try!

**Comment by ifedorenko** [comment] 2018-02-01 16:30
I rebased  #1560 on the current master. Give it a try, let me know how it works for you.

**Comment by pypb** [comment] 2018-02-01 18:29
@ifedorenko I compiled restic from master with your pull request and I've done some quick tests.

I set up a new repo in the same bucket, did a backup of ~14GB using release restic 0.8.1. I got hundreds of "Please reduce your request rate" but the backup was successful.

On that repo I have then run _check_ and _rebuild-index_ multiple times with both the release version and the newly compiled one. 

I have to do more extensive tests, but so far it seems that the release version fails almost every time when running _check_ - with different 'pack does not exist' or 'not found in index' errors for each run. New version is successful every time.

_rebuild-index_ has so far been successful every run with both versions - but the new version is roughly three times quicker.

I'll do some more tests and post the results.

**Comment by ifedorenko** [comment] 2018-02-01 18:51
yeah, we've optimized reindex to eliminate ~2/3 of repository calls, so 3x faster is expected.

**Comment by fd0** [comment] 2018-02-24 18:52
Cool, thanks for the original report and the feedback! I'm going to close this issue, we've recently released 0.8.2 which includes the fixes proposed by @ifedorenko, so it should be fine.

The underlying issue is caused by the DigitalOcean Spaces service itself, see https://www.digitalocean.com/community/questions/rate-limiting-on-spaces

Please leave a comment so we can reopen this issue if it happens again and restic is unable to compensate!

**Closed by fd0** 2018-02-24 18:52 UTC

**Comment by pypb** [comment] 2018-03-03 21:54
I can confirm that 0.8.2 solves my problems. Backups are now much more stable.

Thanks guys!

**Comment by fd0** [comment] 2018-03-04 09:30
Cool, thanks for the feedback, I appreciate it!
