### ISSUE TITLE
Stuck upload to B2

### ISSUE THREAD

**Issue by shindere** [restic/restic#5066] opened 2024-09-18 21:02 UTC
This issue is opened in relation with [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082048).

Basically, I use BackBlaze to do backupus for several years now
using the same script and did never encounter any problem so far.
(Thanks, restic is a very cool tool which improves my life by making me
feelmuch more secure.)

A few days ago the backup script started to stale.

I checked with several `-v` that it is not actually sending anything.
Just that the time progresses indefinitely but the backup never completes.

I did remove a bunch of snapshots with prune, which freed 20GB but
even that got stale at the repacking
stage.

I don't think it's a problem with quotas because I didn't receive
any alert from BaclBlaze whereas they are enabled.

Happy to provide any additional info which could help.

**Comment by legrostdg** [comment] 2024-09-19 08:13
Hi, it would help to have complete the command line you used to be able to reproduce the bug, and maybe an extract of the end of the DEBUG_LOG you got (removing sensible information of course).

**Comment by shindere** [comment] 2024-09-21 09:54
Thanks. I notice that the bug has disappeared.

I am currently using another ISP so I don't know whether it's because of
that, or because there was another intermitent problem and the fact that
this works now from another ISP is just a coincidence.

What I can say, though, is that no update happened onmy system between
when it worked and when it started to not work.

I will be back to the "not-working" ISP at the beginning of next week
and will report back here if it still does not work.

It feels good to be able to backupu again!!

**Comment by shindere** [comment] 2024-10-07 20:44
The problem has re-appeared without anything having changed on the
machine.

I did capture a log but it's 241089 lines long and, with just a braille
device, I find it super hard to find the relevant part.

Any hint on a text to lookfor and/or a way to sanitize the log before
sharing?

**Comment by shindere** [comment] 2024-10-13 06:45
One more observation is that the behaviour seems to depend on which IP
address is used.

Indeed, when connecting from home (fixed IP) the command gets stale,
while when using another network, say the one ofmy mobile phone (which
is itself not connected to my home network, Imade sure of that by
disconnectingthe wireless and turning off my router), fromthere the
backup works.

**Comment by MichaelEischer** [comment] 2024-10-16 20:30
This issue reminds me a lot of https://github.com/restic/restic/issues/3636 . There the problem was that one of the backblaze servers ended up in a DNS blocklist. The b2 backend then unfortunately kept retrying uploads endlessly.

The most interesting parts of the debug log are probably the parts where restic sends the requests to the B2 servers.
If you search for lines that include `logger.(*Backend).Save` then the corresponding http request should be logged a few lines later.

An alternative which you can try is to use the S3 backend to upload to B2. It provides better error handling and might also just avoid the issue that block your B2 backups. B2 also provides an S3 API (see the Warning box right at the start of the [B2 section in the restic docs](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2) ). See the [S3 backend docs](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#s3-compatible-storage) for further details on setting up the S3 backend.

The necessary settings for S3 using B2 are something like the following:
```
export RESTIC_REPOSITORY=s3:https://s3.eu-central-003.backblazeb2.com/bucket-name
export AWS_ACCESS_KEY_ID=id of the access key with read-write permissions
export AWS_SECRET_ACCESS_KEY=secret part of the access key
```

**Comment by MichaelEischer** [comment] 2024-10-28 19:13
Is there anything left to do here from our side? Or can we close the issue?

**Comment by shindere** [comment] 2024-10-29 09:47
Michael Eischer (2024/10/28 12:13 -0700):
> Is there anything left to do here from our side? Or can we close the
> issue?

Thanks for asking and sorry I didn't share the conclusion spontaneously.

What fixed the problem was to stop the DSL model for 10 minutes and
restart it.

The 10 minutes do matter as I did restart the modem before but without
the 10 minutes break.

I think this issue can be closed, as well as the associated Debian bug
report.

Thanks!

**Closed** 2024-10-30 20:27 UTC
Labels: state: need feedback, backend: b2
