### ISSUE TITLE
A few stack traces over a flaky internet connection (gateway down for a few minutes)

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1226] opened 2017-09-10 07:17 UTC
## Output of `restic version`
$ restic version
restic 0.7.1
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?
restic with sftp backend

## What backend/server/service did you use?
sftp
internet connection was flaky at points during the backup
last time this happened, restic check showed problems and restic prune died
next time I will capture more information

```
$ $RESTIC -r sftp...
subprocess ssh: Timeout, server example.net not responding.
error saving preliminary index: Close: EOF
panic: Close: EOF

goroutine 246446 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420b3fb30, 0xc213e0, 0xc420014498, 0x101a45, 0x1eeba2, 0x1f9e8fdfc00000, 0xc424cee000, 0x1eeba2, 0x26a000, 0x0, ...)
        src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
        src/restic/archiver/archiver.go:239 +0x3a4

$ $RESTIC -r sftp..
error saving preliminary index: Close: EOF
panic: Close: failed to send packet header: write |1: file already closed

goroutine 264823 [running]:
restic/archiver.(*Archiver).saveChunk(0xc423c9cd70, 0xc213e0, 0xc420014498, 0x33645c, 0x394799, 0x1a90b201300000, 0xc426eae000, 0x394799, 0x3c0000, 0x0, ...)
        src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
        src/restic/archiver/archiver.go:239 +0x3a4

$ $RESTIC -r sftp...
subprocess ssh: Timeout, server example.net not responding.
unable to refresh lock: OpenFile: EOF
unable to refresh lock: cmd.Wait: exit status 255
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
error saving preliminary index: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: failed to send packet header: write |1: file already closed
panic: OpenFile: failed to send packet header: write |1: file already closed

goroutine 98 [running]:
restic/archiver.(*Archiver).dirWorker(0xc4226d5d60, 0xc213e0, 0xc4200a21a8, 0xc421facc00, 0x0, 0xc421fa9c80)
        src/restic/archiver/archiver.go:405 +0xcbf
created by restic/archiver.(*Archiver).Snapshot
        src/restic/archiver/archiver.go:713 +0x68b

```

**Comment by LaszloHont** [comment] 2017-09-12 04:55
restic check shows:

```
pack C: not referenced in any index
pack B: not referenced in any index
pack A: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors
```

**Comment by fd0** [comment] 2017-09-13 12:17
Thanks for the report. This is a duplicate of #353 and therefore I'm closing this issue here. Please subscribe over at #353 to be notified of any progress.

You should be able to re-run all operations, and the final run of `prune` will clean up the remaining bits and pieces.

**Closed by fd0** 2017-09-13 12:17 UTC
