### ISSUE TITLE
Unchanged snapshots take longer than actual backups for S3

### ISSUE THREAD

**Issue by TamalSaha** [restic/restic#882] opened 2017-03-14 09:17 UTC
Hi,
I noticed an interesting behavior for S3 backups. I backup a folder to S3. Then run the same command without any changes to underlying files. The second time seems to take longer than the original backup. I was expecting that since the second time did not backup any files, it will be faster.

```sh
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode/appctl
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode/appctl]
scanned 592 directories, 3049 files in 0:00
[0:51] 100.00%  1.058 MiB/s  53.944 MiB / 53.944 MiB  3641 / 3641 items  0 errors  ETA 0:00 
duration: 0:51, 1.05MiB/s
snapshot 160a918d saved

$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode/appctl
enter password for repository: 
using parent snapshot 160a918d
scan [/home/tamal/go/src/github.com/appscode/appctl]
scanned 592 directories, 3049 files in 0:00
[1:43] 100.00%  536.299 KiB/s  53.944 MiB / 53.944 MiB  3641 / 3641 items  0 errors  ETA 0:00 
duration: 1:43, 0.52MiB/s
snapshot 876ab435 saved
```

Is this expected?

**Comment by middelink** [comment] 2017-03-14 16:35
Not really, only if reading back files from S3 is exceptionally slow. (it needs to read 1 index and at least 592 tree blobs and write hardly anything (new index, new snapshot) provided the trees really did not change)

**Comment by fd0** [comment] 2017-03-14 19:47
The problem here is that all metadata is read from s3, there's no local cache yet. So for each directory, there are two calls to the s3 endpoint (although #883 will probably remove one), which (depending on the latency to the repo and the data structure (dirs vs files)) make take some time and also be slower than the initial backup.

You can try using `backup --force` and report back if that is faster (it should be much faster).

**Comment by TamalSaha** [comment] 2017-03-14 21:14
@fd0, I tried with --force. Backup was much faster with --force.

```bash
# First backup in new repo:
$ ./restic -r s3:s3.amazonaws.com/tigerworks1/t4 backup ~/go/src/github.com/appscode/appctl
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode/appctl]
scanned 592 directories, 3073 files in 0:00
[0:42] 100.00%  1.283 MiB/s  53.868 MiB / 53.868 MiB  3665 / 3665 items  0 errors  ETA 0:00 
duration: 0:42, 1.28MiB/s
snapshot a51e6d42 saved

# Rerun with any change to files
$ ./restic -r s3:s3.amazonaws.com/tigerworks1/t4 backup ~/go/src/github.com/appscode/appctl
enter password for repository: 
using parent snapshot a51e6d42
scan [/home/tamal/go/src/github.com/appscode/appctl]
scanned 592 directories, 3073 files in 0:00
[2:01] 100.00%  455.876 KiB/s  53.868 MiB / 53.868 MiB  3665 / 3665 items  0 errors  ETA 0:00 
duration: 2:01, 0.44MiB/s
snapshot bcc415b9 saved

# Rerun without any chnge to files and use --force
$ ./restic -r s3:s3.amazonaws.com/tigerworks1/t4 backup ~/go/src/github.com/appscode/appctl --force
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode/appctl]
scanned 592 directories, 3073 files in 0:00
[0:01] 100.00%  49.724 MiB/s  53.868 MiB / 53.868 MiB  3665 / 3665 items  0 errors  ETA 0:00 
duration: 0:01, 28.72MiB/s
snapshot d4fb9163 saved
```

**Comment by fd0** [comment] 2017-03-16 11:02
Usually, restic tries to find an older snapshot of the same set of files/dirs your saving now. If it finds one, it incrementally loads the old file names and timestamps (in the `tree` blobs) from the repository. For each file it encounters that was already present in the last snapshot, it checks if the timestamp has been modified. If the timestamp is the same, restic copies the list of blobs from the old snapshot and moves on to the next file.

When `--force` is present, restic won't search for a previous snapshot and will open and re-read each file. If the files are already present in the disk cache in memory, this is usually fast. It then computes the list of blobs that the file consists of and uploads blobs that are not yet present in the repo. For files that have been saved before, all blobs are already present, so very few data is transmitted at all. For a very fast machine, reading and computing the list of blobs is very fast.

The problem is that all tree objects in the former case are fetched from the repo on demand, there's no local metadata cache (yet). So depending on the latency to the remote repo the access times for the tree objects sum up to quite a lot. That's what you're observing, and that's what makes your backup slow.

**Comment by fd0** [comment] 2017-05-14 20:21
So I'm going to close this issue for now, #29 tracks adding a metadata cache. Until that is implemented you can use `backup --force`. Please feel free to add further comments.

**Closed by fd0** 2017-05-14 20:21 UTC
Labels: feedback needed, question
