### ISSUE TITLE
"restic restore -v " has to little info

### ISSUE THREAD

**Issue by robfordww** [restic/restic#3946] opened 2022-10-01 17:33 UTC
I was quite surprised with my first restore that the feedback from the `restic recover` command even with the `-v` flag, is quite sparse.

```
restic.exe restore latest -v -r sftp:sftp@10.0.0.20:/sftp/ -i test -t ..\testrecover
enter password for repository:
repository 408f8340 opened (repository version 2) successfully, password is correct
restoring <Snapshot 6b0ca508 of [C:\Users] at 2022-09-30 20:30:53.7603083 +0200 CEST by COMP\username@Comp> to ..\testrecover
```

There is no confirmation that the restore was successful.  One cannot rule out that the process was killed, so a "finished" message would be nice.  Further, when using the `-v` flag, I would expect it to show the filenames it actually recovers, but it does not. That would be especially useful when applying the `-i` flag.

**Comment by MichaelEischer** [comment] 2022-10-02 20:08
Duplicate of #426.

restic will complain if there was an issue while restoring a backup.

**Closed by MichaelEischer** 2022-10-02 20:08 UTC
