### ISSUE TITLE
Restic hang in check

### ISSUE THREAD

**Issue by 2cadz** [restic/restic#1998] opened 2018-09-13 09:32 UTC
Output of `restic version`
--------------------------

```
debug enabled
restic 0.9.2 (v0.9.2-110-g6bc99ce4) compiled with go1.10.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
RESTIC_PASSWORD_FILE=/etc/restic/restic_pwd.txt
RESTIC_REPOSITORY=sftp:backup:/ovh-backup/vanaheim/restic/myhost
# ./restic check --cleanup-cache
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

SFTP

Expected behavior
-----------------

Ending of check command without error :-)

Actual behavior
---------------

```
debug enabled
using temporary cache in /tmp/restic-check-cache-631445418
repository 802cfbf3 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-631445418
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
Processus arrêté
```

Steps to reproduce the behavior
-------------------------------

`GSOC=10 ./restic check --cleanup-cache`

Do you have any idea what may have caused this?
-----------------------------------------------

I have been using Restic Backup for a few months on several machines and everything is working fine except for one, or the 'check' operation will fail. I suspected a moment memory pb because its use increases with the progress of the 'check'. So I added the intruction 'GSOC = 10' before the execution of the command but that did not solve the pb, and the reading of the logs does not look in this direction.
The only difference with other machines is the contents of the backup, which is not indicated by the '--files-from' parameter but by '--one-file-system'.

I generated the log file with the command:

`GSOC=10 DEBUG_FILES = * ./restic check --cleanup-cache 2> ../debug_check.log`

but the file is very big, i put a link : https://mon-partage.fr/f/9uNTqvHO/

Do you have an idea how to solve the issue?
-------------------------------------------

No

Did restic help you or made you happy in any way?
-------------------------------------------------

Normaly yes :-)

**Comment by 2cadz** [comment] 2018-09-20 06:10
Hi,
So I do not really know what happened, but a re-creation of the repository solved the question. I closed the issue.
Regards

**Comment by fd0** [comment] 2018-09-20 14:14
Hm, interesting. What is `GSOC=10`? Do you maybe mean `GOGC=10` to make the garbage collector more aggressive so that restic uses less memory?

I think restic was still at work, this step in the `check` process unfortunately has no progress output (yet). Did you see any network traffic?

**Comment by 2cadz** [comment] 2018-09-24 06:34
> Hm, interesting. What is GSOC=10? Do you maybe mean GOGC=10 to make the garbage collector more aggressive so that restic uses less memory?

yes, a mispelling

>I think restic was still at work, this step in the check process unfortunately has no progress output (yet). Did you see any network traffic?

I did not check if there was network traffic, but it seems to me that the process is stopped.

Today the 'crash' is reproduced (with 8 snapshots in the repo), so I'll be able to check that (tomorrow)

**Comment by fd0** [comment] 2018-09-25 11:18
I'm not sure what happens here, but I just had another look at the log file:
```
sftp/sftp.go:77 sftp.startClient.func2  13  ssh command exited, err signal: killed
```

This is odd.

In addition, I don't know what the last line in your output means, I've never seen this error before:
```
Processus arrêté
```

I can translate that (with the remains of the bit of French I learned in school) as "Process stopped", that seems to be a message from your shell. It's surely not something restic prints...

You mentioned a 'crash', what you do mean by that? A stack trace?

**Comment by fd0** [comment] 2018-09-25 12:35
Hm, interesting.

**Comment by fd0** [comment] 2018-09-25 12:37
Ok, still no idea. The "err signal: killed" means the OS (Linux) has killed the SSH process, which is different from when a timeout or network interruption occurs. Usually, there's an entry in the kernel log about it...

I'll close this for now, please let us know when it occurs again, and please feel free to add further comments. Thanks!

**Closed by fd0** 2018-09-25 12:37 UTC
Labels: feedback needed

**Comment by 2cadz** [comment] 2018-09-28 05:43
Hi
I know a little more now, and my initial idea was the good one. It is a memory consumption pb, Restic is executed in a container and the hypervisor kills it because it consumes too much memory.

My question then becomes, how to limit memory usage when Restic run a check?

**Comment by fd0** [comment] 2018-09-28 11:12
You can't. I haven't found the cause yet, but it feels to me restic uses too much memory in some circumstances. You can try making the Go runtime garbage collector a lot more aggressive by setting `GOGC=20` (or even 10), but that's about it for now. Did you try with the corrected environment variable yet?
