### ISSUE TITLE
Restic can fail with `Fatal: failed to refresh lock in time` on slow connections

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#4199] opened 2023-02-09 22:32 UTC
Output of `restic version`
--------------------------
0.15.1

Expected behavior
-----------------
Backups should also be possible over a slow network connection.

Actual behavior
---------------
When uploading over a slow network connection, it is possible that a backup or similar operation fails to refresh lock files within 22.5 minutes and fails with `Fatal: failed to refresh lock in time`. This has been reported on IRC and at least at https://github.com/restic/restic/issues/4157#issuecomment-1408669114 .

Steps to reproduce the behavior
-------------------------------
Use a very slow network, then wait for half an hour...

Do you have any idea what may have caused this?
-----------------------------------------------
restic only allows a limited number of concurrent backend connections. Once all are used for uploading pack files, then a lock file refresh is queued behind them. For a slow connection, it is quite possible that a 16MB pack file (with 5 parallel connections) takes longer than half an hour to upload.

Further fallout from #3569.

Do you have an idea how to solve the issue?
-------------------------------------------
Lock file refreshes should be able to bypass the connections limit.

**Comment by gallofeliz** [comment] 2023-02-10 11:19
Hello,

I've just switched from OVH(swift) because of excessive problems to B2 with S3 api. I've the same problem

```
Fatal: failed to refresh lock in time
error: no result
error: no result
error: no result
error: no result
Fatal: unable to save snapshot: context canceled
```

I've tryed twice and same problem. I will try to find an option to make 1 operation by 1, my upload limit is 50KB.

Regards

**Comment by jwiegley** [comment] 2023-02-16 17:24
I have this same problem when uploading to B2 when I set `--limit-upload 100`.

**Comment by gallofeliz** [comment] 2023-02-18 10:23
Hello,

A workaround is to limit concurrent uploads, or what I did and it works (but increase number of files I suppose) is to reduce pack size : RESTIC_PACK_SIZE=4

This is a workaround with risk to increase (maybe) GetObjectsList calls and so cost, and updating lock should not be in this limitation or use one of the concurrent limit dedicated to itself (just avoid to put 1 !)

Regards

**Comment by GottemHams** [comment] 2023-02-22 17:38
Instead of simulating a slow network, you can also just send a `STOP` signal to restic (`killall -STOP restic`). This pretty much suspends the entire process without killing it, so it can be resumed right where it left off (`killall -CONT restic`). I usually do this when I need to pause the backup to do some other disk intensive stuff, which worked fine until the PR you mentioned was merged. ;_;

**Comment by jwiegley** [comment] 2023-02-22 18:17
@GottemHams That's a fantastic suggestion, thank you!! I will use this.

For my B2 problems above, I switched very easily to the S3 endpoints and now the problem is gone for me.

**Comment by MysticalGrape** [comment] 2023-03-04 09:54
I had the same issue on `0.15.1`.  Backup was failing after around 25-30 minutes.

```
using parent snapshot 197c0a63
Fatal: failed to refresh lock in time
Fatal: unable to save snapshot: context canceled
```

I downgraded to `restic_0.14.0_linux_amd64` and backup completed just fine.  

```
repository f8cb7016 opened (repository version 2) successfully, password is correct
using parent snapshot 197c0a63

Files:         722 new,     0 changed, 26007 unmodified
Dirs:            2 new,     5 changed,   121 unmodified
Added to the repository: 3.273 GiB (3.269 GiB stored)

processed 26729 files, 125.233 GiB in 2:54:18
snapshot 2ea0e150 saved
```

ssh config had:
```
                ServerAliveInterval 15
                ServerAliveCountMax 3
```

Server was a storage box in Hetzner (sftp) and I was backing up to it from Australia (ping shows ~274 ms).

**Comment by nicolasfara** [comment] 2023-03-06 08:08
I have the same problem as @MysticalGrape. I have not tried to downgrade to `0.14.0` but noticed that on slow connections the backup fails with the same error. I'm using Backblaze as storage. Do you have any fixes or workaround? I have also tried the @gallofeliz suggestion but with no result.

**Comment by bzed** [comment] 2023-03-13 21:29
On one of my VMs I'm seeing the same issue, but it should be able to push 1gbit/s to B2 - and its an issue I've only seen recently, but I think that the last restic update made things better.

**Comment by MichaelEischer** [comment] 2023-03-26 08:36
> Notice the `RequestTimeTooSkewed` indications. Does this mean the request was queued and had to wait to long or rather that the whole upload just took too long? I guess there's some kind of request time header in the HTTP request?

That depends on which timestamp Wasabi uses to check the upload against. I'm somewhat sure that it's the moment at which the first part of the request arrives at Wasabi. On the restic side, the connection limit applies before creating the request, so restic would use the timestamp right from the moment when it starts to send the request. So a time skew would have to be introduced somewhere during the upload. However, the most frequent cause of skewed timestamps are not synchronized clocks. Have you check that the hosts clock is correct? Although I have to admit that your workaround suggests that it has something to do with how long the upload takes to complete...

**Comment by rsnitsch** [comment] 2023-03-29 10:13
I just encountered the same error while restoring a huge snapshot. (Maybe due to a scheduled backup operation that got started in parallel.)

**Comment by fedxyz** [comment] 2023-03-31 09:57
Unfortunately I have the same issue, I can't backup on some pc because the connection is slow.
The only workaround is to use 0.14.0 version.

IMHO this has to be marked as a bug: if a backup program can't backup data in some conditions this is bug, it is its main purpose.

**Comment by carns** [comment] 2023-04-03 01:52
It sounds like there are a variety of conditions that could trigger this error message.  I had been pondering the problem descriptions and solutions that have been discussed here, only to discover that my problem more closely matched #4274 (I was running an initial restic backup in a powershell script on a windows 11 laptop that was suspending itself before the backup could complete).  I didn't realize that the laptop suspending itself would triggering that error message, so I thought it was hitting some other problem.

**Comment by ctonsing** [comment] 2023-04-06 14:36
We are also observing this same error. Restic v 0.15.1 fails on a slow connection with a rather small backup of about 600MB after about 22 minutes... I would also request you to treat this as a bug please.

**Comment by ctonsing** [comment] 2023-04-20 06:57
Hi guys, is there maybe any news on this issue?

**Comment by MichaelEischer** [comment] 2023-04-23 10:33
https://github.com/restic/restic/pull/4304 should fix most of the issues reported here. If the host suspends while a backup is running, this will still cause the operation to fail, please refer to issue #4262 for that case.


> Addendum 2: No, the restore command has definitely stopped working. Task manager confirms this. restic fails to exit, though. I needed to kill the process by pressing CTRL-C.

@rsnitsch If you're running an non-Windows OS, then please send a SIGQUIT signal to restic or press Ctrl+/ to send the signal. This causes the go runtime to print a stacktrace and crash restic afterwards.

> We are also observing this same error. Restic v 0.15.1 fails on a slow connection with a rather small backup of about 600MB after about 22 minutes... I would also request you to treat this as a bug please.

How slow is the network connection?

**Comment by fedxyz** [comment] 2023-04-23 10:59
Hi @MichaelEischer ,

can you clarify what you wrote in the PR #4304 ? 

I mean the part :

> However, large uploads over slow connections can cause the lock refresh to be stuck behind the large uploads and thus time out.

Because this is the main point of this issue.

Thanks

**Comment by MichaelEischer** [comment] 2023-05-05 21:04
Can someone test whether #4304 solves the problem with slow uploads?

**Comment by MysticalGrape** [comment] 2023-05-06 00:25
Looks like the fix worked. I added my results to https://github.com/restic/restic/pull/4304

**Comment by virtadpt** [comment] 2023-05-11 19:49
Happening with v0.15.2 as well (upgraded about two weeks ago).  Backblaze (B2).  Happens on only one of my filesystems, though.

**Closed** 2023-05-13 19:40 UTC
Labels: type: bug, category: backend

**Comment by JsBergbau** [comment] 2023-05-16 10:56
Just wanted to add that the error "Fatal: failed to refresh lock in time" just occured with 0.15.1 when pausing via "CTRL + Z" and then resuming almost 2 hours later via `fg 1`.

```
Fatal: failed to refresh lock in time
error: no result
error: no result
error: no result
error: no result
Fatal: unable to save snapshot: context canceled
```
Maybe this is already solved in 0.15.2 if not this method may be helpful to reproduce the issue.

I am now doing an index-rebuild and then restarting the backup and pruning afterwards.

**Comment by MichaelEischer** [comment] 2023-05-16 18:00
> Just wanted to add that the error "Fatal: failed to refresh lock in time" just occured with 0.15.1 when pausing via "CTRL + Z" and then resuming almost 2 hours later via `fg 1`.

That behavior is currently by design, see https://github.com/restic/restic/issues/4262 .

> I am now doing an index-rebuild

There is no need to rebuild the index.

**Comment by virtadpt** [comment] 2023-05-16 18:21
I managed to work around the problem with `-o b2.connections=45`.  Interestingly, the other file systems (everything but /opt) still use `-o b2.connections=55` and haven't shown the same problem.

**Comment by JsBergbau** [comment] 2023-05-16 18:45
> There is no need to rebuild the index.

Technically you're right. Since restic was running about 3 hours before, rebuilding the index saved a lot of time, at least I thought so. Because the added blobs are then in the index and then reused and so a lot of time is saved in the compression step. Or am I wrong and this was really unnecessary and didn't save time for the `backup` command?

**Comment by MichaelEischer** [comment] 2023-05-18 14:52
> Because the added blobs are then in the index and then reused and so a lot of time is saved in the compression step. Or am I wrong and this was really unnecessary and didn't save time for the `backup` command?

`backup` uploads intermediate indexes at least every 10 minutes.
