### ISSUE TITLE
Disk unmounts at the end of backup process [macOS]

### ISSUE THREAD

**Issue by iansowinski** [restic/restic#1981] opened 2018-09-04 09:14 UTC
Hey,

I try to backup my archive external hdd (1tb WD, usb 3) to another external hdd (3tb WD, usb 3). I tried it e few times now, but scenario is always the same:

Around 70-80% (all files have around 700GB) disk unmounts (as /Volumes/backup), and mounts again (as /Volumes/backup 1). Backup instead of stopping still copies files to /Volumes/backup (which is now memory of my internal hdd) and errors about missing files (from old /Volumes/backup which is now /Volumes/backup 1) start to appear. Then it stops and I have most of the files on real backup disk and rest on the /Volumes/backup directory on my internal hdd.

Any clues? I changed disksleep via pmste but id doesn't help.

[edit]
restic 0.9.2
macOS 10.12.6

**Comment by dimejo** [comment] 2018-09-04 09:33
restic doesn't do any mounting on it's own. This seems to be an [issue with macOS](https://discussions.apple.com/thread/7732836).

**Comment by fd0** [comment] 2018-09-08 15:45
This is probably caused by the OS, restic does not handle mounting/umounting any disks. I don't see what we can do here, so I'm closing the issue for now.

**Closed by fd0** 2018-09-08 15:45 UTC
