### ISSUE TITLE
Fatal: unable to save snapshot: node "photo.dng" already present

### ISSUE THREAD

**Issue by ldvc** [restic/restic#2454] opened 2019-10-26 21:20 UTC
Output of `restic version`
--------------------------
Restic installed using `brew`
```bash
$ restic version
restic 0.9.5 compiled with go1.13.1 on darwin/amd64
```
How did you run restic exactly?
-------------------------------
```bash
jdoe@host $ restic -r /Volumes/T5/backup/photos --verbose backup /Volumes/photo --exclude-file=/Users/jdoe/excludes.txt                   
open repository
repository e366042e opened successfully, password is correct
lock repository
load index files
start scan on [/Volumes/photo]
start backup on [/Volumes/photo]
scan: lstat /Volumes/photo/2010/2010-12-31/misc_2010-001.dng: no such file or directory
scan: lstat /Volumes/photo/2010/2010-12-31/misc_2010-006.dng: no such file or directory
scan: lstat /Volumes/photo/2010/2010-12-31/misc_2010-027.dng: no such file or directory
error: lstat /Volumes/photo/2010/2010-12-31/misc_2010-001.dng: no such file or directory
error: lstat /Volumes/photo/2010/2010-12-31/misc_2010-006.dng: no such file or directory
error: lstat /Volumes/photo/2010/2010-12-31/misc_2010-027.dng: no such file or directory
Fatal: unable to save snapshot: node "misc_2010-002.dng" already present
```
I'm using env var `RESTIC_PASSWORD_FILE=/Users/jdoe/.restic/t5.photos.repo`

And the exclude file contains:
```bash
$ cat excludes.txt
*@SynoResource
@eaDir
*.vsmeta
.DS_Store
```
So restic is running on my mac running MacOS 10.14.6 (18G95). I've mounted some shared folders from my Synology NAS on the mac (i.e. /Volume/photo) which I'm trying to backup on my local SSD external drive.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local (external SSD)

Expected behavior
-----------------
Files and folders being saved (encrypted) on my external SSD.

Actual behavior
---------------
Restic crash during the backup task, can't go further.

Steps to reproduce the behavior
-------------------------------
I've re-run several time and restic crashed on the same file. I have suspected that the file could be duplicated on the NAS which would trigger this behavior:

```bash
jdoe@nas:~$ find /volume1/photo -iname "misc_2010-002.dng"
/volume1/photo/2010/2010-12-31/@eaDir/misc_2010-002.dng
/volume1/photo/2010/2010-12-31/misc_2010-002.dng
```
In order to circumvent this, I added the `@eaDir` pattern in the `excludes.txt` file without any improvement (is this pattern correct?).

Do you have any idea what may have caused this?
-----------------------------------------------

c.f. previous section.

Do you have an idea how to solve the issue?
-------------------------------------------
Well, no. But I can do some further debug if needed!

Did restic help you or made you happy in any way?
-------------------------------------------------
Just started to use restic but I would like to thanks developers for all the work! It's very easy to start a backup task with this software.

**Comment by cdhowie** [comment] 2019-10-29 18:17
> I have suspected that the file could be duplicated on the NAS which would trigger this behavior:

A duplicate file shouldn't cause this; restic should just deduplicate the contents in the backup.

It sounds more like restic is trying to create the same filename twice _in the same directory_ within the backup, which should not happen.

**Comment by rawtaz** [comment] 2019-11-17 23:42
@ldvc Thanks for being elaborate in your description of the issue.

I can confirm that your `@eaDir` line in the exclude file should indeed take effect. I did some testing and it does take effect for me.

Which version of macOS did you run this on? What filesystem is `/Volumes/photo`?

Also, is this a repo that you have been running backups to for a while? Can you try to do a `restic check` on it?

**Comment by rawtaz** [comment] 2019-11-17 23:54
I tried to reproduce the problem by touching those two files in a similar directory structure:

~~~
$ find . -ls|grep -v repo
.
./excludes.txt
./photo
./photo/2010
./photo/2010/2010-12-31
./photo/2010/2010-12-31/@eaDir
./photo/2010/2010-12-31/@eaDir/misc_2010-002.dng
./photo/2010/2010-12-31/misc_2010-002.dng
~~~

Backup works fine for me:
~~~
$ ~/go/bin/restic -r repo backup photo
enter password for repository: 
repository 9afcfe56 opened successfully, password is correct
created new cache in /Users/rawtaz/Library/Caches/restic

Files:           2 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 382 B

processed 2 files, 0 B in 0:00
snapshot d38b8321 saved
~~~

Restic version:
~~~
$ ~/go/bin/restic version
restic 0.9.5 (v0.9.5-46-g604b18aa) compiled with go1.12.7 on darwin/amd64
~~~

For lack of better ideas I'm thinking check your repo using `restic check` and maybe also `restic rebuild-index`.

**Comment by rawtaz** [comment] 2019-11-18 00:19
Possibly related/same issue: #1866 - can you check your filesystem to see if it has any errors @ldvc?

**Comment by MichaelEischer** [comment] 2020-04-27 20:11
@ldvc Do you still have this issue? Are there any duplicate filenames in `ls -la /Volumes/photo/2010/2010-12-31`? Can you open the files for which lstat fails?

**Comment by ldvc** [comment] 2020-05-12 06:41
Sorry for my unresponsiveness.

@rawtaz:

>Which version of macOS did you run this on?

Mojave (`10.14.6`)

>What filesystem is /Volumes/photo?

smbfs from what I see using following command:
```
$ mount | grep nas
//jdoe@nas._smb._tcp.local/photo on /Volumes/photo (smbfs, nodev, nosuid, mounted by jdoe)
```

@MichaelEischer: I still have the issue but I may have find the culprit (without really understand why). Here's the latest exec of `restic`:

```
$ restic -r /Volumes/T5/backup/photos --verbose backup /Volumes/photo --exclude-file=/Users/jdoe/excludes.txt
open repository
lock repository
load index files
using parent snapshot cf354fee
start scan on [/Volumes/photo]
start backup on [/Volumes/photo]
scan: lstat /Volumes/photo/2004/Nokia/Vidéo000.3gp: no such file or directory
error: lstat /Volumes/photo/2004/Nokia/Vidéo000.3gp: no such file or directory
[...]
scan finished in 576.076s: 45574 files, 303.503 GiB
uploaded intermediate index 35a05d4b
uploaded intermediate index 73b8c652

Files:          12 new,     6 changed, 45556 unmodified
Dirs:            0 new,     1 changed,     0 unmodified
Data Blobs:      1 new
Tree Blobs:      2 new
Added to the repo: 91.783 KiB

processed 45574 files, 303.503 GiB in 19:05
snapshot d51f05af saved
```

Files seems to have weird characters in the name, on the NAS I can access file:
```
jdoe@nas:/volume1/photo/2004/Nokia$ ll *Vid*000*
-rwxr-x--- 1 jdoe family 93148 Jul 29  2015 Vidéo000.3gp

jdoe@nas:/volume1/photo/2004/Nokia$ ls -1 *Vid*000* | od -c
0000000   V   i   d   e 314 201   o   0   0   0   .   3   g   p  \n
0000017
```

While on the mac, I can't:
```
jdoe@mac $ ls -lh /Volumes/photo/2004/Nokia/*Vid*000*
ls: Vidéo000.3gp: No such file or directory
```

Might be a weird behavior of MacOS/Synology smbfs...

**Comment by MichaelEischer** [comment] 2020-05-15 19:05
That looks like a issue with normalization of unicode filenames (I think a file listing displays the variant stored on disk, but when accessing a file the file name could be (de?)normalized).

Is `ls -la .` able to show the file stats? The `node "..." already present` error seems to be gone. And in case a file is inaccessible, then it's expected that restic complains about that file.

**Comment by zanderson-aim** [comment] 2020-12-28 18:25
Incase anyone has this issue on a Windows machine, I got that error with a folder that had a space at the end and a folder that had the same name without the space. Windows Explorer would also complain about this. Solution was rename/delete the folder with the space at the end. 
```
"folder"
"folder "
```

**Comment by MichaelEischer** [comment] 2020-12-28 20:39
@ldvc Do you still get the `node "..." already present`? If no then I'd like to close this issue. The `no such file or directory` cases from your last reply are a problem of the underlying filesystem and nothing restic should try to work around.

@zanderson-aim Please have a look at #1866.

**Comment by zanderson-aim** [comment] 2020-12-28 20:50
@MichaelEischer Yep that would be it. In my case it was Quickbooks / User who created a company name with a space at the end, and all the files it generates after have it. Removing it worked for me, but happy to see there is a fix planned for the future.

**Comment by seqizz** [comment] 2021-01-07 09:19
Just wanted to note: I just saw a similar error, which was caused by a weird duplicate file: 2 hardlinks with same name, under same folder, going to same inode. I didn't know such a thing was possible, but looks like GlusterFS is something different..

**Comment by MichaelEischer** [comment] 2021-07-10 22:49
Now that we have exit code 3 for backups in which not all source files could be read, we could also turn this into a warning and let the backup continue. However, this error usually indicates a file system problem which should be fixed. So I'm still leaning towards just closing this issue.

@seqizz Did the duplicate file fix itself later on?

**Comment by seqizz** [comment] 2021-07-11 04:26
> @seqizz Did the duplicate file fix itself later on?

We manually deleted a hardlink, which shouldn't have been there anyway 👍

**Comment by rawtaz** [comment] 2022-01-02 17:42
Closing this as it's pretty much the same thing as #1866 - please refer to that issue for following up on this.

**Closed by rawtaz** 2022-01-02 17:42 UTC
Labels: state: need feedback
