### ISSUE TITLE
environment variable RESTIC_EXCLUDE_FILE

### ISSUE THREAD

**Issue by Framsfex** [restic/restic#4221] opened 2023-02-23 18:07 UTC
Output of `restic version`
--------------------------

restic 0.15.1 compiled with go1.19.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I would like to have an additional environment variable RESTIC_EXCLUDE_FILE which matches the option 
restic backup --exclude-file ...

What are you trying to do? What problem would this solve?
---------------------------------------------------------

So far I have to use this shell wrapper:
`
root@fex:/opt/s3tik/bin# cat restic-backup
#!/bin/bash
exec restic backup -v --exclude-file $RESTIC_EXCLUDE_FILE "$@"
`

**Comment by Enrico204** [comment] 2023-09-05 21:17
Uhm, the question is: what are you trying to do? Why your shell wrapper is not sufficient?

**Comment by Framsfex** [comment] 2023-09-08 09:19
An extra shell wrapper is always a crude workaround.

There are already various environment variables matching command line options:
https://restic.readthedocs.io/en/stable/040_backup.html?highlight=environment#environment-variables
"replaces ..."

A RESTIC_EXCLUDE_FILE environment variable would be an orthogonal extension,
a "nice to have feature".

**Comment by MichaelEischer** [comment] 2024-07-04 19:41
Duplicate of https://github.com/restic/restic/issues/1233 .

**Closed by MichaelEischer** 2024-07-04 19:41 UTC
