### ISSUE TITLE
Backend: use AttemptGet instead of Test + Get to reduce latency impact

### ISSUE THREAD

**Issue by mappu** [restic/restic#457] opened 2016-02-18 02:01 UTC
Backend abstraction offers Test and Get endpoints. From logging it seems Test (or it's Stat?) is called then followed by Get on all Get requests.

For high-latency backends (example, 200ms or greater) it could prevent efficiently using the network connection. So I think it would be better to add a backend AttemptGet that combines the two requests.

**Comment by fd0** [comment] 2016-02-21 19:45
I agree that it could be better, but where did you see `Test()` followed by `Stat()`?

**Comment by mappu** [comment] 2016-02-22 04:41
>where did you see `Test()` followed by `Stat()`?

nowhere
I did found ( ( Test or Stat, don't know which ) followed by Get ).

**Comment by fd0** [comment] 2017-05-14 20:07
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-05-14 20:07 UTC
Labels: enhancement, feedback needed
