### ISSUE TITLE
Support unattended encrypted backups without key disclosure

### ISSUE THREAD

**Issue by robbat2** [restic/restic#533] opened 2016-06-12 18:50 UTC
## Expected behavior

restic should allow unattended encrypted backups, without disclosing any key material that can lead to decrypting backups. This does tie into #187 as asymmetric keys can be used to general session keys for example.
## Actual behavior

restic requires a password or unsecure key material to do a new backup.

**Comment by fd0** [comment] 2016-06-13 06:46
Hi, thanks for suggesting this feature. Can you please elaborate a bit on how this issue is different than #187?

**Comment by robbat2** [comment] 2016-06-13 18:30
Asymmetric keys are only one of the ways this can be accomplished. Another is immediately pushing the backup to write-only destination (eg a S3 bucket where you can put new content but not read or modify anything already present). Asymmetric key usage (eg generate a session key for the data, use GPG or RSA to protect that key) do ensure that the attacker can't decrypt the backups if they do get their hands on them.

**Comment by anarcat** [comment] 2017-09-18 13:00
couldn't we implement this by simply storing the password in a file and use `--password-file`? that file could then be encrypted with `$WHATEVER` mechanism you prefer. for example, to encrypt the password file with GnuPG, you could do:

```bash
restic backup --password-file <(gpg --decrypt keyfile.gpg)
```

then of course, it's only as unattended as gpg will allow it, but at least there's some level of automation there... i guess that storing the password in standard keyrings (e.g. gnome-keyring and so on) might be another solution...

but yes, #187 would probably be better in the long term.

**Comment by jcollie** [comment] 2017-10-20 18:38
The ability to use HashiCorp's Vault https://www.vaultproject.io/ to store the password would be awesome!

**Comment by osamuaoki** [comment] 2017-10-25 14:58
For convenience, I like to see Gnome keyring supported :-)

FYI: I think the C code  "char *msmtp_password_callback ..." in src/msmtp.c in the source of msmtp gives good example for how to implement such.  It also has code for MAC and WINDOWS equivalents. 
 See code http://msmtp.sourceforge.net/

**Comment by robbat2** [comment] 2017-10-26 18:04
@osamuaoki there are multiple implementations already for accessing keyring: https://github.com/tmc/keyring

**Comment by osamuaoki** [comment] 2017-10-27 08:09
Oh, great!  Let's use the existing golang code!

Thanks for the pointer


2017/10/27 午前3:04 "Robin H. Johnson" <notifications@github.com>:

@osamuaoki <https://github.com/osamuaoki> there are multiple
implementations already for accessing keyring:
https://github.com/tmc/keyring

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/restic/restic/issues/533#issuecomment-339749736>, or mute
the thread

**Comment by spanezz** [comment] 2017-12-24 19:39
I wish there was a `--password-script` as a `--password-file` equivalent that read the password from the standard output of a script. Or maybe just `--password-file '!script'`, where the file is executed if it is prefixed with a `!`.

That way I could have a script that does something like `gpg --decrypt restic.gpg` that would then work with `gpg-agent` so that a sequence of restic invocations (say, `backup`, `forget`, `prune`) would only ask for a password once. That's an idea. Having a script would be rather flexible, and communication via a pipe is more secure than via the environment or via a file in the filesystem.

**Comment by rawtaz** [comment] 2017-12-24 19:51
Specifying stdin with arguments/options that take a file is usually done by specifying stdin as `-`. In this case it would be `--password-file -`. It's quite common in the UNIX/Linux world.

**Comment by fd0** [comment] 2017-12-24 20:04
@spanezz there's no need to implement that in restic, as it is provided by your shell:
```
$ restic --password-file <( gpg --decrypt path-to-key.gpg ) backup [...]
```

Calling restic in this way, the shell starts `gpg` and provides restic with a pipe that it can read like a file.

**Comment by spanezz** [comment] 2017-12-24 20:15
@fd0 nice idea!

It looks like there is too much magic going on, though, at least on `restic init`, which works if `--password-file` points to a file, but not if it points to `/dev/stdin` or `/dev/fd/nn`:
```
$ restic init --repo test --password-file <(echo password)
Fatal: passwords do not match
$ echo password > /tmp/foo
$ restic init --repo test --password-file /tmp/foo
created restic backend 4ff0ddf23e at test

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```

**Comment by fd0** [comment] 2017-12-24 20:18
Yeah, `init` is a special case, that indeed does not work. We could fix the code to support it though.

**Comment by mfsu** [comment] 2018-02-10 22:22
How about this keyring provider?

https://github.com/zalando/go-keyring

**Comment by matthijskooijman** [comment] 2018-08-26 10:06
Isn't this discussion getting off-topic? AFAIU storing the password in a keyring and allowing it to be extracted automatically for unattended backups does not solve this request *at all*. During the backup, restic will have access to the password / key used for encryption. When an attacker compromises the backed-up-machine, he can also gain the key and access to the backup storage, allowing access to and decryption of the backups (including older versions and perhaps also backups of other host, though I haven't checked if the multiple key support fixes this).

**Comment by mfsu** [comment] 2018-08-26 15:36
It takes effort to decrypt the keyring, but no effort is needed if the
credentials are in plaintext. A keyring manager could also allow other
solutions like use of dedicated hardware. Plaintext storage is the weakest
possible solution.

**Comment by tcely** [comment] 2018-08-29 01:30
My summary of this issue:

- fix init password file case
- password script feature
- vault integration
- keyring integration

I haven't seen a reasonable alternative to asymmetric keys for automated backups mentioned. As I understand it, both vault and keyring integrations are just specific cases of the more general script feature. All of these do not have the property of not being able to decrypt backups using the same key material used to encrypt new backups.

It's also worth noting that authorization to access repository data is a distinct concern.

As I see it, there are potentially four levels of encryption when creating backups:
1. The encrypted chunk of backed up data.
1. The repository meta-data
1. The storage of the repository
1. The transport used to access the repository

A solution that provides forward secrecy and uses asymmetric keys to protect the meta-data seems ideal to me. The encryption for storage and transport is likely outside the scope of restic. The data chunks are best served by symmetric encryption in my opinion. How we store those symmetric keys is where we have some flexibility to play with.

**Comment by graphixillusion** [comment] 2018-11-11 20:49
restic --password-file <( gpg --decrypt path-to-key.gpg ) ...

If i use this command under windows, i get: "unable to find specified file". Any way to do this under windows? Thank you!

**Comment by mathstuf** [comment] 2018-11-12 15:59
@graphixillusion The `<( command )` syntax is a bash-ism. Are you using `bash` or `cmd`? I don't know of a way to do it with `cmd`.

**Comment by mathstuf** [comment] 2018-11-13 16:58
You could probably use `gpg --decrypt | restic --password-file /dev/stdin` for winbash. cmd might has something similar too.

**Comment by graphixillusion** [comment] 2018-11-14 17:07
@mathstuf 
with cmd i can use the findstr "^" command. For example this command works good in cmd:

gpg --decrypt "blablabla" | findstr "^" ---> it will output the password

The problem seems that restic doesn't accept this comand followed by the flag -p/--password-file

restic -p (or --password-file) findstr "^" doesn't work.

**Comment by mathstuf** [comment] 2018-11-14 18:50
Even on Linux, it isn't restic that's doing the "command output as argument". That's bash. If cmd doesn't have an equivalent, that's a deficiency of Windows. [Here's a ServerFault question](https://serverfault.com/questions/688645/powershells-equivalent-to-bashs-process-substitution) which might help. Though I think [this SuperUser question](https://superuser.com/questions/289344/is-there-something-like-command-substitution-in-windows-cli) may be more useful.

**Comment by graphixillusion** [comment] 2018-11-14 20:08
I think, for now i found the right compromise: make a ramdisk;  temp save the decrypted password file into it; make whatever you need to do with restic; dismount and delete the ramdisk. Better than nothing. ;) In the meantime, if anyone knows how to do this with the right syntax with cmd under windows, please let me know. thank you.

**Comment by pdf** [comment] 2018-11-14 20:33
> Even on Linux, it isn't restic that's doing the "command output as argument". That's bash. If cmd doesn't have an equivalent, that's a deficiency of Windows.

To be fair, not even all shells on Linux support this syntax - this is definitely a bashism.

**Comment by mholt** [comment] 2018-11-14 22:29
>  a deficiency of restic.

Or a deficiency in other shells, for not being able to write files like that.

Just throwing that out there. :innocent:

Anyway, is this issue different from #187? On the surface, it doesn't seem very feasible, since doesn't some data have to be decrypted in order to encrypt new data and add it to the backup? So even if it was "asymmetric" you would still need a decryption key in order to make new backups, no?

**Comment by smlx** [comment] 2018-11-15 00:09
Something like this might work for shells without process substitution:

```
tmppipe=$(mktemp -u)
mkfifo -m 600 $tmppipe
gpg --decrypt ... | $tmppipe &
restic --password-file $tmppipe
```

**Comment by fd0** [comment] 2018-11-15 13:04
First, please ask usage questions in [the forum](https://forum.restic.net). We're using the GitHub issue tracker for bugs and features only.

Then: Why so complicated: `echo foo | restic -r /tmp/repo snapshots` works great...

**Comment by graphixillusion** [comment] 2018-11-15 19:31
@fd0 

Amazing, thank you! I did it using your suggestion with this command:

gpg --decrypt blablabla | findstr "^" | restic -r /path/to/repo snapshots

**Comment by edysli** [comment] 2019-04-30 13:41
Since version 0.9.4, there is the `--password-command` option (#2094).

**Comment by rawtaz** [comment] 2019-11-21 19:38
@robbat2 AS @edysli mentioned above, restic now has the `--password-command` argument. Does that solve your problem? If so we can close this issue.

**Comment by ja0nz** [comment] 2019-12-18 15:14
Recalling @matthijskooijman I would say the problem is not really solved as there is no true asymmetric key handling. Unattented _gpg --decrypt_ could be compromised at runtime.

Saying that a reader of this thread may take a look at [Duplicacy RSA encryption](https://forum.duplicacy.com/t/new-feature-rsa-encryption/2662) which supports public key chunk encryption and private key restoring.

**Comment by mathstuf** [comment] 2019-12-19 18:19
Note that without a key, dedupe doesn't work so well because you need to decrypt to compare contents. I think the way `obnam` did it is that it allowed different host-specific keys to decrypt the real key. That would allow for at least revoking compromised/deprecated backup hosts without having to change the repository password.

**Comment by 7usr7local** [comment] 2020-02-14 23:53
I don't see *any* notable increase in security in using any kind of keyring, key store or whatsoever compared to storing the "secret" (aka password) in plaintext. If your backup script has access to the keyring or whatever, any attacker can just use that part of your backup script to decrypt the secret.
The only scenario this makes any sense is to "open" the keyring manually and keep it open until shutdown of the server. That way loosing your harddisk would not compromise your backup's security. This can of course be achieved as well by using encryption for the filesystem the password-file is stored on. All approaches of this kind imply that backup won't work after an unattended reboot.
In the end, @robbat2 s request 

> without disclosing any key material

is not fulfilled with any of the shell tricks, key ring accesses or meanwhile available command line options.

Just my two pence though.

**Comment by mfsu** [comment] 2020-02-15 20:55
This discussion has become nonproductive. A solution to #187 will work for
this request, so I think this ticket should just be closed in favor of that
one.

**Comment by MichaelEischer** [comment] 2020-10-04 18:03
Closing this as the remaining issue seems to require asymmetric encryption which belongs into #187.

**Closed by MichaelEischer** 2020-10-04 18:03 UTC
Labels: category: backup, type: feature suggestion
