### ISSUE TITLE
s3 retention hold support 

### ISSUE THREAD

**Issue by udf2457** [restic/restic#4992] opened 2024-08-08 11:48 UTC
Something to consider would be introducing support for [S3 retention hold / object lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)

The intent would be to protect backups from changes or deletion, whether malicious or accidental.

An example scenario could be a cyber attack where S3 credentials were compromised. A retention hold on the S3 bucket would prevent an attacker from simply trashing all the old backups.

My thinking is that `restic backup` would set the lock, and then `restic prune` / `restic forget` would check for presence of retention old / object lock and act accordingly (i.e. skip / ignore).

**Comment by MichaelEischer** [comment] 2024-08-08 20:49
Duplicate of https://github.com/restic/restic/issues/3195

**Closed by MichaelEischer** 2024-08-08 20:49 UTC
