### ISSUE TITLE
Do not output ANSI escape sequences if output is redirected (e.g. to a log file)

### ISSUE THREAD

**Issue by cowwoc** [restic/restic#3184] opened 2020-12-22 06:20 UTC
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

How did you run restic exactly?
-------------------------------
`restic backup --use-fs-snapshot --encoding ascii --verbose=2 -o b2.connections=1 -r b2:repository someDirectory > log.txt`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2

Expected behavior
-----------------
Log file does not contain ANSI escape sequences

Actual behavior
---------------
Log file contains ANSI escape sequences (e..g `[2Klock repository`)

Do you have an idea how to solve the issue?
-------------------------------------------
https://stackoverflow.com/a/22972460/14731

**Comment by dimejo** [comment] 2020-12-22 08:10
This should be fixed with #3150. You can use the [newest beta releases](https://beta.restic.net/?sort=time&order=desc) to try this out.

**Comment by MichaelEischer** [comment] 2020-12-23 19:18
Closing this as duplicate of #3111.

**Closed by MichaelEischer** 2020-12-23 19:18 UTC

**Comment by cowwoc** [comment] 2020-12-25 07:01
Confirmed. This problem does not occur in the latest beta release. Thank you!
