### ISSUE TITLE
Check still fails after prune and rebuild-index

### ISSUE THREAD

**Issue by mholt** [restic/restic#1053] opened 2017-06-20 16:26 UTC
## Output of `restic version`

restic 0.6.1 (v0.6.1-126-gb0fb95df)
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)

```
$ restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 87fc1f5e6cc9397747f09df9756348a72a7771309c0371aa0fd7f2799f794f2f: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors

$ restic prune
counting files in repo
building new index for repo
pack file cannot be listed 87fc1f5e: header is larger than file
[0:03] 100.00%  1 / 1 packs
repository contains 0 packs (0 blobs) with 0B bytes
processed 0 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 0 snapshots
[0:00]   0 / 0 snapshots
found 0 of 0 data blobs still in use, removing 0 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 0 packs, this frees 0B
counting files in repo
pack file cannot be listed 87fc1f5e: header is larger than file
[0:02] 100.00%  1 / 1 packs
finding old index files
saved new index as a1875997
remove 1 old index files
done

$ restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 87fc1f5e6cc9397747f09df9756348a72a7771309c0371aa0fd7f2799f794f2f: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors

$ restic rebuild-index
counting files in repo
pack file cannot be listed 87fc1f5e: header is larger than file
[0:03] 100.00%  1 / 1 packs
finding old index files
saved new index as 23b5fcb0
remove 1 old index files

$ restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 87fc1f5e6cc9397747f09df9756348a72a7771309c0371aa0fd7f2799f794f2f: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors
```

I've also tried this many times in different orders, and check never gets cleared of the errors.

## What backend/server/service did you use?

sftp on LAN

## Expected behavior

It seems like #435 and #1029 were fixed, so I would expect that between prune and rebuild-index, the check would succeed.

## Actual behavior

check reports errors (is it referring to the "pack not referenced in any index" error?)

## Steps to reproduce the behavior

See above; and note that I initiated a backup before this and Ctrl+C'd it to see how it would cope.

## Do you have any idea what may have caused this?

Nope

**Comment by fd0** [comment] 2017-06-20 20:13
Hm, interesting. Thanks for the report! Exactly this should be addressed by #1029. I'll have a look.

**Comment by fd0** [comment] 2017-06-20 20:47
I'm sorry to ask this, but: Are you sure that the version of the restic binary you tried to run `prune` with is  really `restic 0.6.1 (v0.6.1-126-gb0fb95df)`?

The reason I'm asking is that #1036 (which has been merged into master) changes the message to this one:
```
$ bin/restic prune
counting files in repo
building new index for repo
pack file cannot be listed 93d8f826: header is larger than file
[0:03] 100.00%  4982 / 4982 packs
incomplete pack file (will be removed): 26146f3d0191bbdd1b5a7ebacabf890b6780e250126dab92ceb0133b8ee84fb5
[...]
```

Here's the code: https://github.com/restic/restic/pull/1036/files#diff-01d7796292d51bb9997ead47a675b27fR115

**Comment by fd0** [comment] 2017-06-20 20:51
I'm sorry, I should've waited for the `prune` command to finish. I can reproduce it with the latest restic master branch, I'll have an in-depth look now.

**Comment by fd0** [comment] 2017-06-20 20:53
Oh, it seems I forget to mark files as invalid in two cases.

**Comment by mholt** [comment] 2017-06-20 21:56
That's weird about the different error message. Yeah, I'm pretty sure it's right: what I do is `rm -rf $GOPATH/src/github.com/restic/restic` and then `go get -u github.com/restic/restic` and then `go run build.go`. I then `mv ./restic $(which restic)`.

I don't have a chance to test your patch right now but I will try to soon. Don't let me stop you merging it though!

**Closed** 2017-06-21 17:26 UTC
Labels: bug
