### ISSUE TITLE
Interrupted backup not resuming

### ISSUE THREAD

**Issue by safaribaer** [restic/restic#1704] opened 2018-04-04 14:00 UTC
I am fully aware of #1211 and read it.

## Output of `restic version`
./restic version
restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?
mkdir /media/sdf1/B
export REPO="sftp:root@localhost:/media/sdf1/B"
export RESTIC_PASSWORD='PASSWORD'
./restic -r $REPO init
./restic -r $REPO backup /media/DATA01/data
password is correct
scan [/media/DATA01/data]
scanned 7205 directories, 83968 files in 0:01

after 2 minutes ETA ~ 2:30:00
after 34 minutes and over 106GB data Ctrl+C

restart backup
./restic -r $REPO backup /media/DATA01/musik
it starts again and does not resume

This is on Debian 9.4

## What backend/server/service did you use to store the repository?
sftp
Please do not ask why i do not use the filesystem backend.
That my lead into an additional issue.

## Expected behavior
Resume backup.
It had enough time to write the intermediate index files and it also wrote enough data.

## Actual behavior

Backup does not resume.

## Steps to reproduce the behavior

See above

## Do you have any idea what may have caused this?
Maybe resuming does not work on the first snapshot?

## Do you have an idea how to solve the issue?
No

## Did restic help you or made you happy in any way?
Yes it replaced my rsync solution.

**Comment by fd0** [comment] 2018-04-05 11:15
Interesting, thanks for the report. Can you please reproduce it using the following steps:
 * Initialize a new repo
 * Start a backup, cancel it after roughly three minutes
 * Check how many files are in the `index/` folder in the repo
 * Start the backup again while checking the network bandwidth, up to roughly where it left of, no data should be written to the remote over the network

Please report back!

**Comment by safaribaer** [comment] 2018-04-10 18:25
Hi,
thank you for your response.
Yes in the index folder the files appear as expected. After resuming the backup no data is backed up for some time. From this point of view it works as it should. But while it is not backing files up it is reading the files from source again. Especially if this an mounted file system from remote the backup is not shorter and because of the slow transmission (WAN in my case) the numbers of already backed up files or the size of already backed up data does not rise noticably faster. Should restic not also skipp the already backup up files from beeing read again? I try to create some diagrams to  show this behaviour.

**Comment by fd0** [comment] 2018-04-10 19:49
I understand what you're describing: For resuming a backup, restic currently needs to re-read all files. And you're saving files from a mounted file system, so the files need to be re-fetched from a location far away.

For now, restic assumes that it can easily re-read the files it should save, that's what it's optimized for. In order to track where we are, we'd need local state that needs to be managed. With the current architecture that's hard to do and therefore it's unlikely to change.

I have plans for medium-term changes to restic, but for now I'd like to close the issue. Please feel free to add further comments, thanks!

**Closed by fd0** 2018-04-10 19:49 UTC
Labels: feedback needed

**Comment by mikeperalta1** [comment] 2021-12-06 03:36
Just want to add I think I may be suffering from this issue also. I have a remote server that contains encrypted data. The server doesn't decrypt the data; The data is decrypted here. So to backup the remote server, I really must perform the backup here. This means checksums can take awhile to compute, as the remote files must be read.

After an interruption, a resumed backup then (seems to) run checksums again on all files. This leaves a large amount of time where the backup process is simply reading from the remote server without sending anything to the backup destination (until it finally catches up to files that weren't previously sent to the backup destination).

Would it be possible to mark these already-sent files as no longer needing checksums if they were sent during the previously interrupted backup? Or perhaps downgraded to merely checking file size + inode or something? Perhaps ignored altogether? I feel like previously-sent files should just be left alone to help the backup complete a bit faster. If they'd changed since the first backup attempt, the backup could just be run again later to catch the changes.

**Comment by MichaelEischer** [comment] 2021-12-06 21:10
@mikeperalta1 Have a look at #3230.
