### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by stephen-hill** [restic/restic#1879] opened 2018-07-10 12:18 UTC
## Output of `restic version`

```
restic 0.7.0
compiled with go1.8.3 on linux/amd64
```

## How did you run restic exactly?

```restic prune```

## What backend/server/service did you use to store the repository?

External Hard Drive via USB3

## Expected behavior

Handle drive detachment/failure.

## Actual behavior

External drive became read-only while pruning which caused the repository to contain errors.

```
restic prune
repository 3c313c69 opened successfully, password is correct
counting files in repo
building new index for repo
[0:14] 100.00%  89127 / 89127 packs
repository contains 89127 packs (724713 blobs) with 385.738 GiB
processed 724713 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 112 snapshots
[2:00] 100.00%  112 / 112 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

```
restic check
using temporary cache in /tmp/restic-check-cache-929697099
repository 3c313c69 opened successfully, password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree b4f5e976:
  tree b4f5e976: file "vzdump-lxc-114-2017_11_22-04_13_08.tar" blob 412 size could not be found
  tree b4f5e976: file "vzdump-lxc-114-2017_11_22-04_13_08.tar" blob 413 size could not be found
  tree b4f5e976: file "vzdump-lxc-114-2017_11_22-04_13_08.tar" blob 414 size could not be found
  tree b4f5e976: file "vzdump-lxc-114-2017_11_22-04_13_08.tar" blob 415 size could not be found
  tree b4f5e976: file "vzdump-lxc-114-2017_11_22-04_13_08.tar": metadata size (1294725120) and sum of blob sizes (1292453137) do not match
  tree b4f5e976, blob 7ea16105: not found in index
  tree b4f5e976, blob 98a2f373: not found in index
  tree b4f5e976, blob 905a3625: not found in index
  tree b4f5e976, blob daa8ef76: not found in index
error for tree 53371426:
  tree 53371426: file "vzdump-lxc-114-2017_11_21-04_13_05.tar" blob 411 size could not be found
  tree 53371426: file "vzdump-lxc-114-2017_11_21-04_13_05.tar" blob 412 size could not be found
  tree 53371426: file "vzdump-lxc-114-2017_11_21-04_13_05.tar" blob 413 size could not be found
  tree 53371426: file "vzdump-lxc-114-2017_11_21-04_13_05.tar" blob 414 size could not be found
  tree 53371426: file "vzdump-lxc-114-2017_11_21-04_13_05.tar": metadata size (1295329280) and sum of blob sizes (1293057297) do not match
  tree 53371426, blob 7ea16105: not found in index
  tree 53371426, blob 98a2f373: not found in index
  tree 53371426, blob 905a3625: not found in index
  tree 53371426, blob daa8ef76: not found in index
error for tree dcfc5d8d:
  tree dcfc5d8d: file "vzdump-lxc-114-2017_11_20-04_13_10.tar" blob 410 size could not be found
  tree dcfc5d8d: file "vzdump-lxc-114-2017_11_20-04_13_10.tar" blob 411 size could not be found
  tree dcfc5d8d: file "vzdump-lxc-114-2017_11_20-04_13_10.tar" blob 412 size could not be found
  tree dcfc5d8d: file "vzdump-lxc-114-2017_11_20-04_13_10.tar" blob 413 size could not be found
  tree dcfc5d8d: file "vzdump-lxc-114-2017_11_20-04_13_10.tar": metadata size (1294530560) and sum of blob sizes (1292258577) do not match
  tree dcfc5d8d, blob 7ea16105: not found in index
  tree dcfc5d8d, blob 98a2f373: not found in index
  tree dcfc5d8d, blob 905a3625: not found in index
  tree dcfc5d8d, blob daa8ef76: not found in index
Fatal: repository contains errors
```

## Steps to reproduce the behavior

I've not had the time to reproduce this.

## Do you have any idea what may have caused this?

During a long prune (hours), the drive suddenly became read-only. After remounting the drive, this error occured.

## Do you have an idea how to solve the issue?

No, I tried upgrading to restic 0.9.1 compiled with go1.10.3 on linux/amd64, but this didn't fix the issue.

This has not stopped me from creating backups.

**Comment by dimejo** [comment] 2019-02-18 17:35
Looks like a duplicate of #2045.

**Comment by mholt** [comment] 2019-02-18 20:50
I agree; closing in favor of that one, to consolidate the discussion. However, if it does turn up that this is in fact different, we can reopen this one.

**Closed by mholt** 2019-02-18 20:50 UTC
Labels: duplicate
