### ISSUE TITLE
Impossible to backup again on my repository for a snapshot not found

### ISSUE THREAD

**Issue by RomyxBaps** [restic/restic#3433] opened 2021-06-17 15:40 UTC
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------

`./restic -r swift:REPOSITORY:/ backup --exclude-caches --exclude "/swap*" --exclude "/dev/*" --exclude "/proc/*" --exclude "/run/*" --exclude "/sys/*" --exclude "/tmp/*" --exclude "/mnt/*" --exclude "/var/cache/apt/*" --exclude "/var/lib/apt/{mirrors,periodic}/*" / --cache-dir /home -vvv`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Swift Object Storage

Expected behavior
-----------------

The backup is ok

Actual behavior
---------------

```
open repository
enter password for repository: 
repository XXXXXX opened successfully, password is correct
lock repository
load index files
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 462.318748ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 890.117305ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 636.341646ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.107876242s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.511079094s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 3.04096222s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 5.781953173s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 11.222385136s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 9.152900914s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 16.927710407s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 391.517075ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 594.826393ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.326470261s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.212558276s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.779941781s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 3.268621161s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 6.097818893s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 11.639721773s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 10.163325309s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 15.321265721s: conn.ObjectOpen: Object Not Found
Error loading snapshot d5452000: conn.ObjectOpen: Object Not Found
github.com/restic/restic/internal/restic.FindLatestSnapshot.func1
	/restic/internal/restic/snapshot_find.go:38
github.com/restic/restic/internal/restic.ForAllSnapshots.func2
	/restic/internal/restic/snapshot.go:113
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/build/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

```
Steps to reproduce the behavior
-------------------------------

Launch the backup command

Do you have any idea what may have caused this?
-----------------------------------------------

No idea, maybe an internet connection who was cut off

Do you have an idea how to solve the issue?
-------------------------------------------

No idea

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes

I try the `check`command, the `rebuild-index` command but with no result...

**Comment by rawtaz** [comment] 2021-06-17 15:49
Thanks for a detailed report!

Possibly caused by eventual consistency in your provider's systems.

- Which provider are you using for this Swift storage?
- How soon since your last backup of the same files/paths did you run this backup job again?
- Can you please open the `snapshots/` folder in your Swift storage (using your provider's tools or maybe rclone or perhaps Cyberduck or similar) and see if you can find a file there with the name containing `d5452000`?

**Comment by RomyxBaps** [comment] 2021-06-17 16:06
* I use OVH object storage
* I backup my folders every 6 hours between 8 am and 6pm
* How can I do that ? With the command `mount` ? If yes, i already tried and didn't found a file/fodler starting with d5452000
* /

**Comment by rawtaz** [comment] 2021-06-17 16:30
* I backup my folders every 6 hours between 8 am and 6pm

This doesn't answer the question, please try again :)

* How can I do that ? With the command `mount` ? If yes, i already tried and didn't found a file/fodler starting with d5452000

If you mean the `mount` command in restic, then no, that's not what I meant. I am suggesting that you inspect what files/objects are stored in the storage over at OVH. As I already mentioned you can do this using e.g. Cyberduck or whatever other tool you want to use.

I wonder if this could be caused by the restic cache referencing a snapshot that doesn't exist in the repository, I'm not sure. You can try by temporarily renaming your restic cache folder (restic will create a new one), and see if the problem then goes away. If this is the case it begs the question why the snapshot file went missing. But it'd be better to verify that file's existence first.

**Comment by RomyxBaps** [comment] 2021-06-18 08:08
* Sorry for the misunderstood... I backup my server entirely so the last backup I made was 2 days ago.
*  Okay i'll check if I can verify snapshots with linux and cyberduck. Where is the cache folder in a normla situation ? In /tmp ?

**Comment by rawtaz** [comment] 2021-06-18 14:44
I am still asking; How much time passed between the last successful backup and snapshot was created, and the first time you detected the problem?

The cache is stored in one of several paths depending on your operating system and/or environment variables, see: https://restic.readthedocs.io/en/stable/manual_rest.html#caching - When you find it, it's a folder with a SHA256 hash as the name (same as your repository ID I think).

**Comment by MichaelEischer** [comment] 2021-06-19 22:23
Does restic complain about the exact same not found snapshot if you run the backup again?

My current guess is that the Swift storage once again has managed to list a file as exisiting, that later on cannot be retrieved. Please run `restic list snapshots | grep d545200097` to get the full id of the snapshots and then try to inspect the snapshot using `restic cat snapshot <insert-full-snapshot-id-here>`.

@rawtaz restic always lists the snapshots directly at the storage backend. The cache is only used to skip downloading snapshots.

**Comment by RomyxBaps** [comment] 2021-06-21 07:40
> I am still asking; How much time passed between the last successful backup and snapshot was created, and the first time you detected the problem?
> 
> The cache is stored in one of several paths depending on your operating system and/or environment variables, see: https://restic.readthedocs.io/en/stable/manual_rest.html#caching - When you find it, it's a folder with a SHA256 hash as the name (same as your repository ID I think).

Hi, sorry for the late answer. 
The last backup who worked was one day before the bug appear.

I'll check the cache. For your information, I already test with `command --cache-dir /home` to force restic to use a new cache.



> Does restic complain about the exact same not found snapshot if you run the backup again?
> 
> My current guess is that the Swift storage once again has managed to list a file as exisiting, that later on cannot be retrieved. Please run `restic list snapshots | grep d545200097` to get the full id of the snapshots and then try to inspect the snapshot using `restic cat snapshot <insert-full-snapshot-id-here>`.
> 
> @rawtaz restic always lists the snapshots directly at the storage backend. The cache is only used to skip downloading snapshots.

Yes, the restic complain about the snapshot and doesn't want to backup again.
I'll try your command and I come back to you.

**Comment by RomyxBaps** [comment] 2021-06-21 10:04
> I am still asking; How much time passed between the last successful backup and snapshot was created, and the first time you detected the problem?
> 
> The cache is stored in one of several paths depending on your operating system and/or environment variables, see: https://restic.readthedocs.io/en/stable/manual_rest.html#caching - When you find it, it's a folder with a SHA256 hash as the name (same as your repository ID I think).

Hi, I try to mv my .cache/restic folders to create a new one but the commands went to a Fatal Error :
Check command : 
`./restic -r swift:REPONAME:/ check
using temporary cache in /tmp/restic-check-cache-404915546
enter password for repository: 
wrong password or no key found. Try again
enter password for repository: 
repository XXXXXXX opened successfully, password is correct
created new cache in /tmp/restic-check-cache-404915546
create exclusive lock for repository
load indexes
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 282.818509ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 492.389441ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 671.590708ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.351538765s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.569756966s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 656.819981ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 535.697904ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 990.739338ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.10606463s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.635001613s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.982055195s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 4.516962922s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.476837129s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 6.138576273s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.004869008s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 7.354397612s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 13.720092508s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 17.459582659s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 15.244987964s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 15.321265721s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 626.286518ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 529.936996ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.53600189s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.019463592s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.59154515s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.005900769s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.749385269s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 553.62672ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.106431215s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 651.885326ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.847489509s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 4.776550251s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 3.017312237s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 3.043281429s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 8.62753865s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 5.929389018s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 17.744535921s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 8.80426156s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 9.656209421s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 15.032910374s: conn.ObjectOpen: Object Not Found
error: error loading index 39b38ef6: conn.ObjectOpen: Object Not Found
error: error loading index c1de1448: conn.ObjectOpen: Object Not Found
Fatal: LoadIndex returned errors
`
Rebuild-index command : 
`/restic -r swift:REPONAME:/ rebuild-index
enter password for repository: 
repository XXXXXXX opened successfully, password is correct
loading indexes...
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 462.318748ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 890.117305ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 636.341646ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.107876242s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 298.484759ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 600.683895ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.807980427s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 990.739338ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.380473169s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.67875363s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.982055195s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 3.011308614s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 6.715255694s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.092384182s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 6.007303512s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 7.354397612s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 13.720092508s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 17.459582659s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 15.244987964s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 15.321265721s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 626.286518ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 529.936996ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.53600189s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 2.019463592s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 2.59154515s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 264.151541ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 493.746208ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.24566012s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.847489509s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 2.122911223s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.017312237s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.564922144s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.556307748s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 8.894083527s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 5.946792287s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 6.650766285s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 11.829690614s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 13.206392341s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 14.484314132s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 15.032910374s: conn.ObjectOpen: Object Not Found
Fatal: conn.ObjectOpen: Object Not Found
`
Backup command : 
`restic -r swift:REPO:/ backup --exclude-caches --exclude "/swap*" --exclude "/dev/*" --exclude "/proc/*" --exclude "/run/*" --exclude "/sys/*" --exclude "/tmp/*" --exclude "/mnt/*" --exclude "/var/cache/apt/*" --exclude "/var/lib/apt/{mirrors,periodic}/*" /
enter password for repository: 
repository XXXXXX opened successfully, password is correct
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 282.818509ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 492.389441ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 671.590708ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.351538765s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.569756966s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 656.819981ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 535.697904ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 990.739338ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.10606463s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.635001613s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.982055195s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 4.516962922s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.476837129s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 6.138576273s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 4.004869008s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 7.354397612s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 13.720092508s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 17.459582659s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 15.244987964s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 15.321265721s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 626.286518ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 529.936996ms: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 1.53600189s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.019463592s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.59154515s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 2.005900769s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 3.749385269s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 553.62672ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.106431215s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 651.885326ms: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 1.847489509s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 4.776550251s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 3.017312237s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 3.043281429s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 8.62753865s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 5.929389018s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 7.886460409s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 19.80958851s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 9.656209421s: conn.ObjectOpen: Object Not Found
Load(<index/c1de144859>, 0, 0) returned error, retrying after 15.032910374s: conn.ObjectOpen: Object Not Found
Fatal: conn.ObjectOpen: Object Not Found
`

**Comment by RomyxBaps** [comment] 2021-06-21 10:31
> Does restic complain about the exact same not found snapshot if you run the backup again?
> 
> My current guess is that the Swift storage once again has managed to list a file as exisiting, that later on cannot be retrieved. Please run `restic list snapshots | grep d545200097` to get the full id of the snapshots and then try to inspect the snapshot using `restic cat snapshot <insert-full-snapshot-id-here>`.
> 
> @rawtaz restic always lists the snapshots directly at the storage backend. The cache is only used to skip downloading snapshots.

I tried your commands.
I found the snapshot : 
`restic -r swift:REPONAME:/ list snapshots|grep d545200097
enter password for repository: 
d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660
`
But, I can't "cat" the snapshot with the old cache and the new one : 
`restic -r swift:REPONAME:/ forget d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660
enter password for repository: 
repository XXXXXXX opened successfully, password is correct
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 462.318748ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 890.117305ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 636.341646ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.107876242s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.511079094s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 3.04096222s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 5.781953173s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 11.222385136s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 9.152900914s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 16.927710407s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 391.517075ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 594.826393ms: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.326470261s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.212558276s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 1.779941781s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 3.268621161s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 6.097818893s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 11.639721773s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 10.163325309s: conn.ObjectOpen: Object Not Found
Load(<snapshot/d545200097>, 0, 0) returned error, retrying after 15.321265721s: conn.ObjectOpen: Object Not Found
Ignoring "d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660", could not load snapshot: conn.ObjectOpen: Object Not Found
`

**Comment by rawtaz** [comment] 2021-06-21 11:23
As @MichaelEischer suggested, your Swift seems to be telling restic that there is a file named `d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660` in the `snapshots/` path, but when restic asks for that file's contents, Swift tells restic that the file isn't there. Hence, this is a problem with your storage backend, it doesn't behave as it should.

You could verify this by using another tool to access your Swift - Go into the `snapshots` folder on that remote storage, look up the file `d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660` in the list, and then try to download it. Given the symptoms restic is experiencing when asking for the file, you probably won't be able to actually download the file.

**Comment by RomyxBaps** [comment] 2021-06-21 11:57
Hmmm okay and what is the best tool to check this on linux cli ?

**Comment by rawtaz** [comment] 2021-06-21 12:04
A quick DuckDuckGo search yields https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html for installing the `swift` CLI tool, and https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html for how to use it.

You can also use https://rclone.org if you want to, that way you don't have to install the Swift CLI and can instead just install the single rclone binary.

**Comment by RomyxBaps** [comment] 2021-06-21 12:11
Okay thank you.
If I can't download the file `d5452000979698fcde5949f5e3cd7ef8b5fda2380bb9fc72a3fbc3efaa75d660`. If I remove it, the problem will be solved ?

**Comment by rawtaz** [comment] 2021-06-21 12:14
Yeah, I mean if you remove that file then that snapshot will no longer exist, so it just means you lose that snapshot. The other ones should still be available.

But note that perhaps other files too might be listed as existing but not really existing, so you should probably at some point run `check --read-data` to make sure that every single piece of your repository can be accessed, if you want to be 100% sure. This will effectively have to download all your data though, so it will require a bunch of bandwidth and transfer.

**Comment by rawtaz** [comment] 2021-06-21 12:54
FWIW, it would probably be a good idea to go to the bottom of this issue with your provider, instead of just removing the snapshot file and hoping things are well. Your backup storage currently has shown that it cannot be trusted, and that is a *big* deal, and should cause serious concern about its suitability as a backup storage.

Having your provider investigating 100% why it does what it does right now, and having them verify 100% that they fixed the cause of the problem so that it won't happen again, should be a minimum goal to trust this storage in the future.

**Comment by RomyxBaps** [comment] 2021-06-21 13:03
Yes, I wil ltry to lookout with them.

I remove the file and now I have those errors : 
`Load(<index/c1de144859>, 0, 0) returned error, retrying after 19.80958851s: conn.ObjectOpen: Object Not Found
Load(<index/39b38ef636>, 0, 0) returned error, retrying after 20.070423968s: conn.ObjectOpen: Object Not Found
error: error loading index 39b38ef6: conn.ObjectOpen: Object Not Found
error: error loading index c1de1448: conn.ObjectOpen: Object Not Found
Fatal: LoadIndex returned errors
`
Can I repair this ?

**Comment by RomyxBaps** [comment] 2021-06-21 13:04
> Yes, I wil ltry to lookout with them.
> 
> I remove the file and now I have those errors :
> `Load(<index/c1de144859>, 0, 0) returned error, retrying after 19.80958851s: conn.ObjectOpen: Object Not Found Load(<index/39b38ef636>, 0, 0) returned error, retrying after 20.070423968s: conn.ObjectOpen: Object Not Found error: error loading index 39b38ef6: conn.ObjectOpen: Object Not Found error: error loading index c1de1448: conn.ObjectOpen: Object Not Found Fatal: LoadIndex returned errors `
> Can I repair this ?

OKay I think I found the solution with `command rebuild-index --read-all-packs`

**Comment by MichaelEischer** [comment] 2021-06-24 19:40
Judging from the fact that both files in `index` and `snapshot` were missing, I'd assume that also some of the pack files in the `data` folder are missing. When `rebuild-index --read-all-packs` completes successfully please make sure to run `check` or better `check --read-data` (which has to read and download the whole repository). Unless check completes successfully, you should assume that the backup is damaged.

**Comment by MichaelEischer** [comment] 2021-08-07 18:14
Closing this issue as the problem seems to be resolved and was apparently caused by some problem with the storage backend.

**Closed by MichaelEischer** 2021-08-07 18:14 UTC
Labels: type: question/problem, backend: swift
