### ISSUE TITLE
RFC:Improve restic error message when Access Denied

### ISSUE THREAD

**Issue by nexar** [restic/restic#3379] opened 2021-04-27 08:43 UTC
### 

Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When required environment variables e.g. AWS_ACCESS_KEY_ID etc are blank then it would be helpful to know that to allow easy debugging of scripts.  Currently the message says Access Denied which can be misinterpreted as a problem from the Supplier's end.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I was trying to write a script to connect to a Wasabi service point and restic was unable to open the repository because I had typed one of the AWS variable names wrong.  It mentioned that Access Denied and asked if a repository existed at the particular point.

Although clearly this is a user error, where a required variable is found to be blank then it would be super helpful to know that that variable has not been set.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Just starting with restic and find it's design and documentation very logical and easy to understand.  Plus the help from everyone on the forum is AMAZING!!  Thanks very much for this software.

**Comment by MichaelEischer** [comment] 2021-05-14 20:03
I agree that a better error message would be helpful. There's already an older issue reporting the same issue. Closing as duplicate of #2388

**Closed by MichaelEischer** 2021-05-14 20:03 UTC
