### ISSUE TITLE
`check` says `prune` would do more work right after `prune`

### ISSUE THREAD

**Issue by cyounkins** [restic/restic#3161] opened 2020-12-13 06:57 UTC
Output of `restic version`
--------------------------
```
$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic version
[sudo] password for craig:
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name check --read-data-subset=2/50
... (output lost to scrollback) ...
pack 4decbf56: not referenced in any index
pack f6d76cef: not referenced in any index
pack b179fe05: not referenced in any index
pack f180ac20: not referenced in any index
pack b49ab954: not referenced in any index
pack e5dc9845: not referenced in any index
pack 25ce46ac: not referenced in any index
pack 1fec6e84: not referenced in any index
pack 64030df7: not referenced in any index
pack ecf7054f: not referenced in any index
pack cca60501: not referenced in any index
pack 2028bc48: not referenced in any index
pack 55108c83: not referenced in any index
20616 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
read group #2 of 4797 data packs (out of total 405521 packs in 100 groups)
[29:33] 100.00%  4797 / 4797 packs
no errors were found

$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name check --read-data-subset=2/50
[sudo] password for craig:
using temporary cache in /tmp/restic-check-cache-745221159
enter password for repository:
repository 01618c22 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-745221159
create exclusive lock for repository
load indexes
  signal interrupt received, cleaning up
error: error loading index 0e2b5715: context canceled
error: error loading index 0ed163b8: context canceled
error: context canceled
Fatal: LoadIndex returned errors

$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name prune
enter password for repository:
repository 01618c22 opened successfully, password is correct
counting files in repo
building new index for repo
[10:39:53] 100.00%  426137 / 426137 packs
repository contains 426137 packs (6524038 blobs) with 2.124 TiB
processed 6524038 blobs: 559292 duplicate blobs, 198.140 GiB duplicate
load all snapshots
find data that is still in use for 19 snapshots
[4:08] 100.00%  19 / 19 snapshots
found 5885670 of 6524038 data blobs still in use, removing 638368 blobs
will remove 0 invalid files
will delete 4105 packs and rewrite 67972 packs, this frees 219.600 GiB
[46:05:57] 100.00%  67972 / 67972 packs rewritten
counting files in repo
[9:18:06] 100.00%  380897 / 380897 packs
finding old index files
saved new indexes as [ffdbb501 e09f5eab 4a85f968 877a7d2d efd35d33 0c10f8b9 2a04d55f 6201ed31 d3c4c5bc 847a8bce c71c33af 1452ecb2 69e7e64f eea1506f 1aac8e65 4341b9b8 108f34f4 45f9e72c 6519cb73 13ee007a 62ce5e06 8ef2ad03 29e1ce36 2b5307f1 04738f8f ec1492e6 0c69665d bb514f35 f4ddba50 e4188bfa a935f3b3 6142375a 55bca749 1d768f10 d936e07d 852c7bf9 781cf3d5 f45a3c9e 112767e5 1aaff156 836cbdea 48172562 efdc2ec9 8d530545 34e763fa 8f7e27df 78262b4f bb6586a2 8527294c 0494422e 5e601547 9a79eb93 f514dcb9 aa6e371e 5b436d98 1fc37509 14ff9bed 6cd0a53c bf623c17 7d625cf0 8d4c6656 040b18b5 9c82a49b 0640c70c b80a1053 e7a2cd99 12d64819 7ccc4cd5 3889a9d3 a79f9084 a4d821be 37881e4f caa37ca7 c0b5fd20 066a71f0 d6783efc 1c64f1af 6a9cdda7 66bbbc03 c46bd32b 12fc9073 8771e949 4430cb56 73ca5aa3 c3edcf81 573922cc 8761cf57 d8b69906 74587cbf 12d5b5f9 eab54e2f e6e20887 1d1b036b 1c687f5b dddc8db5 c0aa54c1 3ea438b4 337ea698 02738dad 47da074b 820c5566 441ba56a d3284a83 27012699 f4486edb 0e2fc5ee 9f4082c6 8984e7f3 a02b0512 fb97e6dc 6fa85d35 243f2d8e 67a1ce32 195af902 e47ccac4 67c30f86 98dbb14d 1b22b71e e784c824 dc44b354 ec8abfce 05b1cdfb 224fe0dd 1b51a749 08ce4d44 caeb2d41 aa65c383]
remove 667 old index files
[1:02] 100.00%  667 / 667 files deleted
remove 72077 old packs
[1:49:38] 100.00%  72077 / 72077 files deleted
done

$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name check --read-data-subset=3/50
[sudo] password for craig:
using temporary cache in /tmp/restic-check-cache-474186824
enter password for repository:
repository 01618c22 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-474186824
create exclusive lock for repository
load indexes
check all packs
pack 880b14fc: not referenced in any index
1 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

B2, US region

Expected behavior
-----------------

`check` immediately after `prune` should not indicate `prune` would do additional cleanup

Actual behavior
---------------

`check` reports: `1 additional files were found in the repo, which likely contain duplicate data.`

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Possibly the cancelled `check` immediately prior to `prune`?

I'm 95% sure I did not accidentally start any other `restic` processes, and I thought `prune` acquired a write-lock on the repo.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I really appreciate `restic` for its attention to security and data integrity!

**Comment by aawsome** [comment] 2020-12-13 07:46
First note that unreferenced but not needed files are not a problem and can easily occur if you cancel operations that write data, like `backup` or `prune`...

> I'm 95% sure I did not accidentally start any other restic processes, and I thought prune acquired a write-lock on the repo.

There is no write-lock between calling `check` and `prune`. When you work with a remote repo, this could be also because of a write to an eventually-consistent storage..

In fact, the `prune` from 0.11.0 can have a problem with eventually-consistent storages which IMO is fixed in the latest beta, but I don't remember the details so I would have to look at this in more detail to determine if that could be the cause.
I guess your behavior should be due to the `prune` run or a (aborted?) `backup` run just before your `prune`. Do you have a timestamp on the file `/data/88/880b14fc....`?

Best would be if you could reproduce this and then test if the new prune algorithm (in the latest beta builds) also reproduces this...

**Comment by cyounkins** [comment] 2020-12-13 10:21
> Do you have a timestamp on the file /data/88/880b14fc....?

Backblaze web UI shows that file was uploaded 12/17/2019 01:42, about 1 year ago.

I see that `check` outputs `create exclusive lock for repository` but `prune` does not.

`forget` was run, but it was ~24 hours prior to the `prune`. I will run `prune` again and see what happens.

**Comment by aawsome** [comment] 2020-12-13 10:33
Thanks for digging into! So it seems that this is not an issue about parallel backup or eventual consistency, but maybe a `prune` issue. 

It might be that this pack is incomplete or defect in some way and that `prune` from 0.11.0 then simply does not delete it. This should then also happen in your next `prune`; `check` run. But in this case I'm pretty sure that the new `prune` from #2718 handles this situation correctly and will simply delete this unneeded file.

So, please:

- run `prune` from 0.11.0 again
- run `check` again
- if the warning still exists, please repeat with the latest beta.

**Comment by aawsome** [comment] 2020-12-13 10:36
> I see that check outputs create exclusive lock for repository but prune does not.

Thanks for mentioning! `prune` does exclusively lock, so this is simply an inconsistency of the output...

**Comment by cyounkins** [comment] 2020-12-14 06:37
```
$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name prune
[sudo] password for craig:
enter password for repository:
repository 01618c22 opened successfully, password is correct
counting files in repo
building new index for repo
[9:11:38] 100.00%  380898 / 380898 packs
repository contains 380898 packs (5885673 blobs) with 1.909 TiB
processed 5885673 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 19 snapshots
[4:08] 100.00%  19 / 19 snapshots
found 5885670 of 5885673 data blobs still in use, removing 3 blobs
will remove 0 invalid files
will delete 1 packs and rewrite 0 packs, this frees 4.242 MiB
counting files in repo
[9:15:25] 100.00%  380897 / 380897 packs
finding old index files
saved new indexes as [73e67573 a5bacc31 94412573 dcc9450a 1647f494 8086770e 78d547ee b19eef63 1a3d17f8 72158d02 12e55849 5bee19a2 5b1439ba 75304031 8498456a 176aebdd ca90630a 135f3acd 018287c2 ca7a501e 4045460e 7d73e69f 6517e964 7bc7b3a2 eea85c73 9680afe4 a794b975 c5e22965 1a0c786d a713732f e0edcfef 1bd873c0 c77c67fe 9a5d12df d2f23ce3 616d63de 7fe8cdea c9730720 1cd022dd 7050fc54 b3b597f7 839df5d2 5e0280df aa435eef c07ce94e ebdd388d 1067a30e be7e1519 1245b27d 2b007f56 f87be087 f097c813 e0632443 c55d4b3a 881ddd01 3cec24f3 2fecd759 6047d69c eaa9e0d8 ff480cfc d59f6664 11ad1877 095af6bf 678da170 3cf28397 7632e805 ab06a25d e8653550 89df6ee4 d5c0302b 44cadcc8 991c8bf7 ccc76e68 2b86ad98 ed7d16ad 9474358f 8e8827ae 6a6b4fd5 631cd140 094c8fd0 43fb0ee7 13f67dff 837f5897 4852cd36 6593ce87 3f6e900f 1b518121 afad3531 536fd776 b870647e 0a4cd43d 8d14fbdb 92a6d506 507a04fe 5474e46a 8dcde682 a72cbea0 70a2465c 83a6edf7 9588865a 5b328521 f9a31402 90a35026 239df4e2 fee6a713 8ddd670c 41a0d8b6 b2dc498a 6d1a5958 710af6ad 0c6bb7ab 5174bdaf 2bacdcc6 c2b47fbf 48d3d382 187fd89e f671c59b 780f3540 2acb9dcc ef2c124b 6bafac21 1edf198b 14b68cf9 9b253b3b 9b2f3bc8 8c4e1eb4 128f2a7e]
remove 127 old index files
[0:15] 100.00%  127 / 127 files deleted
remove 1 old packs
[0:00] 100.00%  1 / 1 files deleted
done

$ sudo -u restic --preserve-env=B2_ACCOUNT_ID,B2_ACCOUNT_KEY restic -r b2:bucket-name check
[sudo] password for craig:
using temporary cache in /tmp/restic-check-cache-986144452
enter password for repository:
repository 01618c22 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-986144452
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

A second invocation of `prune` deleted the old pack `880b14fc`. It looks like the pack contained 3 blobs.

> `found 5885670 of 6524038 data blobs still in use, removing 638368 blobs`
> `found 5885670 of 5885673 data blobs still in use, removing 3 blobs`

Note that the same number of in-use blobs.

> Backblaze web UI shows that file was uploaded 12/17/2019 01:42, about 1 year ago.

`restic` would not issue file updates that could be subject to eventual consistency, right? The backblaze web UI did not have modified or access times.

So my guess is that some part of `restic` thought the file was deleted when it was not. Some ideas of the cause:

* Unhandled error from Backblaze
* Odd/incorrect use of an HTTP status code (ex: `200 OK` but body says `Try your request again`). This can occur with errors originating from load balancers.
* Connection termination, SSL error
* Backblaze response was erroneously affirmative, the file was never deleted
* Backblaze response was affirmative, the file was deleted, but their a failure in their distributed system caused something akin to a rollback where they chose not to replay deletes

Unrelated to the issue at hand: I was a little surprised to see that index file names appear to not be deterministic, and the index files were re-written. For example, the first index, `73e67573`, is not present in the `prune` output in the original post.

**Comment by MichaelEischer** [comment] 2020-12-15 21:36
restic issues normal put requests, it's up to the backend to provide specific consistency guarantees.

The b2 library used in restic treats everything which is not a `200 OK` reply as an error (this rules out the connection termination / SSL error case). The b2 API also promises that a 200 status code means that the file was deleted, errors return `4xx` status codes (https://www.backblaze.com/b2/docs/b2_delete_file_version.html). My understanding of B2's system is that users directly send their data to the storage pods, so there shouldn't be any broken loadbalancer inbetween.

I'd expect their data storage systems to complete the delete operation (including replication of the change) before returning the confirmation (which sort of rules out the last to options).

The API seems to follow at-least-once semantics, that is once you get an `ok` then the request has definitely been processed. However, it might take a few retries until a request succeeds. And each of the tries might succeed without you as a user learning about that fact (that is when you get an ok for a request, then it was executed at least once, but in case of problems it can be executed multiple times). Possible outcomes of that are that you try to delete a file, which after a failed try, is immediately reported as not present on the next retry (without one ever receiving an `ok`). Or that an upload happens twice, which results in a file with two file versions. The latter case would be a possible explanation for the observed behavior: delete just removes the latest file version, which uncovers the previous file version. The next prune run will then find that file a second time and delete it for good. Note that this scenario "just" requires b2 to behave according to specification, there's no need for implementation bugs. I don't know whether there's any possibility to verify that theory.

The index is (by design) completely rewritten during prune. We might see some incremental index updates also during prune in #1141 but that's won't happen any time soon. As the index files are encrypted and contain a random IV, even saving the same index data a second time will yield a different file name.

**Comment by aawsome** [comment] 2020-12-15 21:42
> A second invocation of `prune` deleted the old pack `880b14fc`. It looks like the pack contained 3 blobs.

Mhh, ok this is not what I was expecting..

> `restic` would not issue file updates that could be subject to eventual consistency, right? The backblaze web UI did not have modified or access times.

`restic` never updates or modifies any file. The filename equals its SHA256-hash. So instead of modifying, restic has to write a new file and delete the old one...

> So my guess is that some part of `restic` thought the file was deleted when it was not. Some ideas of the cause:
> 
>     * Unhandled error from Backblaze
> 
>     * Odd/incorrect use of an HTTP status code (ex: `200 OK` but body says `Try your request again`). This can occur with errors originating from load balancers.
> 
>     * Connection termination, SSL error
> 
>     * Backblaze response was erroneously affirmative, the file was never deleted
> 
>     * Backblaze response was affirmative, the file was deleted, but their a failure in their distributed system caused something akin to a rollback where they chose not to replay deletes

It might be that restic did send a "delete" request for this file, but this deletion (repeatedly) returned an error. IMO this is uncritical; not handling a potential error from the storage backend is just fine in that case. AFAIK restic does retry but would finally just ignore these errors.

In general having a file under `/data` which is not deleted does not corrupt the repository in any way as it is simply deleted by the next `prune` run.

> Unrelated to the issue at hand: I was a little surprised to see that index file names appear to not be deterministic, and the index files were re-written.

Correct. When restic encrypts the contents a second time, it uses a different random nonce. So even if the unencrypted contents are equal, the encrypted contents differ and so does the filename (SHA256 hash).
(In fact the "modification" restic makes relies on this - restic first creates a new file and then deletes the old one. And there is no handling implemented for the case that the old filename equals the new one...)

**Comment by MichaelEischer** [comment] 2020-12-15 22:16
> AFAIK restic does retry but would finally just ignore these errors.

But in that case restic would print multiple warnings and retry the delete operation multiple times, so it's fairly unlikely to fail and in any case it wouldn't happen without letting us know.

**Comment by MichaelEischer** [comment] 2021-01-08 19:58
To sum up what could be done to resolve this issue:

The B2 backend should probably check that deleting a file did actually delete it and not just one of possibly multiple file versions. I didn't notice a simple (and cheap) way to check whether a file actually has multiple versions. What would work is to check that a file no longer exists after deleting it, at the cost of an additional API call per deleted file.

A not properly deleted file is actually only a problem for indexes (and snapshots). Data files which were not deleted properly are no problem for restic, so can also ignore the latter case. A solution for indexes (besides fixing backends) could be to mark indexes which should have been deleted as obsolete, as for example proposed in #2839 (@aawsome I'd still like to leave that PR dormant for a while). Incrementally suppressing old indexes entries as probably necessary for #1141 would also work here.

**Closed** 2022-08-26 20:30 UTC
Labels: backend: b2, category: prune, category: resilience
