### ISSUE TITLE
Expired REST Certificate Wrong Error Message

### ISSUE THREAD

**Issue by MatthewVance** [restic/restic#2349] opened 2019-07-23 01:31 UTC
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
sudo -u restic ./restic-backup-hourly.sh  

The script:
```
#!/bin/bash

#: Title              : restic
#: Date               : August 2, 2018
#: Updated            : July 20, 2019
#: Author             : Matt Vance
#: Version            : 1.1
#: Description        : Script to run regular restic backups
#: License            : MIT License (MIT)

# Copyright (C) 2019 Matthew Vance

export RESTIC_REPOSITORY=rest:https://USER:PASSWORD@192.168.1.2:8889
export RESTIC_PASSWORD_FILE=/home/matt/.restic/restic-pw.txt

HOST=hagrid
CACERT=/home/matt/.restic/vm-bundle.pem
CACHE=/home/restic/.cache
EXCLUDE=/home/matt/.restic/restic-exclude.txt
INCLUDE=/home/matt/.restic/restic-include.txt
LOG=/home/matt/.restic/restic.log
RESTIC=/usr/local/bin/restic

#Define a timestamp function
timestamp() {
date "+%b %d %Y %T %Z"
}

# Add timestamp
echo "$(timestamp): restic.sh started" | tee -a $LOG
echo "-------------------------------------------------------------------------------" | tee -a $LOG

# Run Backups
$RESTIC backup \
--cacert $CACERT \
--cache-dir $CACHE \
--exclude-file $EXCLUDE \
--files-from $INCLUDE \
--host $HOST \
| tee -a $LOG
# --quiet | tee -a $LOG

# Add timestamp
echo "-------------------------------------------------------------------------------" | tee -a $LOG
echo "$(timestamp): restic.sh finished" | tee -a $LOG
printf "\n" | tee -a $LOG
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
My local network server makes the repo available over to clients on my local network via REST. This is done via RClone’s ability to serve restic’s REST backend API over HTTP. Caddy is used to reverse proxy to the service exposed by Rclone. My setup is described in more detail at: https://forum.restic.net/t/restic-example-gists/1751

Expected behavior
-----------------
The error message to indicate the issue is due to an expired certificate on the Caddy reverse-proxy. 

Actual behavior
---------------
It crashes:

```
Jul 22 2019 20:25:56 CDT: restic.sh started
-------------------------------------------------------------------------------
unable to read root certificate: open /home/matt/.restic/gryffindor-bundle.pem: no such file or directory
github.com/restic/restic/internal/backend.Transport
	/restic/internal/backend/http_transport.go:102
main.open
	/restic/cmd/restic/global.go:585
main.OpenRepository
	/restic/cmd/restic/global.go:357
main.runBackup
	/restic/cmd/restic/cmd_backup.go:412
main.glob..func2
	/restic/cmd/restic/cmd_backup.go:62
github.com/spf13/cobra.(*Command).execute
	/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
-------------------------------------------------------------------------------
Jul 22 2019 20:25:56 CDT: restic.sh finished
```

Steps to reproduce the behavior
-------------------------------
Attempt a backup from one Linux box to another over the REST backend exposed by RClone, with the REST service (behind a reverse proxy) using an expired certificate.

Do you have any idea what may have caused this?
-----------------------------------------------
I'm nearly sure the expired certificate issue caused the issue. That's the only thing that should have changed since the last successful backup. I updated the certificate bundle Caddy was using, but forgot to update the bundle file on the Linux box running the backup. Once I updated the file referenced by the CACERT variable in my script with the new bundle, the backup ran as expected. 

Do you have an idea how to solve the issue?
-------------------------------------------
Not at the code level. However, I expect the error handling mishandles expires certificates and thus displays the wrong error message and ends up crashing.

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is great. I recommend it all the time when backup conversations come up. I like the security model, how well this project is run, and the great community on here and the forum.

**Comment by fd0** [comment] 2019-07-23 09:21
Huh, that's interesting. Where does the path in the error message come from?

```
unable to read root certificate: open /home/matt/.restic/gryffindor-bundle.pem: no such file or directory
```

I can see that you pass `--cacert /home/matt/.restic/vm-bundle.pem` to restic, but where does the file `gryffindor-bundle.pem` come from? :)

**Comment by MatthewVance** [comment] 2019-07-23 10:17
That's a typo in the issue report. My script actually passes --cacert
/home/matt/.restic/gryffindor-bundle.pem. I was going to rename a few
things in the issue than decided to keep the real names. Looks like I
missed changing one back.

**Comment by MichaelEischer** [comment] 2021-08-19 12:44
Is this still a problem? Judging from the error message, the path to the certificate is wrong. At that point in the code no certificate parsing has happened yet.

**Comment by MatthewVance** [comment] 2021-08-20 00:54
Renewing my cert resolved my problem. I'm not sure if the underlying issue
is resolved. I had a mistake in my original issue report. The path to the
cert is right, just not in what I reported.

**Comment by MichaelEischer** [comment] 2021-08-20 08:19
I couldn't reproduce this issue with an outdated certificate. The error in the original issue report can only be triggered while reading the certificate, at which point the certificate hasn't been interpreted in any way. That is, at that point restic shouldn't care at all whether the certificate is valid or not.

I'm closing this issue for now, but feel free to reopen it if the problem shows up again.

**Closed by MichaelEischer** 2021-08-20 08:19 UTC
Labels: state: need feedback

**Comment by MatthewVance** [comment] 2021-08-20 10:35
Thanks. Feel free to close it.
