### ISSUE TITLE
Save(<data/...>) returned error

### ISSUE THREAD

**Issue by jkirk** [restic/restic#2269] opened 2019-05-06 22:35 UTC
Output of `restic version`
--------------------------

```
restic 0.9.5 compiled with go1.12.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
% sudo restic --password-file /root/.password-restic-steffi -r /media/steffi/BACKUP01/restic-backup/himalia-home-steffi backup /home/steffi/Bilder /home/steffi/Dokumente /home/steffi/Schreibtisch
repository 5f46e1b5 opened successfully, password is correct
found 5 old cache directories in /root/.cache/restic, pass --cleanup-cache to remove them
Save(<data/749b65af15>) returned error, retrying after 367.839216ms: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 544.140027ms: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 1.090508832s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 2.480888057s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 3.099937081s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 4.416389563s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/749b65af15>) returned error, retrying after 5.284942272s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/8196008d0a>) returned error, retrying after 526.554676ms: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/749b65af15>) returned error, retrying after 10.767026883s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/8196008d0a>) returned error, retrying after 652.785148ms: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 1.534896651s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 1.630640764s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 2.674096621s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 3.602792445s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 2.973312526s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/749b65af15>) returned error, retrying after 6.530304006s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/8196008d0a>) returned error, retrying after 10.639365553s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/749b65af15>) returned error, retrying after 27.816732895s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
Save(<data/8196008d0a>) returned error, retrying after 7.254793648s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Save(<data/8196008d0a>) returned error, retrying after 26.89927355s: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/81/8196008d0a595692888972cc1a77b22844f9e0ef1605f8a6749ec5079734e686: not a directory
Fatal: unable to save snapshot: OpenFile: open /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/74/749b65af15473cc484d39c033a50fba5f8145993d5fd6002f708e8679d96e08e: not a directory
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

External USB HDD with NTFS.

Expected behavior
-----------------

Create a backup / snapshot by fixing the problem automatically or tell the user what to do.

Actual behavior
---------------

Fails to create a backup:
```
Fatal: unable to save snapshot
```

Do you have any idea what may have caused this?
-----------------------------------------------

```
steffi@himalia ~ % ls -l /media/steffi/BACKUP01/restic-backup/himalia-home-steffi/data/ | tail -n 30
drwx------ 1 steffi steffi  8192 Mai  6 12:43 e2
drwx------ 1 steffi steffi 24576 Mai  6 18:42 e3
drwx------ 1 steffi steffi 16384 Mai  6 14:42 e4
-rw------- 1 steffi steffi     0 Aug 16  2018 e5
drwx------ 1 steffi steffi 12288 Mai  6 17:42 e6
drwx------ 1 steffi steffi 16384 Mai  6 12:43 e7
drwx------ 1 steffi steffi 16384 Mai  6 12:43 e8
drwx------ 1 steffi steffi 12288 Mai  6 18:43 e9
drwx------ 1 steffi steffi 16384 Mai  6 17:42 ea
drwx------ 1 steffi steffi 16384 Mai  6 21:47 eb
drwx------ 1 steffi steffi 16384 Mai  6 18:42 ec
drwx------ 1 steffi steffi 24576 Mai  6 21:46 ed
drwx------ 1 steffi steffi 24576 Mai  6 21:45 ee
drwx------ 1 steffi steffi 12288 Mai  6 19:34 ef
drwx------ 1 steffi steffi 12288 Mai  6 16:42 f0
drwx------ 1 steffi steffi 16384 Mai  6 19:42 f1
drwx------ 1 steffi steffi 12288 Mai  6 16:42 f2
drwx------ 1 steffi steffi 16384 Mai  6 21:45 f3
drwx------ 1 steffi steffi 16384 Mai  6 20:44 f4
drwx------ 1 steffi steffi 28672 Mai  6 21:46 f5
-rw------- 1 steffi steffi     0 Aug 16  2018 f6
drwx------ 1 steffi steffi 16384 Mai  6 18:42 f7
drwx------ 1 steffi steffi 12288 Mai  6 21:44 f8
drwx------ 1 steffi steffi 12288 Mai  6 21:45 f9
drwx------ 1 steffi steffi 24576 Mai  6 17:42 fa
drwx------ 1 steffi steffi 16384 Mai  6 19:34 fb
drwx------ 1 steffi steffi 16384 Mai  6 19:34 fc
drwx------ 1 steffi steffi 16384 Mai  6 20:45 fd
drwx------ 1 steffi steffi 16384 Mai  6 21:45 fe
drwx------ 1 steffi steffi 16384 Mai  6 13:42 ff
```

The external HDD was once unplugged without unmounting. This forced me to do a filesystem check which rendered the restic repository unusable. As far as I can remember, I created a new repository but my memory could trick me. Anyway, the failing backup seems to be caused by the empty files and I do not know where they came from.

restic is actually called automatically via cron and the backup silently failed for quite some time now. As this is a "simple" workstation I do not have any monitoring and mail system configured, so I think I need some time to gain back some trust in the backup system. So the main points are: 
* What could possibly cause this empty files?
* How can we avoid that? 
* Backup runs should not fail.

(Please be aware that I just updated restic today. The previous backups were taken with older versions of restic.)

Do you have an idea how to solve the issue?
-------------------------------------------

My workaround was to delete the empty files (zsh(!)):

```
  steffi@himalia ..restic-backup/himalia-home-steffi/data % ls -l *(.)
  -rw------- 1 steffi steffi 0 Aug 17  2018 21
  -rw------- 1 steffi steffi 0 Aug 16  2018 74
  -rw------- 1 steffi steffi 0 Aug 16  2018 81
  -rw------- 1 steffi steffi 0 Aug 16  2018 82
  -rw------- 1 steffi steffi 0 Aug 16  2018 b1
  -rw------- 1 steffi steffi 0 Aug 17  2018 c1
  -rw------- 1 steffi steffi 0 Aug 16  2018 e5
  -rw------- 1 steffi steffi 0 Aug 16  2018 f6
  steffi@himalia ..restic-backup/himalia-home-steffi/data % rm *(.)
```

Did restic help you or made you happy in any way?
-------------------------------------------------

I love restic and I want it to work as reliable as possible (that is why I filed this bug even my spare time is running short and although I found a workaround).

**Comment by MichaelEischer** [comment] 2020-05-01 20:24
> What could possibly cause this empty files?

restic creates these directories once and then only adds packs to them but for sure it won't replace those with empty files. 

The conversion from directories to empty files (I'd be surprised if the directories were empty before) was probably caused by a filesystem error triggered by the unexpected unplugging. This tells me that the NTFS implementation used on your Linux system is not crash safe at all: Basically all somewhat modern filesystems (including NTFS) have a filesystem journal to avoid metadata corruption after a system crash or when a disk disappears. The empty files, however, show that this obviously did not work at all. This error might also show up again the next time the system crashes or when the disk disappears.

_I highly doubt that the backup repository is still intact:_ It has lost 8/256 = 3% of its data which means that several or basically all snapshots are likely to miss data (unless you've only backed-up a few hundred MB of data). You want to run `restic check --read-data` to check the integrity of the whole backup.

There's not much restic can do in this case: When the backup repository just looses a substantial fraction of its data, then restic will have problems. I'd count the "empty files instead of directories" as an obscure enough problem that someone should have a closer look at it instead of letting restic try to fix this automatically. (Just silently removing the empty files is a bad idea, as their existence indicates that the repository is broken which would require repairs before the backup can continue. That way restic would degrade from "fail with an error" to "fail silently" which would be even worse. And restic is currently nowhere near being able to automatically repair arbitrary repository damages.)

**Comment by MichaelEischer** [comment] 2020-10-10 12:17
Closing this as there's not much we can do when the underlying filesystem looses files. The only option of adding redundancy to the repository is already tracked in #256 and #804.

**Closed by MichaelEischer** 2020-10-10 12:17 UTC
Labels: misc: mystery, state: need triaging
