### ISSUE TITLE
Allow setting sftp.command via environment variable

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#4599] opened 2023-12-26 21:12 UTC
Output of `restic version`
--------------------------

restic 0.15.2 compiled with go1.20.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Allow setting the SFTP command via environment variable. This would allow configuring the SFTP backend completely via environment variables like the other backends.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would allow me to set environment variables for all backends I want to use and then just change the repo to switch between repositories.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Moving a restic repo via `rclone` from S3 to SFTP just worked.

**Comment by bluppfisk** [comment] 2024-05-29 20:49
agree it would be nice to have this. I need to use `-o sftp.command=ssh -4 nas.mydomain.com -s sftp` to force ipv4 (the interface isn't listening on ipv6 but the domain resolves to an ipv6 first)

**Comment by MichaelEischer** [comment] 2024-07-06 17:24
Duplicate of https://github.com/restic/restic/issues/1233 .

**Closed by MichaelEischer** 2024-07-06 17:24 UTC
