### ISSUE TITLE
panic after SIGCONT

### ISSUE THREAD

**Issue by viric** [restic/restic#504] opened 2016-05-03 13:06 UTC
## Output of `restic version`

master as of today
## Actual behavior

```
$ fg
restic backup -e /srv/nfs/tmp/restic-ramon -r /mnt/usb-backup/restic-tmp/ /srv/nfs/tmp
panic: rename  /mnt/usb-backup/restic-tmp/data/f2/f24ae14bcdb97264070f271a72558e91bb8ad73a5223952030fb1482574107d5: no such file or directory
```

restic had ~700GB of 850, at that moment. I was not the first snapshot. The repository fs is an ntfs3g (fuse).
## Steps to reproduce the behavior

I had ctlr-z restic, run some commands completelyunrelated to /mnt/usb-backup, and then fg.

**Comment by fd0** [comment] 2016-05-03 19:58
Hi, thanks for reporting this. I'm unable to reproduce it, suspending and resuming restic works well. I suspect it's connected to the underlying file system. The error in the panic tells me that the tempfile restic created vanished.

Do you have an idea how that could've happened?

**Comment by viric** [comment] 2016-05-03 21:49
I only remember that there was a 3-line or so backtrace (I don't know why I didn't copy it here!), and I checked the existence of the file. It did not exist. The directory f2 existed.

**Comment by fd0** [comment] 2016-07-02 16:55
I've just run into this myself, the cause here was a full file system. Can you confirm that this may have happened to you also?

**Comment by fd0** [comment] 2017-05-14 20:08
Since there hasn't been any activity here recently I'm going to close this issue for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-05-14 20:08 UTC
Labels: bug, feedback needed
