### ISSUE TITLE
Restic 0.9.6 uploads every file, every time

### ISSUE THREAD

**Issue by joshdreagan** [restic/restic#2499] opened 2019-12-05 17:50 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
/usr/bin/restic backup --host 'machine1' --tag 'user1@machine1' --repo 'sftp:restic@backup1.local:/repositories/hugerepo' --password-file '/home/user1/.config/restic/secret' /mnt/storage01/Music /mnt/storage01/Videos

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp

Expected behavior
-----------------
I would expect the incremental backup to scan through the files, upload only the new/modified ones, and create the snapshot.

Actual behavior
---------------
In version 0.9.5, the incremental backup would quickly scan through all the files, find the files that were new/modified, upload them, and create the snapshot. In version 0.9.6, the incremental backup seems to be scanning/uploading every file. I have an 16TB backup made up of files that range from ~100MB-6GB. So this takes quite a while. Typically about 24hrs vs the 5-10 min it used to take for just the new/modified files. At the end of the backup, the summary shows that some large subset of the files have been modified even though they haven't. After it's completed, I do a `restic diff ...` of the new and previous snapshots and it will show the correct stats with only the actual new/modified files. So I'm not sure what the backup thinks is changing.

Steps to reproduce the behavior
-------------------------------
I suppose the steps would be:
1. Run a backup (preferably with some large files so you can see it scanning/uploading).
1. Modify/add some files.
1. Run another backup.
1. Verify that only the new/modified files were uploaded and marked as changed/new in the summary.

Do you have any idea what may have caused this?
-----------------------------------------------
The files being backed up reside on a gluster volume. Perhaps there's some issue with the retrieval of the file attributes as documented in #1736 that is causing restic to think the files have changed.

Do you have an idea how to solve the issue?
-------------------------------------------
¯\\\_(ツ)\_/¯

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic has been rock solid. I've been using it for over a year now and have even had to do a restore after a disk failure. So far it does its job well.

**Comment by rawtaz** [comment] 2019-12-05 19:26
Can you elaborate a bit on what the symptoms of this issue are? For example:

- Can you verify and reproduce that restic is showing different amounts of new/changed/unchanged files, given the same set of changes, between 0.9.5 and 0.9.6?

- Can you explain what makes you think that restic is actually *transferring* data that it has already backed up previously?

The way I read your report it seems that when you `restic diff` you get the right information, which makes me think that it has not sent to the repository data that it had already stored previously.

**Comment by buschjost** [comment] 2019-12-05 19:40
I suspect this to be very similar to #2495 - so to be caused by also using the ctime as modification indicator. 

You could try the `--ignore-inode` flag to see if this fixes your problem. There might be gluster specific ctime behaviour - or maybe you deactivated it? This seems to be possible: 
https://docs.gluster.org/en/latest/release-notes/6.0/ . Maybe you use an older cluster version where it was not enabled by default? 
Also Gluster 7 seems to have gotten some bugfixes related to ctime: https://docs.gluster.org/en/latest/release-notes/7.0/ "ctime changes: tar still complains file changed as we read it if uss is enabled" and others.

**Comment by dimejo** [comment] 2019-12-06 08:26
Does this happen aswell if you re-run a 2nd backup (without unmounting) the gluster volume?

**Comment by joshdreagan** [comment] 2019-12-06 20:52
Thank you all for the replies. Sorry for the delay. I had to wait until my backup finished so I could get the results. It took quite a while (~44hrs). Let me try as best I can to answer the individual questions.

@rawtaz 

> Can you verify and reproduce that restic is showing different amounts of new/changed/unchanged files, given the same set of changes, between 0.9.5 and 0.9.6?

I'm hesitant to revert to 0.9.5 now that I've completed backups with 0.9.6. This is an actual backup and I didn't want to risk corrupting it. So, for now, my evidence is a bit anecdotal in that I saw it start happening once I upgraded to 0.9.6.

> Can you explain what makes you think that restic is actually transferring data that it has already backed up previously?

The network activity shows that it's transferring data, and the restic output shows that it's doing something that's taking a good amount of time on the files that it thinks have changed. I'm not positive it's necessarily sending the data. It's much more likely that it's downloading (from the gluster volume), scanning/hashing the chunks, and then determining that those chunks already exist since the file hasn't actually changed.

@buschjost 

> I suspect this to be very similar to #2495 - so to be caused by also using the ctime as modification indicator.

It's possible.

> You could try the --ignore-inode flag to see if this fixes your problem. There might be gluster specific ctime behaviour - or maybe you deactivated it?

I will look into this. I haven't deactivated ctime, only atime on the volume.

> Maybe you use an older cluster version where it was not enabled by default?

I am currently running gluster version 7.0, and the cluster.op-version is 70000 (which is the same as cluster.max-op-version).

@dimejo 

> Does this happen aswell if you re-run a 2nd backup (without unmounting) the gluster volume?

I typically just leave the gluster volume mounted. It only unmounts when I restart the machine, or upgrade gluster. Which is rare. I will try to run another backup without adding or modifying any files, but it might take a while to finish. So I'll report back as soon as it's done.

In the meantime, here's the summary that was printed after the last backup completed:

```
Files:          12 new, 12602 changed,  2168 unmodified
Dirs:            0 new,     2 changed,     0 unmodified
Added to the repo: 46.045 GiB

processed 14782 files, 14.461 TiB in 44:18:47
snapshot 8aa161b2 saved
```

You can see that it got the 12 new files, but also thinks 12602 of the existing ones have changed. And here's the summary from the diff:

```
Files:          12 new,     0 removed,     0 changed
Dirs:           12 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:  38952 new,     0 removed
Tree Blobs:   3238 new,  3226 removed
  Added:   46.781 GiB
  Removed: 751.889 MiB
```

Here, you can see that it still has the 12 new files, but it sees that 0 of the others had changed (which is accurate).

**Comment by joshdreagan** [comment] 2019-12-06 21:35
@dimejo 

Ok. The second run didn't take nearly as long, but still picked up a bunch of "changed" files that have not been touched. Here's the summary from the backup that I ran immediately after the last one (with no files added or changed, and no unmount):

```
Files:           0 new,   378 changed, 14404 unmodified
Dirs:            0 new,     2 changed,     0 unmodified
Added to the repo: 1.451 KiB

processed 14782 files, 14.461 TiB in 29:35
snapshot d2a5c0a5 saved
```

You can see that it still thinks 378 files have changed. It seems to be random it which files it thinks change and how many of them. So the time taken to run the backups varies widely. Here's the summary of the diff:

```
Files:           0 new,     0 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:      0 new,     0 removed
Tree Blobs:    260 new,   260 removed
  Added:   8.917 MiB
  Removed: 8.917 MiB
```

So you can see that 0 files were added and 0 were actually updated.

I'll try the `--ignore-inode` option next and report back.

**Comment by joshdreagan** [comment] 2019-12-06 23:17
The `--ignore-inode` option seems to be the magic sauce. I added that to my backup command and ran it again (with no added/modified files) and got the correct results (0 new, 0 changed). It also completed in about 3-4 min. Which is normal. I then added some new files and ran another backup supplying the option again and, once again, received the correct results. Many thanks for all the assistance!

**Comment by rawtaz** [comment] 2019-12-07 00:32
@joshdreagan https://github.com/restic/restic/issues/2495 is about hard links, do you have that? I'm wondering if it's the same thing that's causing your symptoms, as in that other issue. If your changed files aren't due to hard links, i suppose that it's because of ctime changes to the files. Any thoughts on that?

Since you say you haven't explicitly observed the same data (for already backed up files) being transferred again, I think we can ignore that part of the original post for now, it's probably other data and then it all makes much more sense with the symptoms starting with 0.9.6 since 0.9.5. It's probably the ctime changes in 0.9.6, caused by something in your filesystem modifying the ctime of those files restic reports as changed when backing up.

**Comment by joshdreagan** [comment] 2019-12-07 00:58
@rawtaz I don't have any hard links that I've created in the backup set. That said, I do know that gluster uses hard links under the covers. I wouldn't think they'd be visible as such from the mount though. I know gluster also adds many extended attributes to the underlying files as stored on disk, and those attributes are not visible from the remote mount. Sort of an underlying, hidden implementation detail.

That said, in the docs, the `--ignore-inode` options states:

> In filesystems that do not support inode consistency, like FUSE-based ones and pCloud, it is possible to ignore inode on changed files comparison by passing `--ignore-inode` to `backup` command.

The remote gluster mount is indeed a FUSE-based one. So I do believe these issues are very much related. Perhaps a more detailed explanation of the `--ignore-inode` option in the docs is what's needed. In particular, a more thorough explanation of the statement "filesystems that do not support inode consistency, like FUSE-based ones".

**Comment by rawtaz** [comment] 2019-12-07 01:33
Thanks for everyones' input. I'm closing this issue now, with the rationale that possible changes in flags available to configure the change detection will be tracked/dealt with in #2495 for now, and updating the documentation as mentioned in this and that other issue is tracked in #2503 which I created just now.

Feel free to add further comments if needed, but please put them in #2503 if it's about updating the documentation!

**Closed by rawtaz** 2019-12-07 01:33 UTC
