### ISSUE TITLE
panic when checking repo

### ISSUE THREAD

**Issue by aminehmida** [restic/restic#314] opened 2015-10-01 11:42 UTC
Hi, first of all thank you for this great piece of software :+1: 

**Restic version** : e738d35c compiled 2015-10-01 11:59:10 with go version go1.5.1 linux/amd64

**Expected behavior:** report the integrity and consistency of the backup without panic and unlock the repository when executing `$ restic check` 

**Observed behavior:**  having this message in the stdout
```
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
```
and a panic [attached - debug enabled](https://gist.github.com/aminehmida/0e193889022465749c6c) in the stderr without unlocking the repo (need to run `$ restic unlock` )

My repo is stored in a usb drive formated with NTFS if this can help.

**Comment by fd0** [comment] 2015-10-01 12:29
Thanks for reporting this issue, it is indeed a bug.

**Comment by episource** [comment] 2015-10-01 15:36
This is probably the same as #311.

**Comment by episource** [comment] 2015-10-02 15:07
Today I ran into the same issue, but in an interesting context: I copied a restic repository created with the current master version (e738d35) from an internal ext4 drive to a samba share backed by an external ntfs-formatted usb3 device attached to a Windows 10 client.  The copy has been verified to be identical with the source repository:

```
$ diff -qr /media/backup-intern/restic/limucs-main.repo /mnt/backup-extern/restic/limucs-main.repo
diff -qr /media/backup-intern/restic/limucs-main.repo   31,64s user 373,25s system 9% cpu 1:14:56,53 total
```

If I run `restic check` on the source repository, no issues are found. Howerver, if I run `restic check` on the copied repository, the same nil pointer dereference error as above occurs. These are the last lines of the debug log:
```
[...]
2015/10/02 16:49:49 [ checker.loadTreeWorker] 166 checker.go:321 load tree 52334555
2015/10/02 16:49:49 [           Index.Lookup] 166 index.go: 98 id 52334555 found in pack ab9a0283 at 3677006, length 2707
2015/10/02 16:49:49 [ checker.loadTreeWorker] 168 checker.go:321 load tree ab9a943f
2015/10/02 16:49:49 [           Index.Lookup] 168 index.go: 98 id ab9a943f found in pack 8aacd119 at 3000126, length 1687
2015/10/02 16:49:49 [ checker.loadTreeWorker] 170 checker.go:321 load tree a08bd1eb
2015/10/02 16:49:49 [           Index.Lookup] 170 index.go: 98 id a08bd1eb found in pack 748d3e6a at 1750222, length 947
2015/10/02 16:49:49 [ checker.loadTreeWorker] 166 checker.go:324 load tree <nil> (52334555) returned err open /mnt/backup-extern/restic/limucs-main.repo/data/ab/ab9a02831a04a19ee9f3fb346aced22fbf04f6cf8c99f0a1b885340fc170feb5: input/output error
2015/10/02 16:49:49 [ checker.loadTreeWorker] 166 checker.go:330 sent tree 52334555
2015/10/02 16:49:49 [    checker.filterTrees] 108 checker.go:440 input job tree 52334555
2015/10/02 16:49:49 [    checker.filterTrees] 108 checker.go:395 closing output channels
```
dmesg does not report any read/write errors! 

Restic has been compiled using go version `go version go1.4.2 linux/amd64`.

**Comment by fd0** [comment] 2015-10-02 17:44
I'm able to reproduce it, working on it now. It's indeed a duplicate of #311

**Comment by episource** [comment] 2015-10-02 17:48
The nil pointer dereference is explained by #311. However the source of the input/output error remains unclear: Multiple runs of diff do not raise any IO-Errors!

Would be interesting to see the debug log of the original reporter. Also an input/output error?

**Comment by fd0** [comment] 2015-10-02 18:44
I'm pretty sure that it's not caused by an i/o error, I was able to reproduce it with a fresh repository with just one (non-interrupted) backup.

**Closed** 2015-10-11 19:49 UTC
Labels: bug
