### ISSUE TITLE
Compute and store Merkle tree of backed up data

### ISSUE THREAD

**Issue by pcouy** [restic/restic#4057] opened 2022-11-29 16:28 UTC
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When performing a `backup`, compute the [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree) of the the backed up files, directory structure and metadata, and store it in the repository as snapshot metadata.

A new `check` flag would perform a Merkle tree based integrity check by mounting a snapshot, computing the merkle tree of this mount, and comparing it with the stored Merkle tree. Likewise, the `restore` command could fail or raise a warning in case there is a mismatch between the merkle trees.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Make sure restored data is identical to the originally backed up data, similar to what is proposed in #1620 . Using Merkle tree instead of independently hashing each file would allow checking the integrity of the whole directory tree by comparing the root hashes only. Finding the corrupted file(s) (or the ones that were changed between two snapshots) in case of a root hash mismatch would also be a lot easier

**Comment by MichaelEischer** [comment] 2022-12-01 21:03
I totally don't get the point of adding a second Merkle-tree like data structure to the repository format. In the current format a tree blob already contains the hashes of the blocks of a file or the hash of other trees blobs. And the snapshot contains the hash of the root tree blob. Or in other words that's already some kind of Merkle tree (although a Merkle tree normally exclusively contains data in the leave nodes, and never in the inner nodes).

Which problem exactly are you trying to solve? It sounds like a duplicate of #805 to me?

**Comment by greatroar** [comment] 2023-01-13 16:57
Can this issue be closed?

**Comment by MichaelEischer** [comment] 2023-01-13 22:39
I think so. There has been no further feedback and I don't understand the original suggestion.

**Closed by MichaelEischer** 2023-01-13 22:39 UTC
Labels: state: need feedback
