### ISSUE TITLE
feature for prune/check and other backup or restore can run at the same time

### ISSUE THREAD

**Issue by gluthgao** [restic/restic#1186] opened 2017-08-28 13:57 UTC
this is not a bug, that's a feature improvement.
I have 5 machines to protect and all the backup data is written to my NAS.
The problem here is when any of the machine is in running backup then there is no chance to run the prune or check. can we just improve to make it can run at the same time for the repo maintain task?

Thanks

**Comment by fd0** [comment] 2017-08-29 19:19
That's a nice request, but it's really hard to do. I don't have a plan on how to support this operation safely, but I'll think about it.

**Comment by aawsome** [comment] 2020-07-09 18:54
IMO this is a duplicate of #1141

**Comment by MichaelEischer** [comment] 2020-07-25 10:36
Agreed. Closing this as duplicate of #1141. The only way of properly implementing this, which I can imagine is to have something like a garbage collection in two phases.

**Closed by MichaelEischer** 2020-07-25 10:36 UTC
Labels: type: feature suggestion
