### ISSUE TITLE
macOS: drop fuse support (restic mount)

### ISSUE THREAD

**Issue by fd0** [restic/restic#3096] opened 2020-11-14 12:56 UTC
The library we're using for fuse (https://github.com/bazil/fuse) [dropped support for macOS entirely](https://github.com/bazil/fuse/issues/224) a while back because the source code for osxfuse is [not available any more](https://github.com/osxfuse/osxfuse/issues/590). For now, we've pinned the last working version so `restic mount` still works.

In  #3094, I've disabled the fuse tests on macOS because they fail randomly.

Some thoughts:
 * At some point I'd like to update the `fuse` again, then restic on macOS will not be able to use the `mount` command any more
 * It feels to me that macOS will lose the ability to load custom kernel modules (osxfuse is a kernel module) sooner than later
 * Until now restic consists only of Go code, we don't need `cgo` for building. That makes the build process (for us as well as for our users) **much** simpler and we haven't had any issues.

My idea would be to refactor the fuse code and implement a simple webserver view as well as a WebDAV server (see #485) as an alternative to fuse. This way, also users on Windows benefit.

**Comment by ncw** [comment] 2020-11-14 14:35
We recently faced this situation in the rclone project - see https://github.com/rclone/rclone/issues/4393 for details.

However we were already using https://github.com/billziss-gh/cgofuse for a CGO based interface to `libfuse` on Windows so we've extended this support to macOS.

I've found cgofuse a bit more compatible and reliable than bazil/fuse as it uses `libfuse` directly and there are lots of little tweaks in `libfuse` that bazil/fuse doesn't implement.

Using cgofuse requires building with CGO support. However the cgofuse library itself doesn't cause the resultant binary to depend on libfuse as it dynamically loads the libfuse module at runtime. This means that you can run rclone on macOS without having OSXFUSE installed - only `rclone mount` will fail if you don't have it.

```
$ ldd rclone
$ ldd `which rclone`
	linux-vdso.so.1 (0x00007ffd0bd38000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f65ba06c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f65ba049000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f65b9e57000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f65ba090000)
```

I'd quite like to swap to cgofuse everywhere (rclone uses it for macOS and Windows) but the cgo barrier for cross compiling is high on Linux systems as there are so many of them!

Note that I've had quite a few problems with cross compiled macOS builds of rclone. In particular with dns resolution, certificate handling and handling user info. Using a cgo enabled build which was built on macOS has solved those problems and it is easy to do with GitHub actions now.

So.. If you added cgofuse support you would
- `+` gain Windows support too
- `+` fix macOS support
- `-` have to deal with cgo builds for macOS and Windows
- `-` have to re-implement `restic mount` with cgofuse

As for the last point cgofuse is much closer to `libfuse` than `bazil/fuse` which I think makes the implementation easier, but it **is** different. The factored out code which is different is about 800 lines of code for each in rclone which is a non-trivial amount of code. Rclone has a very well developed VFS layer so all the common code is in that.

> My idea would be to refactor the fuse code and implement a simple webserver view as well as a WebDAV server (see #485) as an alternative to fuse. This way, also users on Windows benefit.

I think you'd be pulling out a read only VFS layer from the fuse code. This is worth doing as it makes plugging it into other things much easier.

If you were to do a really simple webserver, provided
- rclone can read the directory listings
- you support HEAD and Range on the objects

Then rclone can serve an `rclone mount` from it, or `rclone serve webdav/sftp/http/ftp/etc` from it.

We could possibly make some automation for this - I could make the http backend auto start restic to keep it seamless.

> * It feels to me that macOS will lose the ability to load custom kernel modules (osxfuse is a kernel module) sooner than later

We are not there yet though and I know if I dropped `rclone mount` from macOS then I'd have a lot of unhappy users.

**Comment by fd0** [comment] 2020-11-14 19:22
Thank you very much for the comprehensive information! I'm not sure what we'll do, I'm very reluctant to introduce cgo.

**Comment by fgma** [comment] 2020-11-14 21:06
Just for reference: I've did a protoype using cgofuse on windows (where it does not need cgo besides the name) https://github.com/restic/restic/pull/2862

**Comment by ncw** [comment] 2020-11-15 11:51
> Thank you very much for the comprehensive information!

You are welcome

> I'm not sure what we'll do, I'm very reluctant to introduce cgo.

`cgo` on Windows and macOS have been no trouble at all in the rclone project. Other than having to do the builds on Windows and macOS machines which was reasonably easy to accomplish with GitHub actions. In the Windows and macOS worlds, dynamically linked executables are 100% compatible everywhere (unlike the Linux world).

What I did in rclone was introduce a build tag which you have to set explicitly to include any of the `cgo` stuff. This means that you can still cross compile restic and it will work, you just won't get the `mount` feature on macOS and Windows. The GitHub actions builders set that build tag so the release (and beta) binaries have that feature in. See [rclone's build script](https://github.com/rclone/rclone/blob/095c7bd801a8ef01bb4a9c792340fa3c0a302fe8/.github/workflows/build.yml#L35-L42) for more details!

**Comment by fd0** [comment] 2020-12-03 20:20
A user [reported](https://forum.restic.net/t/cannot-mount-on-macos-with-macfuse-4-x/3338) that restic does not work with osxfuse 4 any more. :(

**Comment by darthShadow** [comment] 2020-12-03 21:17
I can confirm that the cgo variant of mount in rclone still works with MacFuse/OSXFuse 4 but the pure-go variant doesn't any more.

**Comment by ivoanjo** [comment] 2021-02-17 15:47
Might be worth documenting it somewhere. I've been bitten by it not working on macos, and I was going a bit back and forth thinking this may be some permission or something issue, until I found this ticket.

**Comment by koalalorenzo** [comment] 2021-09-11 11:11
It would be nice to have this planned for a future release! It is not needed but since the new Mac are coming up soon, it will be a huge pain in there for my flow. 😅

**Comment by maiux** [comment] 2021-10-30 06:51
> It would be nice to have this planned for a future release! It is not needed but since the new Mac are coming up soon, it will be a huge pain in there for my flow. 😅
> 
> Edit: It does not work also on macOS Monterey, as OSXFUSE does not support the newer version. I tried to install osxfuse from brew, and I got the issue.

not sure if it fits your needs but I'm using this workaround: [https://forum.restic.net/t/restic-mount-on-osx-and-windows-in-2021/4487](url)

**Comment by bdillahu** [comment] 2021-11-05 03:18
> It would be nice to have this planned for a future release! It is not needed but since the new Mac are coming up soon, it will be a huge pain in there for my flow. 😅
> 
> Edit: It does not work also on macOS Monterey, as OSXFUSE does not support the newer version. I tried to install osxfuse from brew, and I got the issue.

Yep... first time I've needed to recover something (be careful with "rm -rf" :-)) since I upgraded... now it's going to be more painful.

I can mount it on a linux box and get files from there, but...

**Comment by rawtaz** [comment] 2021-11-05 03:21
There's a `restore` command, as well as `find` and `ls` in restic ;)

**Comment by bdillahu** [comment] 2021-11-05 03:22
> There's a `restore` command, as well as `find` and `ls` in restic ;)

Thanks... I guess I can go read up on them and try to figure out how to do what I want... whereas (especially since I just hosed my home directory), I figured I could do what I know and just rsync over from the last snapshot what I need...

Appreciate the reminder though... seriously.

**Comment by rawtaz** [comment] 2021-11-05 03:24
Here are the docs: https://restic.readthedocs.io/en/stable/050_restore.html#restoring-from-a-snapshot

**Comment by bdillahu** [comment] 2021-11-05 03:29
> Here are the docs: https://restic.readthedocs.io/en/stable/050_restore.html#restoring-from-a-snapshot

One question... is it possible to restore just files that don't exist? i.e. if the snapshot file is older than what's currently there, leave what's there? It's unclear at a quick read if it just overwrites everything or not.

Thanks!

**Comment by rawtaz** [comment] 2021-11-05 03:36
Unfortunately not, #407 and #2662 are on that topic but for now mounting the repo and using e.g. rsync is the closest you'll get I think.

**Comment by bdillahu** [comment] 2021-11-05 03:36
> Unfortunately not, #407 and #2662 are on that topic but for now mounting the repo and using e.g. rsync is the closest you'll get I think.

Thanks... I've got my rsync running from my linux VM and it seems to be doing fine.

I will try to read up and play with the restore a bit more for the next fiasco... appreciate the help!

**Comment by zhengpd** [comment] 2022-01-14 13:11
Any news on this? Does `restic mount` work on Monterey now?

**Comment by xeor** [comment] 2022-08-21 18:22
Another bump.. Is there any good alternative while we wait that anyone know that makes it more seamless to restore files?

**Comment by rawtaz** [comment] 2022-08-21 19:01
Good question @xeor - personally I just use the `restore` command (and `find` if need be), but if I needed to browse snapshots I would consider firing up a Docker container (or a VM, if you fancy that) in which I run `restic mount` to browse and restore whatever files I want in there (to the host's filesystem of course).

**Comment by xeor** [comment] 2022-08-21 19:18
Thanks for the answer @rawtaz! I was thinking about using a container as well, but I'm on an m1-mac, and I'm not sure if I'll be able to easiely get fuse inside. I could maybe run fuse inside a container on a linux-vm.. Doesn't fuse require the host to have a /dev/fuse or something?

**Comment by rawtaz** [comment] 2022-08-21 19:30
Docker Desktop for Mac actually runs a Linux VM behind the scenes (using the macOS virtualization layer), but I do believe you have to use arm-based containers (you specify the type/arch when you `docker pull`). So whatever FUSE needs should be able to run inside that container.

Since everyone and their cat use Docker containers on M1 machines nowadays though, that should be fine. I personally don't know if FUSE has any problems with arm/M1 architecture, I suggest that if you don't know that it won't work, just try it :)

Interestingly enough, someone asked about this exact thing (although not mentioning M1) at https://stackoverflow.com/questions/73263343/how-can-i-use-a-fuse-filesystem-inside-docker-on-macos a couple of weeks ago. They say they didn't get it working, but didn't provide any details as to why, so I still don't know a reason why it wouldn't work. It runs in a Linux VM, so I don't see why it wouldn't. If the Docker/container aspect is making it more complicated, one can use a regular VM using https://getutm.app instead.

**Comment by gabrielwhite** [comment] 2022-08-21 19:47
Use Docker. Bind mount the directory you want to restore to and then copy the files out of the container.

**Comment by hraban** [comment] 2022-08-22 00:11
For a completely different workaround out of left field: how about using /restic/ as an /rclone backend/, i.e. the opposite of "https://github.com/restic/restic/issues/1561"? Instead of `restic mount` offering its virtual filesystem to FUSE, it could offer its virtual filesystem to rclone, instead. Users could then use rclone to actually inspect the data.

Aside from rclone having (apparently?) done the heavy lifting for directly mounting virtual filesystems on OSX, it has another hidden gem: docker volumes. You can serve any rclone backend as a virtual docker volume, "https://rclone.org/docker/". Again, rclone has done the heavy lifting here, allowing users to bind a restic backend (iow, what would normally be mounted using `restic mount`) as a docker volume to a docker container.

That would also solve this issue, right? @ncw what do you think of this, would that make sense from an rclone perspective?

**Comment by cva** [comment] 2022-08-22 15:22
> Thanks for the answer @rawtaz! I was thinking about using a container as well, but I'm on an m1-mac, and I'm not sure if I'll be able to easiely get fuse inside. I could maybe run fuse inside a container on a linux-vm.. Doesn't fuse require the host to have a /dev/fuse or something?

I wrote up some instructions in [this thread](https://forum.restic.net/t/cannot-mount-on-macos-with-macfuse-4-x/3338/5) on the forum a while ago to get `restic mount` working in docker for macOS. When I wrote that originally I was on an intel mac, but I just tested and it still seems to work on my new m1 mac

**Comment by xeor** [comment] 2022-09-10 22:50
Maybe https://www.fuse-t.org is an alternative. It looks promising. It doesn't just drop in on restic tho, I am still getting `cannot locate OSXFUSE`

**Comment by MichaelEischer** [comment] 2022-09-11 13:58
fuse-t has been out for about a week. So there's no way to tell whether it will even work properly. And from the looks of it, it might require CGO, which we don't want to use.

**Comment by noamross** [comment] 2022-09-11 19:44
Here's an interim Docker/rclone solution for browsing restic snapshots: https://forum.restic.net/t/restic-mount-on-osx-and-windows-in-2021/4487/12?u=noamross

**Comment by ncw** [comment] 2022-09-16 16:24
@xeor @MichaelEischer  https://www.fuse-t.org looks very interesting.
> fuse-t has been out for about a week. So there's no way to tell whether it will even work properly. And from the looks of it, it might require CGO, which we don't want to use.

My reading is that it will definitely require CGO as the magic is done in the libfuse replacement. From its docs

> When a filesystem issues a mount API call, libfuse launches a FUSE-T NFS server that exposes a local TCP port to the macOS mount process and another communication channel to libfuse. 

I think you are going to have to bite the bullet and use cgo with [cgofuse](https://github.com/winfsp/cgofuse) (see my comment above https://github.com/restic/restic/issues/3096#issuecomment-727215997 for a lot more detail!).

The way I did this in rclone was to have another command `cmount` which is only compiled in if `cgo` is enabled.

Note also that cgofuse under Windows does **not** require CGO any more - that is how we use it in rclone now.

Other alternatives as @fd0 suggested is to implement a webdav server #485 - this would enable rclone to mount it also.

Or if restic could expose the file system that this defines https://github.com/restic/restic/tree/master/internal/fuse as an [io.Fs](https://pkg.go.dev/io/fs#FS) or something similar, then that would make it easy to build a webdav server, an alternative cgofuse based mount, or an rclone backend (as @hraban suggested) from it, so I think that is the first job.

**Comment by enj** [comment] 2022-09-16 18:33
I am a bit too over committed right now to make a pull request, but I replaced `bazil.org/fuse` with `github.com/anacrolix/fuse` (which is hard fork of https://github.com/zegl/fuse/pull/1).  This allows mounts to work on macOS 12.5.

https://github.com/restic/restic/commit/0318faede78c1d2f8be48381bebc0be5e6b7f574

**Comment by MichaelEischer** [comment] 2022-11-12 14:17
`github.com/anacrolix/fuse` indeed looks like a temporary solution.

However, in the long term we'll probably have to switch to a different library as there seems to be no actively maintained fork of bazil/fuse.

While looking for alternatives, I've found the following libraries:
- https://github.com/seaweedfs/fuse an older fork of bazil/fuse, which looks like it will be replaced by go-fuse
- https://github.com/hanwen/go-fuse : A completely different implementation, which however seems to only support Linux and macOS. That would mean the we loose fuse support on freebsd
- https://github.com/jacobsa/fuse : Somewhat related to bazil/fuse such that migrating the code might be easier. But also only Linux and macOS support.
- https://github.com/winfsp/cgofuse : Already mentioned in this issue, basically works everywhere, but requires CGO. For Windows as cgo-free mode exists
- https://github.com/keybase/dokan-go : Uses the Dokany driver on Windows to create a file system from userspace. Requires CGO.

**Closed** 2022-11-26 11:15 UTC
Labels: category: project, category: mount, platform: darwin

**Comment by Fischmuetze** [comment] 2023-02-09 06:52
This project could be helpful for some situations 
https://github.com/emuell/restic-browser/
Works like a charm for me.

**Comment by ncw** [comment] 2023-02-10 11:40
@necrevistonnezr wrote:
> One more upvote to integrate Fuse-T which is now integrated into the wonderful Cryptomator as well: https://github.com/cryptomator/cryptomator/releases/tag/1.7.0-beta1

I'm pretty sure Fuse-T will require CGO to link with their library, and thus cgofuse to access it. Rclone users have got this combo working with rclone's cgofuse support on macOS.
