### ISSUE TITLE
restic process hangs in state "D" (and therefore cannot even be killed)

### ISSUE THREAD

**Issue by aksdb** [restic/restic#1028] opened 2017-06-14 08:18 UTC
## Output of `restic version`
```
restic 0.6.1
compiled with go1.8.3 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
```
restic backup --one-file-system -r /mnt/network/backups/MyMachine.restic -p /home/... /home/...
```
(Actual list of directories and files to be backed up is stripped for privacy reasons; the target directory name is anonymized as well.)

## What backend/server/service did you use?
Filesystem, but the target is a CIFS share with Kerberos authentication.

## Expected behavior
The process fails due to filesystem error(s).

## Actual behavior
The process waits for an IO-resource and hangs indefinitely, also blocking me from unmounting the network share.

```
$ ps ax | grep restic
 3428 ?        Dl     0:27 restic backup --one-file-system -r .....
```

Also the backup process sometimes hangs for quite a while (I would estimate 20 seconds without any visible progress; only the "MiB/s" counter decreases constantly) and then prints an error like the following, before proceeding.

```
error loading tree: read /mnt/network/backups/MyMachine.restic/data/b7/b700e1edcf4717747eadb6fd2631b0a7bd2ed68a11c41c23073e0e6cee7fbbf3: bad file descriptor
```
... although I can access that file via shell:
```
$ file /mnt/network/backups/MyMachine.restic/data/b7/b700e1edcf4717747eadb6fd2631b0a7bd2ed68a11c41c23073e0e6cee7fbbf3
/mnt/network/backups/MyMachine.restic/data/b7/b700e1edcf4717747eadb6fd2631b0a7bd2ed68a11c41c23073e0e6cee7fbbf3: data
```

## Steps to reproduce the behavior
I don't know, yet. I can only assume (see below).

## Do you have any idea what may have caused this?
I presume due to a network hickup or the expiration of the Kerberos ticket, the filesystem doesn't handle a specific request. The same mount point can still be written to and read from, but restic stays in state "D". The only thing getting me out of this situation is a reboot.

**Comment by fd0** [comment] 2017-06-15 10:47
Thanks for raising this issue. According to [this post on StackOverflow](https://stackoverflow.com/a/1475715), restic is waiting for IO from the filesystem (CIFS mount in your caes). I'm not sure if there's anything we can do here, besides having a better UI which informs the user that there's no progress...

**Comment by aksdb** [comment] 2017-06-16 07:45
Yes, the behavior is explainable. But it's still not a good behavior. In these cases where restic hangs in state D, the only thing I can do is reboot. Restic cannot be killed (because, as the StackOverflow post explains, the process is blocked) but therefore I also cannot unmount (to remount) the apparently defective mount point. Restic therefore keeps me no other choice than to reboot the machine.

These "Bad file descriptor" errors also indicate, that CIFS doesn't cope with something (maybe many parallelly opened file handles? too many files per directory? something along those lines), so there is definitely something wrong with CIFS that should be handled better on the driver side. If possible, restic should still be "forgiving" in the case of "unstable" mount points / filesystems.

Just in case: before switching to restic, I used attic and borg for backup. They had some problems from time to time (maybe due to the same CIFS errors), but they didn't block endlessly and just finished/cancelled at some point.

**Comment by fd0** [comment] 2017-06-16 10:16
I agree that the situation is very bad for you as a user. I'd be very annoyed to if I had to reboot my machine in this situation. However, I'm not convince that restic is to blame here, I agree with you that the CIFS implementation may be faulty. If we find a way to make restic more "forgiving", I'd gladly implement it!

I'm trying to find out what makes restic different from the other programs. It is implemented in Go, which means that for blocking IO, there may be a different OS thread per operation. restic uses a few open files on the repository in parallel. In addition, it catches SIGINT (^c) to properly clean up locks it left in the repo. This obviously doesn't work if the mount is broken. Hm.

How did you try to kill restic? Maybe that is the problem. Is this issue reproducible? When it happens the next time, could you try to press `C-\`, or manually send `SIGABRT` to the process with `pkill -ABRT restic`. The Go runtime will then print the current stacks for all Goroutines (not so interesting) and the program is terminated.

**Comment by aksdb** [comment] 2017-06-18 08:48
The actual backup mostly runs as cron job, so I usually can't take a look. I just notice that there are no new snapshots for quite some time and then find out via "ps ax | grep restic" that there is still some old process running and locking the repo. `restic snapshots` apparently still works (so the filesystem isn't completely gone). I can also touch, delete, move, etc. files on the mount point.

At one point I thought "well, the process hangs for hours now, so it's probably not doing anything anyway", unlocked the restic repo, and ran a "restic check" on it. It also threw the "bad file descriptor" two or three times and suddently it also ceased working - the progress didn't increase but the mb/s counter decreased constantly. After about 10 minutes without further progress I hit ctrl+c, it printed that it's cleanup / quitting (I don't remember the actual wording), but the process didn't actually end (`ps ax` showed it to be stuck in state D as well).

Apart from SIGINT I also tried SIGKILL and SIGTERM - neither of them helped to kill the process. I didn't know Go had special handling for SIGABRT, but will gladly try that to narrow the problem, the next time I find restic hanging in state D :-)

**Comment by fd0** [comment] 2017-09-29 19:06
So, did you experience the issue again? I'm inclined to close this issue for now because we don't have a way to improve this. What do you think?

**Comment by aksdb** [comment] 2017-10-02 08:31
I haven't had a problem since a few weeks. I played around with CIFS a bit more and think the following solution circumvented the problem:
Putting `options cifs enable_oplocks=0` into `/etc/modprobe.d`.

I don't know, why it is only restic that runs into this problem, but at least it works now (or at least it seems so :-)) If you don't have any further idea what restic could do differently regarding IO, I guess you can close this ticket.

**Comment by fd0** [comment] 2017-10-02 09:22
Ok, thanks for the feedback!

**Closed by fd0** 2017-10-02 09:22 UTC
Labels: feedback needed, undecided
