### ISSUE TITLE
"Say Thanks" link goes to a 404

### ISSUE THREAD

**Issue by philipmw** [restic/restic#2726] opened 2020-05-11 00:43 UTC
I want to make a donation to restic. The github README includes a "Say Thanks" link, which goes to https://saythanks.io/to/restic, but that URL returns a 404!

Please update the README to include one or more ways I can financially support this project.

**Comment by rawtaz** [comment] 2020-05-11 03:05
@philipmw Unfortunately donations won't happen, see #2415. But the link is indeed not working, I'll leave this issue open so we can look into that at some point (not a high priority right now). Thanks!

**Comment by greatroar** [comment] 2020-05-11 18:16
Duplicate of #2590.

**Comment by rawtaz** [comment] 2020-05-11 18:19
Nice catch @greatroar.

**Closed by rawtaz** 2020-05-11 18:19 UTC
Labels: category: user interface, state: need investigating
