### ISSUE TITLE
[AWS S3] Fail to run init command with client.BucketExists: Access Denied 

### ISSUE THREAD

**Issue by blackpiglet** [restic/restic#4085] opened 2022-12-13 03:12 UTC
Output of `restic version`
--------------------------
v0.14.0

How did you run restic exactly?
-------------------------------
`restic init --repo=s3:s3-us-east-2.amazonaws.com/bucket-name/prefix/restic/default --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS S3

Expected behavior
-----------------
Should finish without any error reported.

Actual behavior
---------------
failed: client.BucketExists: Access Denied.\n\n: exit status 1

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
My problem is exactly same with issue #1477. I think previous fix is break with PR #3798
https://github.com/restic/restic/pull/3798#issuecomment-1347638635

Do you have an idea how to solve the issue?
-------------------------------------------
In function `isAccessDenied `, change error.Code from `Access Denied ` to `AccessDenied `.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Sure. Thanks for creating this great tool.

May I ask whether there is plan for v0.14.0's patch?

**Comment by jsobiecki** [comment] 2023-02-08 08:30
I can confirm I run into similar problem. I have backups stored in single bucket, but with different prefixes. I'm able to create new files and create structure I want. But what I see in logs is:
```
restic repository is not ready: error running command=restic init --repo=s3:https://s3.[REDACTED]/backups/backup-live/restic/[REDACTED]-173-production --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:https://s3.[REDACTED]/backups/backup-live/restic/[REDACTED]-173-production failed: client.BucketExists: Access Denied.\n\n: exit status 1
```
I'm using minio instance as S3 provider.

**Comment by blackpiglet** [comment] 2023-02-08 11:31
v0.15 and v0.15.1 should already have the fix.

**Comment by MichaelEischer** [comment] 2023-02-09 22:17
Looks like we forgot to close the issue after merging #4086.
@jsobiecki Please open a new issue if this is still a problem with restic 0.15.0/0.15.1.

**Closed by MichaelEischer** 2023-02-09 22:17 UTC
