### ISSUE TITLE
restic init hangs if AWS region not specified

### ISSUE THREAD

**Issue by canton7** [restic/restic#2597] opened 2020-02-22 12:59 UTC
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------

```
export RESTIC_REPOSITORY="s3:s3.amazonaws.com/my-bucket"
export AWS_ACCESS_KEY_ID="..."
export AWS_SECRET_ACCESS_KEY="..."
export RESTIC_PASSWORD="..."

restic init
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

An S3 bucket, located in the London region (eu-west-2)

Expected behavior
-----------------

Resitc initializes the repository.

Actual behavior
---------------

Restic hangs indefinitely with no output.

If I add `-o s3.region="eu-west-2"`, then the repository is initialized as expected.

Steps to reproduce the behavior
-------------------------------

Follow the instructions in [Setting up Restic with Amazon S3](https://restic.readthedocs.io/en/stable/080_examples.html#setting-up-restic-with-amazon-s3), but create the bucket in the London (eu-west-2) region.

**Comment by rawtaz** [comment] 2020-03-31 03:35
@canton7 Thanks a lot for reporting this. I'd like to ask you for some verification and info. Can you tell me:

- The region you are using is not the default one for your account, is that correct? Im asking because if it was the default one, I would expect this to work without you having to use `-o s3.region="..."` or `AWS_DEFAULT_REGION`.

- Where in the S3 dashboard or similar can a user find the technical name for the region they should specify in `-o s3.region="..."` or `AWS_DEFAULT_REGION`?

I'm thinking we need to update the documentation article you linked to. The adjusting of region is mentioned in https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3 but not in the https://restic.readthedocs.io/en/stable/080_examples.html#setting-up-restic-with-amazon-s3 that you linked to. So assuming what I asked above is correct, we need to update the latter.

**Comment by canton7** [comment] 2020-03-31 08:56
https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3 says:

> If needed, you can manually specify the region to use by either setting the environment variable `AWS_DEFAULT_REGION` or calling restic with an option parameter like `-o s3.region="us-east-1"`. If the region is not specified, the default region is used. **Afterwards, the S3 server (at least for AWS, `s3.amazonaws.com`) will redirect restic to the correct endpoint.**

(Emphasis mine).

This doesn't appear to be happening (although I'm not sure whether the blame for this lies with restic or AWS).

My understanding is that there's no default region for an AWS account -- any mention I find of default regions on google refers to tooling, where you can specify a default region in a tool for the tool to use. When I log into the AWS console I start off in eu-west-1 (which is the region I put my S3 bucket in), although my understanding is that this just takes you to your last-used region, and doesn't indicate a default.

My interpretation of "the default region is used" in the doc above is that if `-o s3.region` isn't used, then the default specified by `AWS_DEFAULT_REGION` is used (and if this isn't set, presumably some internal default is used?).

If you click the region selector in the top right of the AWS console, you get a list of all regions:

![List of regions in AWS Console](https://user-images.githubusercontent.com/568104/78007027-a19b6c80-7335-11ea-8dba-819e2e9f0c70.png).

So, my interpretation of this issue is that either the line "Afterwards, the S3 server (at least for AWS, `s3.amazonaws.com`) will redirect restic to the correct endpoint" is wrong (in which case it should be removed, and replaced with documentation saying that the region must always be specified, and the tutorial updated), or restic isn't correctly handling this redirect (in which case restic should be fixed).

**Comment by MichaelEischer** [comment] 2022-05-15 14:31
Duplicate of #2279.

**Closed by MichaelEischer** 2022-05-15 14:31 UTC
Labels: help: wanted, category: documentation, backend: s3
