### ISSUE TITLE
Add --json option to "restic snapshots" (feature)

### ISSUE THREAD

**Issue by yhafri** [restic/restic#726] opened 2017-01-18 07:24 UTC
## Output of `restic version`

Any

## Expected behavior

Being able to embed the result of `snapshots` in other services (ex. daily nice formatted HTML report).

```
$ restic --json -r /tmp/backup snapshots
{
  [ "id:"40dc1520", "date":"2015-05-08 21:38:30", "host":"kasimir", "tag":"", "directory":"/home/user/work" ],
  [ "id:"79766175", "date":"2015-05-08 21:40:19", "host":"kasimir", "tag":"", "directory":"/home/user/work" ]
}
```

## Actual behavior

```
$ restic -r /tmp/backup snapshots
ID        Date                 Host    Tags   Directory
----------------------------------------------------------------------
40dc1520  2015-05-08 21:38:30  kasimir        /home/user/work
79766175  2015-05-08 21:40:19  kasimir        /home/user/work
```

**Comment by fd0** [comment] 2017-01-18 11:14
Interesting idea, thanks for reporting it!

**Comment by yhafri** [comment] 2017-01-31 14:55
Fantastic job @fd0. 
I'll start testing and report any issue I may found

**Comment by yhafri** [comment] 2017-01-31 16:31
And special thanks to @ibib for the PR

**Comment by yhafri** [comment] 2017-02-26 21:35
Hi guys

Can we extend this *--json* feature to the *find* command?
Something like:

`$ restic --json find -s 82a6e9de *.pdf`

@ibib @fd0 your thoughts on this please ?

**Comment by ibib** [comment] 2017-02-27 08:04
Sounds great. My masterplan is to implement a JSON output for every command.

The Problem is that i cant give you a timeline for it.

**Comment by yhafri** [comment] 2017-02-27 08:07
@ibib excellent
As I've told @fd0 before, we can donate for it if you're interested.

**Comment by fd0** [comment] 2017-02-27 19:25
I think it's a good idea (I've talked about it with @ibib already). I'm going to close this issue, since the option for the `snapshots` command is already implemented.

**Closed by fd0** 2017-02-27 19:25 UTC
Labels: enhancement
