### ISSUE TITLE
Bash pipe with head leaves the repository locked

### ISSUE THREAD

**Issue by dimejo** [restic/restic#2196] opened 2019-03-03 14:45 UTC
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic snapshots | head -n 10`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------

Actual behavior
---------------
```
restic check
using temporary cache in /tmp/restic-check-cache-600586774
repository 08168f89 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-600586774
create exclusive lock for repository
Fatal: unable to create lock in backend: repository is already locked by PID 28123 on host.example.net by root (UID 0, GID 0)
lock was created at 2019-03-03 15:34:11 (13.666345407s ago)
storage ID 8f80d61c
```

Steps to reproduce the behavior
-------------------------------
See above.

Do you have any idea what may have caused this?
-----------------------------------------------
I've no idea why the lock isn't removed when head is involved, but i've tried the same with `tail` and `grep` which don't seem to leave a lock behind.

Maybe this is related to my system:
`CentOS Linux release 7.6.1810 (Core)` with `head (GNU coreutils) 8.22`

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by ibib** [comment] 2019-03-03 17:11
I would say it is working as intended.
https://unix.stackexchange.com/revisions/84828/2

**Comment by dimejo** [comment] 2019-03-04 08:05
Thanks for the link, but I'm not sure if I understand correctly. Why doesn't `tail` behave the same way as `head`?

**Comment by fd0** [comment] 2019-03-04 12:44
This issue is a duplicate of #1466. It works with `tail` because `tail` reads all lines printed by restic, so `SIGPIPE` is not sent to the process. On the other hand, `head` only reads the first 20 lines and then terminates, causing the shell to send `SIGPIPE` to restic.

**Closed** 2019-03-04 12:45 UTC
Labels: duplicate
