### ISSUE TITLE
Consider shipping release tarball with vendored dependencies

### ISSUE THREAD

**Issue by illiliti** [restic/restic#3647] opened 2022-02-13 19:33 UTC
Output of `restic version`
--------------------------

0.12.1

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Add release tarball with vendored dependencies. For example, [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/vendor) does this by simply maintaining vendor directory. You can also setup CI to vendor dependencies into release tarball without needing to keep vendor directory within repository. Here is the command that can be used for this: `go mod vendor`

What are you trying to do? What problem would this solve?
---------------------------------------------------------

With vendored dependencies, i can build restic from source **without internet connection** by using this command: `go build -mod=vendor`

**Comment by illiliti** [comment] 2022-02-13 19:35
Please reconsider https://github.com/restic/restic/issues/2482 because vendoring produces self-contained code which allows offline builds.

**Comment by MichaelEischer** [comment] 2024-05-25 20:52
Duplicate of #3945

**Closed by MichaelEischer** 2024-05-25 20:52 UTC
