### ISSUE TITLE
Stale lock persists on cloud storage

### ISSUE THREAD

**Issue by anothernewusername** [restic/restic#3732] opened 2022-05-01 11:58 UTC
### What's the version of restic you used?
restic 0.13.0 compiled with go1.18 on linux/amd64

### What commands did you execute to get to where the bug occurred?
Using a persistend systemd timer calling a systemd service "restic-backup.service" with a "restic-backup.conf" file every day at 00:00 basically using "restic -r sftp:path/to:/repo backup".
1. Backing up to my local NAS --> no problems
2. Backing up to a cloud storage (Hetzner Storagebox) --> peristend stale lock every now and then

### What did you expect?
Backing up to cloud storage and continue the backup / start a new backup in case the source machine shuts down while backup was still in process. Realizing the stale lock and removing it after 30 min like described in the docs.

### What happened instead?

> Mai 01 13:32:25 machine restic[5452]: unable to create lock in backend: repository is already locked by PID 66938 on machine by user (UID 1000, GID 1000)
> Mai 01 13:32:25 machine restic[5452]: lock was created at 2022-04-27 22:54:55 (86h37m30.571878722s ago)

### Are you aware of a way to reproduce the bug?
Seems like shutting down my pc during the backup process to the cloud storage is all it takes to create a persisting stale lock. 

### Additional information
- Backing up to cloud storage is much slower than to my local NAS due to low upload speed.
- Backup to cloud storage waits for backup to NAS to be completed

**Comment by MichaelEischer** [comment] 2022-05-02 19:46
From the description here it looks like this is a duplicate of #2736. If the machine shuts down while the backup runs, it is possible to leave a lock behind. In that case you'd have to manually call `unlock`.

However, something seems to be missing from the description. Running the `backup` command _cannot_ cause this exact warning. So please provide the actual commands you've run.

**Comment by anothernewusername** [comment] 2022-05-03 20:51
Thank you for your quick reply. My backup automation consists of a systemd timer, a systemd user service and an environment file.


My systemd.timer:

```
[Unit]
Description=daily backup with restic to storagebox

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
```

My systemd user service:
```
[Unit]
Description=Restic backup service

# order: restic-backup-nas --> restic-backup-storagebox --> restic-prune-nas --> restic-prune-storagebox
After=restic-backup-nas.service

# Watch the service for 120 s trying to start
StartLimitIntervalSec=120

# Limit the allowed attempts within the watched timeframe to 10
StartLimitBurst=10


[Service]
Type=oneshot
ExecStart=restic backup --verbose --tag systemd.timer --tag *TAG* $BACKUP_EXCLUDES $BACKUP_PATHS
ExecStartPost=restic forget --verbose --tag systemd.timer --tag *TAG* --group-by "paths,tags" --keep-daily $RETENTION_DAYS --keep-weekly $RETENTION_WEEKS --keep-monthly $RETENTION_MONTHS --keep-yearly $RETENTION_YEARS
EnvironmentFile=%h/.config/restic-backup-storagebox.conf

# Retry starting the service after exiting with failure code
Restart=on-failure

# Wait for 10 s before retrying to start the service
RestartSec=10
```

My EnvironmentFile:
```
BACKUP_PATHS="/home/*user*"
BACKUP_EXCLUDES="--exclude-file /home/*user*/.restic_excludes --exclude-if-present .exclude_from_backup"
RETENTION_DAYS=7
RETENTION_WEEKS=4
RETENTION_MONTHS=12
RETENTION_YEARS=10
RESTIC_REPOSITORY=sftp:*storagebox*:
RESTIC_PASSWORD=*password*
```

I *renamed* some tags, paths and user names due to privacy reasons. Please let me know if there is any more information I can provide.

**Comment by MichaelEischer** [comment] 2022-05-07 09:34
The failing command here is `forget`. So you'll probably have to add a call to `unlock` before that. Just make sure that you use at least restic 0.10.

**Comment by anothernewusername** [comment] 2022-05-11 19:47
Thank your for pointing this out. I moved `forget` in my prune script (`forget --prune`) to reduce the possible occasions for this error as it only runs once a month.
Is it safe to use `unlock` in an automated script? There seems to be a problem with realizing the lock as a stale one (in my case) so I wonder if restic will recognize a legit lock?

**Comment by MichaelEischer** [comment] 2022-05-14 14:07
> There seems to be a problem with realizing the lock as a stale one (in my case) so I wonder if restic will recognize a legit lock?

All commands except `unlock` never check whether a lock is stale. They just check whether any lock exists. In contrast, `unlock` will remove all locks that are older than half an hour. That assumes that all hosts accessing the repository have reasonably synchronized clocks (and use restic >= 0.10.0). For SFTP that is AFAICT sufficient to prevent lock problems.

For certain other backends #3569 is necessary to prevent a race condition related to backups that are interrupted suspending a host.

**Comment by anothernewusername** [comment] 2022-05-22 18:24
Thank you again for the explanation.  Seems to work fine so far! Issue could be closed from my side.

I know asking for dates is rude but still I am curious when the mentioned PR could be merged? Maybe you can share some information like "within the year" or "next major release"?

**Comment by MichaelEischer** [comment] 2022-05-23 19:47
The main bottleneck is maintainer time. I hope @fd0 finds time for the PR before the next release, but I obviously can't promise anything more specific.

**Closed by MichaelEischer** 2022-05-23 19:47 UTC
Labels: state: need feedback
