### ISSUE TITLE
B2 backup super slow

### ISSUE THREAD

**Issue by segersniels** [restic/restic#2673] opened 2020-03-29 17:57 UTC
Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.13.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic -r b2:<bucket> --option b2.connections=50 backup <dir>`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
> Backblaze B2

Expected behavior
-----------------
Restic initial backups don't take hours to backup directories that are only a couple of GB big.

Actual behavior
---------------
Restic is uploading at a speed between 5 and 50KB/sec (as seen in nethogs). Also worth noting that I get 1Gbps down and 40Mbps up from my ISP. 

Steps to reproduce the behavior
-------------------------------
- Try to backup a directory using a B2 backend

Do you have any idea what may have caused this?
-----------------------------------------------
Not sure since everything else is working perfectly fine 😞 

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Of course! I'm planning to use it as my backup tool for the foreseeable future. If I ever figure out why it uploads so slow though 😅

**Comment by MichaelEischer** [comment] 2020-03-29 19:35
Such slow upload speeds are indeed unexpected. For local low-latency backup targets restic is easily able to saturate a 1Gbps connection, so even with the higher latency of Backblaze your 40Mbps upload should be the bottleneck. Restic packs file chunks into packs with a size of a few MB which are then uploaded via HTTPS. 
Have you set any special environment variables? What output does the backup command print?

Can you please try to manually upload a file with several MB into that B2 bucket?

**Comment by segersniels** [comment] 2020-03-29 19:47
> What output does the backup command print?

```
repository f1210de6 opened successfully, password is correct
[24:00] 13.80%  226 files 3.023 GiB, total 3624 files 21.911 GiB, 0 errors ETA 2:30:06
```

> Have you set any special environment variables?

```
B2_ACCOUNT_ID=
B2_ACCOUNT_KEY=
RESTIC_PASSWORD=
```

**Comment by segersniels** [comment] 2020-03-29 19:51
> Can you please try to manually upload a file with several MB into that B2 bucket?
It literally takes a second or something to upload a file manuall.

**Comment by MichaelEischer** [comment] 2020-03-29 20:08
I assume you've already tried to restart the backup run?

**Comment by segersniels** [comment] 2020-03-29 20:24
> I assume you've already tried to restart the backup run?

Yes, multiple times and even tried rebooting.

**Comment by rawtaz** [comment] 2020-03-30 22:06
Would it be possible for you to try [using the rclone backend](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) with your B2?

In general I think the state of this issue is that it needs to be isolated, and one way to do that is to try the same operation with different transports. Besides trying another transport against B2, it would also be interesting to try the same backup run with a different backend, e.g. [REST-server](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#rest-server). I mean just temporarily, so it shouldn't be too costly if you just get a VPS for a day or so.

**Comment by MichaelEischer** [comment] 2020-04-19 08:55
@segersniels Could you test whether you get a reasonable backup performance when backing up a single 1GB file, as in #2696. You can create that file e.g. using `dd if=/dev/urandom of=test bs=1m count=1024`.

Do you use the EU or US region of B2? It apparently makes a large difference regarding performance, whether you use the nearby region or not.

**Comment by MichaelEischer** [comment] 2020-05-23 09:28
Closing this as the issue rather looks like it's not actually caused by restic. Feel free to comment if this issue hasn't resolved itself by now.

**Closed by MichaelEischer** 2020-05-23 09:28 UTC
Labels: backend: b2, category: backup, state: need feedback, state: need investigating

**Comment by tfluehmann** [comment] 2021-02-17 15:34
I am facing a similar issue with small files. I receive notifications from google cloud storage when a file has been updated, I fetch the file and move it to a b2 restic repository.
The files I am backing up are ~5KB each and I do one by one. In the beginning it was pretty fast, but the more files I backup, the slower it gets.

Here my logs with the timestamps
```
"timestamp": "2021-02-17 15:19:35,063", "message":"downloaded file: /backups/5cf6dbe4-e316-42ab-aeb4-542370c28a49.json"
"timestamp": "2021-02-17 15:19:35,063", "message":"file_path to backup: /backups/5cf6dbe4-e316-42ab-aeb4-542370c28a49.json"}
"timestamp": "2021-02-17 15:19:35,063", "message":"executing command: /usr/bin/restic -o b2.connections=100 --verbose=3 --no-lock snapshots --host test"}
"timestamp": "2021-02-17 15:19:41,490", "message":"File exists, run backup command"}
"timestamp": "2021-02-17 15:19:41,490", "message":"executing command: /usr/bin/restic -o b2.connections=100 --verbose=3 --no-lock backup /backups/5cf6dbe4-e316-42ab-aeb4-542370c28a49.json"}
"timestamp": "2021-02-17 15:20:28,215", "message":"Backup created for file: /backups/5cf6dbe4-e316-42ab-aeb4-542370c28a49.json"}
```
As you can see, the timestamps between the backup command and log when it finished is 47 seconds which is extremely long for a 5KB file from my point of view.

I've set the following environment variables in my environment:
```
RESTIC_PASSWORD_FILE=
RESTIC_REPOSITORY=b2:my-bucket:my-repository
B2_ACCOUNT_ID=
B2_ACCOUNT_KEY=
TMPDIR=
RESTIC_CACHE_DIR=
```
Since I use restic for each file and delete the file afterwards,  I cannot use rclone from what I've seen so far.
Do you have any further inputs how I can improve the speed? Or is there a limitation in terms of repository size/amount of files per repository?

**Comment by MichaelEischer** [comment] 2021-02-17 21:08
@tfluehmann How many snapshots does your repository contain? Does `restic list locks` print more than one line? By the way the `backup` command always ignores the `--no-lock` option. Is the `RESTIC_CACHE_DIR` always the same path? The backup command should print several lines of output. At which point does it stall? Which restic version are you using? 0.12.0 could be quite a bit faster here.

restic can handle snapshots without problems which contain several million files. In regards to the number of snapshots I wouldn't recommend more than a few hundreds as everything above that will slow down the startup of several commands.

**Comment by tfluehmann** [comment] 2021-02-17 21:52
@MichaelEischer thanks for your reply.
`restic list locks` does not show more than one lock usually. I had this problem in the beginning a couple months ago but that is fixed now.
`RESTIC_CACHE_DIR` stays the same all the time yes. I am using restic version 0.12.0 since yesterday, it helped a bit, but sadly not a complete game changer.
Our large repository contains around 50k snapshots, one for every file stored in it, since I have to backup each file one by one when they arrive.
Is there a way to combine snapshots?

Here is the complete output of a backup I just created with an example file.
```
backup@report-backup:~$ restic -o b2.connections=100 --verbose=3 backup ./file
open repository
repository d5ad6f44 opened successfully, password is correct
lock repository
load index files
no parent snapshot found, will read all files
start scan on [./file]
start backup on [./file]
scan finished in 16.246s: 1 files, 4 B
new       /file, saved in 0.005s (4 B added)

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:      1 new
Tree Blobs:      1 new
Added to the repo: 360 B

processed 1 files, 4 B in 0:27
snapshot 5e2d6026 saved
```
I think loading the index files and scanning for the file took most of the time. As you can see, a small 4B file took 27 seconds to be stored.
Running restic check also literally takes forever to load indexes.

**Comment by MichaelEischer** [comment] 2021-02-21 19:28
> Our large repository contains around 50k snapshots, one for every file stored in it, since I have to backup each file one by one when they arrive.
> Is there a way to combine snapshots?

So far it's not possible to modify snapshots after they were created. 50k snapshots definitely sound like these could be the cause of the performance problem. What probably take most of the time is that restic has to list all existing snapshots in the repository, which for that amount of snapshots will take several rounds of communication with the backend. Solving that scaling problem will require changes to the repository format, see #523.

Restic normally scans all snapshots to avoid reading all files over and over again. However, as you're just backing up a single file which always changes, you could use `backup --force ...` to let restic skip listing the snapshots.

> I think loading the index files and scanning for the file took most of the time. As you can see, a small 4B file took 27 seconds to be stored.
> Running restic check also literally takes forever to load indexes.

Which version of restic are we talking about here? The most time consuming step here is probably once again reading all the individual snapshot file.

**Comment by tfluehmann** [comment] 2021-02-22 10:24
> Restic normally scans all snapshots to avoid reading all files over and over again. However, as you're just backing up a single file which always changes, you could use backup --force ... to let restic skip listing the snapshots.

Okay thanks for the hint. I'll try it with `--force` for the backup.

> Which version of restic are we talking about here? The most time consuming step here is probably once again reading all the individual snapshot file.

I updated restic to version 0.12 last week.

**Comment by tfluehmann** [comment] 2021-02-22 11:55
> > Restic normally scans all snapshots to avoid reading all files over and over again. However, as you're just backing up a single file which always changes, you could use backup --force ... to let restic skip listing the snapshots.
> 
> Okay thanks for the hint. I'll try it with `--force` for the backup.
> 
> > Which version of restic are we talking about here? The most time consuming step here is probably once again reading all the individual snapshot file.
> 
> I updated restic to version 0.12 last week.

I tried out the --force flag for the backup and it increased the speed to ~12 seconds for the same small backup mentioned above.

**Comment by aawsome** [comment] 2021-02-22 17:09
> since I have to backup each file one by one when they arrive.

If you backup only single files, you'll also have lots of index files if you don't run `prune` or `rebuild-index` regularly. If you don't want to prune, you can run `rebuild-index` which is also very fast with 0.12.0.
