### ISSUE TITLE
backup a lot faster with new hostname

### ISSUE THREAD

**Issue by flibustenet** [restic/restic#1074] opened 2017-07-02 08:30 UTC
## Output of `restic version`
restic 0.7.0 (v0.7.0-1-ge7577d7)
compiled with go1.8 on linux/amd64
rest-server 0.9.3 (v0.9.3-0-gb2e4715) compiled with go1.8 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

On the server
```
$ rest-server --path restic-repo/
```
Locally
```
$ export RESTIC_REPOSITORY=rest:http://bck:8000/repo
$ restic init
$ restic backup projets/flibuste
scan [/home/wilk/projets/flibuste]
scanned 2579 directories, 9914 files in 0:00
[2:13] 100.00%  1.084 MiB/s  144.171 MiB / 144.171 MiB  12493 / 12493 items  0 errors  ETA 0:00 
duration: 2:13, 1.08MiB/s
snapshot 77173222 saved
```
Now i make a new backup without any change
```
$ restic backup projets/flibuste
using parent snapshot 77173222
scan [/home/wilk/projets/flibuste]
scanned 2579 directories, 9914 files in 0:00
[0:38] 100.00%  3.787 MiB/s  144.171 MiB / 144.171 MiB  12493 / 12493 items  0 errors  ETA 0:00 
duration: 0:38, 3.73MiB/s
snapshot eff9b547 saved
```
Again a new backup but i set a new hostname
```
$ restic backup --hostname h projets/flibuste
scan [/home/wilk/projets/flibuste]
scanned 2579 directories, 9914 files in 0:00
[0:03] 100.00%  47.109 MiB/s  144.171 MiB / 144.171 MiB  12493 / 12493 items  0 errors  ETA 0:00 
duration: 0:03, 39.97MiB/s
snapshot cd1448eb saved
```
## What backend/server/service did you use?

rest-server

## Expected behavior

backup with same hostname should be as fast as backup with different hostname.
Say differently, backup without change could be a lot faster ! (indeed, except this problem i found the same duration with rsync, which is very fine !)

**Comment by flibustenet** [comment] 2017-07-02 08:55
I did the same tests with minio backend (same server, same data), the results are exactly the same, 3s with `--hostname h`, 39s without `--hostname`.

**Comment by flibustenet** [comment] 2017-07-02 09:16
On local filesystem backend the result are opposite, with different `--hostname` it's slower:
```
$ restic backup --hostname h projets/logics/ -r /tmp/r
scan [/home/wilk/projets/logics]
scanned 9836 directories, 50025 files in 0:01
[0:44] 100.00%  38.245 MiB/s  1.643 GiB / 1.643 GiB  59861 / 59861 items  0 errors  ETA 0:00 
duration: 0:44, 37.81MiB/s

$ restic backup --hostname h projets/logics/ -r /tmp/r
duration: 0:03, 524.95MiB/s

$ restic backup --hostname h2 projets/logics/ -r /tmp/r
duration: 0:19, 85.92MiB/s
```

**Comment by fd0** [comment] 2017-07-02 09:36
Heh, thanks for leaving your observations. The startling behavior you see is caused by restic not (yet) having a local metadata cache. What happens here is:
 * With the rest or s3 backend: Restic finds a previous backup (`using parent snapshot`), so it starts loading metadata. Depending on the latency of the remote and the performance of your system (CPU, memory, cached data) this may be slower than just re-reading and re-hashing all data locally
 * Which incidentally happens when you change the hostname: Restic doesn't find a previous backup (no `using parent snapshot` but knows which blobs have already been saved to the repo, so it re-reads and re-hashes all data but then discovers that it only need to change a tiny bit, so that's fast

For the local backend, all data is readily available with negligible latency, and that's faster than re-reading and re-hashing all data. You should also be able to see a difference in CPU usage and IO bandwidth during backup.

Also, when you change the hostname restic won't find the previous backup, that may be changed in the future.

My plan is to introduce a client-side metadata cache (see #29, #1040), so I'm going to close this issue for now. Please feel free to add further comments.

**Closed by fd0** 2017-07-02 09:36 UTC

**Comment by flibustenet** [comment] 2017-07-02 13:09
Thanks, it's good to understand
