### ISSUE TITLE
No intermediate snapshots on large uploads

### ISSUE THREAD

**Issue by olistrut** [restic/restic#1489] opened 2017-12-19 15:25 UTC
## Output of `restic version`
0.8.0 
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
 /usr/local/bin/restic  -r b2:[repoName] backup [directory]
Backing up to a Backblaze repository from a local HDD 

## What backend/server/service did you use to store the repository?
B2

## Expected behavior
With a very large initial or incremental back (in this case: ~1.5TB over a 5Mbit/s uplink) the initial backup (as well as incremental backups with significant volume of new data) will take up a lot of time. I am currently expecting ~2 months for full initial backup. 

When running this large initial backup, restic should create snapshots at reasonable intervals (e.g., every 12 hours) to create a consistent state if - for whatever reason - the upload is interrupted. If the initial upload is interrupted, it should also be possible to restore any data already uploaded.

## Actual behavior
When a large incremental upload is interrupted, checking the repository results in a large volume of packs not referenced in any index. Pruning would delete this data. During the period of the initial upload it is also not possible to list or restore any data already uploaded.

Currently, the only workaround would be to manually select e.g., individual smaller directories to upload sequentially. 

[Note: even with periodic snapshots, a limited amount of data might still be in unreferenced packs. This is ok. However, periodic snapshots would significantly reduce the amount of data in unreferenced packs.]

## Steps to reproduce the behavior

Start backing up large volume of new data
Interrupt upload (e.g., through Ctrl-C)
Run repository check (will result in error messages)
or 
Try to list snapshots/restore data (will result in no data found to be restored)

## Do you have an idea how to solve the issue?
Introduce an optional "max-upload-time" argument that would terminate the backup process in an orderly fashion (saving a snapshot) after a specified number of hours or days.

**Comment by rawtaz** [comment] 2017-12-19 16:14
I'm sorry if I'm a bit sceptic, but why should work be spent implementing this, when you can easily back up individual parts of the total you want to back up, to effectively get the same thing done? It's a one-time thing.

**Comment by fd0** [comment] 2017-12-19 19:54
Thanks for reporting this. While the idea seems to be nice, there are several problems with it. Among others, what should be contained in these intermediate snapshots? After the backup, they need to be removed again.

There are two things that you can do:
 * What's already implemented is that restic regularly (at least every five minutes or so) writes intermediate index files which list the files already uploaded. When the backup is interrupted and restarted, restic reads the index files and knows which blobs are already present in the repo (those are not uploaded again). So it'll continue uploading roughly where it left of.

 * If you need intermediate snapshots, I'd like to suggest using a local hard drive and backup into the drive for two months. During the time, use `rclone` to slowly sync the repo to B2. This is possible because restic will only add files when a new snapshot is added. When the sync is complete, save new backups directly into the repo at B2.

I'm closing this issue for now. Please feel free to add further comments. Thanks!

**Closed by fd0** 2017-12-19 19:54 UTC

**Comment by olistrut** [comment] 2017-12-19 20:26
Thanks for responding so promptly. 

I understand that all data is on B2 even in case of an interruption and will not be uploaded again. This was one of the first things I have tried and it has worked like a charm. 

I think what is confusing me is that no matter how much I have already uploaded, if I were to suffer local data loss before the full initial backup completed, there would be no way for me to recover any of the data already uploaded. In an ideal scenario, the temporary snapshot would allow me to at least recover the data which has been correctly uploaded. This could be either through a command line switch (as initially suggested) or through creating temporary snapshots every x hours (and deleting upon completing the full backup). 

I fully understand if this is not a priority, but wanted to make sure to explain why - from my user perspective - the current behavior seems less than ideal.

**Comment by fd0** [comment] 2017-12-19 20:31
Thanks for the additional explanation!

**Comment by rawtaz** [comment] 2017-12-19 20:41
@olistrut The problem is that even if you could do what you want, i.e. look at a snapshot of what restic had uploaded so far, this would be of limited value because you haven't been in control och which files/directories were prioritized. Even if you list the things to back up in order of importance on the command line when backing them up (assuming you don't just backup one single folder), you might end up in a situation where you want to get e.g. the last set of files/directories in that first folder you backed up. And it might not be there, because restic hadn't gotten that far.

Honestly I'm not sure if restic processes the files simply in the order they would appear if you did e.g. `find`, or if it does it in some other order, but IMO the only sane way to make sure that you can restore what you might want to before some total backup is done, is to start small - first back up the very most important things, then the less and less important things one by one. Only you know what is the most critical items, restic will never be able to know that.
