### ISSUE TITLE
Multiple test failures with stack traces

### ISSUE THREAD

**Issue by ckemper67** [restic/restic#606] opened 2016-09-04 17:50 UTC
I have seen this test fail a couple of times, but it does not seem to be always reproducible. Note that I see two FUSE mounts on my Macbook. Maybe the test failures do not clean up the mount?

## Output of `restic version`
restic compiled manually
compiled at unknown time with go1.6.2 on darwin/amd64

commit e443454c4bc7323a3e5a402af6abb78e1f133e7f
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Sun Sep 4 15:46:50 2016 +0200

    Add OS and Arch to 'version' output

## Expected behavior
Tests pass

## Actual behavior

```
# cmds/restic
Now serving /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-328120637/repo at /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-mount-742795114
Don't forget to umount after quitting!
integration_fuse_test.go:80: Invalid number of snapshots: expected 3, got 2

--- FAIL: TestMount (2.35s)
       	testing.go:24: using low-security KDF parameters for test
       	testing.go:24: using low-security KDF parameters for test
       	lock.go:76: setting lock timeout to 0
       	integration_test.go:51: repository initialized at /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-328120637/repo
       	integration_test.go:64: backing up [/var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-328120637/testdata]
       	integration_test.go:64: backing up [/var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-328120637/testdata]
       	integration_test.go:64: backing up [/var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-328120637/testdata]
Error umounting: unmount /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-mount-742795114: resource busy
helpers.go:215: unexpected error: chmod /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-mount-742795114: read-only file system

error for testdata/0/0/9/37: Lstat: lstat /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-798296398/testdata/0/0/9/37: no such file or directory
error walking dir testdata/0/0/9/37: Lstat: lstat /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-132343135/testdata/0/0/9/37: no such file or directory
error walking dir 0/9: Open: open /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-193273988/testdata/0/0/9: no such file or directory
index d5697fe0 has old format
index d5697fe0 has old format
error for /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir: lchown /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir: operation not permitted
Lchown
restic/errors.Wrap
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/errors/wrap.go:22
restic.Node.restoreMetadata
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:155
restic.(*Node).CreateAt
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:142
restic.(*Restorer).restoreNodeTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:102
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:53
restic.(*Restorer).RestoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:122
cmds/restic.CmdRestore.Execute
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/cmd_restore.go:119
cmds/restic.cmdRestoreExcludes
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:92
cmds/restic.cmdRestore
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:82
cmds/restic.TestCheckRestoreNoLock.func1
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:854
cmds/restic.withTestEnvironment
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_helpers_test.go:213
cmds/restic.TestCheckRestoreNoLock
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:855
testing.tRunner
       	/usr/local/opt/go/libexec/src/testing/testing.go:473
runtime.goexit
       	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1998
error for /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/bar: lchown /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/bar: operation not permitted
Lchown
restic/errors.Wrap
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/errors/wrap.go:22
restic.Node.restoreMetadata
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:155
restic.(*Node).CreateAt
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:142
restic.(*Restorer).restoreNodeTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:122
cmds/restic.CmdRestore.Execute
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/cmd_restore.go:119
cmds/restic.cmdRestoreExcludes
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:92
cmds/restic.cmdRestore
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:82
cmds/restic.TestCheckRestoreNoLock.func1
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:854
cmds/restic.withTestEnvironment
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_helpers_test.go:213
cmds/restic.TestCheckRestoreNoLock
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:855
testing.tRunner
       	/usr/local/opt/go/libexec/src/testing/testing.go:473
runtime.goexit
       	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1998
error for /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/bar2: lchown /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/bar2: operation not permitted
Lchown
restic/errors.Wrap
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/errors/wrap.go:22
restic.Node.restoreMetadata
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:155
restic.(*Node).CreateAt
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:142
restic.(*Restorer).restoreNodeTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:122
cmds/restic.CmdRestore.Execute
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/cmd_restore.go:119
cmds/restic.cmdRestoreExcludes
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:92
cmds/restic.cmdRestore
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:82
cmds/restic.TestCheckRestoreNoLock.func1
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:854
cmds/restic.withTestEnvironment
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_helpers_test.go:213
cmds/restic.TestCheckRestoreNoLock
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:855
testing.tRunner
       	/usr/local/opt/go/libexec/src/testing/testing.go:473
runtime.goexit
       	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1998
error for /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/baz: lchown /var/folders/pg/0mtxyk6155x0qzfr7n8jyr500000gn/T/restic-test-837288907/restore/testdir/baz: operation not permitted
Lchown
restic/errors.Wrap
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/errors/wrap.go:22
restic.Node.restoreMetadata
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:155
restic.(*Node).CreateAt
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/node.go:142
restic.(*Restorer).restoreNodeTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/restorer.go:122
cmds/restic.CmdRestore.Execute
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/cmd_restore.go:119
cmds/restic.cmdRestoreExcludes
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:92
cmds/restic.cmdRestore
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:82
cmds/restic.TestCheckRestoreNoLock.func1
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:854
cmds/restic.withTestEnvironment
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_helpers_test.go:213
cmds/restic.TestCheckRestoreNoLock
       	/Users/ckemper/work/src/github.com/restic/restic/src/cmds/restic/integration_test.go:855
testing.tRunner
       	/usr/local/opt/go/libexec/src/testing/testing.go:473
runtime.goexit
       	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1998
FAIL
```

## Steps to reproduce the behavior
gb test

**Comment by fd0** [comment] 2016-09-04 18:13
Thanks for reporting this, I've seen this a couple of times locally the past days, but haven't gotten around to it.

**Comment by fd0** [comment] 2016-09-15 19:17
I've found the cause for the failed tests, should be fixed soon.

**Closed** 2016-09-15 19:53 UTC
Labels: bug
