### ISSUE TITLE
Minor inconsistency and syntax in command line / man page for verbose option

### ISSUE THREAD

**Issue by clwgh** [restic/restic#4294] opened 2023-04-15 16:15 UTC
Output of `restic version`
--------------------------

`restic 0.15.1 compiled with go1.19.5 on linux/amd64`

How did you run restic exactly?
-------------------------------

To display the command line options
`restic`

To view the man page options
`man restic`

Expected behavior
-----------------

Correct syntax for `verbose` on the command line output and consistency with the man page

Actual behavior
---------------

Running `restic` shows the `verbose` option as follows:

```
-v, --verbose n     be verbose (specify multiple times or a level using --verbose=n, max level/times is 2)
```

Running `man restic` shows the `verbose` option as follows:

```
-v, --verbose[=0]   be verbose (specify multiple times or a level using --verbose=n, max level/times is 3)
```

**Observations**
- The command line output has a minor error – it should state `--verbose=n` (or `--verbose[=n]`) not `--verbose n`, as the space causes an error

```
$ restic -r /media/disk --verbose 2 restore abcd1234 --target Desktop
unknown command "2" for "restic"

Did you mean this?
	ls
```

- The man page output does correctly list the `=` sign but is written as `=0` instead of `=n` (it goes on to use `n` in the description)
- The command line output states the max level is `2` and the man page output states the max level is `3`

Steps to reproduce the behavior
-------------------------------

Run `restic` and `man restic` and observe the descriptions for `verbose` at the end of the options/flags section.

Do you have an idea how to solve the issue?
-------------------------------------------

- Confirm correct syntax and max level and update command line output and man page text to make consistent across both

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I have just discovered restic and think it is fantastic. I'll be using it to manage a couple of TB so have been immersed in the man page and options and examples, hence noticing the minor inconsistency above. Thankyou to the devs and the community for the continued work and support on restic. I'm looking forward to finishing testing and using it properly.

**Comment by MichaelEischer** [comment] 2023-04-17 19:13
Duplicate of #3926. The `=0` shows the default value of the parameter. I don't think cobra allows us to change that.

> * The command line output states the max level is `2` and the man page output states the max level is `3`

This means that the man pages installed on your system and the restic version do not match. We autogenerate (`restic generate --man some/path`) the man pages on each release.

**Closed by MichaelEischer** 2023-04-17 19:13 UTC

**Comment by clwgh** [comment] 2023-04-18 08:22
It's not a duplicate of #3926. I am reporting that the restic help text and the man page text do not align. Whatever the correct syntax, should they not both be reporting the same thing?

> This means that the man pages installed on your system and the restic version do not match.

Then that is a result of following the restic [instructions](https://restic.readthedocs.io/en/stable/020_installation.html). "Once downloaded, the official binaries can be updated in place using the restic self-update command"
```
$ sudo apt install restic
$ restic version
restic 0.12.1 compiled with go1.18.1 on linux/amd64
$ restic
... max level/times is 3
$ sudo restic self-update
successfully updated restic to version 0.15.1
$ restic version
restic 0.15.1 compiled with go1.19.5 on linux/amd64
$ restic
... max level/times is 2
```

**Comment by MichaelEischer** [comment] 2023-04-27 19:50
The different rendering of the help text and the man pages is a result of cobra using different implementations for both cases: https://github.com/spf13/cobra/blob/v1.6.1/doc/man_docs.go#L183 and https://github.com/spf13/pflag/blob/v1.0.5/flag.go#L728 . Neither variant is configurable, such that we'd have to reimplement the relevant part. And I really don't think that's a good idea.

> Then that is a result of following the restic [instructions](https://restic.readthedocs.io/en/stable/020_installation.html). "Once downloaded, the official binaries can be updated in place using the restic self-update command"

This only refers to the binary. The man pages are not updated automatically. Have a look at the `restic generate` command.

**Comment by clwgh** [comment] 2023-04-29 03:18
Thanks Michael, I will explore this next time I am testing. I appreciate the work from you and others in maintaining restic. My report here is from the point of view of a newcomer to restic finding his way through the instructions and noticing this minor inconsistency afterwards.

With more use the more detailed tweaks may become obvious but not so initially. In case it can be improved I'm reporting it as per `CONTRIBUTING.md` : _"However even "minor" details as fixing spelling errors, improving documentation or pointing out usability issues are a great help also."_

Thanks again.
Chris
