### ISSUE TITLE
'unknown command "<path to files>" for "restic' error

### ISSUE THREAD

**Issue by Rhalah** [restic/restic#3440] opened 2021-06-23 13:21 UTC
Just followed instructions at 040_backup.rst and issued the command:

restic -r <path_to_repo> --verbose backup <path to files>

This gives the above error and I had to remove "--verbose" to get it right.
After that, I took a look at the manual and it seems the correct order should be:

restic backup -r <path_to_repo> --verbose <path to files>

Didn't test because I'm doing the backup right now.
Just wanted to point this behaviour.

**Comment by rawtaz** [comment] 2021-06-23 13:56
Please tell us where in the documentation (e.g. the URL to it) you read these instructions.

Please also show the exact command that you ran, and all of its output. Thanks!

**Comment by Rhalah** [comment] 2021-06-23 14:01
> Please tell us where in the documentation (e.g. the URL to it) you read these instructions.
> 
> Please also show the exact command that you ran, and all of its output. Thanks!

Hello!

I followed the instructions here:
https://restic.readthedocs.io/en/stable/040_backup.html
Sorry. Thought that mentioning the file 040_backup.rst would be enough, since I followed the github link in the page.

The exact command was:
restic --repo rhalahrestic --verbose backup /media/rhalah/HD-E1/
that gives the error:
unknown command "/media/rhalah/HD-E1/" for "restic"

**Comment by rawtaz** [comment] 2021-06-23 14:08
Which restic version are you using? If not 0.12.0 (which is the latest release), can you please upgrade to 0.12.0 (either by downloading it here from GitHub's releases or by running `restic self-update`) and see if you can reproduce the problem?

**Comment by Rhalah** [comment] 2021-06-25 17:11
Sorry!
I meant I adapted the line
restic -r /srv/restic-repo --verbose backup ~/work (on the page linked above)
to my case and got the error.
My version is 0.8.3 and it seems it doesn't support self-update feature.
I'll install a newer version and put here if this solves the problem.

Still, in the page
https://restic.readthedocs.io/en/stable/manual_rest.html
It is said that to do a backup one uses:  restic backup [flags] FILE/DIR [FILE/DIR]
Is that not preferable?

Thanks alot!

**Comment by rawtaz** [comment] 2021-06-25 17:30
The `--verbose` option is better shown where it should be places, that is entirely correct. This is fixed in #3442.

There are both global and per-command options in restic, you can see which ones are what by issuing e.g. `restic help backup`. The global ones should be placed before the subcommand such as `backup`, and the command-specific options should be placed after the command but before any of its arguments.

Looking forward to hearing about your retry with 0.12.0, which is a version you should be using now because it has immense performance improvements since 0.8.3.

**Comment by MichaelEischer** [comment] 2021-06-27 16:18
The `--verbose` flag did not exist in restic 0.8.3 (see for example https://restic.readthedocs.io/en/v0.8.3/manual_rest.html). Thus cobra guesses that it could be an option named `--verbose` which accepts one argument, that is `--verbose backup`. That guess is obviously wrong but that explains the symptoms here.

**Comment by MichaelEischer** [comment] 2024-05-25 20:15
Closing as there seems nothing left to be done here.

**Closed by MichaelEischer** 2024-05-25 20:15 UTC
Labels: type: question/problem, state: need feedback
