### ISSUE TITLE
Can we `restic dump` more than one path at a time to get a combined archive ? else can it be added ?

### ISSUE THREAD

**Issue by akharrou** [restic/restic#3588] opened 2021-12-02 08:34 UTC
> restic 0.12.1 compiled with go1.17.2 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Is there a builtin way to dump multiple paths at a time ? If not can this be added ?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Trying to dump more than one directory and combine them into one tar archive file:

```zsh
$> restic dump latest ~/work/dir1 ~/work/dir2  \
    --archive tar | gzip -c > /tmp/work.tgz
```

> also it would be very nice if instead of specifying `--archive FORMAT` followed by piping to gzip etc, we could do something like `--target myarchive.tar.gz` and `restic` could infer what file to write the output to and the format and compression to use.

solves problem of inconvenience, user-interface usability/ease-of-use, not having to repeat command multiple times and spend extra time and effort wrapping with custom scripting.

---

`borg` offers both and allows listing the files that are exported (dumped):

```zsh
$> borg export-tar --list /srv/borg-repo::latest /tmp/work.tgz \
       ~/work/dir1 ~/work/dir2
```

**Comment by MichaelEischer** [comment] 2024-07-04 19:09
Duplicate of https://github.com/restic/restic/issues/4173

**Closed by MichaelEischer** 2024-07-04 19:09 UTC
Labels: type: feature enhancement, help: wanted, category: dump
