### ISSUE TITLE
Many restores lock

### ISSUE THREAD

**Issue by lissom** [restic/restic#3652] opened 2022-02-18 22:06 UTC
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------

The below command is executed on many (let's say 50) machines against the same repo.
`./restic_0.12.1 --json snapshots --tag full latest`
The next step is ./restic_0.12.1 restore id_from_above, so it might be running on other machines.
We need the info out of tags is why we get the snapshot info 1st.  Though it seems like putting latest in restore should force the same behavior with only one command.
A backup happens once an hour.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3

Expected behavior
-----------------

Readers do not lock each other out of operations, rather than waiting 100s, the snapshot id is returned immediately.

Actual behavior
---------------

Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 552.330144ms: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 1.080381816s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 1.31013006s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 1.582392691s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 2.340488664s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 4.506218855s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 3.221479586s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 5.608623477s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 7.649837917s: The specified key does not exist.
Load(<lock/a6015a7fd9>, 0, 0) returned error, retrying after 15.394871241s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 507.606314ms: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 656.819981ms: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 535.697904ms: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 660.492892ms: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 920.315446ms: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 1.090001075s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 1.32137013s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 1.338359384s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 2.984558086s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 1.818837414s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 2.669912672s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 3.268621161s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 6.097818893s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 7.759814515s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 6.775550206s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 6.809451431s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 16.05103845s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 9.0544704s: The specified key does not exist.
Load(<lock/f15a11da2c>, 0, 0) returned error, retrying after 26.244032286s: The specified key does not exist.
Load(<lock/f2aa7aadda>, 0, 0) returned error, retrying after 23.002952479s: The specified key does not exist.

Steps to reproduce the behavior
-------------------------------

Create a snapshot, restore on many machines (say 50) at the same time, this can happen:
get tag_id `./restic_0.12.1 --json snapshots --tag full latest`
use tag_id `./restic_0.12.1 --json restore tag_id` 

Do you have any idea what may have caused this?
-----------------------------------------------

It looks likes readers block each other.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Still evaluating.  Seems like great software :)

**Comment by MichaelEischer** [comment] 2022-02-18 22:15
This is essentially issue #2596, just with a different way to reproduce it.

A workaround could be to pass the `--no-lock` flag to the `snapshots` command.

> Create a snapshot, restore on many machines (say 50) at the same time, this can happen:

Just to make sure this is clear: each machine can read everything that is stored in the repository.

**Comment by lissom** [comment] 2022-02-18 22:30
To clarify your comment, it's perfectly safe to use --no-lock even when snapshots are being created during reading?

Are --no-lock reads, assuming the snapshot being read is guaranteed to be present, safe when `forget` or `prune` operations are taking place (i.e. we're getting latest and only removing snapshots for 30 days ago, with snapshots every hour)? Or would the --no-lock solution require a maintenance window?

Yes, every machine can read everything in the repo is intended.

Having read the old solution, S3 is now consistent, so it should be safe to to read not exists and released.

**Comment by MichaelEischer** [comment] 2022-02-18 22:53
`snapshots --no-lock` will in the worst case exit with an error if a snapshot disappears unexpectedly. However, as the command only reads data, that's the worst than can happen for that command.

> Having read the old solution, S3 is now consistent, so it should be safe to to read not exists and released.

The problem is primarily that the retry strategy is not well adjusted to lock files that are removed while checking.

**Comment by MichaelEischer** [comment] 2022-08-20 15:49
I just noticed that this is a duplicate of #1523.

**Closed by MichaelEischer** 2022-08-20 15:49 UTC
