### ISSUE TITLE
restic didn't find previous snapshot, asks to remove cache directories

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [restic/restic#1872] opened 2018-07-02 21:24 UTC
## Output of `restic version`
restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?

`restic backup --exclude-file=/usr/local/etc/exclude_file.txt --tag=new_backup_2 /`

## What backend/server/service did you use to store the repository?

local backend

## Expected behavior
Restic normally locates a previous snapshot but this time it didn't. It seemed to set a larger than normal __ETA__ but this reduced to a time frame that I expect.

## Actual behavior
restic doesn't print that it located a previous snapshot, instead it shows this:

`found 2 old cache directories in /root/.cache/restic, pass --cleanup-cache to remove them`

## Steps to reproduce the behavior
I upgraded to fedora 28 between this backup and my last backup and installed some programs. I don't know if the large system upgrade confused restic because initially the __ETA__ was about 4 times what I expect based on my last few backups but to iterate again, this time frame greatly reduced.

## Do you have any idea what may have caused this?
I think may be the reason restic didn't output the *"found previous snapshot"* notice is that I didn't use `--verbose` as an option this time. May be you can confirm this?

## Do you have an idea how to solve the issue?

May be restic did find the previous snapshot and that it only tells you when the `--verbose` option is selected.

**Comment by fd0** [comment] 2018-07-11 20:06
Hey, thanks for the report! This is indeed normal behavior: restic finds the previous snapshot by looking at the list of files/dirs to save. In the special case of `/`, it replaces it with the contents of `/`. From before your upgrade to now, something was changed in `/` (which is likely on a full system upgrade). So restic was unable to find a previous snapshot. The algorithm is rather dumb at the moment and could be improved.

When no previous snapshot could be found, restic re-reads all files and dirs, only to then detect that it doesn't need to save most of the data, but you'll still experience much CPU and IO load because everything needs to be read and processed.

The option `--verbose` doesn't have anything to do with it.

By the way, the version you're using is rather old, restic 0.9.1 is the most recent one. In that version, the detection for a previous snapshot has been improved (not a lot, but a tiny bit).

The next backup after the one which took some time should be fast again.

I'm closing this issue for now, it's not a bug. We are however aware that restic is rather dumb in finding a previous snapshot in this situation.

Please feel free to add further comments/feedback! Thanks!

**Closed by fd0** 2018-07-11 20:06 UTC

**Comment by ChukwuemezieChristopherAneke** [comment] 2018-07-30 18:58
Thanks @fd0 for explaining. I did not realise restic was on such a fast release cycle. I will be upgrading when available.

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-06-17 19:44
@fd0 I'm still using quite an old version of restic so I'm trying to upgrade my old version of restic to the latest version, but I'm not sure whether I installed restic from source or installed the binary. How do I know how my version of restic was installed? Does the following `restic version` give any hints?

```
$ restic version
restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64
```

**Comment by dimejo** [comment] 2019-06-18 07:44
This will search for installed packages named restic and output the used respoitory aswell.
`dnf list installed | grep restic`
AFAICT copart/restic provides the latest restic version for Fedora 28 and 30. The easiest procedure would probably be to enable the copr repository again and update restic.

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-06-18 18:39
@dimejo good suggestion. Although I already determined that the restic I installed is not from the copart/restic repository because first of all `restic version` shows:

```
restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64
```
> compiled with go1.10.2 on linux/amd64

is the key because I never installed golang on my system (now I remember getting the beta binary because I didn't want to install yet another programming language just to compile a program)

Secondly from inspecting `dnf history` I found two transactions that contained the pattern `restic` on the command line so I investigated those two transactions by executing the commands (as root):

`dnf history info 7`
transaction 7 showed that I installed restic from the copart/restic repository:
> Packages Altered:
    Install restic-0.8.3-1.fc26.x86_64 @copart-restic

`dnf history info 15`
where as transaction 15 showed that I removed the restic rpm that was installed from the copart/restic repository:

> Packages Altered:
    Removed restic-0.8.3-1.fc27.x86_64 @copart-restic

which leaves the restic binary as the version of restic I have installed in `/usr/bin/restic`
More evidence that my restic executable `/usr/bin/restic` is the precomiled binary is:
> (v0.8.3-266-g9f5565b0)

from the output of restic version. Although I can't find *"(restic-v0.8.3-266-g9f5565b0)"* in the [restic beta download site] (because 0.8.3 is too old so no longer available), I can see that the typical name of a restic beta binary is restic-vMAJOR.MINOR.UPDATE-VERSION-GIT_COMMIT_HASH which matches my installed version of restic perfectly

Lastly `dnf list --installed | grep restic` returned nothing which backs up the above conclusion that I have the restic beta binary installed in `/usr/bin/restic`.

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-06-18 18:50
@dimejo the question now is, will removing `/usr/bin/restic` affect my restic repository? That is, after removing `/usr/bin/restic` then installing the latest restic from the fedora repositories will I be able to continue using my old restic repositories as if nothing changed?

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-06-18 19:47
@fd0 @dimejo how do I uninstall a restic beta binary that was installed in `/usr/bin`? In other words, what is the safest way to uninstall a restic beta binary that was installed in `/usr/bin`?

**Comment by dimejo** [comment] 2019-06-19 08:19
> @dimejo the question now is, will removing /usr/bin/restic affect my restic repository and restic password? That is, after removing /usr/bin/restic then installing the latest restic from the fedora repositories will I be able to continue using my old restic repositories as if nothing changed?

Removing the binary doesn't do anything with your repository. But if v0.8.3 was the last version of restic you've used, you might notice that the first backup with restic v0.9 or newer will take significantly longer. The reason for this is a rework of the archiver code. More on this can be found in the [release notes](https://github.com/restic/restic/releases/tag/v0.9.0).

> @fd0 @dimejo how do I uninstall a restic beta binary that was installed in /usr/bin? In other words, what is the safest way to uninstall a restic beta binary that was installed in /usr/bin?

If this binary was installed manually you can simply remove/replace it. I personally drop manually installed binaries in `/usr/local/bin` because that makes them easier to distinguish from package installations.

PS: Starting with restic v0.9.3 you can easily update manually installed binaries of restic with the comamnd `restic self-update`.

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-06-19 19:25
@dimejo thanks for answering. I also install manually installed binaries in `/usr/local/bin`. restic was one of the first programs I manually installed on linux, at the time I was a beginner so I didn't know linux best practises about installation directories. By the way, how were you notified about my comment? I pinged @fd0 so I am curious to know how you became aware of it. 

It would be useful if you could comment on issue #2312 , thanks

@fd0 I'm seeing this again after I upgraded from fedora 29 to fedora 30 except this time after restic re-read all files and dirs when no previous snapshots could be found it seemed that restic did not detect that it doesn't need to save most of the data
