### ISSUE TITLE
forget does not apply policy --keep-within correctly

### ISSUE THREAD

**Issue by ramos** [restic/restic#2396] opened 2019-09-10 15:42 UTC
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.6 on freebsd/amd64

How did you run restic exactly?
-------------------------------
restic -r b2:XXX forget --keep-within 7m

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
backblaze

Expected behavior
-----------------
Forget all snapshots older than 7 months minus one day (last snapshot was from yesterday)

Actual behavior
---------------
All snapshots are kept

Steps to reproduce the behavior
-------------------------------
restic -r b2:XXX forget --keep-within 7m

Keeps all snapshots:

Applying Policy: all snapshots within 7m of the newest
keep 105 snapshots:
ID        Time                 Host        Tags        Reasons    Paths
-------------------------------------------------------------------------------
XXXXXXXX  2019-03-11 16:23:24  hostname                within 7m  YYY
XXXXXXXX  2019-03-12 12:00:13  hostname                within 7m  YYY
XXXXXXXX  2019-03-13 12:00:11  hostname                within 7m  YYY
XXXXXXXX  2019-03-14 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-03-15 12:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-03-18 12:00:10  hostname                within 7m  YYY
XXXXXXXX  2019-03-19 16:01:05  hostname                within 7m  YYY
XXXXXXXX  2019-03-22 16:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-03-26 16:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-03-27 16:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-03-29 16:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-03-30 16:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-03-31 16:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-02 15:23:39  hostname                within 7m  YYY
XXXXXXXX  2019-04-03 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-04-04 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-05 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-08 12:00:10  hostname                within 7m  YYY
XXXXXXXX  2019-04-09 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-10 12:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-04-11 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-12 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-13 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-14 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-15 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-04-16 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-22 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-23 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-04-24 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-04-26 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-04-27 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-01 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-02 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-05 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-07 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-08 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-09 12:00:12  hostname                within 7m  YYY
XXXXXXXX  2019-05-10 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-12 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-13 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-05-14 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-05-15 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-16 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-17 12:00:12  hostname                within 7m  YYY
XXXXXXXX  2019-05-18 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-19 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-05-20 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-21 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-22 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-23 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-05-24 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-27 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-05-28 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-05-29 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-05-30 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-03 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-04 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-05 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-06-07 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-09 12:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-06-10 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-06-11 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-06-12 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-13 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-06-14 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-06-24 12:00:11  hostname                within 7m  YYY
XXXXXXXX  2019-06-25 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-06-26 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-06-28 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-02 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-04 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-05 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-06 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-08 12:00:16  hostname                within 7m  YYY
XXXXXXXX  2019-07-09 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-10 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-11 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-12 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-13 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-15 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-16 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-17 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-18 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-19 12:00:10  hostname                within 7m  YYY
XXXXXXXX  2019-07-21 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-07-22 12:00:07  hostname                within 7m  YYY
XXXXXXXX  2019-07-25 12:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-07-30 12:00:58  hostname                within 7m  YYY
XXXXXXXX  2019-08-06 12:00:08  hostname                within 7m  YYY
XXXXXXXX  2019-08-09 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-08-10 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-08-12 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-08-14 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-08-15 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-08-26 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-08-27 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-08-29 12:00:06  hostname                within 7m  YYY
XXXXXXXX  2019-08-30 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-08-31 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-09-02 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-09-03 12:00:04  hostname                within 7m  YYY
XXXXXXXX  2019-09-04 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-09-05 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-09-06 12:00:05  hostname                within 7m  YYY
XXXXXXXX  2019-09-09 12:00:05  hostname                within 7m  YYY
-------------------------------------------------------------------------------
105 snapshots

keep 38 snapshots:
ID        Time                 Host        Tags                    Reasons    Paths
-----------------------------------------------------------------------------------------------
XXXXXXXX  2019-01-20 12:48:19  hostname                            within 7m  YYY
XXXXXXXX  2019-01-22 07:02:07  hostname                            within 7m  YYY
XXXXXXXX  2019-01-22 11:00:37  hostname                            within 7m  YYY
XXXXXXXX  2019-01-23 11:10:59  hostname                            within 7m  YYY
XXXXXXXX  2019-01-24 11:00:35  hostname                            within 7m  YYY
XXXXXXXX  2019-01-25 11:11:55  hostname                            within 7m  YYY
XXXXXXXX  2019-01-26 11:35:45  hostname                            within 7m  YYY
XXXXXXXX  2019-01-28 11:00:37  hostname                            within 7m  YYY
XXXXXXXX  2019-01-29 11:00:35  hostname                            within 7m  YYY
XXXXXXXX  2019-01-30 11:00:44  hostname                            within 7m  YYY
XXXXXXXX  2019-01-31 11:00:50  hostname                            within 7m  YYY
XXXXXXXX  2019-02-01 11:00:46  hostname                            within 7m  YYY
XXXXXXXX  2019-02-04 11:00:41  hostname                            within 7m  YYY
XXXXXXXX  2019-02-05 11:00:41  hostname                            within 7m  YYY
XXXXXXXX  2019-02-06 11:00:40  hostname                            within 7m  YYY
XXXXXXXX  2019-02-07 11:00:34  hostname                            within 7m  YYY
XXXXXXXX  2019-02-08 11:00:38  hostname                            within 7m  YYY
XXXXXXXX  2019-02-09 16:32:53  hostname                            within 7m  YYY
XXXXXXXX  2019-02-10 11:00:36  hostname                            within 7m  YYY
XXXXXXXX  2019-02-11 11:00:46  hostname                            within 7m  YYY
XXXXXXXX  2019-02-12 11:00:36  hostname                            within 7m  YYY
XXXXXXXX  2019-02-13 11:00:59  hostname                            within 7m  YYY
XXXXXXXX  2019-02-14 11:00:45  hostname                            within 7m  YYY
XXXXXXXX  2019-02-15 11:00:43  hostname                            within 7m  YYY
XXXXXXXX  2019-02-16 11:00:43  hostname                            within 7m  YYY
XXXXXXXX  2019-02-18 11:00:48  hostname                            within 7m  YYY
XXXXXXXX  2019-02-19 11:00:33  hostname                            within 7m  YYY
XXXXXXXX  2019-02-20 11:00:40  hostname                            within 7m  YYY
XXXXXXXX  2019-02-21 11:00:36  hostname                            within 7m  YYY
XXXXXXXX  2019-02-22 11:00:50  hostname                            within 7m  YYY
XXXXXXXX  2019-02-23 11:00:36  hostname                            within 7m  YYY
XXXXXXXX  2019-02-26 11:00:36  hostname                            within 7m  YYY
XXXXXXXX  2019-02-28 11:00:47  hostname                            within 7m  YYY
XXXXXXXX  2019-03-01 11:00:48  hostname                            within 7m  YYY
XXXXXXXX  2019-03-03 11:00:49  hostname                            within 7m  YYY
XXXXXXXX  2019-03-04 11:00:42  hostname                            within 7m  YYY
XXXXXXXX  2019-03-05 11:00:49  hostname                            within 7m  YYY
XXXXXXXX  2019-03-05 12:31:48  hostname    keep,Before HD upgrade  within 7m  YYY
-----------------------------------------------------------------------------------------------
38 snapshots

keep 2 snapshots:
ID        Time                 Host        Tags        Reasons    Paths
----------------------------------------------------------------------------------------
XXXXXXXX  2019-01-20 02:42:02  hostname                within 7m  YYY
XXXXXXXX  2019-01-20 11:49:58  hostname                within 7m  YYY
----------------------------------------------------------------------------------------
2 snapshots

keep 1 snapshots:
ID        Time                 Host        Tags        Reasons    Paths
-----------------------------------------------------------------------------------------------------------------------
XXXXXXXX  2019-01-30 07:36:22  hostname    keep        within 7m  YYY
-----------------------------------------------------------------------------------------------------------------------
1 snapshots

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

**Comment by cfbao** [comment] 2019-09-10 16:39
I think you're seeing the expected behaviour, not a bug.

By default, `forget` groups snapshots based on their hostnames and paths before applying the policy to each group seperately.

For example, if you have
* some snapshots with path `/location1` from 2019-01-01 to 2019-03-31, and
* some snapshots with path `/location2` from 2019-04-01 to 2019-06-30.

If now you use `--keep-within 3m` with the default grouping, no snapshots will be forgotten, because they're all within 3 months from the latest snapshots _in their respective groups_.

To override the default grouping behaviour, use the `--group-by` flag. You can also use tags to help you achieve more customized grouping behaviour.

**Comment by MichaelEischer** [comment] 2020-03-21 20:48
@ramos I assume this issue is resolved. Could you close it?

**Closed** 2021-05-15 11:11 UTC
