### ISSUE TITLE
restic hangs if rclone is configured with less connections than restic

### ISSUE THREAD

**Issue by aeltawela** [restic/restic#2925] opened 2020-09-14 22:58 UTC
Output of `restic version`
--------------------------
restic 0.9.6

How did you run restic exactly?
-------------------------------
restic -r rclone:xxx:xxx --verbose backup /xxx

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone ftp

Expected behavior
-----------------
restic should backup the files normally

Actual behavior
---------------
retic hangs after counting the files, even the debug info is not printed after it hangs

Steps to reproduce the behavior
-------------------------------
1. Configure rclone to use 2 connection (in fact any number <5)
2. Use restic to backup files using the same rclone configurations
3. Restic hangs after counting the files

Do you have any idea what may have caused this?
-----------------------------------------------
I noticed that the default no. of connections in restic for clone is 5 and if rclone is configured with less than 5, it hangs.

Do you have an idea how to solve the issue?
-------------------------------------------
I changed the default value in restic and recompiled it, it works fine
file internal/backend/rclone/config.go

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, of course.

**Comment by MichaelEischer** [comment] 2020-09-15 21:12
How exactly did you limit rclone to two connections? I've just tried the options ` --transfers 1 --checkers 1` and with these the backup seems to be a bit slow but still working for me.

What do you mean with "counting the files" exactly? The `scan finished in 75.821s: 123456 files, 123.456 GiB` line? Please try `--verbose=3` as parameter for the backup command.

**Comment by aeltawela** [comment] 2020-09-26 08:51
@MichaelEischer, I limited the connection by editing "internal/backend/rclone/config.go" that is the only way it works.

Verbose was not really useful, it didn't show anything exceptional -- it is just hang.

**Comment by MichaelEischer** [comment] 2020-09-27 21:02
So in other words you've replaced the "5" in the following line with `2`?
https://github.com/restic/restic/blob/14b312f00dd176ef2fa03014a7cd441f73b72d2c/internal/backend/rclone/config.go#L21

`restic -r rclone:test-repo -o rclone.connections=2 backup path` should also limit the number of connections to two. I've also verified that this actually sets the number of connections in the config. Please try restic 0.10.0 which now notices when rclone exited unexpectedly. If that doesn't help, please kill the hanging restic run by sending it a SIGABRT and post the resulting stacktrace.

**Comment by iridescent86** [comment] 2020-10-11 13:03
Hello, I'm joining the discussion as i ran into the same issue.
I was trying to use FTP with a hosting provider that limits the maximum number of connections. After adding the `concurrency = 2` option to the rclone remote configuration i started to experience the lockup at each attempt. I was then able to reproduce with a local FTP server.

I'm using the following versions:
```
CentOS Linux release 7.8.2003 (Core) on x86_64
kernel 3.10.0-1127.19.1.el7.x86_64
restic 0.10.0 compiled with go1.15.2 on linux/amd64
rclone v1.53.1 - os/arch: linux/amd64 - go version: go1.15
```

With rclone configured as follows:
```
$ cat ~/.config/rclone/rclone.conf
[local-ftp]
type = ftp
host = 127.0.0.1
user = upload
pass = ...
concurrency = 2
```

I'm observing the lockup when running a backup with the following command:
```
$ RESTIC_PASSWORD=password restic -r rclone:local-ftp:/home/upload/backup --verbose=3 backup /mnt/snapshot
open repository
repository 74d68caf opened successfully, password is correct
created new cache in /root/.cache/restic
lock repository
rclone: 2020/10/11 14:49:11 ERROR : locks: error listing: directory not found
load index files
rclone: 2020/10/11 14:49:12 ERROR : index: error listing: directory not found
rclone: 2020/10/11 14:49:12 ERROR : snapshots: error listing: directory not found
start scan on [/mnt/snapshot]
start backup on [/mnt/snapshot]
scan finished in 0.217s: 1 files, 2.000 GiB
[0:10] 0.77%  0 files 15.740 MiB, total 1 files 2.000 GiB, 0 errors ETA 21:31
/mnt/snapshot/test.dat
```

At which point the restic process has entered what seems to be a deadlock and does not even respond to Ctrl-C.

The issue does not appear when using TCP sockets instead of stdin/stdout:
```
$ rclone serve restic --addr 127.0.0.1:8080 --b2-hard-delete --drive-use-trash=false local-ftp:/home/upload/backup &
$ RESTIC_PASSWORD=password restic -r rest:http://127.0.0.1:8080 backup /mnt/snapshot
repository 74d68caf opened successfully, password is correct
2020/10/11 14:54:23 ERROR : index: error listing: directory not found
2020/10/11 14:54:23 ERROR : snapshots: error listing: directory not found

Files:           1 new,     0 changed,     0 unmodified
Dirs:            2 new,     0 changed,     0 unmodified
Added to the repo: 2.000 GiB

processed 1 files, 2.000 GiB in 0:07
snapshot 06a1eea6 saved
$ pkill rclone
```

And, as suggested in the past messages, limiting the number of rclone connections to the same number:
```
$ RESTIC_PASSWORD=password restic -r rclone:local-ftp:/home/upload/backup -o rclone.connections=2 backup /mnt/snapshot
repository f18642f2 opened successfully, password is correct
rclone: 2020/10/11 14:58:39 ERROR : index: error listing: directory not found
rclone: 2020/10/11 14:58:39 ERROR : snapshots: error listing: directory not found

Files:           1 new,     0 changed,     0 unmodified
Dirs:            2 new,     0 changed,     0 unmodified
Added to the repo: 2.000 GiB

processed 1 files, 2.000 GiB in 0:08
snapshot 800389f9 saved
```

As a side note i also tested on a VM, and was only able to reproduce when the VM as 3 or more VCPU. It never happened on a single VCPU VM. So it looks like a concurrency / starvation issue.

**Comment by MichaelEischer** [comment] 2020-10-11 16:00
@iridescent86 Could you send a SIGABRT signal (e.g. `pgrep restic` to find the PID of restic, then `kill -6 <restic-pid>`) to restic when it gets stuck?

**Comment by iridescent86** [comment] 2020-10-11 22:39
So when restic is stuck it no longer reacts to SIGINT, but SIGTERM and SIGABRt do work.
I've attached the dumps obtained when sending SIGABRT to restic and to rclone (in two separate tries).
Also forgot to mention, when restic get  stuck, the run duration and ETA are still updated so most likely not all threads are blocked.
[restic_abrt.log](https://github.com/restic/restic/files/5362283/restic_abrt.log)
[rclone_abrt.log](https://github.com/restic/restic/files/5362284/rclone_abrt.log)

**Comment by MichaelEischer** [comment] 2020-10-15 20:11
@iridescent86 Which rclone version are you using? The stack trace looks like the hang occured in rclone inf the ftp backend, which would also explain why I couldn't reproduce the problem. This could be related to rclone/rclone#3984 which requires rclone 1.52 or newer.

**Comment by iridescent86** [comment] 2020-10-15 21:42
For rclone i picked the latest stable one, v1.53.1. As you mentioned issue 3984 is supposed to be fixed after 1.52 and newer. Also the issue happens during backups, i did not try with restore.
I was able to reproduce on different FTP servers. I first tried with the server of my hosting providers. Then i tried to narrow down the problem and tried with a FTP server running on localhost. Same results.

**Comment by MichaelEischer** [comment] 2020-10-17 21:24
@iridescent86 I can reproduce the issue when using rclone with the ftp backend. It looks like there's some problem with tracking the concurrency limit. It might be related to creating new folders (at least it looks like there's always a stacktrace with "mkdir", but that could also be a red herring). Could you open an issue for rclone?

Here's one of the stack traces I've collected
```
rclone: goroutine 49211 [chan receive]:
rclone: github.com/rclone/rclone/lib/pacer.(*TokenDispenser).Get(...)
rclone: 	github.com/rclone/rclone/lib/pacer/tokens.go:24
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).getFtpConnection(0xc0004902d0, 0xc, 0xc000adb7ba, 0x2)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:245 +0x1e5
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).getInfo(0xc0004902d0, 0xc000adb7b0, 0xc, 0xc, 0xa, 0xc000040870)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:606 +0xa7
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).mkdir(0xc0004902d0, 0xc000adb7b0, 0xc, 0xc000adb7b0, 0xc)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:638 +0xb0
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).mkParentDir(0xc0004902d0, 0xc000040870, 0x48, 0xc000b23740, 0xc000068c70)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:674 +0xb3
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).Put(0xc0004902d0, 0x59a79a0, 0xc000c14dc0, 0x596e620, 0xc000988d20, 0x59b7f00, 0xc000ba6640, 0x0, 0x0, 0x0, ...)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:583 +0x4c
rclone: github.com/rclone/rclone/fs/operations.RcatSize(0x59a79a0, 0xc000c14dc0, 0x59be060, 0xc0004902d0, 0xc000040870, 0x48, 0x5984c20, 0xc00047e0f0, 0x4eb96c, 0xbfdaf5925bbc5780, ...)
rclone: 	github.com/rclone/rclone/fs/operations/operations.go:1428 +0x339
rclone: github.com/rclone/rclone/cmd/serve/restic.(*Server).postObject(0xc0001b83e0, 0x599b7e0, 0xc00055c210, 0xc000bcd200, 0xc000040870, 0x48)
rclone: 	github.com/rclone/rclone/cmd/serve/restic/restic.go:275 +0x170
rclone: github.com/rclone/rclone/cmd/serve/restic.(*Server).ServeHTTP(0xc0001b83e0, 0x599b7e0, 0xc00055c210, 0xc000bcd200)
rclone: 	github.com/rclone/rclone/cmd/serve/restic/restic.go:242 +0x759
rclone: golang.org/x/net/http2.(*serverConn).runHandler(0xc000259500, 0xc00055c210, 0xc000bcd200, 0xc000895ea0)
rclone: 	golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/server.go:2147 +0x8b
rclone: created by golang.org/x/net/http2.(*serverConn).processHeaders
rclone: 	golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/server.go:1881 +0x505
```

**Comment by iridescent86** [comment] 2020-10-18 15:08
@MichaelEischer thanks for your analysis, i've summarized the findings in https://github.com/rclone/rclone/issues/4694, could you please have a look in case something is not correct?

**Comment by MichaelEischer** [comment] 2022-10-30 20:59
Is this issue still relevant?

**Comment by iridescent86** [comment] 2022-11-01 23:08
For what concerns me, i haven't run into this after making the changes described above, and it does not look like anyone else complained.

**Comment by MichaelEischer** [comment] 2022-11-04 21:16
Then lets close the issue for now. Feel free to reopen it if the problem still exists.

**Closed by MichaelEischer** 2022-11-04 21:16 UTC
Labels: type: bug, state: need feedback, backend: rclone
