### ISSUE TITLE
chmod: interrupted system call error on cifs filesystem

### ISSUE THREAD

**Issue by stucki** [restic/restic#3060] opened 2020-11-05 11:20 UTC
Output of `restic version`
--------------------------
```
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```
(The same problem already happened with 0.10.0. With 0.9.6, the problem does not happen.)

How did you run restic exactly?
-------------------------------
```
sudo restic -r /mnt/DiskStation/home/Backup/restic/thinkpad/ backup .
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
cifs

Expected behavior
-----------------
There should be no errors.

Actual behavior
---------------
I'm getting lots of errors like this:
```
repository d6e1b983 opened successfully, password is correct
found 9 old cache directories in /home/mstucki/.cache/restic, run `restic cache --cleanup` to remove them
Save(<data/8d102e2a0a>) returned error, retrying after 552.330144ms: Chmod: chmod /mnt/DiskStation/home/Backup/restic/thinkpad/data/8d/8d102e2a0a1193b0ab0eef6ed45231c03b4b3c57cc834b86f88d7ef15ee0b458: interrupted system call/.config/Slack/Service Worker/CacheStorage/4c237d5e33167c88df3e45d9c8b59fdd4d727472/b8a8c36e-9161-4f65-a8e8-106fe31b117a/7294396a45530ea3_0
Save(<data/3eb60ccaa0>) returned error, retrying after 720.254544ms: Chmod: chmod /mnt/DiskStation/home/Backup/restic/thinkpad/data/3e/3eb60ccaa0d867b37834a9f56772da522deba870d6eafb5b038af5ec5dd9c5f4: interrupted system call/.config/Slack/Service Worker/CacheStorage/4c237d5e33167c88df3e45d9c8b59fdd4d727472/b8a8c36e-9161-4f65-a8e8-106fe31b117a/7294396a45530ea3_0
Save(<data/d53e9e3de0>) returned error, retrying after 582.280027ms: Chmod: chmod /mnt/DiskStation/home/Backup/restic/thinkpad/data/d5/d53e9e3de0b578500eb5f0c293da531caeb8901d8a13822a7752094b1cf2ec57: interrupted system call/.config/chromium/Default/Favicons
Save(<data/bcf9a753f8>) returned error, retrying after 468.857094ms: Chmod: chmod Save(<data/3908f499f8>) returned error, retrying after 462.318748ms: Chmod: chmod /mnt/DiskStation/home/Backup/restic/thinkpad/data/39/3908f499f86824f7f08a10c2454566d02d574532a5c9ab7dcf6d95730a96b8ad: interrupted system call/.config/libreoffice/4/user/registrymodifications.xcu
Save(<data/c569b555b5>) returned error, retrying after 593.411537ms: Chmod: chmod /mnt/DiskStation/home/Backup/restic/thinkpad/data/c5/c569b555b5f4787457ec2c963224eaf9d5aefbd7e075f76ee0d25b944ed5787d: interrupted system call/.mozilla/firefox/vxrcnvik.mobile/places.sqlite
```

Steps to reproduce the behavior
-------------------------------
When I repeat the backup process, the errors are gone. I guess it will come back when more data changes and I repeat the backup...

Do you have any idea what may have caused this?
-----------------------------------------------
Using an older restic version (`restic_0.9.6_linux_amd64`), the problem does not occur. However, it also happened with 0.10.0 but I didn't report the bug back then...

Do you have an idea how to solve the issue?
-------------------------------------------
The workaround is to stick with 0.9.6.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm really happy with Restic so far. Hoping that the issue can get resolved easily. Thanks for all your work! :+1:

**Comment by greatroar** [comment] 2020-11-05 11:56
Looks like a duplicate of #2659, except now it's Chmod that fails. That can be worked around in our Chmod wrapper.

**Comment by stucki** [comment] 2020-11-05 16:17
@greatroar Thanks for the feedback! I can confirm that the workaround with `export GODEBUG=asyncpreemptoff=1` has fixed the problem for me!

**Comment by fd0** [comment] 2020-11-05 17:14
awesome, thanks for the report @stucki and the diagnosis @greatroar. I'll close this issue for now, please feel free to add further comments.

**Closed by fd0** 2020-11-05 17:14 UTC
