### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by mjf** [restic/restic#3493] opened 2021-08-24 12:22 UTC
Output of `restic version`
--------------------------

```
restic 0.12.0 compiled with go1.14.12 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Not every option that may make sense to have it's environment variable equivalent for already has it's environment variable.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I need to pass CA certificate file path from the environment right now.

```sh
# ...
declare -x RESTIC_CACERT_FILE='/path/to/pem'
# ...
restic backup /etc
```

The similar feature request could be addressed for almost every option missing the possibility to be pre-defined (defaulted) in the environment.

**Comment by MichaelEischer** [comment] 2021-10-09 22:20
Duplicate of #1233, related to #1926.

**Closed by MichaelEischer** 2021-10-09 22:20 UTC
