### ISSUE TITLE
Error while pruning: Number of used blobs is larger than available blobs

### ISSUE THREAD

**Issue by git-commit** [restic/restic#1707] opened 2018-04-05 21:01 UTC
So when I ran restic prune for the first time today, it told me to post this. So here I am.
If you want me to run some diagnostic commands against the restic repo, I'm more than happy to help out.

Maybe a dupe of:  #1633

## Output of `restic version`
```
restic 0.8.3
compiled with go1.10 on darwin/amd64
```

## How did you run restic exactly?
`restic prune` against a rest repo inside my LAN

Output:
```
Thu Apr  5 22:23:10 CEST 2018
password is correct
counting files in repo
building new index for repo
[4:03] 100.00%  19920 / 19920 packs
repository contains 19920 packs (558337 blobs) with 93.198 GiB
processed 558337 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 8 snapshots
[0:40] 100.00%  8 / 8 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

## What backend/server/service did you use to store the repository?
`rest-server`

## Expected behavior
Successful prune without any errors.

## Actual behavior
Apparently restic lost some blobs along the way.
Here's a short description of most of the operation run against this repo:
- hourly backups (via wan and lan)
- A call `restic forget -y 20 -m 24 -w 12 -d 31 --prune` Output: https://gist.github.com/git-commit/62e416acaf7f9ecada2d3e93f65300a7
- A call `restic check` Output: https://gist.github.com/git-commit/58bcd0b693ee2bf3f6ff1520bf799881

## Steps to reproduce the behavior
Did not try yet.

## Do you have any idea what may have caused this?
My workplace internet connection is kinda wonky when many people use it. While running the `restic forget` command I put the pc to sleep and continued with it at home. Maybe in some cases the restic continues without a correct acknowledgement from the rest-server?

## Do you have an idea how to solve the issue?
Nope

## Did restic help you or made you happy in any way?
Once setup, the combination of restic with the rest-server works like a charm. Especially because both can be used with a single binary download only.

**Comment by fd0** [comment] 2018-04-05 21:08
Hey, thanks for the report. It's not a dupe of #1633, the person over there got errors. Did you see any errors before?

What restic is complaining about is that there are references to some data (blobs == small parts of files) in the repo which it cannot find. Is the file system of the storage location corrupt? Did anybody delete a file? Were there any errors before?

I'm not sure yet what's going on here.

The repo itself is fine, except there's a single directory which contains files that cannot be restored any more, because the data cannot be found any more...

**Comment by fd0** [comment] 2018-04-05 21:10
Oh, sorry, now I see the errors in the previous run of `restic forget --prune`. The errors are still different, because it looks like restic was temporarily unable to resolve a host, but succeeded eventually. Hm.

**Comment by git-commit** [comment] 2018-04-05 21:17
Sorry I didn't mention those errors more obviously.

I am running a FS check now, but I've no reason to suspect the FS to be corrupt. Also I'm the only one able to access the backup location, so anyone deleting a file is also very unlikely.

As for previous errors:
* I had a dangling lock on the repo once and was not sure where it came from. After an unlock everything was fine however.
* The folder to backup is changing mid-backup from time to time. It contains several directories which seem to be used for cache, that I haven't excluded manually yet. The option `--exclude-caches` doesn't seem to catch them.

**Comment by fd0** [comment] 2018-04-06 10:30
Hm. Doesn't sound like you did anything wrong... It feels to me that an upload of a file to the repo failed and restic did not recognize it. Or the file was removed from the repo at some point.

The repo is in a good state apart from that single directory. If restic ever comes across the source data, it'll re-upload it and the repo will heal itself. Apart from that, the snapshot will eventually be removed with `forget`, and then the errors reported by `check` vanish.

I don't have any ideas on how to find out what happened further. Can you maybe check your logs for any obviously different errors which occurred during `backup` or `prune`?

**Comment by git-commit** [comment] 2018-04-19 10:57
After a recent prune run, the `restic check` now runs without errors. I'll let you know if this issue comes up again.
BTW: Is there a place to talk about restic without opening an issue?

**Comment by dimejo** [comment] 2018-04-19 11:43
> BTW: Is there a place to talk about restic without opening an issue?

https://forum.restic.net/

**Comment by fd0** [comment] 2018-05-05 10:36
I'm closing this issue for now, I'm not aware of anything we can do here for restic. Please feel free to add further comments. Thanks!

**Closed by fd0** 2018-05-05 10:36 UTC
