### ISSUE TITLE
Output of restic forget --json is not a valid json

### ISSUE THREAD

**Issue by ismaildem** [restic/restic#4162] opened 2023-01-18 15:27 UTC
Output of `restic version`
--------------------------

`restic 0.15.0 compiled with go1.19.5 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic forget --keep-last 1 --prune --json -q`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Expected behavior
-----------------
always a valid json output when using --json flag

Actual behavior
---------------
In addition to the json response, restic also writes a line at the end that looks like this
`[0:00] 100.00%  7 / 7 packs processed`

this makes the whole output incompatible with json
restic writes the output only when a snapshot is deleted. 

Steps to reproduce the behavior
-------------------------------
run restic backup multiple times and run the command above to delete at least one snapshot 

Do you have any idea what may have caused this?
-----------------------------------------------
Version 0.14.0 was still fine

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
sure, always :blush:

**Comment by MichaelEischer** [comment] 2023-01-20 23:45
Duplicate of #4147 and to an extent #3129.

**Closed by MichaelEischer** 2023-01-20 23:45 UTC
