### ISSUE TITLE
Debug Info on output, when enter an empty "new" password

### ISSUE THREAD

**Issue by busybee63** [restic/restic#3388] opened 2021-05-10 18:07 UTC
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/386

How did you run restic exactly?
-------------------------------
PS T:\> restic -r xxx init
enter password for new repository:         _(entering here just return)_
an empty password is not a password
main.ReadPassword
        /restic/cmd/restic/global.go:367
main.ReadPasswordTwice
        /restic/cmd/restic/global.go:376
main.runInit
        /restic/cmd/restic/cmd_init.go:61
main.glob..func12
        /restic/cmd/restic/cmd_init.go:25
github.com/spf13/cobra.(*Command).execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /restic/cmd/restic/main.go:98
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_386.s:1333
PS T:\>

_The same behaviour with command:_

PS T:\> restic -r restic-st key add
enter password for repository:
repository 3a1ebf59 opened successfully, password is correct
enter new password:
an empty password is not a password
main.ReadPassword
        /restic/cmd/restic/global.go:367
main.ReadPasswordTwice
        /restic/cmd/restic/global.go:376
main.getNewPassword

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------
no text after "an empty password is not a password"
I guess, that is some debug information, not designed for final release

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------
Just press "Return" when you asked for new password

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It' always a pleasure to work with restic!

**Comment by rawtaz** [comment] 2021-05-10 18:14
@busybee63 Can you reproduce this when running restic in the regular command prompt in Windows? I don't have a Windows machine nearby to test with right now. But it doesn't happen on a Mac restic binary, so it seems to be Windows specific so far.

**Comment by rawtaz** [comment] 2021-05-11 15:27
Yeah that's what I meant, CMD. Okay, thanks. If someone else can reproduce this, it would be good to know. I guess it needs investigating nonetheless :)

**Comment by busybee63** [comment] 2021-05-12 15:34
I checked with the 64-version, same behaviour
- restic 0.12.0 compiled with go1.15.8 on windows/amd64

But self-compiled versions from yesterdays master (standard and debug) do not show that.
- restic 0.12.0.Stephan compiled with go1.16.4 on windows/amd64

**Comment by MichaelEischer** [comment] 2021-05-14 20:35
This has been fixed in #3283

**Closed by MichaelEischer** 2021-05-14 20:35 UTC
Labels: platform: windows, state: need investigating
