### ISSUE TITLE
restore status

### ISSUE THREAD

**Issue by nunotexbsd** [restic/restic#3838] opened 2022-07-26 11:34 UTC
Hello,

Could restore have ongoing status?
Example:

```
Processed 269 (34.6 GB) of 408 (36.4 GB) 96.1 MB/s (95.2%) remaining 18s.
Processed 270 (34.6 GB) of 408 (36.4 GB) 95.4 MB/s (95.2%) remaining 17s.
Processed 271 (35.5 GB) of 408 (36.4 GB) 95.8 MB/s (97.7%) remaining 8s.
(...)
```

**Comment by MichaelEischer** [comment] 2022-07-30 14:33
Please fill out the issue template otherwise we can't help you. Judging from the output you're using a very old restic version.

But anyways, this issue is a duplicate of #426. Please add an upvote to the issue if you're interested in that feature request.

**Closed by MichaelEischer** 2022-07-30 14:33 UTC
