### ISSUE TITLE
Generate autocomplete script to /dev/stdout

### ISSUE THREAD

**Issue by GeertJohan** [restic/restic#2511] opened 2019-12-11 10:04 UTC
I'm using restic 0.9.6 compiled with go1.13.4 on linux/amd64

I'm trying to add autocomplete to my `.zshrc` by adding this line:
```zsh
source <(restic generate --zsh-completion /dev/stdout)
```

Having generated completion in zshrc is very common in the k8s ecosystem;
```zsh
source <(kubectl completion zsh)
source <(minikube completion zsh)
source <(helm completion zsh)
```

This is quite cool because the user doesn't have to think about overwriting a previously generated completion script when they upgrade the tool.

However, it doens't work with restic, because restic writes a message to /dev/stdout when running the generate command.
> writing zsh completion file to /dev/stdout

This message breaks interpreting the outputted script. When I start a new terminal with zsh in it:
> /proc/self/fd/13:1: command not found: writing
> _arguments:comparguments:325: can only be called from completion function
> _arguments:comparguments:325: can only be called from completion function

The first line, "command not found: writing" seems to relate to the "writing zsh completion file to /dev/stdout" message.

I would like to have a way to achieve the same as kubectl and other tools, generating the latest autocomplete code when starting a new terminal with zsh so that the autocomplete is always up-to-date.

Maybe the message can be written to /dev/stderr so that it can be filtered in `.zshrc`, or the message is silenced when using `/dev/stdout` as output file?

I didn't report this as a bug because generating the autocomplete code to `/dev/stdout` probably isn't what the author of the autocomplete functionality had in mind. 

If the maintainer of this software agrees with a proposed solution, I'd be very happy to work on a PR.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It's huge. Having an easy tool to maintain secure offsite backups is great. Since restic, I backup more often. Thanks!

**Comment by GeertJohan** [comment] 2019-12-11 10:11
I'm now wondering if this autocomplete script is meant to be `source`d at all?

```zsh
restic generate --zsh-completion .zsh-restic-autocomplete
```

In .zshrc:
```zsh
source .zsh-restic-autocomplete
```

When opening a new terminal with zsh:
```
_arguments:comparguments:325: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
```

And `restic <tab>` doesn't autocomplete.

**Comment by rawtaz** [comment] 2019-12-11 15:45
How does other software do it? Do they never write anything but the completion script/data to the output, or do they silence themselves when the target is stdout? I think it's a matter of following best practices here.

@GeertJohan If you could investigate the

~~~
_arguments:comparguments:325: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
~~~

messages, that'd be great!

**Comment by shtratos** [comment] 2019-12-13 18:46
This is issue has been discussed at length here: https://github.com/spf13/cobra/issues/881

There's also a PR that tries to fix this with `WONTFIX: works as intended` by maintainers:
https://github.com/spf13/cobra/pull/887#issuecomment-536621700

Apparently, sourcing the code directly is not the right way to install completions in zsh.

A workaround is also mentioned for apps using cobra that would like to support bash-like behaviour:
https://github.com/corneliusweig/rakkess/blob/eb1ac91e5cddba8f3fbb14d88fff6e863738d8a8/cmd/completion.go#L78

I guess Restic can either add a workaround or change autocompletion documentation for zsh users.

**Comment by metalsp0rk** [comment] 2020-11-26 06:55
This issue is quite old, but: 

```
$ restic generate --zsh-completion /dev/stdout | head
writing zsh completion file to /dev/stdout
#compdef _restic restic


function _restic {
  local -a commands

  _arguments -C \
    '*--cacert[`file` to load root certificates from (default: use system certificates)]:' \
    '--cache-dir[set the cache `directory`. (default: use system default cache directory)]:' \
```

```
$ restic generate --zsh-completion /dev/stdout --quiet | head
#compdef _restic restic


function _restic {
  local -a commands

  _arguments -C \
    '*--cacert[`file` to load root certificates from (default: use system certificates)]:' \
    '--cache-dir[set the cache `directory`. (default: use system default cache directory)]:' \
    '--cleanup-cache[auto remove old cache directories]' \
```

Using the `--quiet` flag suppresses the message that is causing the error.

**Comment by abraithwaite** [comment] 2021-05-15 13:15
Ran into this today, @metalsp0rk thank you for pointing out that CLI option! :-)

**Comment by MichaelEischer** [comment] 2022-05-15 09:51
A clean solution would be to support `-` as filename when the completion should be printed on stdout. In that case restic should automatically disable the verbose status output.  For an implementation this probably means that we should for example use `GenBashCompletion` instead of `GenBashCompletionFile` and provide the output file ourselves. Anyone interested in a PR?

**Comment by MichaelEischer** [comment] 2024-07-03 20:50
When the destination is not a terminal, then by now the `writing [...] completion file to [...]` is no longer shown by now.

**Closed** 2024-10-09 20:19 UTC
Labels: type: feature enhancement, help: wanted, help: minor complexity, category: generate
