### ISSUE TITLE
S3 Glacier

### ISSUE THREAD

**Issue by edpichler** [restic/restic#2817] opened 2020-07-01 18:28 UTC
Guys, I really need to use Glacier to do backups.

I am doing it, but I get this message sometimes.

![image](https://user-images.githubusercontent.com/358696/86278395-97a93400-bbd8-11ea-911f-97fc1c1a7f65.png)

I would like restic has a feature that wherever this happens, he ask me if if I want to request the file to be restored from Glacier to S3 so I can try run again later.
Then in some hours I can try the backup again.
Restic don't need to wait the file to be restored. Once it's restored, it will follow the s3 lifecycle and stay available for some days.

This feature would make restic unbeatable. By far the cheapest way to do backup.

Something like `restic backup --always-restore-from-glacier=yes`

I don't know how to program in go. I if knew I could try to change the code.
Also, instead of listing just the prefix of the s3 file that is on glacier, he could list the entire file, so I can parse the errors and try to fix it if other script to try again restic later. I have many files...

**Comment by davidjericho** [comment] 2020-07-28 02:41
I'm looking at a similar problem, working out how to map a snapshot and potentially a file within a snapshot to which packs in data/ I need to retrieve. https://github.com/restic/restic/issues/2796 looks related, as it's adding a cold storage support in the form of a --dry-run option on restore.

**Comment by moggers87** [comment] 2020-07-31 12:16
I think this is a duplicate iof #541

**Comment by aawsome** [comment] 2020-08-07 05:05
see also #2504

**Comment by MichaelEischer** [comment] 2022-10-30 21:22
Duplicate of #3202

**Closed by MichaelEischer** 2022-10-30 21:22 UTC
