### ISSUE TITLE
error after disk full: index is not complete

### ISSUE THREAD

**Issue by cstrotm** [restic/restic#3400] opened 2021-05-17 16:52 UTC
restic 0.12.0 compiled with go1.16rc1 on linux/amd64

After a disk full situation, I've moved all restic repo data to a new, larger disk. A `restic prune` now gives me:

```
[...]
2 snapshots have been removed, running prune
loading indexes...
loading all snapshots...
finding data that is still in use for 34 snapshots
[4:55] 100.00%  34 / 34 snapshots
searching used packs...
{<data/00619cce> <data/00e787f2> <data/0428247a> <data/053d12a9> <data/06df710b> <data/06ea5c1c> <data/07d8c650> <data/08f40976> <data/0f4657ff> <data/0ff4dcbc> <data/19714f2e> <data/1c3c9c6f> <data/23ba2740> <data/28797cbf> <data/2bcd6111> <data/2dd70643> <data/30885ca2> <data/30b41826> <data/30fd8e78> <data/3111e060> <data/32d3494b> <data/3360da02> <data/337baff7> <data/380c681d> <data/384acc81> <data/3d0ec991> <data/3ed94393> <data/3fe5e29d> <data/3ff36cb1> <data/40f488f6> <data/44047d4f> <data/459b40de> <data/470ec79b> <data/49eb26b8> <data/4bf115e5> <data/4ccd8004> <data/4de95371> <data/53c1cb0e> <data/5774dcda> <data/59074944> <data/5b385a5d> <data/5b9e6afa> <data/5f0eb332> <data/62542538> <data/633958a2> <data/65b8a177> <data/66524710> <data/666a92fb> <data/668fe578> <data/691b4549> <data/6a186c75> <data/6b11aa49> <data/6b271514> <data/6b43dee2> <data/6b7159ec> <data/6bdd4e1f> <data/6c01f1c1> <data/6c1edea4> <data/6e86aa3b> <data/6f0fefc1> <data/70bd703c> <data/7114c9a4> <data/73dfe2ea> <data/759d9f83> <data/7ab8f290> <data/7b7c1f00> <data/7c072cb0> <data/7f7a4d3a> <data/814d209d> <data/81d1634c> <data/83255b72> <data/8760d9a1> <data/89891177> <data/899c21e1> <data/8bafc5e4> <data/8e54e4c8> <data/8f0a2c4d> <data/95001289> <data/955da312> <data/97187741> <data/98784ac7> <data/9a814bcd> <data/9ed3e630> <data/9ef49891> <data/a646b8e0> <data/a9a29d79> <data/ab825e02> <data/ab8d528d> <data/abf165bf> <data/ac05d0e0> <data/ac67260e> <data/afbc3b4e> <data/b40d2a1e> <data/b6fd373b> <data/b7bae8cd> <data/bd08c691> <data/be0ab901> <data/c337e8d7> <data/c7b93e2a> <data/cadf6256> <data/ce1f186b> <data/d19fa040> <data/d8c08bd4> <data/d9e24927> <data/de26c14d> <data/defb21f5> <data/e08faae9> <data/e104c671> <data/e35ab780> <data/e4a7ca25> <data/e7365664> <data/e86f258e> <data/e950bbca> <data/f0efa134> <data/f0fe2502> <data/f1597d70> <data/f1d1bfbf> <data/f2c441c4> <data/f433630e> <data/f4bc171b> <data/f6552c7c> <data/f8d49ab5> <data/f9ccd4c5> <data/fb93c905>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete[

```

I've rebuild the index (but without --read-all-packs) before doing the prune.

**Comment by MichaelEischer** [comment] 2021-06-05 11:09
Which backend do you use to store the files? What errors did restic report when the disk ran out of space? Is this the first failing `prune` run?

Please run the `check --read-data` command to verify the repository integrity. That will read and check the whole repository including all pack files. If this would cause huge traffic costs then just run `check`.
Which warnings did `rebuild-index` report?

It would be helpful to know which snapshots are missing blobs: Please run `restic find --blob 00619cce 00e787f2 0428247a 053d12a9 06df710b [...]` (with the ids of the blobs reported as missing) to find the affected snapshots.

**Comment by unclesamwk** [comment] 2021-06-16 11:07
same error to ...

root@backup006:~# restic -r /data/server.internal/folder prune
repository 0f9ecf83 opened successfully, password is correct
warning: running prune without a cache, this may be very slow!
loading indexes...
loading all snapshots...
finding data that is still in use for 15 snapshots
[0:16] 100.00%  15 / 15 snapshots
searching used packs...
{<data/bb98b328>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete

**Comment by MichaelEischer** [comment] 2021-06-20 12:34
@unclesamwk Did you also have a full disk during the backup? Or is just the error message the same. In the latter case please open a separate issue. Otherwise please provide the information I've requested above.

**Comment by unclesamwk** [comment] 2021-06-21 10:59
There was a time when the hard disk was full and backup runs. This caused the error in the repo. I can't get rid of it now.

**Comment by MichaelEischer** [comment] 2021-06-24 19:45
@unclesamwk Please provide the information I've requested in comment https://github.com/restic/restic/issues/3400#issuecomment-855224026.

**Comment by saberya** [comment] 2021-07-12 02:26
Maybe I had same problem ,but I dont think it cauesed by disk full;
I encounter this almost everyday and cant reslove it, or even understand what trigger it;
It really took me a lot of time, restic is a good tool, I hope that sb can give me a little help;
Well, I'll describe my problem and operations as follows:
------
restic 0.12.0 CentOS release 6.6
I backup my mysql-data via restic with mount remote repostory to local file system
-------

**Firstly, _restic -r /mnt/backup/repo1 backup  /root/mysql_bak/ --password ..._**
OK，it succeed.but i think there is something wrong with this snapshot.
**Secondly,_restic -r /mnt/backup/repo1  check  --password-file=..._**
it failed with following error log
```
using temporary cache in /tmp/restic-check-cache-956472566
repository 6890ac2a opened successfully, password is correct
created new cache in /tmp/restic-check-cache-956472566
create exclusive lock for repository
load indexes
check all packs
pack daac2bc1: unexpected file size: got 0, expected 4765734
check snapshots, trees and blobs
[0:00] 100.00%  6 / 6 snapshots
Fatal: repository contains errors
```
umhhh,,,,maybe it caused by Corrupted file，but I dont know what lead to this error;
this problem appeared many times with high frequency;
i think my  server is stable and disk is abundant；

**Thirdly,i tried to resolve this problem**
_restic -r /mnt/backup/repo1 prune 75f16341 --password-file=... --verbose_
75f16342 is the error snapshot
it failed with following error 
`repository 6890ac2a opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 6 snapshots
[0:00] 100.00%  6 / 6 snapshots
searching used packs...
{<data/423e668c> <data/4c5f1a17> <data/a24f19fc>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete


searching used packs...
collecting packs for deletion and repacking
pack daac2bc1: calculated size 4765732 does not match real size 0
`
**Forthly ,_restic rebuild-index_**
also failed, but i miss the log

**Fifthly, _restic backup_ again, it falied**

```
Save(<data/e893418011>) returned error, retrying after 552.330144ms: Sync: sync /mnt/backup/repo1/data/e8/e893418011982ce20fa4064d1: input/output errorak/test/file1_210712_040001.sql.gz_split021
Save(<data/952f81102b>) returned error, retrying after 720.254544ms: Sync: sync /mnt/backup/repo1/data/95/952f81102b181b2e503f22724d8424d2974c3c38794f9bab0ef972d20d5aee25: host
is downysql_bak/test/file2_210712_040001.sql.gz_split021
Save(<data/fb88f1e58b>) returned error, retrying after 582.280027ms: Sync: sync /mnt/backup/autodb2/repo1/data/fb/fb88f1e58bf4034a1076c5cdf391e17d4a8d6016acd9b2779b9bc7ce39253e4f: input/output error
```
I don't understand what's going on with those message

**Sixthly, _restic check_** 

```
repository 6890ac2c opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 6 snapshots
[0:00] 100.00%  6 / 6 snapshots
searching used packs...
{<data/423e668d> <data/4c5f1a17> <data/a24f19fc>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete
```
Oh, man, intersting I was completely dumbstruck，i had rebuild the repository, but id didnt work;
**who can help me, at least,tell me how to operate to resolve this problem，Thank you very much**
i have used resic for three months, i really ran into a lot of problems and solved them manually every time

**Comment by MichaelEischer** [comment] 2021-07-12 19:15
@saberya I've moved your comment to issue #3455 which you created with an empty description.

**Comment by MichaelEischer** [comment] 2021-08-17 19:45
Closing this issue as the requested information was not provided.

**Closed by MichaelEischer** 2021-08-17 19:45 UTC
Labels: state: need feedback, state: need investigating
