### ISSUE TITLE
wrong Windows drive handling

### ISSUE THREAD

**Issue by frederich** [restic/restic#333] opened 2015-11-02 09:39 UTC
Normally you can address a whole Windows drive via `c:\` or `c:`. Restic cannot handle `c:\` literals. All snapshots are empty.

```
%HOME%\restic.exe -r g:\backup backup e:\
                                     ^^^^^  

g:\>restic -r backup ls 0f81a5b0
enter password for repository:
snapshot of [e:\] at 2015-11-02 10:29:35.0378875 +0100 CET:
```

Creating a snapshot without the trailing blackslash works.
```
%HOME%\restic.exe -r g:\backup backup e:
```

**Comment by fd0** [comment] 2015-11-02 16:49
Hm, this is strange behaviour, I cannot reproduce this on Linux and don't have a windows machine available.

**Comment by frederich** [comment] 2015-11-02 16:55
I'm on it. 

You can easily spin up a small Windows testing instance (is scriptable) on [GCP](https://console.developers.google.com). Is very cheap.

**Comment by fd0** [comment] 2015-11-02 17:02
Does it work with a subdir of `e:\`? Or with quotes around the path?

https://github.com/restic/restic/issues/334 looks like it's possible to backup with a drive path, maybe it's an escape/quoting thing.

**Comment by frederich** [comment] 2015-11-04 09:42
I've run some tests. Normally each physical Windows drive as a `$RECYCLE.BIN` and `System 
Volume Information` folder. Both folder are not backup relevant. I think restic can automatically ignore them if the specified backup path is a Windows drive literal: c:\, d:\, e:\.

The drive literal `e:\` works, but only when `$RECYCLE.BIN` and `System Volume Information` are excluded. See log attachment.

The wrong call
```
e:\tmp>e:\home\jf\bin\restic -r restic_drive backup e:\
```
The right call
```
e:\home\jf\bin\restic -r restic_drive backup --exclude "$RECYCLE.BIN" --exclude "System Volume Information" e:\
```

**Comment by frederich** [comment] 2015-11-04 09:43
I cannot attach the log file. I've no write permissions on this repository.

**Comment by frederich** [comment] 2015-11-04 10:15
Another path issue. But I don't know whether is the correct behaviour. If anyone invoke restic with `backup e:` it doesn't backup the e drive. Instead it backups the current working directory. Invoking it with `backup e:\` backups the e drive.

```
e:\> cd /tmp
e:\tmp>

e:\tmp>e:\home\jf\bin\restic -r restic_drive backup e:
debug log file restic_drive.log
debug enabled
enter password for repository:
scan [e:\tmp]
←[2Kscanned 10264 directories, 72884 files in 0:01GiB
←[2KInterrupt received, cleaning up464 MiB / 27.529 GiB  63 / 83148 items  0 errors  ETA 18:15
```

**Comment by frederich** [comment] 2015-11-04 18:37
Should I send the log file?

**Comment by fd0** [comment] 2015-11-04 19:07
I don't think this will help, someone (or me) with a windows machine needs to debug this.

**Comment by fd0** [comment] 2016-08-16 07:20
We've recently added support for long paths in Windows, please try this again and leave a comment if it still occurs. Until that I'm closing the issue (we can reopen it later).

**Closed by fd0** 2016-08-16 07:20 UTC
Labels: backup, bug, help wanted, platform:Windows
