### ISSUE TITLE
Restore many small files very slow

### ISSUE THREAD

**Issue by yhafri** [restic/restic#687] opened 2016-12-09 21:07 UTC
## Output of `restic version`

```
$ restic version
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-11-30 04:53:47 with go1.7.3 on darwin/amd64

$ minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

## Expected behavior

Restore should be as fast or even faster than backup for  small files. Even if they are many.

## Actual behavior

While the backup operation if quite fast (see below), the restore is in the other hand very very slow.
Never lasts in my case.

## Steps to reproduce the behavior
```
$ cp -rf /usr/share /tmp

$ restic backup --force /tmp/share
scan [/tmp/share]
scanned 2561 directories, 28941 files in 0:00
[1:31] 100.00%  4.691 MiB/s  426.896 MiB / 426.896 MiB  31502 / 31502 items  0 errors  ETA 0:00
duration: 1:31, 4.65MiB/s
snapshot 8af9d029 saved

$ rm -rf /tmp/share
```

```
$ restic snapshots
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
8af9d029  2016-12-09 21:38:33  localhost              /tmp/share
```

```
$ restic restore --target /tmp/ 8af9d029
restoring <Snapshot 8af9d029 of [/tmp/share] at 2016-12-09 21:51:04.716484602 +0100 CET by xxxx@localhost> to /tmp/
error for /tmp/share/doc/ntp/access.html: open /tmp/share/doc/ntp/access.html: permission denied
OpenFile
restic.Node.createFileAt
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/node.go:199
restic.(*Node).CreateAt
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/restic/restorer.go:122
main.runRestore
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/cmds/restic/cmd_restore.go:135
main.glob..func13
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/github.com/spf13/cobra/command.go:648
main.main
	/var/folders/vp/fw3j6w856bz5nwbj287rscq80000gn/T/restic-build-985703156/src/cmds/restic/main.go:41
runtime.main
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:183
runtime.goexit
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086
error for /tmp/share/doc/ntp/accopt.html: open /tmp/share/doc/ntp/accopt.html: permission denied
OpenFile
[...]
```

The restore is still running after ~20mn.

And why these permission errors?

**Comment by fd0** [comment] 2016-12-10 10:45
Thanks for your report. This is caused by two things: The metadata for the directories is fetched on demand from the repo and not yet cached locally, so for high-latency backends this adds up to quite a lot of waiting time for restic. The other thing is that (in contrast to backup) restore is run sequentially.

**Comment by fd0** [comment] 2016-12-10 10:47
The permission errors come from the fact that the files you're restoring still exist, so `open()` with the `O_CREATE` flag fails (the file already exists). Try restoring to an empty directory.

**Comment by yhafri** [comment] 2016-12-10 15:43
Thanks for the update. Any plan to make the restore parrarel or at least efficiently cache the metadata somehow?

**Comment by fd0** [comment] 2016-12-10 15:58
Yes, but no timeline. You can track #386 if you like to be notified of any update.

**Comment by yhafri** [comment] 2016-12-10 17:48
Hmm. I really expected  *restic* to be faster to restore files than backup(ing) them.
What's the point if you have to wait 20h to restore 20MiB directory of small files :-( ?

I'm willing to donate if you can focus on this problem and consider it as _high priority_ ?

**Comment by fd0** [comment] 2016-12-10 19:28
Something doesn't add up here, that smells like a different problem. Could you please give me a bit more details on the data you're saving?

How many small files are in this 20MiB directory? How many directories? What's the latency (ping) and bandwidth to and from the backend?

Did you try local or sftp instead of s3 with minio? The s3 protocol is rather complex and may add additional round trips, which may amplify the problem if the backend is remote with a high latency...

I don't take donations at the moment, but thanks for the offer.

**Comment by yhafri** [comment] 2016-12-10 21:25
@fd0 the _20MiB/20h_ was a way of speaking. I was simply referring to the 2nd bullet of restic's [description](https://restic.github.io/).

> Fast: Backing up your data with restic should only be limited by your network or hard disk bandwidth so that you can backup your files every day. Nobody does backups if it takes too much time. Restoring backups should only transfer data that is needed for the files that are to be restored, so that this process is also fast.

Answers:
1. I've only tried with a remote Minio instance for now.
2. Test size: 2561 directories, 28941 files (see above in this ticket)
3. Ping test:
```
$ ping xx.xx.xx.xx
PING xx.xx.xx.xx (xx.xx.xx.xx): 56 data bytes
64 bytes from xx.xx.xx.xx: icmp_seq=0 ttl=61 time=31.729 ms
64 bytes from xx.xx.xx.xx: icmp_seq=1 ttl=61 time=26.575 ms
64 bytes from xx.xx.xx.xx: icmp_seq=2 ttl=61 time=25.142 ms
64 bytes from xx.xx.xx.xx: icmp_seq=3 ttl=61 time=26.173 ms
64 bytes from xx.xx.xx.xx: icmp_seq=4 ttl=61 time=26.400 ms
^C
--- xx.xx.xx.xx ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 25.142/27.204/31.729/2.317 ms
```
4. My UP bandwidth is large enough (fiber channel). Remote machine is limited at 100Mb/sec for download.
5. Even when trying locally, it's still slow. On my local laptop:

```
$ restic backup --force /usr/share
scan [/usr/share]
scanned 725 directories, 14857 files in 0:00
[0:05] 100.00%  77.658 MiB/s  398.869 MiB / 398.869 MiB  15582 / 15582 items  0 errors  ETA 0:00
duration: 0:05, 71.90MiB/s
snapshot 04ea0581 saved

$ time restic restore --target /tmp/share 04ea0581 2>/dev/null
restoring <Snapshot 04ea0581 of [/usr/share] at 2016-12-10 22:14:08.020394694 +0100 CET by local to /tmp/foo

real	0m25.793s
user	0m19.811s
sys	0m6.248s
```

**Comment by fd0** [comment] 2016-12-11 10:11
Thanks for the report, I can reproduce your finding. Did you know that you can access files and directories stored in the repo via the fuse `mount` command?

**Comment by fd0** [comment] 2016-12-11 10:14
I've found the cause for the error with `lchown`: Restic tries to set the owner of the restored files to `root`, which is denied since it runs as a user without administrative privileges. The reporting needs to be improved, though.

**Comment by yhafri** [comment] 2016-12-11 10:42
> Thanks for the report, I can reproduce your finding. Did you know that you can access files and directories stored in the repo via the fuse mount command?

Yes, i'm aware of the FUSE feature.

**Comment by fd0** [comment] 2017-09-29 18:53
So, I'm going to close this for now, as #1040 was merged a few days ago which adds a local metadata cache. It speeds up operations tremendously.

**Closed by fd0** 2017-09-29 18:53 UTC
Labels: enhancement, restore
