### ISSUE TITLE
Panic when backup to SFTP

### ISSUE THREAD

**Issue by Niondir** [restic/restic#665] opened 2016-11-08 21:41 UTC
## Output of `restic version`
restic 0.3.0 (v0.3.0-22-g149c01a)
compiled at 2016-11-08 10:17:03 with go1.6.3 on linux/amd64

## Expected behavior
Some more helpful error text or a successful backup

## Actual behavior
```
/ # restic backup /data
scan [/data]
scanned 27 directories, 117 files in 0:00
subprocess ssh: packet_write_wait: Connection to 192.168.0.10 port 22: Broken pipe
panic: cmd.Wait: exit status 255872 MiB / 96.238 MiB  77 / 144 items  0 errors  ETA 0:02

goroutine 143 [running]:
panic(0xa6e500, 0xc821006260)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
restic/archiver.(*Archiver).saveChunk(0xc820012e10, 0x304a88, 0x80f3d, 0x0, 0xc82100a000, 0x80f3d, 0xa0000, 0xc8200d89a0, 0x7f64477593d0, 0xc822194110, ...)
        /tmp/restic-build-354546125/src/restic/archiver/archiver.go:164 +0x12b
created by restic/archiver.(*Archiver).SaveFile
        /tmp/restic-build-354546125/src/restic/archiver/archiver.go:236 +0x629
/ #
```

## Steps to reproduce the behavior
I'm not sure, there seems to be an ussue with the SFTP pipe. I had already successful but smaller backups to that sftp. I can also connect passwordless.

Any help to further debug the issue is welcome.

**Comment by Niondir** [comment] 2016-11-08 21:44
Sometime I also get 

```
scanned 27 directories, 117 files in 0:00
subprocess ssh: Connection to u00001.your-storagebox.de closed by remote host.  ETA 0:01
panic: cmd.Wait: exit status 255
```

**Comment by debe** [comment] 2016-11-08 23:29
It's a defect in their (hetzner) sftp implementation (proftpd release path). I was told it's already fixed in proftpd current and will be deployed once released. But when I look at the release cycle I've doubts that this will take place soon.

**Comment by fd0** [comment] 2016-11-09 07:56
@debe thanks for the hint, do you have any background information on that? e.g. a bug tracker entry from proftpd or a discussion on the mailing list?

@Niondir thanks for reporting this, I'm going to close this issue as it's a duplicate of #353.

**Closed by fd0** 2016-11-09 07:56 UTC

**Comment by debe** [comment] 2016-11-09 08:46
@fd0 sadly not. But I took the opportunity to request a link to the bug tracker entry of proftpd just now.

**Comment by Niondir** [comment] 2016-11-09 09:03
I have the feeling that retrying helps. Over night I got the backup running (it was trying every hour). Not sure if some retry / reconect mechanic inside restic could also fix it.

**Comment by debe** [comment] 2016-11-09 11:43
I just got a response back. The bug should be this one http://bugs.proftpd.org/show_bug.cgi?id=4244

should we continue in #353?
