### ISSUE TITLE
Restic backup SFTP crash

### ISSUE THREAD

**Issue by joshdreagan** [restic/restic#2000] opened 2018-09-17 22:23 UTC
Output of `restic version`
--------------------------

restic 0.9.2 compiled with go1.10.3 on linux/arm

How did you run restic exactly?
-------------------------------

restic backup --parent &lt;snapshot_id&gt; --hostname &lt;hostname&gt; --tag &lt;tag&gt; &lt;path&gt; &lt;path&gt; ...

Output is too large to paste in. Here's a Git Gist: [https://gist.github.com/joshdreagan/c135f317c720352147fc7bb182e4b30c](https://gist.github.com/joshdreagan/c135f317c720352147fc7bb182e4b30c).

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

SFTP

Expected behavior
-----------------

Actual behavior
---------------

Ran for about 4-5 hours and then abruptly crashed.

Steps to reproduce the behavior
-------------------------------

1. Initialize a restic repo (SFTP)
2. Run a very large (~12TB) backup

Do you have any idea what may have caused this?
-----------------------------------------------

Not sure exactly, but I believe it has something to do with the fact that the backup takes a really long time and that it's over SFTP. I was able to mount the source directory (containing the files to be backed up) directly on the backup machine and run restic using local paths (ie, `restic -r /path/to/repo /path/to/source/files` instead of going over SFTP) and it did eventually complete (though it took about 3-4 days).

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by joshdreagan** [comment] 2018-09-19 22:17
Just confirmed that this also happens when using the rest-server backend. However, this time I also got the following log message (in addition to the stack trace I linked to above):

```
runtime: out of memory: cannot allocate 6488064-byte block (2666283008 in use)s ETA 7:46:34
fatal error: out of memoryes
```

However, I monitored both the client and backup machines and neither had exhausted their memory/swap.

**Comment by fd0** [comment] 2018-09-20 14:16
Thanks for the report, I've had a look at the stack trace and it crashed because it failed to allocate more memory. So I'd like to close this as a duplicate of #1988. Please feel free to add further comments. Thanks!

**Closed by fd0** 2018-09-20 14:16 UTC
