### ISSUE TITLE
Make File I/O a remote process similar to rsync

### ISSUE THREAD

**Issue by haraldh** [restic/restic#4525] opened 2023-10-20 20:56 UTC
Output of `restic version`
--------------------------

```
❯ restic version
restic 0.15.2 compiled with go1.20.8 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The file I/O should be a separate process which can be started on a remote machine via ssh or similar.
It's like doing rsync, but without storing the files, but putting them in the backup store.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would solve the key/secret problem: 
1. start restic on a trusted machine with all the secrets available
2. restic starts the file I/O process via ssh or whatever remote shell mechanism on the machine to backup
3. the restic process on the trusted machine can connect to the backup backend as is
4. the file I/O process delivers file metadata and file contents to the process on the trusted server on request

A simple backup user with allowed ssh public key can be installed on the to be backed up machine.
No attacker gaining access to the machine being backed up is able to get more data than he already has (no access to backups).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Very nice! Thanks for the hard work!

**Comment by MichaelEischer** [comment] 2023-10-21 17:06
Duplicate of #299 . I wouldn't expect any progress on that feature in the next few years as it requires a complete rearchitecture of the backup implementation.

**Closed by MichaelEischer** 2023-10-21 17:07 UTC
