### ISSUE TITLE
Differences b/w processed and expected values given in progress information after completion of backup may be confusing to users

### ISSUE THREAD

**Issue by Dr-Big-Man** [restic/restic#486] opened 2016-03-20 16:08 UTC
## Output of `restic version`

restic 0.1.0
compiled at 2016-03-20 16:22:53 with go1.6
## Expected behavior

enter password for repository:
scan [/Users/drbigman/Google Drive]
scanned 145 directories, 2177 files (2322 items) in 0:00
[0:35] 100%  10.617 MiB/s  374.767 MiB / 374.767 MiB  2322 / 2322 items  0 errors  ETA 0:00
duration: 0:35, 10.46MiB/s
snapshot d4e6e77a saved
## Actual behavior

enter password for repository:
scan [/Users/drbigman/Google Drive]
scanned 145 directories, 2177 files in 0:00
[0:35] 99.46%  10.617 MiB/s  372.750 MiB / 374.767 MiB  2318 / 2322 items  0 errors  ETA 0:00
duration: 0:35, 10.46MiB/s
snapshot d4e6e77a saved
## Steps to reproduce the behavior
- initialize repository, e.g.: ./restic init -r /tmp/backup
- perform backup operation of arbitrary dataset, e.g.: ./restic backup -r /tmp/backup ~/Google\ Drive/

Progress information displayed during execution of the backup does after finalization _not_ match the expected values - as displayed above at 'Actual behavior':

> 372.750 MiB / 374.767 MiB
> 
> 2318 / 2322 items

My expectation would definitely be, that differences are clearly indicating non-successful completion of the backup task. Those values _need_ to match - otherwise there is little use to me in displaying them at all? Currently the information does neither allow to confirm that creation of the backup succeeded correctly, _nor_ to identify possible problems/errors? This poses the question, what this data is displayed for at all, if it might only confuse the user afterwards?

(BTW: As perfectly explained by fd0 after presentation at C4 (2016-01-29: restic - Backups mal richtig), the observed behavior is due to inevitable changes in underlying dataset while performing backup.) 

Hope, this issue will help to find solution to this really minor nuisance - anyway, I promised to open issue, so here it is. 😉 Otherwise many thanks for this impressive project and best success.

Greetings
Dr. Big Man

**Comment by fd0** [comment] 2016-03-22 15:03
Thanks for bringing it up. I think it is indeed caused by changed files during the runtime of restic, but let's call it a bug and investigate if we can do better. I can understand your confusion.

**Comment by fd0** [comment] 2017-04-16 18:10
Could you please report whether the latest release still does this? I haven't seen this in a while, so I'm going to close the issue for now (we can always reopen it later).

**Closed by fd0** 2017-04-16 18:10 UTC
Labels: bug
