### ISSUE TITLE
0.13.1 was remarkably faster than 0.14.0

### ISSUE THREAD

**Issue by leapfog** [restic/restic#3964] opened 2022-10-11 14:08 UTC
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

(precompiled from github release page)

How did you run restic exactly?
-------------------------------
$ `restic_0.14.0_linux_amd64` --cacert certfile backup --exclude-caches --exclude /foo/bar/baz /foo/bar

(while `RESTIC_PASSWORD_FILE` and `RESTIC_REPOSITORY` are defined)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
the repository is in a `local folder` on the `same disk array`

(there are about 700 snapshots for the last 24 months)

Expected behavior
-----------------

be (more or less) as fast as 0.13.1 was

Actual behavior
---------------

0.14.0 is remarkably slower than 0.13.1

I backup about 45,000,000 files (about 35TB) where most of the files aren't modified between backup runs. 0.13.1 needs about **4 hours 30 minutes** (±15 minutes) while 0.14.0 needs about **5 hours 30 minutes** (±15 minutes). I measured about 40 backup runs, 20 for each.

I also tested (10x each) on a subset where runtime is increased from **6 minutes 30 seconds** to about **9 minutes**.

Steps to reproduce the behavior
-------------------------------
none

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm using restic for a quite a while now, on several machines. It was useful in many situations from accidentally deleted files to a broken harddisk. Thanks a lot for creating/maintaining it!

**Comment by deajan** [comment] 2022-10-11 14:19
Did you enable compression perhaps ?
Did you migrate repo version from v1 to v2 ?

**Comment by Alwaysin** [comment] 2022-10-11 14:22
Pretty sure it's a duplicate of https://github.com/restic/restic/issues/3916.
@leapfog try a dev version containing https://github.com/restic/restic/pull/3927 on https://beta.restic.net/ (a binary that is more recent than Sept 12)

**Comment by leapfog** [comment] 2022-10-11 18:16
@Alwaysin seems you're right. Latest beta finishes as fast as 0.13.1. When running 10 times, latest beta even beats 0.13.1 (66min vs. 69min). Is it safe to use that beta or should I wait until 0.14.1?

**Comment by Alwaysin** [comment] 2022-10-11 18:25
Heard some people saying they run dev versions as production (not necessarily enterprise production, idk).
Maintainers seem to only allow quality code to be merged, but you never know, there could always be a bug. Better safe than sorry I'd say.

Anyway I think it's quite an important issue actually and it should IMHO trigger a release rather sooner than later (I am not involved in the project, it's just an opinion).

**Comment by rawtaz** [comment] 2022-10-11 18:28
I'd run it.

**Comment by rawtaz** [comment] 2022-10-11 18:35
@leapfog As there is nothing *actionable* in this issue, might you close it?

**Closed** 2022-10-11 18:37 UTC

**Comment by MichaelEischer** [comment] 2022-10-11 20:28
Except for #3916, a performance difference is mostly likely due to either #3878 or #3854. Actually, I'd be rather surprised/shocked if #3916 would make a 1 hour difference for a 45million files backup.

> Is it safe to use that beta or should I wait until 0.14.1?

In general the beta builds are safe to use, although there could be some rare exceptions from time to time. That said, I'm not aware of a serious problem in the latest builds (as of this moment). Some smaller bugs like #3954 can show up from time to time, although these usually only cause temporary problems, which can be fixed by up/downgrading restic.

**Comment by leapfog** [comment] 2022-10-12 07:30
I did not mention that I do not backup all files in one run but instead have 13 folders that, in sum, hold these 35TB/45M files. Doing all at once, I'd have to keep (or forget) all the files for/at the same time. While doing individual backups allows applying individual policies. So in fact I do something like `for d in folder*/; do restic backup "$d"; done`.

Having that in mind, it's not that 0.14.0 needs an extra hour, but about extra 5 minutes **per invocation**. So at first glance #3916 and #3878 really look promising. (But isn't #3854 about restoring sparse files?)

**Comment by leapfog** [comment] 2022-10-12 10:03
The daily backup is done and yesterday's beta does indeed beat 0.13.1: Todays backup was done in **exactly 4 hours** while 0.13.1 needed something **between 4:08 and 4:41** and 0.14.0 needed something **between 5:14 and 5:44** (with each 16 backup runs).

I think I'll stick to the beta build and look forward to the next release. Thanks @MichaelEischer and others!

**Comment by MichaelEischer** [comment] 2022-10-14 19:26
> Having that in mind, it's not that 0.14.0 needs an extra hour, but about extra 5 minutes **per invocation**

That sounds indeed like an explanation. 5 minutes for such a large repository are approximately to what I'd expect.

> (But isn't #3854 about restoring sparse files?)

Yes, but there's also an optimization to speed up chunking for files containing large sections which only consist of zero bytes.
