### ISSUE TITLE
failed to read all source data during backuples

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [restic/restic#2947] opened 2020-09-23 15:55 UTC
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on darwin/amd64

How did you run restic exactly?
-------------------------------
`export RESTIC_REPOSITORY=/path/to/restic/repository/`

`export RESTIC_PASSWORD=password`

`sudo restic backup --tag=full_backup --one-file-system --verbose /`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

External hard drive

Expected behavior
-----------------
Full Backup should complete without any errors just like on my linux laptop

Actual behavior
---------------
I got hundreds of error messages from restic saying `operation not permitted`

When the `restic backup` operation finished, the final message restic printed to `stdout` was:
```
Warning: failed to read all source data during backuples 357.807 GiB, 239 errors
```

With so many errors, can the snapshot created by this backup operation actually be used to restore the system to the state it was in when `restic backup` was run?

Steps to reproduce the behavior
-------------------------------
Run the following commands, making sure to allow `sudo` to inherit the RESTIC_REPOSITORY and RESTIC_PASSWORD environment variables from the user's environment (You do this by editing the sudoers file)

```
export RESTIC_REPOSITORY=/path/to/restic/repository/

export RESTIC_PASSWORD=password

sudo restic backup --tag=full_backup --one-file-system --verbose /
```

Do you have any idea what may have caused this?
-----------------------------------------------
I think that despite being run as `sudo`, restic still doesn't have access to hundreds of files on a Mac's file system. In contrast, on linux, running restic using `su -c "restic backup --tag=full_backup --one-file-system --verbose /"` would cause `restic` to access all files and directories, and complete the backup operation without any errors.

Do you have an idea how to solve the issue?
-------------------------------------------
I don't know why restic cannot access hundreds of files and directories on MacOS even when run as sudo. Fixing this would solve the issue.

**Comment by rawtaz** [comment] 2020-09-23 16:03
This would probably have been a better fit for [the forum's Getting Help section](https://forum.restic.net/c/help/7), but let's continue here.

Is this the first time you ran restic on macOS? What macOS version are we talking about? The macOS is very picky about these things, so I'm not surprised you get errors like this. Here's a pretty long issue about it, which has been around through several macOS versions to the extent that one can even see how things change with them: https://github.com/restic/restic/issues/2051

Anyway, in order to actually have anything relevant to say about your specific symptoms, we need you to be more specific. Please give the information I asked above and also pastebin or similar the entire output including the command you run. If most of the error messages are redundant you can of course remove most of them, as long as we can see clear examples of it all.

**Comment by ChukwuemezieChristopherAneke** [comment] 2020-09-23 17:06
Yes, this is the first time I ran `restic` on MacOS.

MacOS Catalina version 10.15.6

Here is the [entire output](https://pastebin.com/JuXZAZgE "`restic backup` output pasted on pastebin")

I hope this is useful, thanks.

**Comment by rawtaz** [comment] 2020-09-24 00:45
I could be wrong but it looks like macOS security measures at work, so it's not an issue in restic from what I can tell. Can you verify that your own documents and such files were successfully backed up?

**Comment by MichaelEischer** [comment] 2020-09-24 20:47
Closing this as duplicate of #2051, as the problematic files are exactly those for which access is restricted by macOS security features. The only thing new in the error log is that restic exits with an explicit warning, which was added in restic 0.10.0.

**Closed by MichaelEischer** 2020-09-24 20:47 UTC
