### ISSUE TITLE
sftp freezing when called using sftp.command

### ISSUE THREAD

**Issue by mdemoulin** [restic/restic#1547] opened 2018-01-11 22:45 UTC
## Output of `restic version`

restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
sudo /usr/local/lib/restic_0.8.1_linux_amd64 --password-file /usr/local/etc/restic/private/restic-passwd -r sftp:backup@backup:/mnt/restic -o sftp.command=restic-sftp snapshots

It says that it is connected, but it then freezes...

## What backend/server/service did you use to store the repository?
I am running an ssh server on backup. The sftp.command is restic-sftp, which is
#!/bin/bash
sftp -i/home/bak/.ssh/id_rsa backup

## Expected behavior

I'd like restic to connect to my ssh/scp server without freezing. restic-sftp works as expected (no passphrase needed).
## Actual behavior
It freezes.

## Steps to reproduce the behavior

Just as above.

## Do you have any idea what may have caused this?
I do not.

## Do you have an idea how to solve the issue?
I do not.

## Did restic help you or made you happy in any way?
I do very much like restic, having banged my head trying to use CrashPlan and IDrive! Once this hurdle is cleared, I'll try hooking it up to B2

Again, thanks!

**Comment by mdemoulin** [comment] 2018-01-11 23:32
Actually, I may have stripped out too much from the restic-sftp script. It actually is:
#!/bin/bash
sftp -i/home/bak/.ssh/id_rsa backup@backup

Thanks again!

**Comment by fd0** [comment] 2018-01-12 08:38
Hi, thanks for the report. What you see is not a bug in restic, but rather a misinterpretation what `sftp.command` means: For restic, that's the command it runs to talk sftp via stdin/stdout. Usually, this is `ssh user@host -s sftp`, where the `-s sftp` instructs the remote side to run an sftp server process.

If, for example, you run an sftp server directly on a TCP port (a very unusual thing to do), as opposed to tunnelled via `ssh`, you would need to e.g. run netcat in order to establish the connection with: `-o sftp.command "nc server 1234"`).

What you did instead was configure restic to run the sftp client program, which does not work because restic needs to speak the `sftp` protocol with the process, and the sftp client is meant to be used by users.

So, as a quick fix you need to change the shell script to run `ssh -i /home/bak/.ssh/id_rsa backup@backup -s sftp` instead of the sftp client.

But I wonder, why did you use a shell script at all?

I'd rather recommend adding an entry in the `~/.ssh/config` (or even `/etc/ssh/ssh_config`) for the host, like this:

```
Host backup
     Hostname backup
     User backup
     IdentityFile /home/bak/.ssh/id_rsa
```

Then you can run `restic --repo sftp:backup:/path/to/repo/on/server backup [...]` and there's no need to run any custom shell script.

I'm going to close this issue as it is not a bug, please report back if it works for you, thanks!

**Closed by fd0** 2018-01-12 08:38 UTC

**Comment by mdemoulin** [comment] 2018-01-12 16:11
The /etc/ssh/ssh_conf thing fixed it.

The issue was caused by a combination of three things:
1 the backup needs to be tun as root (to catch every file);
2 I certainly did not to give root ssh access to the backup server; and
3 I was running everything through a shell script, and the quoting was causing problems
