### ISSUE TITLE
Restic dump: --path and --host flags switched in v0.15.0

### ISSUE THREAD

**Issue by lchdev** [restic/restic#4284] opened 2023-04-07 11:38 UTC
Hi !

I just recently upgraded to restic v0.15.1 from v0.14.0.
After the upgrade, my backup scripts that were using the `restic dump` command started to fail.

It seems that the `--host` and `--path` flags have been switched, as you can see in the following output:

```
> restic dump --host lchxps --path /test/file.txt latest /test/file.txt
repository 4174adfa opened (version 2, compression level auto)
Fatal: failed to find snapshot: snapshot filter (Paths:[lchxps] Tags:[] Hosts:[/test/file.txt]): no snapshot found
```

This works with v0.14.0, but is broken in v0.15.0 and v0.15.1.

Note that if I intentionally invert the `--host` and `--path` flags, the proper behavior is restored:

```
> restic dump --path lchxps --host /test/file.txt latest /test/file.txt
Hello World !
```

Also note that other commands (such as `restic restore`) do not seem to be impacted.

Thx for the great work on restic :)

**Comment by MichaelEischer** [comment] 2023-04-07 12:33
Duplicate of #4211

**Comment by meise** [comment] 2023-04-07 12:33
Looks like a duplicate of https://github.com/restic/restic/issues/4211 and https://github.com/restic/restic/issues/4252.

Try to build current master branch. Problem should be fixed in https://github.com/restic/restic/pull/4212.

**Closed by MichaelEischer** 2023-04-07 12:33 UTC
