### ISSUE TITLE
`--use-fs-snapshot` for macOS APFS

### ISSUE THREAD

**Issue by cyounkins** [restic/restic#3764] opened 2022-05-22 01:28 UTC
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.13 on darwin/arm64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Manage the creation of a point-in-time snapshot to use as the source of the backup when on macOS.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Concurrent writes during backup without snapshots can cause a variety of silent corruptions. I wrote about some of the scenarios here: https://cyounkins.medium.com/correct-backups-require-filesystem-snapshots-23062e2e7a15

Snapshots can be managed using `tmutil`. Wikipedia says "Since macOS 10.13 High Sierra, all devices with flash storage are automatically converted to APFS. As of macOS 10.14 Mojave, Fusion Drives and hard disk drives are also upgraded on installation"

Cross reference #3557 , which is this for ZFS

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
`restic` is fantastic and I recommend it to everyone! Thank you.

**Comment by MichaelEischer** [comment] 2022-05-22 15:43
Duplicate of #3714

**Closed by MichaelEischer** 2022-05-22 15:43 UTC
