### ISSUE TITLE
Display transferred data amounts and rate in live stats

### ISSUE THREAD

**Issue by alphapapa** [restic/restic#1850] opened 2018-06-17 04:55 UTC
As mentioned at https://github.com/restic/restic/commit/ff785924de95a07c800180f692c9e5d948431935#commitcomment-29388450, it would be nice if the live stats displayed the amount of actually transferred data and the rate at which it is sent.

It would also be nice if it could display the "overhead," i.e. how much data is sent and received from the remote backend that is not actual backed-up data (e.g. Obnam has a nice summary of overhead at the end of a backup run).  It might not be useful to do show the overhead for local repositories.

**Comment by MichaelEischer** [comment] 2020-10-05 19:33
Closing this as it's a duplicate of #1581.

**Closed by MichaelEischer** 2020-10-05 19:33 UTC
Labels: type: feature suggestion

**Comment by alphapapa** [comment] 2020-10-05 22:25
@MichaelEischer Since that issue does not mention overhead, it would be appreciated if you would copy that part of my request to that issue.  Otherwise, by closing this issue as a duplicate, that part of my request is effectively lost.

**Comment by MichaelEischer** [comment] 2020-10-05 23:14
@alphapapa I've copied the overhead part over to #1581, sorry I've somehow missed that part. This issue is clearly related to #1581, so I would have expected at least a corresponding comment. So I guess the duplication just got missed.

**Comment by alphapapa** [comment] 2020-10-06 14:11
Thanks!
