### ISSUE TITLE
Restic restore should take a diff of the local and only restore what is needed

### ISSUE THREAD

**Issue by abbotadmin** [restic/restic#4651] opened 2024-01-22 09:12 UTC
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic seems like a fantastic framework on the tin - The backup feature seems to work perfectly. Creating snapshots and only sending the diff is IMO one of its key pillars. I have unfortunately since found that `restore` has no such functionality as it blindly downloads entire snapshots regardless of what already exists locally.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
My usecase for Restic is as a build artifact tool - We develop video games creating large 10+GB builds that often have very little differences between builds. We are trying to use Restic to push those builds to Backblaze for backup and for downloading and using internally. Whilst the `backup` command works very well, the `restore` command is a problem for us as we now have to redownload 30GBs each time we want to get the `latest` as it does not do a diff or care about what the previous snapshot is locally.

**Comment by MichaelEischer** [comment] 2024-01-23 19:28
Duplicate of https://github.com/restic/restic/issues/407 and/or https://github.com/restic/restic/issues/2662 .
My plan is to tackle those issue for the next restic release.

**Closed by MichaelEischer** 2024-01-23 19:28 UTC

**Comment by MichaelEischer** [comment] 2025-03-23 20:11
@patrickwolf at that point in time "not planned" was also used for duplicate issues on Github. Besides, this has already been implemented in restic 0.17.0

**Comment by patrickwolf** [comment] 2025-03-24 14:57
> Besides, this has already been implemented in restic 0.17.0

great thank you!
