### ISSUE TITLE
2x performance regression with 0.11.0 on first backup

### ISSUE THREAD

**Issue by FabioPedretti** [restic/restic#3206] opened 2020-12-31 17:25 UTC
Comparing some restic versions (0.9.5, 0.9.6, 0.10.0 and 0.11.0) against [borg](https://github.com/borgbackup/borg) (see the full results at https://github.com/borgbackup/borg/issues/4498#issuecomment-752999511), with 20000 small files on a NFS, I noticed the much improved speed on second backup (likely due to https://github.com/restic/restic/pull/2970), but also noticed that the first backup (with the source already in the system cache) is about 2x slower.

Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
export RESTIC_REPOSITORY="/mnt/sshfs/myrepo"
export RESTIC_PASSWORD="x"
/usr/bin/time -f"%E" restic --cache-dir /tmp/restic-cache backup -q --tag ::1 /mnt/nfs/mysource

(using the script at: https://gist.github.com/FabioPedretti/350e18f79134a58eacdcb0793bb36735)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Private cloud accessed with SSHFS

Expected behavior
-----------------
First backup (with NFS source already on system cache) should be as fast as 0.10.0 / 0.9.6 / 0.9.5.

Actual behavior
---------------
First backup (with NFS source on system cache) is 2x slower than on 0.10.0 / 0.9.6 / 0.9.5.
If dropping system cache (with echo 3 > /proc/sys/vm/drop_caches ) 0.11.0 performs similar to previous versions.
Full results at https://github.com/borgbackup/borg/issues/4498#issuecomment-752999511 .

Steps to reproduce the behavior
-------------------------------
See "How did you run restic exactly?" section.

Do you have any idea what may have caused this?
-----------------------------------------------
https://github.com/restic/restic/pull/2970 ?

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by fd0** [comment] 2021-01-01 09:11
Just to confirm, what you're talking about are these numbers:

    Repo:   remote on SSHFS
    Source: rotating disks on NFS

    Testing with 20000 *small, all different* files

    restic 0.10.0 hot cache, first backup:   0:13.73
    restic 0.10.0 hot cache, second backup:  0:18.82

    restic 0.11.0 hot cache, first backup:   0:26.02
    restic 0.11.0 hot cache, second backup:  0:08.08

restic 0.10.0 an before takes roughly 13 seconds on the first backup and restic 0.11.0 takes double that (26 seconds). Correct?

**Comment by fd0** [comment] 2021-01-01 09:31
I'm unable to reproduce it. I've tried with the same 200k files stored in ext4 on a rotating disk, repository was stored in a `tmpfs`.

Can you please repeat the test to confirm 0.10.0 is fast on the second backup and 0.11.0 is slow?

If that's the case, would you mind running `git bisect` between `v0.10.0` and `v0.11.0` as well as run the tests with `strace -f -c` so we can check the differences in syscalls?

Thanks a lot!

**Comment by FabioPedretti** [comment] 2021-01-06 17:29
Yes, I was referring to that result. For me the issue is 100% reproducible (tried for many days), however after some check, if I put a
`find -type f -exec cat '{}' > /dev/null \;`
before the "hot cache" tests, I get with 0.11 similar results of 0.10.
So in the end it looks like something related to the system/test conditions for some reasons invalidating the system cache.
Still strange however that it only happens with 0.11 and not with 0.10.

**Comment by fd0** [comment] 2021-01-07 08:18
That's indeed odd, hm. I'm not aware of any relevant changes between 0.10.0 and 0.11.0. Would you be willing to run a `git bisect` so we can pin the commit?

**Comment by fd0** [comment] 2021-01-28 09:09
I'm closing this issue for now, please let me know if you're interested in doing a bisect so we can find out what's going on. Thanks!

**Closed by fd0** 2021-01-28 09:09 UTC
Labels: state: need feedback

**Comment by FabioPedretti** [comment] 2021-01-28 09:17
OK, I was testing against borg to see how they compare (the result is that restic is faster for the "many unchanged files" use case) but actually I don't have time to work anymore on this.
Maybe I'll try again when I'll consider migration to restic (likely when borg 1.1 will go out of support (borg 1.2 is slower) or restic will support compression).
Thanks.

**Comment by fd0** [comment] 2021-01-28 19:13
Fair enough, thanks for the feedback! :)
