### ISSUE TITLE
Can't copy from FUSE mount

### ISSUE THREAD

**Issue by durcom** [restic/restic#988] opened 2017-06-01 16:43 UTC
## Output of `restic version`

latest
## How did you start restic exactly? (Include the complete command line)
restic mount -allow-other -r repolocation (on ubuntu 16.04)

## What backend/server/service did you use?
samba
## Expected behavior
I can mount the restic repository no problem.  I have it shared out as read only via Samba and can view all files/folders in the snapshots from a win 7 machine.  However, when I try to copy a file from the share to the local workstation I get a "Could not find this item...This is no longer located in \\server\share  Verify the item location and try again".  I also cannot open any file from the samba share.

Other interesting issue is if I hit "properties" in windows on a folder on the samba share, the # of files and total file size of the folder shows incorrect in windows 7 (less than it should be).  However, if I do it a second time, it returns the correct numbers.

**Comment by durcom** [comment] 2017-06-01 18:56
Further Details:

Seems like folders copy fine, just files can't be accessed.  When I look at windows properties for the files on the samba share it comes back with files size zero, and on security tab of properties it shows "requested info is unavailable".

**Comment by fd0** [comment] 2017-06-01 19:08
Hm, I don't have any idea how to start debugging this. Could you please create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)? Please be aware that it may contain sensitive data such as file and directory names.

**Comment by durcom** [comment] 2017-06-01 19:32
Sorry, compiling stuff etc. is beyond me.  Linux noobie...

Can't you just create a restic repository on linux, back up a few files to it and then try to access from win via samba to see if you can reproduce it?

here is my smb.conf file:  

global]
	map to guest = bad user
	log file = /var/log/samba/log.%m
	passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
	pam password change = yes
	panic action = /usr/share/samba/panic-action %d
	winbind trusted domains only = yes
	passdb backend = tdbsam
	workgroup = WORKGROUP
	passwd program = /usr/bin/passwd %u
	max log size = 1000
	winbind use default domain = yes
	os level = 20
	server string = %h server
	unix password sync = yes
	obey pam restrictions = yes
	write raw = no
	syslog = 0
	dns proxy = no
	read raw = no
	usershare allow guests = yes
	server role = standalone server
	hide dot files = no
#        server signing = auto
#        client signing = auto

# File creation mask is set to 0700 for security reasons. If you want to
# create files with group=rw permissions, set next parameter to 0775.
   create mask = 0770

# Directory creation mask is set to 0700 for security reasons. If you want to
# create dirs. with group=rw permissions, set next parameter to 0775.
   directory mask = 0770

[printers]
   comment = All Printers
   browseable = no
   path = /var/spool/samba
   printable = yes
   guest ok = no
   read only = yes
   create mask = 0700

[restic2]
	writeable = yes
	public = yes
	force create mode = 770
	path = /mnt/restic_mnt
	guest account = ed
	delete readonly = yes
	force user = root
	create mode = 770
	valid users = root,ed,@root,@ed
	force group = root
	directory mode = 770
	force directory mode = 770

**Comment by durcom** [comment] 2017-06-01 19:37
![image](https://cloud.githubusercontent.com/assets/29127322/26697374/baaea6a4-46df-11e7-9a68-bbe7fca54d1e.png)

above shows file on samba share from restic mount   (note size 10K)

![image](https://cloud.githubusercontent.com/assets/29127322/26697401/e3feb468-46df-11e7-8d79-e4ba1e0654ff.png)

Same file but shows files size of "0"

![image](https://cloud.githubusercontent.com/assets/29127322/26697431/0acc242c-46e0-11e7-8cf8-d6319b9cbb3a.png)

shows security error

![image](https://cloud.githubusercontent.com/assets/29127322/26697469/2a7a2b3e-46e0-11e7-8805-1f4342cb79ed.png)

error when I try to copy

**Comment by middelink** [comment] 2017-06-01 22:10
Wasn't there some issue with the inode/handles in the fuse mount not being persistent?
Can you try to copy a file from the /mnt/restic_mnt to say /tmp? (instead of going thru samba) It will make clear if it the mount itself is bad or your remounting with samba is.

**Comment by durcom** [comment] 2017-06-02 01:13
I can copy on the linux machine from the mount to another folder and it works fine, so it is something to do with Samba I think.

**Comment by durcom** [comment] 2017-06-06 16:29
middelink, are you talking about an issue with restic or with fuse in general in regards to the handles not being persistent?  any background on that issue?

**Comment by fbkopp** [comment] 2017-06-06 18:33
I have the same error and i think mount a repository and share via samba should work out of the box.

**Comment by fd0** [comment] 2017-06-06 19:17
@fbkopp please describe your situation and the error you're seeing.

@durcom which system user is used for samba? which is used for running restic?

**Comment by fbkopp** [comment] 2017-06-10 16:48
@fd0 I have same situation as @durcom have described above. Using Ubuntu 16.04 and running restic and samba share as root user. As client used windows 10. I can list directories and files, this part is ok. Coping a file is the trouble. As windows special char COLON (:) are forbidden, i changed fuse code to replace with underline (samba option "mangled names" not helped) , and this was the first problem i resolved changed the code (https://github.com/restic/restic/blob/master/src/restic/fuse/snapshot.go#L127) , the second is really that cannot copy the file from samba share.  
ps; sorry for my bad english.

**Comment by fbkopp** [comment] 2017-06-10 18:46
i have create a debu log.

- add user root to samba
smbpasswd -a root
- enable root user on samba
smbpasswd -e root

/etc/samba/smb.conf:
[test_restic]
  path = /home/test_restic
  guest ok = yes
  valid users = root
  guest only = yes
  browseable = yes
  read only = yes
  force user = root
  force group = root

replace line src/restic/fuse/snapshot.go#L127 with: timestamp := strings.Replace(snapshot.Time.Format(time.RFC3339),":","_",-1)

restic command:
root@kopp-pc:~# restic -r /tmp/repo/ mount --allow-other /home/test_restic/mounpoint/

used gnome nautilus to browse samba share
smb://kopp-pc/test_restic/mounpoint/snapshots/2017-06-10T14_48_21-03_00/linux/zoneminder-doc_1.30.4-xenial-2017051701_all.deb

[restic-debug.txt](https://github.com/restic/restic/files/1066033/restic-debug.txt)

**Comment by obrienmd** [comment] 2018-01-09 23:47
Same issue here, with latest restic (0.8.1) on Ubuntu 16.04.3 server, Samba 4.3.x and Windows 10 client.

**Comment by fd0** [comment] 2018-01-13 09:31
I've pushed a possible fix to the branch `fix-988`, can one of you please try it and report back? I've uploaded a compiled version of that branch here: https://fd0.me/tmp/restic_v0.8.1-38-gf49f5c59_linux_amd64.bz2

**Comment by obrienmd** [comment] 2018-01-13 15:36
Sure, I should have a chance to try this in the next day or so - thanks!

**Comment by obrienmd** [comment] 2018-01-14 03:04
Sorry, no luck - same issue with that build. I think this build wasn't build with debug, as I set the env var and don't see a debug log in /tmp.

**Comment by fd0** [comment] 2018-01-14 09:05
Yes, the build was without debug, we already have a debug log. I'll try to find time to setup a samba share...

**Comment by fd0** [comment] 2018-01-14 12:56
We (@scoddy and I) are unable to reproduce the issue at all, using Debian stable with Samba `4.5.12-Debian` and Linux, Windows 7 and Windows 10 as clients. Everything works, accessing files and folders, coping files, folder properties and sizes etc.

What we need from you:
 * exact problem description
 * exact version of samba
 * the smb.conf that you used
 * a small sample repository with just a few files that can be used to reproduce the issue (including the password for the repo)
 
So I'm now going to close this issue for now, I'm pretty certain it is not a bug in restic. Please feel free to add further comments so that we can eventually find the cause for this issue.

**Closed by fd0** 2018-01-14 12:56 UTC
Labels: feedback needed, fuse

**Comment by obrienmd** [comment] 2018-01-15 13:08
That gave me a good lead (newer Samba) - I believe this is some sort of interop bug between older versions of Samba and restic's FUSE mount (I tried a few others without issue), as I compiled 4.7.x from source on 16.04 and it didn't exhibit the same behavior.

I'm going to move forward on all repo-hosting servers using Debian testing, and 18.04 is just around the proverbial corner. On the other hand, I'd like to help if you think it's worth it - if you do, please let me know and I'll re-run tests and pull the data you described.

**Comment by Mortim** [comment] 2018-03-03 16:15
I also ran into this problem and tried to pinpoint it a bit more.
I am using:
```
$ smbd -V
Version 4.5.12-Debian
$ restic version
restic 0.8.3
compiled with go1.10 on linux/amd64
```
and on Windows:
```
>restic.exe version
restic 0.8.3
compiled with go1.10 on windows/amd64
```

The main thing I found out is that the problem seems to only occur with backups done from a Windows host.

Here is a small restic repo (password is test) with just two snapshots, one done from Windows and one from Linux: [restic_test.tar.gz](https://github.com/restic/restic/files/1777605/restic_test.tar.gz)
When this is mounted with `restic mount --allow-other ./mount/` and shared via samba, I can access the file in the Linux snapshot fine from a Win10 machine, but the Windows snapshot gives an error ("Could not find this item") when I try to open the file.

My smb.conf looks like this:
```
[global]
   map to guest = bad user
   guest account = guestuser
[data]
  follow symlinks = yes
  path = /mnt/disk1/
  browseable = yes
  read only = yes
  guest ok = yes
  vfs objects = catia
  catia:mappings = 0x3a:0xf7
```
The rest is left default. The catia mapping is used to map the colon, as otherwise the names of the folders with the snapshot times get mangled badly. The Problem also occurs without this.
I hope that helps, if you need any more info please tell me.
