### ISSUE TITLE
Recover from no free space fails writing lock file

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#4595] opened 2023-12-21 10:44 UTC
Output of `restic version`
--------------------------
restic 0.15.2 compiled with go1.20.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Backblaze B2

Problem description / Steps to reproduce
----------------------------------------
I exceeded the storage cap and would like to recover from this.
Running `restic prune --unsafe-recover-no-free-space SOME-ID --no-lock` fails with
```
Save(<lock/1b3579591f>) returned error, retrying after 475.560722ms: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
```

Expected behavior
-----------------
Restic should honor the `--no-lock` flag and don't try to upload a lock file.

Actual behavior
---------------
Restic ignores the `--no-lock` option and still tries to upload a lock file.

Do you have any idea what may have caused this?
-----------------------------------------------
Restic ignoring the `--no-lock` option.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I did a full restore after migrating to new drives and it worked flawlessly.

**Comment by MichaelEischer** [comment] 2024-07-06 20:11
Duplicate of #3582

**Closed by MichaelEischer** 2024-07-06 20:11 UTC
Labels: type: bug, category: prune
