### ISSUE TITLE
Incremental backups of the same (small) directory very slow

### ISSUE THREAD

**Issue by yhafri** [restic/restic#684] opened 2016-12-03 19:46 UTC
## Output of `restic version`

```
$ restic version
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-11-30 04:53:47 with go1.7.3 on darwin/amd64
```

A colleague confirmed the same behavior on a single file under Linux.

```
$ restic version
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-11-30 04:39:06 with go1.6.2 on linux/amd64
```

## Expected behavior

Subsequent backups of the same directory should be faster than the initial backup.

## Actual behavior

The first backup was quick. Running the same backup on the same directory (no change has been made to it) never last.

This can be related to this  [ticket](https://github.com/restic/restic/issues/386)

## Steps to reproduce the behavior

Here is what i did for testing:
```
$ mkdir t && cd t
$ for i in `seq 1 15`; do dd if=/dev/urandom of=$i.bin bs=1M count=1; done
$ du -hs .
15M	.
```

Then, try to backup the directory more than once with [Minio](https://www.minio.io/).

## Workaround

Using `backup --force` seems to solve it. 
I'm now having this option set by default in my *.bashrc*:
```
alias rbackup="restic backup --force"
```

**Comment by fd0** [comment] 2016-12-03 20:52
Thanks for reporting this issue. Could you please create a debug log?

**Comment by fd0** [comment] 2017-05-14 20:20
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-05-14 20:20 UTC
Labels: bug, feedback needed
