### ISSUE TITLE
rest backend: Panic if connection drops or times out, halting backup

### ISSUE THREAD

**Issue by mholt** [restic/restic#1057] opened 2017-06-21 18:01 UTC
## Output of `restic version`

restic 0.6.1 (v0.6.1-127-gd76fa22b)
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)

restic --repo "rest:https://my-server.com/myrepo" backup --exclude-file ~/exclude.txt ~

## What backend/server/service did you use?

rest (rest-server)

## Expected behavior

Backup resumes after broken connection

## Actual behavior

My Internet quality here is horrible, and sometimes the connection drops:

```
panic: client.Post: Post https://my-server.com/myrepo/data/e06018692a80f493c7c62b4c4dec1d2608f4cd39e9a21bc0f62ece91959902ce: read tcp 192.168.1.88:55244-><ip>:443: read: connection reset by peer

goroutine 16962 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4248db720, 0x181d6a0, 0xc420012408, 0x119135, 0x200182, 0x108715a7800000, 0xc425594000, 0x200182, 0x26a000, 0xc421bd3e40, ...)
	src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:239 +0x3a4
```

Or times out:

```
panic: client.Post: Post https://my-server.com/myrepo/data/3765a301e5cb31f42680707932a3d446178776a4bc8b9295c7e4c56e9749dc76: read tcp 192.168.1.88:52331-><ip>:443: read: operation timed out
```

## Steps to reproduce the behavior

Killing the backend should do the trick

## Do you have any idea what may have caused this?

Restic doesn't attempt to re-establish connections during backups. I think restic should do this so I don't have to put my restic command in a loop...

Also, even with a good connection, it's not uncommon for me to close my laptop, travel somewhere else, then open it up and reconnect to the Internet. It'd be nice if restic would just resume the backup when the connection is restored.

**Comment by fd0** [comment] 2017-06-24 08:02
Yeah, restic should retry when the backend returns an error. This is a duplicate of #415.

**Closed by fd0** 2017-06-24 08:02 UTC

**Comment by mholt** [comment] 2017-06-24 15:42
Ah, sorry about that. I saw that issue but didn't realize it applied to any backend. Thanks for looking into it!
