### ISSUE TITLE
restore to wrong path (path not preserved inside snapshot)

### ISSUE THREAD

**Issue by MrMoronIV** [restic/restic#1701] opened 2018-04-02 15:36 UTC
## Output of `restic version`
restic 0.8.3
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?
In a bash script to create the backup
/usr/bin/restic -r swift:backups:/filebackups -p /etc/resticBackupP --files-from /backupList backup

backupList is:
/var/www/html/site
/home

The backup is created as expected, (I think)?

Now when I do a restore using a bash script: 
/usr/bin/restic -r swift:backups:/filebackups -p /etc/resticBackupP restore latest --target /tmp/restic

it outputs two folders in /tmp/restic:

/home
/site

Also when I mount the repository, it gives me the same folders in the latest snapshot directory

## What backend/server/service did you use to store the repository?

Swift

## Expected behavior

I expected:

/home
/var/www/html/site

## Actual behavior

I got
/home
/site

## Steps to reproduce the behavior

just do a backup and restore (or mount) as described above

## Do you have any idea what may have caused this?

no idea

## Do you have an idea how to solve the issue?

have no clue

When I do a snapshots command I get the backup with the two paths defined correctly in the overview, it's only when I restore or mount that it does funny stuff and act like /site is on the same level as /home

## Did restic help you or made you happy in any way?

Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you Thank you thank you.

I've been waiting 10 years for a program as simple and user-friendly as this, Did I say thank you? Thank you!

That mounting option to browse backups,,,,,, omg :heart: I'm in love.
It's weird what can make you happy

**Comment by dimejo** [comment] 2018-04-02 17:10
This looks like a duplicate of #1286.

**Comment by fd0** [comment] 2018-04-02 17:43
Hey, thanks for your report. It was very heartwarming to read that you like restic a lot. I can relate to that very much, as I started restic to scratch my own itch because at the time (nearly four years ago) it felt like there wasn't any good backup program.

Yep, this issue is a duplicate of #549 (and #1286, incidentally), so I'm closing it as a duplicate. restic does not preserve enough path information. I'm currently working on the new archiver code (see #1494).

Please subscribe over at #549 to get notified of any (eventual) progress. Thanks!

**Closed** 2018-04-02 17:43 UTC
Labels: bug, duplicate

**Comment by MrMoronIV** [comment] 2018-04-02 19:38
You're welcome for the kind words.

Do you have somewhat of an ETA for the new archiver? I see this issue is over a year old now.

**Comment by fd0** [comment] 2018-04-02 19:54
I've learned (the hard way) not to promise any deadlines, but rest assure: I'm currently working on it every day. You can follow my progress in #1494, I sometimes push my code there and update the todo list at the top of the issue.
