### ISSUE TITLE
go install restic

### ISSUE THREAD

**Issue by cathalgarvey** [restic/restic#368] opened 2015-12-07 16:57 UTC
Hi,

After a glance at the `build.go` file it appears that much of the complexity that build-script deals with is vendoring of dependencies; a recognised problem in Go. However, this build system seems to preclude using `go get github.com/restic/restic` as an install option, which is a pity!

Now that a number of third party systems exist to handle github-tag-specific `go get`ting, or alternatively now that a number of clean vendoring systems exist, is there a plan to move to a `go install restic` system that would clean things up? :)

**Comment by fw42** [comment] 2015-12-07 16:58
What "clean vendoring systems" are you referring to?

**Comment by xor-gate** [comment] 2015-12-07 18:34
I think @cathalgarvey means restic is not compliant with vanilla go tools to build, install and test restic. Which was also a pain in the ass when I tried to create a debian package.

This is not possible with restic (as far as I tested):
https://golang.org/doc/code.html

**Comment by fd0** [comment] 2015-12-07 19:58
Oh, that's wrong, restic is compliant with the "go way" of installing software, just run:

    $ go get github.com/restic/restic/cmd/restic

(The main binary lives in `cmd/restic`, so `go get github.com/restic/restic` only gets you the top-level library)

When the restic repository is checked out in `$GOPATH/src/github.com/restic/restic` and the dependencies have been installed into the `GOPATH` (e.g. by running `godeps restore`), all the usual Go tools and workflows can be used (e.g. `cd cmd/restic && go build`). The setup is described here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#development-environment

We're using `build.go` to solve the following problems:
 * The compile process for end-users (not developers!) should be easy. Especially they should not have to setup a `GOPATH` and check out the repository into exactly the right sub directory (`src/github.com/restic/restic`), instead the code should be compilable directly from a clone of the repository. In the background, a `GOPATH` is built on the fly by `build.go` in a temporary directory.
 * Builds should be reproduceable, `build.go` always uses exactly the vendored dependencies
 * The resulting restic binary should have a unique version number that can be used to exactly identify what code was used to build it, for this `build.go` adds the git commit id (among others), so all dependencies are fixed.
 * The build process does not depend on any third-party tools that aren't installed with a standard Go environment, so we can tell users: "Install Go and run `go run build.go`, then you're done."

I'm thinking about switching to `gb` for developers, because that's a really nice build system, but that's still not good for end-users.

**Comment by fd0** [comment] 2015-12-07 20:09
If you find your question was answered successfully, please close this issue :)

**Comment by cathalgarvey** [comment] 2015-12-07 20:13
Thankyou for that information Alexander, that helps a lot! :)

Will close when I'm back at Keyboard.

On 7 December 2015 20:09:14 GMT+00:00, Alexander Neumann <notifications@github.com> wrote:
>If you find your question was answered successfully, please close this
>issue :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/restic/restic/issues/368#issuecomment-162645486

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2015-12-08 07:34 UTC
Labels: question

**Comment by dolanor** [comment] 2015-12-10 15:07
I must say that I don't see a lot of end-user going to github and do a go get.
I would even say that most of end-user wouldn't have go in the right place.
And if you have go, you should have GOPATH.

So it's either
* you download go and configure it well with a gopath, and then you can't go install/build like the standard go app
or
* you download go and and install go without configuring it right, and then you have to do a non-standard build

None of them seems a good option to me for end-users.

How about a static restic binary in some simple website instead ? This would be more what end-users would do in the first place. And with a nice continuous integration/deployment system like drone, nothing really has to be done for it.

What do you think?

**Comment by cathalgarvey** [comment] 2015-12-10 16:50
There should be a binary download option for users without Go installed. But, for users with go installed, the install should be `go install github.com/restic/restic`. What exists now is a suggestion to install go, half-configure it, and then run a script for vendoring purposes. That's half-way in between the two routes I think restic should offer; sane binaries, and sane `go get`/`go install`.

But, as long as you *can* `go get`, I'm satisfied. ;)

**Comment by fd0** [comment] 2015-12-10 19:52
I'll answer to @dolanor first:

> I must say that I don't see a lot of end-user going to github and do a go get.

In my experience, this is a bit different: I've seen a lot of first-time users who do exactly the following: Go to the website and follow the instructions there, which currently tells you to clone the repo and run the build script.

> And if you have go, you should have GOPATH.

I disagree: Most people I've talked to can easily install Go by running `apt-get install golang-go` or `dnf install go`, but don't have an idea what a `GOPATH` even is. They don't care about a `GOPATH`, they just like to use restic.

> So it's either
>
>  * you download go and configure it well with a gopath, and then you can't go install/build like the standard go app or
>  *  you download go and and install go without configuring it right, and then you have to do a non-standard build

I think that's wrong: Currently, you don't have to configure anything at all. You install Go, run the build command, and you're done. No configuration involved at all, and even does not leave any clutter outside of the repository directory.

> None of them seems a good option to me for end-users.

I disagree again: I'm convinced that the process we're having at the moment is good based on the feedback I'm getting. There isn't a single GitHub issue where someone wasn't able to compile restic. I'll happily point people to the documentation on how to setup a proper GOPATH whenever someone would like to hack on restic.

> How about a static restic binary in some simple website instead? This would
be more what end-users would do in the first place. And with a nice continuous
integration/deployment system like drone, nothing really has to be done for it.
>
> What do you think?

Yes, but we'll do that later. There are some issues that must be resolved first.

@dolanor So, what's your proposal for changing the build process? Dump `build.go` and offer pre-compiled binaries? How would that solve the things that `build.go` currently does? https://github.com/restic/restic/issues/368#issuecomment-162642530

**Comment by fd0** [comment] 2015-12-10 20:06
> But, for users with go installed, the install should be go install github.com/restic/restic.

I disagree, please have a look at https://github.com/restic/restic/issues/368#issuecomment-162642530

Using `go install ...` does not work. I'll only list a few points that will be really painful to deal with:

 * `go install` will always fetch the master branch for all dependencies in a transitive fashion. When one of these libraries change a function signature (which happens quite often), the build breaks. For the user, this looks like restic is crappy software, because it does not even compile. In my opinion, that's really bad, because a first impression cannot be repeated, so the user will search for some other backup solution.

 * Suppose the build process with `go install` successfully compiles a binary, and a user reports a bug, what should the user report as the restic version? How can we (as developers) reproduce the issue, without any clue exactly what versions of the libraries (and restic!) were used? That's really bad, because it not only frustrates the user (the bug isn't solved) but also the developers, who have no idea what caused the bug.

 * When users already have an old version of a library in their GOPATH, `go install` won't fetch the library nor update the repository, so the old version will be used. This makes it even harder to remotely guess what version of that library was used to compile the binary.

 * This also means that when arbitrary versions of the dependencies are used, the CI tests are worthless, because users will almost certainly end up with a different mix of libraries, which wasn't at all tested in the CI tests. That's not good.

> What exists now is a suggestion to install go, half-configure it, and then run a script for vendoring purposes.

Now you're being unfair: There is no configuration step and `build.go` solves more issue than only vendoring, see my comment above.

Let's say that we change the minimum Go version to 1.5, so we can use the Go vendor experiment and have vendoring built into the `go build` command, this would only solve that single point. What about having a proper version in the binary? What about not having to setup a GOPATH as an end user?

> That's half-way in between the two routes I think restic should offer; sane binaries, and sane go get/go install.

I agree that we should offer binaries at some point. I strongly disagree regarding go get/go install. In my opinion, that's quite the opposite of sane. :)

Thanks for your opinion, @dolanor and @cathalgarvey. It helped me to question the current build system. Unfortunately, I still stand by my opinions ;)

**Comment by devster31** [comment] 2015-12-12 23:50
##### `go install` will always fetch the master branch for all dependencies...

`godep save -r` rewrites the imports so that the `go` commands always use the correct version of the dependencies; from their readme:
>The additional flag `-r` tells save to automatically rewrite package import paths. This allows your code to refer directly to the copied dependencies in `Godeps/_workspace`. So, a package C that depends on package D will actually import `C/Godeps/_workspace/src/D`. This makes C's repo self-contained and causes `go get` to build C with the right version of all dependencies.  

It would be horrible to look at but it would do its job.
##### When users already have an old version of a library in their GOPATH, go install won't fetch the library nor update the repository, so the old version will be used.

This is easily fixable with the `-u` option if I'm not mistaken; from `go help get`:
>The -u flag instructs get to use the network to update the named packages and their dependencies.

Assuming both the above are acceptable solutions the versioning issue could theoretically be solved the way `hugo` does it or in a similar fashion: they hardcode the version as a constant (something that the `build.go` takes into account by reading the VERSION file) and generate build date at compile time (go version and architecture could be added) they also have a way to include a commit hash with a build flag for developers. The stuff that's now done on the `build.go` file could be done at compile time with `go get` or `go install`, also `go get` downloads the repository itself, which means that a commit hash could also be generated during the build process.
https://github.com/spf13/hugo/blob/master/commands/version.go
This all assumes that master branch (or whatever the default is) is always stable. Also, all of this doesn't actually help for end-users that do not have a `$GOPATH`, however I feel that these users would benefit the most from a compiled binary.

**Comment by xor-gate** [comment] 2015-12-15 20:50
Restic could be build automaticly build for multiple platforms on push:
https://gobuilder.me

**Comment by fd0** [comment] 2015-12-16 07:44
Thanks for the hint, there are several similar services.

We need to discuss this when the time comes. There are some problems to solve before we can offer binaries for all platforms (e.g. CGO for libc `getpwent()`).

And for automatic compilation, having reproducable builds and an exact version number is even more important.

**Comment by cathalgarvey** [comment] 2016-04-12 08:34
..So, it appears that the build system has been changed to include a ton more magic, and `go get <url>` no longer works. Now import paths are coming from a root src dir "restic" and the build-script establishes this directory at build time.

I use restic a lot, and I will continue to because it's great. But this makes re-deploying on new machines really awkward, whereas I'd have loved a two-liner:

```bash
sudo apt-get install golang-go
GOPATH=$HOME/go go get github.com/restic/restic/src/cmds/restic
```

**Comment by fd0** [comment] 2016-04-12 09:32
Hi, thanks for your comment. I can see that it is a bit more complicated to install restic since we've switch to using `gb` as the build tool in #444. That's where the folder structure comes from: it's the standard structure `gb` projects are required to have.

I've outlined above why we think that using `go get` is not a good idea. It used to work, but as a byproduct of switching to `gb`, using `go get` does not work any more. We have no plans to make it work again, due to the points I detailed in the comments in this issue.

You can easily install restic as follows:
```
$ sudo apt install golang-go
$ git clone https://github.com/restic/restic && cd restic && go run build.go
```
This uses the officially recommended way of building restic as described in our README file. For working on restic, it's recommended to install and use `gb build` to build it. `gb` does not require any configuration at all and just works.

By the way: Why do you recompile restic on every new machine you install, rather than copying the (statically linked) binary over?

**Comment by cathalgarvey** [comment] 2016-04-12 10:16
Understood, if unfortunate from my perspective.

> By the way: Why do you recompile restic on every new machine you install, rather than building it locally 
> and copying the (statically linked) binary over? I'd love to understand your use case here.

Restic is only one of many tools that I habitually install on a fresh machine upon installing Python3.x and Go. In both language cases there's a great package manager for installing libraries and tools; respectively, `pip` and `go <cmd>`. Yes, the latter in particular suffers problems, but those problems are common to all package management systems and stem largely from developer foibles and inconsistencies (of which I too am guilty).

Also, when I want to update software, I can do `go get -u <url>` and updates proceed silently and quickly. Likewise, `pip` supports easy updating, handy in particular for fast-moving packages like `youtube-dl`.

So, asking "why not just do it our way?" is kind of like asking why I don't compile everything from source and just use my own custom-built distro; on a new machine and for regular software updates, my best friends are `apt-get`, `pip3` and `go`. Anything that falls outside their scope and requires special handling is misfortune, from my point of view.

Still, restic offers binaries and may end up in the Ubuntu repos someday, and failing that it's a tempdir-and-copy-paste job to install at present. Where possible I re-use my own built binaries, but sometimes I don't have a clear path to get a binary file from one computer to another, and internet installation is (for most packages) faster and cleaner.
