### ISSUE TITLE
Backup include/exclude-list

### ISSUE THREAD

**Issue by Thor77** [restic/restic#414] opened 2016-02-06 12:32 UTC
I would really appreciate an option to specify a directory include/exclude-list to the backup-command (maybe implemented like [--include-filelist](http://duplicity.nongnu.org/duplicity.1.html#sect9) in duplicity):
```
+ /etc/
- /etc/letsencrypt/
+ /var/lib/
+ /home/
- /home/vmail/
```
would result in backing up `/etc/` recursively without `/etc/letsencrypt`, `/var/lib/` and `/home/` without `/home/vmail/`

**Comment by fd0** [comment] 2016-02-06 12:39
Thanks for raising the issue. I had a look at the old issues about this function, and it seems I came up with exactly the same proposal, see #233.

**Comment by fd0** [comment] 2016-02-06 13:09
As discussed on IRC, close this issue a duplicate of #233, @Thor77 really meant something subtly different. New issues for that are #416 and #417.

**Closed by fd0** 2016-02-06 13:09 UTC
Labels: backup, feature, help wanted
