### ISSUE TITLE
feat: Improve Logging in Case of Errors/Retries

### ISSUE THREAD

**Issue by ichtestemalwieder** [restic/restic#2556] opened 2020-01-20 06:31 UTC
First of all thanks, for the very helpfull program! 

Problem:
When running backups with the `--verbose` flag, I got the following logs below. The most important thing about backups is reliability and being able to trust the program/restic. However these logs only show the error. We do not get any information about the (hopefully) successfull remediation of the error! The logs below "continue" directly after the error but it is not abvious if the lines after the error are the successfull remediation or not. But this information is absolutely necessary, I currently have completely lost trust in restic and live in fear, as I do not know if my backups are corrupted/inconsistent/incomplete. 

Solution/Feature-Request:
Please directly log after the error what was done to remediate the error and if the remediation was successfull. Thanks very much!

Envs: 
latetest restic with rclone backend
backup to onedrive personal 

```
...
uploaded intermediate index 05db61b4
rclone: 2020/01/15 21:50:08 ERROR : data/a1/a19305969440ef594154f8d44a055153368cf6725b29dc369ef9b3c6e41d3711: Post request put error: itemNotFound: uploadSessionNotFound: Upload session not foundl-DATA/My Businesses/sjkjhkjhkjhkjs.de/Design/Designer/Designer.docx
rclone: 2020/01/15 21:50:08 ERROR : data/a1/a19305969440ef594154f8d44a055153368cf6725b29dc369ef9b3c6e41d3711: Post request rcat error: itemNotFound: uploadSessionNotFound: Upload session not found
Save(<data/a193059694>) returned error, retrying after 720.254544ms: server response unexpected: 500 Internal Server Error (500)
uploaded intermediate index 96e04496
...
uploaded intermediate index 879130a2
rclone: 2020/01/15 22:09:27 ERROR : data/fd/fdda4523dbd3c5a59027b596a842ab3be1149a1fd1a4ed718be84c1ff78fa3ce: Post request put error: itemNotFound: uploadSessionNotFound: Upload session not foundl-DATA/My Data/Alte Outlook Daten/Outl@sjkjhkjhkjhkjs.de-0000000c.pst
rclone: 2020/01/15 22:09:27 ERROR : data/fd/fdda4523dbd3c5a59027b596a842ab3be1149a1fd1a4ed718be84c1ff78fa3ce: Post request rcat error: itemNotFound: uploadSessionNotFound: Upload session not found
Save(<data/fdda4523db>) returned error, retrying after 582.280027ms: server response unexpected: 500 Internal Server Error (500)
uploaded intermediate index 9697feca
uploaded intermediate index 6c57def4
...
uploaded intermediate index 4ac4d51f
rclone: 2020/01/16 02:54:01 ERROR : data/73/735ece9362103b1eb280d444e84db1a15253664b96ca5ce4dab302794e8c64c9: Post request put error: invalidRange: fragmentOverlap: The uploaded fragment overlaps with data that has already been received.einzusortieren/Groove Magazin/98 54 Groove IMG_20180515_0004.pdf
rclone: 2020/01/16 02:54:01 ERROR : data/73/735ece9362103b1eb280d444e84db1a15253664b96ca5ce4dab302794e8c64c9: Post request rcat error: invalidRange: fragmentOverlap: The uploaded fragment overlaps with data that has already been received.
Save(<data/735ece9362>) returned error, retrying after 468.857094ms: server response unexpected: 500 Internal Server Error (500)
uploaded intermediate index 57c6741e
uploaded intermediate index 1fbfd800
....

```

**Comment by MichaelEischer** [comment] 2020-03-29 19:45
Would your issue be solved by #1734 / #2661 ?

**Comment by creativeprojects** [comment] 2020-03-29 20:19
I've had the same fear, but after looking at the code, I can confirm if it cannot load or save after retrying you do get a Fatal error and the backup (or restore) stops.

**Comment by MichaelEischer** [comment] 2021-07-10 22:51
Closing as duplicate of #1734.

**Closed by MichaelEischer** 2021-07-10 22:51 UTC
Labels: state: need feedback, type: feature enhancement
