### ISSUE TITLE
doc: Tilde (~) does not expand to home in exclude-file

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2691] opened 2020-04-13 11:57 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
`--exclude /home/jc/foo` works  
`--exclude $HOME/foo` works  
`--exclude ~/foo` works
Now in `--exclude-file ~/.foo`:
```
/home/jc/foo` works  
# ^ works
$HOME/foo` works  
# ^ works
~/foo
# ^ does not work
```

What are you trying to do?
--------------------------
Save other people's time troubleshooting why the excludes file does not work.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It worked.

**Comment by dimejo** [comment] 2020-04-13 12:58
Duplicate of #396.

**Comment by dimejo** [comment] 2020-04-13 13:01
Looks like there's an open PR (#1499) which hasn't been merged yet.

**Comment by rawtaz** [comment] 2020-04-18 10:51
This is know, but wasn't explicitly documented. I added a note in the manual. Thanks!!

**Closed** 2020-04-18 11:01 UTC
Labels: category: documentation
