### ISSUE TITLE
Curious restore failure

### ISSUE THREAD

**Issue by vt-alt** [restic/restic#2647] opened 2020-03-15 22:08 UTC
restic 0.9.6 compiled with go1.14 on linux/amd64

When I backup restic sources dir (after full compilation) and restore afterwards It restores incomplete when restore target is already restored directory. It alternates wrong restore with correct restore then. Full session log:
```
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic version
restic 0.9.6 compiled with go1.14 on linux/amd64
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ export RESTIC_PASSWORD=testic
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test init
created restic repository 83a2f98990 at ../test

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test backup .
repository 83a2f989 opened successfully, password is correct
created new cache in /usr/src/.cache/restic

Files:        4026 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 62.720 MiB

processed 4026 files, 103.242 MiB in 0:01
snapshot 1a48f50c saved
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x; ls -la x
repository 83a2f989 opened successfully, password is correct
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
total 200
drwx------ 12 builder builder   560 Mar 15 22:05 .
drwxr-xr-x 13 builder builder   580 Mar 15 22:05 ..
drwxr-xr-x  4 builder builder    80 Mar 15 22:02 .build
drwxr-xr-x  3 builder builder   100 Nov 22 15:18 .github
-rw-r--r--  1 builder builder    18 Nov 22 15:18 .gitignore
-rw-r--r--  1 builder builder    20 Nov 22 15:18 .hound.yml
-rw-r--r--  1 builder builder  1383 Nov 22 15:18 .travis.yml
-rw-r--r--  2 builder builder 82051 Nov 22 15:18 CHANGELOG.md
-rw-r--r--  2 builder builder  8403 Nov 22 15:18 CONTRIBUTING.md
-rw-r--r--  2 builder builder  1071 Nov 22 15:18 GOVERNANCE.md
-rw-r--r--  2 builder builder  1345 Nov 22 15:18 LICENSE
-rw-r--r--  2 builder builder   164 Nov 22 15:18 Makefile
-rw-r--r--  2 builder builder  6441 Nov 22 15:18 README.rst
-rw-r--r--  2 builder builder     6 Nov 22 15:18 VERSION
-rw-r--r--  2 builder builder   707 Nov 22 15:18 appveyor.yml
-rw-r--r--  2 builder builder 16110 Nov 22 15:18 build.go
drwxr-xr-x 19 builder builder   440 Nov 22 15:18 changelog
drwxr-xr-x  3 builder builder    60 Nov 22 15:18 cmd
drwxr-xr-x  2 builder builder    60 Nov 22 15:18 contrib
drwxr-xr-x  6 builder builder   660 Nov 22 15:18 doc
-rw-r--r--  2 builder builder   520 Nov 22 15:18 doc.go
drwxr-xr-x  2 builder builder   100 Nov 22 15:18 docker
-rw-r--r--  2 builder builder  2115 Nov 22 15:18 go.mod
-rw-r--r--  2 builder builder 24287 Nov 22 15:18 go.sum
drwxr-xr-x  4 builder builder   100 Nov 22 15:18 helpers
drwxr-xr-x 27 builder builder   540 Nov 22 15:18 internal
-rw-r--r--  2 builder builder 16128 Nov 22 15:18 run_integration_tests.go
drwxr-xr-x  9 builder builder   200 Nov 22 15:18 vendor
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x; ls -la x
repository 83a2f989 opened successfully, password is correct
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
total 12
drwx------ 12 builder builder  300 Mar 15 22:05 .
drwxr-xr-x 13 builder builder  580 Mar 15 22:05 ..
drwxr-xr-x  4 builder builder   80 Mar 15 22:02 .build
drwxr-xr-x  3 builder builder  100 Nov 22 15:18 .github
-rw-r--r--  1 builder builder   18 Nov 22 15:18 .gitignore
-rw-r--r--  1 builder builder   20 Nov 22 15:18 .hound.yml
-rw-r--r--  1 builder builder 1383 Nov 22 15:18 .travis.yml
drwxr-xr-x 19 builder builder  380 Nov 22 15:18 changelog
drwxr-xr-x  3 builder builder   60 Nov 22 15:18 cmd
drwxr-xr-x  2 builder builder   40 Nov 22 15:18 contrib
drwxr-xr-x  6 builder builder  120 Nov 22 15:18 doc
drwxr-xr-x  2 builder builder   40 Nov 22 15:18 docker
drwxr-xr-x  4 builder builder   80 Nov 22 15:18 helpers
drwxr-xr-x 27 builder builder  540 Nov 22 15:18 internal
drwxr-xr-x  9 builder builder  180 Nov 22 15:18 vendor
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x; ls -la x
repository 83a2f989 opened successfully, password is correct
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
total 200
drwx------ 12 builder builder   560 Mar 15 22:05 .
drwxr-xr-x 13 builder builder   580 Mar 15 22:05 ..
drwxr-xr-x  4 builder builder    80 Mar 15 22:02 .build
drwxr-xr-x  3 builder builder   100 Nov 22 15:18 .github
-rw-r--r--  1 builder builder    18 Nov 22 15:18 .gitignore
-rw-r--r--  1 builder builder    20 Nov 22 15:18 .hound.yml
-rw-r--r--  1 builder builder  1383 Nov 22 15:18 .travis.yml
-rw-r--r--  2 builder builder 82051 Nov 22 15:18 CHANGELOG.md
-rw-r--r--  2 builder builder  8403 Nov 22 15:18 CONTRIBUTING.md
-rw-r--r--  2 builder builder  1071 Nov 22 15:18 GOVERNANCE.md
-rw-r--r--  2 builder builder  1345 Nov 22 15:18 LICENSE
-rw-r--r--  2 builder builder   164 Nov 22 15:18 Makefile
-rw-r--r--  2 builder builder  6441 Nov 22 15:18 README.rst
-rw-r--r--  2 builder builder     6 Nov 22 15:18 VERSION
-rw-r--r--  2 builder builder   707 Nov 22 15:18 appveyor.yml
-rw-r--r--  2 builder builder 16110 Nov 22 15:18 build.go
drwxr-xr-x 19 builder builder   440 Nov 22 15:18 changelog
drwxr-xr-x  3 builder builder    60 Nov 22 15:18 cmd
drwxr-xr-x  2 builder builder    60 Nov 22 15:18 contrib
drwxr-xr-x  6 builder builder   660 Nov 22 15:18 doc
-rw-r--r--  2 builder builder   520 Nov 22 15:18 doc.go
drwxr-xr-x  2 builder builder   100 Nov 22 15:18 docker
-rw-r--r--  2 builder builder  2115 Nov 22 15:18 go.mod
-rw-r--r--  2 builder builder 24287 Nov 22 15:18 go.sum
drwxr-xr-x  4 builder builder   100 Nov 22 15:18 helpers
drwxr-xr-x 27 builder builder   540 Nov 22 15:18 internal
-rw-r--r--  2 builder builder 16128 Nov 22 15:18 run_integration_tests.go
drwxr-xr-x  9 builder builder   200 Nov 22 15:18 vendor
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x; ls -la x
repository 83a2f989 opened successfully, password is correct
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
total 12
drwx------ 12 builder builder  300 Mar 15 22:05 .
drwxr-xr-x 13 builder builder  580 Mar 15 22:05 ..
drwxr-xr-x  4 builder builder   80 Mar 15 22:02 .build
drwxr-xr-x  3 builder builder  100 Nov 22 15:18 .github
-rw-r--r--  1 builder builder   18 Nov 22 15:18 .gitignore
-rw-r--r--  1 builder builder   20 Nov 22 15:18 .hound.yml
-rw-r--r--  1 builder builder 1383 Nov 22 15:18 .travis.yml
drwxr-xr-x 19 builder builder  380 Nov 22 15:18 changelog
drwxr-xr-x  3 builder builder   60 Nov 22 15:18 cmd
drwxr-xr-x  2 builder builder   40 Nov 22 15:18 contrib
drwxr-xr-x  6 builder builder  120 Nov 22 15:18 doc
drwxr-xr-x  2 builder builder   40 Nov 22 15:18 docker
drwxr-xr-x  4 builder builder   80 Nov 22 15:18 helpers
drwxr-xr-x 27 builder builder  540 Nov 22 15:18 internal
drwxr-xr-x  9 builder builder  180 Nov 22 15:18 vendor
builder@x86_64:~/RPM/BUILD/restic-0.9.6$
```

If I backup sources dir before compilation there is no failures.

**Comment by vt-alt** [comment] 2020-03-15 22:13
There is how it behaves if I add `--verify`:
```
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x --verify 2>&1 | head
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
verifying files in x
finished verifying 4026 files in x
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x --verify 2>&1 | head
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
verifying files in x
ignoring error for /CHANGELOG.md: stat x/CHANGELOG.md: no such file or directory
ignoring error for /CONTRIBUTING.md: stat x/CONTRIBUTING.md: no such file or directory
ignoring error for /GOVERNANCE.md: stat x/GOVERNANCE.md: no such file or directory
ignoring error for /LICENSE: stat x/LICENSE: no such file or directory
ignoring error for /Makefile: stat x/Makefile: no such file or directory
ignoring error for /README.rst: stat x/README.rst: no such file or directory
ignoring error for /VERSION: stat x/VERSION: no such file or directory
ignoring error for /appveyor.yml: stat x/appveyor.yml: no such file or directory
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x --verify 2>&1 | head
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
verifying files in x
finished verifying 4026 files in x
builder@x86_64:~/RPM/BUILD/restic-0.9.6$ restic -r ../test restore latest -t x --verify 2>&1 | head
restoring <Snapshot 1a48f50c of [/usr/src/RPM/BUILD/restic-0.9.6] at 2020-03-15 22:05:16.495930998 +0000 UTC by builder@localhost.localdomain> to x
verifying files in x
ignoring error for /CHANGELOG.md: stat x/CHANGELOG.md: no such file or directory
ignoring error for /CONTRIBUTING.md: stat x/CONTRIBUTING.md: no such file or directory
ignoring error for /GOVERNANCE.md: stat x/GOVERNANCE.md: no such file or directory
ignoring error for /LICENSE: stat x/LICENSE: no such file or directory
ignoring error for /Makefile: stat x/Makefile: no such file or directory
ignoring error for /README.rst: stat x/README.rst: no such file or directory
ignoring error for /VERSION: stat x/VERSION: no such file or directory
ignoring error for /appveyor.yml: stat x/appveyor.yml: no such file or directory
builder@x86_64:~/RPM/BUILD/restic-0.9.6$
```

**Comment by vt-alt** [comment] 2020-03-15 22:21
Note that invalid restore does not produce non-zero `exit` code. (Not even message if `--verify` is not specified.) This is unusual and non-unix style behavior that would make restore failures undetected.

Also why it "ignoring error" if it's verification failure?

**Comment by ifedorenko** [comment] 2020-03-15 23:37
FWIW, I was not able to reproduce the problem on Mac OS. I've used _slightly_ different setup as I didn't want to mess my home directory:

    export RESTIC_REPOSITORY=local:/tmp/restic-test-repo
    export RESTIC_PASSWORD=test123
    export RESTIC_CACHE_DIR=/tmp/restic-restore-cache

but everything else was copy&paste from your report, so I am not sure what's going on.

Please open separate issue for incorrect exit code in case of  restore --verify failure.

**Comment by vt-alt** [comment] 2020-03-16 01:39
It's reproducible with your repo/cache/pass settings. I can upload archive (38M) of the data which would reproduce the problem.

**Comment by vt-alt** [comment] 2020-03-16 01:51
OK, I temporary uploaded there: https://github.com/vt-alt/restic-tmp/raw/master/restic-0.9.6-artifacts.tgz
sha26sum:
```
2829b0d8db0ecec8b6ca0b500f2790c4f7621c3eaaf1d8dfbeca4260f189776c  restic-0.9.6-artifacts.tgz

```
This would reproduce the problem (history):
```
  505  tar xvf restic-0.9.6-artifacts.tgz
  506  cd restic-0.9.6/
  507  export RESTIC_REPOSITORY=local:/tmp/restic-test-repo
  508  export RESTIC_PASSWORD=test123
  509  export RESTIC_CACHE_DIR=/tmp/restic-restore-cache
  510  restic_0.9.6_linux_amd64 init
  511  restic_0.9.6_linux_amd64 backup .
  512  restic_0.9.6_linux_amd64 restore latest -t x
  513  ls -la x
  514  restic_0.9.6_linux_amd64 restore latest -t x
  515  ls -la x
```
`restic_0.9.6_linux_amd64` binary is from your release page.

**Comment by ifedorenko** [comment] 2020-03-16 03:11
The behaviour you observe appears to be triggered by files with multiple links to them (i.e. `.build/src/github.com/restic/restic` directory in your example). Given that incremental restore behaviour is currently undefined, I think the easiest way to avoid "surprises" is to require restore target directory to not exist or be empty.

**Comment by vt-alt** [comment] 2020-03-16 20:50
1. So you not going to fix it.
2. Why not report error message (and error exit code) when restore is failed in such way?

**Comment by ifedorenko** [comment] 2020-03-16 20:55
I propose to fix this by failing restore (with error message and none-zero exit code) if target directory exists and is not empty.

**Comment by vt-alt** [comment] 2020-03-16 20:56
That's definitely would be better than nothing.

**Comment by MichaelEischer** [comment] 2022-05-15 15:51
restore is still problematic but with different symptoms: Existing files are no longer deleted, but may require some changes to allow restore to its work. Especially files that are marked as readonly are not overwritten right now. In addition, #2578 and maybe other problems have to be fixed.

**Comment by MichaelEischer** [comment] 2024-05-25 15:50
Restoring the restic folder multiple times in a row works fine by now (see https://github.com/restic/restic/issues/4757 ). The remaining problems are tracked in https://github.com/restic/restic/issues/4575 .

**Closed by MichaelEischer** 2024-05-25 15:50 UTC
Labels: type: bug, help: wanted, category: restore
