### ISSUE TITLE
Does not compile: github.com/census-instrumentation/opencensus-proto

### ISSUE THREAD

**Issue by Mebus** [restic/restic#2428] opened 2019-09-30 08:24 UTC
Hallo,

I am trying to compile the latest git version and this is the error, I get:

``` 
➜  restic git:(20223558) ✗ go run build.go 
go: contrib.go.opencensus.io/exporter/ocagent@v0.4.3 requires
        github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: invalid pseudo-version: version before v0.1.0 would have negative patch number
➜  restic git:(20223558) ✗ go version
go version go1.13.1 linux/amd64
➜  restic git:(20223558) ✗
```

Mebus

**Comment by djmaze** [comment] 2019-10-11 06:47
Same here on Debian 10 (docker image `golang`).

**Comment by djmaze** [comment] 2019-10-11 06:51
This seems to be a problem with Go 1.13: https://github.com/Azure/go-autorest/issues/449

**Comment by fd0** [comment] 2019-10-11 10:40
Huh, that's odd. I don't get this error, using Go 1.13.1. Can you try running `go clean -cache -modcache`?

**Comment by djmaze** [comment] 2019-10-11 21:47
That does not help. Here is a [Dockerfile for reproduction](https://gist.github.com/djmaze/fcaeda42f47354ce6fb4928a26132e69).

**Comment by dawidd6** [comment] 2019-10-13 09:19
Solution: `go run **-mod=vendor** build.go`

**Comment by gertcuykens** [comment] 2019-10-30 01:15
Real solution: fix dependencies in go.mod by either upgrading ocagent@v0.4.3 or use of go mod replace :P

ref: https://github.com/Azure/go-autorest/issues/449

I was hoping that now that we have go modules `go get -u github.com/restic/restic` would replace `go run -mod=vendor build.go` because it defeats the purpose of modules if every go repository in the ecosystem is going to make its own build.go

**Comment by rawtaz** [comment] 2019-11-18 22:02
There will be attention to the build system in the foreseeable future, so I think this will be fixed then.

**Comment by MichaelEischer** [comment] 2020-10-10 12:21
This has been fixed some time ago on the master branch.

**Closed by MichaelEischer** 2020-10-10 12:21 UTC
