### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by 4001982248998** [restic/restic#3273] opened 2021-02-09 07:12 UTC
Output of `restic version`
--------------------------
``restic 0.11.0 compiled with go1.15.3 on linux/amd64``

How did you run restic exactly?
-------------------------------
```
export AWS_ACCESS_KEY_ID="…"
export AWS_SECRET_ACCESS_KEY="…"
export RESTIC_PASSWORD="…"
export RESTIC_REPOSITORY="s3:https://…"

restic prune
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio S3 Server: ``minio version RELEASE.2021-01-16T02-19-44Z``

Expected behavior
-----------------
Backing up files, and subsequently forgetting and pruning old backups.

Actual behavior
---------------
```
[…]<data/ced7cbda> <data/931aabfd> <data/6a736808> <data/d926aa48> <data/51746a12> <data/244ab8ae> <data/0303a105> <data/1d02d291> <data/b46959c4> <data/11020e7a> <data/b3976f3a> <data/3d79920a> <tree/fb64d8ee> <data/4129b167> <data/05ef3fbb> <data/6ac0faa3> <data/576c0962> <data/8be5f484> <data/d945a160> <data/126b8037> <data/9c642e90> <data/b37b632d> <data/e4699e46> <data/5ceba166> <data/ffea635a> <tree/0f179024> <data/6e7a9f23> <data/1045f19d> <data/f379235c> <tree/adbfab5b> <data/5108aa8e> <data/a506c6f8> <data/17db5155> <data/2fa7f444> <data/17afef28> <data/ac6fceef> <data/85b6deb4> <data/4213366a> <data/0e50c97a> <data/b26a3f8a> <data/edfcc4be> <data/ac4b1f54> <data/adba4bd9> <data/dff3c176> <tree/e4edd525> <data/fb5effc8> <data/fad21018>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

Steps to reproduce the behavior
-------------------------------
Repeating the prune subcommand.

Do you have any idea what may have caused this?
-----------------------------------------------
Could it be that a running forgetting/pruning process was overlapped by a new backup process?

Do you have an idea how to solve the issue?
-------------------------------------------
If the answer to the above question is “yes”, then perhaps a better locking mechanism would help(??).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I like restic's restore method of simply mounting the backups. That's wonderful.

**Comment by MichaelEischer** [comment] 2021-02-11 21:42
Did prune print other warnings before failing with `Data blobs seem to be missing`?

Did you notice any errors reported in prior restic runs or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running? Is this the first failing `prune` run? Do you have logs of the `backup` and `prune` run before the failing one? Did restic report any errors there?

How often do you run `backup`, `check` and/or `prune`?

Is the repository used by multiple hosts or just a single host?
Do you use the `unlock` command or is it called automatically from your backup scripts?

Please run `check` to get more details on the current state of the repository. If downloading all data from the repository isn't a problem, then please run `check --read-data` instead to perform a full integrity check.

Did you run any commands previously to try to repair the damage? I'm especially interested in whether you ran `rebuild—index`? If the answer is no, then please create a backup of the repository index (the `index/` folder in the repository). Or at least do **NOT** run `rebuild index` for now.

It would be helpful to know which snapshots are missing blobs: Please run `restic find --blob ced7cbda 931aabfd 6a736808 [...]` (with the ids of the blobs reported as missing) to find the affected snapshots.

It would be interesting to know whether the damaged snapshot(s) is/are for example the latest snapshot or maybe some random older one(s). Is there any correlation between prune runs and the creation time of the damaged snapshots? Did you run prune since these snapshots were created?
If you still have the log files: Did any of these backup runs report errors?

**Comment by 4001982248998** [comment] 2021-02-12 07:12
Wow, that is quite a lot of debugging guidance. Thanks a lot! I am new to the project and still learning it. I will try to gather more information and report back. It will take a while, as some commands take hours, but I will try to find smaller repositories that show symptoms.

**Comment by 4001982248998** [comment] 2021-03-12 13:06
Hello, thank you for your patience.

I have abstained from forgetting old backups for a while and left the job to just daily backing up files. Just daily ``backup``s, no ``check``s, no ``forget``s or ``prune``s, from a single host and without manual ``unlock``.

Today, I have issued a ``restic check`` for the first time, and it alerted me about errors.

Following your hints, I ran ``check`` and a subsequent ``check --read-data``. Also, I ran ``find --blob …`` for one of the missing blobs. It did output so many lines that I did not search for another. But I asked for the list of ``snapshots``.

I have attached the output gathered by typescript. Honestly, I do not know how to proceed. Is that of any value to the case?
[restic-debug.txt](https://github.com/restic/restic/files/6130190/restic-debug.txt)

**Comment by MichaelEischer** [comment] 2021-03-12 17:19
@4001982248998 The log output looks rather concerning. It shows that the repository is damaged in some way which might prevent you from restoring (parts of) the latest snapshots.

```
pack ffe3fdac: not referenced in any index
pack f9be1693: not referenced in any index
pack f953dbcd: not referenced in any index
pack fd155061: not referenced in any index
pack ff05dff4: not referenced in any index
pack fc7aa2d9: not referenced in any index
```
That looks like a lot of pack files whose name starts with `f` are missing from the index. The only way I can think of that could cause this is that you've run `rebuild-index` and the minio server then only returned an incomplete pack file listing. Which makes me wonder whether this could be the same problem as in #3317? Please use restic 0.12.0 to run `rebuild-index` and make sure that is reports something like `adding pack file to index fff[...]` (a pack file name that starts with 3 `f`s or more!). If necessary restart the command a few times.

Have you run `rebuild-index` before?

```
error for tree b58c2fc7:
  id b58c2fc7c7defc720061799be737771d730256eeacf66c8151e7ea1096eef8d4 not found in repository
```

That is a new error that was _not_ present when you posted the initial error reported by `prune`. It's probably caused by the thousand pack files missing from the index.

**Comment by 4001982248998** [comment] 2021-03-17 08:20
I think I removed every backup snapshot and restarted the backup schedule from scratch, without regular forgetting or pruning.

As per your advice, thank you, I have upgraded restic and let it rebuild the index, which seems to be successful. A typescript log is attached.
[rebuild-index.txt](https://github.com/restic/restic/files/6154750/rebuild-index.txt)

**Comment by MichaelEischer** [comment] 2021-03-20 19:39
The fact that `rebuild-index` has been able to fix the repository, suggests that this might be the same problem as in #3317 where minio returned an incomplete file listing (could you test whether e.g. the minio client could end up with an incomplete file list from time to time?). With restic 0.12.0 that should be less of a concern as `prune` won't leave the repository behind with an incomplete index in that case.

Is there something left to do here or can we close this issue?

**Comment by seqizz** [comment] 2021-03-26 09:17
Ooh I need to check the issues a bit more often. Today I saw the same thing: prune failed with `id 6ff43febc96837da611a7dc5fe53f2786232da25afb680b8bb0be65543590eb3 not found in repository` and rebuild-index succeeded afterwards. That was something confusing to see. Thanks for explanation @MichaelEischer.

IMHO the issue can be closed, since the theory seems to be correct, but I have a small question: Could rebuild-index be harmful? You've advised to not to run it above, I have automation already in place which tries rebuild-index in case of a prune failure (and that was one of the rare occasions that it actually helped). But I put it there because I was thinking it won't cause a repository state to get worse in any way.

**Comment by 4001982248998** [comment] 2021-03-26 11:20
I think it can be closed. Thank you!

**Comment by MichaelEischer** [comment] 2021-03-27 12:22
@seqizz Running rebuild-index can in some cases with missing pack files cause `restore` to fail completely when trying to restore those files, see #2334. It's sort of possible to work around this by either excluding the affected files during restore or using #2876.

**Closed by MichaelEischer** 2021-03-27 12:22 UTC
Labels: state: need feedback

**Comment by viewpointsa** [comment] 2022-04-05 07:17
My experiment with bad repository ( restic_0.9.6_linux_386, Swcalway S3 compatible ) :
```
ERROR : Restic prune failed prune cmd restic-prune.sh Load(<data/62d775fc53>, 591, 4466402) returned error, retrying after 504.93271ms: We encountered an internal error. Please try again.
Load(<data/62d775fc53>, 591, 4466402) returned error, retrying after 1.069808567s: We encountered an internal error. Please try again.
[...]
Load(<data/62d775fc53>, 591, 4466402) returned error, retrying after 18.821158392s: We encountered an internal error. Please try again.
pack file cannot be listed 62d775fc537a88b715444ac726b5d6b888bb9459676e0f3ebb221b79b8ec86d4: We encountered an internal error. Please try again.
using temporary cache in /home/restic/cache/restic-check-cache-325510339
created new cache in /home/restic/cache/restic-check-cache-325510339
create exclusive lock for repository
load indexes
```
Move to another bucket, and try to check : KO
```
[15:28:32]root@neuron:/etc/scripts# ./myrestic check
using temporary cache in /home/restic/cache/restic-check-cache-110750638
repository 1efe5395 opened successfully, password is correct
created new cache in /home/restic/cache/restic-check-cache-110750638
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
Load(<data/59cd4236c2>, 0, 0) returned error, retrying after 396.557122ms: Copy: read tcp 192.168.10.2:45670->51.159.62.7:443: read: connection reset by peer
Load(<data/f5004c0327>, 0, 0) returned error, retrying after 398.541282ms: Copy: read tcp 192.168.10.2:45667->51.159.62.7:443: read: connection reset by peer
Load(<data/f6da491550>, 0, 0) returned error, retrying after 626.286518ms: Copy: read tcp 192.168.10.2:45666->51.159.62.7:443: read: connection reset by peer
Load(<data/e6a8221a8c>, 0, 0) returned error, retrying after 389.253811ms: Copy: read tcp 192.168.10.2:45696->51.159.62.7:443: read: connection reset by peer
Load(<data/2282b97f27>, 0, 0) returned error, retrying after 423.976982ms: Copy: read tcp 192.168.10.2:45775->51.159.62.7:443: read: connection reset by peer
error for tree 90db4f61:
  tree 90db4f61: file "FileName.exe" blob 57 size could not be found
  tree 90db4f61: file "FileName.6.3.2_x86.exe" blob 58 size could not be found
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 51 size could not be found
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 52 size could not be found
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 53 size could not be found
  tree 90db4f61, blob 867fea33: not found in index
  tree 90db4f61, blob ea200ed9: not found in index
  tree 90db4f61, blob 3b95d010: not found in index
  tree 90db4f61, blob 992024a2: not found in index
  tree 90db4f61, blob 414ec451: not found in index
error for tree 3d31592c:
  tree 3d31592c: file "FileName.6.3.2_x86.exe" blob 57 size could not be found
  tree 3d31592c: file "FileName.6.3.2_x86.exe" blob 58 size could not be found
  tree 3d31592c, blob 867fea33: not found in index
  tree 3d31592c, blob ea200ed9: not found in index
Fatal: repository contains errors
```
Find corresponding file: KO
```
[15:47:10]root@neuron:/etc/scripts# ./myrestic find --show-pack-id --tree 3d31592c
repository 1efe5395 opened successfully, password is correct
Found tree 3d31592c23c66196f67664a03417241c263d63d6c3e8b13eb07514fe3c060140
 ... path /path/to/file
 ... in snapshot 0aec03a4 (2022-03-14 04:10:03)
Found tree 3d31592c23c66196f67664a03417241c263d63d6c3e8b13eb07514fe3c060140
 ... path /path/to/file
 ... in snapshot 45348b88 (2022-03-28 04:10:02)
Note: cannot find pack for object '3d31592c', unable to parse ID: invalid length for 
```
Try prune: KO
```
[09:49:50]root@neuron:/etc/scripts# ./myrestic prune
repository 1efe5395 opened successfully, password is correct
counting files in repo
building new index for repo
[4:16:01] 100.00%  75722 / 75722 packs
repository contains 75722 packs (619948 blobs) with 358.701 GiB
processed 619948 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 450 snapshots
[2:38] 100.00%  450 / 450 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

Install lasted version from online binaries 0.13 : KO
```
[09:38:11]root@neuron:/etc/scripts# ./myrestic version
restic 0.13.0 compiled with go1.18 on linux/386
[09:38:17]root@neuron:/etc/scripts# ./myrestic check
using temporary cache in /home/restic/cache/restic-check-cache-3201120487
repository 1efe5395 opened successfully, password is correct
created new cache in /home/restic/cache/restic-check-cache-3201120487
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 90db4f61:napshots...
  tree 90db4f61: file "FileName.6.3.2_x86.exe" blob 867fea334966e7b6843506bc9768ae8b384c056254422e0f0ab34887b17d6d2a not found in index
  tree 90db4f61: file "FileName.6.3.2_x86.exe" blob ea200ed9a0dbdedf490f70a4c94a0fb515c499cd1cab30fbd1ca9b2f62852489 not found in index
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 3b95d01033838335f5d6a80e77aa81c9e6940f65613365cfbbec964a70dae52f not found in index
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 992024a2ffbda675c1a1ebcfff7eafb68d1681c7ceb72e6e7223f49dfeb75bae not found in index
  tree 90db4f61: file "FileName.7.3.11_x64.exe" blob 414ec45142eb56865c3b1367ebbde0d14498b6c6a9b9e51317236c5f8c0d32b2 not found in index
error for tree 3d31592c:
  tree 3d31592c: file "FileName.6.3.2_x86.exe" blob 867fea334966e7b6843506bc9768ae8b384c056254422e0f0ab34887b17d6d2a not found in index
  tree 3d31592c: file "FileName.6.3.2_x86.exe" blob ea200ed9a0dbdedf490f70a4c94a0fb515c499cd1cab30fbd1ca9b2f62852489 not found in index
[6:52] 100.00%  450 / 450 snapshots...
Fatal: repository contains errors
```
Rebuild index with new version : KO
```
[10:51:19]root@neuron:/etc/scripts# ./myrestic rebuild-index
repository 1efe5395 opened successfully, password is correct
loading indexes...
getting pack files to read...
rebuilding index
[0:28] 100.00%  75722 / 75722 packs processed...
deleting obsolete index files
[0:10] 100.00%  26 / 26 files deleted...
done
```
Backup with force : OK 
```
[14:08:43]root@neuron:/etc/scripts# ./myrestic backup --force /mnt/path
open repository
repository 1efe5395 opened successfully, password is correct
lock repository
load index files
no parent snapshot found, will read all files
start scan on [/mnt/path]
start backup on [/mnt/path]
scan finished in 436.109s: 60845 files, 278.121 GiB
[26:19] 29.87%  26964 files 83.083 GiB, total 60845 files 278.121 GiB, 0 errors ETA 1:01:48
[26:19] 29.87%  26964 files 83.084 GiB, total 60845 files 278.121 GiB, 0 errors ETA 1:01:48
[28:40] 30.42%  27206 files 84.606 GiB, total 60845 files 278.121 GiB, 0 errors ETA 1:05:34
[28:40] 30.42%  27206 files 84.607 GiB, total 60845 files 278.121 GiB, 0 errors ETA 1:05:34

Files:       60846 new,     0 changed,     0 unmodified
Dirs:        12173 new,     0 changed,     0 unmodified
Data Blobs:   1014 new
Tree Blobs:  11920 new
Added to the repo: 621.886 MiB

processed 60846 files, 278.151 GiB in 1:30:50
snapshot 0aa5a12f saved
```
Then check and prune again correct my problem. I hope this help other people
