### ISSUE TITLE
lstat error on excluded filesystem

### ISSUE THREAD

**Issue by pille** [restic/restic#3424] opened 2021-06-11 11:59 UTC
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.5 on linux/amd64

How did you run restic exactly?
-------------------------------
```
/usr/bin/restic backup --verbose --one-file-system /
RESTIC_REPOSITORY="s3:http://s3-storage/restic"

# mount |fgrep proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
```
What backend/server/service did you use to store the repository?
----------------------------------------------------------------
minIO

Expected behavior
-----------------

no error messages, clean exit status
restic should not access files outside backup sources `(--one-file-system)`

Actual behavior
---------------
errors:
`error: lstat /proc/5994: no such file or directory`
backup was successful, but indicated an error that should not have happened.

Steps to reproduce the behavior
-------------------------------
see above

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by greatroar** [comment] 2021-06-12 09:34
Looks like a duplicate of #3366.

**Comment by MichaelEischer** [comment] 2021-06-13 12:26
Closing as duplicate of #3366.

**Closed by MichaelEischer** 2021-06-13 12:26 UTC
