### ISSUE TITLE
Debian packaging (repository)

### ISSUE THREAD

**Issue by xor-gate** [restic/restic#355] opened 2015-11-22 21:25 UTC
Hi all,

I started to create a debian package of restic which builds and runs fine and is installable. In some weeks I will hopefully setup a debian wheezy repository. Currently I have my draft in my master branch, look at the `debian` folder and the `Makefile` deb target:
https://github.com/xor-gate/restic

The tests are disabled because I could not get them work. 
Also when using `build.go` and /tmp is mounted as noexec it fails in a painfull way :_).

I'm no real debian developer but have many experience on linux and unix systems. So it is possible it doesn't meet the full debian packaging guidelines (yet).

**Comment by fd0** [comment] 2015-11-22 21:27
Thanks for the effort. You can set the temporary directory via the environment variable `TMPDIR`.

**Comment by xor-gate** [comment] 2015-11-22 21:30
I will look into it and when it is acceptable I will document, squash and create a pull request.

**Comment by mika** [comment] 2016-01-22 16:36
https://github.com/xor-gate/restic does no longer exist, is anyone (still) working on the Debian packaging?

**Comment by Mebus** [comment] 2016-01-22 16:54
A Debian repo for this would be great.

Mebus

**Comment by xor-gate** [comment] 2016-01-22 20:52
@mika, i had screwed up the repository. Now it is "polished" and reproducable.

https://github.com/xor-gate/restic/tree/debian
https://github.com/xor-gate/restic/releases/tag/v0.0.1-debian

Please use the makefile in a container or VM. No guarantees :-)

**Comment by xor-gate** [comment] 2016-01-31 17:46
If @fd0 is interessted I can clean it up a bit and create a pull request of this ? Actual signing and setup of a repository can be done with e.g. http://bintray.com

**Comment by sjoerd-ccu** [comment] 2016-02-01 08:54
@xor-gate Do you intend to push/maintain it into debian? Assuming my first test with restic work out nicely I'd be happy to sponsor an upload :)

**Comment by xor-gate** [comment] 2016-02-01 10:24
@sjoerd-ccu i'm not a official debian developer and maintaining a package can be time consuming. My current debian packaging will need some love to actual make it into the debian packaging system.

**Comment by sjoerd-ccu** [comment] 2016-02-01 10:42
I'm a Debian Developer, hence i can sponsor an upload and review your packaging. But yes the real choice you need to make is whether you want to maintain it properly :)

**Comment by fd0** [comment] 2016-02-01 12:03
I was a Debian Developer myself once, but did not have the time any more.

I'd very much appreciate someone stepping up and maintaining a proper package, either inside of Debian or outside. I can also host a repository for packages outside of Debian (e.g. on GitHub), but this would need someone else to manage the packaging. :)

If there is interest, we can e.g. also add a repository for group-maintaining, e.g. at github.com/restic/pkg-debian or so.

**Comment by xor-gate** [comment] 2016-02-01 12:50
I would like to maintain the package (outside of debian) but for having it upstream in Debian it would be much more effort and community communication. Then I would setup it under bintray which just works out of the box. Keep in mind that we maybe want a restic/packaging repository so also archlinux and other distros could benefit. Maybe also RPM. I had a look at http://packager.io but the packages it emits are bloated.

**Comment by jmallach** [comment] 2016-02-01 14:46
Hi there,

As another Debian Developer with an eye put on restic, I can only urge you to reconsider your view of maintaining restic outside of Debian is much effort. It's basically the same effort, or in my experiece, actually less effort.

Debian would give you visibility, mirrors, continous testing of upgrades, build reproducibilty, a gateway for inclusion in Ubuntu and so many other things I cannot list here.

You already have a Debian developer offering sponsorship. Here's another one.

I'd be glad to see your packaging effort in Debian officially. If it's not you, it's quite easy someone else will end up doing it sooner or later.

**Comment by fd0** [comment] 2016-02-01 14:58
So, as far as I can see we have enough people who are interested in maintaining this for Debian. You can have a repository in the restic organisation if you like, e.g. github.com/restic/pkg-Debian, and have access to that repo. Are you interested in group-maintaining?

From my point of view (main author) I'd be awesome to have a group of people maintaining the packages for the different distributions, I'm glad to help :)

**Comment by xor-gate** [comment] 2016-02-02 21:09
@fd0 I seperate repo would be handy. And I would like to kickstart it and with multiple people involved it would be nice as most people do this in their spare time (me).

**Comment by fd0** [comment] 2016-02-02 22:03
@xor-gate great, I've created https://github.com/restic/pkg-Debian and enabled push access for you. When you have someone else who should have write access, please let me know.

**Comment by mika** [comment] 2016-02-03 15:14
@xor-gate thanks for sharing your work! Sadly your approach with the "go get" inside the build process (https://github.com/xor-gate/restic/blob/debian/Makefile) isn't what's considered best practices for Debian packaging and has no chance in resulting in an *official* Debian package (as in "within the Debian project"), especially since the official build infrastructure doesn't even allow network access during build time. Of course this shouldn't prevent anyone from providing Debian packages outside of Debian, so jftr && jfyi. :)

A few days ago I started to look at the Debian packaging of restic and this is what I have in my shell history what should be relevant as a starting point (disclaimer: that might not be 100% correct nor complete, consider it as a starting point where I just left off):

````
 dh-make-golang github.com/restic/restic
 dh-make-golang github.com/jessevdk/go-flags-dev
 dh-make-golang github.com/juju/errors-dev
 dh-make-golang github.com/restic/chunker
 dh-make-golang github.com/juju/errors
 dh-make-golang github.com/jessevdk/go-flags
 dh-make-golang github.com/minio/minio-go
 dh-make-golang github.com/juju/testing
 dh-make-golang gopkg/check.v1 golang-gopkg-check.v1-dev 
 dh-make-golang github.com/juju/loggo
 dh-make-golang github.com/juju/utils 
````

JFTR: I'm a Debian Developer as well and would be happy to also sponsor any uploads (but I currently lack time to take care of the packaging and maintaining the packages properly myself).

**Comment by xor-gate** [comment] 2016-02-03 15:16
@mike Yes I know, it was just a dirty fix to get it working. Can you point me to instructions how golang tags/commits could be used in the debian golang packaging process?

**Comment by mika** [comment] 2016-02-03 15:19
@xor-gate: check out dh-make-golang, it's supposed to make most of the work for you (PS: I'm mika, not mike, JFYI :))

**Comment by digitalcrab** [comment] 2016-02-17 11:56
Hello, guys. Any success? ;) 
Hope this can help you a little bit
https://github.com/laher/goxc

**Comment by schorsch3000** [comment] 2016-09-27 15:58
Any news in here?
Is there a reliable source for a debian packe or is building your own the way to go?

**Comment by jannic** [comment] 2016-11-29 09:03
Just to mention it here: An ITP has been filed to the debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846176

**Comment by xor-gate** [comment] 2016-11-29 13:30
Hi guys, sorry for my non-responsiveness as I'm the author if this "issue".  I have not been using restic for a long time now (fairly because [borgbackup](https://github.com/borgbackup/borgbackup) is currently more stable, and has a same set of features). Therefor I have not invested time and effort to continue debian packaging. I was waiting to have some sort of stable restic release (which I use myself) to finish debian packaging and creating a repository.

If people don't want to maintain a debian repository (with own servers) it could be considered to use [Bintray](https://bintray.com/) for repo/bandwidth hosting.

Again, I'm sorry for the silence on this topic and hopefully you understand.

**Comment by fd0** [comment] 2016-11-29 13:58
Thanks for letting us know. I'm glad you found a backup solution that works for you :)

**Comment by legrostdg** [comment] 2016-11-29 18:10
Woops, I had not seen this bug (and the packaging repository), I've started this from scratch, and sent an ITP yesterday (which resulted in a link to this bug :-)). I can share the result soon, and would be totally open to group maintenance.

**Comment by legrostdg** [comment] 2016-12-01 09:40
I've packaged the two missing dependencies (golang-github-elithrar-simple-scrypt and golang-github-restic-chunker) and I'm looking for sponsors to get these in the archive before I can share the restic package, preferably in a working state :-).

**Comment by legrostdg** [comment] 2016-12-01 09:41
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846346
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846347

**Comment by fd0** [comment] 2016-12-01 20:25
Thanks @mika for sponsoring the packages :)

**Comment by legrostdg** [comment] 2016-12-05 21:37
Update: golang-github-minio-minio-go seems too old for restic. At least the build fails with:

    restic/backend/s3/s3.go:39: assignment count mismatch: 2 = 1

I'm trying to get 0.2.0 in Debian: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846969 (I've also contacted the last uploader privately)

**Comment by jannic** [comment] 2016-12-05 22:18
@legrostdg: Alternatively, you could try reverting 06b23edb for the debian package. Not nice, but may be a workaround if updating the minio package takes too long.
(See  https://github.com/minio/minio-go/commit/56218997d01f6c8d77b91154079b57ccf8cf581a for the API change in minio. AFAIKT they only changed the way the result is reported back to the caller. But I didn't check if there are other incompatibilities between minio 2.0.1 and 2.0.2.)

**Comment by legrostdg** [comment] 2016-12-06 00:09
I guess it won't be long to update minio, if I have no answer from the last uploader, I'll update the package myself and ask for a sponsor in the pkg-go team. What a weird numbering scheme, though! 2.0.1 not API compatible to 2.0.2... @jannic: Thanks for the suggestion!

**Comment by fd0** [comment] 2016-12-06 07:19
What version number will the restic binary from the Debian package report? When compiled from source, the vendored dependencies are use, so the version number (which includes the Git commit and/or the contents of the `VERSION`  file) exactly specifies which code has been compiled, including dependencies. How do we handle that for the Debian package? Use a suffix like `0.3.0-debian1`?

I think it's important to know, because once restic is in Debian, users will report bugs so we need to know which code they used...

**Comment by mika** [comment] 2016-12-06 07:28
@legrostdg I'm happy to sponsor the updated package, though never received a private mail about it if that was about me, ping me with the according URLs and I'd be happy to take care

**Comment by legrostdg** [comment] 2016-12-06 16:05
@mika: no it's wasn't you I sent the email :-). Anyway the updated version is available there:
https://mentors.debian.net/debian/pool/main/g/golang-github-minio-minio-go/golang-github-minio-minio-go_2.0.2+dfsg-1.dsc

@fd0: the debian suffix is usually `-$debian_version`, so for example `0.3.0-1`. The users should report bugs to the debian bts, which may be forwarded there (or not). Of course, a dependency of restic with a different version in debian that the ones in vendors may break the build, but it's the only way to get a DFSG compliant package... The package source will of course be available in a publicly accessible VCS.

**Comment by jmallach** [comment] 2016-12-07 09:58
@legrostdg, minio/minio-go is used by gitlab-ci-multi-runner already in the archive. Can you test build gitlab-ci-multi-runner with minio-go 2.0.2 to see if the build does not break with the new version?

**Comment by jmallach** [comment] 2016-12-07 10:18
Please also note the stretch freeze is looming on us, and if restic wants to have a chance of being in stretch it should be uploaded ASAP, as it'll have to pass the ftp-master manual checks being a new package, and then survive the 10 day transition period before it can land in Debian testing. The window closes on the 5th. If it's not there by then, it's out.

https://wiki.debian.org/DebianStretch

**Comment by fd0** [comment] 2016-12-07 10:18
Thanks for the reminder. @legrostdg let me know if I can do anything to help here :)

**Comment by legrostdg** [comment] 2016-12-07 12:44
@jmallach gitlab-ci-multi-runner builds with minio-go 2.0.2+dfsg-1 (the one on mentors). I can send the .build 
I'm aware of the freeze, I'll do as fast as I can :-).

@fd0 for now, I'm not sure you could do much right now. It would help to only have the last releases (and not arbitrary git commits) of the dependencies in vendor/.

**Comment by fd0** [comment] 2016-12-07 16:43
@legrostdg Could you please ensure that `golang-github-elithrar-simple-scrypt-dev` includes my fix in https://github.com/elithrar/simple-scrypt/commit/2325946f714c95de4a6088202c402fbdfa64163b? otherwise, restic is broken on 386 (see #676).

**Comment by legrostdg** [comment] 2016-12-07 16:58
the golang-github-elithrar-simple-scrypt-dev now in debian sid is based on this (last) commit.

**Comment by fd0** [comment] 2016-12-07 18:01
Ok, great to know.

**Comment by jmallach** [comment] 2016-12-14 09:53
@legrostdg, has your package been sponsored already?

**Comment by fd0** [comment] 2016-12-14 10:00
FYI: I've released restic 0.3.1 yesterday.

**Comment by legrostdg** [comment] 2016-12-14 12:11
@jmallach I'm still waiting for golang-github-minio-minio-go-dev to be sponsored, but it should be done soon.

@fd0 I've imported restic 0.3.1

Right now, the build (with `go run build.go` and `go run build.go --test`) goes well, but the package creation fails at the end. I've asked pkg-go-maintainers about this, and I'm waiting for an anwser. It is probably an issue with dh-golang...

    dpkg-buildpackage
    -----------------
    
    dpkg-buildpackage: info: source package restic
    dpkg-buildpackage: info: source version 0.3.1-1
    dpkg-buildpackage: info: source distribution UNRELEASED
    dpkg-buildpackage: info: source changed by Félix Sipma <felix+debian@gueux.org>
     dpkg-source --before-build restic-0.3.1
    dpkg-buildpackage: info: host architecture amd64
     fakeroot debian/rules clean
    dh clean --buildsystem=golang --with=golang
       dh_testdir -O--buildsystem=golang
       dh_auto_clean -O--buildsystem=golang
       dh_autoreconf_clean -O--buildsystem=golang
       dh_clean -O--buildsystem=golang
     dpkg-source -b restic-0.3.1
    dpkg-source: info: using source format '3.0 (quilt)'
    dpkg-source: info: building restic using existing ./restic_0.3.1.orig.tar.gz
    dpkg-source: info: building restic in restic_0.3.1-1.debian.tar.xz
    dpkg-source: info: building restic in restic_0.3.1-1.dsc
     debian/rules build
    dh build --buildsystem=golang --with=golang
       dh_testdir -O--buildsystem=golang
       dh_update_autotools_config -O--buildsystem=golang
       dh_autoreconf -O--buildsystem=golang
       dh_auto_configure -O--buildsystem=golang
       debian/rules override_dh_auto_build
    make[1]: Entering directory '/<<PKGBUILDDIR>>'
    go run build.go
    make[1]: Leaving directory '/<<PKGBUILDDIR>>'
       debian/rules override_dh_auto_test
    make[1]: Entering directory '/<<PKGBUILDDIR>>'
    go run build.go --test
    ok  	restic	14.374s
    ok  	restic/archiver	87.269s
    ok  	restic/backend	2.500s
    ok  	restic/backend/local	1.824s
    ok  	restic/backend/mem	1.956s
    ok  	restic/backend/rest	0.033s
    ok  	restic/backend/s3	0.018s
    ok  	restic/backend/sftp	0.004s
    ok  	restic/backend/test	2.072s
    ok  	restic/checker	8.874s
    ok  	restic/crypto	0.814s
    ?   	restic/debug	[no test files]
    ?   	restic/errors	[no test files]
    ok  	restic/filter	0.529s
    ?   	restic/fs	[no test files]
    ok  	restic/fuse	1.423s
    ok  	restic/index	72.766s
    ?   	restic/list	[no test files]
    ok  	restic/location	0.005s
    ?   	restic/mock	[no test files]
    ok  	restic/pack	0.013s
    ok  	restic/pipe	0.014s
    ok  	restic/repository	6.332s
    ?   	restic/test	[no test files]
    ok  	restic/walk	1.685s
    ok  	restic/worker	0.003s
    ok  	cmds/restic	56.811s
    ok  	cmds/restic-server	0.026s
    make[1]: Leaving directory '/<<PKGBUILDDIR>>'
     fakeroot debian/rules binary
    dh binary --buildsystem=golang --with=golang
       dh_testroot -O--buildsystem=golang
       dh_prep -O--buildsystem=golang
       dh_auto_install -O--buildsystem=golang
    	mkdir -p /<<PKGBUILDDIR>>/debian/restic/usr/share/gocode/src/github.com/restic/restic
    	cp -r -T src/github.com/restic/restic /<<PKGBUILDDIR>>/debian/restic/usr/share/gocode/src/github.com/restic/restic
       dh_install -O--buildsystem=golang
       dh_installdocs -O--buildsystem=golang
       dh_installchangelogs -O--buildsystem=golang
       dh_perl -O--buildsystem=golang
       dh_link -O--buildsystem=golang
       dh_strip_nondeterminism -O--buildsystem=golang
       dh_compress -O--buildsystem=golang
       dh_fixperms -O--buildsystem=golang
       dh_strip -O--buildsystem=golang
       dh_makeshlibs -O--buildsystem=golang
       dh_shlibdeps -O--buildsystem=golang
       dh_installdeb -O--buildsystem=golang
       dh_golang -O--buildsystem=golang
    can't load package: package restic: cannot find package "restic" in any of:
    	/usr/lib/go-1.7/src/restic (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic (from $GOPATH)
    can't load package: package restic/archiver: cannot find package "restic/archiver" in any of:
    	/usr/lib/go-1.7/src/restic/archiver (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/archiver (from $GOPATH)
    can't load package: package restic/backend: cannot find package "restic/backend" in any of:
    	/usr/lib/go-1.7/src/restic/backend (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend (from $GOPATH)
    can't load package: package restic/backend/local: cannot find package "restic/backend/local" in any of:
    	/usr/lib/go-1.7/src/restic/backend/local (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend/local (from $GOPATH)
    can't load package: package restic/backend/mem: cannot find package "restic/backend/mem" in any of:
    	/usr/lib/go-1.7/src/restic/backend/mem (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend/mem (from $GOPATH)
    can't load package: package restic/backend/rest: cannot find package "restic/backend/rest" in any of:
    	/usr/lib/go-1.7/src/restic/backend/rest (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend/rest (from $GOPATH)
    can't load package: package restic/backend/s3: cannot find package "restic/backend/s3" in any of:
    	/usr/lib/go-1.7/src/restic/backend/s3 (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend/s3 (from $GOPATH)
    can't load package: package restic/backend/sftp: cannot find package "restic/backend/sftp" in any of:
    	/usr/lib/go-1.7/src/restic/backend/sftp (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/backend/sftp (from $GOPATH)
    can't load package: package restic/checker: cannot find package "restic/checker" in any of:
    	/usr/lib/go-1.7/src/restic/checker (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/checker (from $GOPATH)
    can't load package: package restic/crypto: cannot find package "restic/crypto" in any of:
    	/usr/lib/go-1.7/src/restic/crypto (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/crypto (from $GOPATH)
    can't load package: package restic/debug: cannot find package "restic/debug" in any of:
    	/usr/lib/go-1.7/src/restic/debug (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/debug (from $GOPATH)
    can't load package: package restic/errors: cannot find package "restic/errors" in any of:
    	/usr/lib/go-1.7/src/restic/errors (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/errors (from $GOPATH)
    can't load package: package restic/filter: cannot find package "restic/filter" in any of:
    	/usr/lib/go-1.7/src/restic/filter (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/filter (from $GOPATH)
    can't load package: package restic/fs: cannot find package "restic/fs" in any of:
    	/usr/lib/go-1.7/src/restic/fs (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/fs (from $GOPATH)
    can't load package: package restic/fuse: cannot find package "restic/fuse" in any of:
    	/usr/lib/go-1.7/src/restic/fuse (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/fuse (from $GOPATH)
    can't load package: package restic/index: cannot find package "restic/index" in any of:
    	/usr/lib/go-1.7/src/restic/index (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/index (from $GOPATH)
    can't load package: package restic/list: cannot find package "restic/list" in any of:
    	/usr/lib/go-1.7/src/restic/list (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/list (from $GOPATH)
    can't load package: package restic/location: cannot find package "restic/location" in any of:
    	/usr/lib/go-1.7/src/restic/location (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/location (from $GOPATH)
    can't load package: package restic/pack: cannot find package "restic/pack" in any of:
    	/usr/lib/go-1.7/src/restic/pack (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/pack (from $GOPATH)
    can't load package: package restic/pipe: cannot find package "restic/pipe" in any of:
    	/usr/lib/go-1.7/src/restic/pipe (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/pipe (from $GOPATH)
    can't load package: package restic/repository: cannot find package "restic/repository" in any of:
    	/usr/lib/go-1.7/src/restic/repository (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/repository (from $GOPATH)
    can't load package: package restic/test: cannot find package "restic/test" in any of:
    	/usr/lib/go-1.7/src/restic/test (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/test (from $GOPATH)
    can't load package: package restic/walk: cannot find package "restic/walk" in any of:
    	/usr/lib/go-1.7/src/restic/walk (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/walk (from $GOPATH)
    can't load package: package restic/worker: cannot find package "restic/worker" in any of:
    	/usr/lib/go-1.7/src/restic/worker (from $GOROOT)
    	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/restic/worker (from $GOPATH)
    go list of dependencies failed with code 31488,  at /usr/bin/dh_golang line 55.
    debian/rules:8: recipe for target 'binary' failed
    make: *** [binary] Error 123
    dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
    --------------------------------------------------------------------------------

**Comment by legrostdg** [comment] 2016-12-14 12:13
Link to my messages to pkg-go-maintainers: https://lists.alioth.debian.org/pipermail/pkg-go-maintainers/Week-of-Mon-20161212/009670.html

**Comment by zcalusic** [comment] 2016-12-14 12:19
@legrostdg this is #660 in effect. build.go uses tricks, mangles $GOPATH etc... and dh-golang probably expects a well laid out Go source to do its magic properly. Unfortunately, #660 was rejected...

**Comment by fd0** [comment] 2016-12-14 12:55
The `build.go` program was meant for end-users, not necessarily for package maintainers. It is entirely possible to use the `go` tool for it:
```
$ GOPATH=$PWD:$GOPATH go build -ldflags "-s -w -X \"main.compiledAt=$(date '+%Y-%m-%d %H:%M:%S')\" -X \"main.version=$(cat VERSION)-debian1\"" -o restic cmds/restic
```

This sets the version fields in the binary accordingly. When the vendored dependencies should be used, the `GOPATH` given to `go build` must be slightly modified:
```
$ GOPATH=$PWD:$PWD/vendor go build -ldflags "-s -w -X \"main.compiledAt=$(date '+%Y-%m-%d %H:%M:%S')\" -X \"main.version=$(cat VERSION)-debian1\"" -o restic cmds/restic
```

This is basically what the `build.go` does.

The `version` command works then:
```
$ ./restic version
restic 0.3.1-debian1
compiled at 2016-12-14 18:53:38 with go1.7 on linux/amd64
```

**Comment by fd0** [comment] 2016-12-14 12:57
Maybe @stapelberg can help? :)

**Comment by legrostdg** [comment] 2016-12-14 13:05
I think the problem is on debian side (dh-golang, debian/rules, other?). `go run build.go` builds just fine.

**Comment by zcalusic** [comment] 2016-12-14 13:50
You could try this hack:
```
ln -s ../src/restic vendor/restic
go install ./src/cmds/restic
```
I used to do this before, to be able to "go install" the binary. But, this will not add the tags @fd0 mentions few comments above, so it is just a hack.

**Comment by jmallach** [comment] 2016-12-14 14:02
@legrostdg does it help if I sponsor it ASAP?

**Comment by legrostdg** [comment] 2016-12-14 14:31
@jmallach not so much... Once golang-github-minio-minio-go-dev is in sid, we'll still have the issue mentioned in my previous comment.

**Comment by legrostdg** [comment] 2016-12-14 14:50
ok, I think I almost have a working package. I removed dh-golang, and used dh only.

**Comment by jmallach** [comment] 2016-12-14 14:58
@legrostdg but the faster golang-github-minio-minio-go-dev hits the NEW queue, hopefully faster it'll get cleared. Do you have a sponsor looking at this already, or should I have a look myself?

**Comment by legrostdg** [comment] 2016-12-14 15:08
@jmallach See https://lists.debian.org/debian-mentors/2016/12/msg00154.html I'll contact you soon if I have no feedback from Gianfranco or Dmitry

**Comment by jmallach** [comment] 2016-12-14 16:13
@legrostdg ah, this package has already been uploaded, so we're all set. Is this the only missing dependency? https://ftp-master.debian.org/deferred.html

**Comment by legrostdg** [comment] 2016-12-14 16:26
@jmallach oh, yes, I forgot: Gianfranco put it in deferred.
That's the only missing dependency. I've uploaded the restic package to mentors. (see RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848148)

**Comment by legrostdg** [comment] 2016-12-16 12:47
I now need reviewers and sponsors for restic to enter in sid, if people want to have a look (see RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848148).

@jmallach still no answer from Gianfranco and Dmitry. Maybe you could upload the latest version on mentors (the one in the deferred queue is not the latest revision)?

**Comment by legrostdg** [comment] 2016-12-18 15:48
`golang-github-minio-minio-go-dev` 2.0.2 is in sid now. My package of `restic` still have no sponsor nor tester, so we'll probably have no `restic` in stretch, as the package would have to be sid before the 25th...

**Comment by stapelberg** [comment] 2016-12-18 15:53
I’m replying to the RFS as we speak.

**Comment by stapelberg** [comment] 2016-12-18 16:03
Replied: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848148#14

**Comment by jmallach** [comment] 2016-12-18 17:14
Did you see my comments on mentors.debian.net?

**Comment by stapelberg** [comment] 2016-12-18 17:20
No. If you want to take this RFS, please assign it to you and reply on the bug.

That said, the comments themselves have merit; thanks for the review.

**Comment by fd0** [comment] 2016-12-18 18:14
@legrostdg Unfortunately, restic 0.3.1 contains a bug which makes it panic whenever an error occurs while reading files during backup (details #699), so I've released 0.3.2 a few minutes ago, which includes nothing except the bugfix. Could you please upload that release?

**Comment by fd0** [comment] 2016-12-18 18:17
And regarding to the comment on the package: restic is not intended to be used as a library (at least not for now), so from my point of view it's not necessary to install the source code anywhere. When you have a new package ready I can also offer to have a look. After all, I was a Debian Developer once ;)

**Comment by fd0** [comment] 2016-12-18 18:43
Further review comments from my side:
 * Modifying `build.go` as you do in [`0001-replace-vendor-src-by-usr-share-gocode-src.patch`](https://gitweb.gueux.org/restic.git?p=restic.git;a=blob;f=debian/patches/0001-replace-vendor-src-by-usr-share-gocode-src.patch;h=7b1220dd0c3d38b46328a1c99b2c8b60aaf4ba54;hb=HEAD) is a bad idea: During build, the program creates a new `GOPATH` constructed from the restic source code and the vendor directory in a temporary directory. After the patch is applied, all the source code available in `/usr/share/gocode/src` is copied to the temp dir, that's unnecessary and slows down the build.
 * I was astonished to see that you removed a section from the manual regarding installation on other OS/Distributions in [`0002-Debianize-doc-Manual.md.patch`](https://gitweb.gueux.org/restic.git?p=restic.git;a=blob;f=debian/patches/0002-Debianize-doc-Manual.md.patch;h=25e6916c4cb6eee84b87bafdab604e496ab16471;hb=HEAD). I must say that I don't like this change at all. There's no reason to hide the installation instructions, and you also remove quite a lot of "getting started" text which shows the user how to get help for restic commands. If you do not like the section about Debian, I'm sure we can work something out.

If you need help getting the binary to build with `go build`, please reach out, I'm glad to assist.

**Comment by fd0** [comment] 2016-12-18 20:06
Here's a sample `debian/rules`: https://gist.github.com/fd0/c3ec442e3b77be0f959425469f6b7583

**Comment by jmallach** [comment] 2016-12-18 22:29
Please avoid including build dates and the like in binaries. They make it impossible to reproduce the build and obtain a byte-for-byte identical package. https://reproducible-builds.org/docs/timestamps/

**Comment by jmallach** [comment] 2016-12-18 22:56
Hi @stapelberg! I propose that when @legrostdg addresses the GPL-3 thing in debian/* (I also noticed, seems I forgot to add that one), the Manual.md thing, the install code bit and add the pristiner-tar bit, the first of us two who gets to re-review does the upload.

Switching to pkg-go can happen after restic has transitioned once to testing, and before February 5th. The less steps that can delay the upload, the better. @legrostdg, let us know if you can work on these in the short term.

**Comment by legrostdg** [comment] 2016-12-19 11:35
I replied to @stapelberg concerns, on the debian bug report.

I also imported 0.3.2.

Concerning `0002-Debianize-doc-Manual.md.patch` I did remove the installation paragraph because these manual installation instructions are not suitable for Debian, it is usual to remove these from Debian packages. I did also remove the end of the paragraph with the basic usage instructions because I felt like this was just the output of `--help`. I think this should probably in a new paragraph but in the meantime, I just renamed the paragraph "basic usage" and restored this part of the Manual.md.

Concerning `0001-replace-vendor-src-by-usr-share-gocode-src.patch`, you are aware that the vendor/src dir has to be removed from the package, right? I added this patch because `go run build.go` failed if vendor/src was not existent. I'm of course open to something else. Do you think it would be better to remove everything which mentions vendor?

I just uploaded a new package to mentors. Thanks for your reviews!

**Comment by fd0** [comment] 2016-12-19 12:11
@legrostdg For building, I'd suggest using `go build`  with `GOPATH` set, see here: https://gist.github.com/fd0/c3ec442e3b77be0f959425469f6b7583

You can also leave the `main.compiledAt`  variable unset, this will get you reproduceable builds, I'll remove the timestamp from restic shortly (as suggested by @jmallach).

**Comment by legrostdg** [comment] 2016-12-19 14:33
Thanks, I've updated the package with your debian/rules, and removed my patch for modifying vendor in build.go.

**Comment by fd0** [comment] 2016-12-19 20:11
Looks good from my side!

**Comment by jmallach** [comment] 2016-12-19 23:54
Same here!

**Comment by jmallach** [comment] 2016-12-20 00:17
I have signed & uploaded this. It will hopefully appear soon in the NEW queue. Good work Félix!

**Comment by legrostdg** [comment] 2016-12-20 00:28
Thanks! I hope it will reach unstable within 5 days, so that restic can be in stretch. I would have preferred to get a feedback from @stapelberg but I guess you're right, we can fix the package to use dh-golang and set the maintainer to pkg-go later.

**Comment by jmallach** [comment] 2016-12-20 00:48
Yeah, I wanted to get the clock ticking, and the package is more than good enough for the archive already. I am strongly aligned with @stapelberg regarding debian/*'s GPL+3. It is becoming more and more standard practice that the packaging just follows the upstream license, or at least it is dual licensed, unless the upstream license is non-free, of course.

Regarding the manual.md patch, I also don't see the point in patching it, but I think it would be less of an issue if you could add a manpage for restic that can be even contributed upstream. Starting with what help2man outputs is a good start and gets rid of much of the grunt work.

I also noticed the source is in section utils, while the binary is in section misc. I'd settle for utils, or admin, or whatever, but not misc.

Finally, for the nitpicker in me, use https on the "Format" URL in d/copyright. :)

**Comment by jmallach** [comment] 2016-12-22 19:23
restic_0.3.2-2_amd64.changes ACCEPTED into unstable, unstable

The hardest is now over. Congrats @legrostdg and @fd0! Let's see if RC bugs leave us alone and we make it in testing before the 5th!

**Comment by fd0** [comment] 2016-12-22 22:06
Awesome!

**Comment by jmallach** [comment] 2017-01-04 10:55
And to probably close this issue,

https://tracker.debian.org/news/829517

restic 0.3.2-2 MIGRATED to testing

@fd0, it'd be nice if a new release could be made during the next week or so, that includes the latest fixes, and in particular https://github.com/restic/restic/commit/e1fc455079f37b27e162d4fcab666da0caa5bc6e. Last restic updates can go into stretch in if uploaded around Jan 22th or so.

**Comment by fd0** [comment] 2017-01-04 12:26
Cool, thanks for letting us know. I'll do a release next week, probably 0.3.3 (no larger changes, just bugfixes).

**Comment by fd0** [comment] 2017-01-08 09:49
Done: [restic 0.3.3](https://github.com/restic/restic/releases/tag/v0.3.3)

**Closed by fd0** 2017-01-08 09:49 UTC
Labels: project

**Comment by fd0** [comment] 2017-01-08 09:56
I've announced the debian package in the blog, together with the new release: https://restic.github.io/blog/2017-01-08/restic-0.3.3-released

**Comment by legrostdg** [comment] 2017-01-08 15:03
I've seen that the code for rest-server has been moved to another directory. Unfortunately it won't be possible to have another package enter stretch.

What can be done is to add a patch to add rest-server back, or to have stretch without this functionality. What do you think?

**Comment by fd0** [comment] 2017-01-08 18:59
The REST server is a separate package now. And it is not built automatically by `build.go`, so it technically wasn't in the package before. It is also not necessary for running restic, only if you want to use a different transport than sftp or s3.

**Comment by legrostdg** [comment] 2017-01-08 21:21
OK! I've pushed the updated package to mentors.

**Comment by fd0** [comment] 2017-02-08 20:58
Hey, restic 0.4.0 was released recently and I think it should be uploaded to Debian ASAP. @legrostdg can you please have a look?

I also noticed that 0.3.3 wasn't uploaded either. Is there anything I can do to speed up uploading new versions?

**Comment by legrostdg** [comment] 2017-02-08 21:01
I've seen the recent releases, but Debian has entered full freeze, so there won't be any non rc fixing upload to unstable before stretch is released.

**Comment by stapelberg** [comment] 2017-02-08 21:02
You could upload to experimental in the meantime.

**Comment by fd0** [comment] 2017-02-08 21:03
Ah, that explains it. Hm, bummer.

**Comment by jannic** [comment] 2017-02-08 21:05
BTW, 0.3.3 was uploaded and entered testing before full freeze:
https://tracker.debian.org/pkg/restic

**Comment by fd0** [comment] 2017-02-08 21:09
Thanks for the correction, I just looked at the "news" box.

**Comment by SnakeO** [comment] 2018-03-01 10:22
Is there a PPA I can use to install the latest version of restic on Ubuntu 16.04LTS ?
