### ISSUE TITLE
Support for hard links

### ISSUE THREAD

**Issue by jgfrm** [restic/restic#733] opened 2017-01-20 21:47 UTC
For full linux backups, support of hard links

**Comment by pvgoran** [comment] 2017-01-21 01:16
DUplicate of #152.

**Comment by fd0** [comment] 2017-01-21 17:40
Thanks for raising this issue, it is indeed a duplicate so I'm closing this issue. You can subscribe to #152 if you'd like to be notified of the process.

**Closed by fd0** 2017-01-21 17:40 UTC
