### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alecbl** [restic/restic#1517] opened 2017-12-31 10:53 UTC
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
RESTIC_PASSWORD=$RESTIC_PASSWORD B2_ACCOUNT_ID=$B2_ACCOUNT_ID B2_ACCOUNT_KEY=$B2_ACCOUNT_KEY /usr/bin/restic --cache-dir=$cache_dir -r b2:$b2_bucket:/ backup $bkp_dir -e $bkp_dir_exclude -o b2.connections=10

And on the dataset in which it panics, I get this output:
panic: runtime error: invalid memory address or nil pointer dereference11649 items  0 errors  ETA 41:46 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x30]

goroutine 2380372 [running]:
panic(0xa36200, 0xe71070)
        /usr/lib64/go/src/runtime/panic.go:540 +0x45e
runtime.panicmem()
        /usr/lib64/go/src/runtime/panic.go:63 +0x5e
runtime.sigpanic()
        /usr/lib64/go/src/runtime/signal_unix.go:367 +0x17c
created by net.(*Resolver).goLookupIPCNAMEOrder
        /usr/lib64/go/src/net/dnsclient_unix.go:482 +0x21c
password is correct
unable to create lock in backend: repository is already locked by PID 12213 on nfs1 by root (UID 0, GID 0)
lock was created at 2017-12-29 18:47:25 (35h59m1.245739467s ago)
storage ID 2919f7d7

The execution trace (at least on 0.8.0) tends to be different and not always the same. The panic part is consistent.

I've ran it on VM's on different hosts. I have high confidence a hardware issue isn't involved. The dataset resides on a btrfs filesystem. I've ran it with different kernels (grsec+4.9 branch, and 4.14 branch). I get no errors logged by the kernel elsewhere. (It's not going OOM or anything, I've increased VM memory to 16 GB).
The OS running is gentoo amd64 hardened.

## What backend/server/service did you use to store the repository?
B2 Storage Cloud

## Expected behavior
I expected all the directories to backup successfully.

## Actual behavior
Out of 4 directories, restic backups 3 which are < 200gb each, and always panics on one which is > 750gb in size.

## Steps to reproduce the behavior
I'm not sure. It always fails for me on that data set. At least since 0.8.0. Possibly also used 0.7.3 but not sure.

## Do you have any idea what may have caused this?
No.

## Do you have an idea how to solve the issue?
Sorry, I don't.

## Did restic help you or made you happy in any way?
Not yet but I'm hoping :)

**Comment by Philippe23** [comment] 2017-12-31 14:56
I just got this same error, also with B2 as a backend on a data set that's been backing up fine daily for weeks.

**Comment by fd0** [comment] 2017-12-31 16:13
Hey, thanks for the reports. Can one of you paste the complete output from a crash? Thanks!

**Comment by Philippe23** [comment] 2017-12-31 16:15
Pretty much what @alecbl had above: ```
using parent snapshot ad88b6e9
scan [/home]
[2:16] 42061 directories, 865060 files, 166.977 GiB
scanned 42061 directories, 865060 files in 2:16
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x56c202]

goroutine 3231 [running]:
net.(*dnsMsg).Pack(0xc435cae780, 0x330b6a94, 0xc420153c40, 0x44c198, 0x336fff349b494)
	/usr/lib64/go/src/net/dnsmsg.go:759 +0x2b2
net.(*dnsPacketConn).dnsRoundTrip(0xc4203b6a20, 0xc435cae780, 0xe8a460, 0xe8a460, 0x0)
	/usr/lib64/go/src/net/dnsclient_unix.go:47 +0x32
net.(*Resolver).exchange(0xe88f70, 0xe4dac0, 0xc423667200, 0xc4201d01a0, 0xd, 0xc426ba7d60, 0x1e, 0xe40001, 0x12a05f200, 0x0, ...)
	/usr/lib64/go/src/net/dnsclient_unix.go:138 +0x48e
net.(*Resolver).tryOneName(0xe88f70, 0xe4dac0, 0xc423667200, 0xc4201bfa40, 0xc426ba7d60, 0x1e, 0x1, 0xc42048f7a8, 0x55b17e, 0xc420411204, ...)
	/usr/lib64/go/src/net/dnsclient_unix.go:161 +0x148
net.(*Resolver).goLookupIPCNAMEOrder.func1(0xe88f70, 0xe4dac0, 0xc423667200, 0xc4201bfa40, 0xc42a5432d0, 0xc4236672c0, 0xc420480001)
	/usr/lib64/go/src/net/dnsclient_unix.go:483 +0x8d
created by net.(*Resolver).goLookupIPCNAMEOrder
	/usr/lib64/go/src/net/dnsclient_unix.go:482 +0x21c
```

**Comment by fd0** [comment] 2017-12-31 16:39
Is that all? Nothing more?

It's a panic that occurs in the Go standard library, I'm going to report the bug upstream.

**Comment by fd0** [comment] 2017-12-31 16:41
Can you please reproduce the issue again while capturing the network traffic with `wireshark`? That may be very helpful.

**Comment by alecbl** [comment] 2018-01-01 11:07
I can do that (wireshark). It might be done in 24h, or it might take me a week max.
Could you mention what traffic you might want/need on wireshark? If I do it with a whitelist it might save me some time than capping all and then seeing if there's anything that might be sensitive and unrelated to filter out.

Thanks!

**Comment by fd0** [comment] 2018-01-01 16:43
Capturing port 53 is probably enough, so the capture filter could be `port 53`.

**Comment by FiloSottile** [comment] 2018-01-05 19:57
Run with env var `GOTRACEBACK=system` to see what spawned that goroutine.

**Comment by Philippe23** [comment] 2018-02-15 13:06
I haven't gotten this on a backup again, but I went to do my first prune and I've gotten it 2 out of 2 tries.  (Granted, the prune operation takes hours and eats up $$ in bandwidth, I/O fees, and storage.)

I don't have a wireshark capture, but I do have the more verbose `GOTRACEBACK=system` suggested by @FiloSottile above.  Here you go: [restic_dns_crash.log](https://github.com/restic/restic/files/1727695/restic_dns_crash.log)

Let me know if a wireshark dump is still desired.  I'll have to do some finagling, since hours of DNS traffic on this machine will have a ton of noise in it, but maybe I can clone it and have the clone run the prune.  Prune doesn't need to be run on the originating machine, right?  All the data it deals with is in the backup, so aside from not having the cache prune could be run from any machine as long as it has the credentials, right?

**Comment by Philippe23** [comment] 2018-02-16 16:00
Tried on another VM with more memory (16GB + 12GB swap), and got same error, but different callstack (perhaps it's just deeper?).  This one is without `GOTRACEBACK=system`, but I'm running again with that set and will report back what happens.  In the meantime, here's the output.

```
# restic prune
password is correct
counting files in repo
building new index for repo
[3:20:35] 100.00%  44906 / 44906 packs
repository contains 44906 packs (1776777 blobs) with 207.046 GiB
processed 1776777 blobs: 473236 duplicate blobs, 10.952 GiB duplicate
load all snapshots
find data that is still in use for 252 snapshots
[2:04:20] 100.00%  252 / 252 snapshots
found 1248297 of 1776777 data blobs still in use, removing 528480 blobs
will remove 0 invalid files
will delete 937 packs and rewrite 5674 packs, this frees 18.720 GiB
[3:40:01] 84.53%  4796 / 5674 packs rewritten
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e pc=0x4e7d82]

goroutine 994298 [running]:
internal/poll.(*FD).writeUnlock(0x1e)
        /usr/lib64/go/src/internal/poll/fd_mutex.go:247 +0x22
internal/poll.(*FD).Write(0xc426e52700, 0xc422770800, 0x2f, 0x7d0, 0x2f, 0x0, 0x0)
        /usr/lib64/go/src/internal/poll/fd_unix.go:224 +0x2eb
net.(*netFD).Write(0xc426e52700, 0xc422770800, 0x2f, 0x7d0, 0x7d0, 0xc4319ea500, 0x0)
        /usr/lib64/go/src/net/fd_unix.go:220 +0x52
net.(*conn).Write(0xc435dcceb8, 0xc422770800, 0x2f, 0x7d0, 0x0, 0x0, 0x0)
        /usr/lib64/go/src/net/net.go:188 +0x6d
net.(*dnsPacketConn).dnsRoundTrip(0xc4202752a0, 0xc426e52600, 0xe8a460, 0xe8a460, 0x0)
        /usr/lib64/go/src/net/dnsclient_unix.go:51 +0x55
net.(*Resolver).exchange(0xe88f70, 0xe4dac0, 0xc43ae02fc0, 0xc43106af90, 0xd, 0xc435def3e0, 0x1e, 0x1c, 0x12a05f200, 0x0, ...)
        /usr/lib64/go/src/net/dnsclient_unix.go:138 +0x48e
net.(*Resolver).tryOneName(0xe88f70, 0xe4dac0, 0xc43ae02fc0, 0xc420313b80, 0xc435def3e0, 0x1e, 0x1c, 0xc4201bf3b0, 0xc4358c2480, 0xc4204606a4, ...)
        /usr/lib64/go/src/net/dnsclient_unix.go:161 +0x148
net.(*Resolver).goLookupIPCNAMEOrder.func1(0xe88f70, 0xe4dac0, 0xc43ae02fc0, 0xc420313b80, 0xc420275260, 0xc43ae030e0, 0xc43031001c)
        /usr/lib64/go/src/net/dnsclient_unix.go:483 +0x8d
created by net.(*Resolver).goLookupIPCNAMEOrder
        /usr/lib64/go/src/net/dnsclient_unix.go:482 +0x21c
```

I should note that while I am also running Gentoo amd64 hardened, my versions are slightly different from @alecbl's:
```
restic 0.8.0
compiled with go1.9.2 on linux/amd64
```

**Comment by rawtaz** [comment] 2018-02-16 16:34
What about running memtest to check your memory?

**Comment by Philippe23** [comment] 2018-02-16 16:46
@rawtaz 

At least for me, my VM's are AWS EC2 instances located in different zones so they're definitely on different machines.  Seems like a stretch that we're seeing this on 3 different machines with such similar setups.

Also, I haven't had any other memory issues on the primary/original VM, so it seems odd that it only hits restic's DNS requests and not any of the thousands of others that happen on the machine each day.

Restic is the only go application I have installed, so it seems to me that it's far more likely a restic or go bug than bad memory.

**Comment by fd0** [comment] 2018-02-16 18:53
My bet is that it is a bug in the Go DNS resolver which is seldomly triggered.

In order to report this to the Go developers, could you all please post what `restic version` reports, so we can pin down the exact versions of restic and the Go compiler this happens with?

**Comment by Philippe23** [comment] 2018-02-16 20:03
@fd0, consolidated for your convience:

@alecbl posted this with the original issue creation:

> restic 0.8.1
> compiled with go1.9.2 on linux/amd64

Mine:

> restic 0.8.0
> compiled with go1.9.2 on linux/amd64

So far we're the only two who've chimed in here, and we're both running Gentoo amd64 Hardened.  I specifically am running the Gentoo _"default/linux/amd64/17.0/hardened (stable)"_ profile to be precise.  Not sure about @alecbl.  We're also both B2 users.

I'm currently partway through another prune attempt on the 16GB+12GB VM.  After that fails, unless there's something else you want me to try first, I'm likely to spin up a different Linux OS AMI to see if I can get the purge to complete (because every failure adds another 8GB of data when the purge adds it, but fails to finish and clean out the old and it's starting to add up).  That would be a data point from another distro, but also might not make it as 100% reproduceable....  Not sure if there's a way to run the pruge through gdb or something to be able to inspect the callstack better -- never done any go development.

**Comment by fd0** [comment] 2018-02-16 20:44
Thanks! The next question the Go developers will ask: Does it still occur with Go 1.10 (which was released just ~50 minutes ago)? I can build binaries for you, both for 0.8.1 and the latest master, if you're interested in trying that...

In other news, recent changes introduced in master will probably make `prune` do only one third of the requests to B2, so it'll be much faster (and cheaper).

**Comment by Philippe23** [comment] 2018-02-16 21:15
Sure, I'll give it a try with your binaries.

**Comment by fd0** [comment] 2018-02-16 22:30
You can find a binary for the latest master branch here: https://beta.restic.net/?sort=time&order=desc Starting with `restic-v0.8.1-143-g28b00891` it is using Go 1.10.

I've uploaded restic 0.8.1 compiled with Go 1.10 here: https://fd0.me/tmp/restic_0.8.1_go1.10_linux_amd64

**Comment by Philippe23** [comment] 2018-02-16 23:31
Thanks, I'll try them over the weekend.

That prune run on the 16+12 VM with `GOTRACEBACK=system` set finished.  Here's the output: 
[restic_dns_crash_more_mem.log](https://github.com/restic/restic/files/1733133/restic_dns_crash_more_mem.log)

**Comment by Philippe23** [comment] 2018-02-21 13:05
`restic_0.8.1_go1.10_linux_amd64` finished the prune successfully on a 16GB RAM+12GB Swap VM.

**Comment by Philippe23** [comment] 2018-02-22 19:42
Additional information.  `restic prune` no longer recreates the issue on my original VM now that the prune completed on the dataset.

One caveat to the above is that I recompiled restic before doing this test, so I was running 
```
restic 0.8.1
compiled with go1.9.4 on linux/amd64
```
instead of 0.8.0 compiled on 1.9.2.  Since @alecbl had the issue with 0.8.1 on 1.9.2, it seems there's slight chance that 1.9.4 actually has the fix, but it's probably more likely that not having to actually move data made fewer DNS requests and thus the bug didn't present itself.  (I may try to downgrade to 1.9.2 at some point just to try it, but I may not since each try is costing me I/O + bandwidth fees.)

Mostly this just means that I can't verify if it was @fd0's toolchain/build settings vs 1.10 was what fixed it.

Just to make it clear, this doesn't change the fact that the 0.8.1 + 1.10 build above seems to not have the issue.

**Comment by fd0** [comment] 2018-02-25 12:04
I'm closing this issue for now. If it happens again, please add a comment so we can reopen it. Thanks!

**Closed by fd0** 2018-02-25 12:04 UTC
Labels: backend:b2, bug
