### ISSUE TITLE
Improve behavior of restic snapshots output after --files-from 

### ISSUE THREAD

**Issue by oficsu** [restic/restic#3451] opened 2021-07-04 19:45 UTC
Output of `restic version`
--------------------------

restic 0.11.0 compiled with go1.15.4 on linux/amd64 (Installed from Ubuntu Hirsute repo)

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Let's say we want to backup following directory tree:
```
.
└── prefix/
    ├── backup_all/
    │   ├── file_1.txt
    │   └── file_2.txt
    └── backup_some/
        ├── file_3.txt
        ├── file_4.txt
        ├── file_5.txt
        ├── file_6.txt
        ├── file_7.txt
        └── file_8.txt
```

As reflected in the name, from the `prefix/backup_some/`, we only need to backup... `file_6.txt`, for example. And in this case, `--files-from` is a better way to do this than `--exclude`/`--exclude-file`. Because unlike this example, `prefix/backup_some/` can contain many more files and generation of `files-from` file can be easier than `exclude-file`. And in both cases, I expect the result to be similar: we backup **part of the `prefix`** directory tree, so the `restic snapshots` command should show the path to only prefix in the output, no more, no less

**In fact**, the output is different: using `--exclude-file` we get the expected behavior, but with `--files-from` we get two paths: to `prefix/` and to `prefix/backup_some/file_6.txt`. With more files (and longer paths), the output becomes hard to read

Steps to reproduce the behavior
-------------------------------

1) Create a next directory tree somewhere:

```bash
mkdir -p prefix/backup_all/ \
         prefix/backup_some/

touch prefix/backup_all/file_1.txt \
      prefix/backup_all/file_2.txt

touch prefix/backup_some/file_3.txt \
      prefix/backup_some/file_4.txt \
      prefix/backup_some/file_5.txt \
      prefix/backup_some/file_6.txt \
      prefix/backup_some/file_7.txt \
      prefix/backup_some/file_8.txt
```

2) Set the variables and init some repo:
```bash
export RESTIC_PASSWORD=123
export RESTIC_REPOSITORY=./repo
restic init
```

3) Prepare a list of files from the second directory for backup:
```bash
echo ./prefix/backup_some/file_6.txt > backup_these.txt
```

4) Backup our files in the `prefix/` with restic:
```bash
restic backup ./prefix/ \
      --exclude=./prefix/backup_some/ \
      --files-from=./backup_these.txt
```
5) Get the snapshots list:
```bash
restic snapshots
```
```
ID        Time        ...  Paths
---------------------------------------------------------
b2061084  2021-07-04  ...  /prefix
                           /prefix/backup_some/file_6.txt
---------------------------------------------------------
1 snapshots
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Since both paths start with a common prefix (`/prefix` in this case), I find it more logical that only the `/prefix` is displayed in the `Paths` column, something like that:
```
ID        Time        ...  Paths
---------------------------------------------------------
b2061084  2021-07-04  ...  /prefix
---------------------------------------------------------
1 snapshots
```
Perhaps some of the users can rely on current behavior, so I think the best solution is to add a new flag that will change the behavior: it will disable adding directories from `--files-from` file to `Paths` column **or, even better**, will enable detection of a common prefix among files list. I think both new behaviors could be useful. For example, with the second one we can
```bash
echo './prefix/backup_all/file_1.txt' >> backup_these.txt
restic backup --files-from=./backup_these.txt
```
Now we can see the following output:
```
ID        Time        ...  Paths
---------------------------------------------------------
...       ...         ...  ...
dc5ace30  2021-07-04  ...  /prefix/backup_all/file_1.txt
                           /prefix/backup_some/file_6.txt
---------------------------------------------------------
1 snapshots
```
It would be great if we could change the behavior to see the only `/prefix` path:
```
ID        Time        ...  Paths
---------------------------------------------------------
...       ...         ...  ...
dc5ace30  2021-07-04  ...  /prefix
---------------------------------------------------------
1 snapshots
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I just learned about this wonderful tool today and I hope that it will help me regularly from this day on.

**Comment by wren** [comment] 2021-07-13 18:20
Hi! This looks like a duplicate of an issue I filed last year (#3198). In that, I'm referring to `--files-from-raw`, but it looks like it also affects `--files-from`. There's also a related issue (#2246) about how this path detection problem also affects parent detection for snapshots.

> Perhaps some of the users can rely on current behavior, so I think the best solution is to add a new flag that will change the behavior...

I completely agree! There's actually already a PR (#3200) to implement a new flag (`--set-path`) for a snapshot. So, if your example above, it might looks something like `restic backup --set-path=./prefix --files-from=./backup_these.txt`. The PR has been getting reviewed for a while, but it seems like it might be ready (although there haven't been any core contributor reviews, so I'm not sure what the status is, or how to move it forward).


> ... or, even better, will enable detection of a common prefix among files list.

I suggested something similar in #3198 and there's some discussion around it there, but it was ruled out as too complicated (which makes sense to me).

**Comment by MichaelEischer** [comment] 2021-07-16 19:20
Closing as duplicate of #3198 to keep the discussion on the too long path lists in one place.

Determining a common prefix among the files could only be an approximate operation and I guess there would be lots of different opinions on how many paths the result should have. And I not sure whether an option to determine a path prefix would be worth the trouble.

**Closed by MichaelEischer** 2021-07-16 19:20 UTC
