### ISSUE TITLE
Excessive file/disk reading despite available parent and identical metadata

### ISSUE THREAD

**Issue by ATLief** [restic/restic#2819] opened 2020-07-05 23:04 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64

How did you run restic exactly?
-------------------------------
restic backup --exclude-file=/root/system-backup/exclude.txt --tag=new4 --tag=focal --password-file=/root/system-backup/password.txt -r /mnt/backup/restic/ /

What backend/server/service did you use to store the repository?
-----------------------------------------------------------------
A mounted filesystem on a local disk

Expected behavior
-----------------
Restic checks all files but doesn't read them if all metadata is the same (as it did in 0.9.5)

Actual behavior
---------------
Restic reads every single file even if all of the metadata is the same

Steps to reproduce the behavior
-------------------------------
Perform a normal restic backup (with or without specifying --parent)

**Comment by rawtaz** [comment] 2020-07-05 23:17
Please paste the command and its output from `restic snapshots` (with relevant arguments) and tell us which snapshot you expect restic to use as the parent snapshot?

**Comment by ATLief** [comment] 2020-07-05 23:29
Thanks for following up. Here's an excerpt of the output:

> repository c63c41de opened successfully, password is correct                                                    
> ID        Time                 Host        Tags                          Paths                                  
> ------------------------------------------------------------------------------
> [...]
> 2a0feb63  2020-07-04 15:04:04  postulate   new4,focal                    /
> 3d8addb6  2020-07-04 23:04:01  postulate   new4,focal                    /
> de2a3cce  2020-07-05 04:04:02  postulate   new4,focal                    /
> 3c1c32ae  2020-07-05 11:04:02  postulate   new4,focal                    /
> ------------------------------------------------------------------------------

I expected `3c1c32ae` to use `de2a3cce` as the parent snapshot (although I think it actually did). In my limited testing, specifying --parent reduced the backup time from ~7 hours to ~5 hours. But both of these times are still significantly higher than the ~30 mins 0.9.5 took to deal with the same amount of data (~3TB).

This was the command used for snapshots:
`restic snapshots --no-lock --path=/ --password-file=/root/system-backup/password.txt -r /mnt/backup/restic/`

**Comment by rawtaz** [comment] 2020-07-05 23:52
Can you please pastebin the complete command and all of its output from when you run your `restic backup --exclude-file=/root/system-backup/exclude.txt --tag=new4 --tag=focal --password-file=/root/system-backup/password.txt -r /mnt/backup/restic/ /` and after that `restic backup --exclude-file=/root/system-backup/exclude.txt --tag=new4 --tag=focal --password-file=/root/system-backup/password.txt -r /mnt/backup/restic/ --verbose /` (added `--verbose` flag)? Feel free to edit tags of course.

**Comment by dimejo** [comment] 2020-07-06 07:34
> Restic checks all files but doesn't read them if all metadata is the same (as it did in 0.9.5)

There was a bug in older versions of restic which prevented it from recognizing metadata changes. Is it possible that the metadata changes between backups? Which filesystem are you using and do you remount between backups?

**Comment by ATLief** [comment] 2020-07-06 15:06
@dimejo It's possible but very unlikely. The metadata for some files will definitely change between backups (sometimes while the contents stay the same), but I've been seeing sustained reads (~50MB/s to ~300MB/s) for the duration of the backup, which would be consistent with the metadata for nearly every file changing. Most of the data I'm backing up is relatively "cold" and isn't modified often.

I'm using Ext4, and I don't remount between backups. I usually restart once a month and thus "remount" the filesystem then.

@rawtaz [Here's the output of the second command.](https://pastebin.com/raw/Bjj58j28)

**Comment by buschjost** [comment] 2020-07-06 17:05
When I understood it correctly you can trigger Restic to behave like before #2249 when you add the flag `--ignore-inode`. 
But you may will miss out metadata changes then. According to the issue this could include:

> If fileChanged() returns false, the old node is copied over, which not only (correctly) copies over the list of blobs the file consists of, but also all metadata information. The current ownership and other attributes which can be changed without changing the mtime are discarded.

**Comment by rawtaz** [comment] 2020-07-06 19:42
Well it clearly does use a parent snapshot, as per https://pastebin.com/raw/Bjj58j28 ("using parent snapshot e3cae808"). Are you saying that the behavior changed between 0.9.5 and 0.9.6? Can you reproduce that in a way such that we can clearly see the differences between 0.9.5 and 0.9.6?

**Comment by ATLief** [comment] 2020-07-06 21:41
Possibly some additional insight: running the earlier backup command with `--verbose=2` and (grep) filtering the output shows that, of the 214625 files modified, 214478 had only their metadata changed ("0 B added"). That strikes me as very unlikely and I wonder whether `restic` is incorrectly determining that files have been modified and unnecessarily rereading them. Furthermore, using version 0.9.5 or specifying `--ignore-inode` reduced the number of reported modified files from 200k+ to less than 200.

@buschjost Thanks for the suggestion. Indeed, using it returns restic to its former speed. But surely there must be a way to pickup metadata changes without rereading the entire file (maybe by skipping reading the file contents if the mtime and size are the same?).

@rawtaz Sure: the speed and reported modified file count. I can provide statistics of a few runs but in general version 0.9.5 (or specifying `--ignore-inode`) takes less than 30 mins and reports less then 200 modified files, while version 0.9.6 (without `--ignore-inode`) takes at least 4 hours and reported more than 200k modified files.

**Comment by rawtaz** [comment] 2020-07-08 02:30
@ATLief Seems rather related to inode changes then. We have established that restic is using a parent snapshot as it should, and you have verified that ignoring inode changes gives you the expected behavior. I can only presume that your inodes have been touched. Shall we close this or what is your current take on it? Do you feel something is still amiss?

**Comment by greatroar** [comment] 2020-07-08 06:44
> But surely there must be a way to pickup metadata changes without rereading the entire file

restic does detects the inode change cheaply, but that then triggers a rescan if ctime has changed. This was introduced in #2212 to fix #2179: some programs mess with the mtime, so it alone is not considered reliable.

If mtime changes are really the problem, this is a duplicate of #2495. @rawtaz having to specify --ignore-inode is a hack, because it also turns of inode number checking. #2558 asks for a new flag to trust the mtime, separate from --ignore-inode, which is the cleaner option.

**Comment by ATLief** [comment] 2020-07-09 19:22
@greatroar The problem is that ctime regularly changes despite files (and their metadata) otherwise staying the same. In my particular case, it's because I regularly and recursively `chmod` and `chown` certain directories to ensure permissions compliance. Unfortunately this also means that your proposed solution (adding a `--trust-mtime` flag) wouldn't completely fix this problem; metadata-only changes (like removing "x" permission from files in /etc/cron.??*/, which I do fairly regularly) still won't be picked up. In this case I think your solution would actually be redundant.
@rawtaz I think that something is still amiss, but after re-reading #2495 I think that this issue is a duplicate of that one, albeit with less snark.

**Closed** 2021-01-28 23:02 UTC
