### ISSUE TITLE
restic crash when backing up

### ISSUE THREAD

**Issue by despiegk** [restic/restic#529] opened 2016-06-06 18:53 UTC
## Output of `restic version`

restic 0.1.0 (v0.1.0-550-ge1b5593)
compiled at 2016-06-06 15:41:08 with go1.6.2

## Expected behavior

backup about 6 GB of data, 270000 files
crashes after about 1h

i expected after crash to continue where it broke, but backup restarted from scratch

## Actual behavior

```
kdspro:MYDATA despiegk$ restic -r backup/ backup /Volumes/Untitled/BTRFS-Backup/ --exclude=*/dvd/** --exclude=*.git --exclude=*/music/**
enter password for repository:
scan [/Volumes/Untitled/BTRFS-Backup]
scanned 6758 directories, 269529 files in 3:34
panic: json: error calling MarshalJSON for type *restic.Node: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]

goroutine 80 [running]:
panic(0x56a100, 0xc8299b90e0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
restic.(*Archiver).dirWorker(0xc8207db360, 0xc82459dec0, 0xc8234b6210, 0xc8234ac720, 0xc8234aca20)
	/var/folders/6n/9yp0w_0n5qq3kcmsplgyf0s00000gn/T/restic-build-254630958/src/restic/archiver.go:404 +0xde2
created by restic.(*Archiver).Snapshot
	/var/folders/6n/9yp0w_0n5qq3kcmsplgyf0s00000gn/T/restic-build-254630958/src/restic/archiver.go:713 +0x88b
kdspro:MYDATA despiegk$ restic version
restic 0.1.0 (v0.1.0-550-ge1b5593)
compiled at 2016-06-06 15:41:08 with go1.6.2
```

## Steps to reproduce the behavior

tried it 3x now
happens on exact same file

**Comment by fd0** [comment] 2016-06-08 19:09
Thanks for reporting! This is very interesting and I've seen this bug before (I think it was in your report). Can you please run `stat` on the file and report back?

**Comment by fd0** [comment] 2016-07-02 10:53
Hey, did you find the time to have a look at the file that crashes the backup process? I'd really like to find out what goes wrong here...

**Comment by meinz90** [comment] 2016-07-16 17:30
I think I have the same problem. But I don't know which file crashes the backup process.

`scanned 20637 directories, 107211 files in 0:00
panic: json: error calling MarshalJSON for type *restic.Node: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]

goroutine 82 [running]:
panic(0x973d60, 0xc82a5ef660)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
restic.(*Archiver).dirWorker(0xc82120c370, 0xc82540ba30, 0xc828e65760, 0xc8211fcde0, 0xc8211fd0e0)
	/tmp/restic-build-565916957/src/restic/archiver.go:404 +0xde2
created by restic.(*Archiver).Snapshot
	/tmp/restic-build-565916957/src/restic/archiver.go:713 +0x88b
`

**Comment by cfcs** [comment] 2016-07-17 10:45
Perhaps you could run it with `strace`, ie `strace -e stat64,stat,open 2>syscalls.txt    {{restic commandline}}` and examine the last lines of syscalls.txt before the crash to find the offending file?

**Comment by meinz90** [comment] 2016-07-17 11:31
I just tried to reproduce the error with strace but now restic works just fine...
The only thing I changed since yesterday is the following: I run FSlint to find dublicated files and there were some big (about 4GB) dublicated installation images. I deleted them. Could this dublicated files have caused the error?

**Comment by fd0** [comment] 2016-07-20 19:10
Maybe, maybe not. I'll add code to report a more detailed error for such cases, so we can track if it happens again.

**Comment by despiegk** [comment] 2016-09-16 16:28
I need to find this disk back which I used for this test )-:
unfortunately I can only test when I have enough bandwidth & this disk
sorry for that

**Comment by fd0** [comment] 2016-09-17 06:26
Take your time. I'll close this issue in the meantime, please report back when you find the disk :)

**Closed by fd0** 2016-09-17 06:26 UTC
Labels: bug, feedback needed

**Comment by fd0** [comment] 2016-09-17 08:44
I've added code in #620 to print a more verbose message for this error which includes the path to the file that caused it and the time with the invalid year. If you see this again, please report it here!
