### ISSUE TITLE
panic on corrupt data

### ISSUE THREAD

**Issue by wjkohnen** [restic/restic#1359] opened 2017-10-16 10:10 UTC
## Output of `restic version`
```
restic 0.7.3 (v0.7.3-0-g81473f45)
compiled with go1.9.1 on linux/amd64
```
## How did you run restic exactly?

```
export RESTIC_PASSWORD='xxx'
export RESTIC_REPOSITORY='/media/path/to/cifs/share/backup'
restic prune
```

```
counting files in repo
building new index for repo
[13:32] 100.00%  39145 / 39145 packs
incomplete pack file (will be removed): 025bc4aea89b1922c365d44404627ea3cabf2e0b09633727674e086cb6b44ad4
incomplete pack file (will be removed): 07aa00dc283460daea27317331941e8c581c8269a74bd13b8220615138079288
incomplete pack file (will be removed): 0ed6bd5ea651b30bd7e8ddc5e60901bcf6abb80cf0dbe9e5d3489d89437a27b2
incomplete pack file (will be removed): 172790c88aef58480690e51530e3d910d1a99e4fa44e6c2b93274970e62d244e
incomplete pack file (will be removed): 26226e5246d6e96acbffc0e3ec250ea2de1f4812e5faf7fee9f706110f9e1248
incomplete pack file (will be removed): 30fe4600160bcdfc34342a0b5a4d7fb5f1876e4c289fae9057b164e4e858007a
incomplete pack file (will be removed): 33cabadd8e98da240ff58076fb0025482fdf3104237a721f3952bbbeb37984ee
incomplete pack file (will be removed): 392fb5641d51eaca8ed0357e3953c738341b3af73095de491647458b1092e101
incomplete pack file (will be removed): 4c8c0c977833236591152e982e0bcd6ce5658e206330380c3cb94230db910322
incomplete pack file (will be removed): 579a332e4486ed4ed62cabdc52dfa00bb14fae8840fe0470d16afe8020b86587
incomplete pack file (will be removed): 57f763e717790debb0bebe29cee08cdbc8dbf51b1162cc67f7215366c146cb9b
incomplete pack file (will be removed): 59c3ed3de86211eaf2c0b785c484e8a5fa65214821ada383a0d7c116c5fd5003
incomplete pack file (will be removed): 696cc3f80b4a66ca66680789cfb9293d65df3716a1e1e761a17aa50e328cd25b
incomplete pack file (will be removed): 6b9ad98baf4bb9ea9263c4c7fbe39f5b72c8917bdce6f7c2481cf0b07f8ca477
incomplete pack file (will be removed): 75fde966ecb4dd03a27ccddfa26cefdf24e043d36fc7e50a451d2e200eb9f626
incomplete pack file (will be removed): 7e46102c9cde193e05b8b364eb30d58bac3e2706faa6ace18012a47195b5aea4
incomplete pack file (will be removed): 7ffe7a4a20d6e658f5398165cd3c483a5b790c9396b2c165e33138c98d15b1c8
incomplete pack file (will be removed): 856da9f9c3f9381db5502caed86e6cf313f160c818217ab850dafb3f0f4d1a92
incomplete pack file (will be removed): 8e3e48f0926ece64b41355dc9eaa9d6ab9c4b5e16badc5ab6585b3bce7216060
incomplete pack file (will be removed): 8f9c3cef53d10c75a418151e56384fa13ab2e9829dbcc43bb31be7435f3410a3
incomplete pack file (will be removed): 9206f00eb8256eab5acf0e9dc5267e40ecdd187f999b043618128c223ee5c5fa
incomplete pack file (will be removed): 94582b296357c87f27454c7c6c69b5ed83263de6afa44294683e40e50184c56c
incomplete pack file (will be removed): 972e3ebe28291dab56715b0b52205006cc104c638f443bfb6d8b54a526fb238e
incomplete pack file (will be removed): 98b89c99bf51610e3297642423441024f92bc93c0b3676805b9d66d8bc91823e
incomplete pack file (will be removed): a90872270a92b09405c79cb916c9521037d81baeebd79b5015fa34fc00e5fd47
incomplete pack file (will be removed): b20115c16349c91f4dcff3c0d693135cab4805e0c758674825e1cd94b2211e69
incomplete pack file (will be removed): b263557fc701dfb86789854dc1df7a69b7ac8e668964e95c1b11511225b93ec9
incomplete pack file (will be removed): b317520753f97ce5adb9d4affe8cc6c27fbc3a33bfef1fc54c463e1f8ed5e0dd
incomplete pack file (will be removed): b69cc10fb8a434a78f58d5db9ce22d9afc73ccd29169aa85a60089be3ae5b32a
incomplete pack file (will be removed): bc385c736fe1b8fdfbb240cfc624b6ad1e42c91afb39bbc6dca2645a59add09f
incomplete pack file (will be removed): bfdb3d28bab448a332039fa1997ec668afff21ae9689225ba47011bb51c5c743
incomplete pack file (will be removed): c7b471676d16875b39809b59d70d7a1fb5fb3ca5ac38b4c539a274854773b9a7
incomplete pack file (will be removed): cb95849106320bab7e8918ddff85ad816164dd8bfbdc30686a4dc6c07cc490d5
incomplete pack file (will be removed): cd647ce53e2c4de96b73c862b9f4c1f9aade14ae959966a9c73f6a2a7c651b06
incomplete pack file (will be removed): cdcaf4d1dd15d76c3a9fcacdee083f3fcda90e3fa2767be8cd93f2e3ad7bf7c3
incomplete pack file (will be removed): d7326659c9286c3b0d0133f4bed59d77b8331f26f733ba538fc86d4ebe61f9cf
incomplete pack file (will be removed): e094adb5dc6c3b6790f7173d16953f917c482a716511e19fe87efdd6088e6e5e
incomplete pack file (will be removed): e62441c3102e27a19b37fe7bccb14d2ff0756d684da94cb51bf9ca0bf6d310ec
incomplete pack file (will be removed): ed87316714b59ce78609874fe0b7a3a1843c742c6e8f45d523c40ea8df8e35c2
incomplete pack file (will be removed): f4312a6a98d0d7b0091b1e17fc942cedd62a40f8cb89ebd617d58f87bf569d38
incomplete pack file (will be removed): f797077f052555392489a855455627f8cc5eac508889f2e91e0ec439bf97711c
repository contains 39104 packs (1529209 blobs) with 182.168 GiB bytes
processed 1529209 blobs: 159557 duplicate blobs, 32.046 GiB duplicate
load all snapshots
find data that is still in use for 75 snapshots
[1:56:10] 100.00%  75 / 75 snapshots
found 1365166 of 1529209 data blobs still in use, removing 164043 blobs
will remove 41 invalid files
will delete 65 packs and rewrite 8767 packs, this frees 32.409 GiB
hash does not match id: want e115da22be833c848bdd655c480eca96379c9cc8f2bb19b1d2de1dd8c3e34180, got 730d8a5105265c0f1a25bb6ca7ffff34934b6680cd7381d4a603db0c1f1d97c7
github.com/restic/restic/internal/repository.Repack
	src/github.com/restic/restic/internal/repository/repack.go:52
main.pruneRepository
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:250
main.runPrune
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func16
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
main.main
	src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337
```
-->

## What backend/server/service did you use?
Backup is direct access via cifs mounted NAS. From output of `mount`:
`//nas/theshare on /media/path/to/cifs/share type cifs (rw,nosuid,nodev,relatime,vers=1.0,cache=strict,username=wjkohnen,domain=thedomain,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.0.212,file_mode=0600,dir_mode=0700,nounix,serverino,mapposix,rsize=61440,wsize=65536,echo_interval=60,actimeo=1)`

## Expected behavior
Do something meaningful with broken data, e.g. warn and continue or repair it. Do no panic!
## Actual behavior
Panic!
## Steps to reproduce the behavior

I do not recall how I've managed to corrupt the data. Might or might not be restic's fault. 

## Do you have an idea how to solve the issue?
No, not yet.

**Comment by fd0** [comment] 2017-10-16 10:37
Hey, thanks for the report. How old is that repo? I'm interested in the oldest restic version that you used with this repo.

And I agree: restic should not panic here.

**Comment by wjkohnen** [comment] 2017-10-16 10:45
I think it was this one, but not 1000% sure:
```
restic 0.7.0 (v0.7.0-0-g27ea0623)
compiled with go1.8.3 on linux/amd64
```

**Comment by fd0** [comment] 2017-10-16 10:50
Hm, thanks.

The story for this error message is: Restic saved a data blob (e.g. a small part of a file) at the ID `e115da22be`, but the SHA256 hash of the data is `730d8a5105` (both shortened). That could've happened a long time ago in an ancient version of restic when a file is written to during the backup (e.g. a log file), but should not occur any more. So you have a repo with a blob that does not contain what restic thinks it contains.

**Comment by wjkohnen** [comment] 2017-10-16 10:56
The backend is a Synology box; generally I have limited trust in these boxes. It might be bit rot, who knows.

```
$ ls -l data/e1/e115da22be833c848bdd655c480eca96379c9cc8f2bb19b1d2de1dd8c3e34180
-rw------- 1 wjkohnen wjkohnen 5060768 Sep  4 15:53 data/e1/e115da22be833c848bdd655c480eca96379c9cc8f2bb19b1d2de1dd8c3e34180
$ sha256sum data/e1/e115da22be833c848bdd655c480eca96379c9cc8f2bb19b1d2de1dd8c3e34180
730d8a5105265c0f1a25bb6ca7ffff34934b6680cd7381d4a603db0c1f1d97c7  data/e1/e115da22be833c848bdd655c480eca96379c9cc8f2bb19b1d2de1dd8c3e34180
```
Before that mtime I had upgraded to `0.7.1`:

```
$ /usr/local/stow/restic-0.7.1/bin/restic version
restic 0.7.1 (v0.7.1-0-g04cfb984)
compiled with go1.8.3 on linux/amd64
```

**Comment by fd0** [comment] 2017-10-16 11:03
You're right, and I checked the wrong place: The error is that the backend returned a file whose file name does not match the SHA256 sum, exactly what you discovered. I've scratched out my comment above. So this is before any signatures are checked, and it is likely bit rot.

**Comment by fd0** [comment] 2017-10-16 11:10
In this case, restic can also try recovering the file, which means reading the blobs from the file and checking their signature, so that only a few blobs from the file are lost. That's not implemented yet, but I've thought about it already.

**Comment by wjkohnen** [comment] 2017-10-19 13:41
FYI, after removing the pertinent file, `prune` terminated succesfully:

```
$ restic prune
counting files in repo
building new index for repo
[10:11] 100.00%  40213 / 40213 packs
incomplete pack file (will be removed): 025bc4aea89b1922c365d44404627ea3cabf2e0b09633727674e086cb6b44ad4
incomplete pack file (will be removed): 07aa00dc283460daea27317331941e8c581c8269a74bd13b8220615138079288
incomplete pack file (will be removed): 0ed6bd5ea651b30bd7e8ddc5e60901bcf6abb80cf0dbe9e5d3489d89437a27b2
incomplete pack file (will be removed): 172790c88aef58480690e51530e3d910d1a99e4fa44e6c2b93274970e62d244e
incomplete pack file (will be removed): 26226e5246d6e96acbffc0e3ec250ea2de1f4812e5faf7fee9f706110f9e1248
incomplete pack file (will be removed): 30fe4600160bcdfc34342a0b5a4d7fb5f1876e4c289fae9057b164e4e858007a
incomplete pack file (will be removed): 33cabadd8e98da240ff58076fb0025482fdf3104237a721f3952bbbeb37984ee
incomplete pack file (will be removed): 392fb5641d51eaca8ed0357e3953c738341b3af73095de491647458b1092e101
incomplete pack file (will be removed): 4c8c0c977833236591152e982e0bcd6ce5658e206330380c3cb94230db910322
incomplete pack file (will be removed): 579a332e4486ed4ed62cabdc52dfa00bb14fae8840fe0470d16afe8020b86587
incomplete pack file (will be removed): 57f763e717790debb0bebe29cee08cdbc8dbf51b1162cc67f7215366c146cb9b
incomplete pack file (will be removed): 59c3ed3de86211eaf2c0b785c484e8a5fa65214821ada383a0d7c116c5fd5003
incomplete pack file (will be removed): 696cc3f80b4a66ca66680789cfb9293d65df3716a1e1e761a17aa50e328cd25b
incomplete pack file (will be removed): 6b9ad98baf4bb9ea9263c4c7fbe39f5b72c8917bdce6f7c2481cf0b07f8ca477
incomplete pack file (will be removed): 75fde966ecb4dd03a27ccddfa26cefdf24e043d36fc7e50a451d2e200eb9f626
incomplete pack file (will be removed): 7e46102c9cde193e05b8b364eb30d58bac3e2706faa6ace18012a47195b5aea4
incomplete pack file (will be removed): 7ffe7a4a20d6e658f5398165cd3c483a5b790c9396b2c165e33138c98d15b1c8
incomplete pack file (will be removed): 856da9f9c3f9381db5502caed86e6cf313f160c818217ab850dafb3f0f4d1a92
incomplete pack file (will be removed): 8e3e48f0926ece64b41355dc9eaa9d6ab9c4b5e16badc5ab6585b3bce7216060
incomplete pack file (will be removed): 8f9c3cef53d10c75a418151e56384fa13ab2e9829dbcc43bb31be7435f3410a3
incomplete pack file (will be removed): 9206f00eb8256eab5acf0e9dc5267e40ecdd187f999b043618128c223ee5c5fa
incomplete pack file (will be removed): 94582b296357c87f27454c7c6c69b5ed83263de6afa44294683e40e50184c56c
incomplete pack file (will be removed): 972e3ebe28291dab56715b0b52205006cc104c638f443bfb6d8b54a526fb238e
incomplete pack file (will be removed): 98b89c99bf51610e3297642423441024f92bc93c0b3676805b9d66d8bc91823e
incomplete pack file (will be removed): a90872270a92b09405c79cb916c9521037d81baeebd79b5015fa34fc00e5fd47
incomplete pack file (will be removed): b20115c16349c91f4dcff3c0d693135cab4805e0c758674825e1cd94b2211e69
incomplete pack file (will be removed): b263557fc701dfb86789854dc1df7a69b7ac8e668964e95c1b11511225b93ec9
incomplete pack file (will be removed): b317520753f97ce5adb9d4affe8cc6c27fbc3a33bfef1fc54c463e1f8ed5e0dd
incomplete pack file (will be removed): b69cc10fb8a434a78f58d5db9ce22d9afc73ccd29169aa85a60089be3ae5b32a
incomplete pack file (will be removed): bc385c736fe1b8fdfbb240cfc624b6ad1e42c91afb39bbc6dca2645a59add09f
incomplete pack file (will be removed): bfdb3d28bab448a332039fa1997ec668afff21ae9689225ba47011bb51c5c743
incomplete pack file (will be removed): c7b471676d16875b39809b59d70d7a1fb5fb3ca5ac38b4c539a274854773b9a7
incomplete pack file (will be removed): cb95849106320bab7e8918ddff85ad816164dd8bfbdc30686a4dc6c07cc490d5
incomplete pack file (will be removed): cd647ce53e2c4de96b73c862b9f4c1f9aade14ae959966a9c73f6a2a7c651b06
incomplete pack file (will be removed): cdcaf4d1dd15d76c3a9fcacdee083f3fcda90e3fa2767be8cd93f2e3ad7bf7c3
incomplete pack file (will be removed): d7326659c9286c3b0d0133f4bed59d77b8331f26f733ba538fc86d4ebe61f9cf
incomplete pack file (will be removed): e094adb5dc6c3b6790f7173d16953f917c482a716511e19fe87efdd6088e6e5e
incomplete pack file (will be removed): e62441c3102e27a19b37fe7bccb14d2ff0756d684da94cb51bf9ca0bf6d310ec
incomplete pack file (will be removed): ed87316714b59ce78609874fe0b7a3a1843c742c6e8f45d523c40ea8df8e35c2
incomplete pack file (will be removed): f4312a6a98d0d7b0091b1e17fc942cedd62a40f8cb89ebd617d58f87bf569d38
incomplete pack file (will be removed): f797077f052555392489a855455627f8cc5eac508889f2e91e0ec439bf97711c
repository contains 40172 packs (1554038 blobs) with 186.845 GiB bytes
processed 1554038 blobs: 178032 duplicate blobs, 35.723 GiB duplicate
load all snapshots
find data that is still in use for 79 snapshots
[40:27] 100.00%  79 / 79 snapshots
found 1371521 of 1554038 data blobs still in use, removing 182517 blobs
will remove 41 invalid files
will delete 65 packs and rewrite 9604 packs, this frees 36.086 GiB
[24:35] 100.00%  9604 / 9604 packs rewritten
counting files in repo
[8:01] 100.00%  31926 / 31926 packs
finding old index files
saved new index as e9594003
remove 11 old index files
[1:44] 100.00%  9669 / 9669 packs deleted
done
```

**Comment by wjkohnen** [comment] 2017-10-19 13:44
(before I've made a backup of the repository; I'll try to investigate it when I have time.)

**Comment by cafuego** [comment] 2018-01-16 05:08
I'm seeing the same issue with one of my repositories. I'm pretty sure the repo was originally created with restic 0.7.1, the forget/purge panic I'm getting now is with
```
cafuego@restic-debug-vm:/srv$ restic version
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

**Comment by cafuego** [comment] 2018-01-16 06:07
I just attempted the suggested fix (remove the problem file, then rerun restic) and got a new error:

```
cafuego@ restic-debug-vm:/srv$ restic prune -o gs.connections=2                                                 password is correct
counting files in repo
building new index for repo
error listing restic/data/: googleapi: Error 503: Backend Error, backendError
[1:02:43] 29.32%  36000 / 122797 packs
repository contains 36000 packs (301908 blobs) with 177.257 GiB
processed 301908 blobs: 50086 duplicate blobs, 9.068 GiB duplicate
load all snapshots
find data that is still in use for 14 snapshots
[1:14] 100.00%  14 / 14 snapshots
number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

**Comment by cafuego** [comment] 2018-01-17 01:10
On re-run with concurrent connections limited to 1:

```
cafuego@restic-debug-vm:/srv$ restic prune -o gs.connections=1
password is correct
counting files in repo
building new index for repo
Load(<data/7f6cc5064a>, 4, 7637172) returned error, retrying after 537.225527ms: googleapi: got HTTP response code 503 with body: Service Unavailable
Load(<data/90ee62a936>, 4, 5148652) returned error, retrying after 530.277987ms: googleapi: got HTTP response code 503 with body: Service Unavailable
error listing restic/data/: googleapi: Error 500: Backend Error, backendError
[5:35:46] 94.46%  116000 / 122797 packs
repository contains 116000 packs (971903 blobs) with 571.283 GiB
processed 971903 blobs: 259163 duplicate blobs, 54.088 GiB duplicate
load all snapshots
find data that is still in use for 14 snapshots
[1:14] 100.00%  14 / 14 snapshots
found 401647 of 971903 data blobs still in use, removing 570256 blobs
will remove 0 invalid files
will delete 20111 packs and rewrite 14575 packs, this frees 162.065 GiB
Load(<data/0f4bb05224>, 0, 0) returned error, retrying after 352.570557ms: googleapi: got HTTP response code 503 with body: Service Unavailable
[1:16:21] 100.00%  14575 / 14575 packs rewritten
counting files in repo
[4:35:29] 100.00%  91142 / 91142 packs
finding old index files
saved new index as 28f2c153
remove 24 old index files
[1:04:13] 100.00%  34686 / 34686 packs deleted
done
```

Am now re-re-running the prune command again with gs.connections=1.

**Comment by fd0** [comment] 2018-01-19 13:55
@cafuego that's odd, it looks like you're not allowed to list the `data/` directory any more... how did you delete the file?

**Comment by cafuego** [comment] 2018-02-05 22:59
I deleted the file via the web console (after saving a copy locally first).  I'm not really sure if the issue there is an actual problem with the API or me hitting a rate limiter; on the next run that error did not re-occur.

At any rate, after having removed the one file with the hash/id mismatch, all restic operations have been running successfully for the past 2 weeks without the `gs.connections` limit set on them 🎉

**Comment by fd0** [comment] 2018-02-25 09:04
Thanks for the feedback. I'll close this issue for now as it is not a bug in restic per se (but I agree restic could handle it a lot better). Please feel free to add further comments, thanks!

**Closed by fd0** 2018-02-25 09:04 UTC
Labels: bug
