### ISSUE TITLE
Prune operation fails repeatedly (B2 Bucket)

### ISSUE THREAD

**Issue by tscs37** [restic/restic#2473] opened 2019-11-18 05:39 UTC
Output of `restic version`
--------------------------

```
/ # restic version
restic 0.9.5 compiled with go1.12.4 on linux/amd64
/ # 
```

How did you run restic exactly?
-------------------------------

```
restic prune --no-cache --no-lock --limit-upload 5000 --limit-download 10000 --cache-dir /cache -vvvv
```

Run using a docker container with the --hostname flag on backups to supply the correct hostname.

Restic is not being run in parallel, the backup operation is entirely manual.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

I use a B2 Bucket to store the backup repository

Expected behavior
-----------------

Restic Prunes unneeded backups and files as well as doing a dedup. It does not use locks to block the repository.

Actual behavior
---------------

Restic fails partway into the process, failing to free over 5TB of data due to a "already locked" error. This occurs despite supplying the `--no-lock` flag and occurs regardless whether or not this flag is present. The repository becomes locked up until `restic unlock` is run to manually clear the locks.

```
counting files in repo,
building new index for repo,
[63:14:32] 100.00%  1661186 / 1661186 packs,
,
repository contains 1661186 packs (10662314 blobs) with 7.803 TiB,
processed 10662314 blobs: 844029 duplicate blobs, 280.468 GiB duplicate,
load all snapshots,
find data that is still in use for 3 snapshots,
[17:23:28] 100.00%  3 / 3 snapshots,
,
found 3228835 of 10662314 data blobs still in use, removing 7433479 blobs,
will remove 0 invalid files,
will delete 1152764 packs and rewrite 73168 packs, this frees 5.845 TiB,
[59:38:23] 100.00%  73168 / 73168 packs rewritten,
,
counting files in repo,
Fatal: unable to create lock in backend: repository is already locked exclusively by PID 1 on 4d5e617a29db by root (UID 0, GID 0),
lock was created at 2019-11-11 17:15:36 (152h40m7.829255086s ago),
storage ID 50eb6df7,
```

Steps to reproduce the behavior
-------------------------------

1. Create a large B2 Bucket backup repository
2. Run restic prune (the operation must take over 24 hours and a DSL line might be required)
3. Wait for the error to occur

Do you have any idea what may have caused this?
-----------------------------------------------

The exclusive lock restic creates during the operation is not properly deleted. This either occurs because B2 does not immediately delete the lock or because during the operation the internet connection is renewed multiple times (DSL internet connection) which prevents restic from properly cleaning up the locks.

Additionally this is caused by restic using locks when instructed not to create locks via `--no-lock`

Do you have an idea how to solve the issue?
-------------------------------------------

Restic should obey the `--no-lock` flag and not use locks during the prune operation.

Restic should recognize locks that is has created previously during the current operation and ignore them or try to remove these stale locks.

Restic might be failing the unlock silently in some situations, the unlock should verify if the lock was properly deleted and if not, retry the unlock and log this situation.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic makes me very happy to be able to run my backups, it's just getting expensive due to being unable to run prune.

**Comment by LasseMoench** [comment] 2019-11-19 18:28
I am seeing a (possibly) similar issue on arch linux with restic 0.9.5 when backing up onto a raspberry pi over my local network (so probably no latency / B2 related issue). I run a backup and then prune, and apparently locks wont get removed after that. I see a lot of error messages related to the lock removal:

```
Nov 19 03:58:47 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 551.989051ms: file does not exist
Nov 19 03:58:47 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 682.213708ms: file does not exist
Nov 19 03:58:48 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 595.880191ms: file does not exist
Nov 19 03:58:49 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 846.962821ms: file does not exist
Nov 19 03:58:49 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 1.272821447s: file does not exist
Nov 19 03:58:51 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 5.375696554s: file does not exist
Nov 19 03:58:56 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 6.206946257s: file does not exist
Nov 19 03:59:02 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 9.050356586s: file does not exist
Nov 19 03:59:11 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 16.856197904s: file does not exist
Nov 19 03:59:28 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 26.48770063s: file does not exist
Nov 19 03:59:55 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 479.221239ms: file does not exist
Nov 19 03:59:55 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 825.124197ms: file does not exist
Nov 19 03:59:56 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 592.048294ms: file does not exist
Nov 19 03:59:57 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 2.271092829s: file does not exist
Nov 19 03:59:59 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 1.897660915s: file does not exist
Nov 19 04:00:01 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 4.335212229s: file does not exist
Nov 19 04:00:05 gaspodelaptop .backup.sh[10059]: Remove(<lock/6a7949ff5f>) returned error, retrying after 4.257055915s: file does not exist
```
I have to run restic unlock before the next backup for it to work. This seems to happen during prune.

**Comment by rawtaz** [comment] 2019-11-19 20:07
@LasseMoench What backend are you using? When you are seeing those warnings over and over again, if you look in the filesystem on the Rpi, is the referenced lock file present or not?

**Comment by tscs37** [comment] 2019-11-19 20:39
I don't see any errors at all, even at highest verbosity levels, so it might not be related.

**Comment by LasseMoench** [comment] 2019-11-19 20:51
@rawtaz I am using sftp. I am running the backups automated at night, I will run one manually and check if the lock file is present. I don't think it's a permission issue as I didn't knowingly change anything on the pi or the system that is backed up. If the error is not related I should probably open an own issue or ask in the forums first. Sorry for hijacking this issue.

**Comment by rawtaz** [comment] 2019-11-25 02:44
@LasseMoench Have you had a time to investigate?

**Comment by LasseMoench** [comment] 2019-11-25 10:36
@rawtaz Unfortunately, I wasn't able to reproduce the error again. I assume it must have been due to a bad wifi connection or something. Will keep an eye on it.

**Comment by larsks** [comment] 2019-11-26 13:26
@rawtaz I was about to open a bug with the same title, but I guess I'll piggy back on here. I'm also backing up to a B2 backend, and I keep running into problems because restic leaves the repository locked. It looks like the `prune` operation is failing with a similar error to what was reported in [an earlier comment](https://github.com/restic/restic/issues/2473#issuecomment-555643752):


```
Nov 25 00:33:12 madhatter restic[428660]: counting files in repo
Nov 25 00:34:03 madhatter restic[428660]: building new index for repo
Nov 25 05:03:21 madhatter restic[428660]: [4:29:18] 100.00%  85854 / 85854 packs
Nov 25 05:03:21 madhatter restic[428660]: repository contains 85854 packs (4238029 blobs) with 392.499 GiB
Nov 25 05:03:23 madhatter restic[428660]: processed 4238029 blobs: 0 duplicate blobs, 0 B duplicate
Nov 25 05:03:23 madhatter restic[428660]: load all snapshots
Nov 25 05:03:23 madhatter restic[428660]: find data that is still in use for 17 snapshots
Nov 25 05:06:34 madhatter restic[428660]: [3:11] 100.00%  17 / 17 snapshots
Nov 25 05:06:34 madhatter restic[428660]: found 4121142 of 4238029 data blobs still in use, removing 116887 blobs
Nov 25 05:06:36 madhatter restic[428660]: will remove 0 invalid files
Nov 25 05:06:37 madhatter restic[428660]: will delete 722 packs and rewrite 2301 packs, this frees 8.067 GiB
Nov 25 06:39:17 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 534.530556ms: Delete: b2_delete_file_version: 400: File not present: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2 4_z78488d26a4ca42d865120817_f1014042240437c74_d20191125_m112807_c000_v0001028_t0002
Nov 25 06:40:11 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 880.427839ms: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:14 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 1.342133838s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:15 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 1.28514116s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:16 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 2.515434556s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:19 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 3.016929897s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:22 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 3.019006601s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:25 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 4.278851187s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:30 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 17.034979119s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:41:47 madhatter restic[428660]: Remove(<lock/c5e5dcf14b>) returned error, retrying after 25.410923677s: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2
Nov 25 06:42:13 madhatter restic[428660]: unable to refresh lock: Delete: b2_download_file_by_name: 404: bucket lars-backup-home does not have file: locks/c5e5dcf14b1600513e426a768e3d70dd648468c09284b39254b37d4f49cabac2

```

Those errors repeat for a total of around 700 lines. A subsequent `restic backup` job fails:

```
Nov 26 00:00:09 madhatter restic[530279]: Fatal: unable to create lock in backend: repository is already locked exclusively by PID 428660 on madhatter by restic (UID 1002, GID 1002)
Nov 26 00:00:09 madhatter restic[530279]: lock was created at 2019-11-25 00:33:06 (23h27m3.23684918s ago)
Nov 26 00:00:09 madhatter restic[530279]: storage ID 03bff2e0
```

And ultimately I have to manually `restic unlock` the repository.

**Comment by tscs37** [comment] 2019-11-26 13:29
I still think the lock files returning a 404 on the backend is an unrelated error since I don't see it on my end. But it might be related since my DSL connection is interrupted every 24 hours.

Possibly two changes could be made to fix this behaviour:
- When a lock deletion returns a 404, consider it completed but print a warning ("Warning: Lock deleted by other process")
- Keep a list of all locks created by the process, ignore the presence of these locks if they are improperly removed

To verify if this is a connection issue I'm currently running a prune operation from a dedicated server that has a permanent gigabit uplink.

**Comment by larsks** [comment] 2019-11-26 15:32
> When a lock deletion returns a 404, consider it completed but print a warning ("Warning: Lock deleted by other process")

I'm suspicious: restic is complaining about a lockfile not being found, but subsequent restic operations are failing because a lockfile exists. There isn't another operation running in parallel, so it's not like something else deleted the lock.

It seems like ignoring the 404 error in this situation would simply mask the problem, and we would still have the `Fatal: unable to create lock in backend:` errors in subsequent runs.

**Comment by tscs37** [comment] 2019-11-26 15:35
It's possibly because prune takes out multiple locks in my experience and when it comes time to delete them, a single missing lock causes everything to fail and if a single deletion does not properly complete, the operation also fails.

This can easily occur if the connection is not stable of Backblaze doesn't delete the file fast enough and restic still "sees" the deleted lock half a second later.

The real problem is that restic crashes hard in this case, leaving a locked repository because it couldn't remove a lock; it should attempt to cleanup all remaining locks.

**Comment by larsks** [comment] 2019-11-26 15:45
I wonder if accessing b2 via rclone rather than natively would avoid this particular problem?

**Comment by tscs37** [comment] 2019-11-26 15:54
I'm still testing if an uninterrupted connection experiences the same problem or if it is related to B2 and very large repositories (after all it's +6TB). ETA will be around 2-4 days at the current time.

**Comment by tscs37** [comment] 2019-12-13 05:00
The prune has completed without error using a dedicated server. The problem is therefore most likely the connection being interrupted around midnight.

So, restic might have to include an option to deal with DSL connections and large repos, it seems that the best option there might be to handle keys better since that seems to be where the primary problem lies in my case.

**Comment by bzed** [comment] 2020-02-10 08:13
I've seen this issue on my VMs during the last nights, so it might not be a DSL issue. But even with a good connection, pruning takes way too long on B2.

**Comment by aawsome** [comment] 2020-02-18 15:17
If prune speed is an issue, you may want to try out #2340 or #2513

**Comment by tscs37** [comment] 2020-02-18 16:38
even if prune is being speed up, this would hide the issue, not fix it, so it would only be a matter of time until it surfaces again. the issue itself is not speed itself, I'm fine if it runs slow, it's that it's some combination of "runs a long time" and "home connection" causes prune to fail.

**Comment by bzed** [comment] 2020-02-19 11:55
But those are two different issues.  Home connection issues can happen during all operations, that's nothing that should be fixed for pruning only.

**Comment by tscs37** [comment] 2020-02-19 12:03
If the prune operation takes longer than 24 hours then there is no way for it to run correctly. Almost all other operations will cleanly handle it, including creating a backup, which can be "resumed" after the interruption as already uploaded data isn't uploaded again and restores can be spliced into small directories.

Keep in mind that Prune took almost 17 days to complete for me (>400 hours) so unless the optimizations in the linked issue can improve on prune runtimes by two orders of magnitudes, it's not going to solve the underlying issue for the amount of data I back up. If prune takes longer than 24 hours then it's impossible to circumvent the issue, and the runtime would have to be below 10 hours as I cannot start a prune during any time of the day.

**Comment by aawsome** [comment] 2020-02-19 19:19
Sorry I didn't want to spoil this issue and speed issues with prune should be discussed e.g. in #2513 (added a comment there for @tscs37)

**Comment by vespian** [comment] 2020-03-05 20:33
> I wonder if accessing b2 via rclone rather than natively would avoid this particular problem?

FWIW I switched recently from native B2 client to `rclone` and noticed that Backblaze is occasionally returning `is too busy` errors. I wonder if it is related to this issue. I have not seen it while using native client but I did see the 404s described in this issue.

```
Mar 05 21:11:54 budrys.engel.vespian.net system_backup.sh[18509]: Save(<data/ec2bb61d46>) returned error, retrying after 282.818509ms: server response unexpected: 500 Internal Server Error (500)
Mar 05 21:11:54 budrys.engel.vespian.net system_backup.sh[18501]: <13>Mar  5 21:11:54 system_backup.sh: Save(<data/ec2bb61d46>) returned error, retrying after 282.818509ms: server response unexpected: 500 Internal Server Error (500)
Mar 05 21:15:41 budrys.engel.vespian.net system_backup.sh[18509]: rclone: 2020/03/05 21:15:41 ERROR : data/e1/e1bdbde6451d5b4e8ae13bf8564be1ff6c3d1485d0f158f2a5ab38048d2a85b2: Post request put error: c002_v0001133_t0029 is too busy (503 service_unavailable)
Mar 05 21:15:41 budrys.engel.vespian.net system_backup.sh[18501]: <13>Mar  5 21:15:41 system_backup.sh: rclone: 2020/03/05 21:15:41 ERROR : data/e1/e1bdbde6451d5b4e8ae13bf8564be1ff6c3d1485d0f158f2a5ab38048d2a85b2: Post request put error: c002_v0001133_t0029 is too busy (503 service_unavailable)
Mar 05 21:15:42 budrys.engel.vespian.net system_backup.sh[18509]: rclone: 2020/03/05 21:15:42 ERROR : data/e1/e1bdbde6451d5b4e8ae13bf8564be1ff6c3d1485d0f158f2a5ab38048d2a85b2: Post request rcat error: c002_v0001133_t0029 is too busy (503 service_unavailable)
Mar 05 21:15:42 budrys.engel.vespian.net system_backup.sh[18501]: <13>Mar  5 21:15:42 system_backup.sh: rclone: 2020/03/05 21:15:42 ERROR : data/e1/e1bdbde6451d5b4e8ae13bf8564be1ff6c3d1485d0f158f2a5ab38048d2a85b2: Post request rcat error: c002_v0001133_t0029 is too busy (503 service_unavailable)
Mar 05 21:15:55 budrys.engel.vespian.net system_backup.sh[18509]: Save(<data/e1bdbde645>) returned error, retrying after 328.259627ms: server response unexpected: 500 Internal Server Error (500)
Mar 05 21:15:55 budrys.engel.vespian.net system_backup.sh[18501]: <13>Mar  5 21:15:55 system_backup.sh: Save(<data/e1bdbde645>) returned error, retrying after 328.259627ms: server response unexpected: 500 Internal Server Error (500)
```

**Comment by MichaelEischer** [comment] 2020-04-12 22:46
@tscs37 Is the log output containing "Fatal: unable to create lock in backend" the result of a single or multiple commands? After looking a while at the code, I don't see any way how restic could create that output in a single command run. From what I can tell that error message can _only_ be returned by `lockRepoExclusive` or `lockRepo`. However, that function is only ever called when restic begins the execution of a command.  The second `counting files in repo` output looks like it comes from the call to `rebuildIndex` in prune, but that function does not lock the repository again. The fatal error message can also not be the result of a failed lock refresh as that would lead to different error messages. The timestamps in the log output also miss 12 hours, and I hope that B2 didn't take that long to list all files in the repository.

@larsks The `unable to refresh lock` problem you see is rather easy to explain: The lock file removal fails with `400 file_not_present` but actually the file was removed successfully. However, that causes the lock refresh code, to fail permanently as the `lockID` is never updated to the new file and the old lock was already removed.
https://github.com/restic/restic/blob/3ee6b8ec63f661bf97828c066cf777e58ff97357/internal/restic/lock.go#L232-L236

This could be partially solved by #2596 (which would essentially let restic ignore the 404 error) but the locking code should also handle this situation much better. It would be a good idea if restic doesn't flood the backend with lock files.

@vespian 500/503 HTTP status codes (or actually every `5xx` status code) say that there is a problem on the server side for which the client is not responsible.

**Comment by tscs37** [comment] 2020-04-13 19:09
The "Fatal: unable to create lock in backend" is the result of a single run, even after removing all locks from the bucket manually and waiting a day as well as clearing the local cache to ensure there is no possible way that multiple locks are held. B2 does not take that long to list all files but processing all files in the repository on the local end did require that amount of time. That didn't change when I ran it on a remote server with a gigabit uplink. The timestamp of the lock coincides with the time I started the command (152 hours).

**Comment by MichaelEischer** [comment] 2020-04-15 20:04
@tsc37 Do you have another log with the failed prune operation (just noticed the "repeatedly" in the bug title)? I took another look at the restic source code and couldn't find _any_ way through the code which would generate your log output with just a single call to `prune`. Running both `prune` and another restic command could generate the log output, but for a single `prune` call it should be impossible.

Is there a reason why you pass both `--no-cache` and `--cache-dir`?

**Comment by tscs37** [comment] 2020-04-15 20:07
It was a temporary change to test if cache affected the entire thing, I usually run with cache.

I don't have any more logs, I don't run prune very often and at the moment the repository has shrunk in size enough that the issue disappeared. It did occur in the same fashion reproducibly in the original sized repo.

**Comment by aksingh11** [comment] 2020-10-06 11:20
same problem with the b2 repository . 

issue solved by generating new master application keys at b2

**Comment by MichaelEischer** [comment] 2020-10-07 11:56
@aksingh11 Can you explain a bit more and post a log of the actual error messages? Which restic version do you use? Right now this issue contains error logs with 3 or 4 different root causes.

**Closed** 2022-03-21 10:10 UTC
Labels: category: prune, state: need triaging
