### ISSUE TITLE
scan: CreateFile \\?\\con: The parameter is incorrect.

### ISSUE THREAD

**Issue by rjuliasim** [restic/restic#2723] opened 2020-05-10 12:14 UTC
Hello, 
I just started using restic (version 0.9.6) on Windows 10.
During my initial backup and during any further backup I get the following messages: 

scan: CreateFile \\\\?\\\\con: The parameter is incorrect.
scan: CreateFile \\\\?\\\\con: The parameter is incorrect.
scan: CreateFile \\\\?\\\\con: The parameter is incorrect.
scan: CreateFile \\\\?\\\\con: The parameter is incorrect.

and

error: CreateFile \\\\?\\\\con: The parameter is incorrect.
error: CreateFile \\\\?\\\\con: The parameter is incorrect.
error: CreateFile \\\\?\\\\con: The parameter is incorrect.
error: CreateFile \\\\?\\\\con: The parameter is incorrect.

Speculation: It may be that I have 4 files with "strange" filenames, if I interpret \\\\?\\\\con as escape sequences. But how do I get the full path of theses files? So I can rename the files.

Any suggestions?

**Comment by rawtaz** [comment] 2020-05-10 13:53
@rjuliasim I don't mean to be harsh, but you made three obvious mistakes here:

1. You didn't post this in the forum, as requested when you opened the issue (if it's not a bug report or a feature suggestion, you are asked to instead post it in the forum).

1. You did not fill out the issue template that you were presented with when opening this issue (the questions).

1. You did not even supply the command you used to run the backup.

For these reasons I will close this issue. We try our best to be helpful, but if you don't even take the time to read the information you are presented with when opening an issue we will focus on posts and issues that do provide the information we kindly ask for. The instructions are there for very good reasons, believe it or not ;)

I would recommend that you post in [the forum](https://forum.restic.net/), and when you do that make sure to include all relevant information. Thanks!

**Closed by rawtaz** 2020-05-10 13:53 UTC

**Comment by rjuliasim** [comment] 2020-05-11 08:28
Dear @rawtaz,

you are right closing this.
I somehow misinterpreted on
https://restic.net/
under "Contact"  the sentence
"If you discover a bug or find something surprising, please feel free to open
a github issue <https://github.com/restic/restic/issues/new>."
as you, better the restic project, would use github issues as a sort of a
forum. I just followed the link
in the above cited sentence.
I didn't know/realize that you had a separate forum at
https://forum.restic.net/

Sorry, my fault

rjuliasim
