### ISSUE TITLE
Unexpected behaviour when using -one-file-system

### ISSUE THREAD

**Issue by xSWIGx** [restic/restic#1416] opened 2017-11-05 19:07 UTC
## Output of `restic version`
```
root@Server:~# restic version
restic 0.7.3
compiled with go1.9 on linux/amd64
```

## How did you run restic exactly?
`restic -r /mnt/backup/ backup --one-file-system / /mnt/storage/ --exclude "/mnt/files"`

## What backend/server/service did you use?
Filesystem

## Expected behavior
I would like filesystem snapshot with:
1) `/` -  root filesystem without sys, dev, etc...
2) `/mnt/storage` - this **mounted** filesystem on its own place

## Actual behavior
What i have:
1) `/ `-  root filesystem without sys, dev, etc...
2) `/mnt/storage` - this **mounted** filesystem on its own place
3) `/storage` - this folder contain all duplicated files from /mnt/storage

## Steps to reproduce the behavior
1) Use `restic -r /mnt/backup/ backup --one-file-system / /mnt/storage/ --exclude "/mnt/files"` to make backup snapshot.
2) Use `restic -r /mnt/backup/ mount /mnt/restic/` then check `/mnt/restic/snapshots/<snapshot_name>/`. This will contain both `/mnt/storage` and `/storage`
OR
Use `restic -r /mnt/backup/ restore latest --target /tmp/restore --path "/"` then check `/tmp/restore` for `/mnt/storage` and `/storage`.

**Comment by fd0** [comment] 2017-11-05 19:58
Thanks for reporting this issue. It's not specific to `--one-file-system`, but rather how the archiving code works at the moment, it's a duplicate of #549 (please see over there for a more in-depth description). I'm going to close this issue as a duplicate, please subscribe over at #549 for progress information.

**Closed by fd0** 2017-11-05 19:58 UTC

**Comment by fd0** [comment] 2017-11-05 20:02
As a workaround, you can run `restic backup --exclude-file ~/.restic-exclude /` and exclude all mounted dirs that shouldn't be in the backup manually, this is described here in a bit more detail: https://forum.restic.net/t/full-system-restore/126/8?u=fd0
