### ISSUE TITLE
Restic prune wont work if the hard drive is almost full

### ISSUE THREAD

**Issue by AlertSubject** [restic/restic#3724] opened 2022-04-28 12:51 UTC
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on windows/amd64

How did you run restic exactly?
--------------------------

PS H:\Backup> restic -r H:\Backup prune
enter password for repository:
repository dcde14a8 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 1 snapshots
[1:34] 100.00%  1 / 1 snapshots
searching used packs...
collecting packs for deletion and repacking
[5:43] 100.00%  787565 / 787565 packs processed

to repack:        34164 blobs / 278.468 MiB
this removes        294 blobs / 22.843 MiB
to delete:       124233 blobs / 155.654 GiB
total prune:     124527 blobs / 155.676 GiB
remaining:      3797474 blobs / 3.483 TiB
unused size after prune: 23.257 GiB (0.65% of remaining size)

deleting unreferenced packs
[0:04] 100.00%  40 / 40 files deleted
repacking packs
Save(<data/bb928909bb>) returned error, retrying after 552.330144ms: write \\?\H:\Backup\data\bb\bb928909bb0516ff532c16c5e5fa6d05cc9752cd27cfebd747183491e567745c: There is not enough space on the disk.
Save(<data/2dc4bb2994>) returned error, retrying after 720.254544ms: write \\?\H:\Backup\data\2d\2dc4bb299473b6af5e2078ebd7f19a438ad2b12e84d3db49d23fbf7b1a31d489: There is not enough space on the disk.
Save(<data/69fdb1ae19>) returned error, retrying after 582.280027ms: write \\?\H:\Backup\data\69\69fdb1ae196bc356d9ef40c80316d23e94998d9acc231a5ca58d89b081efc00a: There is not enough space on the disk.
Save(<data/6773ed1e94>) returned error, retrying after 468.857094ms: write \\?\H:\Backup\data\67\6773ed1e949ca71f60a4db6bde8d03033f30acd1929e23a6d1d2817dcd8b7f38: There is not enough space on the disk.
Save(<data/0f04382218>) returned error, retrying after 462.318748ms: write \\?\H:\Backup\data\0f\0f04382218b87de8884bd569ac436657a00c32137c97ebe8cb8fcfb8f43fadc3: There is not enough space on the disk.
Save(<data/64b1e71bce>) returned error, retrying after 593.411537ms: write \\?\H:\Backup\data\64\64b1e71bcecd343ae5c4c5de4e1a2a6a7ee4ca4680e2c099b91e38267d4480cd: There is not enough space on the disk.
Save(<data/fb5a0b4d08>) returned error, retrying after 282.818509ms: write \\?\H:\Backup\data\fb\fb5a0b4d089c777a507ac88e7d1451cacb156ca276e2beed7131529c8d35e3eb: There is not enough space on the disk.
Save(<data/0f04382218>) returned error, retrying after 492.389441ms: write \\?\H:\Backup\data\0f\0f04382218b87de8884bd569ac436657a00c32137c97ebe8cb8fcfb8f43fadc3: There is not enough space on the disk.
Save(<data/2dc4bb2994>) returned error, retrying after 447.727139ms: write \\?\H:\Backup\data\2d\2dc4bb299473b6af5e2078ebd7f19a438ad2b12e84d3db49d23fbf7b1a31d489: There is not enough space on the disk.
Save(<data/6773ed1e94>) returned error, retrying after 600.683895ms: write \\?\H:\Backup\data\67\6773ed1e949ca71f60a4db6bde8d03033f30acd1929e23a6d1d2817dcd8b7f38: There is not enough space on the disk.
Save(<data/64b1e71bce>) returned error, retrying after 761.409471ms: write \\?\H:\Backup\data\64\64b1e71bcecd343ae5c4c5de4e1a2a6a7ee4ca4680e2c099b91e38267d4480cd: There is not enough space on the disk.
Save(<data/a1dd406d53>) returned error, retrying after 656.819981ms: write \\?\H:\Backup\data\a1\a1dd406d5305fbe4d3be831f2a1c30f5eb7d7a29725b5b0d9903701e5671361b: There is not enough space on the disk.
Save(<data/69fdb1ae19>) returned error, retrying after 535.697904ms: write \\?\H:\Backup\data\69\69fdb1ae196bc356d9ef40c80316d23e94998d9acc231a5ca58d89b081efc00a: There is not enough space on the disk.
signal interrupt received, cleaning up
PS H:\Backup>

What backend/server/service did you use to store the repository?
--------------------------
A USB hard drive 

Expected behavior
-----------------

Restic should free up hard drive space by getting rid of unused data from the 3 snapshots that I used to 'forget' command on

Actual behavior
---------------

Restic says it cant complete the action because there isn't enough space on the disk

Steps to reproduce the behavior
-------------------------------

Have a hard drive with a few gigs of free storage left
start a new restic backup that would use up more storage than is available
-> Now the drive only has a few kilobyte of free storage left
start forgetting old snapshots
run the prune command
be sad because it didnt free up any storage and instead failed to run

Do you have any idea what may have caused this?
-----------------------------------------------
no free storage left to repack (?)

Do you have an idea how to solve the issue?
-------------------------------------------
programming magic that I dont understand

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I love using restic for my backups ever since a friend introduced me to it
And its rather easy to understand and use, even without any special knowledge. Thanks to the docs :)

**Comment by MichaelEischer** [comment] 2022-04-30 17:25
This is a duplicate of #1153. To solve your problem you'll probably have to use #3481 (assuming that you have less free space than the size of the `index/` folder)

**Closed** 2022-04-30 17:25 UTC
