### ISSUE TITLE
Progress for restore operation

### ISSUE THREAD

**Issue by gnottgen** [restic/restic#3627] opened 2022-01-09 20:15 UTC
Output of `restic version`
--------------------------

restic 0.12.1 compiled with go1.16.6 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I would apreciate if the restore command would show a progress of the operation. Very nice would be a percentage of the remaining size (maybe with an ETA), but already the current file in progress would do the trick.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I tried a restore (just for testing) of a big repository and wondered if restic is still working or if it is hanging, because there was no output at all (after the initial information about the snapshot to restore, of course).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Though I didn't had to do a restore until now (and hopingly I never will have to), it seems to be an excellent backup tool for me. It's great to use in scripts and my backup and the backup of several PCs of my family are relying on restic. 
I'm running it through a PowerShell-script on windows-machines pushing to a linux machine via sftp and it works like charm. Also the repo's integrity check is a great tool to use before mirroring the repo to an out-of-house-machine.
Thank you very much for restic! (i tried to donate, but i only found #884 and #2415 which unfortunately are saying that it's not easily possible) But it makes me happy every time i'm doing a backup ;-)

**Comment by dimejo** [comment] 2022-01-09 20:40
Sounds like a duplicate of #426.

**Comment by MichaelEischer** [comment] 2022-01-12 19:14
It is.

**Closed by MichaelEischer** 2022-01-12 19:14 UTC
