### ISSUE TITLE
Prune fails when drive is full

### ISSUE THREAD

**Issue by holzvvorm** [restic/restic#3289] opened 2021-02-19 14:50 UTC
Recently a backup couldn't be finished because my drive ran out of free space. After deleting some snapshots and trying to prune them the prune command failed probably because of no available space.
Sadly I didn't document the error sufficiently, I don't even know what the error-message said exactly. I fixed the issue by enlarging the partition.

**Comment by rawtaz** [comment] 2021-02-19 15:17
Hi,

Glad to hear the problem was fixed. As this isn't a bug report or similar (it's not unexpected that prune can't do its work if you don't have any space left for it, although you could try using the options to the prune command to control how much space it needs to do said work), it would be better to post this in the forum next time.

I'm closing this as the problem is solved :+1:

**Closed by rawtaz** 2021-02-19 15:17 UTC

**Comment by holzvvorm** [comment] 2021-02-19 15:19
Okay, I thought this might be a bug, but it makes sense that prune needs some space to repack stuff or something like that.

**Comment by dimejo** [comment] 2021-02-19 16:09
Which version of restic are you using? Prune has been reworked in the latest version (v0.12.0) and AFAIK it now deletes unused packs (freeing some space) first before doing any rewrites.

**Comment by holzvvorm** [comment] 2021-02-20 16:53
@dimejo That sounds good. I think this happened a week before I upgraded to v0.12.0, so I'll hopefully be fine in the future. Thanks!
