### ISSUE TITLE
performance regression with new archiver code

### ISSUE THREAD

**Issue by tk7r** [restic/restic#1753] opened 2018-05-02 05:51 UTC
## Output of restic 0.8.3 - compiled with go1.10 on darwin/amd64

password is correct
using parent snapshot 41fe8ca6
scan [/Users/thomasko]
scanned 203642 directories, 923001 files in 1:40
[2:50] 100.00%  350.991 GiB / 350.988 GiB  1126648 / 1126643 items  1 errors  ETA 0:00 
duration: 2:50
snapshot 84d57f41 saved
      281.77 real       317.25 user       169.60 sys

## Output of restic 0.8.3 (v0.8.3-217-g8026e6fd) compiled with go1.10.1 on darwin/amd64

[59:00] 36.97%  473781 files 129.896 GiB, total 922319 files 351.322 GiB, 3 errors ETA 1:40:34
[1:41:27] 94.40%  693174 files 331.637 GiB, total 922319 files 351.322 GiB, 18 errors ETA 6:01
[2:11:05] 99.63%  917467 files 350.037 GiB, total 922319 files 351.322 GiB, 18 errors ETA 0:28
     8045.00 real      2588.35 user       588.89 sys

## How did you run restic exactly? 

i run these commands on an existing repository.

/usr/bin/time restic backup --hostname patmos \
--exclude '.DS_Store' \
--exclude '/Users/thomasko/Library/Caches/' \
--exclude '/Users/thomasko/Library/Developer/' \
--exclude '/Users/thomasko/Library/Mail/' \
--exclude '/Users/thomasko/Library/Logs/' \
--exclude '/Users/thomasko/\.npm/'  \
--exclude '/Users/thomasko/\.sonar/' \
--exclude '/Users/thomasko/\.m2/repository/' \
--exclude '/Users/thomasko/\.gradle/caches/' \
--exclude '/Users/thomasko/\.gradle/daemon/' \
--exclude '/Users/thomasko/\.gradle/wrapper/' \
--exclude '/Users/thomasko/\.gradle/native/' \
--exclude '/Users/thomasko/.cache/' \
/Users/thomasko

## What backend/server/service did you use to store the repository?

the repository is on a local server. S3 (minio) - both executions 0.8.3 and 0.8.3-217 (compiled from master) ran with the same repository.

## Expected behavior

run as fast as before

## Actual behavior

runs slower 

## Steps to reproduce the behavior

run restic against an existing repository.

## Do you have any idea what may have caused this?

i ran restic-0.8.3-release, restic-v0.8.3-191-g6d4c40f8 and restic-v0.8.3-217-g8026e6fd but i only have the above output available. - i ran the backups multiple times to exclude a possible server slowdown causing this behaviour. but the only difference (repository server, network, backup source, running programs at the time of backup, ...) was the restic version.

## Do you have an idea how to solve the issue?

maybe printing the filename during backup causes the performance problem?

**Comment by tk7r** [comment] 2018-05-02 07:38
## Output of restic 0.8.3 (v0.8.3-221-g26757ae2) compiled with go1.10.2 on darwin/amd64

repository 7e5130b9 opened successfully, password is correct

Files:         245 new,   664 changed, 921454 unmodified
Dirs:            0 new,     1 changed,     0 unmodified
Added:      556.837 MiB

processed 922363 files, 351.563 GiB in 1:21:47
snapshot 3a0895a0 saved
     4907.81 real       309.80 user       281.43 sys

## Observation

Maybe only the first run of the new archiver code causes a slowdown because of the file metadata rewrite - so i did a second run with the new-archiver code. The slowdown here is not as bad as the first run but still "extremely noticable"...

**Comment by fd0** [comment] 2018-05-02 14:30
Hey, thanks for the report! What hardware is that? It sounds like a potent OS X machine with a fast SSD, is that the case?

> Maybe only the first run of the new archiver code causes a slowdown because of the file metadata rewrite - so i did a second run with the new-archiver code. The slowdown here is not as bad as the first run but still "extremely noticable"...

You're right in your analysis: The first backup with the new archiver code re-reads everything, which explains the runtime. This is due to #549 being resolved, and the directory structure within the snapshot will therefore be different.

You can test your theory with the status output by running `restic backup [...] | cat`. When stdout is piped into `cat`, restic detects that it does not have a terminal, and will not print any status display.

Also, what's different to the old archiver code: We're using **much** less concurrent file access. By default, only two files are read in parallel, according to our experiments this seems to be the sweet spot for most machines. If you like to try different values, you can change it here: https://github.com/restic/restic/blob/26757ae2e53e17b75f98c9bc9c74d343ea226b6d/internal/archiver/archiver.go#L98-L113

Please report back!

**Comment by tk7r** [comment] 2018-05-03 11:58
Sorry for the late reply - testing took a while

## summary

no significant differences in performance ... results below.
machine: MacBook Pro (latest model with Core i7 and 1TB SSD, APFS encrypted)

## result: pipe output to 'cat'

restic backup | cat ...
5141.78 real       331.37 user       279.78 sys

## result: concurrent set to 4

restic 0.8.3 (v0.8.3-223-g2a672588-dirty) compiled with go1.10.2 on darwin/amd64

repository 7e5130b9 opened successfully, password is correct

Files:          61 new,   368 changed, 921962 unmodified
Dirs:            0 new,     1 changed,     0 unmodified
Added:      287.575 MiB

processed 922391 files, 351.995 GiB in 1:25:05
snapshot cd9ad2d7 saved
     5106.11 real       308.92 user       278.84 sys

## result: concurrent set to 16

restic 0.8.3 (v0.8.3-223-g2a672588-dirty) compiled with go1.10.2 on darwin/amd64

repository 7e5130b9 opened successfully, password is correct

Files:        2667 new,   784 changed, 921584 unmodified
Dirs:            0 new,     1 changed,     0 unmodified
Added:      184.121 MiB

processed 925035 files, 352.036 GiB in 1:27:01
snapshot 222abb7b saved
     5222.08 real       307.56 user       275.67 sys

**Comment by fd0** [comment] 2018-05-03 19:08
Hm, interesting. The stats at the end say that it does not re-read all the data. So where does it spend so much time?

Did you maybe disable the local cache? Can you maybe try a backup with 0.8.3 again, to see if it still fast? (maybe you need to run two, because the first one may be very slow again, it may be re-read all local files)...

One thing you could try is building restic with the `profile` tag, `go run build.go --tags profile`, and then running it like this to write a CPU profile:
```
$ ./restic --cpu-profile . backup [...]
```

It'll then write a file `cpu.pprof` into the current directory. Maybe also do that with a so-called "block profile", via `--block-profile .`. You can then upload the files (there's nothing secret in them, just timing information and symbols from the program) somewhere for me to look at.

Another idea would be to find a small subset (maybe one directory or so) of your data that's fast archiving with 0.8.3, and much slower with the current master code. Then we could run with `backup -v -v` and maybe write a debug log (`go run build.go -tags debug`, then `DEBUG_LOG=log ./restic backup [...]`).

I don't have any more ideas right now :)

Thanks!

**Comment by tk7r** [comment] 2018-05-03 19:50
a quick feedback:
- i haven't explicitly disabled the cache (please see the restic call from my first posting)
- my first take is running the new-archiver profilings
- after that i will run plain 0.8.3 multiple times
it will take a little time

**Comment by fd0** [comment] 2018-05-03 20:10
Great, thank you very much for your time and patience :)

I'm eager to find out what's going on here.

**Comment by fd0** [comment] 2018-05-05 11:08
Hm, the profiles unfortunately don't tell me anything. The CPU profile shows that it spent just about 320 seconds CPU time overall, which matches with the output of `time` you got. So it must be something else than CPU usage.

I have a different idea: Maybe your directory is structured in a way which triggers a very odd corner case I didn't foresee when rewriting the archiver. Can you paste a rough structure (e.g. the output of `tree`) somwhere, maybe obfuscated file/dir names?

Do you have **tons** of files in a single directory? Or a very deep directory structure?

**Comment by tk7r** [comment] 2018-05-05 19:56
## debug log

i have created a debug log, but it contains all (sensitive) file names ... i don't want to upload it publicly. But i have collected some more information fragments...

## distribution chart of directory depth in backup set

occurence   depth
   60 /                               1
  414 //                              2
 2353 ///                             3
 4559 ////                            4
15392 /////                           5
30170 //////                          6
30289 ///////                         7
59849 ////////                        8
55796 /////////                       9
20075 //////////                     10
22863 ///////////                    11
33963 ////////////                   12
32604 /////////////                  13
11369 //////////////                 14
 4930 ///////////////                15
 3747 ////////////////               16
 5005 /////////////////              17
 1158 //////////////////             18
  646 ///////////////////            19
  127 ////////////////////           20
   89 /////////////////////          21
   21 //////////////////////         22
   10 ///////////////////////        23

so i think its deeply nested ... - when i back up my mailserver there are many more files in a single directory - so that's also a scenario i have.

## first run of restic 0.8.3-release

using parent snapshot 110aa9c6
scan [/Users/thomasko]
scanned 207499 directories, 932817 files in 1:49
error for thomasko/Library/Preferences/com.apple.AddressBook.plist.y5sJ9tb: Lstat: lstat /Users/thomasko/Library/Preferences/com.apple.AddressBook.plist.y5sJ9tb: no such file or directory
error for thomasko/cpu.pprof: Lstat: lstat /Users/thomasko/cpu.pprof: no such file or directory
warning for /Users/thomasko/restic-stable-firstrun.cast: file has changed
warning for /Users/thomasko/restic-stable-firstrun.cast: expected 23399135 bytes, saved 23399860 bytes
[1:15:01] 100.00%  351.792 GiB / 351.774 GiB  1140324 / 1140316 items  2 errors  ETA 0:00
duration: 1:15:01
snapshot 2be02880 saved
     4625.49 real      4199.42 user       641.53 sys

the first run is slow ... that was clear.

## second run of restic 0.8.3-release

using parent snapshot 2be02880
scan [/Users/thomasko]
scanned 207498 directories, 932825 files in 2:04
warning for /Users/thomasko/restic-stable-secondrun.cast: file has changed
warning for /Users/thomasko/restic-stable-secondrun.cast: expected 1857442 bytes, saved 1857672 bytes
[4:14] 100.00%  351.801 GiB / 351.799 GiB  1140323 / 1140323 items  0 errors  ETA 0:00
duration: 4:14
snapshot a7279208 saved
      396.06 real       375.05 user       196.19 sys

the second run took only a little over 4 minutes for processing 930.000 files!

## wild guess

the interesting part about this is that all new-archiver-backups took nearly about as much time as the first run of 0.8.3-release. i haven't looked at the code but could it be that 0.8.3-release uses the cache on its second run(s) and new-archiver not?

## screencasts

i have attached the 3 asciinema screen casts:
1. restic-new-archiver.cast (run of new archiver code) - slow, so i only recorded the first 7 minutes; progressed to about 0,5 % finished.
2. restic-stable-firstrun.cast - slow
3. restic-stable-secondrun.cast - fast (again)
(you can run it with 'asciinema play ....cast' to get a live impression of the performance degradation)

[screencasts.zip](https://github.com/restic/restic/files/1977021/screencasts.zip)

**Comment by fd0** [comment] 2018-05-05 20:50
Hm. Random observations:

 * The first run with stable spends 4200s (almost the complete run time of the process) in user mode, which means that it uses a lot of CPU. That's expected: it's hashing/encrypting all the data.

 * The second run with stable is short, still almost all time is spent in user mode, probably decrypting/comparing files

 * For a subsequent run with the new archiver code, it spends time somewhere else, not in user and not in kernel mode. It could be blocked by syscalls, or it could be waiting on something. We need to find out what that is.

**Comment by fd0** [comment] 2018-05-05 20:56
Oh, I have a suspicion, would you mind running the new archiver code again with this patch applied? https://gist.github.com/0832a521b20837a6fc34a5b0549cc996

**Comment by fd0** [comment] 2018-05-05 21:01
And please run it with `strace -c -e getdents64` :)

**Comment by fd0** [comment] 2018-05-05 21:17
Ok, scratch the `strace`, that'll just falsify the measurements (and won't work on darwin out of the box anyway).

**Comment by fd0** [comment] 2018-05-06 10:02
Can you please confirm that the restic binary you compiled (the one which has the performance regression) was built **without** the `debug` tag?

**Comment by tk7r** [comment] 2018-05-06 15:46
## first run of new-archiver without tags (again)

repository 7e5130b9 opened successfully, password is correct

Files:       924071 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added:      53.763 MiB

processed 924071 files, 351.800 GiB in 2:16:13
snapshot 628a3713 saved
     8174.72 real      2445.02 user       592.21 sys

## next run of new-archiver without tags

(with quiet)

5012.34 real       299.37 user       308.51 sys

## run new-archiver without tags including patch

repository 7e5130b9 opened successfully, password is correct

Files:           9 new,   431 changed, 920748 unmodified
Dirs:            0 new,     1 changed,     0 unmodified
Added:      76.497 MiB

processed 921188 files, 351.492 GiB in 1:22:19
snapshot ca3153f2 saved
time spent in readdirnames(): 13.313692311s
     4940.35 real       301.78 user       300.43 sys

**Comment by fd0** [comment] 2018-05-06 17:34
Hm, very odd. I don't have any idea what's going on here...

**Comment by tk7r** [comment] 2018-05-07 11:46
wild guess - i stumbled over a performance regression in go 1.10 (https://github.com/golang/go/issues/24078) - maybe there are such effects in go 1.10.2 too...
To get some evidence i re-compile 0.8.3 myself with go 1.10.2 and run the tests. That evidence may not conclusive because the new-archiver code works differently and triggers other effects - i will try to run benchmarks with my data on freebsd (0.8.3 & new-archiver branches).

**Comment by fd0** [comment] 2018-05-07 12:16
Another idea would be to compile and test the new archiver code with Go 1.9

**Comment by tk7r** [comment] 2018-05-07 16:05
i ran 0.8.3-release - recompiled with go1.10.2 - that thing is even faster that the 0.8.3-release using go 1.10!

## firstrun (slow - expected)
password is correct
using parent snapshot ca3153f2
scan [/Users/thomasko]
scanned 206072 directories, 929769 files in 3:16
[1:22:53] 100.00%  351.372 GiB / 351.372 GiB  1135840 / 1135841 items  0 errors  ETA 0:00 
duration: 1:22:53
snapshot d5d5c339 saved
     5199.23 real      4322.91 user       682.33 sys

## secondrun over vpn (official build runs in 4:14 on local network!!!)
password is correct
using parent snapshot d5d5c339
scan [/Users/thomasko]
scanned 206072 directories, 929760 files in 1:51
[2:44] 100.00%  351.379 GiB / 351.379 GiB  1135833 / 1135832 items  0 errors  ETA 0:00 
duration: 2:44
snapshot 35663b66 saved
      289.06 real       305.34 user       163.90 sys

**Comment by fd0** [comment] 2018-05-07 18:44
> i ran 0.8.3-release - recompiled with go1.10.2 - that thing is even faster that the 0.8.3-release using go 1.10!

New Go releases usually improve the speed :)

**Comment by tk7r** [comment] 2018-05-07 23:48
i ran tests with 0.8.3-stable and new-archiver on freebsd. Data is exactly the same as with all previous backups, but now run on freebsd.

test sequence:
1. repo A - restic 0.8.3 - first run
2. repo A - restic 0.8.3 - second run
3. repo B - restic-new-archiver - first run
4. repo B - restic-new-archiver - second run
5. repo A - restic-new-archiver - first run
6. repo A - restic-new-archiver - second run

freebsd performs well in contrast to macosx (all the previous tests) with all the same data. new-archiver on freebsd shows both filename output lines changing during the backup process. on macosx the second line barely changes. the runtime implementation seems to be different on macosx somehow...


# ./restic_backup_newarchiver
* restic init
Fatal: create key in repository at s3:http://archive1.home.intra:9000/restic.tests failed: repository master key and config already initialized

* restic backup
repository 62fd6200 opened successfully, password is correct

Files:           0 new,     0 changed, 914483 unmodified
Dirs:            0 new,     0 changed,     4 unmodified
Added:      0 B  

processed 914483 files, 351.127 GiB in 8:11
snapshot 1c5b59d7 saved
      491,85 real       701,27 user       231,04 sys

**Comment by tk7r** [comment] 2018-05-07 23:50
## ./restic_backup_stable

* restic init
created restic repository 62fd6200c7 at s3:http://archive1.home.intra:9000/restic.tests

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
* restic backup
password is correct
scan [/tank/sysbackup/patmos/Users/thomasko]
scanned 205757 directories, 923238 files in 3:50
[1:11:11] 100.00%  351.127 GiB / 351.127 GiB  1128995 / 1128995 items  0 errors  ETA 0:00
duration: 1:11:11
snapshot 236c9533 saved
     4502,78 real     10839,38 user      1388,48 sys



## ./restic_backup_stable
* restic init
Fatal: create key in repository at s3:http://archive1.home.intra:9000/restic.tests failed: repository master key and config already initialized

* restic backup
password is correct
using parent snapshot 236c9533
scan [/tank/sysbackup/patmos/Users/thomasko]
scanned 205757 directories, 923238 files in 4:33
[8:50] 100.00%  351.127 GiB / 351.127 GiB  1128995 / 1128995 items  0 errors  ETA 0:00
duration: 8:50
snapshot f9a6c84f saved
      812,99 real       925,89 user       302,11 sys



## ./restic_backup_newarchiver
* restic init
created restic repository 6b08850c98 at s3:http://archive1.home.intra:9000/restic.newtests

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
* restic backup
repository 6b08850c opened successfully, password is correct
[1:12:47] 65.42%  497874 files 229.691 GiB, total 914483 files 351.127 GiB, 0 errors ETA 38:29

Files:       914483 new,     0 changed,     0 unmodified
Dirs:            4 new,     0 changed,     0 unmodified
Added:      294.696 GiB

processed 914483 files, 351.127 GiB in 2:02:48
snapshot ff43f151 saved
     7368,54 real      8263,37 user      1244,54 sys



## ./restic_backup_newarchiver
* restic init
Fatal: create key in repository at s3:http://archive1.home.intra:9000/restic.newtests failed: repository master key and config already initialized

* restic backup
repository 6b08850c opened successfully, password is correct

Files:           0 new,     0 changed, 914483 unmodified
Dirs:            0 new,     0 changed,     4 unmodified
Added:      0 B

processed 914483 files, 351.127 GiB in 8:38
snapshot 9d1ed61e saved
      518,73 real       736,89 user       258,30 sys



## # ./restic_backup_newarchiver
* restic init
Fatal: create key in repository at s3:http://archive1.home.intra:9000/restic.tests failed: repository master key and config already initialized

* restic backup
repository 62fd6200 opened successfully, password is correct
[31:51] 36.96%  471273 files 129.761 GiB, total 914483 files 351.127 GiB, 0 errors ETA 54:20
/tank/sysbackup/patmos/Users/thomasko/Library/Application Support/iMazing/Library/Apps/Icons/org.videolan.vlc-ios-305

Files:       914483 new,     0 changed,     0 unmodified
Dirs:            4 new,     0 changed,     0 unmodified
Added:      1.795 KiB

processed 914483 files, 351.127 GiB in 1:19:39
snapshot 03fdb8ed saved
     4779,20 real      3749,19 user       547,83 sys



## ./restic_backup_newarchiver
* restic init
Fatal: create key in repository at s3:http://archive1.home.intra:9000/restic.tests failed: repository master key and config already initialized

* restic backup
repository 62fd6200 opened successfully, password is correct

Files:           0 new,     0 changed, 914483 unmodified
Dirs:            0 new,     0 changed,     4 unmodified
Added:      0 B

processed 914483 files, 351.127 GiB in 8:11
snapshot 1c5b59d7 saved
      491,85 real       701,27 user       231,04 sys

**Comment by fd0** [comment] 2018-05-08 06:25
very interesting information, thank you already! Just to confirm, did you try to increase the files read concurrently for OS X to 4 or even 16 yet? The place in the source code is here:

https://github.com/restic/restic/blob/cf1fb50f9c3958537aea2603c929cf2c57f42125/internal/archiver/archiver.go#L102

**Comment by tk7r** [comment] 2018-05-08 06:54
i have alread changed that to 4 and 16 - please see the posting 5 days ago - changing that made no difference.

on freebsd both lines change very frequently - on macosx some files simply hang there for a very long time (one was 800 bytes long, the other one 2 MB). they hung half a minute there ...

the question is: what is different on macosx your new code triggers?

**Comment by fd0** [comment] 2018-06-08 17:37
I've got no idea, sorry. Is anybody able to help here?

**Comment by MichaelEischer** [comment] 2020-09-30 20:59
@tk7r Does this issue still exist for you? For me the backup performance on macOS is ok.

**Comment by tk7r** [comment] 2020-09-30 21:14
it seemed to be an issue with my virus scanner. „old“ restic was running fine, but some new restic behaviour or access pattern triggered more checks in the virus scanner than before. - i think this issue can be closed.
i am running restic on macos too and it works fine so far (at least with disabled virus scanner).

**Comment by rawtaz** [comment] 2020-09-30 21:20
Thanks @tk7r, then we'll close this now!

**Closed by rawtaz** 2020-09-30 21:20 UTC
Labels: category: backup, help: wanted, platform: darwin, state: need feedback
