### ISSUE TITLE
Restic Not Able to Grab S3 Config

### ISSUE THREAD

**Issue by ghost** [restic/restic#2250] opened 2019-04-23 20:39 UTC
Output of `restic version`
--------------------------
0.9.4

How did you run restic exactly?
-------------------------------
I am running restic through a backup system called `bivac`, but essentially it just runs the restic container with given args.

cmd: `restic snapshots --no-cache -r s3:s3.amazonaws.com/xxx/monitoring/data-prometheus-consul-server-0`

I expect this command to work, however I am getting the error: 

```
Fatal: create repository at s3:s3.amazonaws.com/xxx/monitoring/data-prometheus-consul-server-0 failed: client.BucketExists: Head https://xxx.s3.dualstack.us-east-1.amazonaws.com/: 301 response missing Location header
```

I've traced down the issue to it trying to find the region specific bucket however that shouldn't be the case. When I run this locally (not in kubernetes) this works fine, however around 7 hours ago (when most of your docker images were updated) this stopped working in my cluster. 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Expected behavior
-----------------

To be able to see the repository in S3

Actual behavior
---------------

Not able to get to the repository

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

I have a feeling this correlates to the mass update of the docker images in docker hub. We never experienced this issue before.

Do you have an idea how to solve the issue?
-------------------------------------------
For now I'll rollback the version and hope this fixes the issue, but it seems like the region selected is the default in AWS which would lead me to believe it has something to do with an aws region setting.

**Comment by fd0** [comment] 2019-04-24 07:35
Hey, thanks for the report! Unfortunately this is an odd error condition and the message is very misleading: The cause is that the credentials you're using for accessing S3 do not have the `GetBucketLocation` permission. It has come up [in the forum](https://forum.restic.net/t/unable-to-access-s3-repos-after-0-9-5-upgrade/1604) and here: https://github.com/restic/restic/issues/2129#issuecomment-462450686

Can you please verify that that the credentials have the required permission and try again? Thanks!

**Comment by sascha-andres** [comment] 2019-05-28 11:55
@fd0 currently experiencing the same issue but with a user having S3 full permissions so it seems to be something else

**Comment by sascha-andres** [comment] 2019-05-28 12:22
@fd0 forget about my previous comment

Will not work: region specific endpoints directly
Will work: non specific endpoint with correct bucket name (my fault)

**Comment by MichaelEischer** [comment] 2020-09-30 23:08
@sascha-andres Is there something we should change in restic or the documentation? Or can this issue be closed?

**Comment by MichaelEischer** [comment] 2020-11-15 13:22
Closing this in favor of #2250.

**Comment by MichaelEischer** [comment] 2020-11-15 13:22
Errhh, I mean #2264.

**Closed by MichaelEischer** 2020-11-15 13:22 UTC
Labels: state: need feedback

**Comment by juninhobill** [comment] 2021-04-20 14:54
Hello, just trying those scripts to backup some files to AWS S3 and got this error:

[[Internet]] Repository string could not be parsed.

But the same string were used to create the respository and it worked, but when I tried to run the scheduled task in the windows task scheduler I'm geeting this error. Do you have any ideas on how to make it working??

By the way, the string that I'm using is: "s3:s3.amazonaws.com/xxx.xxx.xxx/BackupTest

Thank you so much!!!

**Comment by jpbostic** [comment] 2022-07-16 02:36
FWIW - and apologies if this was pointed out elsewhere - I learned that virtual-host-style URIs are also needed for AWS s3 ["access points" (private endpoints), which only support that style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-points-restrictions-limitations.html):

> You can only address access points using virtual-host-style URLs.

These access points are really nice because a VM inside AWS private network (VPC) can send data to/from them without transiting a NAT gateway, i.e. much lower transfer charges.
