### ISSUE TITLE
Any way for a repo with empty / without password?

### ISSUE THREAD

**Issue by Friday13th87** [restic/restic#3790] opened 2022-06-06 23:08 UTC
I am on restic 0.13.1 and found restic as i am using rclone for quiet a while now.

As i am using an crypted rclone mount / repo and as my full system is encrypted it would be just a waste of time and energy (as it is encrypting my backup twice ?! ) to use an restic repo which is encrypted by rclone AND by restic.

As i was searching that topic and saw that this feature request was already there at 2017 i was wondering if there are any news about that topic? Or is there maybe any fork around which is accepting empty password?

for automatic backups i need to save the password in a file anyway...

I dont understand that restic is not able to work without a password as restic is the only backup software which is working together with rclone so well, its making absolutley no sense to force people using a password if they are encrypted anyway, does it?
but hopefully i am just to stupid to set it up without a password

**Comment by greatroar** [comment] 2022-06-07 07:18
Duplicate of #1786, as you noted. Just to summarize what was already explained there: no password does not mean no encryption. Unencrypted backups are currently not supported; see #1018.

**Comment by MichaelEischer** [comment] 2022-06-08 18:03
There haven't been any news regarding that feature. So the rationale from #1018 is still up to date.

**Closed by MichaelEischer** 2022-06-08 18:03 UTC
