### ISSUE TITLE
backup on windows get stuck using sftp backend

### ISSUE THREAD

**Issue by dirk777** [restic/restic#780] opened 2017-02-08 08:33 UTC
## Output of `restic version`
debug enabled
restic 0.4.0
compiled with go1.7.5 on windows/amd64

## Expected behavior
backup should finish

## Actual behavior
backup get stuck after ~100 MB reached. It works with less data.

following output repeats every 10 sec.

`received output: [16:50] 46.22%  105.169 KiB/s  103.732 MiB / 224.421 MiB  314 / 1960 items  0 errors  ETA 19:35` 

debug log repeats the following messages:
```
2017/02/07 17:44:31 repository/master_index.go:164      repository.(*MasterIndex).FullIndexes   77      checking 2 indexes
2017/02/07 17:44:31 repository/master_index.go:167      repository.(*MasterIndex).FullIndexes   77      index 0xc0420f61c0 is final
2017/02/07 17:44:31 repository/master_index.go:167      repository.(*MasterIndex).FullIndexes   77      index 0xc0420f60e0 is final
2017/02/07 17:44:31 repository/master_index.go:179      repository.(*MasterIndex).FullIndexes   77      return 0 indexes
```

## Steps to reproduce the behavior
use restic in version 0.4.0 or 0.3.3 on windows 10 with latest updates, OpenSSH 7.4p1-1 (for windows) with SSH Key-Based Authentication,  sftp backend  in LAN or WAN, amount of data higher than 100MB

PS: it works with restic 0.4.0 and 0.3.3 with same sftp backend, same repository and same data on macOS Sierra

PPS: restic is great :-)

**Comment by fd0** [comment] 2017-02-08 19:31
Huh, that's odd. Thanks for reporting it!

**Comment by fd0** [comment] 2017-02-08 19:33
What operating system and SSH/sftp implementation is used on the server side?

**Comment by dirk777** [comment] 2017-02-08 20:19
I tried Strato's HiDrive, a 1&1 WebSpace and local the sftp backend on my Mac Mini running El Capitan. Always same behaviour.

**Comment by fd0** [comment] 2017-02-08 20:31
Ah, interesting. Thanks for providing additional details! It looks like the client is at fault.

**Comment by dextorious** [comment] 2017-02-28 02:53
I'm getting the same issue (except for me it gets stuck on ~37MB) using openssh v7.3 from msys2 on Windows 7. Haven't found any workable solutions for backing up over SFTP from Windows yet.

**Comment by ManiacTwister** [comment] 2017-03-18 19:32
I can reproduce this, it doesn't matter which backend i'm using. I tried it withsftp, rest and sftp with plink.exe (with the changes from #818)

```
archiver/archiver.go:599        archiver.(*Archiver).saveIndexes        72      saving full indexes
repository/master_index.go:164  repository.(*MasterIndex).FullIndexes   72      checking 10 indexes
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420dec40 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420ded20 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420f00e0 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420de070 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420de000 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420f01c0 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420f0000 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420f0230 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420de1c0 is final
repository/master_index.go:167  repository.(*MasterIndex).FullIndexes   72      index 0xc0420de0e0 is final
repository/master_index.go:179  repository.(*MasterIndex).FullIndexes   72      return 0 indexes

```

**Comment by fd0** [comment] 2017-03-18 19:45
Oh, that's interesting. Can you tell us a bit about your setup? Which version of restic are you using? How much data is saved until restic stops? Does it also happen with the local backend?

What are the last lines (~20 or so) before the index stuff in the debug log?

**Comment by ManiacTwister** [comment] 2017-03-18 20:25
Restic version 0.5.0, I'm backing up the images files of Windows Backup.

It sometimes stops between 500MB and 800MB of processed files, differs between every run.

Here is a complete log: http://data.s7t.de/restic.log

**Comment by fd0** [comment] 2017-03-19 08:47
Thanks for taking the time to make a full debug log, that's very helpful. Does it also happen with the local backend?

**Comment by ManiacTwister** [comment] 2017-03-19 10:35
I can't test an full local backup currently because there isn't enough diskspace, but at least it ran without any hangup for the first 5 GB

**Comment by electron128** [comment] 2018-04-01 08:51
Server:
Linux ubuntuvbox 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016

Client:
Windows 7
OpenSSH_7.3p1, OpenSSL 1.0.2j  26 Sep 2016
(ssh exe from PortableGit-2.11.0-64-bit.7z.exe)
public key auth

This version gets stuck after 80MB:
restic 0.3.2
compiled at 2017-01-05 14:24:31 with go1.7.4 on windows/amd64

The latest version works for all 400MB of test data:
restic 0.8.3
compiled with go1.10 on windows/386

**Comment by fd0** [comment] 2018-04-01 09:02
Thanks for the report! I'll close this issue for now. Anybody observing this issue again: Please add a comment so we can reopen this!

On a different note: We've just added support for `rclone` to restic (see #1657), which you can also use to access backends via sftp. It uses an internal SSH client, docs for setup are here: https://rclone.org/sftp/

**Closed by fd0** 2018-04-01 09:02 UTC
Labels: bug, help wanted, platform:Windows
