### ISSUE TITLE
Option to ignore missing files

### ISSUE THREAD

**Issue by pertoft** [restic/restic#3108] opened 2020-11-18 07:59 UTC
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It would be really nice to have an option E.g. --ignore-missing-files which would allow the backup job to complete.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am trying to use restic to backup a splunk server. I am doing this this by building a list of files (only selecting raw data and skipping metadata) and then use restic to backup the files:
restic backup --files-from backupset.txt'

This works great, but the volumes are big and it takes hours to complete a backup, and during this time, splunk can rotate some files and then restic breaks and says a file does not exist and abort the job.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Overall, restic is a very nice backup tool. Good job!

**Comment by rawtaz** [comment] 2020-11-18 11:17
Closing this as it's practically a duplicate of #3098. Please comment in there on the options of using a snapshot to have a consistent, non-changing set of files to back up, or use exclude files or similar. There were three other options mentioned in #3098.

**Closed by rawtaz** 2020-11-18 11:17 UTC
