### ISSUE TITLE
backup should allow whitelisting via include patterns, ignoring anything that doesn't match.

### ISSUE THREAD

**Issue by gitboy** [restic/restic#433] opened 2016-02-12 05:17 UTC
Imagine you have a filesystem hierarchy with 'snapshots' directories distributed at arbitrary
locations throughout where this directory is produced by some other tool. We don't know ahead of time which other directories to exclude. I'm currently using find to do this and supplying a long argv list of directories to restic, but then I lose preceeding path information in the resulting restic repo..

**Comment by fd0** [comment] 2016-02-12 07:02
Hi, thanks for raising this issue. Supporting whitelists/include patterns for backup is planned, see #414. I think this is is a duplicate, do you agree?

**Comment by fd0** [comment] 2017-01-06 19:06
Since there was no feedback for this issue, I'm going to close it as a duplicate of #414.

**Closed by fd0** 2017-01-06 19:06 UTC
Labels: feature, question
