### ISSUE TITLE
Restore hard links on *nix

### ISSUE THREAD

**Issue by djadala** [restic/restic#566] opened 2016-08-09 00:12 UTC
original files, see inode/device are equal:
```
stat /home/jambo/go/src/local/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc /home/jambo/golang/src/github.com/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc
  File: ‘/home/jambo/go/src/local/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc’
  Size: 2353      	Blocks: 8          IO Block: 4096   regular file
Device: 15h/21d	Inode: 19297756    Links: 2
Access: (0444/-r--r--r--)  Uid: ( 1000/   jambo)   Gid: ( 1000/   jambo)
Access: 2016-03-09 05:05:40.354887768 +0200
Modify: 2016-03-09 05:05:40.354887768 +0200
Change: 2016-03-09 09:10:56.556327665 +0200
 Birth: -
  File: ‘/home/jambo/golang/src/github.com/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc’
  Size: 2353      	Blocks: 8          IO Block: 4096   regular file
Device: 15h/21d	Inode: 19297756    Links: 2
Access: (0444/-r--r--r--)  Uid: ( 1000/   jambo)   Gid: ( 1000/   jambo)
Access: 2016-03-09 05:05:40.354887768 +0200
Modify: 2016-03-09 05:05:40.354887768 +0200
Change: 2016-03-09 09:10:56.556327665 +0200
 Birth: -
```

restored:

```
stat /opt/big/restore/home/jambo/go/src/local/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc /opt/big/restore/home/jambo/golang/src/github.com/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc
  File: ‘/opt/big/restore/home/jambo/go/src/local/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc’
  Size: 2353      	Blocks: 8          IO Block: 4096   regular file
Device: 1eh/30d	Inode: 15984615    Links: 1
Access: (0444/-r--r--r--)  Uid: ( 1000/   jambo)   Gid: ( 1000/   jambo)
Access: 2016-03-09 05:05:40.354887768 +0200
Modify: 2016-03-09 05:05:40.354887768 +0200
Change: 2016-07-31 03:00:06.907364726 +0300
 Birth: -
  File: ‘/opt/big/restore/home/jambo/golang/src/github.com/icza/gowut/.git/objects/50/7cd5ea64c50c3df60df39dbb0d55769e755cbc’
  Size: 2353      	Blocks: 8          IO Block: 4096   regular file
Device: 1eh/30d	Inode: 16025073    Links: 1
Access: (0444/-r--r--r--)  Uid: ( 1000/   jambo)   Gid: ( 1000/   jambo)
Access: 2016-03-09 05:05:40.354887768 +0200
Modify: 2016-03-09 05:05:40.354887768 +0200
Change: 2016-07-31 03:01:42.602489940 +0300
 Birth: -
```

**Comment by fd0** [comment] 2016-08-09 20:01
Hi, thanks for pointing this out. Restoring hardlinks is a feature that is not yet implemented. The repository contains enough data to restore hardlinks in the future, but restic does not do this on restore at the moment.

I'd appreciate someone taking the time and implement this. :smile:

**Comment by fd0** [comment] 2016-08-11 14:40
This is actually a duplicate of #152, I'm closing this issue. Comments can still be added of course.

**Closed by fd0** 2016-08-11 14:40 UTC
Labels: feature, help wanted, restore
