### ISSUE TITLE
`prune` hangs forever

### ISSUE THREAD

**Issue by asm0dey** [restic/restic#3396] opened 2021-05-15 06:20 UTC
Output of `restic version`
--------------------------

`restic 0.12.0 compiled with go1.15.8 on linux/amd64`

How did you run restic exactly?
-------------------------------

`RCLONE_FTP_CONCURRENCY=2 /usr/bin/restic --password-command='command here' -r rclone:ftp_backup:wwwdata prune`

hangs forever on step `[6:16:21] 4.02%  63 / 1569 packs repacked`, but the number of packs repacked is different every time
.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rclone + ftp

Expected behavior
-----------------

It should not hang

Actual behavior
---------------

It hangs

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Constantly makes me happy when because allowed me to preserve tones of data

**Comment by MichaelEischer** [comment] 2021-05-15 12:05
Which rclone version are you using? The issue looks a lot like #2925 to me. Could you try whether `-o rclone.connections=2` fixes the problem?

**Comment by asm0dey** [comment] 2021-05-15 12:33
The latest. Worked around by allowing 7 connections instead of 2.

**Comment by asm0dey** [comment] 2021-05-15 12:43
BTW, tcpdump shown only empty packages during hang, ltrace shown only multiple SIGURGs, memory and processor utilisation were extremely low, go gc logs shown only very rare collections like 88->88->84

**Comment by MichaelEischer** [comment] 2021-05-15 15:10
> Worked around by allowing 7 connections instead of 2.

In restic or in rclone? Did you take a look at #2925?

Can you send SIGQUIT to rclone when it hangs? That will kill the process and provide a stacktrace of all goroutines.

**Comment by asm0dey** [comment] 2021-05-15 16:49
In those env variable. To a pity I can't reproduce this anymore because prune it's already performed. I think this issue should be closed as duplicate

**Comment by MichaelEischer** [comment] 2021-05-16 10:25
Closing as duplicate of #2925.

**Closed by MichaelEischer** 2021-05-16 10:25 UTC
