### ISSUE TITLE
Periodically print progress information when output device is not TTY

### ISSUE THREAD

**Issue by RedL0tus** [restic/restic#2265] opened 2019-05-05 05:12 UTC
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.11.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I use restic as a systemd daemon, and I found out that when restic is not outputting to TTY, it does not give me any information about the current progress unless the action is finished. It would be wonderful to have a way to know the progress in this kind of situation.

What are you trying to do?
--------------------------
If this feature is implemented, we can know if restic is hanged or running, and know the progress when doing some time-consuming actions as a, for example, systemd daemon.

Current output:
```
+ restic prune
counting files in repo
building new index for repo
[1:07:41] 100.00%  25821 / 25821 packs
repository contains 25821 packs (2660207 blobs) with 112.837 GiB
processed 2660207 blobs: 102028 duplicate blobs, 2.071 GiB duplicate
load all snapshots
find data that is still in use for 4 snapshots
[1:27] 100.00%  4 / 4 snapshots
found 1112281 of 2660207 data blobs still in use, removing 1547926 blobs
will remove 0 invalid files
will delete 7384 packs and rewrite 8134 packs, this frees 50.006 GiB
[5:24:04] 100.00%  8134 / 8134 packs rewritten
counting files in repo
[39:08] 100.00%  13977 / 13977 packs
finding old index files
saved new indexes as [e1b57149 84198d5b 4733a8bf 598c99fa d33ccb78]
remove 174 old index files
```

Expected output:
```
counting files in repo
[00:00] 0% 0 / 13977 packs
[05:00] 12.82% 1792 / 13977 packs
...
[39:08] 100.00%  13977 / 13977 packs
```

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is doing a good job :)

**Comment by MichaelEischer** [comment] 2020-11-15 17:16
Closing this as duplicate of #2706.

**Closed** 2020-11-15 17:20 UTC

**Comment by RedL0tus** [comment] 2020-11-16 06:46
Well I even forgot I've opened this issue...
