### ISSUE TITLE
Huge loadavg on check --read-data

### ISSUE THREAD

**Issue by viric** [restic/restic#436] opened 2016-02-12 09:16 UTC
I'm running a "restic check --read-data". The system stays with loadavg > 40.

I see that the restic process has 52 threads, and I guess than over 40 of them are reading from disk.

I'm in a quadcore computer (nproc=8)... is this normal?

**Comment by fd0** [comment] 2016-02-13 18:40
Thanks for your question. Yes, this is normal. The current code does not yet have configurable limits on the concurrency.

A load of 40 and above does not necessarily cause any problems. Do you experience any problems besides the load counter?

**Comment by viric** [comment] 2016-02-14 12:38
I don't understand... GOMAXPROCS should be the limit for OS threads, isn't it? Or runtime.NumCPU().

My system, if 40 OS threads are doing disk IO (spinning hard disk), becomes quite unusable for the user. A simple Ctrl-C to stop restic takes 10 to 20 seconds.

**Comment by viric** [comment] 2016-02-14 12:41
although, if I recall correctly, any goroutine doing IO is going to spawn a new OS thread.

**Comment by fd0** [comment] 2016-02-14 12:43
Exactly, that's the cause for the larger number of threads you see. Do you have swap space enabled? Could you run `free -m` and paste it here, so we can see whether the lagginess you experience is caused by your system swapping out other processes to cache disk IO done by restic?

**Comment by viric** [comment] 2016-02-14 12:43
It's an 8GB RAM system... There were 1.8GB resident iirc. (I don't have the system at hand today)

**Comment by viric** [comment] 2016-02-14 12:49
In my dualcore system, I get restic using 46 threads (check --read-data). Loadavg > 30. The spinning disk gets 65 transactions-per-second, with total of ridiculous 0.25MB/s.

**Comment by fd0** [comment] 2016-02-14 12:52
Hm, you may have a point here. The default number of goroutines loading and checking data from the disk is 40, that's fine for remote resources that are far away, so the whole process isn't influenced too much by the latency to the remote system. But it's probably too much for a local disk.

How did you measure the bandwith?

**Comment by viric** [comment] 2016-02-14 13:03
I use iostat, from sysstat.

For remote disks, also 40? TCP is going to kill the network if there are 40 connections. Please allow tuning the number of io routines. Spinning disks drop bandwidth fast, on parallel accesses.

**Comment by viric** [comment] 2016-02-14 13:06
I'll set it to 1 and try. :)
I don't see why any parallelism may help here, if the task is doing only io. If the task does io+cpu (let's say, hashing), then parallelism is a workaround to get better throughput; but for 40 to make sense, the cpu time proportion over io time should be of 40.

**Comment by viric** [comment] 2016-02-14 13:13
Auhm. In this system, with defaultParallelism=1, I also get 0,25MB/s 64tps. 4% of restic cpu time, all time waiting. Other tests I do with other software read fine at 25MB/s (it's a usb2 external disk).

**Comment by fd0** [comment] 2016-02-14 13:31
That's an interesting case, thanks for reporting! What file system do you use for the external hard disk? What happens (in terms of IO bandwidth) when you use `tar` to read the repo, e.g. with `tar c repo | pv > /dev/null`?

**Comment by viric** [comment] 2016-02-14 13:35
I exactly had run that tar command with pv, to measure 25MB/s. :)

There is reiserfs in the disk.

I see with strace that restic does openat/read-a-bit/close. Is it reading the packs internal data in an order completely foreign to packs? That explains 0.25MB/s.

**Comment by fd0** [comment] 2016-02-14 13:37
Ah, hm. You're right, that could've been optimized to check one pack at a time. At the moment, restic checks each *blob* for itself, which means accessing a pack (with many blobs) multiple times: https://github.com/restic/restic/blob/master/checker/checker.go#L694-L738

**Comment by viric** [comment] 2016-02-14 13:39
So... I think that concurrency=1 and optimising that to serialised read of packs, would be a huge win. Specially for such a heavy operation! :)

**Comment by fd0** [comment] 2016-02-14 13:39
Agreed! Thanks for the productive discussion!

**Comment by fd0** [comment] 2016-02-14 20:54
Hm, I had a second look, and I was wrong: restic indeed reads the packs one by one and then verifies all blobs contained in each pack. So that's not the problem here.

**Comment by viric** [comment] 2016-02-15 09:22
In strace I was seeing openat() / read(few KBs) / close(), and start anew at openat(another pack) / read(few KBs) / close()....

May it be the part that reads the blobs for file tree (that may be not very much serialised), not the blobs for file data?

Strange.

**Comment by viric** [comment] 2016-02-15 09:42
I'm checking... I see 0,3MB/s in a stage where it just stats all the packs. As it is slow (800GB repository), this would be one step to report in packs_stated/packs_to_stat.

I'm not sure if restic resists signals... stracing, I've seen several:
```
pack 49f5ba4bf47e85a02343e1cff67cfee618359dba43734656b08211f06b67b977: stat /mnt/usb-backup/restic-tmp/data/49/49f5ba4bf47e85a02343e1cff67cfee618359dba43734656b08211f06b67b977: interrupted system call
```
This should not be an error; the call should just be retried.

**Comment by viric** [comment] 2016-02-15 09:45
Here is the kind of strace I see after the stats, for a single OS thread. Check the seeks, read sizes, etc.
```
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/88/883f9407a147c423577e9732ced2566c3278298bf1bae0065d0e586778c2b8a6", O_RDONLY|O_CLOEXEC) = 26
lseek(26, 868685, SEEK_SET)             = 868685
read(26, "\16u\223\35\334\204\"5\346\253\215\17\213\6\373`\363\270\273\3370W\200U\21e\222\202\177\327\222@"..., 1533) = 1533
close(26)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/2f/2fc007c310473307b5b2e9e6ffbfdb03849619ebdd573f81671780c8a7dc8330", O_RDONLY|O_CLOEXEC) = 19
lseek(19, 2725062, SEEK_SET)            = 2725062
read(19, "\342\340l-\266;\306v)\243y\276\374\363f+\373\31\355\5\251\331\225'=V\36\202\277/\5l"..., 402) = 402
close(19)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/1e/1e016728e80d3c5305fc39607b95fda224873133c5cb9f1e0123b238b76e5019", O_RDONLY|O_CLOEXEC) = 31
lseek(31, 693920, SEEK_SET)             = 693920
read(31, "\221\23,\34\322U\350\252qhm\341\336^@\240\204\320\203\215\26\314K\rk\266\3179A\223V'"..., 72735) = 72735
close(31)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/94/94c5237b9dc539f384e3c988682d741e9dd9e20fd6c22027ae68b3002b5ac414", O_RDONLY|O_CLOEXEC) = 34
lseek(34, 1899756, SEEK_SET)            = 1899756
read(34, "\300\301z\24q]Ta\357\320z\265\327>\1\234\225\261\\\243[fO\301\372\2119dsd\\\10"..., 1492) = 1492
close(34)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/0f/0ff46b6e7a3fea785fc99ec74115152168c386dbeea049fe010bc32561b98fdc", O_RDONLY|O_CLOEXEC) = 30
lseek(30, 1905168, SEEK_SET)            = 1905168
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/7a/7ae697fb740abf7100c4511cbbe71731ccab3a6cbf4467b49f8ec8d9a9df9b6f", O_RDONLY|O_CLOEXEC) = 6
lseek(4, 3988008, SEEK_SET)             = 3988008
lseek(16, 1277447, SEEK_SET)            = 1277447
lseek(6, 2456252, SEEK_SET)             = 2456252
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/a1/a1596aa984830b8098a9ec5b2982c543c771cd7014535f557b1fbd678ca203e3", O_RDONLY|O_CLOEXEC) = 38
read(38, "\327\362\325\0040^L\323\31%\20\333\321\334\264(\366t2\343\311\vh\314l\274\316\6m;k5"..., 3920) = 3920
close(38)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/92/92786cccd0c0b7d6acf848e10b59e5feebc22b5ba9d15e741255ce3894569011", O_RDONLY|O_CLOEXEC) = 41
lseek(41, 3202694, SEEK_SET)            = 3202694
read(41, "4j4K\273\204Sd2\2322\344`\276\33\364>A7\241\"\4\263\304\3619\177\237\177\257G\255"..., 847) = 847
close(41)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/03/03cf7b9de1e17811a0b556da917df2029500c6bd98fffff41b0e118d410d1ed2", O_RDONLY|O_CLOEXEC) = 16
lseek(16, 2685711, SEEK_SET)            = 2685711
read(16, "\v`\234\274\255\330\371X\272F\365V6\4\3224\332\343\231H\245\20\\\236\265\3067\32\316\325\264d"..., 2360) = 2360
lseek(20, 1975459, SEEK_SET)            = 1975459
read(20, "/\247M\0273K\2072\204\315v\237\377}:2\330[\3570)\215D\357\331\1\267\374\224\212\237\0"..., 9735) = 9735
close(20)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/5b/5b98d470bf1377f2c15df9900b9fe242074b853ae5edda258fc2dda34008d738", O_RDONLY|O_CLOEXEC) = 23
read(23, "\336\35&\324l\373\374\310/\245\233\300\247N\31s\230\334\205B\205\36\366\340\10&\225\202fv*\276"..., 2905) = 2905
close(23)                               = 0
openat(AT_FDCWD, "/mnt/usb-backup/restic-tmp/data/16/1619f055982f584e2031e47a6423b2915a07880935259d052e56a22b92c23bc0", O_RDONLY|O_CLOEXEC) = 19
lseek(19, 3383709, SEEK_SET)            = 3383709

```

**Comment by viric** [comment] 2016-02-15 09:52
The lack of retrial after signal affects reads too:
```
error for tree a721b8cb:
  read /mnt/usb-backup/restic-tmp/data/27/27b0e84ed1dd5ffed331f359ac6977070e073ac42f84db281634c311a9aa5fa8: interrupted system call
```

**Comment by viric** [comment] 2016-02-15 11:01
Right, reading data works properly seralized. But as the tasks per routine are read+calculate, some degree of parallelism definitely means faster check speed. 40, for me, means far too much IO colliding.

**Comment by fd0** [comment] 2018-10-03 10:33
Superseded by #1763, which is about adding a global switch for controlling concurrent access, closing.

**Closed by fd0** 2018-10-03 10:33 UTC
Labels: enhancement
