### ISSUE TITLE
TestOverwriteXattr fails when /tmp is tmpfs

### ISSUE THREAD

**Issue by ncopa** [restic/restic#4987] opened 2024-08-07 11:01 UTC
Output of `restic version`
--------------------------
0.17.0

What backend/service did you use to store the repository?
---------------------------------------------------------

n/a

Problem description / Steps to reproduce
----------------------------------------

The unit test TestOverwriteXattr fails when /tmp is mounted as tmpfs.

From Alpine Linux build log where this happened:
```
{"name":"","type":"","mtime":"0001-01-01T00:00:00Z","atime":"0001-01-01T00:00:00Z","ctime":"0001-01-01T00:00:00Z","uid":0,"gid":0,"linktarget":"vÃ¡lÃ®d \t ÃœÃ±iÂ¢Ã²de \n Å›áº—Å•inÇµ","content":null}
{"name":"","type":"","mtime":"0001-01-01T00:00:00Z","atime":"0001-01-01T00:00:00Z","ctime":"0001-01-01T00:00:00Z","uid":0,"gid":0,"linktarget":"\u0000\u0001\u0002\ufffd\ufffd\ufffd","linktarget_raw":"AAEC+vv8","content":null}
--- FAIL: TestOverwriteXattr (0.00s)
    node_xattr_all_test.go:35: [31mxattr mismatch got [] expected [{user.foo [98 97 114]}][39m
        
FAIL
FAIL	github.com/restic/restic/internal/restic	0.724s
```

Expected behavior
-----------------

Test either pass or is skipped.

Actual behavior
---------------

Test fails.

Do you have any idea what may have caused this?
-----------------------------------------------

the [tmpfs(5) man page](https://man7.org/linux/man-pages/man5/tmpfs.5.html#NOTES) says:

>     The tmpfs filesystem supports extended attributes (see xattr(7)),
>      but user extended attributes are not permitted.

The test creates a temp directory, which is created under /tmp and then tries to create extended attr `user.foo`, which fails.

Possible fix:
If the first try of setting the extended attr fails with permission denied, then `t.Skip()` instead of fail.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Greets from a fellow open sourcer! I'm just trying to troubleshoot why the build failed on Alpine Linux.

It did make me happy to see that you do have lots of tests. This particular issue is sort of hard to predict and was a bit tricky to debug, but still happy that you do test things.

**Comment by MichaelEischer** [comment] 2024-08-08 20:51
Duplicate of https://github.com/restic/restic/issues/4646 . If anyone is interested in helping with a fix, see that issue.

**Closed by MichaelEischer** 2024-08-08 20:51 UTC
