### ISSUE TITLE
Support RESTIC_HOSTNAME to overrive system hostname.

### ISSUE THREAD

**Issue by systemmonkey42** [restic/restic#2890] opened 2020-08-18 03:24 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/arm

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I have a number of systems where the hostname is not reliably unique, and I would like to override
the hostname of the system with an evironment variable `RESTIC_HOSTNAME`

This should override the default hostname, but not the `-H | --host` option.

What are you trying to do?
--------------------------

Get consistent backups regardless of hostname changes, or hostname duplication.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always.

**Comment by MadsBen** [comment] 2020-09-05 17:10
You can run restic in docker and set the hostname on the container.

I use this image:
https://github.com/djmaze/resticker

**Comment by MichaelEischer** [comment] 2020-10-10 09:13
Closing this as duplicate of #1233, which also contains a discussion of `--host`.

**Closed by MichaelEischer** 2020-10-10 09:13 UTC
Labels: category: user interface, state: need triaging, type: feature suggestion
