### ISSUE TITLE
Integrity check failed: Data seems to be missing

### ISSUE THREAD

**Issue by JPPhoto** [restic/restic#3365] opened 2021-04-18 11:50 UTC
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.15.8 on linux/amd64`

How did you run restic exactly?
-------------------------------

I experienced some connectivity timeout issues when backing up (yet the backup completed), so I ran `prune` and received error messages. I ran `rebuild-index` and then `prune` again:

`restic -r ~/backup/restic prune --verbose=2 --cache-dir ...`

```
loading indexes...
loading all snapshots...
finding data that is still in use for 218 snapshots
[3:58:53] 100.00%  218 / 218 snapshots

searching used packs...
{<data/25b65038> <data/46a5b4a0> <data/57106cf3> <data/5c482f76> <data/697c74d4> <data/748a35c5> <data/bbf4c15e> <data/d2dbaea6> <data/dc856fef>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete

```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

I ran `prune` on the system housing the repository rather than remotely for performance reasons.

Expected behavior
-----------------

I expected prune to identify and fix any corruption.

Actual behavior
---------------

Prune failed and I cannot determine the state of the repository.

Steps to reproduce the behavior
-------------------------------

Run `prune` again.

Do you have any idea what may have caused this?
-----------------------------------------------

Connectivity issues and a `backup` run that claimed it worked properly but likely corrupted data.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

**Comment by JPPhoto** [comment] 2021-04-18 14:35
I feel that I should elaborate on how I'm connecting to the backend when I run `backup`. The backend is REST running in a container and is hosted on a remote Linux box that only exposes SSH. I set up a persistent SSH tunnel using `autossh` and I forward the remote REST port locally to connect to it that way. Essentially, it looks like the backend is local but it's actually not - this shouldn't make any difference to restic, as far as I can tell.

A larger question is if connectivity issues or spontaneous crash/reboot of a remote server would result in this type of corruption. Are critical file operations not done atomically? Could restic use some type of journaling system to avoid corruption? And what can I do from here?

**Comment by aawsome** [comment] 2021-04-19 16:47
You have blobs that are referenced by snapshots still in use but do not exist in the index. So indicates that your repo is corrupted and in this state no pruning should be performed.

Do you still have the output of the `prune` run before `rebuild-index`?

**Comment by JPPhoto** [comment] 2021-04-19 16:49
@aawsome No, I don't have that log any more - nor the one that shows the problems I experienced backing up.

**Comment by aawsome** [comment] 2021-04-19 16:57
Mhh - that makes a root cause analysis much harder. It might be that a bug in rest-server (fixeed by (https://github.com/restic/rest-server/pull/142) ) is the cause.

So what you can do:
- Run `restic check` to ensure your repo is really corrupted (should give a similar output as the `prune` run).
- If you really miss blogs, the best you can do is rerun your `backup` run(s). As you already did run `rebuild-index`, `backup` is able to recognise missing blogs and re-save them. So there is a good chance this will repair you repo. Always run `check` after to see if this improved the situation.

**Comment by JPPhoto** [comment] 2021-04-19 18:31
@aawsome I'm running rest-server v0.10.0 so it's entirely likely that the bug you indicated is responsible. I moved away from sftp for performance reasons, but I'd gladly switch back if it meant more stability. Does the sftp code guarantee atomicity or operate differently?

I removed the snapshot that I believe contained the corruption and ran the backup job again. I received a lot of messages like:

```
error: parts of X not found in the repository index; storing the file again
```

I'm running prune again following this backup and it appears to be doing much better.

**Comment by aawsome** [comment] 2021-04-20 04:46
> I removed the snapshot that I believe contained the corruption and ran the backup job again. I received a lot of messages like:
> 
> ```
> error: parts of X not found in the repository index; storing the file again
> ```

Actually no need to remove a snapshot first. But these are the messages I wanted to see :wink: Each message means that a blob was re-saved and you repository was healed a bit. If `check` after did not not complain, your repo is completely sane again.

As it seems there is no possibility to find the root cause and it supposedly is no restic issue, can you close this issue?

**Closed** 2021-04-20 11:25 UTC
