### ISSUE TITLE
String escape bug in restic

### ISSUE THREAD

**Issue by 3xNihil0** [restic/restic#3726] opened 2022-04-29 21:17 UTC
Output of `restic version`
--------------------------
`restic 0.13.1 compiled with go1.18 on windows/amd64`

How did you run restic exactly?
-------------------------------
It runs on a machine with Windows 10 Enterprise LTSC, using `PowerShell` in non-privileged mode on a non-privileged user account. When I try to get a list of my locally stored snapshots, I type the following:
` restic list snapshots -r 'C:\Users\ExNihilo\Local Backup\'`

It doesn't matter if I use single or double quotes, because it returns in both cases
`Fatal: unable to open repo at C:\Users\ExNihilo\Local Backup": ReadDir: open \\?\C:\Users\ExNihilo\Local Backup"\keys: The filename, directory name, or volume label syntax is incorrect.`

Maybe I did something wrong, but this syntax should be fairly okay I guess.

Also, this problem appears when trying to create a new snapshot:
`restic -r "C:\Users\ExNihilo\Local Backup" --verbose backup "C:\Users\ExNihilo\Nextcloud\Documents\Important Files\"`

It returns:
`open repository`
`enter password for repository:`
`repository 5606b5e7 opened successfully, password is correct`
`lock repository`
`load index files`
`using parent snapshot 8dfeb461`
`start scan on [C:\Users\ExNihilo\Nextcloud\Documents\Important Files"]`
`start backup on [C:\Users\ExNihilo\Nextcloud\Documents\Important Files"]`
`scan: CreateFile \\?\C:\Users\ExNihilo\Nextcloud\Documents\Important Files": The filename, directory name, or volume label syntax is incorrect.`
`scan finished in 0.277s: 0 files, 0 B`
`error: CreateFile \\?\C:\Users\ExNihilo\Nextcloud\Documents\Important Files": The filename, directory name, or volume label syntax is incorrect.`

`Files:           0 new,     0 changed,     0 unmodified`
`Dirs:            8 new,     0 changed,     0 unmodified`
`Data Blobs:      0 new`
`Tree Blobs:      0 new`
`Added to the repo: 0 B`

`processed 0 files, 0 B in 0:00`
`snapshot ffc9d588 saved`
`Warning: at least one source file could not be read`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
In this case I just used the PC's local drive in order to save a local backup for offline-access purpose.

Expected behavior
-----------------
As on GNU/Linux-Systems and macOS, I'd expect restic to list the snapshots / to save a new snapshot on the repo, because there seems nothing wrong with the parameter's syntax.

Actual behavior
---------------
Restic claims the parameter ill-formed and doesn't list the snapshots / save a new snapshot on the repo.

Steps to reproduce the behavior
-------------------------------
Type in the simple commands on `Windows PowerShell` I listed above, using the corresponding version of restic.

Do you have any idea what may have caused this?
-----------------------------------------------
It seems there's actually missing a double quotation mark in the applications code which's aim should be to escape the parameter sequence for the file path.

Do you have an idea how to solve the issue?
-------------------------------------------
When I modify the commands provided above in such a way that I add the missing double quotation mark (_see the double quotation mark in the code example below, right before the_ `C:\`), then restic works quite fine and without any issues it creates a new snapshot:
`restic -r "C:\Users\ExNihilo\Local Backup" --verbose backup '"C:\Users\ExNihilo\Nextcloud\Documents\Important Files\'`

The second path is escaped by single quotation marks in order to let the double quotation pass into the final string restic is processing. Doing so prevents the entire issue described here.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, it helped me a lot and it's a great tool on Linux and macOS! I really appreciate your work - keep going :)

**Comment by MichaelEischer** [comment] 2022-04-30 10:51
This is a duplicate of #2449. The attempts to work around the problem in [#3637](https://github.com/restic/restic/pull/3637#issuecomment-1086911678) look like this is a bug in how PowerShell escapes paths rather than in restic.

**Closed by MichaelEischer** 2022-04-30 10:51 UTC
