### ISSUE TITLE
Background check fails when no pty, and then assumes foreground and uses terminal

### ISSUE THREAD

**Issue by donbowman** [restic/restic#1819] opened 2018-05-26 22:41 UTC
## Output of `restic version`

restic 0.9.0 (v0.9.0-0-ge4019194) compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?

/usr/bin/restic backup --verbose=9 --hostname=foobar /etc

RESTIC_PASSWORD=XXX
RESTIC_REPOSITORY=rest:https://don:XXX@backup.XXX/don

open repository
repository e0167288 opened successfully, password is correct
lock repository
load index files
using parent snapshot 74313129
start scan on [/etc]
start backup on [/etc]
panic: runtime error: slice bounds out of range

goroutine 7 [running]:
github.com/restic/restic/internal/ui/termstatus.(*Terminal).SetStatus(0xc420026de0, 0xc4200667a0, 0x1, 0x1)
	src/github.com/restic/restic/internal/ui/termstatus/status.go:310 +0x319
github.com/restic/restic/internal/ui.(*Backup).update(0xc420227c70, 0x1, 0x0, 0x4e, 0x0, 0x0, 0x0, 0x0, 0xc420062d00, 0x0)
	src/github.com/restic/restic/internal/ui/backup.go:181 +0x69e
github.com/restic/restic/internal/ui.(*Backup).Run(0xc420227c70, 0xc06fc0, 0xc420071240, 0x0, 0x0)
	src/github.com/restic/restic/internal/ui/backup.go:139 +0x5d5
main.runBackup.func2(0x0, 0x0)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:360 +0x75
github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc42001ca50, 0xc42000b100)
	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb9

## What backend/server/service did you use to store the repository?

rest server

## Expected behavior

In internal/ui/termstatus/background_linux.go
we have this function IsProcessBackground(). It calls syscall.TIOCGPGRP.

I am running w/o a pty and this is failing. But the function assumes this means !background,
so the terminal stuff still gets called.

Maybe assume background if this fails.

**Comment by fd0** [comment] 2018-05-27 09:50
Hey, thanks for the report. How do you run restic without a pty? What's the easiest way for me to reproduce this?

**Comment by fd0** [comment] 2018-05-27 09:52
It's a duplicate of #1803, I'm closing this bug here.

**Closed by fd0** 2018-05-27 09:52 UTC
Labels: 0.9.0, bug, duplicate
