### ISSUE TITLE
one-file-system does not correctly handle sub-paths

### ISSUE THREAD

**Issue by zx2c4** [restic/restic#907] opened 2017-04-13 16:32 UTC
`/mnt/storage` is a filesystem. `/` is a filesystem. `/` has many file systems mounted underneath it, including `/mnt/storage`.

What happens if I run:

```
$ du -shcx / /mnt/storage/Archives/
```

It will give me the sum total of files used on `/`, on the `/` filesystem, and of `/mnt/storage/Archives/` on the `/mnt/storage` filesystem. This is the correct behavior.

However, if I run:

```
$ restic -r ... backup -x / /mnt/storage/Archives/
```

Then it will backup everything in `/` *and* everything in `/mnt/storage/`, since `/mnt/storage/` is under `/`, and the addition of `/mnt/storage/Archives/` to the command line added in the `/mnt/storage` filesystem to the allowed lists. This is the incorrect behavior.

Rather, `-x` should anchor each traversal point to that root point's filesystem, like what `du` does.

**Comment by fd0** [comment] 2017-04-13 16:53
Hey, thanks for taking the time to report this. It is actually a known issue, the code responsible for `--one-file-system` is unable to handle nested mount points. I'm going to close this as a duplicate of #702, please subscribe to that issue if you want to be notified once it's resolved.

In the meantime, you could make separate backups (but running at the same time) of `/` and `/mnt/storage/Archives`.

**Closed by fd0** 2017-04-13 16:53 UTC

**Comment by zx2c4** [comment] 2017-04-13 16:56
Hey @fd0. Thanks. Just saw that bug a few seconds before you posted. Sorry for the duplicate.

Question: if I do two separate backups, and then later, after you fix this issue, move to doing one single backup, will `--parent` still auto-populate with the identical information?

**Comment by fd0** [comment] 2017-04-13 17:00
No big deal, I'll just close duplicates ;)

When you move to a separate backup, the first run will re-read all files, but restic will recognize that all data has already been saved in the repo, so no new data is uploaded. The next backup after that will again use a parent snapshot.

**Comment by fd0** [comment] 2017-04-13 19:05
Could you please check if the code in #908 if that works for you?
