### ISSUE TITLE
Panic while backing up to S3 connection reset and broken pipe

### ISSUE THREAD

**Issue by cakeface** [restic/restic#824] opened 2017-02-24 14:39 UTC
I'm having trouble backing up some large NFS drives to S3 using restic.  AWS has a new EFS (Elastic File System) product that provides NFS as a service. Unfortunately there is no way to snapshot these drives so I was hoping to use restic.  These issues have blocked me from using it so I'm not evaluating other backup options.  I'll try to help get these resolved as the architecture and design of restic is preferable to other options I've found.  My go skills are a bit minimal but I may take a crack at a PR for the fix.

## Output of `restic version`
Latest from master compiled on the machine. Last commit 4a51ddf741b58430b8c24db82b61ac4ce9c5f284
```
restic 0.4.0 (v0.4.0-71-g4a51ddf)
compiled with go1.6 on linux/amd64
```

## Expected behavior
Restic should complete successfully when backing up large directories from NFS to AWS S3 bucket. 

## Actual behavior
Restic fails with a panic error during backup.  

```
root@jobs-1:/proj/restic# ./backup_efs.sh
scan [/proj/source]
scanned 25667 directories, 1125384 files in 30:27
panic: client.PutObject: Put https://backup-efs-irl-pubfactory.s3-eu-west-1.amazonaws.com/restic/data/f5dcd03a553e4957901cf849b8cae6b1ca5a7ee379716d4858aeda9a3cf02a54: write tcp 10.200.2.241:51111->52.218.48.83:4
43: write: broken pipe

goroutine 2028346 [running]:
panic(0xa72f60, 0xc8203b2780)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
restic/archiver.(*Archiver).saveChunk(0xc8203dc410, 0x0, 0x3d9a5b, 0x174fb4be00000, 0xc827092000, 0x3d9a5b, 0x5ea000, 0xc8200d4000, 0x7f51c9174b80, 0xc84a84e0a8, ...)
        /tmp/restic-build-465106983/src/restic/archiver/archiver.go:163 +0x12b
created by restic/archiver.(*Archiver).SaveFile
        /tmp/restic-build-465106983/src/restic/archiver/archiver.go:237 +0x70f
scan [/proj/staticfiles]
scanned 1473 directories, 14947 files in 0:20
[4:41] 100.00%  47.601 MiB/s  13.063 GiB / 13.063 GiB  16420 / 16420 items  0 errors  ETA 0:00
duration: 4:41, 47.48MiB/s
snapshot c6c17143 saved
scan [/proj/env]
scanned 588 directories, 946821 files in 45:38
panic: client.PutObject: Put https://backup-efs-irl-pubfactory.s3-eu-west-1.amazonaws.com/restic/data/87ce82cac7736c2f58c1cd249d8dd1582a49b7a768e008cadf6b9cc344ad260f: write tcp 10.200.2.241:60911->52.218.64.35:4
43: write: connection reset by peer

goroutine 344633 [running]:
panic(0xa72f60, 0xc8338763c0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
restic/archiver.(*Archiver).saveChunk(0xc8290a6a50, 0x399afe607, 0x800000, 0x8d412c900cafd, 0xc83ae82000, 0x800000, 0x936000, 0xc820194000, 0x7ff03be60b10, 0xc8201880e0, ...)
        /tmp/restic-build-465106983/src/restic/archiver/archiver.go:163 +0x12b
created by restic/archiver.(*Archiver).SaveFile
        /tmp/restic-build-465106983/src/restic/archiver/archiver.go:237 +0x70f
```

## Steps to reproduce the behavior
1. Create an S3 bucket and IAM role with access.  If needed I can provide details on this.  
2. Install go on Ubuntu 14.04 m4.large VM at AWS with 60GB EBS gp2 volume.
```
add-apt-repository ppa:ubuntu-lxc/lxd-stable
apt-get install golang
```
3. Check out latest master of restic and compile using build.go.
4. Mount 3 separate EFS volumes to the machine using NFS mounts. I can provide details if needed. Mounts are approximately 1.1TB, 14GB and 417GB
4. Run Backup using the following settings in a shell script, backup_efs.sh

```shell
#!/bin/bash

export AWS_ACCESS_KEY_ID="XXXXXXXXXXXX"
export AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXXXXXXXXXXXXXXX"

export RESTIC_REPOSITORY="s3:s3.amazonaws.com/<bucket>"
export RESTIC_PASSWORD="XXXXXXXXXXXXXX"

# Before using this script there is a manual step to initialize the restic repository. I'm not sure
# how to make this step idempotent right now.
#
# restic init

./restic backup /proj/source
./restic backup /proj/staticfiles
./restic backup /proj/env
```

**Comment by cakeface** [comment] 2017-02-24 14:45
I apologize, I didn't do a thorough research job on this.  This issue may be a duplicate of issue #415

**Comment by fd0** [comment] 2017-02-27 18:56
This is indeed a duplicate of #415, thanks for your comprehensive report though!

**Closed by fd0** 2017-02-27 18:56 UTC
