### ISSUE TITLE
Using tags causes restic backup to fail and exit with error

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [restic/restic#1810] opened 2018-05-24 17:40 UTC
## Output of `restic version`
restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?
```
export RESTIC_REPOSITORY="/run/media/Seagate EXT"
export RESTIC_PASSWORD="foo"
restic init
[user@host Seagate EXT]$ restic backup --verbose --tag HDD --exclude-file=/usr/local/etc/restic-exclude.txt .
open repository
repository 2f131fac opened successfully, password is correct
lock repository
load index files
start scan on [.]
start backup on [.]
scan: lstat (unreachable): no such file or directory
scan finished in 2.702s: 0 files, 0 B
Fatal: unable to save snapshot: Readdirnames . failed: readdirent: input/output error: readdirent: input/output error
```

## What backend/server/service did you use to store the repository?
Local repository (i.e. external hard drive)

## Expected behavior
Restic should start scanning the backup target data and backup this data concurrently.

I would like restic to backup data to the local repository when the command above is entered in its current form i.e. with the `--tag` flag.
## Actual behavior
Restic attempts to begin the backup process but fails within a second or two and then returns an error saying that the backup directory does not exist, even though the external hard drive was still plugged in.

## Steps to reproduce the behavior

1. Create local repository in external hard drive.
2. Write a command to backup all data in this external hard drive into the restic repository in this location.
3. Add an `--exclude-file=` sub command containing directories you want to exclude in this external HDD.
4. Add a tag using `--tag HDD` either just after `--verbose` or just before the directory you want to backup (I tested both, same result).

## Do you have any idea what may have caused this?
Yes I removed the tag and only then was I able to successfully start the backup. There isn't a reason why a tag should cause the backup to fail so I suspect it may be because I am using the capital letters "HDD" for the tag's argument.

## Do you have an idea how to solve the issue?
Yes see directly above

## Did restic help you or made you happy in any way?
Restic actually makes backing up fun. This is one of the best backup programs available. I look forward to when documentation catches up to development because it will be even better.

**Comment by fd0** [comment] 2018-05-24 19:17
Thanks for the report. This is something else, I don't think it has something to do with the tag. I cannot reproduce it, the backup (with your exact command line) works fine here. In addition, the error message (that the current directory `.` could not be read) does not hint that the tag is involved in any way.

I noticed something else:
 * The backup repository (where the files should be stored) is `/run/media/Seagate EXT`, which has a space in the name
 * Is it maybe possible that you're currently within the same directory? That still should not cause the error, but I'd like to confirm...

Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by ChukwuemezieChristopherAneke** [comment] 2018-05-26 08:56
Yes I cd'ed into the Seagate Ext directory so the space is not an issue. 
I don't think rebuilding restic applies to me because I am using the restic beta binary so I didn't actually build it from source. Would this mean re-downloading restic from source? If so, do I lose my environment variables, passwords, repostories and other restic related things.

Some more questions:
- How else can I create a debug log?
- Does the debug log collect data from after the log was created or is it able to collect data from before? I am asking in case I am not able to reproduce the bug.

**Comment by fd0** [comment] 2018-05-26 09:00
The beta binaries do not have the code enabled that generates the debug log, because it'll impact performance so it's not enabled by default. Rebuilding is the only way to get a debug log.

What you could try before is running restic through `strace`, like this:
```
$ strace -o log -f restic backup [...]
```

Then paste the relevant excerpt from the log (or attach the log to this issue).

**Comment by fd0** [comment] 2019-04-27 19:52
Since we haven't received any feedback in a long time I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!

**Closed by fd0** 2019-04-27 19:52 UTC
Labels: feedback needed
