### ISSUE TITLE
Restic dump command flags mistake

### ISSUE THREAD

**Issue by zebby76** [restic/restic#4252] opened 2023-03-15 19:48 UTC
Output of `restic version`
--------------------------

restic 0.15.1 compiled with go1.19.5 on linux/amd64

How did you run restic exactly?
-------------------------------

1. First, i take a dump from my Postgres database and store as snapshot in Restic :

```
DB_CONNECTION_URL="postgresql://xxx:yyy@aaa.bbb.ccc.dddd:5432/bluedb?connect_timeout=30"
RESTIC_TAG="bluedb,schema_example_adm"

bash-5.1$ pg_dump -T cache_container -w --clean -Fp -O --schema=schema_example_adm ${DB_CONNECTION_URL} | \
  restic backup --host localhost --tag ${RESTIC_TAG} --stdin --stdin-filename pgdump.sql

repository 9de5c9a9 opened (version 2, compression level auto)

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repository: 1.299 KiB (802 B stored)

processed 1 files, 1020 B in 0:00
snapshot abbd7544 saved
```

2. A quick check allows me to see that my snapshot is well included in the Restic repository

```
bash-5.1$ restic snapshots
repository 9de5c9a9 opened (version 2, compression level auto)
ID        Time                 Host        Tags                       Paths
---------------------------------------------------------------------------------
abbd7544  2023-03-15 20:23:17  localhost   bluedb,schema_example_adm  /pgdump.sql
---------------------------------------------------------------------------------
1 snapshots
```

3. I want to reload the dump stored as a snapshot in Restic, but the `dump` command returns an error reporting `no snapshot found`.  It can be noticed that the arguments passed to the `dump` command do not match ...

```
bash-5.1$ restic dump --host localhost --tag ${RESTIC_TAG} --path /pgdump.sql latest pgdump.sql | psql ${DB_CONNECTION_URL}
Fatal: failed to find snapshot: snapshot filter (Paths:[localhost] Tags:[[bluedb, schema_example_adm]] Hosts:[/pgdump.sql]): no snapshot found
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Minio S3 Bucket

Expected behavior
-----------------

```
bash-5.1$ restic dump --tag ${RESTIC_TAG} --path /pgdump.sql latest pgdump.sql | psql ${DB_CONNECTION_URL}
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
COMMENT
REVOKE
REVOKE
GRANT
GRANT
```

Actual behavior
---------------

```
bash-5.1$ restic dump --host localhost --tag ${RESTIC_TAG} --path /pgdump.sql latest pgdump.sql | psql ${DB_CONNECTION_URL}
Fatal: failed to find snapshot: snapshot filter (Paths:[localhost] Tags:[[bluedb, schema_example_adm]] Hosts:[/pgdump.sql]): no snapshot found
```

Steps to reproduce the behavior
-------------------------------

1. take a backup with `host` and `tags` arguments  
2. restore the backup  

Do you have any idea what may have caused this?
-----------------------------------------------

It seems that it is a regression compared to the version v0.14.0, everything works correctly with this version of Restic

Do you have an idea how to solve the issue?
-------------------------------------------

Not really, my knowledge of Go is very limited

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes I use it daily, it allows me to take backups of my databases and store them securely.  
The ease of restoration is really appreciated.

**Comment by greatroar** [comment] 2023-03-17 10:16
Duplicate of #4211, already fixed in master by #4212.

**Closed** 2023-03-17 14:33 UTC
