### ISSUE TITLE
Permission Denied during Restore using restic with velero

### ISSUE THREAD

**Issue by prajyotparab** [restic/restic#2289] opened 2019-05-30 06:48 UTC
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-0-gcd9b229) 

How did you run restic exactly?
-------------------------------

Using restic with velero
- Created backup of my resources with Persistent Volume (PV) on cluster 1
- Trying to restore it on cluster 2
Storage used : Minio (both cluster pointing to same backup storage location)
- Restore completes without any errors (Deployments, PV can be seen on cluster 2)
- But the deployments never come up in running state 
  - pod associated to it is in pending state
  - docker container of pod throwing error 
`ERROR looking for /restores/mongodb-app-ibm-mongodb-dev-datavolume/.velero/7817a7da-76ef-11e9-8851-fa163e586ef1: stat /restores/mongodb-app-ibm-mongodb-dev-datavolume/.velero/7817a7da-76ef-11e9-8851-fa163e586ef1: permission denied`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio

Expected behavior
-----------------
After restore done using the restic plugin with velero (all deployments should be in ready state)

Actual behavior
---------------
POD container throwing error :
`ERROR looking for /restores/mongodb-app-ibm-mongodb-dev-datavolume/.velero/7817a7da-76ef-11e9-8851-fa163e586ef1: stat /restores/mongodb-app-ibm-mongodb-dev-datavolume/.velero/7817a7da-76ef-11e9-8851-fa163e586ef1: permission denied`

Steps to reproduce the behavior
-------------------------------
MongoDB Sample application already up and running with Persistent Volume on cluster 1

1.Annotated POD
2.Create Backup
3.Restore on Cluster 2

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes - Easy to use tool for backup & restore of persistent volumes seamlessly (useful when working with cloud providers lacking plugins to support PV backups)

**Comment by MichaelEischer** [comment] 2020-03-21 22:21
Your error message is not printed by restic. This rather looks like something else, maybe Velero, messed up the file permissions.

Judging from the [Velero documentation of their restic integration](https://velero.io/docs/v1.3.1/restic/) the problematic file is written by a controller for `PodVolumeRestore`.

> on success, writes a file into the pod volume, in a `.velero` subdirectory, whose name is the UID of the Velero restore that this pod volume restore is for

That is in case this issue still exists it seems to be a problem with Velero. If this were caused by an unexpected behavior of restic, please provide steps to reproduce that can be followed without spinning up a whole kubernetes (?) cluster and storage backend (The abstraction level of your steps to reproduce would probably be useful for a bug report in the Velero bugtracker ).

**Comment by MichaelEischer** [comment] 2020-04-01 15:04
@prajyotparab Your issue looks like it's not (directly) caused by restic. I'll close this issue for now, but feel free to reopen it, if you still think it's a problem with restic.

**Closed by MichaelEischer** 2020-04-01 15:04 UTC
Labels: state: need feedback, type: question/problem
