### ISSUE TITLE
prune --no-repack option

### ISSUE THREAD

**Issue by rmmh** [restic/restic#2305] opened 2019-06-12 05:45 UTC
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
`restic prune` currently does both pack deletions and rewrites. Pack deletions are fast but rewriting is slow, and requires fetching data from the backend (#2162). This fetching is very expensive for some cloud storage options (B2, Glacier, etc).

A new prune option to skip the repacking step and only delete entirely unneeded packs would allow faster incremental pruning operations.

What are you trying to do?
--------------------------
restic prune against b2

**Comment by ibib** [comment] 2019-06-12 06:23
Duplicate of https://github.com/restic/restic/pull/1994 ?

**Comment by rmmh** [comment] 2019-06-13 20:04
Somewhat, if that gets in this is equivalent to `--repack-threshold 100`.

**Closed** 2020-11-05 09:12 UTC
