### ISSUE TITLE
Add flag to apply retention policy to objects stored in S3

### ISSUE THREAD

**Issue by virtualdxs** [restic/restic#3759] opened 2022-05-16 05:52 UTC
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18.1 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Add a flag to certain restic subcommands (at least backup and copy) to have restic apply a retention policy ([PutObjectRetention docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectRetention.html)) on objects it creates in S3 other than the lockfiles. 

Two parameters would be required:

1. Mode: Governance (admin can override retention period) or Compliance (retention period cannot be overridden at all)
2. RetainUntilDate: When the immutability will expire. Ideally this could be provided either as an end date or a duration (where restic automatically calculates the end date).

It would also have to be determined whether restic should renew the retention period on objects referenced by the current backup, on all objects in the repo, or not at all. (And whether this should be configurable.)

Background:
S3 Object Lock is a useful feature that can help protect against ransomware by making objects in S3 immutable. From my understanding, it can either be turned on for an entire bucket (so all new objects have retention applied), or on individual files. The global solution would be ideal as it guarantees nothing is missed and would require no code in the client. However, restic creates lock files in the bucket which cannot be removed if retention is in place. Therefore, I propose that restic implement the ability to use the PutObjectRetention API to apply an object lock to its objects but not the lock files.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm finally getting to setting up backup again and I was incredibly impressed by restic's feature set. After reading up on it I decided to go all in with it as I'm confident in its stability and the fact that I'll actually be able to restore my backups when I need to. Also, I'm really happy about how little of my own automation I have to write around it :)

**Comment by MichaelEischer** [comment] 2022-05-16 19:24
Duplicate of #3195. Just refreshing object locks isn't really sufficient, we'll also need some additional sanity checks to prevent someone from breaking a repository without anyone noticing.

**Closed by MichaelEischer** 2022-05-16 19:24 UTC

**Comment by tbodt** [comment] 2026-04-17 07:50
> Duplicate of [#3195](https://github.com/restic/restic/issues/3195). Just refreshing object locks isn't really sufficient, we'll also need some additional sanity checks to prevent someone from breaking a repository without anyone noticing.

@MichaelEischer I can't find details on what kind of repository breakage is worth worrying about, could you clarify?
