### ISSUE TITLE
"Connection timed out" during backup to Wasabi cloud storage

### ISSUE THREAD

**Issue by ralphhaselbach** [restic/restic#3122] opened 2020-11-25 10:00 UTC
Hello,

When trying to backup to Wasabi cloud storage, I get the following error message:
Fatal: unable to save snapshot: client.PutObject: Put https://s3.eu-central-1.wasabisys.com/BUCKET_NAME/data/39/39a7......5dae: read tcp SERVER_IP_ADDRESS:44272->130.117.252.11:443: read: connection timed out

Can you please help with this?

Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
Contents of .restic.env file in home folder of non-root user used for the backups:
```
export AWS_ACCESS_KEY_ID="MY_KEY_ID"
export AWS_SECRET_ACCESS_KEY="MY_ACCESS_KEY"
export RESTIC_PASSWORD="MY_PASSWORD"
export RESTIC_REPOSITORY="s3:https://s3.eu-central-1.wasabisys.com/MY_BUCKET"
```

**Used commands:**
```
backup_folder="/backup"
source /home/serverbackup/.restic.env
/usr/bin/restic --verbose=3 backup $backup_folder/20*
```

**Console output:**
```
serverbackup@SERVER:~$ /usr/bin/restic --verbose=3 backup $backup_folder/20*
open repository
repository fe504cb8 opened successfully, password is correct
lock repository
load index files
start scan on [/backup/2020-10-31]
start backup on [/backup/2020-10-31]
scan finished in 0.662s: 50 files, 1.476 TiB
new       /backup/2020-10-31/FILENAME1.tar.gz, saved in 88.569s (0 B added)
new       /backup/2020-10-31/FILENAME2.tar.gz, saved in 88.584s (0 B added)
new       /backup/2020-10-31/FILENAME3.tar.gz, saved in 141.153s (0 B added)
new       /backup/2020-10-31/FILENAME4.tar.gz, saved in 52.576s (0 B added)
new       /backup/2020-10-31/FILENAME5.tar.gz, saved in 0.007s (0 B added)
new       /backup/2020-10-31/FILENAME6.tar.gz, saved in 0.018s (0 B added)
new       /backup/2020-10-31/FILENAME7.tar.gz, saved in 234.857s (0 B added)
new       /backup/2020-10-31/FILENAME8.tar.gz, saved in 182.258s (0 B added)
Fatal: unable to save snapshot: client.PutObject: Put "https://s3.eu-central-1.wasabisys.com/BUCKET_NAME/data/39/3985......71a7": read tcp SERVER_IP_ADDRESS:41262->130.117.252.17:443: read: connection timed
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wasabi Cloud Storage (EU)

Expected behavior
-----------------
Backup all files and retry if it experiences a timeout

Actual behavior
---------------
After around 20-25 minutes of backing up data to the cloud repository, the backup task stops and outputs the error message. When I re-run the same command it first checks the already uploaded files (0B added) and then continues to upload files but stops after around 20-25 minutes again.

Steps to reproduce the behavior
-------------------------------
- Use virtual Debian 10 server with the latest updates installed
- Install restic from the official Debian repo
- (Updated restic manually using 'restic update', but didn't solve the issue)
- Create .config.env file
- Initialize repo
- Run backup command

Do you have any idea what may have caused this?
-----------------------------------------------
The Wasabi support replied this to my support request:
"We looked at the CDRs, the reason you saw those timeouts is due to slate socket connection from your application (minIO) wherein its not doing anything but just sitting idle for more than 60s. This gets timed-out on our servers so new connections can be freed up. Please check within your application logs to see if you can address this in minio and you may want to reach out to minio technical team for assistance."

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
The first tests of restic look promising and I'm looking forward to use it for our backups.

**Comment by fd0** [comment] 2020-11-25 15:18
Huh, this is odd.

restic keeps a pool of active connections around for a while and closes them if they aren't needed any more. If the TCP connections are closed by the server (as the support suggests), then I'd expect a different error than read timeout.

Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

You can also try modifying restic's client-side timeout here:

https://github.com/restic/restic/blob/9a97095a4c75e587c8b07e1df8304c08f95c160f/internal/backend/http_transport.go#L75

**Comment by ralphhaselbach** [comment] 2020-11-30 14:07
I tried to rebuild restic with the debug tag however I get the following error message:
`root@server:/home/ralph/restic# go run build.go -tags debug
# github.com/restic/restic/cmd/restic
cmd/restic/cmd_debug.go:90:14: assignment mismatch: 2 variables but pack.List returns 3 values
build failed: exit status 2
exit status 1
`

Also I tried to modify the timeout and rebuild restic without the debug tag but that didn't solve the issue.

**Comment by MichaelEischer** [comment] 2020-12-02 22:00
@ralphhaselbach The build failure of the debug version is fixed by now. You should be able to compile a debug build again. Which go version are you using exactly?

**Comment by ralphhaselbach** [comment] 2020-12-04 09:27
Rebuilding with the debug tag worked now. Please find attached the generated log file.
(File was too big to upload, 26MB, so I deleted lines that seemed not important and replaced it with the text "similar lines -->"

The following go version was used to build the latest version: go version go1.15.5 linux/amd64
[restic-debug_redacted_2.log](https://github.com/restic/restic/files/5641483/restic-debug_redacted_2.log)

**Comment by MichaelEischer** [comment] 2020-12-05 19:38
@ralphhaselbach Can you provide a log with all lines containing either `	212	` (that's a tab before and after the number) or `7de1302b41`? The read timeout error is reported at `2020/12/04 08:40:49` but the request itself was sent before `2020/12/04 08:39:45` at which point the log was cut.

Did you see **any** `returned error, retrying after` lines printed on the terminal? Restic should normally retry failed uploads for exactly 10 times. I don't see any of that in the log or your initial issue description. But at the same time I don't have the faintest clue how it could be possible to bypass the upload retries.

**Comment by ralphhaselbach** [comment] 2020-12-07 08:52
@MichaelEischer I've attached the two log files containing only the lines with these numbers.
[restic-debug-212.txt](https://github.com/restic/restic/files/5651221/restic-debug-212.txt)
[restic-debug-7de1302b41.txt](https://github.com/restic/restic/files/5651244/restic-debug-7de1302b41.txt)

I'm not aware of any of these lines printed on the terminal. For the console output in my initial description I've copied all displayed output and I haven't seen any other error messages.

**Comment by MichaelEischer** [comment] 2020-12-08 21:54
The most relevant part from the logs is this:
```
Line 44735: 2020/12/04 08:23:20 s3/s3.go:260	s3.(*Backend).Save	212	Save <data/7de1302b41>
Line 46279: 2020/12/04 08:23:28 s3/s3.go:274	s3.(*Backend).Save	212	PutObject(BUCKET_NAME, data/7d/7de1302b418eb57f96c011a3f3c15fd8a77aa29471ed547069ad58cd7b6a0269, 5419834)
Line 46290: 2020/12/04 08:23:28 debug/round_tripper_debug.go:82	debug.loggingRoundTripper.RoundTrip	212	------------  HTTP REQUEST -----------
Line 247755: 2020/12/04 08:40:49 debug/round_tripper_debug.go:87	debug.loggingRoundTripper.RoundTrip	212	RoundTrip() returned error: read tcp SERVER_IP_ADDRESS:41620->130.117.252.17:443: read: connection timed out
Line 247756: 2020/12/04 08:40:49 s3/s3.go:277	s3.(*Backend).Save	212	data/7d/7de1302b418eb57f96c011a3f3c15fd8a77aa29471ed547069ad58cd7b6a0269 -> {   0 0001-01-01 00:00:00 +0000 UTC   0001-01-01 00:00:00 +0000 UTC } bytes, err &url.Error{Op:"Put", URL:"https://s3.eu-central-1.wasabisys.com/BUCKET_NAME/data/7d/7de1302b418eb57f96c011a3f3c15fd8a77aa29471ed547069ad58cd7b6a0269", Err:(*net.OpError)(0xc000030460)}: Put "https://s3.eu-central-1.wasabisys.com/BUCKET_NAME/data/7d/7de1302b418eb57f96c011a3f3c15fd8a77aa29471ed547069ad58cd7b6a0269": read tcp SERVER_IP_ADDRESS:41620->130.117.252.17:443: read: connection timed out
```
Which shows that it took 17 minutes (!) for the request to fail. It might be the case that during the last 60 seconds of the upload nothing happened such that the connection was closed on the serverside. The question that remains is why this is happening, along with why is the request not retried by restic.

**Comment by MichaelEischer** [comment] 2020-12-08 22:06
I just found the reason for the second part problem: The exponential back-off used by the `RetryBackend` has a `DefaultMaxElapsedTime` of 15 minutes. It limits how long all retries may take in total. And as the first request takes longer than 17 minutes there won't be any retry.

So we can essentially do three things: Introduce some timeouts based on a minimum upload like 20kb/s (I'm not sure what a good minimum upload speed would be), configure the backoff algorithm to allow longer delays and/or find out why the slow uploads are happening in the first place.

**Comment by ralphhaselbach** [comment] 2020-12-15 13:37
Hi, I'm not sure if I have to do something now, do you need any more information from me or is there something I should try?

**Comment by MichaelEischer** [comment] 2020-12-15 20:42
@ralphhaselbach I was mostly thinking aloud. The most interesting part would be knowing how these slow requests behave exactly, that is are they stuck from the start or somewhere in the middle or was the upload completed but didn't get a reply from wasabi. That would however first require a simpler way to reproduce which produces a smaller log file.

Could you try passing `-o s3.connections=1` to restic? That should limit the number of uploads to one at a time, such that restic is completely stuck while a request is hanging. With that it might be possible to either add additional logging / use tcpdump or similar to get a close look at how much data is transferred.

**Comment by ralphhaselbach** [comment] 2020-12-23 12:05
@MichaelEischer I've run restic again with the mentioned parameter and attached the debug log: [restic-debug-4-redacted.log](https://github.com/restic/restic/files/5728402/restic-debug-4-redacted.log)

Let me know if I can do something.

**Comment by MichaelEischer** [comment] 2020-12-31 15:58
Thanks for the log. The hanging upload is much better visible than before. However, that doesn't shed more light at what's wrong. Once the backup hangs you could try to use `tcpdump host 123.456.789.012` (with the correct wasabi S3 server IP) to check whether there's still some communication happening with the wasabi server. `netstat -nt` should show to which IP restic is currently connected. Maybe that output something interesting. Or nothing at all...

**Comment by MichaelEischer** [comment] 2021-01-08 22:51
@ralphhaselbach I've another thing you could try: run a backup with `-o s3.connections=1` and send a `SIGABRT` signal to restic when it hangs, which will kill restic and print a stacktrace.

**Comment by ralphhaselbach** [comment] 2021-02-02 08:21
@MichaelEischer Sorry, I didn't have the time to look into this until now. It works now, without updating restic since the last time I've tried it. As there was a change to our firewall since then I think it was either an issue with the firewall or with the Wasabi cloud storage.
It works now with and without the `-o s3.connections=1` option.

**Comment by MichaelEischer** [comment] 2021-02-07 17:23
Thanks for the feedback. Then let's close this issue for now as we have no way of reproducing it. Feel free to reopen it if the problem shows up again.

**Closed by MichaelEischer** 2021-02-07 17:23 UTC
Labels: state: need feedback
