### ISSUE TITLE
Being able to backup files from SFTP to a repository

### ISSUE THREAD

**Issue by Ethorbit** [restic/restic#4030] opened 2022-11-22 04:07 UTC
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Currently you can manage repositories over SFTP and on a local filesystem, but Restic doesn't seem to have any built-in functionality for BACKING UP SFTP files to a repository. 

While we COULD use a thirdparty tool to create an SFTP mountpoint; SSHFS is buggy, slow and is no longer being developed and Rclone mounts don't preserve permissions and symlinks. I don't see any good way of doing this.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I have rented game servers that are not owned by me (meaning I cannot just install other stuff to make this happen), they only have sshd running, however, I still want to back those servers' files up regularly using Restic. 

Currently I am forced to use a thirdparty tool to synchronize an SFTP directory with a local directory AND THEN back up those files with Restic. The issue with doing this is that you will have to store all files twice - one in the sync dir and one in the Restic repository, which is bad for storage and speed.

By building this functionality into Restic, it would simply make a lot more sense as it already supports an SFTP backend for managing repositories (so why not for backup too?)

**Comment by schmud** [comment] 2022-11-23 10:54
just a suggestion: you could use rclone's ssh/sftp backend to mount the relevant directories and back them up then.

**Comment by greatroar** [comment] 2022-11-23 19:22
Duplicate of #299. See also #2995.

**Comment by MichaelEischer** [comment] 2022-11-25 23:24
Closing as duplicate of #299.

> Hope it gets added soon.

That is rather unlikely. From just a quick look at the problem, we'd have to figure out how to deal with the much higher latency of a remote backup source compared to a local backup source.

**Closed by MichaelEischer** 2022-11-25 23:24 UTC
