### ISSUE TITLE
restic 0.10.0 crashes while pruning

### ISSUE THREAD

**Issue by leapfog** [restic/restic#2953] opened 2020-09-25 10:44 UTC
Output of `restic version`
--------------------------

restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------

    RESTIC_REPOSITORY=rest:http://server:port/name

    RESTIC_PASSWORD_FILE=/path/to/file

    restic --cacert /path/to/file prune

    repository 97010a1b opened successfully, password is correct
    counting files in repo
    building new index for repo
    [2:36] 100.00%  8015 / 8015 packs
    repository contains 8015 packs (476323 blobs) with 35.611 GiB
    processed 476323 blobs: 46 duplicate blobs, 2.047 MiB duplicate
    load all snapshots
    find data that is still in use for 47 snapshots
    [0:07] 2.13%  1 / 47 snapshots
    decrypting blob ab95e14f4ea9e5cb126a9c7xxxxx82c2b11dca2d7be279019d34f4cddeae6fcb failed: ciphertext verification failed
    github.com/restic/restic/internal/repository.(*Repository).LoadBlob
            github.com/restic/restic/internal/repository/repository.go:198
    github.com/restic/restic/internal/repository.(*Repository).LoadTree
            github.com/restic/restic/internal/repository/repository.go:730
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:19
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
            github.com/restic/restic/internal/restic/find.go:31
    main.getUsedBlobs
            github.com/restic/restic/cmd/restic/cmd_prune.go:276
    main.pruneRepository
            github.com/restic/restic/cmd/restic/cmd_prune.go:158
    main.runPrune
            github.com/restic/restic/cmd/restic/cmd_prune.go:62
    main.glob..func19
            github.com/restic/restic/cmd/restic/cmd_prune.go:27
    github.com/spf13/cobra.(*Command).execute
            github.com/spf13/cobra@v1.0.0/command.go:842
    github.com/spf13/cobra.(*Command).ExecuteC
            github.com/spf13/cobra@v1.0.0/command.go:950
    github.com/spf13/cobra.(*Command).Execute
            github.com/spf13/cobra@v1.0.0/command.go:887
    main.main
            github.com/restic/restic/cmd/restic/main.go:86
    runtime.main
            runtime/proc.go:204
    runtime.goexit
            runtime/asm_amd64.s:1374

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rest-server-0.9.7-linux-arm

run as

    rest-server --path /data/restic --private-repos

Expected behavior
-----------------

prune repository, without crashing

Actual behavior
---------------

restic crashes while pruning

Steps to reproduce the behavior
-------------------------------

It happens every time I run the command above (but might be related to my repo, so maybe not easily reproducible)

Do you have any idea what may have caused this?
-----------------------------------------------

I updated to 0.10.0 and successfully pruned once. Note: While pruning, the machine hibernated twice (caused by no user interaction for >20 minutes). Nevertheless this first prune-run seemd to work:

    repository 97010a1b opened successfully, password is correct
    counting files in repo
    building new index for repo
    Load(<data/8a4b026dec>, 0, 0) returned error, retrying after 552.330144ms: Copy: read tcp 192.168.x.y:34378->192.168.x.z:8000: read: connection reset by peer
    [21:32] 100.00%  54152 / 54152 packs
    incomplete pack file (will be removed): 6e39b23cb0905804c96d7edfebd6810be2266cd58f5311972bc833f3185aaf03
    repository contains 54151 packs (2643966 blobs) with 242.635 GiB
    processed 2643966 blobs: 1294136 duplicate blobs, 51.257 GiB duplicate
    load all snapshots
    find data that is still in use for 43 snapshots
    [0:18] 100.00%  43 / 43 snapshots
    found 476213 of 2643966 data blobs still in use, removing 2167753 blobs
    will remove 1 invalid files
    will delete 31540 packs and rewrite 15913 packs, this frees 236.167 GiB
    Load(<data/c85b5ca395>, 0, 0) returned error, retrying after 720.254544ms: read tcp 192.168.x.y:34426->192.168.x.z:8000: read: connection reset by peer
    [2:22:19] 100.00%  15913 / 15913 packs rewritten
    counting files in repo
    [2:48] 100.00%  8006 / 8006 packs
    finding old index files
    saved new indexes as [c434ec9b afe88c50 1201d3be]
    remove 244 old index files
    [0:00] 100.00%  244 / 244 files deleted
    remove 47453 old packs
    [3:32] 100.00%  47453 / 47453 files deleted
    done

Ever since than, pruning crashes as above.

Do you have an idea how to solve the issue?
-------------------------------------------

No, but so far I checked the repo:

    restic check

    using temporary cache in /tmp/restic-check-cache-604690955
    repository 97010a1b opened successfully, password is correct
    created new cache in /tmp/restic-check-cache-604690955
    create exclusive lock for repository
    load indexes
    check all packs
    check snapshots, trees and blobs
    no errors were found

    restic check --read-data

    using temporary cache in /tmp/restic-check-cache-836105701
    repository 97010a1b opened successfully, password is correct
    created new cache in /tmp/restic-check-cache-836105701
    create exclusive lock for repository
    load indexes
    check all packs
    check snapshots, trees and blobs
    read all data
    [1:06:27] 100.00%  8015 / 8015 packs
    no errors were found

and I run psha on the rest-server machine. There were no complains (except for the config file).

I also tried

    restic find --blob ab95e14f4ea9e5cb126a9c74444482c2b11dca2d7be279019d34f4cddeae6fcb

and got

    repository 97010a1b opened successfully, password is correct
    Unable to load tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
    ... which belongs to snapshot 0c1ccb96014259f42fa9377956f447593437d89d419f2371b0e413ec163bc11a.
    Unable to load tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
    ... which belongs to snapshot 4c67a5ef95c027f41cbb76d0d10ba30bcc343e96212c9f989f2ae9a6d8e1d39a.
    Unable to load tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
    ... which belongs to snapshot f86bc17739745459479518deb31deb6f5aafbb009f7e667bab4dfe4d6d93d73d.

followed by

    restic find --tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0

    repository 97010a1b opened successfully, password is correct
    Found tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
     ... path /usr/share/libreoffice/help/media/icon-themes
     ... in snapshot 0c1ccb96 (2020-07-15 00:00:02)
    Found tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
     ... path /usr/share/libreoffice/help/media/icon-themes
     ... in snapshot 4c67a5ef (2020-07-15 12:00:01)
    Found tree 44d7f2dcf484b909e15c6480d59ca00c2d1bce649733151e7c9fa5ba223b25e0
     ... path /usr/share/libreoffice/help/media/icon-themes
     ... in snapshot f86bc177 (2020-07-15 15:00:02)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not today, but almost every other day since I came to know restic! I'm running four rest-server's at three different locations doing backups for family and at work. Thanks so much for restic!

**Comment by MichaelEischer** [comment] 2020-09-27 20:45
As `check --read-data` is happy, and the shasum of all data files seems to match, it looks like the repository is intact. There's an important difference between check and prune: The first creates a new temporary cache, while the latter uses the existing one. My assumption would be that the local cache somehow ended up with a corrupt pack file.

Please move the cache to some temporary location and then try the prune command again. `restic cache` also displays the path to the repository caches, you'll need the cache whose folder name starts with `97010a1b`. It would also be interesting to know whether the shasums of the cached files match.

**Comment by leapfog** [comment] 2020-09-28 12:58
I left the affected machine alone after doing what I needed to file the bug report. Today, before trying what you asked for, I run the prune command again to confirm the issue is still there. But it wasn't. I was surprised and repeated the prune command, and there again wasn't an issue. Out of curiosity I run it a third time and got an error similar to the first one:

decrypting blob f964b90196327ab0ee96e4ee87aa86c857d66e2cc21c9d60c47e582d384d55dc failed: ciphertext verification failed

Then I checked the local cache with psha and got

wrong hash for 97010a1b54faee748f9bbd14791d824c146eb6ea4a14aedb6168830255cece9a/data/d9/d9b5a6cf1328b9df4e0e660dd84ed002afe2944ac9150b218c7d3827694623d0: wanted 195be3a3684e181b663320df04131408475295302094a72487dc022c6711d902

Now I renamed the local cache and run prune again. Several times. All without an issue.

I have to mention that scheduled backups have been run in the meantime. Backups, forgets and prunes. I forgot to disable them, but I honestly did not expect them to magically fix whatever was wrong. Did they?

**Comment by MichaelEischer** [comment] 2020-09-30 14:31
Hmm, a possible explanation might be that the repository contained multiple duplicates of the blob. And depending on whether prune processes the broken or the intact one first, it fails or not.

restic is able to repair/prune a damaged repository once all damaged snapshots were removed from the repository. So a call to `forget` in the background could also fix problems. However, in that case they shouldn't reappear.

**Comment by tonoriesco** [comment] 2020-10-01 00:08
Just a comment. I think I seeing a similar behaviour...
I'm running a script to do backups and another to "forget" that runs once per week.
In the last run (with the new restic 1.10 in a mac, version from brew) I found in the log something strange, lot of messages:

> pack 2485091c: not referenced in any index
> pack e5240d51: not referenced in any index
> 5289 additional files were found in the repo, which likely contain duplicate data.
> You can run `restic prune` to correct this.

I was surprise because in the forget command I have the `--prune` flag!
I re-run manually the script and the same results all time.

Finally I run manually `restic prune` and everything was repaired. The last backups were a bit chaotic because loosing HD's, external connections, etc. Probably the backup was a bit corrupt, I don't know, but the prune didn't work when specified from the forget command.

Regards.

**Comment by MichaelEischer** [comment] 2020-10-01 08:25
> pack 2485091c: not referenced in any index
> pack e5240d51: not referenced in any index
> 5289 additional files were found in the repo, which likely contain duplicate data.
> You can run `restic prune` to correct this.

This is just a warning, as long as the check command completes with a `no errors were found` line then your repository is fine. This can be caused by e.g. a few interrupted backup runs. Although 5k additional files are quite a lot.
`forget --prune` only runs `prune` if it removed some snapshots.

**Comment by tonoriesco** [comment] 2020-10-01 08:31
Thank you for the explanation.

Effectively, the backup was interrupted several times and is not at all the fault of restic.
In any case, `restic prune`, worked perfectly.

**Comment by MichaelEischer** [comment] 2021-01-08 21:29
@leapfog Any chance you still have the renamed repository cache with the damaged data file along with the intact one? I noticed that it could have been interesting to investigate what happened to the damaged data file in the cache. The interesting pieces would be whether the file sizes are identical and if yes, what has changed (e.g. by taking a look at the output of `diff <(xxd orig) <(xxd broken)`. I'm mostly interested in whether a single byte, multiple byte or a whole block has changed. The actual encrypted bytes aren't that relevant).

If you don't have that file anymore, then I'd suggest to close this issue as there's nothing left to investigate.

**Comment by MichaelEischer** [comment] 2021-05-15 11:12
Closing this issue as there has been no feedback.

**Closed by MichaelEischer** 2021-05-15 11:12 UTC
Labels: category: prune, state: need feedback, state: need investigating
