### ISSUE TITLE
pack 46c8b832 contained in several indexes

### ISSUE THREAD

**Issue by domsl** [restic/restic#698] opened 2016-12-14 17:28 UTC
## Output of `restic version`
restic 0.3.0
compiled at 2016-10-23 23:10:15 with go1.6.2 on linux/amd64

## Behavior
Was running check and got:
```
/opt/restic/restic -r bckp_files/ check
enter password for repository: 
Create exclusive lock for repository
Load indexes
pack 46c8b832 contained in several indexes: {aa8a11da e02b50bd}

run `restic rebuild-index' to correct this
Check all packs
Check snapshots, trees and blobs

```

Now I am worried and I could not find any similar issue..

What does it mean?
Should I just run 
`restic rebuild-index`
and not be worried?

**Comment by fd0** [comment] 2016-12-14 18:34
Oh, interesting, thanks for reporting! I thought I had tackled this bug a long time ago.

You do not need to worry, restic tells you that it has some redundant meta-information saved in the index. You can run `rebuild-index` or `prune`, both will write a new index. But the repo will work just fine even with the redundant information.

**Comment by domsl** [comment] 2016-12-14 22:20
Thank you for the quick reply. Alright that is reassuring - I fixed it now with rebuild-index.

Restic is awesome - thanks for making it. :)

**Comment by zcalusic** [comment] 2016-12-22 19:57
Just hit the same today:
```
pack 3ede1ba8 contained in several indexes: {55e19faf 898e417b}
pack 16963b89 contained in several indexes: {df0f1009 e9c1e3b1}
```

If the info is useful, this were two backups right after the first run ended (~ 100GB of data). Went at blazing 3GB/sec, and left a signature. ;)

**Comment by supermarin** [comment] 2016-12-24 23:48
Same issue. backed up ~200GB data, plugged in the disk in a different box and ran `restic check`. 
Didn't expect this from a freshly created backup

**Comment by lpar** [comment] 2017-06-26 14:10
Just ran into this running restic for the first time.

**Comment by mholt** [comment] 2017-06-27 22:30
Seeing the same thing here on a brand new backup. `rebuild-index` works, but as others have said, not quite expected on a fresh backup that had no errors. Glad it's not a big problem but would be some nice "polish" for the software to have.

(FWIW, that's 2+ million files, or 132,074 packs, totaling about 800 GB backed up in about 2 and a half hours. Pretty impressive.)

Just out of curiosity, what causes this? Is running `rebuild-index` after each backup necessary to optimize the indices?

**Comment by fd0** [comment] 2017-07-01 07:29
> Glad it's not a big problem but would be some nice "polish" for the software to have.

Definitely, I agree. It bugs me a lot that this isn't fixed yet.

> Just out of curiosity, what causes this? Is running `rebuild-index` after each backup necessary to optimize the indices?

Not at all. The underlying problem is that the index handling and managing newly uploaded blobs during the backup process is tightly integrated with the archiving part of restic. That's rather ugly (the oldest part of the code) and **way** too complex, and over time I've tried several times to get including new blobs/pack files right, apparently there's still an issue. I'll do a new release of restic in the next couple of days, afterwards I'll rework the archiver and index handling system.

In the meantime, we could also remove the warning from the output of `check`, because it needlessly scares users. It's not a problem at all that a file is contained in multiple indexes, just a hint for me that there may be still an issue.

**Comment by mholt** [comment] 2017-07-01 14:15
Great explanation -- thanks! Also, congrats on today's 0.7 release!

**Comment by fd0** [comment] 2017-07-01 14:20
thanks!

**Comment by mholt** [comment] 2017-07-01 14:22
(@fd0 Speaking of releases, don't forget to release the restic Caddy plugin! :wink:)

**Comment by fd0** [comment] 2017-07-01 15:51
I haven't forgotten ;)

**Comment by tveastman** [comment] 2017-11-12 03:31
After doing a large initial backup (398gb) onto an NFSv4 share that finished cleanly in about two hours, I ran `restic check` and had quite a few of these.

```
Create exclusive lock for repository
Load indexes
pack ba9aa2fa contained in several indexes: {4ca53d19 8425e57f}
pack 43847a86 contained in several indexes: {6c96348b 79992e4f}
pack 8668d478 contained in several indexes: {8425e57f adc7e55f}
pack f9385d8f contained in several indexes: {049b05a8 8425e57f}
pack f21701af contained in several indexes: {43c4d565 79992e4f}
pack e3329571 contained in several indexes: {98d3fa65 b5c87d56}
pack c306034c contained in several indexes: {686aab68 98d3fa65}
pack 44c0a49c contained in several indexes: {7735660b 79992e4f}
pack 00871777 contained in several indexes: {79992e4f 9475e46c}
pack a7b86e4a contained in several indexes: {369e23ba 8425e57f}
pack 23334e9d contained in several indexes: {4260799e f17af9f7}
pack a56b43b6 contained in several indexes: {02143cda 8425e57f}
pack 1728ee0a contained in several indexes: {98d3fa65 acce117d}
pack 43be4918 contained in several indexes: {686fde22 98d3fa65}
pack 6a971345 contained in several indexes: {79992e4f 9525cd29}
pack 35a461c4 contained in several indexes: {8425e57f e950c2cf}
pack 5e7f6836 contained in several indexes: {79992e4f c40af58a}
pack 9f812974 contained in several indexes: {50812b40 98d3fa65}
pack c84e3403 contained in several indexes: {79992e4f ad84029a}
pack 3c7e5e2b contained in several indexes: {6fd89cd4 7867acae}
pack 271cd8b2 contained in several indexes: {03d8046e 7867acae}
pack 948b42e6 contained in several indexes: {242e4e8e 98d3fa65}
pack a987c9c0 contained in several indexes: {8425e57f d8d9c808}
pack dbf0d98b contained in several indexes: {7867acae bfbb2b4b}
pack cb296203 contained in several indexes: {8425e57f 909b7f11}
pack 6b62b032 contained in several indexes: {6f1aeb02 8425e57f}
pack 84b61e5a contained in several indexes: {3b05c46c 8425e57f}
pack 3ab33e35 contained in several indexes: {016d4b1b 98d3fa65}

run `restic rebuild-index' to correct this
Check all packs
Check snapshots, trees and blobs
```

**Comment by rawtaz** [comment] 2020-02-13 02:22
This [might still be a thing](https://forum.restic.net/t/dropped-packets-while-backing-up-causes-errors-in-archive/1821/6) although I'm not seeing much of this error message in other reports nowadays. Perhaps it got semi-squashed with the new archiver code in restic 0.9.0 that was released in may 2018.

**Comment by MichaelEischer** [comment] 2020-02-24 20:15
This bug still exists. The problem is that `packerManager.savePacker` adds the packs one after another to the index. If an intermediate index upload is triggered at the same time, then the blobs could be stored in different indexes.
Thanks @aawsome for accidentally (?) fixing this issue with `StorePack` in #2523 .

I'd propose to split off a basic implementation of `StorePack` that just gets a list of `restic.PackedBlob` from the index rewrite and fix this issue here rather sooner than later.

There's also another closely related race condition between `repository/Index.Store` and `Index.Finalize`: Suppose a call to `Store` blocks before acquiring the mutex, then the Index is `Finalize`d and voila the store method invokes `panic`. The easiest fix is probably to have the methods `MasterIndex.NotFinalIndexes` and `MasterIndex.FullIndexes` already finalize the indexes while holding `mi.idxMutex`.

**Comment by aawsome** [comment] 2020-02-24 20:49
This fix was not intended :smile: 

I would however question if the fact that a pack is contained in several indices really is a bug. IMO it is not necessary that a pack is completely saved in one index file. I however don't know where there are code parts which assume that complete packs are not spread over more than one index. I know about `Load`/`AddPack` in `internal/index/index.go`.

I personally would claim code that cannot treat this case as "buggy" and remove this check from the `check` command. Actually, the `cleanup-packs` command in #2513 may also produce packs that are spread over many indices...

**Comment by MichaelEischer** [comment] 2020-03-04 22:14
`repository/MasterIndex.ListPack` also assumes that all parts of a pack end up in the same index. But it seems to be only used by a test case, so it can just be removed. My suggestion would be to have both: Let commands try to store all blobs of a pack in the same index file, but still make sure that the code can handle cases where a pack is contained in multiple indexes. The latter case should be rather easy to trigger by killing restic while it rebuild the index.

The reason why I would prefer to store a pack in a single index, is that this limits how many indexes you have to rewrite (to one) when a pack file has to be modified. If I understand the implementation of your `cleanup-packs` command correctly you could also just remove the old rewritten packs from their index and add all new packs to new index files.

That is the full fix for this issue would be to port your `StorePack` implementation, fix the index finalization race condition, fix `index/index.Load/AddPack` to handle packs contained in multiple indexes, remove the check warning and add some documentation that packs can be contained in multiple indexes.

**Comment by aawsome** [comment] 2020-07-09 18:03
> That is the full fix for this issue would be to port your `StorePack` implementation, fix the index finalization race condition

This is already in master

> fix `index/index.Load/AddPack` to handle packs contained in multiple indexes, remove the check warning and add some documentation that packs can be contained in multiple indexes.

This is still open but I think that `internal/index` can anyway be removed soon (my prune reimplementation doesn't use it and after that is merged we can rewrite `rebuild-index` to also just use `internal/repository`).

The bug might be also coming from #2824 i.e. an superseded index file that for some reason has not been deleted.

**Comment by MichaelEischer** [comment] 2020-12-11 19:00
Closing this as now with #2842 and #3006 being merged, all problematic have been replaced or rewritten. I still want to keep the check for packs in multiple indexes as this now serves as a bug check (and in fact has helped me find one some time ago).

**Closed by MichaelEischer** 2020-12-11 19:00 UTC
Labels: category: backup, type: bug
