### ISSUE TITLE
TestMount and TestMountSameTimestamps tests fails

### ISSUE THREAD

**Issue by stkw0** [restic/restic#3901] opened 2022-08-28 18:40 UTC
Output of `restic version`
--------------------------
0.14.0

How did you run restic exactly?
-------------------------------
go test -timeout 30m -v -work -x ./cmd/... ./internal/...

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Not apply

Expected behavior
-----------------
Test pass

Actual behavior
---------------
Test didn't pass. I am using fusermount version 2.9.9

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes :)

**Comment by MichaelEischer** [comment] 2022-08-28 20:17
Please provide more details on your system setup and the full error output generated by the tests. My system using Arch Linux also uses fusermount version 2.9.9 and for me the whole test suite works correctly.

**Comment by stkw0** [comment] 2022-08-28 20:43
Sorry I forgot to add the output on the last comment, here it is the output of the two tests:

```
=== RUN   TestMount
    testing.go:31: using low-security KDF parameters for test
    config.go:74: disabling check of the chunker polynomial
    testing.go:31: using low-security KDF parameters for test
    config.go:74: disabling check of the chunker polynomial
    lock.go:80: setting lock timeout to 0s
    integration_test.go:56: repository initialized at /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-2113816379/repo
    integration_fuse_test.go:87: checking for 0 snapshots: []
integration_fuse_test.go:60: unexpected error: fusermount: exit status 1

    integration_fuse_test.go:53: subdir "snapshots" of dir /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-2113816379/mount never appeared
    integration_fuse_test.go:94: virtual directory "snapshots" doesn't exist
    integration_fuse_test.go:74: unable to umount dir /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-2113816379/mount, last error was: exit status 1: fusermount: failed to unmount /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-2113816379/mount: Operation not permitted
--- FAIL: TestMount (4.30s)
=== RUN   TestMountSameTimestamps
    testing.go:31: using low-security KDF parameters for test
    config.go:74: disabling check of the chunker polynomial
    integration_fuse_test.go:87: checking for 3 snapshots: [28030368 75ad6cdc 5fd0d8b2]
integration_fuse_test.go:60: unexpected error: fusermount: exit status 1

    integration_fuse_test.go:53: subdir "snapshots" of dir /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-1841085805/mount never appeared
    integration_fuse_test.go:94: virtual directory "snapshots" doesn't exist
    integration_fuse_test.go:74: unable to umount dir /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-1841085805/mount, last error was: exit status 1: fusermount: failed to unmount /tmp/portage/app-backup/restic-0.14.0/temp/restic-test-1841085805/mount: Operation not permitted
--- FAIL: TestMountSameTimestamps (4.05s)
```

**Comment by stkw0** [comment] 2022-08-28 20:55
btw is there a way to exclude a given test from the test case?

**Comment by MichaelEischer** [comment] 2022-08-29 20:01
You can set the environment variable `RESTIC_TEST_FUSE` to `false` or `0`.

Judging from the paths in the log output you're using Gentoo?

Does `restic mount /some/path` show any useful error message?

If not my next suggestion would be to use strace to take a look at what's happening:
```
go test -c ./cmd/restic
cd cmd/restic
strace -ff ../../restic.test -test.run '^TestMount$'
```
As fusermount is normally a setuid-binary you'll probably have to run the last command as root to work.

**Comment by MichaelEischer** [comment] 2022-10-16 10:06
I'm closing this issue as I cannot reproduce it and the requested in formation was not provided. Feel free to reopen it when you can provide more information.

**Closed by MichaelEischer** 2022-10-16 10:06 UTC
Labels: state: need feedback
