### ISSUE TITLE
Add support for "**" in exclude filters

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1178] opened 2017-08-26 00:16 UTC
My use case is, that I'd like to make a full backup of a system, but exclude the contents of certain folders like /dev, /run, /tmp or /proc, while the folders themselves should be included in the backup.

Using ```--exclude /proc``` does not deliver the desired result, as this also excludes the folder itself (but I want to have this empty folder on a restore).
Using ```--exclude /proc/*``` does not work either. While this includes the folder, it also includes subdirectories of /proc, like /proc/1/

rsync provides an exclude filter which I've been using so far with my rsnapshot based backup, which does give me the desired results:
See https://download.samba.org/pub/rsync/rsync.html → INCLUDE/EXCLUDE PATTERN RULES
```use '**' to match anything, including slashes. ```

Please consider implementing "**" for exclude filters in restic as well.

**Comment by fd0** [comment] 2017-08-26 10:29
The command `restic backup --exclude '/proc/*' /` (mind the quotes around `/proc/*`) does exactly what you want: Backup everything in `/` including the directory `/proc`, but not the contents of `/proc`. I'm not entirely sure what happened for you, but I have a hunch something like this happened:
 * You ran `restic backup --exclude /proc* /` 
 * Your shell expanded this to: `restic backup --exclude /proc/1 /proc/123 /proc/124 [...] /`
 * So restic happily saved most of the contents of `/proc` (because it was specified in the list of dirs to be saved), except `/proc/1`, which was excluded.

Please note that `**` is already implement (e.g. `--exclude '/root/**/id_rsa'` excludes all ssh keys in all dirs below `/root`), but you need to guard it from the shell so that restic receives the pattern in verbatim.

I'm going to close this for now as I think the issue is already resolved. Please feel free to add further comments (especially if you have an idea on how to improve the documentation!). Thanks!

**Closed by fd0** 2017-08-26 10:29 UTC

**Comment by fd0** [comment] 2017-08-26 10:39
Ah, another thought: If you use a file to read the exclude patterns from (with `--exclude-file`) you don't need to quote it since the shell is not in the loop for this. That's probably easier.

**Comment by mbiebl** [comment] 2017-08-26 19:03
Hm, you're right. I was pretty sure I did quote the argument properly, but apparently I did not.
Sorry for the noise and thanks for the hint regarding --exclude-file, that looks useful.
