### ISSUE TITLE
Fatal: wrong password or no key found  (systemd)

### ISSUE THREAD

**Issue by LanceHaverkamp** [restic/restic#2256] opened 2019-04-27 03:15 UTC
Restic is working GREAT from a simple script!!!
Not having any success automating it with systemd: 

Using restic 0.9.4 compiled with go1.10.7 on linux/amd64 (Fedora 28)

Trying to run Restic with systemd it's failing to login to B2, but can login just fine using a script.
I'm getting the following error when I watch the process in real time:
```
Apr 26 20:40:52 localhost.localdomain restic[10867]: open repository
Apr 26 20:40:54 localhost.localdomain restic[10867]: Fatal: wrong password or no key found
Apr 26 20:40:54 localhost.localdomain systemd[1201]: restic-backup.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 20:40:54 localhost.localdomain systemd[1201]: restic-backup.service: Failed with result 'exit-code'.
Apr 26 20:40:54 localhost.localdomain systemd[1201]: Failed to start Backup with restic before shutdown.
```

Here's the service:
```
[Unit]
Description=Backup with restic before shutdown
Before=poweroff.target halt.target

[Service]
Type=oneshot
ExecStart=/usr/bin/restic backup --verbose --one-file-system --tag systemd.shutdown $BACKUP_EXCLUDES $BACKUP_PATHS
ExecStartPost=/usr/bin/restic forget --verbose --tag systemd.shutdown --group-by paths,tags --keep-daily $RETENTION_DAYS --keep-weekly $RETENTION_WEEKS --keep-monthly $RETENTION_MONTHS --keep-yearly $RETENTION_YEARS
EnvironmentFile=%h/.config/restic-backup.conf

[Install]
WantedBy=poweroff.target halt.target 
```

Here's the EnvironmentFile
```
BACKUP_PATHS="/home/lance"
BACKUP_EXCLUDES="--exclude-file /home/lance/restic-excludes.txt --exclude-if-present .exclude_from_backup"
RETENTION_DAYS=7
RETENTION_WEEKS=4
RETENTION_MONTHS=6
RETENTION_YEARS=3
B2_ACCOUNT_ID=aaaaaaaaaaa
B2_ACCOUNT_KEY=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
RESTIC_REPOSITORY="b2:ccccccccccccccccccc"
RESTIC_PASSWORD="dddddddddddddddddddddddddddddddd"

```

Any suggestions?

**Comment by fd0** [comment] 2019-04-27 07:44
The [forum](https://forum.restic.net) would have been a better place to ask this, we're using the issue tracker on GitHub for bugs and feature requests only. You're describing a usability issue with systemd timers, which is not a bug or feature for restic. Unfortunately, you also did not fill out the issue template.

I don't see anything obviously wrong, maybe it's a quoting issue for the password? Maybe you included double quotes when initializing the script?

From the output of restic I can see that it is able to download files from B2, so the environment variables for B2 are in place and working. I don't know why it does not pick up the password. Are you sure it's the correct one?

What you could try is writing the password to a file, then try to use that with `--password-file`, from the command line as well as via a timer. Maybe that helps.

I'm closing this issue since it's not a bug or feature request for restic. Please feel free to add further comments. If you want to reach a wider audience of restic users (who might have an idea what's going on), please use [the forum](https://forum.restic.net). Thanks!

**Closed by fd0** 2019-04-27 07:44 UTC

**Comment by LanceHaverkamp** [comment] 2019-04-27 15:51
It is a quoting issue, I had special characters in my restic password which would work in a script; but I now see that systemd can't handle quotes in the password.  I changed the password to alphanumeric characters only, which has solved the problem.   Thanks!!!
