### ISSUE TITLE
Omit "unchanged" dirs (files as well) when using -vv option or add option to print important changes only

### ISSUE THREAD

**Issue by mrkafk** [restic/restic#3998] opened 2022-11-03 07:18 UTC
Output of `restic version`
--------------------------

```
unchanged /export/screenlog.0
unchanged /export/public/acme
new       /export/public/newfile
modified  /export/public/testfile, saved in 109.562s (0 B added, 0 B stored, 522 B metadata)
modified  /export/, saved in 117.857s (0 B added, 0 B stored, 787 B metadata)
```

*What should restic do differently? Which functionality do you think we should add?*

`-vv` option causes printing a lot of redundant "unchanged" lines. 

I'd like to track what files are new and modified, but without deleting extraneous lines in output in scripts.

There's some other output when using `-vv` which is not really necessary just to track the changed files. E.g.

```
Files:           0 new,     0 changed, 629314 unmodified
Dirs:            0 new,     4 changed, 129965 unmodified
Data Blobs:      0 new
Tree Blobs:      3 new
Added to the repository: 3.554 KiB (1.559 KiB stored)
```
That's noise I don't really need. I'd only leave those two lines in place:

```
processed 629314 files, 718.570 GiB in 2:06
snapshot b5e85757 saved
```

Seeing how much time the backup took is nice and can be important; and snapshot ID is also good to see in a log when resolving problems or restoring files from backup.

Yes, I can pipe restic output or redirect it to temporary file and do deleting unimportant lines there, but that means some hassle every time I use restic in scripts. Using a command in straightforward manner is nice.

It's not really necessary to modify `-vv` option, but adding an option like `--log-changes` or `--print-changes` or `--print-important-changes` perhaps to track just the changed/new files would be nice.

----------------------------------------------------------------------------------

*What are you trying to do? What problem would this solve?*

I want to log important changes *only* of the directories and files that are backed up. "unchanged" entries are not important.

---------------------------------------------------------

**Comment by MichaelEischer** [comment] 2022-11-04 21:03
This is a duplicate of #3540 and #1805. For now the solution is to create a wrapper script which filters the output accordingly.

**Closed by MichaelEischer** 2022-11-04 21:03 UTC
