### ISSUE TITLE
restore doesn't restore changed files

### ISSUE THREAD

**Issue by Animedium** [restic/restic#547] opened 2016-07-25 14:22 UTC
## Output of `restic version`

restic 0.1.0 (1869591-dirty)
compiled at 2016-07-13 10:24:33 with go1.6.2

Environment: GNU/Linux
## Expected behavior

After restore all files will return to the state from time snapshot was taken.
## Actual behavior

After restore, files with changes were not restored properly. Changes persist after restore or file after restore is mixed.
## Steps to reproduce the behavior
1. Create directory tree

```
/temp
└── RESTIC
    ├── BACKUP
    └── FILES
        ├── Dir01
        │   ├── test01.txt
        │   ├── test02.txt
        │   └── test03.txt
        ├── Dir02
        │   ├── test01.txt
        │   ├── test02.txt
        │   └── test03.txt
        └── Dir03
            ├── test01.txt
            ├── test02.txt
            └── test03.txt
```

In this example all test files contain one line of text like:
`This is content of file Dir01/test01.txt`
1. Initiate repository in BACKUP directory and take backup of FILES directory
2. Modify some test files so the content will look like this (cat command):
3. Dir01/test01.txt:

```
only with line before
This is concent of file Dir01/test01.txt
```
- Dir01/test02.txt

```
This is concent of file Dir01/test02.txt
only line after
```
- Dir02/test01.txt

```
line before
string before   This is concent of file Dir02/test01.txt    string after
line after
```
1. Restore latest backup to --target /temp/RESTIC

RESULT of cat command on files:
- Dir01/test01.txt

```
This is concent of file Dir01/test01.txt
file Dir01/test01.txt
```
- Dir01/test02.txt

```
This is concent of file Dir01/test02.txt
only line after
```
- Dir02/test01.txt

```
This is concent of file Dir02/test01.txt
 of file Dir02/test01.txt   string after
line after
```

**Comment by fd0** [comment] 2016-07-26 12:06
Hey, thanks for reporting this. I find your report confusing, can you try to elaborate what the undesired behavior is?

Regarding the file `Dir02/test01.txt`: Are you sure that the content was 
```
line before
string before   This is concent of file Dir02/test01.txt    string after
line after
```
when running the second backup and
```
This is concent of file Dir02/test01.txt
 of file Dir02/test01.txt   string after
line after
```
after restore?

Can you create a tar of the restic repository and upload it somewhere for me so I can investigate?

**Comment by Animedium** [comment] 2016-07-26 13:47
Here is repository:
[restic_repo.zip](https://github.com/restic/restic/files/383914/restic_repo.zip)

There is no second backup in this test scenario, only one backup and one restore.

So simplified steps look like this:
1. Create environment (files + repository)
2. Take backup
3. Make changes to files
4. Restore from backup

And the undesider behavior is that modified files are not returned to they original versions by restore.

In example of file `Dir02/test01.txt` content will change like this after every step:
1.Creation of file:
```
This is concent of file Dir02/test01.txt
```

2.No changes:
```
This is concent of file Dir02/test01.txt
```

3.Make changes:
```
line before
string before   This is concent of file Dir02/test01.txt    string after
line after
```

4.After restore:
```
This is concent of file Dir02/test01.txt
 of file Dir02/test01.txt   string after
line after
```

**Comment by fd0** [comment] 2016-07-26 14:47
Thanks, I'll have a look. What's the password used for the repo?

**Comment by Animedium** [comment] 2016-07-26 16:19
password is: test01

**Comment by fd0** [comment] 2016-07-27 06:07
What version of restic is this? The `version` command says it's 1869591, but I'm unable to find this commit anywhere.  Can you please paste the output of the following commands:
```
git status
git log --pretty=short origin/master..
```

**Comment by Animedium** [comment] 2016-07-27 11:28
I am really sorry for trouble. I included in report wrong version from different machine where I also tested if this problem is reproducible.

Here is the correct version that I used in this example:
```
restic 0.1.0 (v0.1.0-561-gb8c7622)
compiled at 2016-07-19 16:38:38 with go1.5.1
```

And all commands you asked.
git status
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

git diff is empty

git log --pretty=short origin/master.. is also empty

**Comment by fd0** [comment] 2017-05-14 20:10
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.

**Closed by fd0** 2017-05-14 20:10 UTC
Labels: bug, feedback needed
