### ISSUE TITLE
check and prune ends with "Fatal", print errors, using OVH's Swift backend

### ISSUE THREAD

**Issue by vrischmann** [restic/restic#1860] opened 2018-06-23 17:01 UTC
## Output of `restic version`

    restic 0.9.1 compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?

First I ran `restic forget --keep-daily 7 --keep-weekly 10 --keep-monthly 12`, unfortunately I don't have the output anymore but I know it removed some snapshots.

After I ran `restic prune` which seemed to work.

Then I ran `restic check` which printed a bunch of errors (sorry, don't have the output either).

Finally, now if I ran check I get this:

    using temporary cache in /tmp/restic-check-cache-093480205
    repository 16b9bc64 opened successfully, password is correct
    create exclusive lock for repository
    load indexes
    check all packs
    pack ef469e03: not referenced in any index
    pack e0c863a0: not referenced in any index
    2 additional files were found in the repo, which likely contain duplicate data.
    You can run `restic prune` to correct this.
    check snapshots, trees and blobs
    error for tree cd1aaff0:
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 143 size could not be found
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 144 size could not be found
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 145 size could not be found
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 146 size could not be found
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 147 size could not be found
      tree cd1aaff0: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack": metadata size (354061261) and sum of blob sizes (349517594) do not match
      tree cd1aaff0, blob 41f61c5b: not found in index
      tree cd1aaff0, blob 5c4ce213: not found in index
      tree cd1aaff0, blob ad5cbfbc: not found in index
      tree cd1aaff0, blob f3b1e1cc: not found in index
      tree cd1aaff0, blob 76909a76: not found in index
    error for tree 6663ac19:
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 143 size could not be found
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 144 size could not be found
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 145 size could not be found
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 146 size could not be found
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack" blob 147 size could not be found
      tree 6663ac19: file "pack-a7add597939ebd3f54eb8e6bdf52dcdf1a87ca74.pack": metadata size (354061261) and sum of blob sizes (349517594) do not match
      tree 6663ac19, blob 41f61c5b: not found in index
      tree 6663ac19, blob 5c4ce213: not found in index
      tree 6663ac19, blob ad5cbfbc: not found in index
      tree 6663ac19, blob f3b1e1cc: not found in index
      tree 6663ac19, blob 76909a76: not found in index
    error for tree fd5008e5:
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack" blob 143 size could not be found
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack" blob 144 size could not be found
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack" blob 145 size could not be found
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack" blob 146 size could not be found
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack" blob 147 size could not be found
      tree fd5008e5: file "pack-741019db6f4c11d8bdf23417e938338af74f9f1d.pack": metadata size (354059623) and sum of blob sizes (349515956) do not match
      tree fd5008e5, blob 41f61c5b: not found in index
      tree fd5008e5, blob 5c4ce213: not found in index
      tree fd5008e5, blob ad5cbfbc: not found in index
      tree fd5008e5, blob f3b1e1cc: not found in index
      tree fd5008e5, blob 76909a76: not found in index
    error for tree 1db5a2eb:
      tree 1db5a2eb: file "pack-311f5a07eb1e6932d0e1a8b5ebf8f7b367e7eb89.pack" blob 2 size could not be found
      tree 1db5a2eb: file "pack-311f5a07eb1e6932d0e1a8b5ebf8f7b367e7eb89.pack" blob 6 size could not be found
      tree 1db5a2eb: file "pack-311f5a07eb1e6932d0e1a8b5ebf8f7b367e7eb89.pack" blob 7 size could not be found
      tree 1db5a2eb: file "pack-311f5a07eb1e6932d0e1a8b5ebf8f7b367e7eb89.pack": metadata size (22755569) and sum of blob sizes (18370887) do not match
      tree 1db5a2eb: file "pack-a8856235da7a3505c17bdad8756f5f587c70febd.pack" blob 1 size could not be found
      tree 1db5a2eb: file "pack-a8856235da7a3505c17bdad8756f5f587c70febd.pack": metadata size (2368210) and sum of blob sizes (1360013) do not match
      tree 1db5a2eb, blob 39498cd5: not found in index
      tree 1db5a2eb, blob c45f1f6e: not found in index
      tree 1db5a2eb, blob 27a00591: not found in index
      tree 1db5a2eb, blob 64dd5617: not found in index
    read all data
    [0:47] 100.00%  878 / 878 items
    duration: 0:47
    Fatal: repository contains errors

And if I run `restic prune` I get this:

    repository 16b9bc64 opened successfully, password is correct
    counting files in repo
    building new index for repo
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 331.044657ms: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 561.266802ms: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 326.958564ms: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 1.653941828s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 446.921851ms: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 1.184950781s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 1.991576053s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 2.285664441s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 2.867501263s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 3.105939768s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 3.325044176s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 3.824598567s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 3.755494264s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 6.876366554s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 12.036092651s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 11.767265223s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 15.70085353s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 12.128305337s: conn.ObjectOpen: Object Not Found
    Load(<data/e0c863a075>, 591, 4543457) returned error, retrying after 21.800871483s: conn.ObjectOpen: Object Not Found
    Load(<data/ef469e03f2>, 591, 5392600) returned error, retrying after 27.561846541s: conn.ObjectOpen: Object Not Found
    pack file cannot be listed e0c863a0754823c3ff795c87f1cdfd484e576526825c09f5526f08b33e77d13a: conn.ObjectOpen: Object Not Found
    pack file cannot be listed ef469e03f235ba412f609fa4c750f55d0e3aed4b8010d5d7d42000e68a29ee4b: conn.ObjectOpen: Object Not Found
    [1:30] 100.00%  880 / 880 packs
    repository contains 878 packs (136603 blobs) with 3.951 GiB
    processed 136603 blobs: 0 duplicate blobs, 0B duplicate
    load all snapshots
    find data that is still in use for 8 snapshots
    [0:05] 100.00%  8 / 8 snapshots
    Fatal: number of used blobs is larger than number of available blobs!
    Please report this error (along with the output of the 'prune' run) at
    https://github.com/restic/restic/issues/new

## What backend/server/service did you use to store the repository?

OpenStack Swift hosted by OVH

## Expected behavior

check and prune should not fail.

## Actual behavior

check and prune fail with fatal errors. 

I should note that for the last month or so, I had no problem using this backend.
Also, I can still access the repository (listing snapshots or with mount).

## Steps to reproduce the behavior

Unsure what triggered the problem so I don't know if it's easily reproducible.

## Did restic help you or made you happy in any way?

Sure. restic made it easy to retrieve config files and code repositories after a Ubuntu upgrade made my luks drive inaccessible. Much faster to copy from the mounted repository than recloning 100+ repositories !

**Comment by dimejo** [comment] 2018-06-25 07:41
Unfortunately the OVH swift backend seems to be pretty unreliable as multiple issues on Github are indicating. You can try to run `restic rebuild-index`, but I'm unsure if it helps much.

**Comment by vrischmann** [comment] 2018-06-25 12:16
I did try that and it didn't correct anything yeah.
Sucks that the OVH backend is bad, I'll have to find something else then.

**Comment by fd0** [comment] 2019-04-25 07:22
I think this is caused by the backend service, I'll close this (rather old) issue for now. Please feel free to add further comments. Thanks!

**Closed by fd0** 2019-04-25 07:22 UTC
