### ISSUE TITLE
Forget with grouping by paths produces inconsistent results

### ISSUE THREAD

**Issue by alsimfer** [restic/restic#4484] opened 2023-09-28 12:35 UTC
Output of `restic version`
--------------------------
❯ restic version
restic 0.16.0 compiled with go1.20.6 on linux/amd64

How did you run restic exactly?
-------------------------------
❯ export AWS_ACCESS_KEY_ID=...
❯ export AWS_SECRET_ACCESS_KEY=...
❯ export RESTIC_PASSWORD=...
❯ restic -r s3:https://s3.amazonaws.com/backup/demogp forget --keep-daily 3 --group-by paths --dry-run

```sh
repository e33f06cf opened (version 2, compression level auto)
created new cache in /home/alex/.cache/restic
Applying Policy: keep 3 daily snapshots
keep 3 snapshots:
ID        Time                 Host             Tags                 Reasons         Paths
----------------------------------------------------------------------------------------------------------
c765fbee  2023-09-26 22:23:24  demogp  2023-09-26T20-20-06  daily snapshot  /tmp/index_backup.tgz
7ac44035  2023-09-27 22:23:41  demogp  2023-09-27T20-20-05  daily snapshot  /tmp/index_backup.tgz
3d75fc10  2023-09-28 12:23:43  demogp  2023-09-28T10-20-07  daily snapshot  /tmp/index_backup.tgz
----------------------------------------------------------------------------------------------------------
3 snapshots

remove 81 snapshots:
ID        Time                 Host             Tags                 Paths
------------------------------------------------------------------------------------------
...
3ff64c31  2023-09-25 00:23:05  demogp  2023-09-24T22-20-06  /tmp/index_backup.tgz
a5115adf  2023-09-25 02:23:22  demogp  2023-09-25T00-20-08  /tmp/index_backup.tgz
31c34408  2023-09-25 04:23:20  demogp  2023-09-25T02-20-06  /tmp/index_backup.tgz
260a63c3  2023-09-25 06:23:17  demogp  2023-09-25T04-20-06  /tmp/index_backup.tgz
61dafe9b  2023-09-25 08:23:17  demogp  2023-09-25T06-20-05  /tmp/index_backup.tgz
faf4b844  2023-09-25 10:23:18  demogp  2023-09-25T08-20-05  /tmp/index_backup.tgz
340971f9  2023-09-25 12:23:15  demogp  2023-09-25T10-20-05  /tmp/index_backup.tgz
fea0181a  2023-09-25 14:23:16  demogp  2023-09-25T12-20-06  /tmp/index_backup.tgz
400be127  2023-09-25 16:23:23  demogp  2023-09-25T14-20-06  /tmp/index_backup.tgz
364ad7e3  2023-09-25 18:23:16  demogp  2023-09-25T16-20-06  /tmp/index_backup.tgz
06e2e343  2023-09-25 20:23:13  demogp  2023-09-25T18-20-05  /tmp/index_backup.tgz
1e8ee24a  2023-09-25 22:23:17  demogp  2023-09-25T20-20-06  /tmp/index_backup.tgz
0b172f84  2023-09-26 00:23:07  demogp  2023-09-25T22-20-05  /tmp/index_backup.tgz
ced57d8a  2023-09-26 02:23:14  demogp  2023-09-26T00-20-05  /tmp/index_backup.tgz
4d29e992  2023-09-26 04:23:19  demogp  2023-09-26T02-20-06  /tmp/index_backup.tgz
c5c9a721  2023-09-26 06:23:24  demogp  2023-09-26T04-20-07  /tmp/index_backup.tgz
c51711b6  2023-09-26 08:23:19  demogp  2023-09-26T06-20-07  /tmp/index_backup.tgz
e577b57f  2023-09-26 10:23:45  demogp  2023-09-26T08-20-05  /tmp/index_backup.tgz
f725f67a  2023-09-26 12:23:22  demogp  2023-09-26T10-20-05  /tmp/index_backup.tgz
da483ba2  2023-09-26 14:23:59  demogp  2023-09-26T12-20-07  /tmp/index_backup.tgz
c4a9d712  2023-09-26 16:23:33  demogp  2023-09-26T14-20-08  /tmp/index_backup.tgz
538b4e36  2023-09-26 18:23:23  demogp  2023-09-26T16-20-06  /tmp/index_backup.tgz
be7df5eb  2023-09-26 19:07:41  demogp  2023-09-26T17-04-21  /tmp/index_backup.tgz
e63a8e43  2023-09-26 20:23:26  demogp  2023-09-26T18-20-06  /tmp/index_backup.tgz
16ea9037  2023-09-27 00:23:23  demogp  2023-09-26T22-20-07  /tmp/index_backup.tgz
05776739  2023-09-27 02:23:21  demogp  2023-09-27T00-20-05  /tmp/index_backup.tgz
00bf1072  2023-09-27 04:23:20  demogp  2023-09-27T02-20-06  /tmp/index_backup.tgz
3b6eb749  2023-09-27 06:23:24  demogp  2023-09-27T04-20-05  /tmp/index_backup.tgz
4d9bac3e  2023-09-27 08:23:21  demogp  2023-09-27T06-20-06  /tmp/index_backup.tgz
56cf6afb  2023-09-27 10:23:24  demogp  2023-09-27T08-20-06  /tmp/index_backup.tgz
452e1c1c  2023-09-27 12:23:27  demogp  2023-09-27T10-20-06  /tmp/index_backup.tgz
fd3ea310  2023-09-27 14:23:33  demogp  2023-09-27T12-20-06  /tmp/index_backup.tgz
3b1fcd04  2023-09-27 16:23:34  demogp  2023-09-27T14-20-06  /tmp/index_backup.tgz
bdad4ec4  2023-09-27 18:23:27  demogp  2023-09-27T16-20-06  /tmp/index_backup.tgz
4507f808  2023-09-27 19:07:26  demogp  2023-09-27T17-04-06  /tmp/index_backup.tgz
d81f0ba8  2023-09-27 20:23:37  demogp  2023-09-27T18-20-06  /tmp/index_backup.tgz
18dba51a  2023-09-28 00:23:55  demogp  2023-09-27T22-20-06  /tmp/index_backup.tgz
bfd393b1  2023-09-28 02:23:55  demogp  2023-09-28T00-20-05  /tmp/index_backup.tgz
bbf44bfc  2023-09-28 04:24:28  demogp  2023-09-28T02-20-05  /tmp/index_backup.tgz
e5ee0fda  2023-09-28 06:24:00  demogp  2023-09-28T04-20-06  /tmp/index_backup.tgz
c5ffa71f  2023-09-28 08:23:52  demogp  2023-09-28T06-20-06  /tmp/index_backup.tgz
1b367f54  2023-09-28 10:23:46  demogp  2023-09-28T08-20-06  /tmp/index_backup.tgz
------------------------------------------------------------------------------------------
81 snapshots

keep 3 snapshots:
ID        Time                 Host                                   Tags                 Reasons         Paths
--------------------------------------------------------------------------------------------------------------------------
3796d7fd  2023-09-27 00:22:36  backup-demogp-28262780-wmtgq  2023-09-26T22-20-07  daily snapshot  /tmp/oracle.tgz
920f81e3  2023-09-28 00:23:10  backup-demogp-28264220-9v6cv  2023-09-27T22-20-06  daily snapshot  /tmp/oracle.tgz
0b89dcd8  2023-09-28 12:22:58  backup-demogp-28264940-9w9sm  2023-09-28T10-20-07  daily snapshot  /tmp/oracle.tgz
--------------------------------------------------------------------------------------------------------------------------
3 snapshots

remove 81 snapshots:
ID        Time                 Host                                                             Tags                 Paths
------------------------------------------------------------------------------------------------------------------------------------
...
57bfa5f2  2023-09-25 00:22:19  backup-demogp-28259900-8t9wz                            2023-09-24T22-20-06  /tmp/oracle.tgz
4ae83df2  2023-09-25 02:22:33  backup-demogp-28260020-fshrf                            2023-09-25T00-20-08  /tmp/oracle.tgz
9c14c016  2023-09-25 04:22:33  backup-demogp-28260140-h2l48                            2023-09-25T02-20-06  /tmp/oracle.tgz
2b3a9edf  2023-09-25 06:22:30  backup-demogp-28260260-lr6sj                            2023-09-25T04-20-06  /tmp/oracle.tgz
9b8bef93  2023-09-25 08:22:31  backup-demogp-28260380-vtdkn                            2023-09-25T06-20-05  /tmp/oracle.tgz
ede4412d  2023-09-25 10:22:29  backup-demogp-28260500-xdbrg                            2023-09-25T08-20-05  /tmp/oracle.tgz
1d4fb16f  2023-09-25 12:22:30  backup-demogp-28260620-ldmwm                            2023-09-25T10-20-05  /tmp/oracle.tgz
29a9d486  2023-09-25 14:22:31  backup-demogp-28260740-hvchn                            2023-09-25T12-20-06  /tmp/oracle.tgz
db00e3b2  2023-09-25 16:22:34  backup-demogp-28260860-fc7jr                            2023-09-25T14-20-06  /tmp/oracle.tgz
4ad061e9  2023-09-25 18:22:29  backup-demogp-28260980-fgrst                            2023-09-25T16-20-06  /tmp/oracle.tgz
59ebe5f6  2023-09-25 20:22:29  backup-demogp-28261100-pwbrm                            2023-09-25T18-20-05  /tmp/oracle.tgz
b35ba8af  2023-09-25 22:22:31  backup-demogp-28261220-hc5vh                            2023-09-25T20-20-06  /tmp/oracle.tgz
ab90d2a1  2023-09-26 00:22:22  backup-demogp-28261340-fhn8f                            2023-09-25T22-20-05  /tmp/oracle.tgz
e57b603c  2023-09-26 02:22:28  backup-demogp-28261460-kvklv                            2023-09-26T00-20-05  /tmp/oracle.tgz
6afae620  2023-09-26 04:22:33  backup-demogp-28261580-bk6tm                            2023-09-26T02-20-06  /tmp/oracle.tgz
f11c9dec  2023-09-26 06:22:35  backup-demogp-28261700-45m9x                            2023-09-26T04-20-07  /tmp/oracle.tgz
c33e7aa8  2023-09-26 08:22:32  backup-demogp-28261820-7nck5                            2023-09-26T06-20-07  /tmp/oracle.tgz
ba3fcddc  2023-09-26 10:22:57  backup-demogp-28261940-sfglx                            2023-09-26T08-20-05  /tmp/oracle.tgz
47b33fa3  2023-09-26 12:22:36  backup-demogp-28262060-5c57t                            2023-09-26T10-20-05  /tmp/oracle.tgz
19958301  2023-09-26 14:23:09  backup-demogp-28262180-722vx                            2023-09-26T12-20-07  /tmp/oracle.tgz
365ff1c3  2023-09-26 16:22:43  backup-demogp-28262300-xvc78                            2023-09-26T14-20-08  /tmp/oracle.tgz
6905e172  2023-09-26 18:22:35  backup-demogp-28262420-fldlh                            2023-09-26T16-20-06  /tmp/oracle.tgz
e2de6381  2023-09-26 19:06:53  backup-before-deployment-demogp-backuppod-202309261704  2023-09-26T17-04-21  /tmp/oracle.tgz
c0ab5eda  2023-09-26 20:22:40  backup-demogp-28262540-7mwxk                            2023-09-26T18-20-06  /tmp/oracle.tgz
6df968dd  2023-09-26 22:22:38  backup-demogp-28262660-8mvkl                            2023-09-26T20-20-06  /tmp/oracle.tgz
607ae862  2023-09-27 02:22:34  backup-demogp-28262900-qlrfn                            2023-09-27T00-20-05  /tmp/oracle.tgz
01420a93  2023-09-27 04:22:35  backup-demogp-28263020-fmk2w                            2023-09-27T02-20-06  /tmp/oracle.tgz
12e96cfd  2023-09-27 06:22:34  backup-demogp-28263140-85tp9                            2023-09-27T04-20-05  /tmp/oracle.tgz
2c0d3292  2023-09-27 08:22:33  backup-demogp-28263260-7vvcp                            2023-09-27T06-20-06  /tmp/oracle.tgz
88ea86bd  2023-09-27 10:22:34  backup-demogp-28263380-r4td6                            2023-09-27T08-20-06  /tmp/oracle.tgz
b6e9bd3f  2023-09-27 12:22:42  backup-demogp-28263500-5hjcj                            2023-09-27T10-20-06  /tmp/oracle.tgz
347e7664  2023-09-27 14:22:44  backup-demogp-28263620-2ncsl                            2023-09-27T12-20-06  /tmp/oracle.tgz
48003f03  2023-09-27 16:22:45  backup-demogp-28263740-jb6cx                            2023-09-27T14-20-06  /tmp/oracle.tgz
46e9d14e  2023-09-27 18:22:39  backup-demogp-28263860-ntff6                            2023-09-27T16-20-06  /tmp/oracle.tgz
8a126587  2023-09-27 19:06:40  backup-before-deployment-demogp-backuppod-202309271704  2023-09-27T17-04-06  /tmp/oracle.tgz
7279d0e9  2023-09-27 20:22:51  backup-demogp-28263980-gdx26                            2023-09-27T18-20-06  /tmp/oracle.tgz
72e45512  2023-09-27 22:22:58  backup-demogp-28264100-dmvjt                            2023-09-27T20-20-05  /tmp/oracle.tgz
7b1db60b  2023-09-28 02:23:12  backup-demogp-28264340-d4n82                            2023-09-28T00-20-05  /tmp/oracle.tgz
e56c7176  2023-09-28 04:23:21  backup-demogp-28264460-b6mtk                            2023-09-28T02-20-05  /tmp/oracle.tgz
a57d7c81  2023-09-28 06:23:19  backup-demogp-28264580-7jvt9                            2023-09-28T04-20-06  /tmp/oracle.tgz
d0ed6354  2023-09-28 08:23:07  backup-demogp-28264700-bwn4m                            2023-09-28T06-20-06  /tmp/oracle.tgz
6dbf82fa  2023-09-28 10:23:04  backup-demogp-28264820-56ptr                            2023-09-28T08-20-06  /tmp/oracle.tgz
------------------------------------------------------------------------------------------------------------------------------------
81 snapshots

keep 3 snapshots:
ID        Time                 Host             Tags                 Reasons         Paths
-----------------------------------------------------------------------------------------------------------------------------
3a012ec2  2023-09-26 22:23:11  demogp  2023-09-26T20-20-06  daily snapshot  /home/foo/instance/storage/blobstore
fa76bd90  2023-09-27 22:23:27  demogp  2023-09-27T20-20-05  daily snapshot  /home/foo/instance/storage/blobstore
7967fb0d  2023-09-28 12:23:29  demogp  2023-09-28T10-20-07  daily snapshot  /home/foo/instance/storage/blobstore
-----------------------------------------------------------------------------------------------------------------------------
3 snapshots

remove 81 snapshots:
ID        Time                 Host             Tags                 Paths
-------------------------------------------------------------------------------------------------------------
...
5550f822  2023-09-25 00:22:51  demogp  2023-09-24T22-20-06  /home/foo/instance/storage/blobstore
dd1fd0cd  2023-09-25 02:23:08  demogp  2023-09-25T00-20-08  /home/foo/instance/storage/blobstore
4bd66d43  2023-09-25 04:23:06  demogp  2023-09-25T02-20-06  /home/foo/instance/storage/blobstore
53038056  2023-09-25 06:23:03  demogp  2023-09-25T04-20-06  /home/foo/instance/storage/blobstore
365cf793  2023-09-25 08:23:03  demogp  2023-09-25T06-20-05  /home/foo/instance/storage/blobstore
af57d57d  2023-09-25 10:23:03  demogp  2023-09-25T08-20-05  /home/foo/instance/storage/blobstore
3726bf41  2023-09-25 12:23:03  demogp  2023-09-25T10-20-05  /home/foo/instance/storage/blobstore
4e292254  2023-09-25 14:23:02  demogp  2023-09-25T12-20-06  /home/foo/instance/storage/blobstore
47361299  2023-09-25 16:23:09  demogp  2023-09-25T14-20-06  /home/foo/instance/storage/blobstore
e795a1f4  2023-09-25 18:23:01  demogp  2023-09-25T16-20-06  /home/foo/instance/storage/blobstore
73c66095  2023-09-25 20:23:01  demogp  2023-09-25T18-20-05  /home/foo/instance/storage/blobstore
0f245cad  2023-09-25 22:23:03  demogp  2023-09-25T20-20-06  /home/foo/instance/storage/blobstore
fdf32ecd  2023-09-26 00:22:55  demogp  2023-09-25T22-20-05  /home/foo/instance/storage/blobstore
87b3e6f3  2023-09-26 02:22:59  demogp  2023-09-26T00-20-05  /home/foo/instance/storage/blobstore
45c2eebd  2023-09-26 04:23:06  demogp  2023-09-26T02-20-06  /home/foo/instance/storage/blobstore
69a24333  2023-09-26 06:23:10  demogp  2023-09-26T04-20-07  /home/foo/instance/storage/blobstore
2f207aad  2023-09-26 08:23:06  demogp  2023-09-26T06-20-07  /home/foo/instance/storage/blobstore
209a29cb  2023-09-26 10:23:30  demogp  2023-09-26T08-20-05  /home/foo/instance/storage/blobstore
b8f603b1  2023-09-26 12:23:08  demogp  2023-09-26T10-20-05  /home/foo/instance/storage/blobstore
da8934b3  2023-09-26 14:23:43  demogp  2023-09-26T12-20-07  /home/foo/instance/storage/blobstore
3c72925d  2023-09-26 16:23:17  demogp  2023-09-26T14-20-08  /home/foo/instance/storage/blobstore
5f2adc22  2023-09-26 18:23:08  demogp  2023-09-26T16-20-06  /home/foo/instance/storage/blobstore
1ccb8c41  2023-09-26 19:07:26  demogp  2023-09-26T17-04-21  /home/foo/instance/storage/blobstore
84cd8e36  2023-09-26 20:23:14  demogp  2023-09-26T18-20-06  /home/foo/instance/storage/blobstore
ad393555  2023-09-27 00:23:11  demogp  2023-09-26T22-20-07  /home/foo/instance/storage/blobstore
71ab8b3e  2023-09-27 02:23:07  demogp  2023-09-27T00-20-05  /home/foo/instance/storage/blobstore
60948979  2023-09-27 04:23:08  demogp  2023-09-27T02-20-06  /home/foo/instance/storage/blobstore
f76d98c4  2023-09-27 06:23:09  demogp  2023-09-27T04-20-05  /home/foo/instance/storage/blobstore
f8991582  2023-09-27 08:23:07  demogp  2023-09-27T06-20-06  /home/foo/instance/storage/blobstore
8b9084ef  2023-09-27 10:23:09  demogp  2023-09-27T08-20-06  /home/foo/instance/storage/blobstore
680a9ded  2023-09-27 12:23:15  demogp  2023-09-27T10-20-06  /home/foo/instance/storage/blobstore
de99c7bb  2023-09-27 14:23:19  demogp  2023-09-27T12-20-06  /home/foo/instance/storage/blobstore
87f2e806  2023-09-27 16:23:19  demogp  2023-09-27T14-20-06  /home/foo/instance/storage/blobstore
53dc52b5  2023-09-27 18:23:13  demogp  2023-09-27T16-20-06  /home/foo/instance/storage/blobstore
85caae21  2023-09-27 19:07:13  demogp  2023-09-27T17-04-06  /home/foo/instance/storage/blobstore
b56cb668  2023-09-27 20:23:25  demogp  2023-09-27T18-20-06  /home/foo/instance/storage/blobstore
dd47db11  2023-09-28 00:23:40  demogp  2023-09-27T22-20-06  /home/foo/instance/storage/blobstore
1828a3a9  2023-09-28 02:23:41  demogp  2023-09-28T00-20-05  /home/foo/instance/storage/blobstore
dbc90deb  2023-09-28 04:24:16  demogp  2023-09-28T02-20-05  /home/foo/instance/storage/blobstore
e59621da  2023-09-28 06:23:48  demogp  2023-09-28T04-20-06  /home/foo/instance/storage/blobstore
b3cdc6ca  2023-09-28 08:23:37  demogp  2023-09-28T06-20-06  /home/foo/instance/storage/blobstore
ada69dcc  2023-09-28 10:23:33  demogp  2023-09-28T08-20-06  /home/foo/instance/storage/blobstore
-------------------------------------------------------------------------------------------------------------
81 snapshots

Would have removed the following snapshots ...


```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS S3

Expected behavior
-----------------
After running `restic forgot`, the tags of the `/tmp/oracle.tgz` snapshots correspond with another retained snapshots (paths: `/tmp/index_backup.tgz`, `/home/foo/instance/storage/blobstore`), because those are the most recent ones. According to the [documentation](https://restic.readthedocs.io/en/stable/060_forget.html)

```txt
--keep-daily n for the last n days which have one or more snapshots, keep only the most recent one for each day
```

Actual behavior
---------------
The snapshots with IDs `6df968dd` and `72e45512` are forgotten.

Steps to reproduce the behavior
-------------------------------
One backup is formed of 3 different snapshots. All of them get the same tag (custom timestamp) and started one after another sequentially. The first snapshot (oracle) is created from a different host, compared to another two. The wrongly calculated snapshots also exist when keep-monthly and keep-weekly params are used.

Do you have any idea what may have caused this?
-----------------------------------------------
Not really

Do you have an idea how to solve the issue?
-------------------------------------------
Nope

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Makes me happy everyday!

**Comment by MichaelEischer** [comment] 2023-10-01 15:34
The behavior reminds me of https://github.com/restic/restic/issues/2233 . A day is determined based on the local timestamp stored in a snapshot. The output of `forget` / `snapshots` uses the timezone of the current system (https://github.com/restic/restic/issues/1306).

What is the output of `for i in 3a012ec2 fa76bd90 7967fb0d ; do restic cat snapshot $i | grep time ; done`?

**Comment by alsimfer** [comment] 2023-10-02 09:34
Hi,

Ok, just checked the referenced issue and this indeed would be a problem. The midday snapshot is already scrapped, therefore values from other two:

### blobstore

```bash
for i in 3a012ec2 fa76bd90 ; do restic -r s3:https://s3.amazonaws.com/... cat snapshot $i | grep time ; done                                                                                                                                                                                                                                  
  "time": "2023-09-26T22:23:11.350618562+02:00",
  "time": "2023-09-27T22:23:27.625776441+02:00",
```

### index

```bash
for i in c765fbee 7ac44035 ; do restic -r s3:https://s3.amazonaws.com/... cat snapshot $i | grep time ; done
  "time": "2023-09-26T22:23:24.628660628+02:00",
  "time": "2023-09-27T22:23:41.500862177+02:00",
```

### oracle

```bash
for i in 3796d7fd 920f81e3 0b89dcd8 ; do restic -r s3:https://s3.amazonaws.com/... cat snapshot $i | grep time ; done
  "time": "2023-09-26T22:22:36.668553968Z",
  "time": "2023-09-27T22:23:10.611516149Z",
```

> the +2 hour offset for oracle snapshots is not there
 
This is because the timezone on the host where the oracle snapshot was created is set up differently, compared to hosts where index and blobstore were triggered. Now that I know it, I can work around it. 
If the backups are triggered from Docker containers with different TZ settings, one would be able to overwrite it directly with `TZ=Europe/Berlin restic backup` (or whatever the TZ is) to mitigate the problem. Therefore the [solution](https://github.com/restic/restic/issues/2233#issuecomment-482785652)

> Make forget issue a warning it encounters snapshots that have a different day for local time and UTC 

would be enough for my case.

Tnx for the fast reply!

**Comment by MichaelEischer** [comment] 2023-10-02 17:56
@konidev20 I'm not sure what you intend to say.  `--time timestamp` is always interpreted as local time, not as UTC timestamp. That is, if you are in timezone UTC+2 (aka. CEST), `--time '2023-10-02 19:00:00'` will result in a snapshot with timestamp `"2023-10-02T19:00:00+02:00"`. `--keep-daily` then only uses the date from that timestamp (the time and timezone are ignored!).

**Comment by konidev20** [comment] 2023-10-02 18:12
Yeah, that's what I said too. 

> it will parse the time in the current location. For example, if you set UTC 0:00 and you're in UTC+2 it will parse the time as 2:00AM in your backup run.

> --keep-daily then only uses the date from that timestamp (the time and timezone are ignored!).

Got it.

**Comment by konidev20** [comment] 2023-10-02 18:15
Hey @MichaelEischer, 

Can we add documentation for `--time` timestamp is always interpreted as local time, not as UTC timestamp?

I wasn't clear about it's usage.

**Comment by MichaelEischer** [comment] 2023-10-02 21:29
I guess we can add a few words, but we should try to not complicate the documentation too much.

**Comment by alsimfer** [comment] 2023-10-04 08:30
Hi,

Ah, didn't know about the `--time` param, thanks for the hint. I guess you can use it to mitigate the problem of keeping bundled snapshots together during `restic forget`. But then, assuming the TZ was set up differently on the hosts, you will see strange timestamps with `restic snapshots` command, because the local time and timezone will be evaluated there again.

Therefore I think it is better to make sure the TZ is set correctly on all hosts. A warning about inconsistent TZ setup of grouped snapshots during restic forget would help with that. And the hint in documentation about ignoring local time/timezone infos during keep-daily/weekly/monthly in restic forget would also be helpful.

**Comment by konidev20** [comment] 2023-10-05 06:34
My perspective here is that, if you pass `--time` as UTC time for all your backups, what would happen is that your backups would have timestamps relative to UTC. 

Then probably in the `forget` command we provide the relative `--time` as UTC, and all timestamps would be parsed relative to the UTC time not the local time of the machine running forget. 

I don't know about the complexity of the solution. 

I guess setting TZ is the best for now.

**Comment by MichaelEischer** [comment] 2023-10-21 17:10
I'll treat this issue as a duplicate of #2233 and #1306. Feel free to reopen it if I've missed something.

**Closed by MichaelEischer** 2023-10-21 17:10 UTC
Labels: state: need feedback
