### ISSUE TITLE
restic --quiet is not quiet in 0.12.0 under microsoft windows

### ISSUE THREAD

**Issue by rseffner** [restic/restic#3299] opened 2021-02-23 13:23 UTC
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64

How did you run restic exactly?
-------------------------------
restic_0.12.0_windows_amd64.exe --repo c:\Users\rseffner\Desktop\restic-repo backup c:\Users\rseffner\Desktop\desktop_2017.11.08 --quiet

output is tons of:
"/c/Users/rseffner/Desktop/desktop_2017.11.08/kontakte/Lewold Verlag.msg
[0:27] 7.08%  1813 files 209.863 MiB, total 6612 files 2.893 GiB, 0 errors ETA 5:58
/c/Users/rseffner/Desktop/desktop_2017.11.08/kontakte/Lieske-Elektronik e K .msg
[0:27] 7.09%  1816 files 209.952 MiB, total 6612 files 2.893 GiB, 0 errors ETA 5:58
/c/Users/rseffner/Desktop/desktop_2017.11.08/kontakte/Lindackers - Future-X Software GmbH.msg
[0:27] 7.09%  1818 files 210.024 MiB, total 6612 files 2.893 GiB, 0 errors ETA 5:58"

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local storage

Expected behavior
-----------------
no output for batch running

Actual behavior
---------------
tons of progress output

- on an other system problems with "flushing" the cmd
"flush failed: write /dev/stdout: A device attached to the system is not functioning."

Steps to reproduce the behavior
-------------------------------
as shown

**Comment by hluup** [comment] 2021-02-25 12:40
Seem like the same issue as in this report - https://github.com/restic/restic/issues/3284 There's also a workaround suggested there, but that seems UNIX specific.
There's also a PR already commited to master, that seems to fix it - https://github.com/restic/restic/pull/3286

**Comment by MichaelEischer** [comment] 2021-02-27 12:41
`.\restic.exe backup --quiet restic.log | findstr '^'` seems to work for me. Basically any windows equivalent to the unix `cat -`  should work.

**Comment by MichaelEischer** [comment] 2021-02-27 14:55
Closing this as duplicate of #3284. The current master branch works for me. Prebuilt beta versions of restic are available at https://beta.restic.net/?sort=time&order=desc .

**Closed by MichaelEischer** 2021-02-27 14:55 UTC
