### ISSUE TITLE
Predictable backup output

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2810] opened 2020-06-27 08:39 UTC
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64

How did you run restic exactly?
-------------------------------

Run with Python

    env = { 'RESTIC_REPOSITORY': "s3:http://IP:9002/test", 'RESTIC_PASSWORD': '' }
    cmd = 'restic backup --json test'
    p = subprocess.run(cmd, env=env, stdout=subprocess.PIPE, encoding='UTF-8')
    for line in p.stdout.splitlines():
        line = json.loads(line)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio

Expected behavior
-----------------
Always output exactly one status message of type summary.

Actual behavior
---------------
Sometimes (about 1% of the runs), multiple or none summary messages are returned.

Steps to reproduce the behavior
-------------------------------
I just noticed this in my logs. I didn't find out the criteria when this happens exactly.

Do you have any idea what may have caused this?
-----------------------------------------------
Not really. Maybe some synchronization / multithreading problem?

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Apart from this issue, it runs smoothly so far!

**Comment by rawtaz** [comment] 2020-06-27 09:53
Please be more specific, please edit the post above to include the messages that are working and show which ones are missing when it is not working. Be sure to clarify if it's *all* output from restic that doesn't show at times, or if it's just parts of it. I'm inclined to think this has something to do with Python rather than restic.

**Comment by darkdragon-001** [comment] 2020-06-27 09:58
@rawtaz What do you want to know exactly? There is some number of json objects with `message_type: status`. I don't care about those. Then, I expect exactly one message with `message_type: summary` as the last line to be sent to `stdout`. Sometimes, there is no such message, sometimes there are two identical messages in the last two lines.

**Comment by rawtaz** [comment] 2020-06-27 10:11
Perhaps I'm misunderstanding something, but if with the way you are running things you are getting certain output 99% of the times and not the other 1% of the times, can't you just show us exactly which output you are getting and not getting?

**Comment by darkdragon-001** [comment] 2020-06-27 10:29
I didn't log the full output. When processing line by line, I skip the status messages and only add the other lines to a list. When a line can be parsed as json, it is stored as python object, otherwise as string.

When it's working, the output is a list with a single item containing a python object with `message_type: summary`. When it is not working, the list is either empty or two items with the summary object.

**Comment by darkdragon-001** [comment] 2020-06-27 10:43
I just noted, sometimes, there is even a status message after the summary :open_mouth:

**Comment by rawtaz** [comment] 2020-06-27 10:44
Please try to reproduce this problem without Python - i.e. with running restic directly.

**Comment by darkdragon-001** [comment] 2020-06-27 11:30
Since I have neither time nor knowledge to translate the Python program to bash, further don't have the space and money to run an additional backup job regularly, there is no possibility for me to run this without Python. I guess this bug will live on in the software until someone digs it out in a couple of years again.

**Comment by rawtaz** [comment] 2020-06-27 11:34
Well for whatever it's worth, the first step in isolating the issue is to determine if it happens without the Python involvement too, and the easiest way to do that is to run the restic commands manually. Since you are the only one that has access to the Python thing and the setup the problem occurs in, there's not much we can do without more debugging on your end. But sure, I understand you don't have the time etc for that now. I'm not entirely sure the problem is in restic though, it could just as well be in the Python code.

**Comment by darkdragon-001** [comment] 2020-06-27 11:55
This is the part where restic is called (additionally, it calculates excludes, mounts devices, parses output, writes log files):

```python
import json, subprocess
env = { 'RESTIC_REPOSITORY': "s3:http://IP:9002/test", 'RESTIC_PASSWORD': '' }
cmd = 'restic backup --json test'
p = subprocess.run(cmd, env=env, stdout=subprocess.PIPE, encoding='UTF-8')
out = []
for line in p.stdout.splitlines():
    line_json = json.loads(line)
    if line_json['message_type']=='status':
        continue
    out.append(line_json)
if len(out)==1:
    out = out[-1]
print(out['total_duration'])
```

I get an e-mail on exceptions. They are sent on the `print()` line: Sometimes `out` is `[]` (no summary message), sometimes it contains two status messages.

_NOTE I know that I can use `--quiet` to suppress status messages, but sometimes I need them, but still want to print a nice summary to the log file._

**Comment by rawtaz** [comment] 2020-06-27 12:09
Do you think you can modify the script to call restic in a way such that the output from restic is put into a log file (one for each run) besides the output also going to your script? That way we would investigate the complete output from restic when you're seeing the problem and compare it with a complete output from when the problem isn't showing.

**Comment by darkdragon-001** [comment] 2020-06-27 13:34
I modified the script. Let's wait a few days for the problem to appear again.

**Comment by darkdragon-001** [comment] 2020-06-29 08:28
I just hit the case where the summary message was sent twice.

The output is too long for Github comments (max 65536 characters). I uploaded it [here](https://pastebin.com/aUCXySLb) instead.

**Comment by PrplHaz4** [comment] 2020-06-29 14:49
I've been seeing these duplicate summary lines for a while as well - my bash script runs restic and sends the output of the json summary to a log.  I think this fairly recent PR was submitted to address the issue, but haven't had a chance to test, and I don't think it's in a release yet.

https://github.com/restic/restic/pull/2545

```json
{
  "message_type": "summary",
  "files_new": 0,
  "files_changed": 0,
  "files_unmodified": 49180,
  "dirs_new": 0,
  "dirs_changed": 2,
  "dirs_unmodified": 0,
  "data_blobs": 0,
  "tree_blobs": 3,
  "data_added": 1358,
  "total_files_processed": 49180,
  "total_bytes_processed": 121410184143,
  "total_duration": 120.464916853,
  "snapshot_id": "56ae882c"
}
{
  "message_type": "summary",
  "files_new": 0,
  "files_changed": 0,
  "files_unmodified": 49180,
  "dirs_new": 0,
  "dirs_changed": 2,
  "dirs_unmodified": 0,
  "data_blobs": 0,
  "tree_blobs": 3,
  "data_added": 1358,
  "total_files_processed": 49180,
  "total_bytes_processed": 121410184143,
  "total_duration": 120.464916853,
  "snapshot_id": "56ae882c"
}
```

**Comment by darkdragon-001** [comment] 2020-06-29 15:21
Thanks for your confirmation and link!

Further, I would expect the last status _before_ the summary.

**Comment by rawtaz** [comment] 2020-06-29 22:47
@PrplHaz4 Thanks for that!

@darkdragon-001 Can you try using the [latest master build](https://beta.restic.net/?sort=time&order=desc) for a while and see if the problem is solved with that?

**Comment by darkdragon-001** [comment] 2020-06-30 14:23
@rawtaz I replaced the binary with latest master build. Let's see what will happen :)

**Comment by MichaelEischer** [comment] 2020-07-24 16:54
@darkdragon-001 Any updates on this issue?

**Comment by darkdragon-001** [comment] 2020-07-24 19:35
With the binary from master a month ago, I couldn't notice any problems so far :smiley:

**Comment by MichaelEischer** [comment] 2020-07-25 10:37
So let's close this issue for now. If the error shows up again, just complain :-) .

**Closed by MichaelEischer** 2020-07-25 10:37 UTC
Labels: category: backup, misc: bug, state: need feedback

**Comment by darkdragon-001** [comment] 2020-07-25 19:22
Sure, looking forward to see this in a release!
